### ISSUE TITLE
Unable to connect to AWS S3 via proxy

### ISSUE THREAD

**Issue by Hzc492** [ByConity/ByConity#1007]
My server connects to the Internet through a proxy (http_proxy). When I want to read or write AWS S3 using the `CnchMergeTree` engine, the connection times out. 
```
Received exception from server (version 21.8.7):
Code: 499. DB::Exception: Received from localhost:18684. DB::Exception: Encounter exception when request s3, HTTP Code: -1, RemoteHost: , RequestID: , ExceptionName: , ErrorMessage: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Timeout: connect timed out: 52.219.92.26:443 (version 21.8.7.1), Extra: Could not list objects in bucket [my_bucket_XXX] with prefix byconity/382ab164-dfe2-4d40-a110-95f1ac47abfe/ SQLSTATE: HY000.
```
This is reasonable, byconity is not obligated to read my http_proxy environment variable by itself.

**Since I didn't find out how to set up proxy in the config file**, I modified part of the code myself to make the proxy work, containing:
1. Modify the default parameters of `ClientConfigurationPerRequest` (file `src/IO/S3/PocoHTTPClient.h` line 34) like
```
struct ClientConfigurationPerRequest
{
    Aws::Http::Scheme proxy_scheme = Aws::Http::Scheme::HTTP;
    String proxy_host = "localhost";
    unsigned proxy_port = 1234;
};
```
2. Modify the members of `Aws::Client::ClientConfiguration` in `S3Config::create()` (file `src/IO/S3Common.cpp`) like
```
client_cfg->proxyHost = "localhost";
client_cfg->proxyPort = 1234;
client_cfg->proxyScheme = Aws::Http::Scheme::HTTP;
```
3. Modify the members of `Aws::Client::ClientConfiguration` in `S3CredentialsProviderChain::S3CredentialsProviderChain()` (file `src/IO/S3/Credentials.cpp`) like
```
aws_client_configuration->proxyHost = "localhost";
aws_client_configuration->proxyPort = 1234;
aws_client_configuration->proxyScheme = Aws::Http::Scheme::HTTP;
```

After the modification, even though it **does** connect to AWS via proxy, the insert operation still fails.
```
Received exception from server (version 21.8.7):
Code: 499. DB::Exception: Received from localhost:18684. DB::Exception: Encounter exception when request s3, HTTP Code: 403, RemoteHost: , RequestID: [XXXXXXXXX], ExceptionName: SignatureDoesNotMatch, ErrorMessage: The request signature we calculated does not match the signature you provided. Check your key and signing method., Extra: Could not list objects in bucket [my_bucket_XXX] with prefix byconity/bbc155b5-c91c-4b0b-9cc9-43a13b17ed62/ SQLSTATE: HY000. 
```

**So, is there any idea to help me make it work? Will there be support for proxy in the future?**

=========
SQLs used for test:
```
create table cnch.test (x int, y int) engine=CnchMergeTree order by x settings storage_policy='cnch_default_s3';
insert into cnch.test values (1,2),(2,3),(3,4);
```

**Comment by Hzc492** [comment]
By the way, I also tried `Aws::Http::HttpClient` by setting `s3.use_crt_http_client=true`, `S3Util::listObjectsWithPrefix()` and `S3Util::read()` work well, but `S3Util::uploadPart()` timeout fails. No idea on the reason.

**Comment by dmthuc** [comment]
> http_proxy

Hi @Hzc492 , thank you for reporting the issue, may i know how did you deploy byconity? Did you deploy via k8s?

**Comment by Hzc492** [comment]
> > http_proxy
> 
> Hi @Hzc492 , thank you for reporting the issue, may i know how did you deploy byconity? Did you deploy via k8s?

I deployed directly on the host (without k8s). The configuration mainly refers to `docker/executable_wrapper/config/` 
 (DM+RM+TSO+service+1vw_default+1vw_write, with IPs all localhost). The configuration of the storage in `server.xml`, `worker-write.xml`, and `worker.xml` are
```
<storage_configuration>
    <disks>
        <default></default>
        <server_local_disk1>
            <path>[XXXX/XXX/XX]server_local_disk/data/0/</path>
        </server_local_disk1>
        <server_hdfs_disk0>
            <path>/user/clickhouse/</path>
            <type>bytehdfs</type>
        </server_hdfs_disk0>
        <server_s3_disk0>
            <type>bytes3</type>
            <region>us-east-2</region>
            <endpoint>https://s3.us-east-2.amazonaws.com</endpoint>
            <bucket>[my_bucker_XXX]</bucket>
            <path>byconity/</path>
            <ak_id>XXXXXX</ak_id>
            <ak_secret>XXXXXX</ak_secret>
        </server_s3_disk0>
    </disks>
    <policies>
        <default>
            <volumes>
                <local>
                    <default>default</default>
                    <disk>default</disk>
                    <disk>server_local_disk1</disk>
                </local>
            </volumes>
        </default>
        <cnch_default_hdfs>
            <volumes>
                <hdfs>
                    <default>server_hdfs_disk0</default>
                    <disk>server_hdfs_disk0</disk>
                </hdfs>
            </volumes>
        </cnch_default_hdfs>
        <cnch_default_s3>
            <volumes>
                <s3>
                    <default>server_s3_disk0</default>
                    <disk>server_s3_disk0</disk>
                </s3>
            </volumes>
        </cnch_default_s3>
    </policies>
</storage_configuration>
```

`INSERT` and `SELECT` on HDFS work well.

**Comment by Hzc492** [comment]
fixed myself. 
Strictly speaking, there's nothing wrong with byconity, it just doesn't provide users with a way to easily use proxy via configuration. The `SignatureDoesNotMatch` error when accessing AWS S3 is caused by `PocoHTTPClient`. In the case of http_proxy, Poco will append the port number to the target uri, which results in a mismatch of the previously computed signature.

For those must use http_proxy to access AWS, these two steps help:

1. Add these codes to `PocoHTTPClient::makeRequestInternal` function (file `src/IO/S3/PocoHTTPClient.cpp` line 204):
```
auto request_configuration = per_request_configuration(request);
// add the following lines
if (target_uri.getHost().ends_with("amazonaws.com")) {
    request_configuration.proxy_host = "XX.XX.XX.XX";
    request_configuration.proxy_port = 1234;
    request_configuration.proxy_scheme = Aws::Http::Scheme::HTTP;
}
```
2. Modify `HTTPClientSession::sendRequest` function (file `contrib/poco/Net/src/HTTPClientSession.cpp` line 248):
```
if (!_proxyConfig.host.empty() && !bypassProxy())
{
    // request.setURI(proxyRequestPrefix() + request.getURI());
    // replace the preceding line with the following:
    std::string proxy_request_prefix = proxyRequestPrefix();
    if (proxy_request_prefix.starts_with("https://") && proxy_request_prefix.ends_with("amazonaws.com:443")) 
        proxy_request_prefix = proxy_request_prefix.substr(0, proxy_request_prefix.size() - 4); // remove the ":443"
    request.setURI(proxy_request_prefix + request.getURI());
    proxyAuthenticate(request);
}
```
