### ISSUE TITLE
Installing tso error message

### ISSUE THREAD

**Issue by ThorManager** [ByConity/ByConity#1014]
When installing TSO, there are always errors and dependency issues. I don't know why this is happening，
![image](https://github.com/ByConity/ByConity/assets/96821352/1ff60997-aac4-4d8b-943f-58b632f67d56)
![image](https://github.com/ByConity/ByConity/assets/96821352/c5acd32c-a40e-4d4f-9f77-ff1aefa7e695)

**Comment by dmthuc** [comment]
Hi @ThorManager, it seems that you haven't install byconity-common-static package

**Comment by dmthuc** [comment]
Can you force install both package and retry?

**Comment by ThorManager** [comment]
I have the original package now, it's a bit strange now. Previously, cnch_ The config.xml configuration was incorrect and has been modified now, but the byty day manager still continues to connect to the previous incorrect configuration
![image](https://github.com/ByConity/ByConity/assets/96821352/394c0603-76a0-442e-ac21-9aa5c281979c)
cnch_config 
![image](https://github.com/ByConity/ByConity/assets/96821352/1de256ec-4b99-4eb2-889c-1208c7aa1e23)

**Comment by ThorManager** [comment]
![image](https://github.com/ByConity/ByConity/assets/96821352/a71a4544-44b2-467f-b62f-9a97c1781615)
There's a server that can't even get up or down, I don't know why

**Comment by ThorManager** [comment]
If I have multiple tsos, how should I configure them with server nodes?

**Comment by dmthuc** [comment]
> ![image](https://private-user-images.githubusercontent.com/96821352/294151971-a71a4544-44b2-467f-b62f-9a97c1781615.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNjgzNDQsIm5iZiI6MTcwNDM2ODA0NCwicGF0aCI6Ii85NjgyMTM1Mi8yOTQxNTE5NzEtYTcxYTQ1NDQtNDRiMi00NjdmLWI2MmYtOWE5N2MxNzgxNjE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDExMzQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0NWMwZmQxODI2MzkwNWVmOGUwMjMzODBjMDY3OTEwOWY0ZGQzOWRlZWJiMzMxMTg4NTNmNDg1Yjg2NmRmZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.syybpfMrMqKw1T24etUJDhbHX93n6IW88Vmq_s_5zwo) There's a server that can't even get up or down, I don't know why

This log is not enough

**Comment by ThorManager** [comment]
err log 
![image](https://github.com/ByConity/ByConity/assets/96821352/b7474cb3-1903-4ea3-a9da-4d687e0ddbed)
journalctl  -f -u byconity-server.service
![image](https://github.com/ByConity/ByConity/assets/96821352/d517c885-89e1-4ee1-8a37-b6d63c609050)
And there's also this question
![image](https://github.com/ByConity/ByConity/assets/96821352/22ca7a4a-811e-496b-97be-8dcd1c757fbc)

**Comment by dmthuc** [comment]
> If I have multiple tsos, how should I configure them with server nodes?

You don't need to do anything. The server will automatically find the TSO leader to connect

**Comment by ThorManager** [comment]
So, are the configurations in cnch config written casually? What is the question about the master?

**Comment by dmthuc** [comment]
> err log ，journalctl -f -u byconity-server.service ![image](https://private-user-images.githubusercontent.com/96821352/294168798-b7474cb3-1903-4ea3-a9da-4d687e0ddbed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNjkwMjksIm5iZiI6MTcwNDM2ODcyOSwicGF0aCI6Ii85NjgyMTM1Mi8yOTQxNjg3OTgtYjc0NzRjYjMtMTkwMy00ZWEzLWE5ZGEtNGQ2ODdlMGRkYmVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDExNDUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0OTYzZjNmYTVlODkwYjQxODgyZDYyN2JiYTM1N2RmYTBkNjA1ZjAzYWI3YzJhNWFmZWU3NDg4YTE3ZTY2YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8-7UrymicuG1-ZuOzTpMd_h_NQ-tDGEHIJQfyFm1Dzk) ![image](https://private-user-images.githubusercontent.com/96821352/294169021-d517c885-89e1-4ee1-8a37-b6d63c609050.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNjkwMjksIm5iZiI6MTcwNDM2ODcyOSwicGF0aCI6Ii85NjgyMTM1Mi8yOTQxNjkwMjEtZDUxN2M4ODUtODllMS00ZWUxLThhMzctYjZkNjNjNjA5MDUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDExNDUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzODdmODFiNDcwMDNiNWU4MTNhZDA2NGUxOTI2Y2I3NjRhMDk0YjhhMzU0M2Q2YzJlZjg0NDJjY2YyZTczMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J4Ez1isVUSDGFWxLu5PsCw6IxD3D9oJKORD80_-YTk0)
> 
> And there's also this question ![image](https://private-user-images.githubusercontent.com/96821352/294168831-22ca7a4a-811e-496b-97be-8dcd1c757fbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNjkwMjksIm5iZiI6MTcwNDM2ODcyOSwicGF0aCI6Ii85NjgyMTM1Mi8yOTQxNjg4MzEtMjJjYTdhNGEtODExZS00OTZiLTk3YmUtOGRjZDFjNzU3ZmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDExNDUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4OTk1YTE2ZjZkYzUzNDE5OGI5ZDRhOWU5NDYwOTEyMzI4MTk2NjM0NWQ0Njg5OTE2NDRiYzc5OTcxNzEzODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wz462krn3gMFp5GHeW1FoAxHvwIgX-4IXXA6_btWAE8)

No, I mean the log file in here 
![image](https://github.com/ByConity/ByConity/assets/13962605/0bc50454-cac7-4fa8-b888-81fa60a4ec30)

**Comment by ThorManager** [comment]
Why does daemon-manager keep linking to this strange thing

![image](https://github.com/ByConity/ByConity/assets/96821352/f77d984e-0523-4d7f-aaf6-6cdafb725954)

**Comment by dmthuc** [comment]
btw, you can add my we chat so that we can support easier. My wechat id is `wxid_l50i43mb6vwo12`

**Comment by dmthuc** [comment]
> Why does daemon-manager keep linking to this strange thing
> 
> ![image](https://private-user-images.githubusercontent.com/96821352/294170362-f77d984e-0523-4d7f-aaf6-6cdafb725954.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNjkyMjUsIm5iZiI6MTcwNDM2ODkyNSwicGF0aCI6Ii85NjgyMTM1Mi8yOTQxNzAzNjItZjc3ZDk4NGUtMDUyMy00ZDdmLWFhZjYtNmNkYWZiNzI1OTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDExNDg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2MmExNmJhOWUzMDE3OGYzYmJmMDlkOGQwNThlYzgzZWVlMjAzZjE2OTcxMDVlMzllYmYzMmI4MmY5ZmEyZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ldUkytelYug-Za3-D30Te9UKCIui1SW6uaben-dS4Po)

That is the wrong address, you can see the two ip is separated by a comma. The correct address should be `ip:port`

**Comment by ThorManager** [comment]
I couldn't find you, why don't you add me `Sunflower_01011`
Thank you for your urgent request, Momoda
