### ISSUE TITLE
Create statement execution error

### ISSUE THREAD

**Issue by ThorManager** [ByConity/ByConity#1023]
First of all, may I ask which port number is being connected to? The 9010 port number I linked to write reported an error, while the connection to worker9010 was fine, but the execution error occurred
![image](https://github.com/ByConity/ByConity/assets/96821352/4d3a8f43-77b7-4aae-9486-80660b9985d4)
![image](https://github.com/ByConity/ByConity/assets/96821352/da7a7ccd-9e79-44d7-8403-57589177f32b)

**Comment by dmthuc** [comment]
Hi @ThorManager , the client should only connect to servers.

**Comment by ThorManager** [comment]
![image](https://github.com/ByConity/ByConity/assets/96821352/421ef1a7-3eaf-46ea-840a-ec75251c1aa7)
One server keeps reporting errors

**Comment by dmthuc** [comment]
> ![image](https://private-user-images.githubusercontent.com/96821352/294432802-421ef1a7-3eaf-46ea-840a-ec75251c1aa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2ODA5NTAsIm5iZiI6MTcwNDY4MDY1MCwicGF0aCI6Ii85NjgyMTM1Mi8yOTQ0MzI4MDItNDIxZWYxYTctM2VhZi00NmVhLTg0MGEtZWM3NTI1MWMxYWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDAyMjQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNDBiOWZmOTY2YmFmYTAxYzliODM0YzYwM2U3NzQyZTBhZmVhNWViNjViMjk4NjYxNWE2NDhhOTE5YjU3NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LC83DF-la7KzIT6EvWbE9bczPvZBEGwh1UTn6aGd0HU) One server keeps reporting errors


This is issue has been solved via WeChat. This issue due to ipv6 is not enabled in some machine. The solution is to define environment variable `MY_HOST_IP` with the IPv4 value of the machine (for example, MY_HOST_IP='127.0.0.1') in all the machine. This can be done in many way like defining in `/etc/profile`.
