### ISSUE TITLE
merge task being retried indefinitely

### ISSUE THREAD

**Issue by dogauzuncukoglu** [ByConity/ByConity#1045]
## Bug Report
Merge task fails to complete due to 404 response from s3. Here is the exception logged by write worker.
```
2024.01.11 13:29:57.263550 [ 357 ] {} <Error> executeManipulationTask: Failed to execute ManipulationTask {446950223951429682}, type Merge, ed_mt_v1.`ed_metric_2d6be233-f7bb-4fe1-90a5-28a95c86ec9c` (37908a4f-d72e-4221-aa1e-972fd9854aad):  source_parts: { 20240111_446943989621063692_446943989621063692_0_446943989503098945, 20240111_446944005218369554_446944005218369554_0_446944005139726375, 20240111_446944025483149469_446944025483149469_0_446944023498457152, 20240111_446944036770021421_446944036770021421_0_446944036691116063, 20240111_446944052581761035_446944052581761035_0_446944052463796277 } new_part_names: { 20240111_446943989621063692_446944052581761035_1_446950223951429682 } columns_commit_time: 446925916979593252: Code: 499, e.displayText() = DB::S3::S3Exception: Encounter exception when request s3, HTTP Code: 404, RemoteHost: , RequestID: , ExceptionName: , ErrorMessage: No response body., Extra:  SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):
0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1f837c12 in /opt/byconity/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xdbc33a0 in /opt/byconity/bin/clickhouse
2. DB::S3::S3Exception::S3Exception(Aws::S3::S3Error const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xdd53910 in /opt/byconity/bin/clickhouse
3. DB::S3::S3Util::headObject(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0xdd5a33a in /opt/byconity/bin/clickhouse
4. DB::S3::S3Util::getObjectSize(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0xdd59d83 in /opt/byconity/bin/clickhouse
5. DB::DiskByteS3::getFileSize(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x194123de in /opt/byconity/bin/clickhouse
6. DB::MergeTreeDataPartCNCH::loadPartDataFooter() const @ 0x1a634508 in /opt/byconity/bin/clickhouse
7. DB::MergeTreeDataPartCNCH::loadChecksumsForPart(bool) @ 0x1a6305df in /opt/byconity/bin/clickhouse
8. DB::MergeTreeDataPartCNCH::loadChecksums(bool) @ 0x1a63684e in /opt/byconity/bin/clickhouse
9. DB::IMergeTreeDataPart::getChecksums() const @ 0x1a54fe6a in /opt/byconity/bin/clickhouse
10. DB::MergeTreeDataPartCNCH::loadColumnsChecksumsIndexes(bool, bool) @ 0x1a62ed70 in /opt/byconity/bin/clickhouse
11. void std::__1::__function::__policy_invoker<void (std::__1::shared_ptr<DB::IMergeTreeDataPart>&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::MergeTreeCloudData::loadDataPartsInParallel(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart> > >&)::$_0, void (std::__1::shared_ptr<DB::IMergeTreeDataPart>&)> >(std::__1::__function::__policy_storage const*, std::__1::shared_ptr<DB::IMergeTreeDataPart>&) @ 0x1a5a701a in /opt/byconity/bin/clickhouse
12. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xdc06b9e in /opt/byconity/bin/clickhouse
13. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0xdc089e8 in /opt/byconity/bin/clickhouse
14. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xdc0377f in /opt/byconity/bin/clickhouse
15. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0xdc07a5a in /opt/byconity/bin/clickhouse
16. start_thread @ 0x7ea7 in /lib/x86_64-linux-gnu/libpthread-2.31.so
17. clone @ 0xfca2f in /lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.8.7.1)
```
### Briefly describe the bug
We realized a merge task being rescheduled continuously. We observed the merge task fails with the above message. 
### The result you expected
If the error is an unrecoverable error like expected files somehow not being present in the storage, server should not retry the merge indefinitely. 

### How to Reproduce
Not sure about the root cause but maybe deleting some underlying files from s3 manually might put the server in this stuck merge state. 

### Version
We built from the source code: 39d7858f351be516ebccceb59be129c45d4abe98

**Comment by Alima777** [comment]
@dogauzuncukoglu 
Hi, are the writes and queries all working well, only the merge task fails?

**Comment by dogauzuncukoglu** [comment]
Hi, @Alima777 

Yes everything works well if stuck merge task count is not large. We observed at some point there was ~90 merge tasks that were failing for a table. If it gets to that amount it blocks other merge tasks from being run so performance starts to degrade. It can be resolved by increasing the worker count.

We have truncated the problematic table to fix the issue.

**Comment by Alima777** [comment]
Hi, @dogauzuncukoglu 
> We have truncated the problematic table to fix the issue.

Is only one table wrong?  It seems the meta data of this table somehow not consistent with the acutal data.

**Comment by dogauzuncukoglu** [comment]
Yes. This might be due to some misconfiguration on our side. The table in question had was a target table for a materialized view and we were dropping and recreating mat views very frequently at the time we observed the issue.

I am not sure about the root cause. I would like to ask whether it is possible to prevent task failures in this case?

For example would it make sense to try something like this. Assuming the stuck merge task is running for an older partition?

* stop merges for the table
* set `cnch_merge_only_realtime_partition` to true
* start merges for the table

**Comment by zeromem** [comment]
Hi @dogauzuncukoglu , from your description, seems there are some consistency issue between part meta (in fdb) and part files (in S3). To find the root cause, we need more informations like
* the merge log on worker side, shows which parts are selected to the merge task.
* the system.server_part_log, to check the operation records of those problematic parts.
* and check the operation records of the part files on S3 side. (like when the part file is deleted).

And about the workaround like what you suggested, we have no such strategies for now. 
If there are only a small number of partitions encounter this issue, maybe you can:
* export the data to a tmp table. INSERT INTO tmp SELECT * FROM table WHERE _partition_expression_ ;
* drop the problematic partitions. ALTER TABLE table DROP PARTITION ... ;
* reimport the data from tmp. INSERT INTO table SELECT * FROM tmp;

**Comment by kevinthfang** [comment]
Hi @dogauzuncukoglu , would you please provide the information zeromem listed?
