### ISSUE TITLE
 A large amount of concurrency may cause the database to be unable to be found.

### ISSUE THREAD

**Issue by ThorManager** [ByConity/ByConity#1050]
When using jmeter for stress testing, it was found that the library could not be found. There were not many jmeter threads opened. 1000 threads were cycled 10 times.

The following are logs and error screenshots of the environment at that time

worker log
![b0c230c66ab0557eed33c88fcf2b8a5](https://github.com/ByConity/ByConity/assets/96821352/b8660d3b-9a0e-401f-97db-db1a47a58c8b)

jmeter error
![8ef09b11516e0faaede41839fa270e2](https://github.com/ByConity/ByConity/assets/96821352/7b7aa929-ea4a-4084-9778-3a6202b7f3b6)

select * from system.settings where name ='prefer_cnch_catalog'
![1c9ed7e6cb1b36badc36d23e74ec9e6](https://github.com/ByConity/ByConity/assets/96821352/a38a04cb-2e18-4465-8a79-82b8e7bc874b)

select host(), * from cnch(vw_default, system.settings) where name ='prefer_cnch_catalog'
![fe9e43c4e072bf5dcaa4963603c3b7a](https://github.com/ByConity/ByConity/assets/96821352/0cc3fece-89c9-4140-8944-6a4d23fa6268)

[11.txt](https://github.com/ByConity/ByConity/files/13917519/11.txt)

**Comment by wordhardqi** [comment]
@ThorManager I think this is releated to SessionResource and TSO. could u check the log of TSO to see whether there is any error log and paste here.

**Comment by yuanzhubi** [comment]
It was already confirmed not related to TSO. We still try to find the root cause and fix it.

**Comment by kevinthfang** [comment]
duplicated with #1052
