### ISSUE TITLE
insert cost long time (s3 as backend storage)

### ISSUE THREAD

**Issue by blueskygzhz** [ByConity/ByConity#1067]
![企业微信截图_17055467787791](https://github.com/ByConity/ByConity/assets/147569085/6ece3e44-5f02-4fac-a097-62806de09643)

byconity s3 use list interface to implement exists logic

list is a heavy interface, this will lead to byconity insert overtime

**Comment by skyoct** [comment]
https://github.com/ByConity/ByConity/blob/0ea1689d0d2ba1bb26a7b4f37fc7d563b465197a/src/Disks/DiskByteS3.cpp#L158-L164
According to the comments on the method, "exists" may be used to determine if a prefix or object exists.

Currently, the file structure of S3 should be in the format of root_path/xxxx/data, where xxx is variable. Can we directly use regular expressions to determine if it meets the above rule, and if so, use "getObject" to check its existence?
