### ISSUE TITLE
PartFileDiskCacheSegment  marks_loader missing diskcache argument, this will lead to low performance

### ISSUE THREAD

**Issue by blueskygzhz** [ByConity/ByConity#1086]
https://github.com/ByConity/ByConity/blob/05347a7a580182da01917383bec113e7d9f4f883/src/Storages/DiskCache/PartFileDiskCacheSegment.cpp#L74-L84

**Comment by foreverneverer** [comment]
This only affects the additional bandwidth for reading remote data when caching data, and in the current scenario, the impact of mark data is minimal. 

I will support it later.

**Comment by smmsmm1988** [comment]
this issue has been resolved
