### ISSUE TITLE
bug in memorytracker memory usage statistics, much higher than actual use

### ISSUE THREAD

**Issue by blueskygzhz** [ByConity/ByConity#1116]
top show use only 6GB, but memorytracker show 18GB

![RB56I5J9Ru](https://github.com/ByConity/ByConity/assets/147569085/39301c5f-9cc5-4342-af99-3fa93af66c22)
![STRwtlHFhj](https://github.com/ByConity/ByConity/assets/147569085/fa770aac-149a-466b-a5fc-86331f3bf471)

**Comment by luffyhwl** [comment]
The memory recorded by the memory tracker should be accurate. The reason for the memory mismatch here may be that the log records the memory peak value, while the monitoring has a sampling period that smooths the peak value, resulting in a smaller value in the monitoring than in the log.
