### ISSUE TITLE
diskcache don't support bandwidth rate limiter, this will block user request

### ISSUE THREAD

**Issue by blueskygzhz** [ByConity/ByConity#1129]
![img_v3_027k_0ed03cc1-71e5-4935-8d68-72654b391cfg](https://github.com/ByConity/ByConity/assets/147569085/617373b8-6c9f-49df-80e9-d98f7350924d)

**Comment by foreverneverer** [comment]
Great, I will support it!

**Comment by smmsmm1988** [comment]
this issue has been resolved
