### ISSUE TITLE
Support using the remote function to query ClickHouse

### ISSUE THREAD

**Issue by skyoct** [ByConity/ByConity#1217]
### Describe the feature you'd like
In some scenarios, it is necessary to use both ByConity and ClickHouse. Currently, ClickHouse can use remote queries to access ByConity, but ByConity cannot query ClickHouse.

**Comment by kevinthfang** [comment]
Is there any exception thrown when you are using remote function in ByConity?

**Comment by skyoct** [comment]
Query:
```
select count(*)
from remote('xxxxxxxx', 'db', 'table', 'user', 'password')
where ck_date = today() - 1;
```
Error:
```
Code: 32, e.displayText() = DB::Exception: Attempt to read after eof: while receiving packet from xxxx:9090 SQLSTATE: 22000 (version 21.8.7.1)
```

The same query can be executed in ClickHouse.



ClickHouse Version: 21.8.15.7


> Is there any exception thrown when you are using remote function in ByConity?

**Comment by dmthuc** [comment]
Hi @skyoct , the feature has just been merged.

**Comment by dmthuc** [comment]
Even those the feature is working now but it is lacked of CI test for it. I will close the ticket when the CI test is merged
