### ISSUE TITLE
Specify vw_read when executing SQL

### ISSUE THREAD

**Issue by skyoct** [ByConity/ByConity#1222]
### Describe the feature you'd like
![image](https://github.com/ByConity/ByConity/assets/24541857/37914bc3-29e2-48f4-9f3e-2f414bcba5d6)

**Comment by kevinthfang** [comment]
In DQL please use 'virtual_warehouse' to specify vw. BTW, in DDL please use cnch_vw_default for read worker and cnch_vw_write for write worker.
