### ISSUE TITLE
 With the use of #1068, the list qps remains high.

### ISSUE THREAD

**Issue by skyoct** [ByConity/ByConity#1243]
### Briefly describe the bug
The file path stored in S3 is fixed and there will not be a situation where multiple files exist in one directory. Can we avoid using listObject? List request have a significant impact on the performance of s3.

![image](https://github.com/ByConity/ByConity/assets/24541857/963a7408-4ffc-4fc0-9fe6-c6cfeddfa8c6)

### Version
latest code

**Comment by skyoct** [comment]
I think we can modify the logic in DiskByteS3.
1. removeDirectory does not need to listObjects, just return directly.
2. removeRecursive directly deletes path / 'data'.
3. In exists, first check if the path ends with data, if not, add data, then use head to check if it exists.

**Comment by smmsmm1988** [comment]
hi, @skyoct. It is necessary to avoid using listObject for S3-specific storage policies, but it is still dangerous to directly modify logic of general interfaces of IDisk. A better way is to provide new interfaces such as removePart, partExists, and to call these interfaces from upper-level if we are operating parts stored in S3

**Comment by skyoct** [comment]
@smmsmm1988 Hi, would it be better if the upper layer can be modified, but would this cause a huge workload? For example, every time a relevant operation is performed, it is necessary to first determine whether it is HDFS or S3, and then perform the corresponding operation.

**Comment by smmsmm1988** [comment]
> @smmsmm1988 Hi, would it be better if the upper layer can be modified, but would this cause a huge workload? For example, every time a relevant operation is performed, it is necessary to first determine whether it is HDFS or S3, and then perform the corresponding operation.

@skyoct Compared to the workload of listObject, the workload of determining HDFS/S3 + head, I think, is acceptable. Besides, for interfaces like partExists, the upper layer can call them no matter what the storage is.

**Comment by skyoct** [comment]
@smmsmm1988 Okay, may I ask if there is an expected completion time for this modification?

**Comment by smmsmm1988** [comment]
> @smmsmm1988 Okay, may I ask if there is an expected completion time for this modification?

@skyoct The optimization is now under design. 2~3 weeks may be enough.

**Comment by smmsmm1988** [comment]
this issue has been resolved
