### ISSUE TITLE
File import supports wildcard * matching

### ISSUE THREAD

**Issue by bright-zy** [ByConity/ByConity#1247]
## Enhancement
File import supports wildcard * matching，such as
~~~ 
INSERT INTO olap.olap_test_di_cube_v1 (
site_code,
business_code,
dp_code,
is_riskctrl,
battle_region_code,
province_region_code,
city_code,
date,
uv_count_distinct,
pv_sum
) FORMAT Parquet
INFILE 'hdfs://nxx-xxx/home/bigdata/hdfs2byconity/temp/measure_olap_olap_test_di_cube_v1_1708668744103/part*'

**Comment by yuanzhubi** [comment]
Now it supports "hdfs://part-{00000..00001}" pattern, is it ok?

**Comment by bright-zy** [comment]
> Now it supports "hdfs://part-{00000..00001}" pattern, is it ok?
Some suffixes are irregular, I hope '*' can be implemented.

**Comment by yuanzhubi** [comment]
> > Now it supports "hdfs://part-{00000..00001}" pattern, is it ok?
> > Some suffixes are irregular, I hope '*' can be implemented.

@smmsmm1988 Could you give some suggestions for it? I think it may leads uncontrolled time cost~
