### ISSUE TITLE
File import supports field conversion using functions

### ISSUE THREAD

**Issue by bright-zy** [ByConity/ByConity#1248]
### Describe the feature you'd like
File import supports field conversion using functions, such as uv_count_distinct -> bitmapBuild(uv_count_distinct) as uv_count_distinct
```
INSERT INTO test.olap_test_di_cube_v1 (
site_code,
business_code,
dp_code,
is_riskctrl,
battle_region_code,
province_region_code,
city_code,
date,
uv_count_distinct,
pv_sum
) 
FORMAT Parquet
SELECT 
site_code,
business_code,
dp_code,
is_riskctrl,
battle_region_code,
province_region_code,
city_code,
date,
bitmapBuild(uv_count_distinct) AS uv_count_distinct,
pv_sum
INFILE 'hdfs://nxx-xxx/home/work//hive2byconity/measure_olap_olap_test_di_cube_v1_1708668744103/part*'

**Comment by yuanzhubi** [comment]
@smmsmm1988 How do you think about it? Is this requirement ok to implement?

**Comment by fantasy12345zsq** [comment]
currently, we have External engine，like CnchHDFS，in this case
step1：create a CnchHDFS engine，
step2：just use insert select
![image](https://github.com/ByConity/ByConity/assets/46912832/4026f920-7d80-4076-9645-cf1913642cb3)
