### ISSUE TITLE
It would be better to set a default reviewer for PR

### ISSUE THREAD

**Issue by michelle-0808** [ByConity/ByConity#1279]
No default PR reviewer would be an obstacle for an individual developer to merge a PR into ByConity. 
It is suggested to set a default reviewer so that the PR from an individual developer can be noticed and handled in time.

**Comment by dmthuc** [comment]
Yeah, let me think how to do it

**Comment by dmthuc** [comment]
Hi @michelle-0808 I think the assignment suggestion from github should work well. When you create the PR, click on the Assignees, you should see the suggestion.

**Comment by michelle-0808** [comment]
OK, got it.
