### ISSUE TITLE
ClickHouse client 一直停留在Connectting 状态

### ISSUE THREAD

**Issue by merseyalma** [ByConity/ByConity#1293]
安装的是byconity/byconity:0.3.2镜像

容器状态

![image](https://github.com/ByConity/ByConity/assets/10740987/1d6eb0c8-881b-4c2e-87df-3156e56b0e30)

## Question

- 1

使用 ClickHouse client 22.2.2.1，一直停留在如下图状态
![image](https://github.com/ByConity/ByConity/assets/10740987/05429257-9484-4b54-a68a-dc67bcd66d5b)

- 2

按照 https://byconity.github.io/zh-cn/docs/quick-start/docker-deploy 的链接测试章节，都不成功

![image](https://github.com/ByConity/ByConity/assets/10740987/011d84a2-d734-45f4-b72a-8cbb61661c4c)

![image](https://github.com/ByConity/ByConity/assets/10740987/3c0409cb-814f-4ecb-a87a-00bd295bb737)

![image](https://github.com/ByConity/ByConity/assets/10740987/9c84f24b-0e8c-4920-b431-ff52b42b23b0)

**Comment by dmthuc** [comment]
Hi @merseyalma , thank you for report the issue, the document has been outdated. Let we fix that

**Comment by dmthuc** [comment]
Hi @merseyalma, the correct command to connect to server would be `docker exec -it server_container_id clickhouse client --port 52145`, for example: `docker exec -it 13ae6c15ba2c clickhouse client --port 52145`. So you need to find server_container_id by looking at `docker ps` output. We will find a better way to automate this

**Comment by merseyalma** [comment]
@dmthuc how to import csv file into byconity?
