### ISSUE TITLE
Column ingestion query in 0.3

### ISSUE THREAD

**Issue by bigpieface-so-big** [ByConity/ByConity#1296]
(you don't have to strictly follow this form)

## Question
Is the Column ingestion query capability deprecated in version 0.3?No introduction found in the documentation

**Comment by dmthuc** [comment]
Hi @bigpieface-so-big , you mean the feature ingest a few column from one table to another table? No it is not deprecated.

**Comment by dmthuc** [comment]
I've uploaded the document here https://byconity.github.io/docs/data-import/Ad-hocs/ingest_column
