### ISSUE TITLE
The data merge error, after deploying the byconity cluster

### ISSUE THREAD

**Issue by juppylm** [ByConity/ByConity#130]
I deployed a byconity cluster using docker, 3 work-default nodes for query, and 1 work-write node for data writing.
The data storage is normal, and 3.5 billion data has been entered, but I found that the data is not merged. I manually executed on the server node: ```optimize table xxx.yyy ```and found an error, the information is: 
```DB::Exception: No available service for data.cnch.vm.```
I suspect that there is a problem with the configuration of my cnch-config.yml file. I did not find this configuration item in this file, but I refer to the file configured under the byconity-docker project. Here I need to configure it in this file vm information? I configured resource_manager in this file, why should I configure vm?

**Comment by dmthuc** [comment]
Hi @juppylm , in ByConity we have a thread that always up to merge data so the use of `optimize` query is not necessary. I wonder if you deployment include Daemon-manager?
BTW, we have system table `system.bg_threads` with the meaning of the field like below
```
type: type of background thread: PartGCThread, MergeSelectThread, MemoryBufferManager ...
status: status of thread Running...
startup_time: startup time of thread
num_wakeup: the number of times the thread wakes up (run() method is called) 
```
You can select into this system table to check if merge thread is running

**Comment by juppylm** [comment]
> Hi @juppylm , in ByConity we have a thread that always up to merge data so the use of `optimize` query is not necessary. I wonder if you deployment include Daemon-manager? BTW, we have system table `system.bg_threads` with the meaning of the field like below
> 
> ```
> type: type of background thread: PartGCThread, MergeSelectThread, MemoryBufferManager ...
> status: status of thread Running...
> startup_time: startup time of thread
> num_wakeup: the number of times the thread wakes up (run() method is called) 
> ```
> 
> You can select into this system table to check if merge thread is running with query
> 
> ```
> select * from system.bg_threads where database = 'database' and table = 'table' to see if merge thread is running
> ```

@dmthuc The byconity cluster I deployed contains Daemon-manager. I looked at the stack information and the corresponding source code, and I found that it is indeed there to get the **cnch.vm** information from the cnch-config.yml file. The relevant code information is as follows:
```java
// CnchMergeMutateThread.cpp  
//  line 404 to line 409
        {
            std::lock_guard lock(worker_pool_mutex);
            vw_name = storage.getSettings()->cnch_vw_write;
            /// TODO: pick_worker_algo = storage.getSettings()->cnch_merge_pick_worker_algo;
            worker_pool = getContext()->getCnchWorkerClientPools().getPool(vw_name);
        }
```

I found that the write pool is obtained from the worker client pools. And isn't daemon-manager here for data merging? Why is the pool of worker_write acquired here?

**Comment by dmthuc** [comment]
Hi @juppylm , in ByConity the merge task is create at Server and send the job to the write-worker for merge

**Comment by dmthuc** [comment]
Maybe @canhld94 know what is the problem with this setup

**Comment by canhld94** [comment]
> > Hi @juppylm , in ByConity we have a thread that always up to merge data so the use of `optimize` query is not necessary. I wonder if you deployment include Daemon-manager? BTW, we have system table `system.bg_threads` with the meaning of the field like below
> > ```
> > type: type of background thread: PartGCThread, MergeSelectThread, MemoryBufferManager ...
> > status: status of thread Running...
> > startup_time: startup time of thread
> > num_wakeup: the number of times the thread wakes up (run() method is called) 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can select into this system table to check if merge thread is running with query
> > ```
> > select * from system.bg_threads where database = 'database' and table = 'table' to see if merge thread is running
> > ```
> 
> @dmthuc The byconity cluster I deployed contains Daemon-manager. I looked at the stack information and the corresponding source code, and I found that it is indeed there to get the **cnch.vm** information from the cnch-config.yml file. The relevant code information is as follows:
> 
> ```java
> // CnchMergeMutateThread.cpp  
> //  line 404 to line 409
>         {
>             std::lock_guard lock(worker_pool_mutex);
>             vw_name = storage.getSettings()->cnch_vw_write;
>             /// TODO: pick_worker_algo = storage.getSettings()->cnch_merge_pick_worker_algo;
>             worker_pool = getContext()->getCnchWorkerClientPools().getPool(vw_name);
>         }
> ```
> 
> I found that the write pool is obtained from the worker client pools. And isn't daemon-manager here for data merging? Why is the pool of worker_write acquired here?

Hi @juppylm you're correct, the **cnch.vw** is missing, I will explain it later.

First to make it clear the role of daemon-manager. The background tasks doesn't run on daemon-manager. A background task include two phase: (1) prepare data, (2) execute the task, and (3) commit new data if any. Phase (1) and (3) run on server, and phase (2) runs on worker.
The daemon-manager plays role as an observer for all background tasks on servers from outside, so it can help to: (1) reschedule a background task from one server to another if needed (e.g. a server crash), or (2) detect if there's duplicated background tasks on different servers.

Go back to the original questions, your debug was correct as we're missing `data.cnch.vw` in the worker pool. The reason is: 
 in order to communicate to worker, we either use service discovery (`data.cnch.vw` is an endpoint of service discovery) or resource manager (that will manage all workers). Currently in different places we use different method. Background task uses service discovery, however I didn't config the service discovery for worker in the docker deployment. Queries can still run because for query execution, server connect to worker through resource manager.

We have an PR here https://github.com/ByConity/ByConity/pull/126 to unify both approach (the rule of thumb is when connect to worker, always use resource manager unless resource manager is not available.

I will also add service discovery config for workers in https://github.com/ByConity/byconity-docker, will let you know when it is done.

**Comment by canhld94** [comment]
> > > > Hi @juppylm , in ByConity we have a thread that always up to merge data so the use of `optimize` query is not necessary. I wonder if you deployment include Daemon-manager? BTW, we have system table `system.bg_threads` with the meaning of the field like below
> > > > ```
> > > > type: type of background thread: PartGCThread, MergeSelectThread, MemoryBufferManager ...
> > > > status: status of thread Running...
> > > > startup_time: startup time of thread
> > > > num_wakeup: the number of times the thread wakes up (run() method is called) 
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > You can select into this system table to check if merge thread is running with query
> > > > ```
> > > > select * from system.bg_threads where database = 'database' and table = 'table' to see if merge thread is running
> > > > ```
> > > 
> > > 
> > > @dmthuc The byconity cluster I deployed contains Daemon-manager. I looked at the stack information and the corresponding source code, and I found that it is indeed there to get the **cnch.vm** information from the cnch-config.yml file. The relevant code information is as follows:
> > > ```java
> > > // CnchMergeMutateThread.cpp  
> > > //  line 404 to line 409
> > >         {
> > >             std::lock_guard lock(worker_pool_mutex);
> > >             vw_name = storage.getSettings()->cnch_vw_write;
> > >             /// TODO: pick_worker_algo = storage.getSettings()->cnch_merge_pick_worker_algo;
> > >             worker_pool = getContext()->getCnchWorkerClientPools().getPool(vw_name);
> > >         }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I found that the write pool is obtained from the worker client pools. And isn't daemon-manager here for data merging? Why is the pool of worker_write acquired here?
> > 
> > 
> > Hi @juppylm you're correct, the **cnch.vw** is missing, I will explain it later.
> > First to make it clear the role of daemon-manager. The background tasks doesn't run on daemon-manager. A background task include two phase: (1) prepare data, (2) execute the task, and (3) commit new data if any. Phase (1) and (3) run on server, and phase (2) runs on worker. The daemon-manager plays role as an observer for all background tasks on servers from outside, so it can help to: (1) reschedule a background task from one server to another if needed (e.g. a server crash), or (2) detect if there's duplicated background tasks on different servers.
> > Go back to the original questions, your debug was correct as we're missing `data.cnch.vw` in the worker pool. The reason is: in order to communicate to worker, we either use service discovery (`data.cnch.vw` is an endpoint of service discovery) or resource manager (that will manage all workers). Currently in different places we use different method. Background task uses service discovery, however I didn't config the service discovery for worker in the docker deployment. Queries can still run because for query execution, server connect to worker through resource manager.
> > We have an PR here #126 to unify both approach (the rule of thumb is when connect to worker, always use resource manager unless resource manager is not available.
> > I will also add service discovery config for workers in https://github.com/ByConity/byconity-docker, will let you know when it is done.
> 
> Hi @canhld94. Thank you very much for your explanation, I think I know the role of daemon-manager. I always thought that background tasks run on daemon-manager. There is no need to use the service discovery mechanism after using resource-manager. I feel that the coexistence of the two is a bit confusing.

Yes, we only keep service discovery to discover servers, etc..
I update config for https://github.com/ByConity/byconity-docker, it can trigger merge now. You can try to fetch latest commit and start you cluster again.

**Comment by juppylm** [comment]
> 

Hi @canhld94. Thank you for your guidance, my byconity cluster has been deployed and is running normally.
