### ISSUE TITLE
Read CnchHive table error: DB::Exception: File not found: FileNotFoundException: /user/hive/warehouse/wisedata.db/par10/id=2vb not found.

### ISSUE THREAD

**Issue by xiaomo728** [ByConity/ByConity#132]
I am trying to use the CnchHive table engine. I just built a single-node HDFS and Hive service (open-source version) to test ByConity's ability to query the Hive table.
Here is the SQL that I used to create table in Hive:
```
CREATE TABLE `par10`(
    `name` string)
    PARTITIONED BY (
    `id` string)
    ROW FORMAT SERDE
    'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
    STORED AS INPUTFORMAT
    'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
    OUTPUTFORMAT
    'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
    LOCATION
    '/user/hive/warehouse/wisedata.db/par10';

INSERT INTO par10 VALUES ('1a','2vb');
```
![image](https://user-images.githubusercontent.com/74600187/223127080-0d61e433-c6a7-4455-a9a9-984bdbcc8fd8.png)

Here is the SQL that I used to create CnchHive table in ByConity, and it works:
```
CREATE TABLE hive_test_10 (　
    `id` String,
    `name` String) 
ENGINE = CnchHive('thrift://xx.xx.xxx.xxx:pppp', 'wisedata', 'par10') 
PARTITION BY id;
```

However, when I tried to read the table's data, it caused error:
```
:) select * from hive_test_10;

SELECT *
FROM hive_test_10

Query id: 795a6a56-6b25-4ba8-af9f-ecdea3ef7e4c

0 rows in set. Elapsed: 0.045 sec. 

Received exception from server (version 21.8.7):
Code: 1000. DB::Exception: Received from localhost:9000. DB::Exception: File not found: FileNotFoundException: /user/hive/warehouse/wisedata.db/par10/id=2vb not found. SQLSTATE: HY000. 
```

But on my corresponding HDFS service, the file obviously exists:

![image](https://user-images.githubusercontent.com/74600187/223128766-78d3a277-5588-4a52-9b97-dc545c0e8569.png)

**Comment by xiaomo728** [comment]
Hadoop version: 3.3.4, HIve version 3.1.2

**Comment by hustnn** [comment]
As discussed in the group, support multiple hdfs namenodes has issue, it needs to be fixed

**Comment by xiaomo728** [comment]
> As discussed in the group, support multiple hdfs namenodes has issue, it needs to be fixed

@hustnn Might this bug be fixed ASAP? I have read the relevant code  and feel that the problem may lie here (in `src/Storage/Hive/HiveMetastore.cpp`:)

```
Strings HiveMetastoreClient::getPartsNameInPartition(const StoragePtr & /*storage*/, const String & location)
{
    Strings part_names;
    LOG_DEBUG(&Poco::Logger::get("HiveMetastoreClient"), "partition location = {}", location);
    for (HDFSCommon::DirectoryIterator it = HDFSCommon::DirectoryIterator(location); it != HDFSCommon::DirectoryIterator(); ++it)
    {
        if (startsWith(it.name(), "_") || startsWith(it.name(), "."))
            continue;

        part_names.push_back(it.name());
    }

    return part_names;
}
```

Here the `HDFSCommon::DirectoryIterator()` returns the default HDFS object's iterator but **NOT** related Hive's.
In `HDFSFileSystem.cpp`:
```
DirectoryIterator::DirectoryIterator(const std::string& dir_path_): dir_path(joinPaths({dir_path_}, true))
{
    OpenDir();
    dir_path.setFileName(GetCurrent());
    file = dir_path;
}
```
and for `OpenDir()`:
```
void DirectoryIterator::OpenDir()
{
    file_names.clear();
    HDFSCommon::list(dir_path.toString(), file_names);
    current_idx = -1;
    Next();
}
```
and for `list()`:
```
void list(const std::string& path, std::vector<std::string>& files)
{
    getDefaultHdfsFileSystem()->list(path, files);
}
```
and for `getDefaultHdfsFileSystem()`:
```
fs_ptr<DB::HDFSFileSystem> & getDefaultHdfsFileSystem()
{
    if (defaultHdfsFileSystem == nullptr)
        throw Exception("Not register HDFSFileSystem", ErrorCodes::HDFS_FILE_SYSTEM_UNREGISTER);
    return defaultHdfsFileSystem;
}
```

Is it correct?

**Comment by xiaomo728** [comment]
How can I get _the address of the HDFS_ (that Hive is connected) from the address of Hive's thrift metastore?

**Comment by hustnn** [comment]
> I have read the relevant code and feel that the problem may lie here (in `src/Storage/Hive/HiveMetastore.cpp`:)

yes, you are right, do you have interest on working on it? We can discuss together.  cc @Clark0 @rmq @dong

**Comment by xiaomo728** [comment]
> > I have read the relevant code and feel that the problem may lie here (in `src/Storage/Hive/HiveMetastore.cpp`:)
> 
> yes, you are right, do you have interest on working on it? We can discuss together. cc @Clark0 rmq dong

@hustnn Sure. My idea is as following: 
1. Get the address of the HDFS that Hive connected through the information provided by the **Hive metastore** (i.e. `hms_client`);
2. Create a new `HDFSFileSystem` object in memory;
3. Iterate through the DirectoryIterator by this new HDFSFileSystem.
But I do not know if I can get such information from the Hive metastore. I am sorry that I do not know much about Hive development.

**Comment by Clark0** [comment]
> > > I have read the relevant code and feel that the problem may lie here (in `src/Storage/Hive/HiveMetastore.cpp`:)
> > 
> > 
> > yes, you are right, do you have interest on working on it? We can discuss together. cc @Clark0 rmq dong
> 
> @hustnn Sure. My idea is as following:
> 
> 1. Get the address of the HDFS that Hive connected through the information provided by the **Hive metastore** (i.e. `hms_client`);
> 2. Create a new `HDFSFileSystem` object in memory;
> 3. Iterate through the DirectoryIterator by this new HDFSFileSystem.
>    But I do not know if I can get such information from the Hive metastore. I am sorry that I do not know much about Hive development.

Hi, The HDFS information can be obtained from ```'Apache::Hadoop::Hive::Table'.sd.location``` which get from hms_client->getTable() method.

**Comment by hustnn** [comment]
@xiaomo728 We submit a PR https://github.com/ByConity/ByConity/pull/147, you can take a look
