### ISSUE TITLE
merge task too slow becuase kv map field prefetch is disabled

### ISSUE THREAD

**Issue by blueskygzhz** [ByConity/ByConity#1410]
172.26.33.109 :) select table, thread_id from system.manipulations;

SELECT
    table,
    thread_id
FROM system.manipulations

Query id: 344d914b-a72a-467c-a429-e6edac150414

┌─table────────────────┬─thread_id─┐
│ benchmark_5_billion  │      5718 │
│ benchmark_5_billion  │      5785 │
│ benchmark_5_billion  │      5826 │
│ benchmark_5_billion  │      5765 │
│ benchmark_5_billion  │      5416 │
│ benchmark_5_billion  │      5796 │
│ benchmark_5_billion  │      5864 │
│ benchmark_5_billion  │      5814 │
│ benchmark_5_billion  │      5452 │
│ benchmark_5_billion  │      5715 │
│ benchmark_5_billion  │      5749 │
│ benchmark_5_billion  │      5356 │
│ benchmark_5_billion  │      5443 │
│ benchmark_5_billion  │      5562 │
│ benchmark_15_billion │      5436 │
│ benchmark_15_billion │      5525 │
│ benchmark_15_billion │      5466 │
│ benchmark_15_billion │      5429 │
│ benchmark_15_billion │      5856 │
└──────────────────────┴───────────┘

19 rows in set. Elapsed: 0.005 sec. 

172.26.33.109 :) SELECT arrayStringConcat(arrayMap(x -> demangle(addressToSymbol(x)), trace), '\n') AS stacks FROM system.stack_trace WHERE thread_id = '5856' settings allow_introspection_functions = 1

SELECT arrayStringConcat(arrayMap(x -> demangle(addressToSymbol(x)), trace), '\n') AS stacks
FROM system.stack_trace
WHERE thread_id = '5856'
SETTINGS allow_introspection_functions = 1

Query id: 175ef6a6-8418-489b-9bd2-6d6cdd8a89fd

┌─stacks─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ 
epoll_wait
Poco::Net::SocketImpl::pollImpl(Poco::Timespan&, int)
Poco::Net::SocketImpl::poll(Poco::Timespan const&, int)
Poco::Net::SocketImpl::receiveBytes(void*, int, int)
Poco::Net::HTTPSession::read(char*, long)
Poco::Net::HTTPFixedLengthStreamBuf::readFromDevice(char*, long)
Poco::BasicBufferedStreamBuf<char, std::__1::char_traits<char>, Poco::Net::HTTPBufferAllocator>::underflow()
std::__1::basic_streambuf<char, std::__1::char_traits<char> >::uflow()
std::__1::basic_streambuf<char, std::__1::char_traits<char> >::xsgetn(char*, long)
std::__1::basic_istream<char, std::__1::char_traits<char> >::read(char*, long)
DB::ReadBufferFromIStream::nextImpl()
DB::ReadBufferFromS3::nextImpl()
DB::ReadBuffer::readStrict(char*, unsigned long)
DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&, bool)
DB::CompressedReadBufferFromFile::nextImpl()
DB::MergedReadBufferWithSegmentCache::nextImpl()
DB::MergedReadBufferWithSegmentCache::readBig(char*, unsigned long)
DB::SerializationNumber<double>::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const
DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >*) const
DB::SerializationNamed::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >*) const
DB::SerializationTuple::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >*) const
DB::SerializationArray::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >*) const
DB::IMergeTreeReader::readData(DB::NameAndTypePair const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, bool, unsigned long, unsigned long, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >&)
DB::MergeTreeReaderCNCH::readNecessaryRows(unsigned long, unsigned long, bool, unsigned long, unsigned long, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, unsigned long> > >&, std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&)
DB::MergeTreeReaderCNCH::readRows(unsigned long, unsigned long, unsigned long, unsigned long, std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&)
DB::MergeTreeSequentialSource::generate()
DB::ISource::tryGenerate()
DB::ISource::work()
DB::SourceWithProgress::work()
void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0, void ()> >(std::__1::__function::__policy_storage const*)
DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*)
DB::PipelineExecutor::executeStep(std::__1::atomic<bool>*)
DB::PullingPipelineExecutor::pull(DB::Chunk&)
DB::PullingPipelineExecutor::pull(DB::Block&)
DB::PipelineExecutingBlockInputStream::readImpl()
DB::IBlockInputStream::read()
DB::ExpressionBlockInputStream::readImpl()
DB::IBlockInputStream::read()
DB::MaterializingBlockInputStream::readImpl()
DB::IBlockInputStream::read()
DB::MergeTreeDataMerger::mergePartsToTemporaryPartImpl(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::MergeTreeMetaBase::MergingParams const&, DB::ManipulationListElement*, DB::IMergeTreeDataPart const*) │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

![0e4a828fe30659e2aeae92f0199588e](https://github.com/ByConity/ByConity/assets/147569085/9552b202-bc67-4a36-8c5d-3eaf2d3cc610)

**Comment by kevinthfang** [comment]
working on it
