### ISSUE TITLE
SQL error [36] [07000] occurs when importing data from mysql

### ISSUE THREAD

**Issue by syysummer** [ByConity/ByConity#1471]
When executing CREATE DATABASE 11_test ENGINE = MaterializedMySQL('xxxx:port', 'database', 'root', 'password'); an SQL error [36] [07000] occurs when importing data from mysql: Code: 36, e.displayText () = DB::Exception: Database engine CnchMaterializedMySQL cannot have arguments SQLSTATE: 22000 (version 21.8.7.1) , how to solve this problem?

**Comment by GallifreyY** [comment]
hi @syysummer we use CnchMaterializedMySQL instead of MaterializedMySQL
Can u try this instead?
`CREATE DATABASE 11_test ENGINE = CnchMaterializedMySQL('xxxx:port', 'database', 'root', 'password'); `

**Comment by syysummer** [comment]
Hello @GallifreyY , I still get the same error after replacing the CnchMaterializedMySQL engine you provided. I have the same sample code as provided in the ByConity source code, but it still prompts that CnchMaterializedMySQL does not support parameter passing.

**Comment by GallifreyY** [comment]
hi @syysummer, which version are you using?

**Comment by syysummer** [comment]
hi @GallifreyY , The current ByConity version is 21.7.8.1.

**Comment by GallifreyY** [comment]
hi! In version 0.2.x, there is a bug related to CnchMaterializedMySQL, see here:
https://github.com/ByConity/ByConity/blob/3b31c96290df0d4ef946a30857871217284dcadf/src/Databases/DatabaseFactory.cpp#L124
but we've already fixed it in new version started from 0.3.0:
https://github.com/ByConity/ByConity/blob/88ae5ab8549b857b36cfd2387445f2b7a09c7f7e/src/Databases/DatabaseFactory.cpp#L126
Can upgrade and try again. Appreciate your feedback!

**Comment by syysummer** [comment]
Hello, @GallifreyY ，I'm having some trouble. I'm deploying according to https://github.com/ByConity/byconity-deploy.
image:
  repository: byconity/byconity
  tag: stable
  imagePullPolicy: IfNotPresent, 
is this a 0.3.x image?

**Comment by GallifreyY** [comment]
hi @syysummer, you can find all the images in here:
https://hub.docker.com/r/byconity/byconity/tags

**Comment by syysummer** [comment]
Okay, thank you very much, I will try it with the new image.

**Comment by syysummer** [comment]
> hi @syysummer, you can find all the images in here: https://hub.docker.com/r/byconity/byconity/tags stable is not a 0.3.x image, can change the tag to 0.3.2 and redeploy. Thanks.

hello @GallifreyY ，Thank you so much! After using the 0.3.2 image, the CnchMaterializedMySQL engine can be used normally.
