### ISSUE TITLE
中文文档中实际显示为英文文档

### ISSUE THREAD

**Issue by ixnzh** [ByConity/ByConity#1487]
## ByConity 简介中第三节实际显示依然是英文文档

![image](https://github.com/ByConity/ByConity/assets/156054018/985241b3-d188-4f8e-90e8-82e16ad4c178

**Comment by GallifreyY** [comment]
hi! @tigerwangyb, can help take a look? thanks!

**Comment by wbtiger** [comment]
[PR #221 ](https://github.com/ByConity/byconity.github.io/pull/221)
