### ISSUE TITLE
Does the ByConity cluster service in Kubernetes support the 'SELECT * FROM system.clusters' command?

### ISSUE THREAD

**Issue by xixinil** [ByConity/ByConity#1496]
(you don't have to strictly follow this form)

## Question
![image](https://github.com/ByConity/ByConity/assets/104292932/bf701598-277d-4f52-b9dd-8846efb4a476)

**Comment by GallifreyY** [comment]
hi @xixinil , may I ask how did you deployed byconity? via k8s?

**Comment by GallifreyY** [comment]
hi @xixinil, system.clusters only reflects information from config file. We use virtual_warehouses instead.
`select * from virtual_warehouses;`
will display cluster info. Thanks!

**Comment by xixinil** [comment]
![image](https://github.com/ByConity/ByConity/assets/104292932/17f71aae-8147-4e4b-8db1-4444b27fe5c5)
The error message suggests that we are unable to proceed with the transfer. Could we communicate via WeChat to address this issue?

**Comment by xixinil** [comment]
> 你好@xixinil, system.clusters 仅反映配置文件中的信息。我们使用 virtual_warehouses 来代替。 `select * from virtual_warehouses;` 将显示集群信息。谢谢！

The error message suggests that we are unable to proceed with the transfer. Could we communicate via WeChat to address this issue?

**Comment by zeromem** [comment]
> ![image](https://private-user-images.githubusercontent.com/104292932/317143323-17f71aae-8147-4e4b-8db1-4444b27fe5c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MTg3MjYsIm5iZiI6MTcxMTUxODQyNiwicGF0aCI6Ii8xMDQyOTI5MzIvMzE3MTQzMzIzLTE3ZjcxYWFlLTgxNDctNGU0Yi04ZGIxLTQ0NDRiMjdmZTVjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QwNTQ3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjdjM2Y4ZDQ5MzFiMTI2Y2I4M2ExOWUwYWI0ZjU2NzJjMmJmMzVjNzZiNmY3MDJiOTcwNmUwOWFhNzZmMTU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ahTYYHFDHipz8-BGnODkEE3IbsTAdzKSMPEs5mn-TA8) The error message suggests that we are unable to proceed with the transfer. Could we communicate via WeChat to address this issue?

Hi @xixinil , it should be `system.virtual_warehouses`, and also you can check `system.workers` which tell you more details .

**Comment by GallifreyY** [comment]
virtual_warehouses is in system db, query should be:
`select * from system.virtual_warehouses;`
