### ISSUE TITLE
If importing a large table times out after two hours, how should this be handled?

### ISSUE THREAD

**Issue by xixinil** [ByConity/ByConity#1497]
(you don't have to strictly follow this form)

## Question
Code: 8067, e.displayText() = DB::Exception: Error whiling scanning data through FBDItrator. message: Operation aborted because the transaction timed out SQLSTATE: HY000 (version [21.8.7.1](http://21.8.7.1/))

**Comment by smmsmm1988** [comment]
hi @xixinil , could you please paste the full stack of such exception? Besides, what's the corresponding SQL?
