### ISSUE TITLE
 Delete empty fields in the table

### ISSUE THREAD

**Issue by skyoct** [ByConity/ByConity#1499]
## Question
Due to issue #1467, we are unable to add fields to our table. We want to try deleting some empty fields before adding new fields. Will deleting empty fields affect historical data? Will it put pressure on the system load?

**Comment by smmsmm1988** [comment]
> @smmsmm1988 Columns without written data.

just drop these columns

**Comment by skyoct** [comment]
@smmsmm1988 I tried to delete 20 fields, which will cause some impact on normal usage.

**Comment by smmsmm1988** [comment]
> @smmsmm1988 I tried to delete 20 fields, which will cause some impact on normal usage.

What is the impact? Normally, DROP COLUMNS will produce MUTATIONS on data parts, which will be scheduled to execute at background.

**Comment by skyoct** [comment]
@smmsmm1988 This leads to some queries timing out. For safety reasons, we have switched to a new table, Thank you for your help.
