### ISSUE TITLE
Data import supports partition atomic coverage

### ISSUE THREAD

**Issue by bright-zy** [ByConity/ByConity#1508]
(you don't have to strictly follow this form)

### We have tasks that need to be refreshed every day, including full table refresh and partition refresh. We hope that data partition refresh will not affect business queries, so we hope to support full table or partition coverage like hive and druid, or support table and partition atomic replacement 'swap' like doris

**Comment by GallifreyY** [comment]
hi @bright-zy, could you please elaborate more what feature you want?

**Comment by bright-zy** [comment]
> hi @bright-zy, could you please elaborate more what feature you want?

hi @GallifreyY , I want atomic operations to implement table or partition data replacement

For example, Hive uses OVERWRITE to replace table partitions
insert overwrite test.table1 partition (pt='20240328')
select
column1 ,
column2 ,
column3 
FROM
test.table2
where pt = '20240328'


like StarRocks,
ALTER TABLE table1 SWAP WITH temp_table1;
ALTER TABLE tbl1 REPLACE PARTITION (p1) WITH TEMPORARY PARTITION (tp1);

**Comment by smmsmm1988** [comment]
hi @bright-zy , ByConity has a new feature of INSERT OVERWRITE to address your issue. We are updating the document of such new feature and will send it to you when ready.

**Comment by bright-zy** [comment]
hi @smmsmm1988 ,That would be great. I'm looking forward to it.

**Comment by smmsmm1988** [comment]
> hi @smmsmm1988 ,That would be great. I'm looking forward to it.

https://byconity.github.io/zh-cn/docs/sql-syntax/sql-statements?open_in_browser=true#insert-overwrite

**Comment by bright-zy** [comment]
hi @smmsmm1988  Version 0.3.2 does not support
<img width="583" alt="image" src="https://github.com/ByConity/ByConity/assets/102500454/7fa5b3e8-ee1b-471f-af62-082fb4bd638d">

**Comment by smmsmm1988** [comment]
hi @kevinthfang , could you help check which ByConity version contains the feature of INSERT OVERWRITE?

**Comment by smmsmm1988** [comment]
> hi @smmsmm1988 Version 0.3.2 does not support <img alt="image" width="583" src="https://private-user-images.githubusercontent.com/102500454/321589604-7fa5b3e8-ee1b-471f-af62-082fb4bd638d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3Nzg0ODEsIm5iZiI6MTcxMzc3ODE4MSwicGF0aCI6Ii8xMDI1MDA0NTQvMzIxNTg5NjA0LTdmYTViM2U4LWVlMWItNDcxZi1hZjYyLTA4MmZiNGJkNjM4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQwOTI5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTQ2YjZiZmNjNGYyYmVmMTlmZTAzNDJmZjFlMmQ2M2YwNGQzNTRjNjBlN2RiNDBiZWVjY2FjYWY0N2Y5NTNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GZ3B-ubafAcFkNiOqK54R76VmJRlo1jF-998TVXMGIU">
> 
> ClickHouse client version 21.8.7.1. Connected to ClickHouse server version 21.8.7 revision 54450.

hi @bright-zy , version 0.3.2 does not contain this feature. You can try the latest version 0.4.0.
