### ISSUE TITLE
S3 storage configuration

### ISSUE THREAD

**Issue by syysummer** [ByConity/ByConity#1611]
I encountered a problem. I configured an S3 bucket as storage, created the byconity0 directory under S3 bucket cxxx-xxy, and modified the relevant configuration as follows:
![r9uAkNLjcJ](https://github.com/ByConity/ByConity/assets/40320147/adb1c6c2-759d-4c34-bd3d-af7059b7873b)
![Yi4JDxOL6L](https://github.com/ByConity/ByConity/assets/40320147/78e13039-599b-4ecd-8f37-30322094d606)
After I created the data table with storage_policy = 'cnch_default_s3', I got an error when inserting data into the table. 
SQL 错误 [499] [07000]: Code: 499, e.displayText() = DB::S3::S3Exception: Encounter exception when request s3, HTTP Code: 404, RemoteHost: , RequestID: SV0V3QHNNBT8P5XA, ExceptionName: NoSuchKey, ErrorMessage: The specified key does not exist., Extra: Could not list objects in bucket cxxx-xxy with prefix byconity0/ef0d789d-c1b4-d43e-c7c2-e3a9de4f9ff3/ SQLSTATE: HY000 (version [21.8.7.1](http://21.8.7.1/))
, server ClickHouseNode [uri=http://172.21.30.238:8123/default, options={socket_timeout=6000000,use_server_time_zone=false,use_time_zone=false}]@-621526795
I don't know how else I need to modify the configuration?

**Comment by smmsmm1988** [comment]
hi @syysummer . Maybe you have a misconfiguration of S3, such as endpoint, API key, etc. Could you re-check the configuration again?

**Comment by syysummer** [comment]
hello @smmsmm1988 , Thank you very much. The S3 address and permissions have been confirmed. According to the analysis of the error message, the connection has been successful, but the resource cannot be obtained. The error message is 
<Error> TransactionCleaner: auto DB::TransactionCleaner::scheduleTask((lambda at ../src/Transaction/TransactionCleaner.cpp:170:18) &&, DB::CleanTaskPriority, DB::TxnTimestamp, DB::Protos::TransactionStatus &&)::(anonymous class)::operator()() const : Code: 499, e.displayText() = DB::S3::S3Exception: Encounter exception when request s3, HTTP Code: 404, RemoteHost: , RequestID: 307T495ZWHG4N26M, ExceptionName: NoSuchKey, ErrorMessage: The specified key does not exist. , Extra: Could not list objects in bucket cxxx-xxy with prefix /byconity0/bb6ddf05-3863-ac0a-478e-43ff84771ba6/ SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):
2024.04.12 02:22:07.652764 [ 686 ] {} <Debug> AWSClient: AWS S3 slow read(100ms): https://cxxx-xxy.s3.amazonaws.com/cxxx-xxy?list-type=2&max- keys=1&prefix=%2Fbyconity0%2F48a8e154-335e-0a19-eeba-876679aef136%2F, time = 861ms, header = x-amz-request-id: 307VGAYSA5WMZK7H; x-amz-id-2: NP8Pi8xUp0j+5w4/CHLB5bVxlPYMJp7 GvEdlwM+K3m674IU1s8nZ8ppYKWlnWJcDqXUYH3oynS0 =; Content-Type: application/xml; Transfer-Encoding: chunked; Date: Fri, 12 Apr 2024 02:22:07 GMT; Server: AmazonS3;
May I ask, is there anything else that needs to be configured on byconity?

**Comment by syysummer** [comment]
The problem has been solved. Things you need to pay attention to. After the configuration modification is completed, you need to delete the byconity-server pod and restart it after modifying it again. Thank you.
