### ISSUE TITLE
我在一个没有外网环境的服务器上部署docker开发环境

### ISSUE THREAD

**Issue by ChenMoGe2** [ByConity/ByConity#1622]
我参考这篇文章部署本地环境
https://github.com/ByConity/ByConity/tree/master/docker/debian/dev-env

我看脚本中的部署过程在docker中需要执行git命令，我的服务器没有外网环境，请问如何部署？

**Comment by ixnzh** [comment]
@ChenMoGe2 https://gitlink.org.cn/ByConity/ByConity/releases 可以用这里的链接
