### ISSUE TITLE
边写边读，读取数据会报错

### ISSUE THREAD

**Issue by yijiluo** [ByConity/ByConity#1641]
(you don't have to strictly follow this form)

### Briefly describe the bug
当批量通过insert into format Parquet infile 执行插入的时候，执行select * from test.test limit 10,查询会报错，报错如下：
![image](https://github.com/ByConity/ByConity/assets/131134513/91476c16-569a-4ae9-aed8-490bc8556ced)
![image](https://github.com/ByConity/ByConity/assets/131134513/caa96f12-6758-4907-8dbf-cb77b1f9cf35)
### The result you expected
在写入数据的同时能够稳定读取数据。
### How to Reproduce
批量执行insert into format Parquet infile，然后对表进行查询。
### Version
Byconity 0.3.2

**Comment by Clark0** [comment]
Two kinds of error will happen during insertion? The first query is a timeout, what's the size of the whole table?

**Comment by kevinthfang** [comment]
for the 1st errorm, would you please add some resources and check if the error rate can be decreased?

**Comment by jenrryyou** [comment]
第一个报错是查询超时，第二个可以先尝试加enable_optimizer_fallback=0 看下真正的报错

**Comment by kevinthfang** [comment]
@yijiluo 目前还有问题么？
