### ISSUE TITLE
setting enable_gc_evict_disk_cache  not work

### ISSUE THREAD

**Issue by blueskygzhz** [ByConity/ByConity#1642]
2024.04.18 09:40:03.471239 [ 1064 ] {} (449158665270198365) <Error> carms.carms_usage_statistics (5ecd4c14-e64b-4ca9-8849-6a45658c013a)(PartGCThread): Fail to drop disk cache for carms.carms_usage_statistics (5ecd4c14-e64b-4ca9-8849-6a45658c013a): Code: 49, e.displayText() = DB::Exception: Transaction is not set (empty) SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):

0. /home/carms/byconity_code/contrib/libcxx/include/exception:133: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x26929272 in /usr/bin/clickhouse
1. /home/carms/byconity_code/src/Common/Exception.cpp:97: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x1930a240 in /usr/bin/clickhouse
2. /home/carms/byconity_code/src/Interpreters/Context.cpp:0: DB::Context::getCurrentTransactionID() const @ 0x201554b1 in /usr/bin/clickhouse
3. /home/carms/byconity_code/src/Storages/StorageCnchMergeTree.cpp:1734: DB::StorageCnchMergeTree::sendDropDiskCacheTasks(std::__1::shared_ptr<DB::Context const>, std::__1::vector<std::__1::shared_ptr<DB::ServerDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::ServerDataPart const> > > const&, bool, bool) @ 0x210be3bc in /usr/bin/clickhouse
4. /home/carms/byconity_code/contrib/libcxx/include/string:1470: DB::CnchPartGCThread::doPhaseOnePartitionGC(std::__1::shared_ptr<DB::IStorage> const&, DB::StorageCnchMergeTree&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, DB::TxnTimestamp) @ 0x1f7ad94f in /usr/bin/clickhouse
5. /home/carms/byconity_code/contrib/libcxx/include/iterator:1496: DB::CnchPartGCThread::doPhaseOneGC(std::__1::shared_ptr<DB::IStorage> const&, DB::StorageCnchMergeTree&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_trait

**Comment by smmsmm1988** [comment]
this issue is resolved in the upcoming version
