### ISSUE TITLE
Dead lock may happens when byconity exit

### ISSUE THREAD

**Issue by ArthurZou** [ByConity/ByConity#1647]
here is the backtrace：
![企业微信截图_2d5e2534-dbef-46ad-8976-bd239f0499b5](https://github.com/ByConity/ByConity/assets/7134918/f176a2c3-4145-4ea5-9297-78a0446ba7ba)

This is may caused by attempting to destroy a condition variable upon which other threads are currently blocked

**Comment by ArthurZou** [comment]
Byconity was built by commit 5cf3911931.
this is occasional when program exit.


https://github.com/ByConity/libhdfs3-open/blob/33cc568a560a6d222a5f75aec90c7638b1314a3b/src/client/async_preader/StaticInitialization.cpp
There is a static variable io_context which is a boost::asio::io_context instance.  It will be destructed when program exit.
As the backtrace shows, this will come to :pthread_cond_destroy(&cond_) in  https://github.com/ClickHouse/boost/blob/c0807e83f2824e8dd67a15b355496a9b784cdcd5/boost/asio/detail/posix_event.hpp eventually。 
 Accroding to https://linux.die.net/man/3/pthread_cond_destroy，I guess may be this is caused by attempting to destroy a condition variable upon which other threads are currently blocked

**Comment by wordhardqi** [comment]
``` cpp
{
    namespace AsyncCb
    {
        static boost::asio::io_context io_context;
        boost::asio::io_context & AsioGlobalContext::Instance()
        {
            static AsioGlobalContext globalContextInitializer;
            return io_context;
        }

        AsioGlobalContext::AsioGlobalContext()
        {
//            auto count = std::thread::hardware_concurrency() / 8;
            auto count =  std::thread::hardware_concurrency() ;
            for (int i = 0; i < count; i++)
            {
                // the work guard here is used to keep run() away from returning when there is no work.
                threads.emplace_back([&] {
                    std::string threadName = "hedge-read-" + std::to_string(i);
                    prctl(PR_SET_NAME,threadName.c_str(),0,0,0);
                    auto work = boost::asio::require(io_context.get_executor(), boost::asio::execution::outstanding_work.tracked);
                    io_context.run();
                });
            }
        }
        AsioGlobalContext::~AsioGlobalContext()
        {
            io_context.stop();
            for (auto & th : threads)
            {
                if (th.joinable())
                {
                    th.join();
                }
            }
        }

    }


    LruMultiMap<std::string, PeerCache::value_type> PeerCache::Map;
    LruMultiMap<std::string, PeerCache::value_type_async> PeerCache::MapAsync;
}
```
The code is in StaticInitialization.cpp in libhdfs. It's pretty weird. AsioGlobalContext is inited after io_context so it should be deconstructed before io_context. but the log shows io_context is at least desconsturcted before the AsioGlobalContext

@ArthurZou
