### ISSUE TITLE
Preloading bug

### ISSUE THREAD

**Issue by bright-zy** [ByConity/ByConity#1651]
(you don't have to strictly follow this form)

### Briefly describe the bug
```
Syntax error: failed at position 107 ('='):

ALTER TABLE olap.olap_comm_deal_margin_agreement_indicator_di_cube_v37 MODIFY SETTINGS parts_preload_level=3;

Expected one of: CODEC, PRIMARY KEY, end of query, BitEngineEncode, NULL, INTO OUTFILE, ALIAS, COMPRESSION, BLOOM, TTL, Comma, SETTINGS, SECURITY, ENCRYPT, FORMAT, KV, DEFAULT, NOT, BYTE, MATERIALIZED, COMMENT, BitmapIndex, token, AUTO_INCREMENT
```

### The result you expected
The operation was successful

### How to Reproduce
https://byconity.github.io/docs/query-optimization/query-optimization-with-cache-preload
ALTER TABLE olap.olap_comm_deal_margin_agreement_indicator_di_cube_v37 MODIFY SETTINGS parts_preload_level=3;
### Version
0.4.0

**Comment by GallifreyY** [comment]
hi @bright-zy, sorry for the mislead. It should be SETTING instead of SETTINGS:
`ALTER TABLE olap.olap_comm_deal_margin_agreement_indicator_di_cube_v37 MODIFY SETTING parts_preload_level=3;`
We will update the webpages accordingly. Thanks for the feedback!
