### ISSUE TITLE
Import csv files

### ISSUE THREAD

**Issue by syysummer** [ByConity/ByConity#1662]
ByConity 0.4.0 imports csv files through DBeaver tool, prompting that script parameters cannot be set
 Can't set parameter at index 1 due to no JDBC style '?' placeholder found in the query
![image](https://github.com/ByConity/ByConity/assets/40320147/0cf43bd3-5a9d-4dae-bc80-320d293130d2)
![image](https://github.com/ByConity/ByConity/assets/40320147/2a3bc2b3-1151-42dc-9b3c-7370c09efa85)

**Comment by nudles** [comment]
@syysummer can you share the table create sql and a sample of the csv file?

**Comment by syysummer** [comment]
@nudles 
We exported the sql file and then imported the existing data into ByConity through a python script.

**Comment by nudles** [comment]
@syysummer 
can you try to change these two settings to 1 for your byconity servers (via the configuration files)?
https://github.com/ByConity/ByConity/blob/bfa389c67b623640d20a2ef1b0097d05ba167d6d/src/Core/Settings.h#L375

**Comment by syysummer** [comment]
@nudles Hello,Hello, I have modified the configuration and still cannot import the csv file.
![image](https://github.com/ByConity/ByConity/assets/40320147/1af818dd-2a94-48bf-b788-a5f52452ab0e)
![image](https://github.com/ByConity/ByConity/assets/40320147/eb320ccc-2322-41a7-9640-9aa464517296)
