### ISSUE TITLE
cmake时，循环依赖错误如何解决

### ISSUE THREAD

**Issue by yangtao-taoyang** [ByConity/ByConity#1664]
背景：想在本地mac笔记本下cmake 工程，
clang：15版本
cmake：3.29.2 版本
cmake之后，老是报循环依赖问题，如下：
<img width="1075" alt="image" src="https://github.com/ByConity/ByConity/assets/38877667/351b8070-ea88-4752-a879-eb830fbd2912">

请教下，需要如何才能解决这个问题，多谢🙏

**Comment by kevinthfang** [comment]
We don't support compilation on Mac currently
