### ISSUE TITLE
Turning on the query optimizer will make the query slower.

### ISSUE THREAD

**Issue by syysummer** [ByConity/ByConity#1675]
My steps are as follows. 
The executed SELECT is "SELECT * FROM database.table WHERE id = ((SELECT MAX(id) FROM database.table) - 5);"
![image](https://github.com/ByConity/ByConity/assets/40320147/e8202fb2-c526-4711-af36-8de8879a3149)
byconity version is 0.4.0.

**Comment by FluorineDog** [comment]
try set enable_execute_uncorrelated_subquery=1?

If effective, I think this setting should be enabled by default. We will do it in next version.

**Comment by syysummer** [comment]
Thank you for knowing. I tried to set this parameter, but the difference before and after setting is not obvious.
