### ISSUE TITLE
The Cache Preload does not achieve the expected effect

### ISSUE THREAD

**Issue by bright-zy** [ByConity/ByConity#1676]
(you don't have to strictly follow this form)

## Question
create table
```
CREATE TABLE measure_olap.olap_comm_deal_margin_agreement_indicator_di_cube_v37
(
    ...
)
ENGINE = CnchMergeTree
PARTITION BY toYYYYMMDD(dim_public_date_info_date)
ORDER BY olap_comm_deal_margin_agreement_indicator_di_shop_code
SETTINGS storage_policy = 'cnch_default_hdfs', index_granularity = 8192, parts_preload_level = 3, enable_local_disk_cache = 1
```
query sql
```
SELECT 
toYYYYMMDD(t0.`dim_public_date_info_date`) AS `date`,
t0.`dim_public_date_info_month`  AS `month`,
SUM(t0.`olap_comm_deal_margin_agreement_indicator_di_assess_income_amt_sum`) AS `kaoheshourujine` 
FROM `measure_olap`.`olap_comm_deal_margin_agreement_indicator_di_cube_v37` AS t0 
WHERE  
t0.`olap_comm_deal_margin_agreement_indicator_di_brand_name` IN ('KX','外X,'德X') 
AND t0.`olap_comm_deal_margin_agreement_indicator_di_statistical_name` IN ('月')  
AND t0.`olap_comm_deal_margin_agreement_indicator_di_area_code` IN ('SXX3021')  
AND t0.`olap_comm_deal_margin_agreement_indicator_di_is_agent_city_code` NOT IN (1)   
AND t0.`dim_public_date_info_date` IN ('20240420','20240520')  
GROUP BY t0.`dim_public_date_info_month`,toYYYYMMDD(t0.`dim_public_date_info_date`) LIMIT 2000;
```
result
<img width="405" alt="image" src="https://github.com/ByConity/ByConity/assets/102500454/a63a35c6-5e21-4f05-ab3e-b32cb8b9e739">

first query
<img width="1406" alt="image" src="https://github.com/ByConity/ByConity/assets/102500454/b56bfa4d-6d74-4df3-943b-977a7a574402">

second query
<img width="1152" alt="image" src="https://github.com/ByConity/ByConity/assets/102500454/4319096f-dab0-4294-8977-e935a99bf5bf">

**Comment by foreverneverer** [comment]
Preload need `alter` command to manual triger or some parts is inserted or merged to auto triger. otherwise the existed data in db will not been preloaded to local disk.

so after you open the preload, do you execute `alter` command or insert new part data?

**Comment by bright-zy** [comment]
@foreverneverer I execute alter command or insert new part data is ok, but importing historically existing data is not possible without manually executing.

**Comment by foreverneverer** [comment]
"historically existing data" must "manually executing" can be preloaded
