### ISSUE TITLE
S3 is being uploaded in segments, Is it too small to set the part file size to 16MB?

### ISSUE THREAD

**Issue by FourSpaces** [ByConity/ByConity#1679]
## Question
When I was troubleshooting a 40GB object in Minio, I found that there were over 2000 part files. After reviewing the code of ByConity, I found that the size of the segmented uploaded part file is 16MB. I am concerned that a too small value may lead to an increase in the number of parts, Minio needs to open a large number of files to read data, resulting in increased disk pressure.
Can it be set to 64MB?

https://github.com/ByConity/ByConity/blob/bfa389c67b623640d20a2ef1b0097d05ba167d6d/src/IO/WriteBufferFromByteS3.h#L68C1-L80C1

**Comment by Alima777** [comment]
Hi, @FourSpaces 

Firstly, don't worry about the number of parts. For large object, we will use Multiple upload interface of S3, you can refer to https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html. After the whole request finish, S3 will combine the parts to a single file.

Secondly, if you still want to increase the part size, you can set the `s3_max_single_part_upload_size`

**Comment by FourSpaces** [comment]
@Alima777  One thing that needs to be clarified here is that after uploading in segments to Minio, Part files are independent on physical disks, only associating these parts with an object in metadata.

The following image shows the disk part files of an object under Minio, and we can see that it has many part files.
![image](https://github.com/ByConity/ByConity/assets/13359726/1e39adb7-8be4-4a45-bc9c-121a310554a5)



I have observed that the configuration of 's3_min_upload_part_size' will affect WriteBufferFromS3.cpp. Currently, the WriteBufferFromByteS3.cpp file used by S3 does not use 's3_min_upload_part_size'.

**Comment by Alima777** [comment]
Maybe only minIO is like this.

https://github.com/minio/minio/discussions/17405
https://github.com/minio/minio/discussions/19490

**Comment by Alima777** [comment]
I'm curious how you are using the 40GB object? Insert into ByConity? or something else?

**Comment by FourSpaces** [comment]
@Alima777 
Our data volume is relatively large, ByConity will merge data from a few days ago into a relatively large object.

Due to the lack of file merging at the underlying level of Minio, it is necessary to increase the size of the uploaded part files, which will reduce the disk pressure on the Minio cluster. I think it seems to be a fixed 16MB here. If we change it directly to 64MB, will there be any problems?

**Comment by Alima777** [comment]
> I think it seems to be a fixed 16MB here
I'm afraid that's true...

> If we change it directly to 64MB, will there be any problems?
No problem. If you can make it configurable, that will be much better.

**Comment by FourSpaces** [comment]
@Alima777  Will we modify [this](https://github.com/ByConity/ByConity/blob/bfa389c67b623640d20a2ef1b0097d05ba167d6d/src/IO/WriteBufferFromByteS3.h#L68C1-L80C1)，is there anything else that needs to be modified to meet our needs?

Will this fix `s3_min_upload_part_siz`e in the future?

**Comment by Alima777** [comment]
No, you have to change the code in DiskByteS3.cpp too. @FourSpaces 

Actually, if you can make it configurable and contribute code back to the community, it will be great.

**Comment by FourSpaces** [comment]
Okay, I'll give it a try
