### ISSUE TITLE
执行 insert select 报错，limit 100时正常，10000时报错

### ISSUE THREAD

**Issue by ixnzh** [ByConity/ByConity#1682]
执行 insert select，limit 100时：

![dda81934829b7278ba54dc1aac3d9f0](https://github.com/ByConity/ByConity/assets/156054018/ef3da939-2b0f-4609-83a7-8310a675b5da)

limit 1000和10000时
![f9138c1de41ab6956a151f48f7b57ef](https://github.com/ByConity/ByConity/assets/156054018/f38748c4-cf95-4398-9bf3-477a3ed82c9b)

不限制时和limit10000一样
![638c0af356f943828b5ac5fcba7551f](https://github.com/ByConity/ByConity/assets/156054018/30985147-643a-4ede-99df-c728decdfbfd)

这是否是否符合预期

**Comment by jenrryyou** [comment]
select * from cnch('vw_name', system.query_log) where event_date = today() and initial_query_id = 'the_initial_query_id' and type > 2 and exception_code not in (2010,394, 2003); 看下worker上是否有其他报错，vw_name替换成实际的Vw

**Comment by ixnzh** [comment]
> select * from cnch('vw_name', system.query_log) where event_date = today() and initial_query_id = 'the_initial_query_id' and type > 2 and exception_code not in (2010,394, 2003); 看下worker上是否有其他报错，vw_name替换成实际的Vw

![246c2b0946003106cc1ffa55149ee81](https://github.com/ByConity/ByConity/assets/156054018/c6908bf0-537b-4e16-934f-6ff815381c64)

**Comment by jenrryyou** [comment]
猜测是memory limit 超了，可以先set enable_optimzier =0试下

**Comment by ixnzh** [comment]
如果字段带分区字段就会报错，没有就不会

**Comment by kevinthfang** [comment]
0.4.1版本已解决
