### ISSUE TITLE
already exists error

### ISSUE THREAD

**Issue by syysummer** [ByConity/ByConity#1689]
I don’t know what’s going on. When I select data, I get an error: DB::Exception: DB::Exception: Table ai_data_analysis.k1max_device_event_450140781639368706 already exists. SQLSTATE: 42P07.: While executing Remote SQLSTATE: 42P07. Stack trace:
This is not necessary. This problem occurs occasionally. What is the reason?
Byconity version: 0.4.0

**Comment by yuanzhubi** [comment]
Could you give these information first?
1. table definition 
2. select query
3. exception stack trace

**Comment by syysummer** [comment]
> 3\. exception stack trace
OK, thank you. How can I check the exception stack trace?
![image](https://github.com/ByConity/ByConity/assets/40320147/8b3601a4-81c4-460f-8303-ddd8d51e4d0a)

**Comment by jenrryyou** [comment]
@yuanzhubi you can add a setting enable_optimizer_fallback=0 for query or in user.xml profile section

**Comment by kevinthfang** [comment]
after enable_optimizer_fallback=0, the root cause was found. It's because the FDB storage size exceeds the limit. It's already resolved
