### ISSUE TITLE
How to import incremental data using kafka without HDFS

### ISSUE THREAD

**Issue by syysummer** [ByConity/ByConity#1690]
We deployed byconity on aws and did not install HDFS. However, we wanted to use kafka to import incremental data and found that byconity could not be consumed. After the storage of cnch_system.cnch_kafka_log was changed to S3, an error was still reported. How can I do this without using HDFS? How can I import incremental data using kafka?
![image](https://github.com/ByConity/ByConity/assets/40320147/3aab40fc-a4fb-43a8-b451-26d21b1bd3fe)

**Comment by Alima777** [comment]
How is `Storage policy` in your configuration file like?

**Comment by kevinthfang** [comment]
Please also provide the definition of kafka table.

**Comment by syysummer** [comment]
hello, What you mean is that you can configure the cnch_default_hdfs policy to be stored in S3?

**Comment by syysummer** [comment]
![image](https://github.com/ByConity/ByConity/assets/40320147/9a19484d-837c-4884-94c3-5d96afe973ee)

![image](https://github.com/ByConity/ByConity/assets/40320147/7925871e-b97a-4327-9fbb-ef9a15a25765)

**Comment by Alima777** [comment]
Hi， @syysummer 

Change the cnch_default_hdfs like this:

```
<cnch_default_hdfs>
  <volumes>
    <s3>
      <default>server_s3_disk_0</default>
      <disk>server_s3_disk_0</disk>
    </s3>
  </volumes>
</cnch_default_hdfs>
```


About why it's called `cnch_default_hdfs` even if you use S3....It's a historical reason, we will change it in the future

**Comment by Alima777** [comment]
Have you tried restart after modification? @syysummer 

And what's the port 12001 for?

**Comment by syysummer** [comment]
Restarted. This configuration is in cnch_config. We don’t want to use HDFS now, so we haven’t installed HDFS. Some configurations are using the default ones.
![image](https://github.com/ByConity/ByConity/assets/40320147/096c1dc7-3cbb-4a6c-8824-5557584b9aa2)

**Comment by foreverneverer** [comment]
you can try drop table and re-create table

**Comment by syysummer** [comment]
Thank you, I have also tried it. In order to eliminate the cause of HDFS, HDFS is also installed now, which eliminates the error reported just now, but Kafka does not consume. I wrote a separate script to subscribe to the topic and the data was successfully subscribed. How should I troubleshoot? Is there a problem with kafka not consuming in byconity?

**Comment by smmsmm1988** [comment]
> Thank you, I have also tried it. In order to eliminate the cause of HDFS, HDFS is also installed now, which eliminates the error reported just now, but Kafka does not consume. I wrote a separate script to subscribe to the topic and the data was successfully subscribed. How should I troubleshoot? Is there a problem with kafka not consuming in byconity?

@syysummer what about checking cnch_system.cnch_kafka_log for the table not consuming?

**Comment by smmsmm1988** [comment]
> The cnch_system.cnch_kafka_log table is empty and has no data? Are there any other ways to check? ![image](https://private-user-images.githubusercontent.com/40320147/336266549-8a328282-66a0-44f5-95a2-45fc77cd7341.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NjY0NjAsIm5iZiI6MTcxNzQ2NjE2MCwicGF0aCI6Ii80MDMyMDE0Ny8zMzYyNjY1NDktOGEzMjgyODItNjZhMC00NGY1LTk1YTItNDVmYzc3Y2Q3MzQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDAxNTYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlMGJhMDcwNDIxOWY3YTI2M2ZiMzI0YjQ1NzgxZmU3ZjczYzJiZTE5ODZkOWI5MmMxMDU2NjQ0ODI3MjI4NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VHysX3sZa2Gr6aRENlyHoFK6jHUNmF7wxjwsWyH9w3I)

is 172.31.30.246 the write worker? And please check system.cnch_kafka_tables given the database and kafka table.

**Comment by syysummer** [comment]
172.31.30.246 is the address of the kafka service and the location of byconity deployment. The write worker is on another device.
system.cnch_kafka_tables query result is empty
![image](https://github.com/ByConity/ByConity/assets/40320147/24b4eb16-c4a2-401e-b6d5-9b7b4a416b53)

**Comment by smmsmm1988** [comment]
> 172.31.30.246 is the address of the kafka service and the location of byconity deployment. The write worker is on another device. system.cnch_kafka_tables query result is empty ![image](https://private-user-images.githubusercontent.com/40320147/336287046-24b4eb16-c4a2-401e-b6d5-9b7b4a416b53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0Njk1NjUsIm5iZiI6MTcxNzQ2OTI2NSwicGF0aCI6Ii80MDMyMDE0Ny8zMzYyODcwNDYtMjRiNGViMTYtYzRhMi00MDFlLWI2ZDUtOWI3YjRhNDE2YjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDAyNDc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkMWVhOTZkYzE2N2I3NTdjMGQ5M2Q0Y2RiMDU1MzQ5MzYxNjFkZmViZDJlOTBjZjRmOTY2ZTYxOTkwZmYwMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qTC3ZHf1KPIKYr_iqQ3M70MH8YqO2WtCx0CbY3eVP2o)

So 172.31.30.246 is the server node you deployed? Checking system.cnch_kafka_tables and cnch_system.cnch_kafka_log should be run on the server node. And if 172.31.30.246 is the server node, please run system restart consume {db}.{kafka_table}, and check whether it will restart the consumption.

**Comment by syysummer** [comment]
I tried your method but got an error. In fact, these tables were created.
![image](https://github.com/ByConity/ByConity/assets/40320147/e8781727-95fb-4630-b149-cf9e52a3ca23)
![image](https://github.com/ByConity/ByConity/assets/40320147/26a7949c-5984-410f-8108-5be42386c189)

**Comment by smmsmm1988** [comment]
> I tried your method but got an error. In fact, these tables were created. ![image](https://private-user-images.githubusercontent.com/40320147/336294921-e8781727-95fb-4630-b149-cf9e52a3ca23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NzIwOTcsIm5iZiI6MTcxNzQ3MTc5NywicGF0aCI6Ii80MDMyMDE0Ny8zMzYyOTQ5MjEtZTg3ODE3MjctOTVmYi00NjMwLWIxNDktY2Y5ZTUyYTNjYTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDAzMjk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlYTdiNDRhZTk3YmFiY2E0OWU4MTRjMmE1ZDk4ZjQ5MzAxNDg2OGRiYmM3NDUyZDljZWNkMDFmZDkzOThlMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cn0UmTjxAdU6OBsCz9cCfYZzztuNOYRdHMCkuG4_NbE) ![image](https://private-user-images.githubusercontent.com/40320147/336295009-26a7949c-5984-410f-8108-5be42386c189.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NzIwOTcsIm5iZiI6MTcxNzQ3MTc5NywicGF0aCI6Ii80MDMyMDE0Ny8zMzYyOTUwMDktMjZhNzk0OWMtNTk4NC00MTBmLTgxMDgtNWJlNDIzODZjMTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDAzMjk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhZjczMWUxMjljN2NlOTNiNDdiOWExMjMwMGM2MmZlOTk3MGUwYTM1OTE1OWJkZWJkZDljZDVkNjQyMDQwYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nOBBXqGnHNrnBF4p__GW46BhlxlJqfuCMH_iiNwpLQk)

please send the schema of k1_end_jpg_view and k1_end_jgp_consumer by using show create table

**Comment by syysummer** [comment]
> please send the schema of k1_end_jpg_view and k1_end_jgp_consumer by using show create table
![image](https://github.com/ByConity/ByConity/assets/40320147/713f09da-1555-43dd-af25-26a3c3ecf28b)

**Comment by syysummer** [comment]
> @syysummer The error of system restart consume seems that test_data_yy.k1_end_jpg does not exist or is detached. You can run select * from system.cnch_tables where database = 'xxx' and name = 'yyy' to check the table status. You can check the status of k1_end_jpg, k1_end_jpg_view and k1_end_jpg_consume respectively. You also can run select count(1) from test_data_yy.k1_end_jpg to see the result.

Thank you very much for your patient answer. Kafka data can now be consumed. When you asked me to SYSTEM RESTART COMSUME, I found that daemon manage is necessary. We did not install this. After it is installed and configured correctly, it can be consumed.
