### ISSUE TITLE
Transaction record has been changed by other transactions

### ISSUE THREAD

**Issue by ozcelgozde** [ByConity/ByConity#1694]
### Briefly describe the bug
Hey, l have version 0.4.0 installed and servers print this error during merge:
```
2024.06.05 07:30:07.301218 [ 1462 ] {} <Error> virtual void DB::CnchMergeMutateThread::runImpl(): Code: 11003, e.displayText() = DB::Exception: Transaction 450251353262915843 commit failed because txn record has been changed by other transactions SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x2747d4b2 in /opt/byconity/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x10959fe0 in /opt/byconity/bin/clickhouse
2. DB::CnchServerTransaction::commit() @ 0x2001829c in /opt/byconity/bin/clickhouse
3. DB::CnchServerTransaction::commitV2() @ 0x20014ecb in /opt/byconity/bin/clickhouse
4. DB::CnchMergeMutateThread::removeLockedPartition(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x201af22b in /opt/byconity/bin/clickhouse
5. DB::CnchMergeMutateThread::trySelectPartsToMerge(std::__1::shared_ptr<DB::IStorage>&, DB::StorageCnchMergeTree&, DB::MergeSelectionMetrics&) @ 0x201aaa45 in /opt/byconity/bin/clickhouse
6. DB::CnchMergeMutateThread::tryMergeParts(std::__1::shared_ptr<DB::IStorage>&, DB::StorageCnchMergeTree&) @ 0x201a9ed8 in /opt/byconity/bin/clickhouse
7. DB::CnchMergeMutateThread::runImpl() @ 0x201a6c74 in /opt/byconity/bin/clickhouse
2024.06.05 07:30:07.301821 [ 575 ] {} <Error> virtual void DB::CnchMergeMutateThread::runImpl(): Code: 11003, e.displayText() = DB::Exception: Transaction 450251353052676229 commit failed because txn record has been changed by other transactions SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):
8. DB::ICnchBGThread::run() @ 0x2029b2b1 in /opt/byconity/bin/clickhouse
```
Is this something to be concerned about or just a race condition? 
### The result you expected
No errors
### How to Reproduce

We have CnchMergeTree tables and just letting the server run

### Version
0.4.0

**Comment by wuwenw** [comment]
Hi, can you provide more details about the reproduce step? And does this exception keep popping up?

**Comment by zeromem** [comment]
hi just want to confirm the version, is it 0.4.0 or 0.4.1?

**Comment by ozcelgozde** [comment]
Hi @zeromem, I also tested with v0.4.1 to make sure and it gives me the same error. 
@wuwenw I do nothing special to replicate, just create around 3K CnchMergeTree tables. They dont even have data in them. And then I observe after a while these errors start to occur.

**Comment by ozcelgozde** [comment]
Looking through fdb metrics, I see the errors coincides with transaction conflict spikes: 
![Screenshot 2024-06-10 at 10 26 45](https://github.com/ByConity/ByConity/assets/90635824/b383c966-833d-45e3-a888-fb0400457efc)

**Comment by ozcelgozde** [comment]
Started observing this as well: 
```
2024.06.10 09:35:49.713856 [ 107 ] {} <Error> bool DB::CnchServerManager::renewLease(): Code: 1031, e.displayText() = DB::Exception: FDB error : Operation aborted because the transaction timed out SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x2721e252 in /opt/byconity/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x10776780 in /opt/byconity/bin/clickhouse
2. DB::Catalog::MetastoreFDBImpl::check_fdb_op(int const&) @ 0x200b5aad in /opt/byconity/bin/clickhouse
3. DB::Catalog::MetastoreFDBImpl::batchWrite(DB::Catalog::BatchCommitRequest const&, DB::Catalog::BatchCommitResponse&) @ 0x200b6f7d in /opt/byconity/bin/clickhouse
4. DB::Catalog::MetastoreProxy::updateTopologyMeta(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x200dc9c2 in /opt/byconity/bin/clickhouse
5. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::Catalog::Catalog::updateTopologies(std::__1::list<DB::CnchServerTopology, std::__1::allocator<DB::CnchServerTopology> > const&)::$_142, void ()> >(std::__1::__function::__policy_storage const*) @ 0x2008897f in /opt/byconity/bin/clickhouse
6. DB::Catalog::Catalog::updateTopologies(std::__1::list<DB::CnchServerTopology, std::__1::allocator<DB::CnchServerTopology> > const&) @ 0x2003e9aa in /opt/byconity/bin/clickhouse
7. DB::CnchServerManager::renewLease() @ 0x20bd0e93 in /opt/byconity/bin/clickhouse
8. DB::CnchServerManager::CnchServerManager(std::__1::shared_ptr<DB::Context const>, Poco::Util::AbstractConfiguration const&)::$_2::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::function<bool ()>, unsigned long, std::__1::atomic<unsigned long>&, DB::BackgroundSchedulePoolTaskHolder&) const @ 0x20bd24f6 in /opt/byconity/bin/clickhouse
9. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::CnchServerManager::CnchServerManager(std::__1::shared_ptr<DB::Context const>, Poco::Util::AbstractConfiguration const&)::$_4, void ()> >(std::__1::__function::__policy_storage const*) @ 0x20bd2b16 in /opt/byconity/bin/clickhouse
10. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x2053e8be in /opt/byconity/bin/clickhouse
11. DB::BackgroundSchedulePool::threadFunction() @ 0x20540c67 in /opt/byconity/bin/clickhouse
12. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*, std::__1::shared_ptr<DB::CpuSet>)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*, std::__1::shared_ptr<DB::CpuSet>)::$_1&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x20541477 in /opt/byconity/bin/clickhouse
13. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x107b2cc0 in /opt/byconity/bin/clickhouse
14. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0x107b713a in /opt/byconity/bin/clickhouse
15. start_thread @ 0x7ea7 in /lib/x86_64-linux-gnu/libpthread-2.31.so
16. clone @ 0xfba6f in /lib/x86_64-linux-gnu/libc-2.31.so
 (version **21.8.7.1)**
```

**Comment by smmsmm1988** [comment]
> Started observing this as well:
> 
> ```
> 2024.06.10 09:35:49.713856 [ 107 ] {} <Error> bool DB::CnchServerManager::renewLease(): Code: 1031, e.displayText() = DB::Exception: FDB error : Operation aborted because the transaction timed out SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):
> 
> 0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x2721e252 in /opt/byconity/bin/clickhouse
> 1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x10776780 in /opt/byconity/bin/clickhouse
> 2. DB::Catalog::MetastoreFDBImpl::check_fdb_op(int const&) @ 0x200b5aad in /opt/byconity/bin/clickhouse
> 3. DB::Catalog::MetastoreFDBImpl::batchWrite(DB::Catalog::BatchCommitRequest const&, DB::Catalog::BatchCommitResponse&) @ 0x200b6f7d in /opt/byconity/bin/clickhouse
> 4. DB::Catalog::MetastoreProxy::updateTopologyMeta(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x200dc9c2 in /opt/byconity/bin/clickhouse
> 5. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::Catalog::Catalog::updateTopologies(std::__1::list<DB::CnchServerTopology, std::__1::allocator<DB::CnchServerTopology> > const&)::$_142, void ()> >(std::__1::__function::__policy_storage const*) @ 0x2008897f in /opt/byconity/bin/clickhouse
> 6. DB::Catalog::Catalog::updateTopologies(std::__1::list<DB::CnchServerTopology, std::__1::allocator<DB::CnchServerTopology> > const&) @ 0x2003e9aa in /opt/byconity/bin/clickhouse
> 7. DB::CnchServerManager::renewLease() @ 0x20bd0e93 in /opt/byconity/bin/clickhouse
> 8. DB::CnchServerManager::CnchServerManager(std::__1::shared_ptr<DB::Context const>, Poco::Util::AbstractConfiguration const&)::$_2::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::function<bool ()>, unsigned long, std::__1::atomic<unsigned long>&, DB::BackgroundSchedulePoolTaskHolder&) const @ 0x20bd24f6 in /opt/byconity/bin/clickhouse
> 9. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::CnchServerManager::CnchServerManager(std::__1::shared_ptr<DB::Context const>, Poco::Util::AbstractConfiguration const&)::$_4, void ()> >(std::__1::__function::__policy_storage const*) @ 0x20bd2b16 in /opt/byconity/bin/clickhouse
> 10. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x2053e8be in /opt/byconity/bin/clickhouse
> 11. DB::BackgroundSchedulePool::threadFunction() @ 0x20540c67 in /opt/byconity/bin/clickhouse
> 12. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*, std::__1::shared_ptr<DB::CpuSet>)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*, std::__1::shared_ptr<DB::CpuSet>)::$_1&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x20541477 in /opt/byconity/bin/clickhouse
> 13. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x107b2cc0 in /opt/byconity/bin/clickhouse
> 14. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0x107b713a in /opt/byconity/bin/clickhouse
> 15. start_thread @ 0x7ea7 in /lib/x86_64-linux-gnu/libpthread-2.31.so
> 16. clone @ 0xfba6f in /lib/x86_64-linux-gnu/libc-2.31.so
>  (version **21.8.7.1)**
> ```

hi @ozcelgozde. It seems like the status of fdb is abnormal. Could you please check the log of fdb and find what happened in fdb?

**Comment by ozcelgozde** [comment]
It looks healthy, which logs do you want me to check? 
One thing I notice KV size keeps climbing, started with 80MB. Now its constantly climbing: 
![Screenshot 2024-06-11 at 11 05 31](https://github.com/ByConity/ByConity/assets/90635824/90f4bb8f-e355-4e5d-83fd-1e675c1ca78e)

**Comment by smmsmm1988** [comment]
@ozcelgozde The log of fdb itself, at the time ByConity issues exceptions of "FDB error : Operation aborted because the transaction timed out".
For kv size climbing, is ByConity keeping writing data?

**Comment by ozcelgozde** [comment]
Theres currently no ingestion enabled, so just metadata operations like background gc firing or merge mutate. Let me try to get the logs

**Comment by ozcelgozde** [comment]
I see trace logs in the format of 
```
/var/log/fdb-trace-logs/trace.172.20.53.37.4501.1717850974.XLIQLR.1.58.xml
```
and they dont report anything out of ordinary. /var/fdb/logs directory is empty. 
Can you help with enabling more human readable logs if theres a method you use?

**Comment by smmsmm1988** [comment]
> /var/log/fdb-trace-logs/trace.172.20.53.37.4501.1717850974.XLIQLR.1.58.xml

The xml files under /var/log/fdb-trace-logs are just logs of fdb. They are in specific format so you have to refer to fdb document to understand them: https://github.com/apple/foundationdb/wiki/Understanding-FoundationDB-Log-Files.
BTW, are exceptions "FDB error : Operation aborted because the transaction timed out" still issued by ByConity right now?

**Comment by ozcelgozde** [comment]
Its really rare compared to first error I reported.  
```
2024.06.05 07:30:07.301218 [ 1462 ] {} <Error> virtual void DB::CnchMergeMutateThread::runImpl(): Code: 11003, e.displayText() = DB::Exception: Transaction 450251353262915843 commit failed because txn record has been changed by other transactions SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x2747d4b2 in /opt/byconity/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x10959fe0 in /opt/byconity/bin/clickhouse
2. DB::CnchServerTransaction::commit() @ 0x2001829c in /opt/byconity/bin/clickhouse
3. DB::CnchServerTransaction::commitV2() @ 0x20014ecb in /opt/byconity/bin/clickhouse
4. DB::CnchMergeMutateThread::removeLockedPartition(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x201af22b in /opt/byconity/bin/clickhouse
5. DB::CnchMergeMutateThread::trySelectPartsToMerge(std::__1::shared_ptr<DB::IStorage>&, DB::StorageCnchMergeTree&, DB::MergeSelectionMetrics&) @ 0x201aaa45 in /opt/byconity/bin/clickhouse
6. DB::CnchMergeMutateThread::tryMergeParts(std::__1::shared_ptr<DB::IStorage>&, DB::StorageCnchMergeTree&) @ 0x201a9ed8 in /opt/byconity/bin/clickhouse
7. DB::CnchMergeMutateThread::runImpl() @ 0x201a6c74 in /opt/byconity/bin/clickhouse
2024.06.05 07:30:07.301821 [ 575 ] {} <Error> virtual void DB::CnchMergeMutateThread::runImpl(): Code: 11003, e.displayText() = DB::Exception: Transaction 450251353052676229 commit failed because txn record has been changed by other transactions SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):
8. DB::ICnchBGThread::run() @ 0x2029b2b1 in /opt/byconity/bin/clickhouse
```
Also no ingestion is enabled to cluster but FDB KV usage keeps climbing unreasonably. Started with 70MB now its: 
![Screenshot 2024-06-12 at 15 36 16](https://github.com/ByConity/ByConity/assets/90635824/3f0218a8-2fcb-4de4-914d-c7c2ad5262a0)

**Comment by zeromem** [comment]
@ozcelgozde hi, `Transaction 450251353262915843 commit failed because txn record has been changed by other transactions` could you try to search the txn id `450251353262915843` in all servers and workers? the txn is created by mergemutate thread and so it should be committed by mergemutate thread. but now seems some other thread break this, or  the stat of kv entry is broken (that's why we want to check fdb state)

**Comment by smmsmm1988** [comment]
> 2024.06.05 07:30:07

so does the exception only occur at the time of 2024.06.05 07:30:07? Does it appear again in recent days?

**Comment by ozcelgozde** [comment]
> > 2024.06.05 07:30:07
> 
> so does the exception only occur at the time of 2024.06.05 07:30:07? Does it appear again in recent days?

No it happens all the time

**Comment by smmsmm1988** [comment]
> > > 2024.06.05 07:30:07
> > 
> > 
> > so does the exception only occur at the time of 2024.06.05 07:30:07? Does it appear again in recent days?
> 
> No it happens all the time, every hour or so thousands of them

@ozcelgozde does the same exception still occur for now? If so, could you do as what @zeromem has presented?

**Comment by serenallttyy** [comment]
hi, I am operation from ByConity team. I noticed that you have asked some questions about ByConity. I would like to ask about the progress of Edge Delta. Has it put into production on ByConity? Thank you.

**Comment by kevinthfang** [comment]
@ozcelgozde Do you still have this issue?

**Comment by ozcelgozde** [comment]
yeah @kevinthfang it was due to garbage collector not catching up to transition count, increasing frequency solved it thanks

**Comment by smmsmm1988** [comment]
> yeah @kevinthfang it was due to garbage collector not catching up to transition count, increasing frequency solved it thanks

hi @ozcelgozde, would you like to share the frequency parameter you adjusted?

**Comment by ozcelgozde** [comment]
@smmsmm1988 
I modified  TXN_GC interval: 600000 -> 60000 from below config and also we implemented a more aggressive txn gc mechanism like in this [PR](https://github.com/ByConity/ByConity/pull/1781)
```
daemon_jobs:
    job:
      - name: PART_GC
        interval: 10000
      - name: PART_MERGE
        interval: 10000
      - name: CONSUMER
        interval: 10000
      - name: GLOBAL_GC
        interval: 5000
      - name: TXN_GC
        interval: 600000
```
