### ISSUE TITLE
查询的时候提示Table ods.xxx_450405057856536813 already exists

### ISSUE THREAD

**Issue by xinip** [ByConity/ByConity#1697]
查询的时候提示Table ods.xxx_450405057856536813 already exists

create table:

CREATE TABLE ods.xxx
(
    `dt` String,
    `agent_host_name` String,
    `log_file_path` String,
    `log_file_offset` String,
    `record_date` String,
    `dbname` String,
    `roleid` String,
    `actiontype` String,
    `client_type` String
)
ENGINE = CnchMergeTree
PARTITION BY dt
ORDER BY (actiontype, client_type, dbname)

select SQL:

SELECT c.actiontype,count(1) cnt
from ods.xxx c
where c.dt='2024-06-06'
GROUP by c.actiontype
order by cnt desc

**Comment by kevinthfang** [comment]
把这个setting关掉再试试看enable_optimizer_fallback，设置成0。这个报错一般不是真实错误原因

**Comment by xinip** [comment]
> 把这个setting关掉再试试看enable_optimizer_fallback，设置成0。这个报错一般不是真实错误原因
好像没效果，这个报错太频繁了，我们部署了2个Server,2个worker-write,12个woker,

jdbc URL:jdbc:clickhouse://172.24.150.91:8123/xxx?load_balancing_policy=random&health_check_interval=5000&failover=2&socket_timeout=600000&enable_optimizer_fallback=0


java.sql.SQLException: Code: 57, e.displayText() = DB::Exception: DB::Exception: Table xxx.yyy_450432705315995650 already exists. SQLSTATE: 42P07.: While executing Remote SQLSTATE: 42P07 (version 21.8.7.1)
, server ClickHouseNode [uri=http://172.24.150.91:8123/xxx, options={socket_timeout=600000,enable_optimizer_fallback=0}]@-1319829428
at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:85)
at com.clickhouse.jdbc.SqlExceptionUtils.create(SqlExceptionUtils.java:31)

**Comment by kevinthfang** [comment]
再把优化器关掉试试，enable_optimizer=0

**Comment by xinip** [comment]
通过worker日志以及结合历史操作，仅仅是因为建立只读账号引起的bug，通过更换为xml里面配置账号解决了，
建立账号的SQL如下：

CREATE USER yyyyyy IDENTIFIED WITH sha256_password BY 'xxxxxxxxxxxxx' SETTINGS PROFILE 'default'；

GRANT SELECT ON *.* TO yyyyyy;

byconity-worker报错日志如下：
2024.06.15 01:00:54.517314 [ 274039 ] {} <Fatal> BaseDaemon: ########################################
2024.06.15 01:00:54.517347 [ 274039 ] {} <Fatal> BaseDaemon: (version 21.8.7.1 scm1.0.0.0, build id: D3907A323DB52BD9) (from thread 260498) (no query) Received signal Segmentation fault (11)
2024.06.15 01:00:54.517363 [ 274039 ] {} <Fatal> BaseDaemon: Address: 0x108 Access: read. Address not mapped to object.
2024.06.15 01:00:54.517372 [ 274039 ] {} <Fatal> BaseDaemon: Stack trace: 0x1b23d686 0x1b1e2050 0x1b1e6c49 0x1b241fae 0x1b24c0b4 0x1b242299 0x1b241fdf 0x1b268f86 0x1b241fdf 0x1b88ffdc 0x1b890761 0x1c3df9c7 0x1dc66e2f 0x1dc5de4e 0x1dd8e24d 0x1dc2baad
2024.06.15 01:00:54.531524 [ 274039 ] {} <Fatal> BaseDaemon: 3. DB::GrantedRoles::findGranted(DB::RolesOrUsersSet const&) const @ 0x1b23d686 in /usr/bin/clickhouse
2024.06.15 01:00:54.547759 [ 274039 ] {} <Fatal> BaseDaemon: 4. DB::ContextAccess::setUser(std::__1::shared_ptr<DB::User const> const&) const @ 0x1b1e2050 in /usr/bin/clickhouse
2024.06.15 01:00:54.560490 [ 274039 ] {} <Fatal> BaseDaemon: 5. void std::__1::__function::__policy_invoker<void (StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&, std::__1::shared_ptr<DB::IAccessEntity const> const&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::ContextAccess::ContextAccess(DB::AccessControlManager const&, DB::ContextAccessParams const&)::$_0, void (StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&, std::__1::shared_ptr<DB::IAccessEntity const> const&)> >(std::__1::__function::__policy_storage const*, StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&, std::__1::shared_ptr<DB::IAccessEntity const> const&) @ 0x1b1e6c49 in /usr/bin/clickhouse
2024.06.15 01:00:54.572590 [ 274039 ] {} <Fatal> BaseDaemon: 6. DB::IAccessStorage::notify(std::__1::vector<std::__1::tuple<std::__1::function<void (StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&, std::__1::shared_ptr<DB::IAccessEntity const> const&)>, StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>, std::__1::shared_ptr<DB::IAccessEntity const> >, std::__1::allocator<std::__1::tuple<std::__1::function<void (StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&, std::__1::shared_ptr<DB::IAccessEntity const> const&)>, StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>, std::__1::shared_ptr<DB::IAccessEntity const> > > > const&) @ 0x1b241fae in /usr/bin/clickhouse
2024.06.15 01:00:54.589658 [ 274039 ] {} <Fatal> BaseDaemon: 7. DB::KVAccessStorage::findImpl(DB::IAccessEntity::Type, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x1b24c0b4 in /usr/bin/clickhouse
2024.06.15 01:00:54.604622 [ 274039 ] {} <Fatal> BaseDaemon: 8. DB::IAccessStorage::loginImpl(DB::Credentials const&, Poco::Net::IPAddress const&, DB::ExternalAuthenticators const&) const @ 0x1b242299 in /usr/bin/clickhouse
2024.06.15 01:00:54.619431 [ 274039 ] {} <Fatal> BaseDaemon: 9. DB::IAccessStorage::login(DB::Credentials const&, Poco::Net::IPAddress const&, DB::ExternalAuthenticators const&, bool) const @ 0x1b241fdf in /usr/bin/clickhouse
2024.06.15 01:00:54.634081 [ 274039 ] {} <Fatal> BaseDaemon: 10. DB::MultipleAccessStorage::loginImpl(DB::Credentials const&, Poco::Net::IPAddress const&, DB::ExternalAuthenticators const&) const @ 0x1b268f86 in /usr/bin/clickhouse
2024.06.15 01:00:54.646599 [ 274039 ] {} <Fatal> BaseDaemon: 11. DB::IAccessStorage::login(DB::Credentials const&, Poco::Net::IPAddress const&, DB::ExternalAuthenticators const&, bool) const @ 0x1b241fdf in /usr/bin/clickhouse
2024.06.15 01:00:54.661402 [ 274039 ] {} <Fatal> BaseDaemon: 12. DB::Context::setUser(DB::Credentials const&, Poco::Net::SocketAddress const&) @ 0x1b88ffdc in /usr/bin/clickhouse
2024.06.15 01:00:54.672608 [ 274039 ] {} <Fatal> BaseDaemon: 13. DB::Context::setUser(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Net::SocketAddress const&) @ 0x1b890761 in /usr/bin/clickhouse
2024.06.15 01:00:54.684047 [ 274039 ] {} <Fatal> BaseDaemon: 14. DB::PlanSegmentManagerRpcService::submitPlanSegment(google::protobuf::RpcController*, DB::Protos::SubmitPlanSegmentRequest const*, DB::Protos::ExecutePlanSegmentResponse*, google::protobuf::Closure*) @ 0x1c3df9c7 in /usr/bin/clickhouse
2024.06.15 01:00:54.926233 [ 274039 ] {} <Fatal> BaseDaemon: 15. /build/build_docker/../contrib/incubator-brpc/src/brpc/policy/baidu_rpc_protocol.cpp:0: brpc::policy::ProcessRpcRequest(brpc::InputMessageBase*) @ 0x1dc66e2f in /usr/bin/clickhouse
2024.06.15 01:00:54.942821 [ 274039 ] {} <Fatal> BaseDaemon: 16. /build/build_docker/../contrib/incubator-brpc/src/brpc/input_messenger.cpp:386: brpc::InputMessenger::OnNewMessages(brpc::Socket*) @ 0x1dc5de4e in /usr/bin/clickhouse
2024.06.15 01:00:55.020641 [ 274039 ] {} <Fatal> BaseDaemon: 17.1. inlined from /build/build_docker/../contrib/libcxx/include/memory:1655: std::__1::unique_ptr<brpc::Socket, brpc::SocketDeleter>::reset(brpc::Socket*)
2024.06.15 01:00:55.020678 [ 274039 ] {} <Fatal> BaseDaemon: 17.2. inlined from /build/build_docker/../contrib/libcxx/include/memory:1612: ~unique_ptr
2024.06.15 01:00:55.020687 [ 274039 ] {} <Fatal> BaseDaemon: 17. /build/build_docker/../contrib/incubator-brpc/src/brpc/socket.cpp:1099: brpc::Socket::ProcessEvent(void*) @ 0x1dd8e24d in /usr/bin/clickhouse
2024.06.15 01:00:55.039181 [ 274039 ] {} <Fatal> BaseDaemon: 18. /build/build_docker/../contrib/incubator-brpc/src/bthread/task_group.cpp:304: bthread::TaskGroup::task_runner(long) @ 0x1dc2baad in /usr/bin/clickhouse
2024.06.15 01:00:55.270091 [ 274039 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: 83B3FB6898AA4ACDDD7766EEABD3610E. There is no information about the reference checksum.
2024.06.15 01:00:57.479297 [ 260582 ] {} <Error> BrpcRemoteBroadcastReceiver: Broadcast BrpcReciver[3_2_6_0_172.24.150.91:8124]:ExchangeDataKey[450464174284734480_0_6_18446744073709551615] finished and changed to SEND_CANCELLED with err:'StreamHandler::on_finished called'
2024.06.15 01:00:57.479310 [ 260543 ] {} <Error> BrpcRemoteBroadcastReceiver: Broadcast BrpcReciver[5_1_6_3_172.24.150.91:8124]:ExchangeDataKey[450464174284734480_3_6_18446744073709551615] finished and changed to SEND_CANCELLED with err:'StreamHandler::on_finished called'
2024.06.15 01:00:57.479400 [ 260578 ] {} <Error> BrpcRemoteBroadcastReceiver: Broadcast BrpcReciver[5_1_6_3_172.24.150.91:8124]:ExchangeDataKey[450464174284734480_3_6_18446744073709551615] finished and changed to SEND_CANCELLED with err:'StreamHandler::on_finished called'
2024.06.15 01:00:57.479414 [ 265464 ] {1298856d-4f93-4977-8e10-52ee77e24dd2_4} (450464174284734480) <Error> IBroadcastSender: DB::BroadcastStatus DB::IBroadcastSender::send(DB::Chunk): Code: 2010, e.displayText() = DB::Exception: Interrput waitBecomeRealSender for ExchangeDataKey[450464174284734480_1_2_18446744073709551615] SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x21e476f2 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xea6cf40 in /usr/bin/clickhouse
2. DB::BroadcastSenderProxy::waitBecomeRealSender(unsigned int) @ 0x1d1a2bed in /usr/bin/clickhouse
3. DB::BroadcastSenderProxy::sendImpl(DB::Chunk) @ 0x1d1a288f in /usr/bin/clickhouse
4. DB::IBroadcastSender::send(DB::Chunk) @ 0x1d1a8506 in /usr/bin/clickhouse
5. DB::ExchangeUtils::sendAndCheckReturnStatus(DB::IBroadcastSender&, DB::Chunk) @ 0x1d194e63 in /usr/bin/clickhouse
6. DB::ExchangeBufferedSender::flush(bool, std::__1::shared_ptr<DB::ChunkInfo const> const&) @ 0x1d19dfb0 in /usr/bin/clickhouse
7. DB::MultiPartitionExchangeSink::consume(DB::Chunk) @ 0x1d19bf28 in /usr/bin/clickhouse
8. DB::ISink::work() @ 0x1cfa33e3 in /usr/bin/clickhouse
9. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0, void ()> >(std::__1::__function::__policy_storage const*) @ 0x1cfdf0a1 in /usr/bin/clickhouse
10. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0x1cfdd117 in /usr/bin/clickhouse
11. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long)::$_5>(DB::PipelineExecutor::executeImpl(unsigned long)::$_5&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x1cfdf625 in /usr/bin/clickhouse
12. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xeaacee0 in /usr/bin/clickhouse
13. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0xeab135a in /usr/bin/clickhouse
14. ? @ 0x94ac3 in /usr/lib/x86_64-linux-gnu/libc.so.6
15. ? @ 0x126850 in /usr/lib/x86_64-linux-gnu/libc.so.6

**Comment by kevinthfang** [comment]
好的，多谢反馈
