### ISSUE TITLE
The higher version of the com.clickhouse driver package does not support JDBC connection through Byconity.

### ISSUE THREAD

**Issue by xiongbl526** [ByConity/ByConity#1698]
(you don't have to strictly follow this form)

## Enhancement
<dependency>
      <groupId>com.clickhouse</groupId>
      <artifactId>clickhouse-jdbc</artifactId>
      <version>0.4.6</version>
    </dependency>
The com.clickhouse driver package version 0.3.2-patch11 supports JDBC connection through Byconity. However, the higher versions of the driver package do not support it.

**Comment by xiongbl526** [comment]
com.clickhouse clickhouse-jdbc 0.3.2-patch版本的依赖包 连接byconity,使用preparestatement 查表列数据会返回空，而原生的clickhouse会返回数据
![Uploading f3cd950d126980d7d15674aa09984e3a.png…]()

**Comment by xiongbl526** [comment]
package: com.clickhouse.jdbc.internal.ClickHouseConnectionImpl

protected List<ClickHouseColumn> getTableColumns(String dbName, String tableName, String columns)
            throws SQLException {
        if (tableName == null || columns == null) {
            throw SqlExceptionUtils.clientError("Failed to extract table and columns from the query");
        }

        if (columns.isEmpty()) {
            columns = "*";
        } else {
            columns = columns.substring(1); // remove the leading bracket
        }
        StringBuilder builder = new StringBuilder();
        builder.append("SELECT ").append(columns).append(" FROM ");
        if (!ClickHouseChecker.isNullOrEmpty(dbName)) {
            builder.append('`').append(ClickHouseUtils.escape(dbName, '`')).append('`').append('.');
        }
        builder.append('`').append(ClickHouseUtils.escape(tableName, '`')).append('`').append(" WHERE 0");
        List<ClickHouseColumn> list;
        try (ClickHouseResponse resp = clientRequest.copy().format(ClickHouseFormat.RowBinaryWithNamesAndTypes)
                .option(ClickHouseClientOption.RENAME_RESPONSE_COLUMN, ClickHouseRenameMethod.NONE)
                .query(builder.toString()).executeAndWait()) {
            list = resp.getColumns();
        } catch (Exception e) {
            throw SqlExceptionUtils.handle(e);
        }
        return list;
    }

**Comment by nudles** [comment]
@xiongbl526 do you mean there are two issues ?
1. clickhouse-jdbc 0.3.2-patch returns empty for preparestatement
2. clickhouse-jdbc 0.4.6 does not work

for the second issue, can you share the error messages or other details (byconity version, and the connection settings)?

**Comment by xiongbl526** [comment]
> @xiongbl526 do you mean there are two issues ?
> 
> 1. clickhouse-jdbc 0.3.2-patch returns empty for preparestatement
> 2. clickhouse-jdbc 0.4.6 does not work
> 
> for the second issue, can you share the error messages or other details (byconity version, and the connection settings)?

I previously deployed using the latest version of Byconity. Yesterday, I resolved the issue by redeploying with the Byconity 0.3.2 version image.

**Comment by nudles** [comment]
@xiongbl526 would appreciate if you can share the error messages from the latest Byconity version. Then we can investigate and fix it.

**Comment by xiongbl526** [comment]
> try (ClickHouseResponse resp = clientRequest.copy().format(ClickHouseFormat.RowBinaryWithNamesAndTypes)
>             .option(ClickHouseClientOption.RENAME_RESPONSE_COLUMN, ClickHouseRenameMethod.NONE)
>             .query(builder.toString()).executeAndWait()) {
>         list = resp.getColumns();
Thank you for your prompt reply.
no other error messages；
When using the latest version of Byconity, the code returns empty. However, when using native ClickHouse, this code will return column information of the table.

**Comment by xiongbl526** [comment]
> The root cause is that the jdbc client sends http requests to byconity server with 'compress=1'. byconity server handles the requests with a CompressedWriteBuffer to compress the responses. However, it missed to call the finalize() method explicitly. When CompressedWriteBuffer is destructed, finalize() is called. But it is too late as the response is already sent. As a result, the jdbc receives incomplete response.

Thank you for your timely response.
How to avoid this issue, Byconity version 0.3.2 doesn't have this problem, but version 0.4.1 does.

**Comment by xiongbl526** [comment]
测试byconity1.0.0版本 执行insert into values(?,?,?) 会报错 `Connection conn = null;
        PreparedStatement psmt = null;
        try {
            conn = dataSource.getConnection();
            psmt = conn.prepareStatement("insert into group_accept_user(id,group_id,user_id) values(?,?,?)");
            for (Long userId : userList) {
                psmt.setInt(1, id);
                psmt.setInt(2, groupId);
                psmt.setLong(3, userId);
                psmt.addBatch();
            }
            psmt.executeBatch();
        } finally {
            SQLHelper.close(null, psmt, conn);
        }`
