### ISSUE TITLE
Setup workflow to trigger website build and deployment on docs change

### ISSUE THREAD

**Issue by pswai** [ByConity/ByConity#170]
Following up https://github.com/ByConity/ByConity/pull/169

Our documentations are stored in this repository, however the website source code is stored at https://github.com/ByConity/byconity.github.io. In order to make sure the docs in the deployed website is up-to-date, we need to setup a workflow to automatically do this.

Suggested procedure:
1. Whenever any documentation file is changed in the `master` branch, trigger a pipeline to copy the changes to https://github.com/ByConity/byconity.github.io, `main` branch.
2. https://github.com/ByConity/byconity.github.io will then trigger a build and deployment with the latest content.
3. We can allow this action to push to the `main` branch directly without PR.

File mapping:
```
Format:
ByConity path --> byconity.github.io path
*********

/docs/en/*  --> /docs/*
/docs/zh-cn/* --> /i18n/zh-cn/docusaurus-plugin-content-blog/current
```

@WillemJiang may I have your help to assist on this?

**Comment by WillemJiang** [comment]
@pswai I don't think it's good practices to push change to main branch without PR review， it's important for team to share the knowledge by reviewing the PR.  
Current we can run the website deploy script menually to workaround the multiple repo notification issue.

**Comment by pswai** [comment]
> @pswai I don't think it's good practices to push change to main branch without PR review， it's important for team to share the knowledge by reviewing the PR. Current we can run the website deploy script menually to workaround the multiple repo notification issue.

Sorry for not being clear. The idea is like this:
1. Changes needed to certain docs.
2. [ByConity repo] Create a branch, make changes, submit a PR.
3. [ByConity repo] PR reviewed, merge to `master` branch.
4. [ByConity repo] Detected `/docs/*` changed, push to [byconity.github.io repo] `main` branch.
5. [byconity.github.io repo] Detected changes, build and deploy.

The changes to the docs should be reviewed already in step 3, then step 4 shouldn't required another round of PR. Let me know if you think otherwise.

**Comment by WillemJiang** [comment]
OK. I see. 
We can make the workflow simple by trigger step5 menually this time.   
When building the website, we need to checkout the ByConity repo at same time and copy the /docs/* into the website code.

**Comment by WillemJiang** [comment]
If we move the docs from ByConity repo to the website,  we don't need to keep monitor the changes of /docs/*.
Here is [an example](https://github.com/apache/pulsar/issues/19064) that Plusar move the website related docs into separated repo.
When engineer add a new feature to ByConity repo, we need to remind him to update the website documentation in the PR review comments.

**Comment by pswai** [comment]
> If we move the docs from ByConity repo to the website, we don't need to keep monitor the changes of /docs/*. Here is [an example](https://github.com/apache/pulsar/issues/19064) that Plusar move the website related docs into separated repo. When engineer add a new feature to ByConity repo, we need to remind him to update the website documentation in the PR review comments.

Right, probably can add a bot to remind about updating the docs
