### ISSUE TITLE
Upgrading directly from version 0.2.2 to version 0.4.1 will result in missing data in the query

### ISSUE THREAD

**Issue by skyoct** [ByConity/ByConity#1701]
### Briefly describe the bug
After the upgrade is completed, the number of query data entries is only about 1/8 of the normal number. However, after rolling back to the previous version, the query returns to normal.

### Version
0.2.2->0.4.1

**Comment by jenrryyou** [comment]
Could you provide DDL for your tables and your queries  and query settings?

**Comment by skyoct** [comment]
@jenrryyou It has been sent to your email
