### ISSUE TITLE
hive外表，进行count超时，多次count后结果不对

### ISSUE THREAD

**Issue by ixnzh** [ByConity/ByConity#1704]
在hive上建了外表，进行count超时

多次执行count返回结果为7000w，实际数据13亿

**Comment by kevinthfang** [comment]
@jenrryyou 跟另外一个查询结果变少的问题是不是类似的？

**Comment by jenrryyou** [comment]
select * from system.settings where name = 'optimize_trivial_count_query' 看下optimize_trivial_count_query配置

**Comment by jenrryyou** [comment]
另外内表有这个问题吗？

**Comment by jenrryyou** [comment]
应该是enable_expand_distinct_optimization有点问题，需要关闭，这周会fix

**Comment by superhail** [comment]
已经fix
