### ISSUE TITLE
表开启了自动预加载，merge后没有自动预加载

### ISSUE THREAD

**Issue by bright-zy** [ByConity/ByConity#1715]
(you don't have to strictly follow this form)

### Briefly describe the bug
表开启了自动预加载，merge后没有自动预加载
### The result you expected
merge后，能自动进行数据预加载
### How to Reproduce
进行merge
<img width="268" alt="image" src="https://github.com/ByConity/ByConity/assets/102500454/05c15c1e-4897-4cd1-b337-c67fc2904832">
5分钟后查询
<img width="822" alt="image" src="https://github.com/ByConity/ByConity/assets/102500454/dc354b56-5894-417f-bec9-b3408a898a7a">
从日志中看，是从hdfs拉取的数据
<img width="1211" alt="image" src="https://github.com/ByConity/ByConity/assets/102500454/9e836b48-b5ed-4407-b988-86f413b63ae2">

### Version
k8s部署 0.4.1版本

**Comment by foreverneverer** [comment]
1. 从cnch(server, system.server_part_log)查看发生merge的part name
2. 以上述part name过滤查看cnch('{vw-name}', system.part_log)确定是否发生了preload以及发生的时间

**Comment by bright-zy** [comment]
> 1. 从cnch(server, system.server_part_log)查看发生merge的part name
> 2. 以上述part name过滤查看cnch('{vw-name}', system.part_log)确定是否发生了preload以及发生的时间
1、server 查询
<img width="1402" alt="image" src="https://github.com/ByConity/ByConity/assets/102500454/78b45923-7587-4539-ba8e-dc6d8e225af8">
2、vm 查询
<img width="1071" alt="image" src="https://github.com/ByConity/ByConity/assets/102500454/f9442812-95b8-436e-8e0a-f1a93959beb1">

merge后，vm中确实没有预加载

**Comment by bright-zy** [comment]
> 1. 参考这个确认各个参数参数正常 https://byconity.github.io/docs/query-optimization/query-optimization-with-cache-preload#how-to-enable-and-configure
> 2. 你的worker只有一个节点吗？正常要在server节点上用cnch('vw-name', system.part_log)来查

1、确认配置是正常的
2、3个worker节点
3、历史数据通过insert override 进行了回刷，回刷后的数据进行了merge，然后这部分merge的数据没有自动预加载

**Comment by smmsmm1988** [comment]
> > 1. 参考这个确认各个参数参数正常 https://byconity.github.io/docs/query-optimization/query-optimization-with-cache-preload#how-to-enable-and-configure
> > 2. 你的worker只有一个节点吗？正常要在server节点上用cnch('vw-name', system.part_log)来查
> 
> 1、确认配置是正常的 2、3个worker节点 3、历史数据通过insert override 进行了回刷，回刷后的数据进行了merge，然后这部分merge的数据没有自动预加载

@bright-zy 如果不加override这个关键字，insert后的数据进行merge后，merge的数据会自动预加载吗

**Comment by foreverneverer** [comment]
1. 三个worker节点就不应该cnch('vw-name', system.part_log)来查，原因是preload可能分布在任何节点，你在其中一个worker是查不到另一个worker发生的preload任务
2. 理论上只要开启就一定会发生preload，确认所有woker存在preload任务但是仍然发生miss:
 - 对比preload发生的时间点和查询的时间点是否滞后，即查询时刻，preload任务并没有完成预加载从而导致miss
 - 如果在查询之前完成了预加载，但是仍然miss，在server节点user.xml配置如下参数：<cnch_part_allocation_algorithm>0</cnch_part_allocation_algorithm>

**Comment by bright-zy** [comment]
> > > 1. 参考这个确认各个参数参数正常 https://byconity.github.io/docs/query-optimization/query-optimization-with-cache-preload#how-to-enable-and-configure
> > > 2. 你的worker只有一个节点吗？正常要在server节点上用cnch('vw-name', system.part_log)来查
> > 
> > 
> > 1、确认配置是正常的 2、3个worker节点 3、历史数据通过insert override 进行了回刷，回刷后的数据进行了merge，然后这部分merge的数据没有自动预加载
> 
> @bright-zy 如果不加override这个关键字，insert后的数据进行merge后，merge的数据会自动预加载吗

新插入的数据，merge可以预加载，历史回刷已存在的有问题

**Comment by bright-zy** [comment]
> > > 1. 参考这个确认各个参数参数正常 https://byconity.github.io/docs/query-optimization/query-optimization-with-cache-preload#how-to-enable-and-configure
> > > 2. 你的worker只有一个节点吗？正常要在server节点上用cnch('vw-name', system.part_log)来查
> > 
> > 
> > 1、确认配置是正常的 2、3个worker节点 3、历史数据通过insert override 进行了回刷，回刷后的数据进行了merge，然后这部分merge的数据没有自动预加载
> 
> @bright-zy 如果不加override这个关键字，insert后的数据进行merge后，merge的数据会自动预加载吗
新插入的数据是可以自动预加载的

**Comment by smmsmm1988** [comment]
> 1. 三个worker节点就应该cnch('vw-name', system.part_log)来查，原因是preload可能分布在任何节点，你在其中一个worker是查不到另一个worker发生的preload任务
> 2. 理论上只要开启就一定会发生preload，确认所有woker存在preload任务但是仍然发生miss:
> 
> * 对比preload发生的时间点和查询的时间点是否滞后，即查询时刻，preload任务并没有完成预加载从而导致miss
> * 如果在查询之前完成了预加载，但是仍然miss，在server节点user.xml配置如下参数：<cnch_part_allocation_algorithm>0</cnch_part_allocation_algorithm>

@bright-zy 按照这个试一下呢？

**Comment by bright-zy** [comment]
> * <cnch_part_allocation_algorithm>0</cnch_part_allocation_algorithm>
配置后，观察可以预加载
