### ISSUE TITLE
列的TTL和表的TTL，数据未能按预期清除

### ISSUE THREAD

**Issue by justinxiongbin** [ByConity/ByConity#1722]
(you don't have to strictly follow this form)

## Question
1、建表语句
CREATE TABLE recharge.test
(
    `applytime` DateTime ,
    `orderstate` Int8 ,
    `remark` String TTL applytime + toIntervalSecond(1)  ,
    `updatetime` DateTime TTL applytime + toIntervalSecond(1)
)
    ENGINE = CnchMergeTree
        PARTITION BY toYYYYMMDDhhmmss(applytime)
        PRIMARY KEY ( applytime, orderstate)
        ORDER BY (applytime, orderstate)
        TTL applytime + toIntervalMinute(1)
SETTINGS index_granularity = 8192
COMMENT '测试表';

2、插入一些数据
<img width="756" alt="image" src="https://github.com/ByConity/ByConity/assets/39757839/c9ee4030-2226-458f-94cc-6a890fbf605b">

3、分区信息
<img width="802" alt="image" src="https://github.com/ByConity/ByConity/assets/39757839/f2ec1466-1417-44ef-9114-0b83bc1fc22b">

4、过了很久去查询，满足TTL的列，和满足TTL的行记录，都没有被清除，是我的用法哪里不对吗？

**Comment by zeromem** [comment]
Hi @justinxiongbin ，Byconity 暂不支持行/列级 TTL，计划在下个大版本支持。

另外，你的表 schema 里`PARTITION BY toYYYYMMDDhhmmss(applytime)` 这个用法不太合理。一般 PARTITION 最多到 hour 粒度，通常是day 粒度即可。

同时，Byconity 目前支持 partition 级别的 TTL 淘汰数据。比如 partition 定义为 `PARTITION BY toDate(applytime)`， TTL 定义为 `TTL toDate(applytime) + INTERVAL xxx DAY` 即可实现 xxx 天的 partition 级别 ttl 淘汰数据。

列 ttl 无法像上面说的 partition 级别淘汰。

**Comment by justinxiongbin** [comment]
@zeromem 感谢老师火箭班的回复~
请问一下，例如如下DDL语句，partition级别的淘汰，ByConity会在什么时候执行TTL淘汰？哪个参数可以可以看到TTL淘汰时间，是否可以修改？
CREATE TABLE recharge.test
(
    `applytime` DateTime ,
    `orderstate` Int8 ,
    `remark` String ,
    `updatetime` DateTime
)
    ENGINE = CnchMergeTree
        PARTITION BY toYYYYMMDD(applytime)
        PRIMARY KEY (applytime, orderstate)
        ORDER BY (applytime, orderstate)
        TTL toDate(applytime) + interval 1 day
SETTINGS index_granularity = 8192
COMMENT '测试表';

**Comment by zeromem** [comment]
> 1、partition级别的淘汰，ByConity会在什么时候执行TTL淘汰？哪个参数可以可以看到TTL淘汰时间，是否可以修改？

每个表都有一个专门的 GC 后台线程负责 part 的回收。GC 线程里有一个特殊的步骤就是做 partition 级别的 part 回收。如果你的 partition 定义为 `toDate(applytime)`, TTL 为`toDate(applytime) + INTERVAL 1 DAY`  （需要完全匹配 `toDate(applytime)`），GC 通过计算 partition id 就可以知道这个 partition 过期了（而不需要每个 part 做行级别的淘汰）。

> 2、如果我的分区是PARTITION BY toYYYYM(applytime)，按月分区，那我的TTL淘汰策略是不是也必须改成TTL toMonth(applytime) + interval 1 mouth ?

是的，PARTITION BY 和 TTL 的前半部分需要完全匹配才可以使用 partition 级别的数据淘汰。
另外，PARTITION BY 一般也建议用 Date 类型，不用 toYYYYMMDD 函数。toMonth 函数只能取到月份，需要用 toStartOfMonth 取到完整的当月 date 值。 比如 `PARTITION BY toStartOfMonth(applytime)` ... `TTL toStartOfMonth(applytime) + INTERVAL 1 MONTH`

**Comment by justinxiongbin** [comment]
@zeromem 感谢老师的解答~

按照您的建议，建议直接使用Date类型的字段，不知道是基于性能的考虑呢？还是有其他理由
例如如下两种情况，是否都可以在生产中使用，他们俩的性能或者其他方面，会有很大的差异吗？

情况1：字段  `applytime` DateTime ,    `PARTITION BY toDate(applytime)  TTL toDate(applytime) + interval 1 day`  
情况2：字段  `applydate` Date,    `PARTITION BY applydate  TTL applydate + interval 1 day`

**Comment by smmsmm1988** [comment]
> @zeromem 感谢老师的解答~
> 
> 按照您的建议，建议直接使用Date类型的字段，不知道是基于性能的考虑呢？还是有其他理由 例如如下两种情况，是否都可以在生产中使用，他们俩的性能或者其他方面，会有很大的差异吗？
> 
> 情况1：字段 `applytime` DateTime , `PARTITION BY toDate(applytime) TTL toDate(applytime) + interval 1 day` 情况2：字段 `applydate` Date, `PARTITION BY applydate TTL applydate + interval 1 day`

@justinxiongbin 使用date类型字段，以天为单位来管理part和ttl，可以保证part数目不会太多/太少，对ttl性能、merge性能、查询性能都比较友好。另外，你说的情况1和情况2，是等价的
