### ISSUE TITLE
docker部署安装问题

### ISSUE THREAD

**Issue by Granish** [ByConity/ByConity#1723]
docker-compose在拉取依赖的时候，拉取foundationdb/foundationdb这个镜像是总是出现网络拒绝请求问题
![image](https://github.com/ByConity/ByConity/assets/108119120/3af19906-1523-4658-a32b-18a759f0a66a)
有没有其他jing'x镜像源或者其他解决办法？谢谢！

**Comment by fky2015** [comment]
可以考虑使用 Cloudflare Workers 自建代理（详情请自行搜索教程）；或者使用其他代理服务。

**Comment by fky2015** [comment]
@kevinthfang 因为跟 ByConity 本身不太相关，且已经提供了可能的解决方法。或许我们可以关闭这个 Issue 了？
