### ISSUE TITLE
 Byconity 是否支持java udf?

### ISSUE THREAD

**Issue by xiongbl526** [ByConity/ByConity#1731]
(you don't have to strictly follow this form)

## Question
我们目前使用的java udf方式是将 java程序jar包上传到Bycontiy部署机器上 然后通过xml配置后  再通过执行system reload functions试udf函数生效,
请问byconity是否支持这种方式的udf 或者有其它使用方式吗

**Comment by Clark0** [comment]
AFAIK ByConity does not support java udf so far

**Comment by xiongbl526** [comment]
> AFAIK ByConity does not support java udf so far
请问是否有roadmap 支持java udf?
