### ISSUE TITLE
It's too slow to query Bucket CnchMergeTree statistics from system.cnch_parts.

### ISSUE THREAD

**Issue by zhaojintaozhao** [ByConity/ByConity#1732]
## Bug Report
It's too slow to query Bucket CnchMergeTree statistics from system.cnch_parts.
### Briefly describe the bug
It's normal to query the statistics of Bucket CnchMergeTree from system.parts. 
It's also normal to query the statistics of Bucket CnchMergeTree from system.cnch_tables.
But it's too slow to query the statistics of Bucket CnchMergeTree from system.cnch_parts, even though there aren't any data in these Bucket CnchMergeTree tables.

### How to Reproduce
1. Create a database to store Bucket CnchMergeTree tables: bucket_database
2.  Create a Bucket CnchMergeTree tables in this database.
```
CREATE TABLE bucket_database.bucket1
(
    `id` Int32,
    `name` String,
    `age` UInt8,
    `age_group` UInt8,
    `timestamp` DateTime
)
ENGINE = CnchMergeTree
PARTITION BY toDate(timestamp)
CLUSTER BY (id, toDate(timestamp)) INTO 10 BUCKETS SPLIT_NUMBER 100
ORDER BY id
```
3. Create more than 60 Bucket CnchMergeTree tables without any data just like step2.
4. Query
It takes 5.8s from system.cnch_parts to query count of Bucket CnchMergeTree tables
```
SELECT database, count(*) FROM system.cnch_parts WHERE database ='bucket_database'  GROUP BY database;
```
If to query other databases count statictics without Bucket CnchMergeTree from system.cnch_parts it cost less than 1s
If to query  Bucket CnchMergeTree  count statictics from system.parts  it cost less than 1s

### Version
0.2.2

### Deployment Mode
This is the deployment node information of my cluster:
```
5 FoundationDB node.
3 tso
3 server
3 resource-manager
1 daemon-manager
2 default-worker
2 write-worker

```

 Does anyone face the similar problem?

**Comment by smmsmm1988** [comment]
@zhaojintaozhao  it seems no relation with bucket. You can use the following steps to get the debug log and check where is slow:
1. set send_logs_level = 'trace';
2. rerun the sql

**Comment by zhaojintaozhao** [comment]
I set the setting: enable_optimizer=true;
This is final pipeline log:
```
2024.07.02 14:57:48.809168 [ ... ] {{uuid}} <Trace> PipelineExecutor[...] : Thread finished. Total time: 5.769855515 sec. Execution time: 0.0 sec. Processing time: 0.0 sec. Wait time: 5.769855515 sec.
2024.07.02 14:57:48.809196 [ ... ] {} <Trace> PlanSegmentExecutor[...] : PlanSegment-1 send status to coordinator successfully, query id-{uuid} status.cpu_....
... ... ...
2024.07.02 14:57:48.808932 [ ... ] {{uuid}} <Trace> PipelineExecutor[...] : Thread finished. Total time: 5.766849031 sec. Execution time: 0.0 sec. Processing time: 0.0 sec. Wait time: 5.766849031 sec.
2024.07.02 14:57:48.809341 [ ... ] {} <Trace> MultiPathReceiver[...] : MultiPathReceiver[2_1_0_0_xxxxxxx:xxx] finished and can't change to status code 90099,  msg MultiPathReceiver destroyed . Current status: -1, msg: MultiPathReceiver[2_1_0_0_xxxxxxx:xxxx] received all data
2024.07.02 14:57:48.809595 [ ... ] {{uuid}} <Debug> PipelineExecutor[...] : Pipeline: digraph
{
  rankdir="LR";
  { node [shape = record]
    n140341784343448[label="{ExchangeSource: MultiPathReceiver[1_0_0_1_xxxxxxx:xxxx](1 jobs, execution time: 5.771358186 sec., preparation time: 0.000010602 sec.) (Finished)}"];
    n140341803717848[label="{Resize(0 jobs, execution time: 0 sec., preparation time: 0.00001156 sec.) (Finished)}"];
    n140344941114776[label="{DeserializeBufTransform(0 jobs, execution time: 0 sec., preparation time: 0.000001584 sec.) (Finished)}"];
	...
  }
}
```
We can see that the 1st step: "ExchangeSource: MultiPathReceiver" cost all most of the query duration time.
I searched the query log of ByConity and found that ByConity search metadata information from FoundationDB in a single thread. Searching the metadata of Bucket MergeTree consumes too much time.
This is a part log:
```
2024.07.02 14:57:44.931718 [ ... ] {{uuid}_2} <Trace> MetastoreFDBImpl[...] : get key: default_TM_bucket\_database\_DB_bucket1
2024.07.02 14:57:44.931742 [ ... ] {{uuid}_2} <Trace> FDBClient[...] : Get key: default_TM_bucket\_database\_DB_bucket1
2024.07.02 14:57:44.934703 [ ... ] {{uuid}_2} <Trace> bucket_database.bucket1 ({uuid})[197] : All mutations
2024.07.02 14:57:44.938017 [ ... ] {{uuid}_2} <Trace> Catalog[...] : bucket_database.bucket1 ({uuid}) Staral number of parts is 0, timestamp: 450862373401264128
2024.07.02 14:57:44.938046 [ ... ] {{uuid}_2} <Trace> Catalog[...] : bucket_database.bucket1 ({uuid}) Finital number of parts is 0, timestamp: 450862373401264128
2024.07.02 14:57:44.938057 [ ... ] {{uuid}_2} <Debug> Catalog[...] : Elapsed 2ms to get 0 parts in 0 partitions for table : bucket_database.zmht8f6c-5e623f8812cc) , source : TargetServer(xxxxxx:xxxx), ts : 450862373401264128
......
2024.07.02 14:57:48.362325 [ ... ] {{uuid}_2} <Trace> MetastoreFDBImpl[...] : get key: default_TM_bucket\_database\_DB_bucket1
2024.07.02 14:57:48.362348 [ ... ] {{uuid}_2} <Trace> FDBClient[...] : Get key: default_TM_bucket\_database\_DB_bucket1
2024.07.02 14:57:48.367388 [ ... ] {{uuid}_2} <Trace> bucket_database.bucket1 ({uuid})[197] : All mutations
2024.07.02 14:57:48.371621 [ ... ] {{uuid}_2} <Trace> Catalog[...] : bucket_database.bucket1 ({uuid}) Staral number of parts is 0, timestamp: 450862373401264128
2024.07.02 14:57:48.371650 [ ... ] {{uuid}_2} <Trace> Catalog[...] : bucket_database.bucket1 ({uuid}) Finital number of parts is 0, timestamp: 450862373401264128
2024.07.02 14:57:48.371661 [ ... ] {{uuid}_2} <Debug> Catalog[...] : Elapsed 3ms to get 0 parts in 0 partitions for table : bucket_database.zmht8f6c-5e623f8812cc) , source : TargetServer(xxxxxx:xxxx), ts : 450862373401264128
```

**Comment by smmsmm1988** [comment]
@zhaojintaozhao how many buckets is bucket_database holding? 2~3ms to query FDB is relatively a short time. BTW, would you like to test enable_optimizer=false?

**Comment by zhaojintaozhao** [comment]
> @zhaojintaozhao how many tables is bucket_database holding? 2~3ms to query FDB is relatively a short time. BTW, would you like to test enable_optimizer=false?

If I set enable_optimizer=false, it also the same problem.

**Comment by smmsmm1988** [comment]
@zhaojintaozhao all tables have 0 parts, right? Could you send the detailed log of the slow query id of cnch_parts? We want to see what happened in detail.

**Comment by zhaojintaozhao** [comment]
> @zhaojintaozhao all tables have 0 parts, right? Could you send the detailed log of the slow query id of cnch_parts? We want to see what happened in detail.

Yes, all tables have 0 parts. Just like https://github.com/ByConity/ByConity/issues/1732#issuecomment-2205966804, Each table cost more than 50ms, so If  there are 60 tables, It will cost more than 3s.

**Comment by smmsmm1988** [comment]
> TSO Leader host-port is

OK, I see. It seems the performance of FDB is relatively slow. Could you test the performance of your FDB? The following log is got from my local environment:

[xxx] 2024.07.05 09:20:37.363227 [ xxx ] {xxx} <Trace> Context::getCnchTSOClient: TSO Leader host-port is: xxx
[xxx] 2024.07.05 09:20:37.363295 [ xxx ] {xxx} <Trace> Context::getCnchTSOClient: TSO Leader host-port is: xxx
[xxx] 2024.07.05 09:20:37.363354 [ xxx ] {xxx} <Trace> Context::getCnchTSOClient: TSO Leader host-port is: xxx
[xxx] 2024.07.05 09:20:37.363430 [ xxx ] {xxx} <Trace> Catalog: test.test (xxx) Start handle intermediate parts. Total number of parts is 0, timestamp: 450929737682649088
[xxx] 2024.07.05 09:20:37.363449 [ xxx ] {xxx} <Trace> Catalog: test.test (xxx) Finish handle intermediate parts. Total number of parts is 0, timestamp: 450929737682649088
[xxx] 2024.07.05 09:20:37.363464 [ xxx ] {xxx} <Debug> Catalog: Elapsed 0ms to get 0 parts in 4 partitions for table : test.test (xxx) , source : PartCache, ts : 450929737682649088

BTW, 0.2.2 is an old version. We highly recommend you try the latest version.

**Comment by zhaojintaozhao** [comment]
> > TSO Leader host-port is
> 
> OK, I see. It seems the performance of FDB is relatively slow. Could you test the performance of your FDB? The following log is got from my local environment:
> 
> [xxx] 2024.07.05 09:20:37.363227 [ xxx ] {xxx} Context::getCnchTSOClient: TSO Leader host-port is: xxx [xxx] 2024.07.05 09:20:37.363295 [ xxx ] {xxx} Context::getCnchTSOClient: TSO Leader host-port is: xxx [xxx] 2024.07.05 09:20:37.363354 [ xxx ] {xxx} Context::getCnchTSOClient: TSO Leader host-port is: xxx [xxx] 2024.07.05 09:20:37.363430 [ xxx ] {xxx} Catalog: test.test (xxx) Start handle intermediate parts. Total number of parts is 0, timestamp: 450929737682649088 [xxx] 2024.07.05 09:20:37.363449 [ xxx ] {xxx} Catalog: test.test (xxx) Finish handle intermediate parts. Total number of parts is 0, timestamp: 450929737682649088 [xxx] 2024.07.05 09:20:37.363464 [ xxx ] {xxx} Catalog: Elapsed 0ms to get 0 parts in 4 partitions for table : test.test (xxx) , source : PartCache, ts : 450929737682649088
> 
> BTW, 0.2.2 is an old version. We highly recommend you try the latest version.

This may be caused by the multiple servers of Byconity. If my system has only 1 clickhouse-server, it takes less than 1s, but if my system have 3 clickhouse-servers, it takes 6s

**Comment by smmsmm1988** [comment]
@zhaojintaozhao please help check the following logs for the same db.table:
1. for 1 clickhouse-server, grep logs like "Elapsed xxxms to get 0 parts in 0 partitions for table", get the time cost;
2. for 3 clickhouse-servers, grep logs like "Elapsed xxxms to get 0 parts in 0 partitions for table" in each server for the same table, get each time cost.
 
You can choose two tables and do the steps above for both.

**Comment by zhaojintaozhao** [comment]
> @zhaojintaozhao please help check the following logs for the same db.table:
> 
> 1. for 1 clickhouse-server, grep logs like "Elapsed xxxms to get 0 parts in 0 partitions for table", get the time cost;
> 2. for 3 clickhouse-servers, grep logs like "Elapsed xxxms to get 0 parts in 0 partitions for table" in each server for the same table, get each time cost.
> 
> You can choose two tables and do the steps above for both.

This is trace query log:
```
2024.07.13 15:59:03.265101 [ 3313011 ] {${query_uuid}} <Trace> MetastoreFDBImpl[xxx] : getByPrefix prefix: default_MT_{tableA_uuid}_
2024.07.13 15:59:03.265454 [ 3313011 ] {${query_uuid}} <Trace> Catalog[3933] : Get 0 mutations from catalog
2024.07.13 15:59:03.265465 [ 3313011 ] {${query_uuid}} <Trace> bucket.bucket0_30 ({tableA_uuid})[197] : All mutations:
2024.07.13 15:59:03.265483 [ 3313011 ] {${query_uuid}} <Trace> Context::getCnchTSOClient[4473] : TSO Leader host-port is: {tso_server_A}:{tso_port}
2024.07.13 15:59:03.265671 [ 3313011 ] {${query_uuid}} <Trace> MetastoreFDBImpl[xxx] : getByPrefix prefix: default_TP_{tableA_uuid}_
2024.07.13 15:59:03.266028 [ 3313011 ] {${query_uuid}} <Trace> Context::getCnchTSOClient[4473] : TSO Leader host-port is: {tso_server_A}:{tso_port}
2024.07.13 15:59:03.267988 [ 3313011 ] {${query_uuid}} <Trace> Catalog[xxx8] : bucket.bucket0_30 ({tableA_uuid}) Start handle intermediate parts. Total number of parts is 0, timestamp: 451074756705450694
2024.07.13 15:59:03.268009 [ 3313011 ] {${query_uuid}} <Trace> Catalog[xxxx] : bucket.bucket0_30 ({tableA_uuid}) Finish handle intermediate parts. Total number of parts is 0, timestamp: 451074756705450694
2024.07.13 15:59:03.268018 [ 3313011 ] {${query_uuid}} <Debug> Catalog[xxxx] : Elapsed 1ms to get 0 parts in 0 partitions for table : bucket.bucket0_30 ({tableA_uuid}) , source : TargetServer({server_B}:{port}), ts : 451074756705450694
2024.07.13 15:59:03.268057 [ 3313011 ] {${query_uuid}} <Trace> MetastoreFDBImpl[84] : get key: default_TM_bucket_bucket0\_12
2024.07.13 15:59:03.268074 [ 3313011 ] {${query_uuid}} <Trace> FDBClient[xxx] : Get key: default_TM_bucket_bucket0\_12
2024.07.13 15:59:03.268373 [ 3313011 ] {${query_uuid}} <Trace> MetastoreFDBImpl[xxx] : getByPrefix prefix: default_TB_{tableB_uuid}_
2024.07.13 15:59:03.269212 [ 3313011 ] {${query_uuid}} <Trace> MetastoreFDBImpl[xxx] : getByPrefix prefix: default_MT_{tableB_uuid}_
2024.07.13 15:59:03.269523 [ 3313011 ] {${query_uuid}} <Trace> Catalog[3933] : Get 0 mutations from catalog
2024.07.13 15:59:03.269533 [ 3313011 ] {${query_uuid}} <Trace> bucket.bucket0_12 ({tableB_uuid})[197] : All mutations:
2024.07.13 15:59:03.269548 [ 3313011 ] {${query_uuid}} <Trace> Context::getCnchTSOClient[4473] : TSO Leader host-port is: {tso_server_A}:{tso_port}
2024.07.13 15:59:03.269716 [ 3313011 ] {${query_uuid}} <Trace> MetastoreFDBImpl[xxx] : getByPrefix prefix: default_TP_{tableB_uuid}_
2024.07.13 15:59:03.270081 [ 3313011 ] {${query_uuid}} <Trace> Context::getCnchTSOClient[4473] : TSO Leader host-port is: {tso_server_A}:{tso_port}
2024.07.13 15:59:03.294754 [ 3313011 ] {${query_uuid}} <Trace> Catalog[xxx8] : bucket.bucket0_12 ({tableB_uuid}) Start handle intermediate parts. Total number of parts is 0, timestamp: 451074756705450694
2024.07.13 15:59:03.294782 [ 3313011 ] {${query_uuid}} <Trace> Catalog[xxxx] : bucket.bucket0_12 ({tableB_uuid}) Finish handle intermediate parts. Total number of parts is 0, timestamp: 451074756705450694
2024.07.13 15:59:03.294804 [ 3313011 ] {${query_uuid}} <Debug> Catalog[xxxx] : Elapsed 24ms to get 0 parts in 0 partitions for table : bucket.bucket0_12 ({tableB_uuid}) , source : TargetServer({server_A}:{port}), ts : 451074756705450694
2024.07.13 15:59:03.294863 [ 3313011 ] {${query_uuid}} <Trace> MetastoreFDBImpl[xx] : get key: default_TM_bucket_bucket0\_3
2024.07.13 15:59:03.294886 [ 3313011 ] {${query_uuid}} <Trace> FDBClient[xxx] : Get key: default_TM_bucket_bucket0\_3
2024.07.13 15:59:03.295271 [ 3313011 ] {${query_uuid}} <Trace> MetastoreFDBImpl[xxx] : getByPrefix prefix: default_TP_{tableC_uuid}_
2024.07.13 15:59:03.295580 [ 3313011 ] {${query_uuid}} <Trace> Context::getCnchTSOClient[4473] : TSO Leader host-port is: {tso_server_A}:{tso_port}
2024.07.13 15:59:03.295728 [ 3313011 ] {${query_uuid}} <Trace> MetastoreFDBImpl[xxx] : getByPrefix prefix: default_TP_{tableC_uuid}_
2024.07.13 15:59:03.296052 [ 3313011 ] {${query_uuid}} <Trace> Catalog[xxx8] : bucket.bucket0_3 ({tableC_uuid}) Start handle intermediate parts. Total number of parts is 0, timestamp: 451074756705450694
2024.07.13 15:59:03.296071 [ 3313011 ] {${query_uuid}} <Trace> Catalog[xxxx] : bucket.bucket0_3 ({tableC_uuid}) Finish handle intermediate parts. Total number of parts is 0, timestamp: 451074756705450694
2024.07.13 15:59:03.296093 [ 3313011 ] {${query_uuid}} <Debug> Catalog[xxxx] : Elapsed 0ms to get 0 parts in 0 partitions for table : bucket.bucket0_3 ({tableC_uuid}) , source : KV(can not laverage cache), ts : 451074756705450694
2024.07.13 15:59:03.296106 [ 3313011 ] {${query_uuid}} <Trace> MetastoreFDBImpl[84] : get key: default_TM_bucket_bucket0\_28
2024.07.13 15:59:03.296119 [ 3313011 ] {${query_uuid}} <Trace> FDBClient[xxx] : Get key: default_TM_bucket_bucket0\_28
2024.07.13 15:59:03.296409 [ 3313011 ] {${query_uuid}} <Trace> MetastoreFDBImpl[xxx] : getByPrefix prefix: default_TB_{tableD_uuid}_
2024.07.13 15:59:03.297235 [ 3313011 ] {${query_uuid}} <Trace> MetastoreFDBImpl[xxx] : getByPrefix prefix: default_MT_{tableD_uuid}_
2024.07.13 15:59:03.297536 [ 3313011 ] {${query_uuid}} <Trace> Catalog[3933] : Get 0 mutations from catalog
2024.07.13 15:59:03.297559 [ 3313011 ] {${query_uuid}} <Trace> bucket.bucket0_28 ({tableD_uuid})[197] : All mutations:
2024.07.13 15:59:03.297581 [ 3313011 ] {${query_uuid}} <Trace> Context::getCnchTSOClient[4473] : TSO Leader host-port is: {tso_server_A}:{tso_port}
2024.07.13 15:59:03.297791 [ 3313011 ] {${query_uuid}} <Trace> MetastoreFDBImpl[xxx] : getByPrefix prefix: default_TP_{tableD_uuid}_
2024.07.13 15:59:03.298108 [ 3313011 ] {${query_uuid}} <Trace> Context::getCnchTSOClient[4473] : TSO Leader host-port is: {tso_server_A}:{tso_port}
2024.07.13 15:59:03.324876 [ 3313011 ] {${query_uuid}} <Trace> Catalog[xxx8] : bucket.bucket0_28 ({tableD_uuid}) Start handle intermediate parts. Total number of parts is 0, timestamp: 451074756705450694
2024.07.13 15:59:03.324901 [ 3313011 ] {${query_uuid}} <Trace> Catalog[xxxx] : bucket.bucket0_28 ({tableD_uuid}) Finish handle intermediate parts. Total number of parts is 0, timestamp: 451074756705450694
2024.07.13 15:59:03.324911 [ 3313011 ] {${query_uuid}} <Debug> Catalog[xxxx] : Elapsed 26ms to get 0 parts in 0 partitions for table : bucket.bucket0_28 ({tableD_uuid}) , source : TargetServer({server_A}:{port}), ts : 451074756705450694
```
We can find that  it elapses less than 1ms to get part metadata from local server node, it elapses 1ms--2ms to get part metadata from serverB, and it elapses 24ms--26ms to get part metadata from serverA.  
I find that there are pressure tests to query serverA, so it elapses too much time than serverB.   If I stop the pressure tests it also elapses 1ms--2ms to get part metadat from serverB.

**Comment by smmsmm1988** [comment]
> > @zhaojintaozhao please help check the following logs for the same db.table:
> > 
> > 1. for 1 clickhouse-server, grep logs like "Elapsed xxxms to get 0 parts in 0 partitions for table", get the time cost;
> > 2. for 3 clickhouse-servers, grep logs like "Elapsed xxxms to get 0 parts in 0 partitions for table" in each server for the same table, get each time cost.
> > 
> > You can choose two tables and do the steps above for both.
> 
> This is trace query log:
> 
> ```
> 2024.07.13 15:59:03.265101 [ 3313011 ] {${query_uuid}} <Trace> MetastoreFDBImpl[xxx] : getByPrefix prefix: default_MT_{tableA_uuid}_
> 2024.07.13 15:59:03.265454 [ 3313011 ] {${query_uuid}} <Trace> Catalog[3933] : Get 0 mutations from catalog
> 2024.07.13 15:59:03.265465 [ 3313011 ] {${query_uuid}} <Trace> bucket.bucket0_30 ({tableA_uuid})[197] : All mutations:
> 2024.07.13 15:59:03.265483 [ 3313011 ] {${query_uuid}} <Trace> Context::getCnchTSOClient[4473] : TSO Leader host-port is: {tso_server_A}:{tso_port}
> 2024.07.13 15:59:03.265671 [ 3313011 ] {${query_uuid}} <Trace> MetastoreFDBImpl[xxx] : getByPrefix prefix: default_TP_{tableA_uuid}_
> 2024.07.13 15:59:03.266028 [ 3313011 ] {${query_uuid}} <Trace> Context::getCnchTSOClient[4473] : TSO Leader host-port is: {tso_server_A}:{tso_port}
> 2024.07.13 15:59:03.267988 [ 3313011 ] {${query_uuid}} <Trace> Catalog[xxx8] : bucket.bucket0_30 ({tableA_uuid}) Start handle intermediate parts. Total number of parts is 0, timestamp: 451074756705450694
> 2024.07.13 15:59:03.268009 [ 3313011 ] {${query_uuid}} <Trace> Catalog[xxxx] : bucket.bucket0_30 ({tableA_uuid}) Finish handle intermediate parts. Total number of parts is 0, timestamp: 451074756705450694
> 2024.07.13 15:59:03.268018 [ 3313011 ] {${query_uuid}} <Debug> Catalog[xxxx] : Elapsed 1ms to get 0 parts in 0 partitions for table : bucket.bucket0_30 ({tableA_uuid}) , source : TargetServer({server_B}:{port}), ts : 451074756705450694
> 2024.07.13 15:59:03.268057 [ 3313011 ] {${query_uuid}} <Trace> MetastoreFDBImpl[84] : get key: default_TM_bucket_bucket0\_12
> 2024.07.13 15:59:03.268074 [ 3313011 ] {${query_uuid}} <Trace> FDBClient[xxx] : Get key: default_TM_bucket_bucket0\_12
> 2024.07.13 15:59:03.268373 [ 3313011 ] {${query_uuid}} <Trace> MetastoreFDBImpl[xxx] : getByPrefix prefix: default_TB_{tableB_uuid}_
> 2024.07.13 15:59:03.269212 [ 3313011 ] {${query_uuid}} <Trace> MetastoreFDBImpl[xxx] : getByPrefix prefix: default_MT_{tableB_uuid}_
> 2024.07.13 15:59:03.269523 [ 3313011 ] {${query_uuid}} <Trace> Catalog[3933] : Get 0 mutations from catalog
> 2024.07.13 15:59:03.269533 [ 3313011 ] {${query_uuid}} <Trace> bucket.bucket0_12 ({tableB_uuid})[197] : All mutations:
> 2024.07.13 15:59:03.269548 [ 3313011 ] {${query_uuid}} <Trace> Context::getCnchTSOClient[4473] : TSO Leader host-port is: {tso_server_A}:{tso_port}
> 2024.07.13 15:59:03.269716 [ 3313011 ] {${query_uuid}} <Trace> MetastoreFDBImpl[xxx] : getByPrefix prefix: default_TP_{tableB_uuid}_
> 2024.07.13 15:59:03.270081 [ 3313011 ] {${query_uuid}} <Trace> Context::getCnchTSOClient[4473] : TSO Leader host-port is: {tso_server_A}:{tso_port}
> 2024.07.13 15:59:03.294754 [ 3313011 ] {${query_uuid}} <Trace> Catalog[xxx8] : bucket.bucket0_12 ({tableB_uuid}) Start handle intermediate parts. Total number of parts is 0, timestamp: 451074756705450694
> 2024.07.13 15:59:03.294782 [ 3313011 ] {${query_uuid}} <Trace> Catalog[xxxx] : bucket.bucket0_12 ({tableB_uuid}) Finish handle intermediate parts. Total number of parts is 0, timestamp: 451074756705450694
> 2024.07.13 15:59:03.294804 [ 3313011 ] {${query_uuid}} <Debug> Catalog[xxxx] : Elapsed 24ms to get 0 parts in 0 partitions for table : bucket.bucket0_12 ({tableB_uuid}) , source : TargetServer({server_A}:{port}), ts : 451074756705450694
> 2024.07.13 15:59:03.294863 [ 3313011 ] {${query_uuid}} <Trace> MetastoreFDBImpl[xx] : get key: default_TM_bucket_bucket0\_3
> 2024.07.13 15:59:03.294886 [ 3313011 ] {${query_uuid}} <Trace> FDBClient[xxx] : Get key: default_TM_bucket_bucket0\_3
> 2024.07.13 15:59:03.295271 [ 3313011 ] {${query_uuid}} <Trace> MetastoreFDBImpl[xxx] : getByPrefix prefix: default_TP_{tableC_uuid}_
> 2024.07.13 15:59:03.295580 [ 3313011 ] {${query_uuid}} <Trace> Context::getCnchTSOClient[4473] : TSO Leader host-port is: {tso_server_A}:{tso_port}
> 2024.07.13 15:59:03.295728 [ 3313011 ] {${query_uuid}} <Trace> MetastoreFDBImpl[xxx] : getByPrefix prefix: default_TP_{tableC_uuid}_
> 2024.07.13 15:59:03.296052 [ 3313011 ] {${query_uuid}} <Trace> Catalog[xxx8] : bucket.bucket0_3 ({tableC_uuid}) Start handle intermediate parts. Total number of parts is 0, timestamp: 451074756705450694
> 2024.07.13 15:59:03.296071 [ 3313011 ] {${query_uuid}} <Trace> Catalog[xxxx] : bucket.bucket0_3 ({tableC_uuid}) Finish handle intermediate parts. Total number of parts is 0, timestamp: 451074756705450694
> 2024.07.13 15:59:03.296093 [ 3313011 ] {${query_uuid}} <Debug> Catalog[xxxx] : Elapsed 0ms to get 0 parts in 0 partitions for table : bucket.bucket0_3 ({tableC_uuid}) , source : KV(can not laverage cache), ts : 451074756705450694
> 2024.07.13 15:59:03.296106 [ 3313011 ] {${query_uuid}} <Trace> MetastoreFDBImpl[84] : get key: default_TM_bucket_bucket0\_28
> 2024.07.13 15:59:03.296119 [ 3313011 ] {${query_uuid}} <Trace> FDBClient[xxx] : Get key: default_TM_bucket_bucket0\_28
> 2024.07.13 15:59:03.296409 [ 3313011 ] {${query_uuid}} <Trace> MetastoreFDBImpl[xxx] : getByPrefix prefix: default_TB_{tableD_uuid}_
> 2024.07.13 15:59:03.297235 [ 3313011 ] {${query_uuid}} <Trace> MetastoreFDBImpl[xxx] : getByPrefix prefix: default_MT_{tableD_uuid}_
> 2024.07.13 15:59:03.297536 [ 3313011 ] {${query_uuid}} <Trace> Catalog[3933] : Get 0 mutations from catalog
> 2024.07.13 15:59:03.297559 [ 3313011 ] {${query_uuid}} <Trace> bucket.bucket0_28 ({tableD_uuid})[197] : All mutations:
> 2024.07.13 15:59:03.297581 [ 3313011 ] {${query_uuid}} <Trace> Context::getCnchTSOClient[4473] : TSO Leader host-port is: {tso_server_A}:{tso_port}
> 2024.07.13 15:59:03.297791 [ 3313011 ] {${query_uuid}} <Trace> MetastoreFDBImpl[xxx] : getByPrefix prefix: default_TP_{tableD_uuid}_
> 2024.07.13 15:59:03.298108 [ 3313011 ] {${query_uuid}} <Trace> Context::getCnchTSOClient[4473] : TSO Leader host-port is: {tso_server_A}:{tso_port}
> 2024.07.13 15:59:03.324876 [ 3313011 ] {${query_uuid}} <Trace> Catalog[xxx8] : bucket.bucket0_28 ({tableD_uuid}) Start handle intermediate parts. Total number of parts is 0, timestamp: 451074756705450694
> 2024.07.13 15:59:03.324901 [ 3313011 ] {${query_uuid}} <Trace> Catalog[xxxx] : bucket.bucket0_28 ({tableD_uuid}) Finish handle intermediate parts. Total number of parts is 0, timestamp: 451074756705450694
> 2024.07.13 15:59:03.324911 [ 3313011 ] {${query_uuid}} <Debug> Catalog[xxxx] : Elapsed 26ms to get 0 parts in 0 partitions for table : bucket.bucket0_28 ({tableD_uuid}) , source : TargetServer({server_A}:{port}), ts : 451074756705450694
> ```
> 
> We can find that it elapses less than 1ms to get part metadata from local server node, it elapses 1ms--2ms to get part metadata from serverB, and it elapses 24ms--26ms to get part metadata from serverA. I find that there are pressure tests to query serverA, so it elapses too much time than serverB. If I stop the pressure tests it also elapses 1ms--2ms to get part metadat from serverB.

OK, I'm glad we find the key reason

**Comment by zhaojintaozhao** [comment]
I stop pressure tests and test again. This time I create more than 2thousand empty tables without any part.
If there is just 1 server, it cost 2s to query 2thousand tables metadata from FDB. But If there are 3 servers, it cost 5.6s to to query 2thousand tables metadata.

I suggest that the single-thread mode be changed to the multi-thread mode when the metadata of the table is obtained. The multi-thread concurrency capability can be used to improve the performance.

**Comment by smmsmm1988** [comment]
> partitions for table

Thank you for your suggestion. Typically, it is suggested to query cnch_parts with given database and table. We think query all tables is a low-frequency operation and relatively slow is acceptable. BTW, if you really want to query all tables, you can try system table cnch_parts_info, it only returns basic (but not up-to-date) information and would be fast.

**Comment by zhaojintaozhao** [comment]
> > partitions for table
> 
> Thank you for your suggestion. Typically, it is suggested to query cnch_parts with a given database and table. We think query all tables is a low-frequency operation and relatively slow is acceptable. BTW, if you really want to query all tables, you can try system table cnch_parts_info, it only returns basic (but not up-to-date) information and would be fast.

OK, Thank you.

**Comment by zhaojintaozhao** [comment]
This is because the FoundationDB is deployed on the SATA disk. 
After I deployed FoundationDB  using SSD disk, the performance of ByConity querying FDB metadata was greatly improved, and the problem was solved. 
Thank you. @smmsmm1988
