### ISSUE TITLE
unstable ci test RemoteSenderLimitTest

### ISSUE THREAD

**Issue by Aaaaaaron** [ByConity/ByConity#174]
<img width="670" alt="img_v2_c9cf71fa-0f9f-4bac-b154-21a1dbbe5ehu" src="https://user-images.githubusercontent.com/15643702/226286008-dc2c8980-01d9-4246-8302-3a444ec11eeb.png">

**Comment by hustnn** [comment]
close in https://github.com/ByConity/ByConity/pull/175
