### ISSUE TITLE
ByConity throw exception when query lamda function of arrayMap also occurs 1.0.0-rc2: "Argument 2 of function arrayMap must be array. Found Nullable(Array(String)) instead"

### ISSUE THREAD

**Issue by zhaojintaozhao** [ByConity/ByConity#1744]
## Bug Report
ByConity throw exception when query lamda function of arrayMap. It throws exception: "Received from xx.xx.xx.xx:xxxx. DB::Exception: Argument 2 of function arrayMap must be array. Found Nullable(Array(String)) instead.: While processing arrayAvg(arrayMap(x -> pow(x, 2), CAST(['$H55A_z326076', '$H55A_z873391'], 'Nullable(Array(String))') AS _subquery1)) AS variance SQLSTATE: 42000."

However, the same table structure and data can be run normally on ClickHouse.

### 1. Create table。
```
CREATE TABLE db.table0
(
    `id` String,
    `name` LowCardinality(String),
    `pt_d` DateTime
)
ENGINE = CnchMergeTree
PARTITION BY toDate(pt_d)
PRIMARY KEY (name)
ORDER BY (name)
```

### 2. Insert data
```
insert into table db.table0 select  concat('$H55A_z', toString((rand() % ((1000000 - 1) + 1)) + 1)),concat('abc', toString((rand() % ((100 - 1) + 1)) + 1)),'2020-04-01 11:00:00'  from  numbers(2);
```

### 3. It throw exception when query 
```
sql:
SELECT arrayAvg(arrayMap(x -> pow(x, 2), (select groupArray(id) from db.table0))) AS variance;

ByConity throw exception when query this sql: "Received from xx.xx.xx.xx:xxxx. DB::Exception: Argument 2 of function arrayMap must be array. Found Nullable(Array(String)) instead.: While processing arrayAvg(arrayMap(x -> pow(x, 2), CAST(['$H55A_z326076', '$H55A_z873391'], 'Nullable(Array(String))') AS _subquery1)) AS variance SQLSTATE: 42000."

However, the same table structure and data can be run normally on ClickHouse.
```

### Version
0.2.2

Does any one face the same problem?

**Comment by GallifreyY** [comment]
hi! @zhaojintaozhao we internally has already resolved the problem. Will cherry-pick related changes to byconity soon. In the mean time, you can try to add assumeNotNull() to remove nullable.
eg:
`SELECT arrayAvg(arrayMap(x -> pow(x, 2), assumeNotNull((select groupArray(id) from db.table0)))) AS variance;`

**Comment by zhaojintaozhao** [comment]
> hi! @zhaojintaozhao we internally has already resolved the problem. Will cherry-pick related changes to byconity soon. In the mean time, you can try to add assumeNotNull() to remove nullable. eg: `SELECT arrayAvg(arrayMap(x -> pow(x, 2), assumeNotNull((select groupArray(id) from db.table0)))) AS variance;`

Oh, I'm glad to hear that this issue has been fixed.
I want to known which PR fixed this issue?

**Comment by GallifreyY** [comment]
hi @zhaojintaozhao, i just checked, version 1.0.0-rc2 doesn't have the internal fix. I've already talked with my colleague, he will cherry-pick the fix soon. I'll update u here once merged. 
After that, u can verify the fix by
`set allow_return_nullable_array = 0;`
and run the same query again.

**Comment by zhaojintaozhao** [comment]
> hi @zhaojintaozhao, i just checked, version 1.0.0-rc2 doesn't have the internal fix. I've already talked with my colleague, he will cherry-pick the fix soon. I'll update u here once merged. After that, u can verify the fix by `set allow_return_nullable_array = 0;` and run the same query again.

@GallifreyY :  OK,  Thank you very much.
