### ISSUE TITLE
Add a new profile configuration: max_array_size_as_field to avoid exception: "Array of size is too large to be manipulated as single field, maximum size 1000000"

### ISSUE THREAD

**Issue by zhaojintaozhao** [ByConity/ByConity#1748]
(you don't have to strictly follow this form)

## Bug Report
ByConity throws exception "Array of size is too large to be manipulated as single field, maximum size 1000000" when I query array sql.

Can we dd a new profile configuration: max_array_size_as_field to avoid this exception?

## Briefly describe the bug
When I query this sql to byconity.
```
SELECT groupArray(t.i0) FROM (SELECT sum(column_a) AS i0, column_a FROM db.table WHERE  GROUP BY column_a) AS t
```
It throws exception 
```
Sql exec time out ,error id is xxxxxxxxx，msg：Sql exec error:ClickHouse exception, code: 128, host: xx.xx.xx.xx, port: xxxx; Code: 128, e.displayText() = DB::Exception: Array of size 1669677 is too large to be manipulated as single field, maximum size 1000000: While processing (SELECT groupArray(t.i0) FROM (SELECT sum(column_a) AS i0, column_a FROM db.table WHERE  GROUP BY column_a) AS t) AS arr SQLSTATE: 54000 (version 21.8.7.1)
```

### The result you expected
I find ByConity set max_array_size_as_field=1000000 in ColumnArray.cpp

if array size is large than  1000000, the query thread will throw exception.
```
ColumnArray.cpp
static constexpr size_t max_array_size_as_field = 1000000;

void ColumnArray::get(size_t n, Field & res) const
{
    size_t offset = offsetAt(n);
    size_t size = sizeAt(n);

    if (size > max_array_size_as_field)
        throw Exception(ErrorCodes::TOO_LARGE_ARRAY_SIZE, "Array of size {} is too large to be manipulated as single field, maximum size {}",
            size, max_array_size_as_field);
```

This problem can be avoided if max_array_size_as_field is set to a larger value.

We can set the max_array_size_as_field  in the ByConity config file.

This configuration "max_array_size_as_field is closely related to the query. Can we set this configuration as a profile in users.yml and make it take effect dynamically?"

### Version
0.2.2

**Comment by superhail** [comment]
I think we can add this configuration, u can follow this MR https://github.com/ByConity/ByConity/commit/c6383708e59376a24e9c1376b5d18f0f2b882068(it basically adds a restriction of max plan segment size, just the reverse of what u want to do)

**Comment by zhaojintaozhao** [comment]
> u can follow this MR [c6383708e59376a24e9c1376b5d18f0f2b882068(it](https://github.com/ByConity/ByConity/commit/c6383708e59376a24e9c1376b5d18f0f2b882068(it) basically adds a restriction of max plan segment size, just the reverse of what u want to do)

OKey, I will add a PR this week.

**Comment by kevinthfang** [comment]
Thanks @zhaojintaozhao
