### ISSUE TITLE
It's too slow to query bucket table because there are too many parts.

### ISSUE THREAD

**Issue by zhaojintaozhao** [ByConity/ByConity#1749]
(you don't have to strictly follow this form)

## Question

It's too slow to query bucket table because there are too many parts.

#### 1. ByConity cluster information
There are 3 tso servers, 3 ByConity-Servers, 20 write-workers and 50 default-workers in my ByConity cluster.
#### 2. Bucket CnchMergeTree table info:
I create a bucket CnchMergeTree, just like: 
```
CREATE TABLE db_bucket.bucket0
(
    `id` Int32,
    `name` String,
    `age` UInt8,
    `age_group` UInt8,
	 ......
	`timestamp` DateTime
)
ENGINE = CnchMergeTree
PARTITION BY toDate(timestamp)
CLUSTER BY (id, toDate(timestamp)) INTO 50 BUCKETS SPLIT_NUMBER 100
ORDER BY id;
```
#### 3. Load Data
I import more than 10 bilion rows of data in 1 partition to this Bucket CnchMergeTree.
ByConity write worker import between 100 thousand rows each time.

#### 4. Query Table
It's too slow to query this Bucket table because there are too many parts. 
It throws Exception 
Exception: Code: 159, e.displayText() = DB::Exception: Get data from metastore reached timeout 60000ms. SOLSTATE: HY000 (version 21.8.7.1) (from xx.xx.xx.x:xxx) 

#### 5. Probleam Analysis

* There 10 billion rows of data in 1 partition of this table, I import 100 thousand rows each time. 
* There will be 100 thousand parts if this CnchMergeTree is not a bucket table.
* If this CnchMergeTree table is a bucket table, the number of buckets will be enlarged. In my cluster there are more than 3 million parts.
* It cost too much time when query metadata from FoundationDB.
* It is different from number of bucket table and number of write-worker, so If we import 100 thousand to a bucket table, there will be 20 part because write-worker will bucket these data to 50 buckets.

## 中文描述：
a. default-worker: 50台机器,  write-worker是20台; 建表时分成50个桶
b. 数据导入每次10w条，有100亿的数据， 在不考虑分桶的情况下， 1个分区的数据会产生10w个part
c. 当数据有分桶，此时桶数会放大，在我们的环境中发现放大到了300w个part
d. 查询分桶表时，性能都耗在了元数据获取上, 报错都是获取元数据超时
e. 原因：part数过多，从FDB查的时候慢了
f. 采取了预分区的导入方式，但write-worker个数和bucket桶数不一致，导致预分桶失效了
g. 预分区时, 导入模块只支持单分桶键; 但byconity建表语句建了2个分桶键,也会失效

**Comment by smmsmm1988** [comment]
hi @zhaojintaozhao.
1. Usually timestamp is used for partition by, not for cluster by. It is highly suggested to only use cluster by id.
2. As you have a huge amount of data, you'd better improve from 100 thousand rows to 1 million rows for data importing each time.
3. After data is imported, the background merge is working to reduce the number of parts. So you can wait for a while to query the bucket table.

**Comment by zhaojintaozhao** [comment]
> * Usually timestamp is used for partition by, not for cluster by. It is highly suggested to only use cluster by id.
> * As you have a huge amount of data, you'd better improve from 100 thousand rows to 1 million rows for data importing each time.
> * After data is imported, the background merge is working to reduce the number of parts. So you can wait for a while to query the bucket table.

Hi @smmsmm1988 :
Is there any way to speed up the merge? There are 20 write-workers in my system. How should I adjust the parameters to speed up the merge?  
Is there any way to speed up the merge? I have 20 write-workers in my system. How can I change the default merge parameters to speed up the bucket table merge?

**Comment by smmsmm1988** [comment]
> > * Usually timestamp is used for partition by, not for cluster by. It is highly suggested to only use cluster by id.
> > * As you have a huge amount of data, you'd better improve from 100 thousand rows to 1 million rows for data importing each time.
> > * After data is imported, the background merge is working to reduce the number of parts. So you can wait for a while to query the bucket table.
> 
> Hi @smmsmm1988 :
> 
> Is there any way to speed up the merge? I have 20 write-workers in my system. How can I change the default merge parameters to speed up the bucket table merge?

try the following parameters:
enable_addition_bg_task = 1
cnch_merge_select_nonadjacent_parts = true
max_partition_for_multi_select = 7
max_addition_bg_task_num = max(1.5 * writer_worker_num * core_num_per_write_worker, 200)

**Comment by kevinthfang** [comment]
@zhaojintaozhao did you try the parameters @smmsmm1988  suggested? Do you still have the issue?

**Comment by zhaojintaozhao** [comment]
> @zhaojintaozhao did you try the parameters @smmsmm1988 suggested? Do you still have the issue?

Yes, after I used the parameters provided by @smmsmm1988, the problem was solved. Thank @smmsmm1988  very much.

And thank you.

So I close this issue.

**Comment by zhaojintaozhao** [comment]
This issue can be closed.
