### ISSUE TITLE
DB::Exception: No local available worker group for vw_default SQLSTATE: HY000 (version 21.8.7.1) 

### ISSUE THREAD

**Issue by xiongbl526** [ByConity/ByConity#1750]
(you don't have to strictly follow this form)

## Question
hey,麻烦帮看个问题 k8s helm部署了0.3.2版本Byconity, 这个报错持续了一个多小时 后面自己恢复了
server 2个pod
vw-default 2个pod
vw-write 2个pod
/etc/byconity/cnch-config.yaml

catalog:
  name_space: devops-byconity
catalog_service:
  fdb:
    cluster_file: /etc/byconity/fdb/cluster-file
  type: fdb
cnch_type: server
exchange_port: 9410
exchange_status_port: 9510
hdfs_addr: hdfs://byconity-hdfs-namenodes:8020
http_port: 8123
rpc_port: 8124
service_discovery:
  cluster: default
  daemon_manager:
    headless_service: devops-byconity-daemon-manager-headless
    psm: devops-byconity-daemon-manager
    service: devops-byconity-daemon-manager
  mode: dns
  resource_manager:
    headless_service: devops-byconity-resource-manager-headless
    psm: devops-byconity-resource-manager
    service: devops-byconity-resource-manager
  server:
    headless_service: devops-byconity-server-headless
    psm: devops-byconity-server
    service: devops-byconity-server
  tso:
    headless_service: devops-byconity-tso-headless
    psm: devops-byconity-tso
    service: devops-byconity-tso
  vw: {}
service_discovery_kv:
  resource_manager:
    expired_interval_ms: 6000
    host_path: data.cnch.resource_manager-election
    refresh_interval_ms: 1000
  server_manager:
    expired_interval_ms: 6000
    host_path: data.cnch.server-election
    refresh_interval_ms: 1000
  tso:
    expired_interval_ms: 6000
    host_path: data.cnch.tso-election
    refresh_interval_ms: 1000
tcp_port: 9000
tso_service:
  tso_get_leader_info_interval_ms: 0
  tso_max_retry_count: 3
  tso_window_ms: 3000

**Comment by skyoct** [comment]
@xiongbl526 需要检查一下vw_default对应的pod是否正常运行？
