### ISSUE TITLE
Limiting QPS for S3

### ISSUE THREAD

**Issue by skyoct** [ByConity/ByConity#1751]
### Describe the feature you'd like
When the QPS limit of S3 provided by the cloud provider is exceeded, it will return a QPS limit error directly, causing queries to fail. Can we impose a limit on the maximum QPS usage of ByConity's S3 to ensure that the cloud provider's limit is not triggered?

**Comment by smmsmm1988** [comment]
hi @skyoct. Currently there is no plan to introduce such feature into ByConity engine. We do not want to incur more layers for QPS. Maybe you can try to decrease max_threads to avoid reaching QPS limit of S3.

**Comment by skyoct** [comment]
> hi @skyoct. Currently there is no plan to introduce such feature into ByConity engine. We do not want to incur more layers for QPS. Maybe you can try to decrease max_threads to avoid reaching QPS limit of S3.

Ok, Thank you
