### ISSUE TITLE
system.cnch_parts筛选查询返回结果不准确

### ISSUE THREAD

**Issue by xiongbl526** [ByConity/ByConity#1752]
(you don't have to strictly follow this form)

## Question
SELECT DISTINCT partition
FROM system.cnch_parts
WHERE (database = 'open') AND (table = 'open_msg_log') AND (partition <= '2024-07-12')

Query id: d80ac33b-8652-43dd-b3fd-fbe466efdbeb

┌─partition────┐
│ '2024-07-12' │
│ '2024-07-13' │
│ '2024-07-15' │
│ '2024-07-14' │
│ '2024-07-10' │
│ '2024-07-11' │
└──────────────┘

6 rows in set. Elapsed: 0.302 sec.
上述查询没有问题，但是根据partition 筛选查询返回不准确
SELECT DISTINCT partition
FROM system.cnch_parts
WHERE (database = 'open') AND (table = 'open_msg_log') AND (partition <= '2024-07-11')

Query id: 66ba21bf-0658-4e7c-9ca3-579667c6a1e4

┌─partition────┐
│ '2024-07-12' │
│ '2024-07-13' │
│ '2024-07-15' │
│ '2024-07-14' │
│ '2024-07-10' │
│ '2024-07-11' │
└──────────────┘

6 rows in set. Elapsed: 0.330 sec.

**Comment by smmsmm1988** [comment]
是两个查询都返回了不在筛选范围内的partition是吗？

**Comment by xiongbl526** [comment]
第一个查询没有加筛选条件，第二个加了筛选条件，还是返回了全量数据



---- 回复的原邮件 ----
| 发件人 | Maomeng ***@***.***> |
| 日期 | 2024年07月15日 20:22 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] system.cnch_parts筛选查询返回结果不准确 (Issue #1752) |

是两个查询都返回了不在筛选范围内的partition是吗？

**Comment by smmsmm1988** [comment]
> 第一个查询没有加筛选条件，第二个加了筛选条件，还是返回了全量数据
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | Maomeng ***@***.***> | | 日期 | 2024年07月15日 20:22 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [ByConity/ByConity] system.cnch_parts筛选查询返回结果不准确 (Issue #1752) | 是两个查询都返回了不在筛选范围内的partition是吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

我看你第一个也加了筛选条件AND (partition <= '2024-07-12')？

**Comment by xiongbl526** [comment]
> > 第一个查询没有加筛选条件，第二个加了筛选条件，还是返回了全量数据
> > […](#)
> > ---- 回复的原邮件 ---- | 发件人 | Maomeng _**@**_._**> | | 日期 | 2024年07月15日 20:22 | | 收件人 | _**@**_.**_> | | 抄送至 | _**@**_._**>**_@_**.**_> | | 主题 | Re: [ByConity/ByConity] system.cnch_parts筛选查询返回结果不准确 (Issue #1752) | 是两个查询都返回了不在筛选范围内的partition是吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 我看你第一个也加了筛选条件AND (partition <= '2024-07-12')？

不好意思 拷贝错了 两个都是加 了筛选条件的 条件不同 但是返回结果却相同

**Comment by smmsmm1988** [comment]
@xiongbl526 where partition <= '\'2024-07-11\'' 或者是 where partition_id <= '2024-07-11'。partition列相比于partition_id列，多了个''

**Comment by xiongbl526** [comment]
> @xiongbl526 where partition <= ''2024-07-11'' 或者是 where partition_id <= '2024-07-11'。partition列相比于partition_id列，多了个''
啥意思 那我要怎么筛选

**Comment by smmsmm1988** [comment]
> > @xiongbl526 where partition <= ''2024-07-11'' 或者是 where partition_id <= '2024-07-11'。partition列相比于partition_id列，多了个''
> > 啥意思 那我要怎么筛选

就是如果你想通过partition来筛选的话，需要对数值再加个引号

**Comment by xiongbl526** [comment]
> > > @xiongbl526 where partition <= ''2024-07-11'' 或者是 where partition_id <= '2024-07-11'。partition列相比于partition_id列，多了个''
> > > 啥意思 那我要怎么筛选
> 
> 就是如果你想通过partition来筛选的话，需要对数值再加个引号

SELECT DISTINCT partition
FROM system.cnch_parts
WHERE (database = 'open') AND (table = 'open_msg_log') AND (partition_id <= '2024-07-12')
返回了空   用两个双引号 会报错
Expected one of: DoubleColon, LIKE, GLOBAL NOT IN, AS, DIV, RLIKE, IS, IS NOT DISTINCT FROM, OR, QuestionMark, BETWEEN, NOT LIKE, MOD, escape, AND, Comma, alias, IN, ILIKE, NOT ILIKE, NOT, IS DISTINCT FROM, REGEXP, token, NOT IN, GLOBAL IN

10.42.54.58 :) SELECT DISTINCT partition　FROM system.cnch_parts　WHERE (database = 'open') AND (table = 'open_msg_log') AND (partition <= ''2024-07-12'')

Syntax error: failed at position 125 ('2024') (line 3, col 76):

**Comment by smmsmm1988** [comment]
> > > > @xiongbl526 where partition <= ''2024-07-11'' 或者是 where partition_id <= '2024-07-11'。partition列相比于partition_id列，多了个''
> > > > 啥意思 那我要怎么筛选
> > 
> > 
> > 就是如果你想通过partition来筛选的话，需要对数值再加个引号
> 
> SELECT DISTINCT partition FROM system.cnch_parts WHERE (database = 'open') AND (table = 'open_msg_log') AND (partition_id <= '2024-07-12') 返回了空 用两个双引号 会报错 Expected one of: DoubleColon, LIKE, GLOBAL NOT IN, AS, DIV, RLIKE, IS, IS NOT DISTINCT FROM, OR, QuestionMark, BETWEEN, NOT LIKE, MOD, escape, AND, Comma, alias, IN, ILIKE, NOT ILIKE, NOT, IS DISTINCT FROM, REGEXP, token, NOT IN, GLOBAL IN
> 
> 10.42.54.58 :) SELECT DISTINCT partition　FROM system.cnch_parts　WHERE (database = 'open') AND (table = 'open_msg_log') AND (partition <= ''2024-07-12'')
> 
> Syntax error: failed at position 125 ('2024') (line 3, col 76):

partition列的单引号，需要加\，就是partition <= '\'2024-07-12\''

**Comment by xiongbl526** [comment]
> SELECT DISTINCT partition　FROM system.cnch_parts　WHERE (database = 'open') AND (table = 'open_msg_log') AND (partition <= ''2024-07-12'')

查partition_id用单个引号为啥查不出来呢

**Comment by smmsmm1988** [comment]
> > SELECT DISTINCT partition　FROM system.cnch_parts　WHERE (database = 'open') AND (table = 'open_msg_log') AND (partition <= ''2024-07-12'')
> 
> 查partition_id用单个引号为啥查不出来呢

partition_id需要把日期中的-去掉，partition_id <= '20240712'
