### ISSUE TITLE
Application: DB::ErrnoException: Cannot write to file /var/byconity/disks/DISK_INFOS.tmp, errno: 28, strerror: No space left on device SQLSTATE: 58030

### ISSUE THREAD

**Issue by xiongbl526** [ByConity/ByConity#1753]
(you don't have to strictly follow this form)

## Question
hey，帮忙看个问题，helm 部署了0.3.2版本的byconity 之前的配置是
defaultWorker: &defaultWorker
    replicas: 1
    image: ""
    podAnnotations: {}
    resources: 
     limits:
       memory: "10Gi"
       cpu: "6000m"
     requests:
       memory: "6Gi"
       cpu: "2500m"
vw-default和vw-write都是2个Pod  我调整后的配置
resources: 
     limits:
       memory: "12Gi"
       cpu: "6000m"
     requests:
       memory: "6Gi"
       cpu: "2800m"
执行helm update之后 vw-default两个pod正常更新重启， vw-write 第一个Pod一直报错标题的错误信息

**Comment by skyoct** [comment]
你好，可以参考下这个issue #848

**Comment by xiongbl526** [comment]
> 你好，可以参考下这个issue #848

嗯嗯 昨天有人指导了 谢谢
