### ISSUE TITLE
server服务产生错误日志并导致被killed重启：BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.

### ISSUE THREAD

**Issue by xinip** [ByConity/ByConity#1755]
2024.07.14 09:48:27.957320 [ 430566 ] {} <Fatal> BaseDaemon: ########################################
2024.07.14 09:48:27.957356 [ 430566 ] {} <Fatal> BaseDaemon: (version 21.8.7.1 scm1.0.0.0, build id: B04FC607F093B4E2) (from thread 365088) (no query) Received signal Segmentation fault (11)
2024.07.14 09:48:27.957368 [ 430566 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2024.07.14 09:48:27.957377 [ 430566 ] {} <Fatal> BaseDaemon: Stack trace: 0x216753da 0x216d2ed8 0x21673c63 0x216ba386 0x26fbfeaf 0x26fb6ece 0x270e702d 0x26f84b2d
2024.07.14 09:48:27.960886 [ 430567 ] {} <Fatal> BaseDaemon: ########################################
2024.07.14 09:48:27.960924 [ 430567 ] {} <Fatal> BaseDaemon: (version 21.8.7.1 scm1.0.0.0, build id: B04FC607F093B4E2) (from thread 365030) (no query) Received signal Segmentation fault (11)
2024.07.14 09:48:27.960943 [ 430567 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2024.07.14 09:48:27.960957 [ 430567 ] {} <Fatal> BaseDaemon: Stack trace: 0x216753da 0x216d2ed8 0x21673c63 0x216ba386 0x26fbfeaf 0x26fb6ece 0x270e702d 0x26f84b2d
2024.07.14 09:48:27.963947 [ 430568 ] {} <Fatal> BaseDaemon: ########################################
2024.07.14 09:48:27.963977 [ 430568 ] {} <Fatal> BaseDaemon: (version 21.8.7.1 scm1.0.0.0, build id: B04FC607F093B4E2) (from thread 365031) (no query) Received signal Segmentation fault (11)
2024.07.14 09:48:27.963993 [ 430568 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2024.07.14 09:48:27.964006 [ 430568 ] {} <Fatal> BaseDaemon: Stack trace: 0x216753da 0x216d2ed8 0x21673c63 0x216ba386 0x26fbfeaf 0x26fb6ece 0x270e702d 0x26f84b2d
2024.07.14 09:48:27.968606 [ 430566 ] {} <Fatal> BaseDaemon: 3. void std::__1::__function::__policy_invoker<void (DB::Progress const&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::MPPQueryCoordinator::execute()::$_0, void (DB::Progress const&)> >(std::__1::__function::__policy_storage const*, DB::Progress const&) @ 0x216753da in /usr/bin/clickhouse
2024.07.14 09:48:27.969133 [ 430569 ] {} <Fatal> BaseDaemon: ########################################
2024.07.14 09:48:27.969169 [ 430569 ] {} <Fatal> BaseDaemon: (version 21.8.7.1 scm1.0.0.0, build id: B04FC607F093B4E2) (from thread 365019) (no query) Received signal Segmentation fault (11)
2024.07.14 09:48:27.969191 [ 430569 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2024.07.14 09:48:27.969205 [ 430569 ] {} <Fatal> BaseDaemon: Stack trace: 0x216753da 0x216d2ed8 0x21673c63 0x216ba386 0x26fbfeaf 0x26fb6ece 0x270e702d 0x26f84b2d
2024.07.14 09:48:27.970952 [ 430567 ] {} <Fatal> BaseDaemon: 3. void std::__1::__function::__policy_invoker<void (DB::Progress const&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::MPPQueryCoordinator::execute()::$_0, void (DB::Progress const&)> >(std::__1::__function::__policy_storage const*, DB::Progress const&) @ 0x216753da in /usr/bin/clickhouse
2024.07.14 09:48:27.973849 [ 430568 ] {} <Fatal> BaseDaemon: 3. void std::__1::__function::__policy_invoker<void (DB::Progress const&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::MPPQueryCoordinator::execute()::$_0, void (DB::Progress const&)> >(std::__1::__function::__policy_storage const*, DB::Progress const&) @ 0x216753da in /usr/bin/clickhouse
2024.07.14 09:48:27.978629 [ 430566 ] {} <Fatal> BaseDaemon: 4. DB::ProgressManager::onFinalProgress(unsigned int, unsigned int, DB::Progress const&) @ 0x216d2ed8 in /usr/bin/clickhouse
2024.07.14 09:48:27.979250 [ 430569 ] {} <Fatal> BaseDaemon: 3. void std::__1::__function::__policy_invoker<void (DB::Progress const&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::MPPQueryCoordinator::execute()::$_0, void (DB::Progress const&)> >(std::__1::__function::__policy_storage const*, DB::Progress const&) @ 0x216753da in /usr/bin/clickhouse
2024.07.14 09:48:27.981081 [ 430567 ] {} <Fatal> BaseDaemon: 4. DB::ProgressManager::onFinalProgress(unsigned int, unsigned int, DB::Progress const&) @ 0x216d2ed8 in /usr/bin/clickhouse
2024.07.14 09:48:27.983533 [ 430568 ] {} <Fatal> BaseDaemon: 4. DB::ProgressManager::onFinalProgress(unsigned int, unsigned int, DB::Progress const&) @ 0x216d2ed8 in /usr/bin/clickhouse
2024.07.14 09:48:27.987293 [ 430570 ] {} <Fatal> BaseDaemon: ########################################
2024.07.14 09:48:27.987323 [ 430570 ] {} <Fatal> BaseDaemon: (version 21.8.7.1 scm1.0.0.0, build id: B04FC607F093B4E2) (from thread 365015) (no query) Received signal Segmentation fault (11)
2024.07.14 09:48:27.987333 [ 430570 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2024.07.14 09:48:27.987352 [ 430570 ] {} <Fatal> BaseDaemon: Stack trace: 0x216753da 0x216d2ed8 0x21673c63 0x216ba386 0x26fbfeaf 0x26fb6ece 0x270e702d 0x26f84b2d
2024.07.14 09:48:27.988676 [ 430566 ] {} <Fatal> BaseDaemon: 5. DB::MPPQueryCoordinator::onFinalProgress(unsigned int, unsigned int, DB::Progress const&) @ 0x21673c63 in /usr/bin/clickhouse
2024.07.14 09:48:27.989017 [ 430569 ] {} <Fatal> BaseDaemon: 4. DB::ProgressManager::onFinalProgress(unsigned int, unsigned int, DB::Progress const&) @ 0x216d2ed8 in /usr/bin/clickhouse
2024.07.14 09:48:27.990533 [ 430571 ] {} <Fatal> BaseDaemon: ########################################
2024.07.14 09:48:27.990559 [ 430571 ] {} <Fatal> BaseDaemon: (version 21.8.7.1 scm1.0.0.0, build id: B04FC607F093B4E2) (from thread 365091) (no query) Received signal Segmentation fault (11)
2024.07.14 09:48:27.990572 [ 430571 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2024.07.14 09:48:27.990585 [ 430571 ] {} <Fatal> BaseDaemon: Stack trace: 0x216753da 0x216d2ed8 0x21673c63 0x216ba386 0x26fbfeaf 0x26fb6ece 0x270e702d 0x26f84b2d
2024.07.14 09:48:27.991133 [ 430567 ] {} <Fatal> BaseDaemon: 5. DB::MPPQueryCoordinator::onFinalProgress(unsigned int, unsigned int, DB::Progress const&) @ 0x21673c63 in /usr/bin/clickhouse
2024.07.14 09:48:27.993353 [ 430568 ] {} <Fatal> BaseDaemon: 5. DB::MPPQueryCoordinator::onFinalProgress(unsigned int, unsigned int, DB::Progress const&) @ 0x21673c63 in /usr/bin/clickhouse
2024.07.14 09:48:27.997247 [ 430570 ] {} <Fatal> BaseDaemon: 3. void std::__1::__function::__policy_invoker<void (DB::Progress const&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::MPPQueryCoordinator::execute()::$_0, void (DB::Progress const&)> >(std::__1::__function::__policy_storage const*, DB::Progress const&) @ 0x216753da in /usr/bin/clickhouse
2024.07.14 09:48:27.998675 [ 430566 ] {} <Fatal> BaseDaemon: 6. DB::PlanSegmentManagerRpcService::sendPlanSegmentStatus(google::protobuf::RpcController*, DB::Protos::SendPlanSegmentStatusRequest const*, DB::Protos::SendPlanSegmentStatusResponse*, google::protobuf::Closure*) @ 0x216ba386 in /usr/bin/clickhouse
2024.07.14 09:48:27.998874 [ 430569 ] {} <Fatal> BaseDaemon: 5. DB::MPPQueryCoordinator::onFinalProgress(unsigned int, unsigned int, DB::Progress const&) @ 0x21673c63 in /usr/bin/clickhouse
2024.07.14 09:48:28.000474 [ 430571 ] {} <Fatal> BaseDaemon: 3. void std::__1::__function::__policy_invoker<void (DB::Progress const&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::MPPQueryCoordinator::execute()::$_0, void (DB::Progress const&)> >(std::__1::__function::__policy_storage const*, DB::Progress const&) @ 0x216753da in /usr/bin/clickhouse
2024.07.14 09:48:28.001161 [ 430567 ] {} <Fatal> BaseDaemon: 6. DB::PlanSegmentManagerRpcService::sendPlanSegmentStatus(google::protobuf::RpcController*, DB::Protos::SendPlanSegmentStatusRequest const*, DB::Protos::SendPlanSegmentStatusResponse*, google::protobuf::Closure*) @ 0x216ba386 in /usr/bin/clickhouse
2024.07.14 09:48:28.003361 [ 430568 ] {} <Fatal> BaseDaemon: 6. DB::PlanSegmentManagerRpcService::sendPlanSegmentStatus(google::protobuf::RpcController*, DB::Protos::SendPlanSegmentStatusRequest const*, DB::Protos::SendPlanSegmentStatusResponse*, google::protobuf::Closure*) @ 0x216ba386 in /usr/bin/clickhouse
2024.07.14 09:48:28.007111 [ 430570 ] {} <Fatal> BaseDaemon: 4. DB::ProgressManager::onFinalProgress(unsigned int, unsigned int, DB::Progress const&) @ 0x216d2ed8 in /usr/bin/clickhouse
2024.07.14 09:48:28.008485 [ 430572 ] {} <Fatal> BaseDaemon: ########################################
2024.07.14 09:48:28.008507 [ 430572 ] {} <Fatal> BaseDaemon: (version 21.8.7.1 scm1.0.0.0, build id: B04FC607F093B4E2) (from thread 365085) (no query) Received signal Segmentation fault (11)
2024.07.14 09:48:28.008517 [ 430572 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2024.07.14 09:48:28.008526 [ 430572 ] {} <Fatal> BaseDaemon: Stack trace: 0x216753da 0x216d2ed8 0x21673c63 0x216ba386 0x26fbfeaf 0x26fb6ece 0x270e702d 0x26f84b2d
2024.07.14 09:48:28.008827 [ 430569 ] {} <Fatal> BaseDaemon: 6. DB::PlanSegmentManagerRpcService::sendPlanSegmentStatus(google::protobuf::RpcController*, DB::Protos::SendPlanSegmentStatusRequest const*, DB::Protos::SendPlanSegmentStatusResponse*, google::protobuf::Closure*) @ 0x216ba386 in /usr/bin/clickhouse
2024.07.14 09:48:28.010401 [ 430571 ] {} <Fatal> BaseDaemon: 4. DB::ProgressManager::onFinalProgress(unsigned int, unsigned int, DB::Progress const&) @ 0x216d2ed8 in /usr/bin/clickhouse
2024.07.14 09:48:28.013690 [ 430566 ] {} <Fatal> BaseDaemon: 7. /build/build_docker/../contrib/incubator-brpc/src/brpc/policy/baidu_rpc_protocol.cpp:0: brpc::policy::ProcessRpcRequest(brpc::InputMessageBase*) @ 0x26fbfeaf in /usr/bin/clickhouse
2024.07.14 09:48:28.016202 [ 430567 ] {} <Fatal> BaseDaemon: 7. /build/build_docker/../contrib/incubator-brpc/src/brpc/policy/baidu_rpc_protocol.cpp:0: brpc::policy::ProcessRpcRequest(brpc::InputMessageBase*) @ 0x26fbfeaf in /usr/bin/clickhouse
2024.07.14 09:48:28.017172 [ 430570 ] {} <Fatal> BaseDaemon: 5. DB::MPPQueryCoordinator::onFinalProgress(unsigned int, unsigned int, DB::Progress const&) @ 0x21673c63 in /usr/bin/clickhouse
2024.07.14 09:48:28.018078 [ 430568 ] {} <Fatal> BaseDaemon: 7. /build/build_docker/../contrib/incubator-brpc/src/brpc/policy/baidu_rpc_protocol.cpp:0: brpc::policy::ProcessRpcRequest(brpc::InputMessageBase*) @ 0x26fbfeaf in /usr/bin/clickhouse
2024.07.14 09:48:28.018490 [ 430572 ] {} <Fatal> BaseDaemon: 3. void std::__1::__function::__policy_invoker<void (DB::Progress const&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::MPPQueryCoordinator::execute()::$_0, void (DB::Progress const&)> >(std::__1::__function::__policy_storage const*, DB::Progress const&) @ 0x216753da in /usr/bin/clickhouse
2024.07.14 09:48:28.020309 [ 430571 ] {} <Fatal> BaseDaemon: 5. DB::MPPQueryCoordinator::onFinalProgress(unsigned int, unsigned int, DB::Progress const&) @ 0x21673c63 in /usr/bin/clickhouse
2024.07.14 09:48:28.021632 [ 430566 ] {} <Fatal> BaseDaemon: 8. /build/build_docker/../contrib/incubator-brpc/src/brpc/input_messenger.cpp:386: brpc::InputMessenger::OnNewMessages(brpc::Socket*) @ 0x26fb6ece in /usr/bin/clickhouse
2024.07.14 09:48:28.023727 [ 430569 ] {} <Fatal> BaseDaemon: 7. /build/build_docker/../contrib/incubator-brpc/src/brpc/policy/baidu_rpc_protocol.cpp:0: brpc::policy::ProcessRpcRequest(brpc::InputMessageBase*) @ 0x26fbfeaf in /usr/bin/clickhouse
2024.07.14 09:48:28.024205 [ 430567 ] {} <Fatal> BaseDaemon: 8. /build/build_docker/../contrib/incubator-brpc/src/brpc/input_messenger.cpp:386: brpc::InputMessenger::OnNewMessages(brpc::Socket*) @ 0x26fb6ece in /usr/bin/clickhouse
2024.07.14 09:48:28.026130 [ 430568 ] {} <Fatal> BaseDaemon: 8. /build/build_docker/../contrib/incubator-brpc/src/brpc/input_messenger.cpp:386: brpc::InputMessenger::OnNewMessages(brpc::Socket*) @ 0x26fb6ece in /usr/bin/clickhouse
2024.07.14 09:48:28.027441 [ 430570 ] {} <Fatal> BaseDaemon: 6. DB::PlanSegmentManagerRpcService::sendPlanSegmentStatus(google::protobuf::RpcController*, DB::Protos::SendPlanSegmentStatusRequest const*, DB::Protos::SendPlanSegmentStatusResponse*, google::protobuf::Closure*) @ 0x216ba386 in /usr/bin/clickhouse
2024.07.14 09:48:28.028583 [ 430572 ] {} <Fatal> BaseDaemon: 4. DB::ProgressManager::onFinalProgress(unsigned int, unsigned int, DB::Progress const&) @ 0x216d2ed8 in /usr/bin/clickhouse
2024.07.14 09:48:28.030374 [ 430571 ] {} <Fatal> BaseDaemon: 6. DB::PlanSegmentManagerRpcService::sendPlanSegmentStatus(google::protobuf::RpcController*, DB::Protos::SendPlanSegmentStatusRequest const*, DB::Protos::SendPlanSegmentStatusResponse*, google::protobuf::Closure*) @ 0x216ba386 in /usr/bin/clickhouse
2024.07.14 09:48:28.031512 [ 430569 ] {} <Fatal> BaseDaemon: 8. /build/build_docker/../contrib/incubator-brpc/src/brpc/input_messenger.cpp:386: brpc::InputMessenger::OnNewMessages(brpc::Socket*) @ 0x26fb6ece in /usr/bin/clickhouse
2024.07.14 09:48:28.038401 [ 430572 ] {} <Fatal> BaseDaemon: 5. DB::MPPQueryCoordinator::onFinalProgress(unsigned int, unsigned int, DB::Progress const&) @ 0x21673c63 in /usr/bin/clickhouse
2024.07.14 09:48:28.042609 [ 430570 ] {} <Fatal> BaseDaemon: 7. /build/build_docker/../contrib/incubator-brpc/src/brpc/policy/baidu_rpc_protocol.cpp:0: brpc::policy::ProcessRpcRequest(brpc::InputMessageBase*) @ 0x26fbfeaf in /usr/bin/clickhouse
2024.07.14 09:48:28.043819 [ 430566 ] {} <Fatal> BaseDaemon: 9.1. inlined from /build/build_docker/../contrib/libcxx/include/memory:1655: std::__1::unique_ptr<brpc::Socket, brpc::SocketDeleter>::reset(brpc::Socket*)
2024.07.14 09:48:28.043833 [ 430566 ] {} <Fatal> BaseDaemon: 9.2. inlined from /build/build_docker/../contrib/libcxx/include/memory:1612: ~unique_ptr
2024.07.14 09:48:28.043837 [ 430566 ] {} <Fatal> BaseDaemon: 9. /build/build_docker/../contrib/incubator-brpc/src/brpc/socket.cpp:1099: brpc::Socket::ProcessEvent(void*) @ 0x270e702d in /usr/bin/clickhouse
2024.07.14 09:48:28.044994 [ 430571 ] {} <Fatal> BaseDaemon: 7. /build/build_docker/../contrib/incubator-brpc/src/brpc/policy/baidu_rpc_protocol.cpp:0: brpc::policy::ProcessRpcRequest(brpc::InputMessageBase*) @ 0x26fbfeaf in /usr/bin/clickhouse
2024.07.14 09:48:28.046067 [ 430567 ] {} <Fatal> BaseDaemon: 9.1. inlined from /build/build_docker/../contrib/libcxx/include/memory:1655: std::__1::unique_ptr<brpc::Socket, brpc::SocketDeleter>::reset(brpc::Socket*)
2024.07.14 09:48:28.046083 [ 430567 ] {} <Fatal> BaseDaemon: 9.2. inlined from /build/build_docker/../contrib/libcxx/include/memory:1612: ~unique_ptr
2024.07.14 09:48:28.046087 [ 430567 ] {} <Fatal> BaseDaemon: 9. /build/build_docker/../contrib/incubator-brpc/src/brpc/socket.cpp:1099: brpc::Socket::ProcessEvent(void*) @ 0x270e702d in /usr/bin/clickhouse
2024.07.14 09:48:28.047953 [ 430568 ] {} <Fatal> BaseDaemon: 9.1. inlined from /build/build_docker/../contrib/libcxx/include/memory:1655: std::__1::unique_ptr<brpc::Socket, brpc::SocketDeleter>::reset(brpc::Socket*)
2024.07.14 09:48:28.047966 [ 430568 ] {} <Fatal> BaseDaemon: 9.2. inlined from /build/build_docker/../contrib/libcxx/include/memory:1612: ~unique_ptr
2024.07.14 09:48:28.047970 [ 430568 ] {} <Fatal> BaseDaemon: 9. /build/build_docker/../contrib/incubator-brpc/src/brpc/socket.cpp:1099: brpc::Socket::ProcessEvent(void*) @ 0x270e702d in /usr/bin/clickhouse
2024.07.14 09:48:28.048446 [ 430572 ] {} <Fatal> BaseDaemon: 6. DB::PlanSegmentManagerRpcService::sendPlanSegmentStatus(google::protobuf::RpcController*, DB::Protos::SendPlanSegmentStatusRequest const*, DB::Protos::SendPlanSegmentStatusResponse*, google::protobuf::Closure*) @ 0x216ba386 in /usr/bin/clickhouse
2024.07.14 09:48:28.050249 [ 430570 ] {} <Fatal> BaseDaemon: 8. /build/build_docker/../contrib/incubator-brpc/src/brpc/input_messenger.cpp:386: brpc::InputMessenger::OnNewMessages(brpc::Socket*) @ 0x26fb6ece in /usr/bin/clickhouse
2024.07.14 09:48:28.052795 [ 430571 ] {} <Fatal> BaseDaemon: 8. /build/build_docker/../contrib/incubator-brpc/src/brpc/input_messenger.cpp:386: brpc::InputMessenger::OnNewMessages(brpc::Socket*) @ 0x26fb6ece in /usr/bin/clickhouse
2024.07.14 09:48:28.053322 [ 430569 ] {} <Fatal> BaseDaemon: 9.1. inlined from /build/build_docker/../contrib/libcxx/include/memory:1655: std::__1::unique_ptr<brpc::Socket, brpc::SocketDeleter>::reset(brpc::Socket*)
2024.07.14 09:48:28.053335 [ 430569 ] {} <Fatal> BaseDaemon: 9.2. inlined from /build/build_docker/../contrib/libcxx/include/memory:1612: ~unique_ptr
2024.07.14 09:48:28.053340 [ 430569 ] {} <Fatal> BaseDaemon: 9. /build/build_docker/../contrib/incubator-brpc/src/brpc/socket.cpp:1099: brpc::Socket::ProcessEvent(void*) @ 0x270e702d in /usr/bin/clickhouse
2024.07.14 09:48:28.053813 [ 430566 ] {} <Fatal> BaseDaemon: 10. /build/build_docker/../contrib/incubator-brpc/src/bthread/task_group.cpp:304: bthread::TaskGroup::task_runner(long) @ 0x26f84b2d in /usr/bin/clickhouse
2024.07.14 09:48:28.056004 [ 430567 ] {} <Fatal> BaseDaemon: 10. /build/build_docker/../contrib/incubator-brpc/src/bthread/task_group.cpp:304: bthread::TaskGroup::task_runner(long) @ 0x26f84b2d in /usr/bin/clickhouse
2024.07.14 09:48:28.057757 [ 430568 ] {} <Fatal> BaseDaemon: 10. /build/build_docker/../contrib/incubator-brpc/src/bthread/task_group.cpp:304: bthread::TaskGroup::task_runner(long) @ 0x26f84b2d in /usr/bin/clickhouse
2024.07.14 09:48:28.062850 [ 430572 ] {} <Fatal> BaseDaemon: 7. /build/build_docker/../contrib/incubator-brpc/src/brpc/policy/baidu_rpc_protocol.cpp:0: brpc::policy::ProcessRpcRequest(brpc::InputMessageBase*) @ 0x26fbfeaf in /usr/bin/clickhouse
2024.07.14 09:48:28.063104 [ 430569 ] {} <Fatal> BaseDaemon: 10. /build/build_docker/../contrib/incubator-brpc/src/bthread/task_group.cpp:304: bthread::TaskGroup::task_runner(long) @ 0x26f84b2d in /usr/bin/clickhouse
2024.07.14 09:48:28.070671 [ 430572 ] {} <Fatal> BaseDaemon: 8. /build/build_docker/../contrib/incubator-brpc/src/brpc/input_messenger.cpp:386: brpc::InputMessenger::OnNewMessages(brpc::Socket*) @ 0x26fb6ece in /usr/bin/clickhouse
2024.07.14 09:48:28.071896 [ 430570 ] {} <Fatal> BaseDaemon: 9.1. inlined from /build/build_docker/../contrib/libcxx/include/memory:1655: std::__1::unique_ptr<brpc::Socket, brpc::SocketDeleter>::reset(brpc::Socket*)
2024.07.14 09:48:28.071912 [ 430570 ] {} <Fatal> BaseDaemon: 9.2. inlined from /build/build_docker/../contrib/libcxx/include/memory:1612: ~unique_ptr
2024.07.14 09:48:28.071917 [ 430570 ] {} <Fatal> BaseDaemon: 9. /build/build_docker/../contrib/incubator-brpc/src/brpc/socket.cpp:1099: brpc::Socket::ProcessEvent(void*) @ 0x270e702d in /usr/bin/clickhouse
2024.07.14 09:48:28.074583 [ 430571 ] {} <Fatal> BaseDaemon: 9.1. inlined from /build/build_docker/../contrib/libcxx/include/memory:1655: std::__1::unique_ptr<brpc::Socket, brpc::SocketDeleter>::reset(brpc::Socket*)
2024.07.14 09:48:28.074603 [ 430571 ] {} <Fatal> BaseDaemon: 9.2. inlined from /build/build_docker/../contrib/libcxx/include/memory:1612: ~unique_ptr
2024.07.14 09:48:28.074607 [ 430571 ] {} <Fatal> BaseDaemon: 9. /build/build_docker/../contrib/incubator-brpc/src/brpc/socket.cpp:1099: brpc::Socket::ProcessEvent(void*) @ 0x270e702d in /usr/bin/clickhouse
2024.07.14 09:48:28.081898 [ 430570 ] {} <Fatal> BaseDaemon: 10. /build/build_docker/../contrib/incubator-brpc/src/bthread/task_group.cpp:304: bthread::TaskGroup::task_runner(long) @ 0x26f84b2d in /usr/bin/clickhouse
2024.07.14 09:48:28.084491 [ 430571 ] {} <Fatal> BaseDaemon: 10. /build/build_docker/../contrib/incubator-brpc/src/bthread/task_group.cpp:304: bthread::TaskGroup::task_runner(long) @ 0x26f84b2d in /usr/bin/clickhouse
2024.07.14 09:48:28.092302 [ 430572 ] {} <Fatal> BaseDaemon: 9.1. inlined from /build/build_docker/../contrib/libcxx/include/memory:1655: std::__1::unique_ptr<brpc::Socket, brpc::SocketDeleter>::reset(brpc::Socket*)
2024.07.14 09:48:28.092317 [ 430572 ] {} <Fatal> BaseDaemon: 9.2. inlined from /build/build_docker/../contrib/libcxx/include/memory:1612: ~unique_ptr
2024.07.14 09:48:28.092322 [ 430572 ] {} <Fatal> BaseDaemon: 9. /build/build_docker/../contrib/incubator-brpc/src/brpc/socket.cpp:1099: brpc::Socket::ProcessEvent(void*) @ 0x270e702d in /usr/bin/clickhouse
2024.07.14 09:48:28.102229 [ 430572 ] {} <Fatal> BaseDaemon: 10. /build/build_docker/../contrib/incubator-brpc/src/bthread/task_group.cpp:304: bthread::TaskGroup::task_runner(long) @ 0x26f84b2d in /usr/bin/clickhouse
2024.07.14 09:48:28.261634 [ 430566 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: EACBB9EF5AE2A06BEDB8935164DA3F4D. There is no information about the reference checksum.
2024.07.14 09:48:28.263461 [ 430567 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: EACBB9EF5AE2A06BEDB8935164DA3F4D. There is no information about the reference checksum.
2024.07.14 09:48:28.265101 [ 430568 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: EACBB9EF5AE2A06BEDB8935164DA3F4D. There is no information about the reference checksum.
2024.07.14 09:48:28.270359 [ 430569 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: EACBB9EF5AE2A06BEDB8935164DA3F4D. There is no information about the reference checksum.
2024.07.14 09:48:28.289470 [ 430570 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: EACBB9EF5AE2A06BEDB8935164DA3F4D. There is no information about the reference checksum.
2024.07.14 09:48:28.292261 [ 430571 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: EACBB9EF5AE2A06BEDB8935164DA3F4D. There is no information about the reference checksum.
2024.07.14 09:48:28.309948 [ 430572 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: EACBB9EF5AE2A06BEDB8935164DA3F4D. There is no information about the reference checksum.
2024.07.14 09:48:49.133426 [ 365010 ] {} <Fatal> BaseDaemon: (version 21.8.7.1 scm 1.0.0.0, build id: B04FC607F093B4E2) (from thread 365088) (no query) generate core minidump path: /data/logs/byconity-server//b7d34ddc-0262-4b68-a66d16b6-0e77abdc.dmp
2024.07.14 09:49:55.085823 [ 430641 ] {} <Warning> Application: Calculated checksum of the binary: EACBB9EF5AE2A06BEDB8935164DA3F4D. There is no information about the reference checksum.

### Byconity-server程序产生的dump文件
[b7d34ddc-0262-4b68-a66d16b6-0e77abdc.dmp](https://github.com/user-attachments/files/16243872/b7d34ddc-0262-4b68-a66d16b6-0e77abdc.dmp)

**Comment by ixnzh** [comment]
已修复，待查看合并情况
