### ISSUE TITLE
0.4.2版本 新增配置cnch_merge_enable_batch_select/cnch_merge_max_total_rows_to_merge报错

### ISSUE THREAD

**Issue by xiongbl526** [ByConity/ByConity#1758]
(you don't have to strictly follow this form)

## Question
users.yaml文件
profiles:
  default:
    load_balancing: random
    log_queries: 1
    max_execution_time: 1000
    exchange_timeout_ms: 300000
    cnch_part_attach_limit: 300000
    cnch_merge_enable_batch_select: 1
    cnch_merge_max_total_rows_to_merge: 40000000
  新增配置后执行helm upgrade后报错<Error> Application: DB::Exception: Unknown setting cnch_merge_enable_batch_select SQLSTATE: 42000
  cnch_merge_max_total_rows_to_merge也报同样的错误 但是刚开始加的时候更新helm upgrade是没报错的 运行一段时间后server服务中突然报错 导致server有个Pod一直在重启 另外一台server的Pod是正常的

**Comment by smmsmm1988** [comment]
@xiongbl526 这些都是merge tree setting，是不是层级放错了？可以看看另一个正常的pod是怎么配置的

**Comment by xiongbl526** [comment]
> @xiongbl526 这些都是merge tree setting，是不是层级放错了？可以看看另一个正常的pod是怎么配置的

users.yaml不是公共的吗 正常的层级是怎么样的呢

**Comment by smmsmm1988** [comment]
> > @xiongbl526 这些都是merge tree setting，是不是层级放错了？可以看看另一个正常的pod是怎么配置的
> 
> users.yaml不是公共的吗 正常的层级是怎么样的呢

在server.yaml里配置<merge_tree>< cnch_merge_enable_batch_select >1</cnch_merge_enable_batch_select >< cnch_merge_max_total_rows_to_merge > 40000000 </cnch_merge_max_total_rows_to_merge ></merge_tree>

**Comment by xiongbl526** [comment]
> > > @xiongbl526 这些都是merge tree setting，是不是层级放错了？可以看看另一个正常的pod是怎么配置的
> > 
> > 
> > users.yaml不是公共的吗 正常的层级是怎么样的呢
> 
> 在server.yaml里配置<merge_tree>< cnch_merge_enable_batch_select >1</cnch_merge_enable_batch_select >< cnch_merge_max_total_rows_to_merge > 40000000 </cnch_merge_max_total_rows_to_merge ></merge_tree>

感谢
