### ISSUE TITLE
分桶场景下导入的大基数的roaringbitmap会自动优化成多个小的roaringbitmap存放到多个桶么

### ISSUE THREAD

**Issue by xieyanchun** [ByConity/ByConity#1763]
(you don't have to strictly follow this form)
分桶场景下导入的大基数的roaringbitmap会自动优化成多个小的roaringbitmap存放到多个桶么

**Comment by superhail** [comment]
bucket表目前应该是不会使用到这个feature的

**Comment by xieyanchun** [comment]
> bucket表目前应该是不会使用到这个feature的

那在原生clickhouse中 单个bitmap-本地表分片存放导入的方式，迁移到ByConity 只能聚合成一个大的bitmap再导入了么  这样会不会有性能下降。这块有特性规划么。
