### ISSUE TITLE
clickhouse23.3.22.3版本的clickhouse copier工具迁移clickhouse数据到0.4.2版本byconity报错账号密码不对

### ISSUE THREAD

**Issue by xiongbl526** [ByConity/ByConity#1765]
(you don't have to strictly follow this form)

## Question
之前使用0.3.2版本的byconity 可以正常迁移数据过来 上周升级Bcyonity到最新版本 今天再次跑clickhouse copier任务就报错
2024.07.22 03:20:45.555381 [ 23928 ] {} <Error> Application: An error occurred while processing partition 20240718: Code: 516. DB::Exception: Received from xxxxxxxxx. DB::Exception: Worker host:xxxxxxxxx, exception:Code: 516, e.displayText() = DB::Exception: : Authentication failed: password is incorrect or there is no user with such name SQLSTATE: HY000 (version 21.8.7.1) SQLSTATE: HY000. Stack trace:

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x2723c412 in /opt/byconity/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x1078cbc0 in /opt/byconity/bin/clickhouse
2. DB::MPPQueryCoordinator::execute() @ 0x2167270f in /opt/byconity/bin/clickhouse
3. DB::InterpreterSelectQueryUseOptimizer::execute() @ 0x2132bf60 in /opt/byconity/bin/clickhouse
4. DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::IAST>, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*) @ 0x21596843 in /opt/byconity/bin/clickhouse
5. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool) @ 0x21592595 in /opt/byconity/bin/clickhouse
6. DB::TCPHandler::runImpl() @ 0x222bbca3 in /opt/byconity/bin/clickhouse
7. DB::TCPHandler::run() @ 0x222ca8fc in /opt/byconity/bin/clickhouse
8. Poco::Net::TCPServerConnection::start() @ 0x271b1b4c in /opt/byconity/bin/clickhouse
9. Poco::Net::TCPServerDispatcher::run() @ 0x271b202c in /opt/byconity/bin/clickhouse
10. Poco::PooledThread::run() @ 0x2729913a in /opt/byconity/bin/clickhouse
11. Poco::ThreadImpl::runnableEntry(void*) @ 0x27296cec in /opt/byconity/bin/clickhouse
12. start_thread @ 0x7ea7 in /lib/x86_64-linux-gnu/libpthread-2.31.so
13. clone @ 0xfca2f in /lib/x86_64-linux-gnu/libc-2.31.so
: While executing Remote. (AUTHENTICATION_FAILED), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe2939d5 in /usr/bin/clickhouse
1. DB::readException(DB::ReadBuffer&, String const&, bool) @ 0xe2f6c1f in /usr/bin/clickhouse
2. DB::Connection::receiveException() const @ 0x14a5e805 in /usr/bin/clickhouse
3. DB::Connection::receivePacket() @ 0x14a66aed in /usr/bin/clickhouse
4. void boost::context::detail::fiber_entry<boost::context::detail::fiber_record<boost::context::fiber, FiberStack&, DB::PacketReceiver::Routine>>(boost::context::detail::transfer_t) @ 0x14a80317 in /usr/bin/clickhouse
 (version 23.3.22.3 (official build))

**Comment by superhail** [comment]
might relate to https://github.com/ByConity/ByConity/issues/1734

**Comment by xiongbl526** [comment]
thanks ，i try 21.8 clickhouse client？

**Comment by xiongbl526** [comment]
> might relate to #1734
我在byconity上执行时成功的 我试了21.11版本clickhouse-copier也不行
SELECT count()
FROM remote('10.30.207.138:32492', 'product._log', 'default', 'xxxxxxxxxxxxxxx')

Query id: a3b11358-34be-4244-adc5-7c51e0668532

┌───count()─┐
│ 716975000 │

**Comment by superhail** [comment]
@xiongbl526 can u offer a copy of your users.xml? (u can remove the sensitive informatoin)

**Comment by superhail** [comment]
你的Byconity版本是？

**Comment by xiongbl526** [comment]
0.4.2



---- 回复的原邮件 ----
| 发件人 | Alan ***@***.***> |
| 日期 | 2024年07月25日 10:14 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] clickhouse23.3.22.3版本的clickhouse copier工具迁移clickhouse数据到0.4.2版本byconity报错账号密码不对 (Issue #1765) |

你的Byconity版本是？

**Comment by xiongbl526** [comment]
> 你的Byconity版本是？

请问有什么结论吗

**Comment by xiongbl526** [comment]
我在23.4.2版本的clickhouse 中用remote 测试从0.4.2版本的bcyontiy中导入数据也是报错
exception:Code: 516, e.displayText() = DB::Exception: iotadmin: Authentication failed: password is incorrect or there is no user with such name SQLSTATE: HY000 (version 21.8.7.1) SQLSTATE: HY000. (AUTHENTICATION_FAILED)

**Comment by xiongbl526** [comment]
我在23.4.2版本的clickhouse 中用remote 测试从0.4.2版本的bcyontiy中导入数据也是报错
exception:Code: 516, e.displayText() = DB::Exception: iotadmin: Authentication failed: password is incorrect or there is no user with such name SQLSTATE: HY000 (version 21.8.7.1) SQLSTATE: HY000. (AUTHENTICATION_FAILED)



---- 回复的原邮件 ----
| 发件人 | Alan ***@***.***> |
| 日期 | 2024年07月25日 10:14 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] clickhouse23.3.22.3版本的clickhouse copier工具迁移clickhouse数据到0.4.2版本byconity报错账号密码不对 (Issue #1765) |

你的Byconity版本是？

**Comment by superhail** [comment]
https://github.com/superhail/ByConity/tree/fix-auth-0.4.2 试试这个分支

**Comment by superhail** [comment]
@xiongbl526 或者你可以先用21.8版本的clickhouse来导入数据，这个版本的clickhouse应该还是可以和Byconity适配的。

**Comment by xiongbl526** [comment]
谢谢，remote的问题用这个方法可以解决，但是copier工具还是报错



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月29日 10:03 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] clickhouse23.3.22.3版本的clickhouse copier工具迁移clickhouse数据到0.4.2版本byconity报错账号密码不对 (Issue #1765) |

@xiongbl526 可以先在byconity上添加一个和clickhouse相同的用户，这样就可以正常使用

**Comment by xiongbl526** [comment]
clickhouse copier好像是21.11版本才出来的
---- 回复的原邮件 ----
| 发件人 | Alan ***@***.***> |
| 日期 | 2024年07月28日 14:36 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] clickhouse23.3.22.3版本的clickhouse copier工具迁移clickhouse数据到0.4.2版本byconity报错账号密码不对 (Issue #1765) |

@xiongbl526 或者你可以先用21.8版本的clickhouse来导入数据，这个版本的clickhouse应该还是可以和Byconity适配的。

**Comment by superhail** [comment]
@xiongbl526 那这个呢https://github.com/superhail/ByConity/tree/fix-auth-0.4.2

**Comment by xiongbl526** [comment]
> @xiongbl526 可以先在byconity上添加一个和clickhouse相同的用户，这样就可以正常使用

remote是可以了

> https://github.com/superhail/ByConity/tree/fix-auth-0.4.2 试试这个分支 @xiongbl526

是属于v0.4.2-test 这个镜像吗？

**Comment by superhail** [comment]
> > @xiongbl526 可以先在byconity上添加一个和clickhouse相同的用户，这样就可以正常使用
> 
> remote是可以了
> 
> > https://github.com/superhail/ByConity/tree/fix-auth-0.4.2 试试这个分支 @xiongbl526
> 
> 是属于v0.4.2-test 这个镜像吗？

是v0.4.2拉出来的

**Comment by xiongbl526** [comment]
我怎么用呢，代码拉下来手动打镜像嘛？


---- 回复的原邮件 ----
| 发件人 | Alan ***@***.***> |
| 日期 | 2024年07月30日 11:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] clickhouse23.3.22.3版本的clickhouse copier工具迁移clickhouse数据到0.4.2版本byconity报错账号密码不对 (Issue #1765) |

@xiongbl526 可以先在byconity上添加一个和clickhouse相同的用户，这样就可以正常使用

remote是可以了

https://github.com/superhail/ByConity/tree/fix-auth-0.4.2 试试这个分支 @xiongbl526

是属于v0.4.2-test 这个镜像吗？

是v0.4.2拉出来的

**Comment by superhail** [comment]
https://github.com/ByConity/ByConity/releases/tag/0.4.2-testonly-2 @xiongbl526 用这个

**Comment by superhail** [comment]
@xiongbl526 这个试的结果如何了呀？如果没问题的话，我预计就按照这样来修复了

**Comment by xiongbl526** [comment]
今天会尽快测试，及时反馈结果



---- 回复的原邮件 ----
| 发件人 | Alan ***@***.***> |
| 日期 | 2024年07月31日 15:39 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] clickhouse23.3.22.3版本的clickhouse copier工具迁移clickhouse数据到0.4.2版本byconity报错账号密码不对 (Issue #1765) |

@xiongbl526 这个试的结果如何了呀？如果没问题的话，我预计就按照这样来修复了

**Comment by xiongbl526** [comment]
> @xiongbl526 这个试的结果如何了呀？如果没问题的话，我预计就按照这样来修复了

还是报错呢
exception:Code: 516, e.displayText() = DB::Exception: : Authentication failed: password is incorrect or there is no user with such name SQLSTATE: HY000 (version 21.8.7.1) SQLSTATE: HY000. Stack trace:

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x27bb0ad2 in /opt/byconity/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x10c1c7e0 in /opt/byconity/bin/clickhouse
2. DB::MPPQueryCoordinator::execute() @ 0x21da7924 in /opt/byconity/bin/clickhouse
3. DB::InterpreterSelectQueryUseOptimizer::execute() @ 0x21a3c340 in /opt/byconity/bin/clickhouse
4. DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::IAST>, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*) @ 0x21cca502 in /opt/byconity/bin/clickhouse
5. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool) @ 0x21cc5a75 in /opt/byconity/bin/clickhouse
6. DB::TCPHandler::runImpl() @ 0x22aefe63 in /opt/byconity/bin/clickhouse
7. DB::TCPHandler::run() @ 0x22afef1c in /opt/byconity/bin/clickhouse
8. Poco::Net::TCPServerConnection::start() @ 0x27b262cc in /opt/byconity/bin/clickhouse
9. Poco::Net::TCPServerDispatcher::run() @ 0x27b267ac in /opt/byconity/bin/clickhouse
10. Poco::PooledThread::run() @ 0x27c0d7fa in /opt/byconity/bin/clickhouse
11. Poco::ThreadImpl::runnableEntry(void*) @ 0x27c0b3ac in /opt/byconity/bin/clickhouse
12. start_thread @ 0x7ea7 in /lib/x86_64-linux-gnu/libpthread-2.31.so
13. clone @ 0xfca2f in /lib/x86_64-linux-gnu/libc-2.31.so
: While executing Remote. (AUTHENTICATION_FAILED), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe2939d5 in /usr/bin/clickhouse
1. DB::readException(DB::ReadBuffer&, String const&, bool) @ 0xe2f6c1f in /usr/bin/clickhouse
2. DB::Connection::receiveException() const @ 0x14a5e805 in /usr/bin/clickhouse
3. DB::Connection::receivePacket() @ 0x14a66aed in /usr/bin/clickhouse
4. void boost::context::detail::fiber_entry<boost::context::detail::fiber_record<boost::context::fiber, FiberStack&, DB::PacketReceiver::Routine>>(boost::context::detail::transfer_t) @ 0x14a80317 in /usr/bin/clickhouse
 (version 23.3.22.3 (official build))

**Comment by xiongbl526** [comment]
> @xiongbl526 这个试的结果如何了呀？如果没问题的话，我预计就按照这样来修复了

报账号密码错误但是byconity服务里迁移表的xxxx_piece_0分片表 能创建成功

**Comment by xiongbl526** [comment]
0.3.2版本是正常的


---- 回复的原邮件 ----
| 发件人 | Alan ***@***.***> |
| 日期 | 2024年07月31日 15:39 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] clickhouse23.3.22.3版本的clickhouse copier工具迁移clickhouse数据到0.4.2版本byconity报错账号密码不对 (Issue #1765) |

@xiongbl526 这个试的结果如何了呀？如果没问题的话，我预计就按照这样来修复了

**Comment by superhail** [comment]
@xiongbl526 你能把日志打包发下给我吗？

**Comment by xiongbl526** [comment]
好，只要server服务的吗



---- 回复的原邮件 ----
| 发件人 | Alan ***@***.***> |
| 日期 | 2024年08月01日 10:17 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] clickhouse23.3.22.3版本的clickhouse copier工具迁移clickhouse数据到0.4.2版本byconity报错账号密码不对 (Issue #1765) |

@xiongbl526 你能把日志打包发下给我吗？

**Comment by superhail** [comment]
都需要

**Comment by xiongbl526** [comment]
> 都需要
server 读和写的日志 
[server.log](https://github.com/user-attachments/files/16449377/server.log)
[default.log](https://github.com/user-attachments/files/16449378/default.log)
[write.log](https://github.com/user-attachments/files/16449380/write.log)

**Comment by superhail** [comment]
@xiongbl526 这个server的日志好像不完整。或许你可以给个复现的流程么？

**Comment by xiongbl526** [comment]
就是用23.3版本的clickhouse copier工具从23.4.2版本的clickhouse中迁移数据到0.4.2版本的byconity



---- 回复的原邮件 ----
| 发件人 | Alan ***@***.***> |
| 日期 | 2024年08月03日 15:53 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] clickhouse23.3.22.3版本的clickhouse copier工具迁移clickhouse数据到0.4.2版本byconity报错账号密码不对 (Issue #1765) |

@xiongbl526 这个server的日志好像不完整。或许你可以给个复现的流程么？

**Comment by superhail** [comment]
@xiongbl526 辛苦给个具体命令的最小复现case？

**Comment by xiongbl526** [comment]
这个不仅仅是一个命令，前期需要用到zk，将启动数据放在zk里在执行命令，辛苦查下呢



---- 回复的原邮件 ----
| 发件人 | Alan ***@***.***> |
| 日期 | 2024年08月03日 15:59 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] clickhouse23.3.22.3版本的clickhouse copier工具迁移clickhouse数据到0.4.2版本byconity报错账号密码不对 (Issue #1765) |

@xiongbl526 辛苦给个具体命令的最小复现case？

**Comment by superhail** [comment]
@xiongbl526 那先看下日志吧，你有完整的server日志么

**Comment by xiongbl526** [comment]
debug级别的吗？那我周一再给发一份，现在没法远程



---- 回复的原邮件 ----
| 发件人 | Alan ***@***.***> |
| 日期 | 2024年08月03日 16:06 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] clickhouse23.3.22.3版本的clickhouse copier工具迁移clickhouse数据到0.4.2版本byconity报错账号密码不对 (Issue #1765) |

@xiongbl526 那先看下日志吧，你有完整的server日志么

**Comment by superhail** [comment]
@xiongbl526 这个日志的级别已经是trace了，但是缺了一部分，可能是被刷到zip文件里

**Comment by xiongbl526** [comment]
好的，明白，我周一尽早重新发一份



---- 回复的原邮件 ----
| 发件人 | Alan ***@***.***> |
| 日期 | 2024年08月03日 16:13 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] clickhouse23.3.22.3版本的clickhouse copier工具迁移clickhouse数据到0.4.2版本byconity报错账号密码不对 (Issue #1765) |

@xiongbl526 这个日志的级别已经是trace了，但是缺了一部分，可能是被刷到zip文件里

**Comment by xiongbl526** [comment]
[default.log](https://github.com/user-attachments/files/16491649/default.log)
[write.log](https://github.com/user-attachments/files/16491811/write.log)

**Comment by xiongbl526** [comment]
[server1.log](https://github.com/user-attachments/files/16492077/server1.log)
[server2.log](https://github.com/user-attachments/files/16492085/server2.log)
server文件太大了 我分成两个上传的 辛苦看下

**Comment by superhail** [comment]
https://github.com/ByConity/ByConity/releases/tag/0.4.2-testonly-3 @xiongbl526 试下这个

**Comment by xiongbl526** [comment]
好的，辛苦



---- 回复的原邮件 ----
| 发件人 | Alan ***@***.***> |
| 日期 | 2024年08月07日 14:24 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] clickhouse23.3.22.3版本的clickhouse copier工具迁移clickhouse数据到0.4.2版本byconity报错账号密码不对 (Issue #1765) |

***@***.*** 试下这个

**Comment by xiongbl526** [comment]
麻烦看下下载这个镜像报错了 docker pull docker.io/byconity/byconity:0.4.2-testonly-3 Error response from daemon: manifest for byconity/byconity:0.4.2-testonly-3 not found: manifest unknown: manifest unknown



---- 回复的原邮件 ----
| 发件人 | Alan ***@***.***> |
| 日期 | 2024年08月07日 14:24 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] clickhouse23.3.22.3版本的clickhouse copier工具迁移clickhouse数据到0.4.2版本byconity报错账号密码不对 (Issue #1765) |

***@***.*** 试下这个

**Comment by nudles** [comment]
@xiongbl526 docker pull byconity-cn-beijing.cr.volces.com/byconity/byconity:0.4.2-testonly-3 pls try this.

**Comment by xiongbl526** [comment]
it works thanks



---- 回复的原邮件 ----
| 发件人 | Wei ***@***.***> |
| 日期 | 2024年08月08日 10:23 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] clickhouse23.3.22.3版本的clickhouse copier工具迁移clickhouse数据到0.4.2版本byconity报错账号密码不对 (Issue #1765) |

@xiongbl526 docker pull byconity-cn-beijing.cr.volces.com/byconity/byconity:0.4.2-testonly-3 pls try this.

**Comment by superhail** [comment]
@xiongbl526 问题解决了？

**Comment by xiongbl526** [comment]
> @xiongbl526 问题解决了？

是的  这个镜像可以迁移数据了
