### ISSUE TITLE
0.4.2版本 k8s部署 测试kafka引擎 存储表一直写入不了数据

### ISSUE THREAD

**Issue by xiongbl526** [ByConity/ByConity#1769]
(you don't have to strictly follow this form)

## Question
已创建存储表  kafka消费表 
CREATE TABLE a.b_consume
(
    `topic` String,
    `insert_time` DateTime DEFAULT now(),
    `dt` Date DEFAULT toDate(insert_time)
)
ENGINE = CnchKafka
SETTINGS kafka_broker_list = 'xxxxx', kafka_topic_list = 'xxxx,xxxx', kafka_group_name = 'byconity_kafka_consumer', kafka_num_consumers = 1, kafka_format = 'JSONEachRow', kafka_row_delimiter = '\n', kafka_cnch_vw_write = 'vw_kafka'
以及物化视图表
看cnch_system.cnch_kafka_log表里一直有刷新日志 
kafka消费独立pod中没有看到error日志 只有Debug> IRowInputFormat: Skipped 4 rows with errors while reading the input stream
但是消费的数据通过kafka-console-consumer.sh --bootstrap-server --topic xxx --from-beginning 看到的数据格式拷贝出来是正确的json格式

**Comment by ChanneRen** [comment]
这个应该是数据有解析异常，请检查一下 cnch_system.cnch_kafka_log，尤其注意是否有 PARSE_ERROR 类型的日志；如果有该日志，按照日志提示修改

**Comment by xiongbl526** [comment]
> 这个应该是数据有解析异常，请检查一下 cnch_system.cnch_kafka_log，尤其注意是否有 PARSE_ERROR 类型的日志；如果有该日志，按照日志提示修改
我看没有解析错误类型的日志呢
SELECT
    event_type,
    count(*)
FROM cnch_kafka_log
WHERE event_date = '2024-07-24'
GROUP BY event_type

Query id: 8b199ccb-3aed-4e7f-9b2a-ccbf8aa00081

┌─event_type─┬─count()─┐
│ POLL       │    1324 │
│ COMMIT     │    1325 │

**Comment by ChanneRen** [comment]
> > 这个应该是数据有解析异常，请检查一下 cnch_system.cnch_kafka_log，尤其注意是否有 PARSE_ERROR 类型的日志；如果有该日志，按照日志提示修改
> > 我看没有解析错误类型的日志呢
> > SELECT
> > event_type,
> > count(*)
> > FROM cnch_kafka_log
> > WHERE event_date = '2024-07-24'
> > GROUP BY event_type
> 
> Query id: 8b199ccb-3aed-4e7f-9b2a-ccbf8aa00081
> 
> ┌─event_type─┬─count()─┐ │ POLL │ 1324 │ │ COMMIT │ 1325 │

查询加个 sum(rows) ？看着是没有消费到数据。是不是今天没有生产数据？把日期选在报这条日志的日期看看呢？”Debug> IRowInputFormat: Skipped 4 rows with errors while reading the input stream“

**Comment by xiongbl526** [comment]
有生产数据的，另外一个flink任务在正常消费的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月24日 12:37 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] 0.4.2版本 k8s部署 测试kafka引擎 存储表一直写入不了数据 (Issue #1769) |

这个应该是数据有解析异常，请检查一下 cnch_system.cnch_kafka_log，尤其注意是否有 PARSE_ERROR 类型的日志；如果有该日志，按照日志提示修改
我看没有解析错误类型的日志呢
SELECT
event_type,
count(*)
FROM cnch_kafka_log
WHERE event_date = '2024-07-24'
GROUP BY event_type

Query id: 8b199ccb-3aed-4e7f-9b2a-ccbf8aa00081

┌─event_type─┬─count()─┐ │ POLL │ 1324 │ │ COMMIT │ 1325 │

查询加个 sum(rows) ？看着是没有消费到数据。是不是今天没有生产数据？把日期选在报这条日志的日期看看呢？”Debug> IRowInputFormat: Skipped 4 rows with errors while reading the input stream“

**Comment by xiongbl526** [comment]
> > > 这个应该是数据有解析异常，请检查一下 cnch_system.cnch_kafka_log，尤其注意是否有 PARSE_ERROR 类型的日志；如果有该日志，按照日志提示修改
> > > 我看没有解析错误类型的日志呢
> > > SELECT
> > > event_type,
> > > count(*)
> > > FROM cnch_kafka_log
> > > WHERE event_date = '2024-07-24'
> > > GROUP BY event_type
> > 
> > 
> > Query id: 8b199ccb-3aed-4e7f-9b2a-ccbf8aa00081
> > ┌─event_type─┬─count()─┐ │ POLL │ 1324 │ │ COMMIT │ 1325 │
> 
> 查询加个 sum(metric) ？看着是没有消费到数据。是不是今天没有生产数据？把日期选在报这条日志的日期看看呢？”Debug> IRowInputFormat: Skipped 4 rows with errors while reading the input stream“

SELECT
    event_type,
    count(*),
    sum(metric)
FROM cnch_system.cnch_kafka_log
WHERE event_date = '2024-07-24'
GROUP BY event_type

Query id: 74582e8a-ba14-4be9-ab6c-cc902c2b0eef

┌─event_type─┬─count()─┬─sum(metric)─┐
│ POLL       │    2233 │        7476 │
│ COMMIT     │    2233 │           0 │
└────────────┴─────────┴─────────────┘
请问metric和bytes代表啥意思

**Comment by xiongbl526** [comment]
> > > 这个应该是数据有解析异常，请检查一下 cnch_system.cnch_kafka_log，尤其注意是否有 PARSE_ERROR 类型的日志；如果有该日志，按照日志提示修改
> > > 我看没有解析错误类型的日志呢
> > > SELECT
> > > event_type,
> > > count(*)
> > > FROM cnch_kafka_log
> > > WHERE event_date = '2024-07-24'
> > > GROUP BY event_type
> > 
> > 
> > Query id: 8b199ccb-3aed-4e7f-9b2a-ccbf8aa00081
> > ┌─event_type─┬─count()─┐ │ POLL │ 1324 │ │ COMMIT │ 1325 │
> 
> 查询加个 sum(metric) ？看着是没有消费到数据。是不是今天没有生产数据？把日期选在报这条日志的日期看看呢？”Debug> IRowInputFormat: Skipped 4 rows with errors while reading the input stream“
存储表用的是其它的vm 这样有影响吗
CREATE TABLE a.b
(
topic String,
insert_time DateTime DEFAULT now(),
dt Date DEFAULT toDate(insert_time)
)SETTINGS storage_policy = 'cnch_default_oss', index_granularity = 8192, cnch_vw_default = 'vw_default', cnch_vw_write = 'vw_write'

**Comment by ChanneRen** [comment]
metric 代表数据行数，对应 POLL 就是从 kafka 消费到的消息条数；bytes 是对应数据大小

**Comment by ChanneRen** [comment]
你们这个有点奇怪呀，为什么 没有记录 PARSE_ERROR？方便给几条 topic 里写入的 消息吗，我们看看这边能不能复现

**Comment by xiongbl526** [comment]
> 你们这个有点奇怪呀，为什么 没有记录 PARSE_ERROR？方便给几条 topic 里写入的 消息吗，我们看看这边能不能复现

[quixote_ren@163.com]我发到你这个邮箱可以吗

**Comment by ChanneRen** [comment]
> > 你们这个有点奇怪呀，为什么 没有记录 PARSE_ERROR？方便给几条 topic 里写入的 消息吗，我们看看这边能不能复现
> 
> [[quixote_ren@163.com](mailto:quixote_ren@163.com)]我发到你这个邮箱可以吗

可以 de

**Comment by ChanneRen** [comment]
@xiongbl526 我这边测试了一下，数据确实有解析异常，报错信息：Code: 26, e.displayText() = DB::ParsingException: Cannot parse JSON string: expected opening quote: (while reading the value of key properties): (at row 1)
, Stack trace (when copying this message, always include the lines below):

**Comment by xiongbl526** [comment]
嗯，我给的数据有一条是异常的，但是cn_kafka_log里没有解析异常的日志，大部分消息体都是正常的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月24日 15:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] 0.4.2版本 k8s部署 测试kafka引擎 存储表一直写入不了数据 (Issue #1769) |

@xiongbl526 我这边测试了一下，数据确实有解析异常，报错信息：Code: 26, e.displayText() = DB::ParsingException: Cannot parse JSON string: expected opening quote: (while reading the value of key properties): (at row 1)
, Stack trace (when copying this message, always include the lines below):

**Comment by ChanneRen** [comment]
你给的两条数据 这个字段都是json object，默认都是解析不了的，需要添加配置。

至于 cnch_kafka_log 里没有解析异常的日志 确实我们这边没有复现。
你们可以先把这个配置input_format_json_read_objects_as_strings : true 加上，看看数据能否正常导入。

**Comment by xiongbl526** [comment]
数据导入成功了，谢谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月24日 15:53 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] 0.4.2版本 k8s部署 测试kafka引擎 存储表一直写入不了数据 (Issue #1769) |

你给的两条数据 这个字段都是json object，默认都是解析不了的，需要添加配置。

至于 cnch_kafka_log 里没有解析异常的日志 确实我们这边没有复现。
你们可以先把这个配置input_format_json_read_objects_as_strings : true 加上，看看数据能否正常导入。

**Comment by ChanneRen** [comment]
瞅了下代码，在 kafka 表配置了 DEFAULT 列的情况下，确实 cnch_system.cnch_kafka_log 会 cover 不到 PARSE_ERROR 的日志信息；这个我们内部安排修一下

**Comment by ChanneRen** [comment]
对，没有 DEFAULT 列能正常记录 PARSE_ERROR

**Comment by xiongbl526** [comment]
好的，辛苦修一下



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月24日 17:03 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] 0.4.2版本 k8s部署 测试kafka引擎 存储表一直写入不了数据 (Issue #1769) |

对，没有 DEFAULT 列能正常记录 PARSE_ERROR

**Comment by xiongbl526** [comment]
请问下kafka引擎表添加哪个配置可以调整写入parts的行数，就是攒批的量



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月24日 17:03 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] 0.4.2版本 k8s部署 测试kafka引擎 存储表一直写入不了数据 (Issue #1769) |

对，没有 DEFAULT 列能正常记录 PARSE_ERROR

**Comment by smmsmm1988** [comment]
> 请问下kafka引擎表添加哪个配置可以调整写入parts的行数，就是攒批的量
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年07月24日 17:03 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [ByConity/ByConity] 0.4.2版本 k8s部署 测试kafka引擎 存储表一直写入不了数据 (Issue #1769) | 对，没有 DEFAULT 列能正常记录 PARSE_ERROR — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

![image](https://github.com/user-attachments/assets/6569156d-390b-4fe0-af40-dca6ea66ce8c)

**Comment by xiongbl526** [comment]
请问可以把消费的json体通过物化视图保存到存储表指定的一个字段中，其它表字段又能正常到相应字段吗？



---- 回复的原邮件 ----
| 发件人 | Maomeng ***@***.***> |
| 日期 | 2024年07月25日 10:21 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] 0.4.2版本 k8s部署 测试kafka引擎 存储表一直写入不了数据 (Issue #1769) |

请问下kafka引擎表添加哪个配置可以调整写入parts的行数，就是攒批的量
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年07月24日 17:03 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [ByConity/ByConity] 0.4.2版本 k8s部署 测试kafka引擎 存储表一直写入不了数据 (Issue #1769) | 对，没有 DEFAULT 列能正常记录 PARSE_ERROR — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***>

image.png (view on web)

**Comment by ChanneRen** [comment]
用虚拟列 _content，存储表用 String 类型，在 VIEW 表 select 语句中加上 _content 字段就行，kafka 表不用动

**Comment by xiongbl526** [comment]
谢谢，可以的！
请问下如果kafka消费专用的vw所在宿主机宕机了，会保存位点信息待机器恢复后重新消费吗？保存在哪呢？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月25日 14:40 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] 0.4.2版本 k8s部署 测试kafka引擎 存储表一直写入不了数据 (Issue #1769) |

用虚拟列 _content，存储表用 String 类型，在 VIEW 表 select 语句中加上 _content 字段就行，kafka 表不用动

**Comment by ChanneRen** [comment]
会，保存在catalog里发自我的 iPhone在 2024年7月25日，16:06，xiongbl526 ***@***.***> 写道：﻿
谢谢，可以的！
请问下如果kafka消费专用的vw所在宿主机宕机了，会保存位点信息待机器恢复后重新消费吗？保存在哪呢？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月25日 14:40 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] 0.4.2版本 k8s部署 测试kafka引擎 存储表一直写入不了数据 (Issue #1769) |

用虚拟列 _content，存储表用 String 类型，在 VIEW 表 select 语句中加上 _content 字段就行，kafka 表不用动

**Comment by xiongbl526** [comment]
请问下kafka_topic_list是不是不支持 通配符 pre.*匹配多少topic



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月25日 21:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] 0.4.2版本 k8s部署 测试kafka引擎 存储表一直写入不了数据 (Issue #1769) |

会，保存在catalog里发自我的 iPhone在 2024年7月25日，16:06，xiongbl526 ***@***.***> 写道：﻿
谢谢，可以的！
请问下如果kafka消费专用的vw所在宿主机宕机了，会保存位点信息待机器恢复后重新消费吗？保存在哪呢？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月25日 14:40 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] 0.4.2版本 k8s部署 测试kafka引擎 存储表一直写入不了数据 (Issue #1769) |

用虚拟列 _content，存储表用 String 类型，在 VIEW 表 select 语句中加上 _content 字段就行，kafka 表不用动

**Comment by smmsmm1988** [comment]
> 请问下kafka_topic_list是不是不支持 通配符 pre.*匹配多少topic
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年07月25日 21:09 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [ByConity/ByConity] 0.4.2版本 k8s部署 测试kafka引擎 存储表一直写入不了数据 (Issue #1769) | 会，保存在catalog里发自我的 iPhone在 2024年7月25日，16:06，xiongbl526 ***@***.***> 写道：﻿ 谢谢，可以的！ 请问下如果kafka消费专用的vw所在宿主机宕机了，会保存位点信息待机器恢复后重新消费吗？保存在哪呢？
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年07月25日 14:40 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [ByConity/ByConity] 0.4.2版本 k8s部署 测试kafka引擎 存储表一直写入不了数据 (Issue #1769) | 用虚拟列 _content，存储表用 String 类型，在 VIEW 表 select 语句中加上 _content 字段就行，kafka 表不用动 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***> — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

理论上是支持的，但是内外部都没有用过。方便的话你可以试一下

**Comment by xiongbl526** [comment]
我试了不支持



---- 回复的原邮件 ----
| 发件人 | Maomeng ***@***.***> |
| 日期 | 2024年07月26日 17:35 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] 0.4.2版本 k8s部署 测试kafka引擎 存储表一直写入不了数据 (Issue #1769) |

请问下kafka_topic_list是不是不支持 通配符 pre.匹配多少topic
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年07月25日 21:09 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [ByConity/ByConity] 0.4.2版本 k8s部署 测试kafka引擎 存储表一直写入不了数据 (Issue #1769) | 会，保存在catalog里发自我的 iPhone在 2024年7月25日，16:06，xiongbl526 @.> 写道：﻿ 谢谢，可以的！ 请问下如果kafka消费专用的vw所在宿主机宕机了，会保存位点信息待机器恢复后重新消费吗？保存在哪呢？
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年07月25日 14:40 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [ByConity/ByConity] 0.4.2版本 k8s部署 测试kafka引擎 存储表一直写入不了数据 (Issue #1769) | 用虚拟列 _content，存储表用 String 类型，在 VIEW 表 select 语句中加上 _content 字段就行，kafka 表不用动 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.> — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.*>

理论上是支持的，但是内外部都没有用过。方便的话你可以试一下

**Comment by xiongbl526** [comment]
用log.*这种 .*格式是不行



---- 回复的原邮件 ----
| 发件人 | Maomeng ***@***.***> |
| 日期 | 2024年07月26日 17:35 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] 0.4.2版本 k8s部署 测试kafka引擎 存储表一直写入不了数据 (Issue #1769) |

请问下kafka_topic_list是不是不支持 通配符 pre.匹配多少topic
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年07月25日 21:09 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [ByConity/ByConity] 0.4.2版本 k8s部署 测试kafka引擎 存储表一直写入不了数据 (Issue #1769) | 会，保存在catalog里发自我的 iPhone在 2024年7月25日，16:06，xiongbl526 @.> 写道：﻿ 谢谢，可以的！ 请问下如果kafka消费专用的vw所在宿主机宕机了，会保存位点信息待机器恢复后重新消费吗？保存在哪呢？
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年07月25日 14:40 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [ByConity/ByConity] 0.4.2版本 k8s部署 测试kafka引擎 存储表一直写入不了数据 (Issue #1769) | 用虚拟列 _content，存储表用 String 类型，在 VIEW 表 select 语句中加上 _content 字段就行，kafka 表不用动 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.> — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.*>

理论上是支持的，但是内外部都没有用过。方便的话你可以试一下

**Comment by smmsmm1988** [comment]
> 我试了不支持
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | Maomeng ***@***.***> | | 日期 | 2024年07月26日 17:35 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [ByConity/ByConity] 0.4.2版本 k8s部署 测试kafka引擎 存储表一直写入不了数据 (Issue #1769) | 请问下kafka_topic_list是不是不支持 通配符 pre.匹配多少topic … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年07月25日 21:09 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [ByConity/ByConity] 0.4.2版本 k8s部署 测试kafka引擎 存储表一直写入不了数据 (Issue #1769) | 会，保存在catalog里发自我的 iPhone在 2024年7月25日，16:06，xiongbl526 @.> 写道：﻿ 谢谢，可以的！ 请问下如果kafka消费专用的vw所在宿主机宕机了，会保存位点信息待机器恢复后重新消费吗？保存在哪呢？ ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年07月25日 14:40 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [ByConity/ByConity] 0.4.2版本 k8s部署 测试kafka引擎 存储表一直写入不了数据 (Issue #1769) | 用虚拟列 _content，存储表用 String 类型，在 VIEW 表 select 语句中加上 _content 字段就行，kafka 表不用动 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.> — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.*> 理论上是支持的，但是内外部都没有用过。方便的话你可以试一下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

那应该是不支持的，先规避这种使用方法呢

**Comment by kevinthfang** [comment]
目前还有更多问题么？

**Comment by xiongbl526** [comment]
> 目前还有更多问题么？

没有了 希望kafka_topic_list能支持通配符 匹配多个topic

**Comment by xiongbl526** [comment]
我在byconity 0.3.2版本测试kafka引擎报错帮忙看下 Unknown Kafka setting kafka_input_format_json_read_objects_as_strings SQLSTATE: 22000.



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月30日 11:06 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] 0.4.2版本 k8s部署 测试kafka引擎 存储表一直写入不了数据 (Issue #1769) |

目前还有更多问题么？

**Comment by smmsmm1988** [comment]
> 我在byconity 0.3.2版本测试kafka引擎报错帮忙看下 Unknown Kafka setting kafka_input_format_json_read_objects_as_strings SQLSTATE: 22000.
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年07月30日 11:06 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [ByConity/ByConity] 0.4.2版本 k8s部署 测试kafka引擎 存储表一直写入不了数据 (Issue #1769) | 目前还有更多问题么？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

参数名字你是不是写错了，应该是input_format_json_read_objects_as_strings？

**Comment by xiongbl526** [comment]
也会报错unknown kafka setting 这个信息



---- 回复的原邮件 ----
| 发件人 | Maomeng ***@***.***> |
| 日期 | 2024年08月07日 10:15 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [ByConity/ByConity] 0.4.2版本 k8s部署 测试kafka引擎 存储表一直写入不了数据 (Issue #1769) |

我在byconity 0.3.2版本测试kafka引擎报错帮忙看下 Unknown Kafka setting kafka_input_format_json_read_objects_as_strings SQLSTATE: 22000.
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年07月30日 11:06 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [ByConity/ByConity] 0.4.2版本 k8s部署 测试kafka引擎 存储表一直写入不了数据 (Issue #1769) | 目前还有更多问题么？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***>

参数名字你是不是写错了，应该是input_format_json_read_objects_as_strings？

**Comment by smmsmm1988** [comment]
> input_format_json_read_objects_as_strings

0.3.2版本应该是不支持这个参数的，你可以用最新版本试一下
