### ISSUE TITLE
MergeParts 任务启动执行太慢

### ISSUE THREAD

**Issue by bright-zy** [ByConity/ByConity#1770]
(you don't have to strictly follow this form)

## Question
同一个表的离线跑批任务 2024-07-24 06:35:18 执行完成，MergeParts任务2024-07-24 09:24:16开始执行的，有什么参数调整，让离线数据同步完成后，尽快启动Merge

**Comment by smmsmm1988** [comment]
@bright-zy select toStartOfHour(event_time) as t, countIf(event_type = 1) as i, sumIf(num_source_parts , event_type = 2) as m from cnch(server, system.server_part_log) where event_date >= today() - 1 and database = 'xxx' and table = 'yyy' group by t order by t; 执行这个sql检查一下

**Comment by bright-zy** [comment]
> @bright-zy select toStartOfHour(event_time) as t, countIf(event_type = 1) as i, sumIf(num_source_parts , event_type = 2) as m from cnch(server, system.server_part_log) where event_date >= today() - 1 and database = 'xxx' and table = 'yyy' group by t order by t; 执行这个sql检查一下
@smmsmm1988  merge 能执行，就是离线同步完成后，隔好久才启动
<img width="371" alt="image" src="https://github.com/user-attachments/assets/a88d49c1-7747-4ee0-b0d2-feb53caf9044">

**Comment by smmsmm1988** [comment]
> > @bright-zy select toStartOfHour(event_time) as t, countIf(event_type = 1) as i, sumIf(num_source_parts , event_type = 2) as m from cnch(server, system.server_part_log) where event_date >= today() - 1 and database = 'xxx' and table = 'yyy' group by t order by t; 执行这个sql检查一下
> > @smmsmm1988  merge 能执行，就是离线同步完成后，隔好久才启动
> 
> <img alt="image" width="371" src="https://private-user-images.githubusercontent.com/102500454/351623578-a88d49c1-7747-4ee0-b0d2-feb53caf9044.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MTAwOTEsIm5iZiI6MTcyMTgwOTc5MSwicGF0aCI6Ii8xMDI1MDA0NTQvMzUxNjIzNTc4LWE4OGQ0OWMxLTc3NDctNGVlMC1iMGQyLWZlYjUzY2FmOTA0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQwODI5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjJjZDU5NDVkNDdlYTkyZDM1YzRlYmVmYWE0NGVkOWQzMDEzNzFjMWViOTdlY2E4Yjg1ZjFlM2ExYTM3MGI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NUae0Xi1xv22V2RXZ2PB0-isjSyuQ_1kFXoLsx6kyYs">

辛苦去server和dm的log里，grep一下这个表名，看看对应的log，时间范围就是今天早上6点到9点这段时间

**Comment by zeromem** [comment]
是 bucket 表吗？麻烦 也发一下 schema

**Comment by bright-zy** [comment]
> 是 bucket 表吗？麻烦 也发一下 schema

```
CREATE TABLE measure_olap.rpt_databus_task_run_detail_di_cube_v3
(
    `type` Int64,
    `type_name` String,
    `hive_table_name` String,
    `state_name` String,
    `core_flag` String,
    `version_no` String,
    `cluster_id` Int64,
    `task_name` String,
    `task_id` Int64,
    `info_sun_dt` Int64,
    `info_month` Int64,
    `info_year` Int64,
    `less_10` Int64,
    `more_10` Int64,
    `more_20` Int64,
    `more_30` Int64,
    `info_date` Date,
    `pt_count` Int64,
    `task_id_count_distinct` AggregateFunction(groupBitmap, UInt32),
    `run_duration_sum` Int64,
    `hive_table_name_count_distinct` AggregateFunction(groupBitmap, UInt32)
)
ENGINE = CnchMergeTree
PARTITION BY toYYYYMMDD(info_date)
ORDER BY rpt_databus_task_run_detail_di_type
SETTINGS parts_preload_level = 3, enable_local_disk_cache = 1, storage_policy = 'cnch_default_hdfs', index_granularity = 8192
```

**Comment by bright-zy** [comment]
> > > @bright-zy select toStartOfHour(event_time) as t, countIf(event_type = 1) as i, sumIf(num_source_parts , event_type = 2) as m from cnch(server, system.server_part_log) where event_date >= today() - 1 and database = 'xxx' and table = 'yyy' group by t order by t; 执行这个sql检查一下
> > > @smmsmm1988  merge 能执行，就是离线同步完成后，隔好久才启动
> > 
> > 
> > <img alt="image" width="371" src="https://private-user-images.githubusercontent.com/102500454/351623578-a88d49c1-7747-4ee0-b0d2-feb53caf9044.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MTAwOTEsIm5iZiI6MTcyMTgwOTc5MSwicGF0aCI6Ii8xMDI1MDA0NTQvMzUxNjIzNTc4LWE4OGQ0OWMxLTc3NDctNGVlMC1iMGQyLWZlYjUzY2FmOTA0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQwODI5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjJjZDU5NDVkNDdlYTkyZDM1YzRlYmVmYWE0NGVkOWQzMDEzNzFjMWViOTdlY2E4Yjg1ZjFlM2ExYTM3MGI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NUae0Xi1xv22V2RXZ2PB0-isjSyuQ_1kFXoLsx6kyYs">
> 
> 辛苦去server和dm的log里，grep一下这个表名，看看对应的log，时间范围就是今天早上6点到9点这段时间
[server.log](https://github.com/user-attachments/files/16369182/server.log)

**Comment by smmsmm1988** [comment]
> > > > @bright-zy select toStartOfHour(event_time) as t, countIf(event_type = 1) as i, sumIf(num_source_parts , event_type = 2) as m from cnch(server, system.server_part_log) where event_date >= today() - 1 and database = 'xxx' and table = 'yyy' group by t order by t; 执行这个sql检查一下
> > > > @smmsmm1988  merge 能执行，就是离线同步完成后，隔好久才启动
> > > 
> > > 
> > > <img alt="image" width="371" src="https://private-user-images.githubusercontent.com/102500454/351623578-a88d49c1-7747-4ee0-b0d2-feb53caf9044.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MTAwOTEsIm5iZiI6MTcyMTgwOTc5MSwicGF0aCI6Ii8xMDI1MDA0NTQvMzUxNjIzNTc4LWE4OGQ0OWMxLTc3NDctNGVlMC1iMGQyLWZlYjUzY2FmOTA0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQwODI5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjJjZDU5NDVkNDdlYTkyZDM1YzRlYmVmYWE0NGVkOWQzMDEzNzFjMWViOTdlY2E4Yjg1ZjFlM2ExYTM3MGI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NUae0Xi1xv22V2RXZ2PB0-isjSyuQ_1kFXoLsx6kyYs">
> > 
> > 
> > 辛苦去server和dm的log里，grep一下这个表名，看看对应的log，时间范围就是今天早上6点到9点这段时间
> > [server.log](https://github.com/user-attachments/files/16369182/server.log)
> 
> [dm.log](https://github.com/user-attachments/files/16369243/dm.log)

dm.log是不是里面的内容不对？

**Comment by bright-zy** [comment]
> > > > > @bright-zy select toStartOfHour(event_time) as t, countIf(event_type = 1) as i, sumIf(num_source_parts , event_type = 2) as m from cnch(server, system.server_part_log) where event_date >= today() - 1 and database = 'xxx' and table = 'yyy' group by t order by t; 执行这个sql检查一下
> > > > > @smmsmm1988  merge 能执行，就是离线同步完成后，隔好久才启动
> > > > 
> > > > 
> > > > <img alt="image" width="371" src="https://private-user-images.githubusercontent.com/102500454/351623578-a88d49c1-7747-4ee0-b0d2-feb53caf9044.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MTAwOTEsIm5iZiI6MTcyMTgwOTc5MSwicGF0aCI6Ii8xMDI1MDA0NTQvMzUxNjIzNTc4LWE4OGQ0OWMxLTc3NDctNGVlMC1iMGQyLWZlYjUzY2FmOTA0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQwODI5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjJjZDU5NDVkNDdlYTkyZDM1YzRlYmVmYWE0NGVkOWQzMDEzNzFjMWViOTdlY2E4Yjg1ZjFlM2ExYTM3MGI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NUae0Xi1xv22V2RXZ2PB0-isjSyuQ_1kFXoLsx6kyYs">
> > > 
> > > 
> > > 辛苦去server和dm的log里，grep一下这个表名，看看对应的log，时间范围就是今天早上6点到9点这段时间
> > > [server.log](https://github.com/user-attachments/files/16369182/server.log)
> > 
> > 
> > [dm.log](https://github.com/user-attachments/files/16369243/dm.log)
> 
> dm.log是不是里面的内容不对？

@smmsmm1988 
这个表的，没找到其他时间段的日志

**Comment by smmsmm1988** [comment]
@bright-zy 辛苦把server pod上的server.yaml和user.yaml发一下，我们看看配置上有没有什么需要关注的。涉及敏感信息的您可以隐去

**Comment by bright-zy** [comment]
> @bright-zy 辛苦把server pod上的server.yaml和user.yaml发一下，我们看看配置上有没有什么需要关注的。涉及敏感信息的您可以隐去
@smmsmm1988 
发现一个现象，有的是及时的，有的不及时merge，下面是及时merge的
<img width="298" alt="image" src="https://github.com/user-attachments/assets/fa4d6e7b-af57-4183-b4ad-16b3204272d5">
<img width="295" alt="image" src="https://github.com/user-attachments/assets/dc435d36-7a4a-4afc-8e31-1781a2907a1f">


[users.log](https://github.com/user-attachments/files/16372471/users.log)

[server.log](https://github.com/user-attachments/files/16372475/server.log)

**Comment by ho1messi** [comment]
> > > > @bright-zy select toStartOfHour(event_time) as t, countIf(event_type = 1) as i, sumIf(num_source_parts , event_type = 2) as m from cnch(server, system.server_part_log) where event_date >= today() - 1 and database = 'xxx' and table = 'yyy' group by t order by t; 执行这个sql检查一下
> > > > @smmsmm1988  merge 能执行，就是离线同步完成后，隔好久才启动
> > > 
> > > 
> > > <img alt="image" width="371" src="https://private-user-images.githubusercontent.com/102500454/351623578-a88d49c1-7747-4ee0-b0d2-feb53caf9044.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MTAwOTEsIm5iZiI6MTcyMTgwOTc5MSwicGF0aCI6Ii8xMDI1MDA0NTQvMzUxNjIzNTc4LWE4OGQ0OWMxLTc3NDctNGVlMC1iMGQyLWZlYjUzY2FmOTA0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQwODI5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjJjZDU5NDVkNDdlYTkyZDM1YzRlYmVmYWE0NGVkOWQzMDEzNzFjMWViOTdlY2E4Yjg1ZjFlM2ExYTM3MGI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NUae0Xi1xv22V2RXZ2PB0-isjSyuQ_1kFXoLsx6kyYs">
> > 
> > 
> > 辛苦去server和dm的log里，grep一下这个表名，看看对应的log，时间范围就是今天早上6点到9点这段时间
> > [server.log](https://github.com/user-attachments/files/16369182/server.log)
> 
> [dm.log](https://github.com/user-attachments/files/16369243/dm.log)

看日志是 partition selector 有点问题，似乎一直没有选到这个分区。从日志看，6:00～9:00 期间一直选出的 3 个 partition 里都没有这个新写入的分区（part 数一直只有 3 个），但是从日志看 server 没有重启，根据目前的实现看最新写入的分区应该会最优先选中才对。

```
2024.07.24 08:53:03.020791 [ 360034 ] {} <Debug> Catalog: Elapsed 0ms to get 3 parts in 3 partitions for table : measure_olap.rpt_databus_task_run_detail_di_cube_v3 (d4bf8600-809a-40f7-966c-65024380a294) , source : PartCache, ts : 451354921012822027
2024.07.24 08:53:03.021458 [ 360034 ] {} <Debug> measure_olap.rpt_databus_task_run_detail_di_cube_v3 (d4bf8600-809a-40f7-966c-65024380a294)(MergeMutateThread): There is no need to merge parts according to merge selector algorithm: dance
2024.07.24 08:53:03.021468 [ 360034 ] {} <Debug> measure_olap.rpt_databus_task_run_detail_di_cube_v3 (d4bf8600-809a-40f7-966c-65024380a294)(MergeMutateThread): Selected 0 candidate groups

直到这个时间才选出了这个包含 16 个 part 的分区
2024.07.24 09:24:15.513193 [ 360042 ] {} <Debug> Catalog: Elapsed 0ms to get 18 parts in 3 partitions for table : measure_olap.rpt_databus_task_run_detail_di_cube_v3 (d4bf8600-809a-40f7-966c-65024380a294) , source : PartCache, ts : 451355411874578446
2024.07.24 09:24:15.513855 [ 360042 ] {} <Debug> measure_olap.rpt_databus_task_run_detail_di_cube_v3 (d4bf8600-809a-40f7-966c-65024380a294)(MergeMutateThread): Selected 1 candidate groups
```

目前这里缺少日志不太好确定没选中这个分区的原因。我也不太清楚这个表一共有多少分区（从日志看好像是 53 个），暂时可以先调整下表配置增加每次选择的分区数量，以及降低 round robin 的间隔来尽量避免这种情况
```
alter table measure_olap.rpt_databus_task_run_detail_di_cube_v3 modify setting cnch_merge_round_robin_partitions_interval = 180, max_partition_for_multi_select = 10;
```

**Comment by zeromem** [comment]
> > > > > @bright-zy select toStartOfHour(event_time) as t, countIf(event_type = 1) as i, sumIf(num_source_parts , event_type = 2) as m from cnch(server, system.server_part_log) where event_date >= today() - 1 and database = 'xxx' and table = 'yyy' group by t order by t; 执行这个sql检查一下
> > > > > @smmsmm1988  merge 能执行，就是离线同步完成后，隔好久才启动
> > > > 
> > > > 
> > > > <img alt="image" width="371" src="https://private-user-images.githubusercontent.com/102500454/351623578-a88d49c1-7747-4ee0-b0d2-feb53caf9044.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MTAwOTEsIm5iZiI6MTcyMTgwOTc5MSwicGF0aCI6Ii8xMDI1MDA0NTQvMzUxNjIzNTc4LWE4OGQ0OWMxLTc3NDctNGVlMC1iMGQyLWZlYjUzY2FmOTA0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQwODI5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjJjZDU5NDVkNDdlYTkyZDM1YzRlYmVmYWE0NGVkOWQzMDEzNzFjMWViOTdlY2E4Yjg1ZjFlM2ExYTM3MGI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NUae0Xi1xv22V2RXZ2PB0-isjSyuQ_1kFXoLsx6kyYs">
> > > 
> > > 
> > > 辛苦去server和dm的log里，grep一下这个表名，看看对应的log，时间范围就是今天早上6点到9点这段时间
> > > [server.log](https://github.com/user-attachments/files/16369182/server.log)
> > 
> > 
> > [dm.log](https://github.com/user-attachments/files/16369243/dm.log)
> 
> 看日志是 partition selector 有点问题，似乎一直没有选到这个分区。从日志看，6:00～9:00 期间一直选出的 3 个 partition 里都没有这个新写入的分区（part 数一直只有 3 个），但是从日志看 server 没有重启，根据目前的实现看最新写入的分区应该会最优先选中才对。
> 
> ```
> 2024.07.24 08:53:03.020791 [ 360034 ] {} <Debug> Catalog: Elapsed 0ms to get 3 parts in 3 partitions for table : measure_olap.rpt_databus_task_run_detail_di_cube_v3 (d4bf8600-809a-40f7-966c-65024380a294) , source : PartCache, ts : 451354921012822027
> 2024.07.24 08:53:03.021458 [ 360034 ] {} <Debug> measure_olap.rpt_databus_task_run_detail_di_cube_v3 (d4bf8600-809a-40f7-966c-65024380a294)(MergeMutateThread): There is no need to merge parts according to merge selector algorithm: dance
> 2024.07.24 08:53:03.021468 [ 360034 ] {} <Debug> measure_olap.rpt_databus_task_run_detail_di_cube_v3 (d4bf8600-809a-40f7-966c-65024380a294)(MergeMutateThread): Selected 0 candidate groups
> 
> 直到这个时间才选出了这个包含 16 个 part 的分区
> 2024.07.24 09:24:15.513193 [ 360042 ] {} <Debug> Catalog: Elapsed 0ms to get 18 parts in 3 partitions for table : measure_olap.rpt_databus_task_run_detail_di_cube_v3 (d4bf8600-809a-40f7-966c-65024380a294) , source : PartCache, ts : 451355411874578446
> 2024.07.24 09:24:15.513855 [ 360042 ] {} <Debug> measure_olap.rpt_databus_task_run_detail_di_cube_v3 (d4bf8600-809a-40f7-966c-65024380a294)(MergeMutateThread): Selected 1 candidate groups
> ```
> 
> 目前这里缺少日志不太好确定没选中这个分区的原因。我也不太清楚这个表一共有多少分区（从日志看好像是 53 个），暂时可以先调整下表配置增加每次选择的分区数量，以及降低 round robin 的间隔来尽量避免这种情况
> 
> ```
> alter table measure_olap.rpt_databus_task_run_detail_di_cube_v3 modify setting cnch_merge_round_robin_partitions_interval = 180, max_partition_for_multi_select = 10;
> ```

Make sense. 比如一共 60 个 partitions，默认 round robin 间隔是 600s，默认每次选 partition 数量是 3，那完整 round robin 一轮需要 20 次，20*10 = 200min,差不多是 3 个小时。有可能是 partitionselector 初始化读 system.server_part_log 有问题

**Comment by bright-zy** [comment]
> > > > > > @bright-zy select toStartOfHour(event_time) as t, countIf(event_type = 1) as i, sumIf(num_source_parts , event_type = 2) as m from cnch(server, system.server_part_log) where event_date >= today() - 1 and database = 'xxx' and table = 'yyy' group by t order by t; 执行这个sql检查一下
> > > > > > @smmsmm1988  merge 能执行，就是离线同步完成后，隔好久才启动
> > > > > 
> > > > > 
> > > > > <img alt="image" width="371" src="https://private-user-images.githubusercontent.com/102500454/351623578-a88d49c1-7747-4ee0-b0d2-feb53caf9044.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MTAwOTEsIm5iZiI6MTcyMTgwOTc5MSwicGF0aCI6Ii8xMDI1MDA0NTQvMzUxNjIzNTc4LWE4OGQ0OWMxLTc3NDctNGVlMC1iMGQyLWZlYjUzY2FmOTA0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQwODI5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjJjZDU5NDVkNDdlYTkyZDM1YzRlYmVmYWE0NGVkOWQzMDEzNzFjMWViOTdlY2E4Yjg1ZjFlM2ExYTM3MGI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NUae0Xi1xv22V2RXZ2PB0-isjSyuQ_1kFXoLsx6kyYs">
> > > > 
> > > > 
> > > > 辛苦去server和dm的log里，grep一下这个表名，看看对应的log，时间范围就是今天早上6点到9点这段时间
> > > > [server.log](https://github.com/user-attachments/files/16369182/server.log)
> > > 
> > > 
> > > [dm.log](https://github.com/user-attachments/files/16369243/dm.log)
> > 
> > 
> > 看日志是 partition selector 有点问题，似乎一直没有选到这个分区。从日志看，6:00～9:00 期间一直选出的 3 个 partition 里都没有这个新写入的分区（part 数一直只有 3 个），但是从日志看 server 没有重启，根据目前的实现看最新写入的分区应该会最优先选中才对。
> > ```
> > 2024.07.24 08:53:03.020791 [ 360034 ] {} <Debug> Catalog: Elapsed 0ms to get 3 parts in 3 partitions for table : measure_olap.rpt_databus_task_run_detail_di_cube_v3 (d4bf8600-809a-40f7-966c-65024380a294) , source : PartCache, ts : 451354921012822027
> > 2024.07.24 08:53:03.021458 [ 360034 ] {} <Debug> measure_olap.rpt_databus_task_run_detail_di_cube_v3 (d4bf8600-809a-40f7-966c-65024380a294)(MergeMutateThread): There is no need to merge parts according to merge selector algorithm: dance
> > 2024.07.24 08:53:03.021468 [ 360034 ] {} <Debug> measure_olap.rpt_databus_task_run_detail_di_cube_v3 (d4bf8600-809a-40f7-966c-65024380a294)(MergeMutateThread): Selected 0 candidate groups
> > 
> > 直到这个时间才选出了这个包含 16 个 part 的分区
> > 2024.07.24 09:24:15.513193 [ 360042 ] {} <Debug> Catalog: Elapsed 0ms to get 18 parts in 3 partitions for table : measure_olap.rpt_databus_task_run_detail_di_cube_v3 (d4bf8600-809a-40f7-966c-65024380a294) , source : PartCache, ts : 451355411874578446
> > 2024.07.24 09:24:15.513855 [ 360042 ] {} <Debug> measure_olap.rpt_databus_task_run_detail_di_cube_v3 (d4bf8600-809a-40f7-966c-65024380a294)(MergeMutateThread): Selected 1 candidate groups
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 目前这里缺少日志不太好确定没选中这个分区的原因。我也不太清楚这个表一共有多少分区（从日志看好像是 53 个），暂时可以先调整下表配置增加每次选择的分区数量，以及降低 round robin 的间隔来尽量避免这种情况
> > ```
> > alter table measure_olap.rpt_databus_task_run_detail_di_cube_v3 modify setting cnch_merge_round_robin_partitions_interval = 180, max_partition_for_multi_select = 10;
> > ```
> 
> Make sense. 比如一共 60 个 partitions，默认 round robin 间隔是 600s，默认每次选 partition 数量是 3，那完整 round robin 一轮需要 20 次，20*10 = 200min,差不多是 3 个小时。有可能是 partitionselector 初始化读 system.server_part_log 有问题

@zeromem  我先调整下配置观察下，感谢

**Comment by ixnzh** [comment]
按照上述修改后不再出现了

**Comment by bright-zy** [comment]
如果我要配到配置文件中，让所有表生效，应该怎么配置了

**Comment by smmsmm1988** [comment]
> @zeromem 如果我要配到配置文件中，让所有表生效，应该怎么配置了

在配置文件里的<merge_tree></merge_tree>里对应添加配置项即可

**Comment by bright-zy** [comment]
> > @zeromem 如果我要配到配置文件中，让所有表生效，应该怎么配置了
> 
> 在配置文件里的<merge_tree></merge_tree>里对应添加配置项即可

收，我配置下

**Comment by ho1messi** [comment]
> 看日志有报错： PartitionSelector: Failed to load server_part_log digest information from system.server_part_log
> 
> 目前通过设置：alter table measure_olap.rpt_databus_task_run_detail_di_cube_v3 modify setting cnch_merge_round_robin_partitions_interval = 180, max_partition_for_multi_select = 10; 解决
> 
> server_part_log 加载失败可能是什么导致的？

这个问题近期内部版本有个修复，刚看了下 byconity 还没同步过来，怀疑可能也是同样的问题导致的报错。可以按这个修改一下试试

**Comment by smmsmm1988** [comment]
> > 看日志有报错： PartitionSelector: Failed to load server_part_log digest information from system.server_part_log
> > 目前通过设置：alter table measure_olap.rpt_databus_task_run_detail_di_cube_v3 modify setting cnch_merge_round_robin_partitions_interval = 180, max_partition_for_multi_select = 10; 解决
> > server_part_log 加载失败可能是什么导致的？
> 
> 这个问题近期内部版本有个修复，刚看了下 byconity 还没同步过来，怀疑可能也是同样的问题导致的报错。可以按这个修改一下试试
> 
> ![image](https://private-user-images.githubusercontent.com/11469361/360373719-72cd3753-705b-4a81-83a1-751f26815fc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTk2MTgsIm5iZiI6MTcyNDMxOTMxOCwicGF0aCI6Ii8xMTQ2OTM2MS8zNjAzNzM3MTktNzJjZDM3NTMtNzA1Yi00YTgxLTgzYTEtNzUxZjI2ODE1ZmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA5MzUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlN2UwODM3MDQ1MzRkZTJiM2RjN2FhYmUzZTllN2MxNTZlMTBhYmVkYzViM2Y2NWYxOTQ1MDk0OTkwOWVkOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JDypceSxw4YvHdio9QWPWfRd_WVAFHAzXWYVYiOIx58)

@nudles 可以帮忙看下，这个bugfix，内部两个月前已经fix了，但是目前还没有同步到master分支。可以辛苦帮忙cp一下

**Comment by smmsmm1988** [comment]
1.0.0版本解决了这个问题
