### ISSUE TITLE
集群节点间互相报对方节点超时，最后导致查询失败

### ISSUE THREAD

**Issue by xinip** [ByConity/ByConity#1772]
2024.07.25 10:28:10.509175 [ 445417 ] {53258122-2ab8-447e-a7a3-70ddb280e00d_1} (451379018391879682) <Error> Could not load marks from disk cache: Code: 2007, e.displayText() = DB::Exception: Fail to call DB.Protos.FileStreamService.acceptConnection, error code: 1008, msg: [E1008]Reached timeout=5000ms @172.24.151.208:8124 SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x2723c412 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x1078cbc0 in /usr/bin/clickhouse
2. DB::RpcClient::assertController(brpc::Controller const&, int) @ 0x2252218d in /usr/bin/clickhouse
3. DB::DistributedDataClient::createReadStream() @ 0x21f297ad in /usr/bin/clickhouse
4. DB::ReadBufferFromRpcStreamFile::ReadBufferFromRpcStreamFile(std::__1::shared_ptr<DB::DistributedDataClient> const&, unsigned long, char*, unsigned long) @ 0x22049e63 in /usr/bin/clickhouse
5. DB::MergeTreeMarksLoader::loadMarksImpl()::$_2::operator()() const @ 0x22045123 in /usr/bin/clickhouse
6. DB::MergeTreeMarksLoader::loadMarksImpl() @ 0x220436d4 in /usr/bin/clickhouse
7. DB::MergeTreeMarksLoader::loadMarks() @ 0x22042808 in /usr/bin/clickhouse
8. DB::MergeTreeMarksLoader::getMark(unsigned long, unsigned long) @ 0x22041f91 in /usr/bin/clickhouse
9. DB::MergeTreeReaderStreamWithSegmentCache::MergeTreeReaderStreamWithSegmentCache(DB::StorageID const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IDisk>, unsigned long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, long, unsigned long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, long, unsigned long, std::__1::deque<DB::MarkRange, std::__1::allocator<DB::MarkRange> > const&, DB::MergeTreeReaderSettings const&, DB::MarkCache*, DB::UncompressedCache*, DB::IDiskCache*, unsigned long, DB::PartHostInfo const&, DB::MergeTreeIndexGranularityInfo const*, std::__1::function<void (DB::ReadBufferFromFileBase::ProfileInfo)> const&, std::__1::function<void (DB::Progress const&)> const&, int, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) @ 0x22084210 in /usr/bin/clickhouse
10. std::__1::unique_ptr<DB::IMergeTreeReaderStream, std::__1::default_delete<DB::IMergeTreeReaderStream> > std::__1::__function::__policy_invoker<std::__1::unique_ptr<DB::IMergeTreeReaderStream, std::__1::default_delete<DB::IMergeTreeReaderStream> > ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::MergeTreeReaderCNCH::addStreamsIfNoBurden(DB::NameAndTypePair const&, std::__1::function<void (DB::ReadBufferFromFileBase::ProfileInfo)> const&, std::__1::function<void (DB::Progress const&)> const&, int, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::function<std::__1::unique_ptr<DB::IMergeTreeReaderStream, std::__1::default_delete<DB::IMergeTreeReaderStream> > ()>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::function<std::__1::unique_ptr<DB::IMergeTreeReaderStream, std::__1::default_delete<DB::IMergeTreeReaderStream> > ()> > > >*)::$_5::operator()(DB::ISerialization::SubstreamPath const&) const::'lambda'(), std::__1::unique_ptr<DB::IMergeTreeReaderStream, std::__1::default_delete<DB::IMergeTreeReaderStream> > ()> >(std::__1::__function::__policy_storage const*) @ 0x2206cc90 in /usr/bin/clickhouse
11. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::MergeTreeReaderCNCH::executeFileStreamBuilders(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::function<std::__1::unique_ptr<DB::IMergeTreeReaderStream, std::__1::default_delete<DB::IMergeTreeReaderStream> > ()>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::function<std::__1::unique_ptr<DB::IMergeTreeReaderStream, std::__1::default_delete<DB::IMergeTreeReaderStream> > ()> > > >&)::$_4, void ()> >(std::__1::__function::__policy_storage const*) @ 0x2206a62a in /usr/bin/clickhouse
12. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x107cc9f1 in /usr/bin/clickhouse
13. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0x107ce508 in /usr/bin/clickhouse
14. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x107c9100 in /usr/bin/clickhouse
15. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0x107cd57a in /usr/bin/clickhouse
16. ? @ 0x94ac3 in /usr/lib/x86_64-linux-gnu/libc.so.6
17. ? @ 0x126850 in /usr/lib/x86_64-linux-gnu/libc.so.6
 (version 21.8.7.1)

**Comment by inewzone** [comment]
你可以尝试在客户端添加参数 --receive_timeout=6000 --max_execution_time=3600 --exchange_timeout=3600000 --exchange_enable_multipath_reciever=0 例如clickhouse-client -h host --port 9010 --receive_timeout=6000 --max_execution_time=3600 --exchange_timeout=3600000 --exchange_enable_multipath_reciever=0

**Comment by xinip** [comment]
我这边发现2块NVME硬盘，在报错那一时刻开始在接下来的10分钟时间里每块NVME盘写入了近40GB的缓存数据，合计80GB缓存数据，总计计12台worker节点，都是一样的现象，会不会和读取冷数据过多，导致所有节点响应超时？

**Comment by xinip** [comment]
> 你可以尝试在客户端添加参数 --receive_timeout=6000 --max_execution_time=3600 --exchange_timeout=3600000 --exchange_enable_multipath_reciever=0 例如clickhouse-client -h host --port 9010 --receive_timeout=6000 --max_execution_time=3600 --exchange_timeout=3600000 --exchange_enable_multipath_reciever=0

这个exchange_enable_multipath_reciever参数加上去之后会不会让查询变慢？

**Comment by foreverneverer** [comment]
你开启了FileCacheStealing，看看出问题的时候CPU负载怎么样，看起来建立连接都失败了

**Comment by superhail** [comment]
@xinip 可以先看看加大disk cache的配置stealing_connection_timeout_ms能否解决

**Comment by xinip** [comment]
好的，谢谢，我这边试下看看有没有效果

**Comment by kevinthfang** [comment]
@xinip 现在还有问题么？

**Comment by xinip** [comment]
因为要重启worker才能改这个参数，我们现在临时关闭FileCacheStealing

**Comment by smmsmm1988** [comment]
@xinip 请问现在还有进一步的问题吗

**Comment by xinip** [comment]
> @xinip 请问现在还有进一步的问题吗

现在没有了，谢谢各位
