### ISSUE TITLE
安装TSO 服务失败

### ISSUE THREAD

**Issue by Le6688** [ByConity/ByConity#1782]
系统架构：x86_64 Red Hat Enterprise Linux Server 7.9 
Byconity 版本:0.4.1
安装TSO服务安装时提示信息如下：
Creating clickhouse group if it does not exist.
 groupadd -r clickhouse
groupadd: group 'clickhouse' already exists
Creating clickhouse user if it does not exist.
 useradd -r --shell /bin/false --home-dir /nonexistent -g clickhouse clickhouse
useradd: user 'clickhouse' already exists
Will set ulimits for clickhouse user in /etc/security/limits.d/clickhouse.conf.
 chown --recursive clickhouse:clickhouse '/etc/byconity-server'
Log directory /var/log/byconity-server already exists.
Data directory /var/lib/byconity-server already exists.
Data directory /var/lib/byconity-server/server_local_disk/data/0/ already exists.
Pid directory /var/run/byconity-server already exists.
 chown --recursive clickhouse:clickhouse '/var/log/byconity-server'
 chown --recursive clickhouse:clickhouse '/var/run/byconity-server'
 chown clickhouse:clickhouse '/var/lib/byconity-server'
 chown clickhouse:clickhouse '/var/lib/byconity-server/server_local_disk/data/0/'
Setting capabilities for clickhouse binary. This is optional.

**Comment by yuanzhubi** [comment]
这是一个安装的信息打印，请问遇到什么问题了么。

**Comment by Le6688** [comment]
> 这是一个安装的信息打印，请问遇到了什么问题。

我安装完成后，启动TSO 服务发现是没有这个服务的
systemctl status byconity-tso
Unit byconity-tso.service could not be found.

**Comment by yuanzhubi** [comment]
https://byconity.github.io/docs/deployment/package-deployment
这里有介绍安装tso的方法 sudo dpkg -i byconity-tso_0.4.0_amd64.deb  可以安装对应的版本试试？

**Comment by Le6688** [comment]
> https://byconity.github.io/docs/deployment/package-deployment 这里有介绍安装tso的方法 sudo dpkg -i byconity-tso_0.4.0_amd64.deb 可以安装对应的版本试试？

好的，我试一下0.4.0 的版本 .tar 和 rpm 格式的安装包都可以吧？

**Comment by yuanzhubi** [comment]
> > https://byconity.github.io/docs/deployment/package-deployment 这里有介绍安装tso的方法 sudo dpkg -i byconity-tso_0.4.0_amd64.deb 可以安装对应的版本试试？
> 
> 好的，我试一下0.4.0 的版本 .tar 和 rpm 格式的安装包都可以吧？

嗯，如果你是4.1可以考虑安装4.1

**Comment by Le6688** [comment]
> > > https://byconity.github.io/docs/deployment/package-deployment这里有介绍安装tso的方法 sudo dpkg -i byconity-tso_0.4.0_amd64.deb 可以安装对应的版本试试？
> > 
> > 
> > 好的，我试一下0.4.0的版本.tar和rpm格式的安装包都可以吧？
> 
> 嗯，如果你是4.1可以考虑安装4.1

换成4.0 的还是没有起来啊

[root@byconity config]# ll /var/log/byconity-server/
total 0
[root@byconity config]# systemctl status byconity-tso
● byconity-tso.service
   Loaded: not-found (Reason: No such file or directory)
   Active: failed (Result: resources) since Tue 2024-07-30 09:40:54 CST; 13min ago
 Main PID: 29431 (code=exited, status=107)

Jul 30 09:40:38 byconity.novalocal systemd[1]: Unit byconity-tso.service entered failed state.
Jul 30 09:40:38 byconity.novalocal systemd[1]: byconity-tso.service failed.
Jul 30 09:40:54 byconity.novalocal systemd[1]: byconity-tso.service holdoff time over, scheduling restart.
Jul 30 09:40:54 byconity.novalocal systemd[1]: byconity-tso.service failed to schedule restart job: Unit not found.
Jul 30 09:40:54 byconity.novalocal systemd[1]: Unit byconity-tso.service entered failed state.
Jul 30 09:40:54 byconity.novalocal systemd[1]: byconity-tso.service failed.
[root@byconity config]# systemctl start byconity-tso
Failed to start byconity-tso.service: Unit not found.

**Comment by yuanzhubi** [comment]
这个目前是已经安装成功了吧

**Comment by Le6688** [comment]
> 目前这个已经安装成功了吧

是的，目前安装完成了
