### ISSUE TITLE
Segmentation fault when execute insert into

### ISSUE THREAD

**Issue by JiangXiNJU** [ByConity/ByConity#179]
## Bug Report
![image](https://user-images.githubusercontent.com/22412775/226795787-16a3c053-5c57-4299-a755-5967544662bd.png)
![image](https://user-images.githubusercontent.com/22412775/226795834-244f6801-caac-4770-9b9a-126218545cba.png)
`[n196-081-196] 2023.03.22 03:33:05.131951 [ 286 ] <Fatal> BaseDaemon: ########################################
[n196-081-196] 2023.03.22 03:33:05.132052 [ 286 ] <Fatal> BaseDaemon: (version 21.8.7.1 scm 1.0.0.0, build id: 551E8F5B2EBF293E) (from thread 171) (query_id: b4a194b2-04f6-4451-b691-a81135d06eeb) Received signal Segmentation fault (11)
[n196-081-196] 2023.03.22 03:33:05.132090 [ 286 ] <Fatal> BaseDaemon: Address: 0xffffffffffffff58 Access: read. Address not mapped to object.
[n196-081-196] 2023.03.22 03:33:05.132127 [ 286 ] <Fatal> BaseDaemon: Stack trace: 0x14b6ae10 0x14a7c105 0x14058d72 0x140569ac 0x140560f4 0x140561ae 0x13aa1943 0x14d37caf 0x14d32b78 0x14d3fe5c 0x18f04c4c 0x18f0512c 0x18fe5dda 0x18fe398c 0x7f48ce31bea7 0x7f48cce2da2f
[n196-081-196] 2023.03.22 03:33:05.207677 [ 286 ] <Fatal> BaseDaemon: 3. /data01/minh.dao/git/ByConity/src/Storages/MergeTree/MergeTreeDataWriter.cpp:364: DB::MergeTreeDataWriter::writeTempPart(DB::BlockWithPartition&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>, unsigned long, long, long) @ 0x14b6ae10 in /root/app/usr/bin/clickhouse
[n196-081-196] 2023.03.22 03:33:05.263677 [ 286 ] <Fatal> BaseDaemon: 4. /data01/minh.dao/git/ByConity/src/Storages/MergeTree/MergeTreeBlockOutputStream.cpp:31: DB::MergeTreeBlockOutputStream::write(DB::Block const&) @ 0x14a7c105 in /root/app/usr/bin/clickhouse
[n196-081-196] 2023.03.22 03:33:05.323805 [ 286 ] <Fatal> BaseDaemon: 5. /data01/minh.dao/git/ByConity/src/DataStreams/PushingToViewsBlockOutputStream.cpp:190: DB::PushingToViewsBlockOutputStream::write(DB::Block const&) @ 0x14058d72 in /root/app/usr/bin/clickhouse
[n196-081-196] 2023.03.22 03:33:05.335528 [ 286 ] <Fatal> BaseDaemon: 6. /data01/minh.dao/git/ByConity/src/DataStreams/AddingDefaultBlockOutputStream.cpp:0: DB::AddingDefaultBlockOutputStream::write(DB::Block const&) @ 0x140569ac in /root/app/usr/bin/clickhouse
[n196-081-196] 2023.03.22 03:33:05.340081 [ 286 ] <Fatal> BaseDaemon: 7. /data01/minh.dao/git/ByConity/src/DataStreams/SquashingBlockOutputStream.cpp:0: DB::SquashingBlockOutputStream::finalize() @ 0x140560f4 in /root/app/usr/bin/clickhouse
[n196-081-196] 2023.03.22 03:33:05.344551 [ 286 ] <Fatal> BaseDaemon: 8.1. inlined from /data01/minh.dao/git/ByConity/contrib/libcxx/include/memory:2844: std::__1::shared_ptr<DB::IBlockOutputStream>::operator->() const
[n196-081-196] 2023.03.22 03:33:05.344578 [ 286 ] <Fatal> BaseDaemon: 8. /data01/minh.dao/git/ByConity/src/DataStreams/SquashingBlockOutputStream.cpp:51: DB::SquashingBlockOutputStream::writeSuffix() @ 0x140561ae in /root/app/usr/bin/clickhouse
[n196-081-196] 2023.03.22 03:33:05.354364 [ 286 ] <Fatal> BaseDaemon: 9.1. inlined from /data01/minh.dao/git/ByConity/src/Common/Stopwatch.h:32: Stopwatch::elapsedNanoseconds() const
[n196-081-196] 2023.03.22 03:33:05.354400 [ 286 ] <Fatal> BaseDaemon: 9.2. inlined from /data01/minh.dao/git/ByConity/src/Common/Stopwatch.h:34: Stopwatch::elapsedMilliseconds() const
[n196-081-196] 2023.03.22 03:33:05.354419 [ 286 ] <Fatal> BaseDaemon: 9. /data01/minh.dao/git/ByConity/src/DataStreams/CountingBlockOutputStream.cpp:78: DB::CountingBlockOutputStream::writeSuffix() @ 0x13aa1943 in /root/app/usr/bin/clickhouse
[n196-081-196] 2023.03.22 03:33:05.443781 [ 286 ] <Fatal> BaseDaemon: 10. /data01/minh.dao/git/ByConity/src/Server/TCPHandler.cpp:614: DB::TCPHandler::processInsertQuery(DB::Settings const&) @ 0x14d37caf in /root/app/usr/bin/clickhouse
[n196-081-196] 2023.03.22 03:33:05.524204 [ 286 ] <Fatal> BaseDaemon: 11.1. inlined from /data01/minh.dao/git/ByConity/src/Common/Stopwatch.h:43: Stopwatch::nanoseconds() const
[n196-081-196] 2023.03.22 03:33:05.524259 [ 286 ] <Fatal> BaseDaemon: 11.2. inlined from /data01/minh.dao/git/ByConity/src/Common/Stopwatch.h:28: Stopwatch::stop()
[n196-081-196] 2023.03.22 03:33:05.524280 [ 286 ] <Fatal> BaseDaemon: 11.3. inlined from /data01/minh.dao/git/ByConity/src/DataStreams/BlockIO.h:68: DB::BlockIO::onFinish()
[n196-081-196] 2023.03.22 03:33:05.524320 [ 286 ] <Fatal> BaseDaemon: 11. /data01/minh.dao/git/ByConity/src/Server/TCPHandler.cpp:366: DB::TCPHandler::runImpl() @ 0x14d32b78 in /root/app/usr/bin/clickhouse
[n196-081-196] 2023.03.22 03:33:05.620599 [ 286 ] <Fatal> BaseDaemon: 12. /data01/minh.dao/git/ByConity/src/Server/TCPHandler.cpp:1874: DB::TCPHandler::run() @ 0x14d3fe5c in /root/app/usr/bin/clickhouse
[n196-081-196] 2023.03.22 03:33:05.622078 [ 286 ] <Fatal> BaseDaemon: 13. /data01/minh.dao/git/ByConity/contrib/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x18f04c4c in /root/app/usr/bin/clickhouse
[n196-081-196] 2023.03.22 03:33:05.626651 [ 286 ] <Fatal> BaseDaemon: 14. /data01/minh.dao/git/ByConity/contrib/poco/Net/src/TCPServerDispatcher.cpp:114: Poco::Net::TCPServerDispatcher::run() @ 0x18f0512c in /root/app/usr/bin/clickhouse
[n196-081-196] 2023.03.22 03:33:05.630546 [ 286 ] <Fatal> BaseDaemon: 15.1. inlined from /data01/minh.dao/git/ByConity/contrib/poco/Foundation/include/Poco/ScopedLock.h:36: ScopedLock
[n196-081-196] 2023.03.22 03:33:05.630577 [ 286 ] <Fatal> BaseDaemon: 15. /data01/minh.dao/git/ByConity/contrib/poco/Foundation/src/ThreadPool.cpp:213: Poco::PooledThread::run() @ 0x18fe5dda in /root/app/usr/bin/clickhouse
[n196-081-196] 2023.03.22 03:33:05.633877 [ 286 ] <Fatal> BaseDaemon: 16.1. inlined from /data01/minh.dao/git/ByConity/contrib/poco/Foundation/include/Poco/SharedPtr.h:156: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >::assign(Poco::Runnable*)
[n196-081-196] 2023.03.22 03:33:05.633914 [ 286 ] <Fatal> BaseDaemon: 16.2. inlined from /data01/minh.dao/git/ByConity/contrib/poco/Foundation/include/Poco/SharedPtr.h:208: Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable> >::operator=(Poco::Runnable*)
[n196-081-196] 2023.03.22 03:33:05.633936 [ 286 ] <Fatal> BaseDaemon: 16. /data01/minh.dao/git/ByConity/contrib/poco/Foundation/src/Thread_POSIX.cpp:360: Poco::ThreadImpl::runnableEntry(void*) @ 0x18fe398c in /root/app/usr/bin/clickhouse
[n196-081-196] 2023.03.22 03:33:05.634009 [ 286 ] <Fatal> BaseDaemon: 17. start_thread @ 0x7ea7 in /lib/x86_64-linux-gnu/libpthread-2.31.so
[n196-081-196] 2023.03.22 03:33:05.634055 [ 286 ] <Fatal> BaseDaemon: 18. clone @ 0xfca2f in /lib/x86_64-linux-gnu/libc-2.31.so
[n196-081-196] 2023.03.22 03:33:05.759949 [ 286 ] <Fatal> BaseDaemon: Calculated checksum of the binary: 26CE6A2543BDC31DB6339A026B71E95F. There is no information about the reference checksum.

Exception on client:
Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from 127.0.0.1:18684 SQLSTATE: 22000

Connecting to 127.0.0.1:18684 as user default.
Code: 210. DB::NetException: Connection refused (127.0.0.1:18684) SQLSTATE: 08000`

### Briefly describe the bug
Segmentation fault when execute insert into
### How to Reproduce
`CREATE OR REPLACE TABLE test_jx
(
    id UInt64,
    name String
)
ENGINE = MergeTree
ORDER BY id;`

`insert into test_jx values(1,'1');`
### Version
use docker : byconity/byconity-server:stable which is pushed to repository

**Comment by hustnn** [comment]
Hi, the MergeTree engine is not used in ByConity. Can you use `ENGINE = MergeTree` ?

For the core of usage MergeTree, we will take a look.

**Comment by JiangXiNJU** [comment]
> Hi, the MergeTree engine is not used in ByConity. Can you use `ENGINE = MergeTree` ?
> 
> For the core of usage MergeTree, we will take a look.

Do you mean CnchMergeTree ?  CnchMergeTree is good.

**Comment by JiangXiNJU** [comment]
And I have an another question: the docker which I depolyed is not built on the current code of master. 
`docker pull byconity/byconity-server:stable` 
I use the docker command above to get it from public repository.
Is it very different from the current version ?

**Comment by hustnn** [comment]
> MergeTree

oh，yes, my fault, it is CnchMergeTree

**Comment by JiangXiNJU** [comment]
> And I have an another question: the docker which I depolyed is not built on the current code of master. `docker pull byconity/byconity-server:stable` I use the docker command above to get it from public repository. Is it very different from the current version ?

 ^^ we are now testing  Byconity, if `byconity/byconity-server:stable` is too old, we will rebuild the docker

**Comment by hustnn** [comment]
Yes, you can follow this guid to build https://github.com/ByConity/ByConity/blob/master/docker/executable_wrapper/Update_docker_image.md

**Comment by JiangXiNJU** [comment]
> Yes, you can follow this guid to build https://github.com/ByConity/ByConity/blob/master/docker/executable_wrapper/Update_docker_image.md
So,  You mean byconity/byconity-server:stable is indeed very different from the current version ?

**Comment by hustnn** [comment]
it is behind master but not too much.

**Comment by JiangXiNJU** [comment]
> it is behind master but not too much.

OK, thank you very mach!
