### ISSUE TITLE
jdbc连接byconity失败，但手动重试能正常运行

### ISSUE THREAD

**Issue by xiongbl526** [ByConity/ByConity#1791]
(you don't have to strictly follow this form)

## Question
版本:0.4.2

exception:Code: 160, e.displayText() = DB::Exception: Estimated query execution time (1332.9343319404625 seconds) is too long. Maximum: 1000. Estimated rows to process: 33505280: (while reading column user_id): (worker node: devops-byconity-vw-vw-default-0 while reading from part byconitysg/f6528681-3f42-a28e-a92d-7d0119750b77/ from mark 7 with max_rows_to_read = 32799): While executing MergeTreeThread SQLSTATE: HY000 (version 21.8.7.1) SQLSTATE: HY000 (version 21.8.7.1)
, server ClickHouseNode [uri=http://xxxxxxxxxxxxxx/default, options={socket_timeout=1000000}]

**Comment by xiongbl526** [comment]
但是我手动重试，很快就执行好了，已经连续两天出现这个问题了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月01日 10:21 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] jdbc连接byconity失败，但手动重试能正常运行 (Issue #1791) |

设置最大执行时间: settings max_execution_time = 10800000

**Comment by xinip** [comment]
我也是0.4.2，也出现了很多次，[xiongbl526](https://github.com/xiongbl526)你最后怎么解决的？

**Comment by xiongbl526** [comment]
额，我把最大执行时间的超时时间再调大了，这几天没有报错了，以前就给了1000s



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月05日 10:13 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [ByConity/ByConity] jdbc连接byconity失败，但手动重试能正常运行 (Issue #1791) |

我也是0.4.2，也出现了很多次，xiongbl526你最后怎么解决的？
