### ISSUE TITLE
表创建失败

### ISSUE THREAD

**Issue by Le6688** [ByConity/ByConity#1792]
创建表语句：
CREATE TABLE tab(`key` UInt64,`str` String,INDEX inv_idx(str) TYPE inverted(0) GRANULARITY 1)ENGINE = CnchMergeTree ORDER BY key SETTINGS index_granularity = 1024;
报错信息：
Received exception from server (version 21.8.7):
Code: 7002. DB::Exception: Received from localhost:9010. DB::Exception: Can't get process TSO request, type: GetTimestamp SQLSTATE: HY000.

**Comment by smmsmm1988** [comment]
tso server部署了吗

**Comment by Le6688** [comment]
> tso服务器部署了吗

部署了但是有问题，现在已经解决了

**Comment by smmsmm1988** [comment]
> > tso服务器部署了吗
> 
> 部署了但是有问题，现在已经解决了

嗯，一般这种情况大概率就是tso server有问题了
