### ISSUE TITLE
关于内存和磁盘占用高的问题

### ISSUE THREAD

**Issue by justinxiongbin** [ByConity/ByConity#1795]
我部署了一套ByConity，除了worker是读和写两个节点，其他组件都是一个节点，使用的是hdfs存储，

背景：我业务量不复杂，作为归档库使用，
           每天增量同步大约500w~1000w条数据，作为统计报表类使用，对性能要求不是太高，
           8核32G内存 800GB ssd磁盘，所以组件在一台机器上部署，
           利用datax每5分钟增量同步一次，merge应该不会过于频繁，
           目前大约总共5亿条数据

遇到如下问题：
1、服务内存占用特别高，有什么办法可以让内存占用低一点？
2、hadoop_datanode作为业务数据存储，占用28G，算比较低了，但hadoop_namenode不作为存储业务数据，也占用11G，是否算正常？
3、server 是不是会将hadoop_datanode的业务数据完整的在本地再存储一份？导致占用宿主机的磁盘空间？
4、worker_read 是不是会将hadoop_datanode的业务数据完整的在本地再存储一份？导致占用宿主机的磁盘空间？
5、worker_write 是不是会将hadoop_datanode的业务数据完整的在本地再存储一份？导致占用宿主机的磁盘空间？
6、如果我的场景性能要求不是很高，是否可以将server、worker中的缓存数据 只保留一份即可？如果可以的话，应该如何配置？
7、如果我不损坏fdb、hadoop_namenode、hadoop_datanode的情况下，其他的server、worker等各个组件，就算清除干净了重装，之前的业务数据，是否依然安全？，重新安装server、worker等组件，即可直接使用之前的业务数据？

**Comment by smmsmm1988** [comment]
@justinxiongbin 因为有些问题是同一个类别的，所以就统一回答如下了：
1、服务内存占用高需要看是什么导致的，是查询还是写入还是merge，这个不同的case有不同的调优方法；
2、server不会缓存业务数据，write worker也不会缓存业务数据（但是write worker执行insert into select from会缓存），只有read writer会缓存业务数据，所以业务数据只保留一份缓存；
3、fdb、hdfs不损坏的情况下，server、worker可以安全重启、重装
4、hdfs datanode、namenode对biconity来说是黑盒，这块我们也不清楚

**Comment by justinxiongbin** [comment]
> @justinxiongbin 因为有些问题是同一个类别的，所以就统一回答如下了： 1、服务内存占用高需要看是什么导致的，是查询还是写入还是merge，这个不同的case有不同的调优方法； 2、server不会缓存业务数据，write worker也不会缓存业务数据（但是write worker执行insert into select from会缓存），只有read writer会缓存业务数据，所以业务数据只保留一份缓存； 3、fdb、hdfs不损坏的情况下，server、worker可以安全重启、重装 4、hdfs datanode、namenode对biconity来说是黑盒，这块我们也不清楚

非常感谢老师的解答~

请问一下，对于read worker和write worker，想要达到清理磁盘空间的效果的话
1、是否可以配置自动清理缓存？
2、是否可以手动配置缓存?

**Comment by smmsmm1988** [comment]
缓存不会自动清理，需要手动清理缓存，命令为：alter disk cache drop table db.table settings virtual_warehouse = 'xxx', drop_vw_disk_cache = 1

对于server内存占用高，可以先看下是不是集群表比较多，且part数目比较多？

对于server占用磁盘空间增长，怀疑可能是log刷的太多了，可以进到server的容器中，通过du -sh来看哪个目录占用的高，就知道原因了。

**Comment by justinxiongbin** [comment]
> 缓存不会自动清理，需要手动清理缓存，命令为：alter disk cache drop table db.table settings virtual_warehouse = 'xxx', drop_vw_disk_cache = 1
> 
> 对于server内存占用高，可以先看下是不是集群表比较多，且part数目比较多？
> 
> 对于server占用磁盘空间增长，怀疑可能是log刷的太多了，可以进到server的容器中，通过du -sh来看哪个目录占用的高，就知道原因了。

1、server容器内，log不多，主要占用磁盘大的是unique_key_index_cache
<img width="574" alt="image" src="https://github.com/user-attachments/assets/160f9f45-a751-4728-96bb-9902fb1df23c">

2、我大概10张表，大表，都是按天分区的，其余几张小表 按照 月分区的。 整个业务schema，part数目只有300多个

**Comment by justinxiongbin** [comment]
> 缓存不会自动清理，需要手动清理缓存，命令为：alter disk cache drop table db.table settings virtual_warehouse = 'xxx', drop_vw_disk_cache = 1
> 
> 对于server内存占用高，可以先看下是不是集群表比较多，且part数目比较多？
> 
> 对于server占用磁盘空间增长，怀疑可能是log刷的太多了，可以进到server的容器中，通过du -sh来看哪个目录占用的高，就知道原因了。

1、server容器内，log不多，主要占用磁盘大的是unique_key_index_cache
<img width="574" alt="image" src="https://github.com/user-attachments/assets/160f9f45-a751-4728-96bb-9902fb1df23c">

2、我大概10张表，大表，都是按天分区的，其余几张小表 按照 月分区的。 整个业务schema，part数目只有300多个

**Comment by smmsmm1988** [comment]
@justinxiongbin 你这个server磁盘占用高，和unique表的缓存有关，可以调整如下参数：unique_key_index_disk_cache_max_bytes。默认是50GB，可以根据你的磁盘情况进行调整，配置完后重启生效

**Comment by smmsmm1988** [comment]
@justinxiongbin 请问还有进一步的问题吗

**Comment by justinxiongbin** [comment]
> table

alter disk cache drop table db.table settings virtual_warehouse = 'xxx', drop_vw_disk_cache = 1

**Comment by justinxiongbin** [comment]
> 缓存不会自动清理，需要手动清理缓存，命令为：alter disk cache drop table db.table settings virtual_warehouse = 'xxx', drop_vw_disk_cache = 1
> 
> 对于server内存占用高，可以先看下是不是集群表比较多，且part数目比较多？
> 
> 对于server占用磁盘空间增长，怀疑可能是log刷的太多了，可以进到server的容器中，通过du -sh来看哪个目录占用的高，就知道原因了。

alter disk cache drop table db.table settings virtual_warehouse = 'xxx', drop_vw_disk_cache = 1 
这个是对单张表进行释放worker缓存的吗？
这个语句是在ByConity客户端执行就可以吗？
执行一次，然后整个集群中的reader和writer都会释放缓存吗？

unique_key_index_disk_cache_max_bytes。默认是50GB，这个在什么地方修改？是直接在server.yml 中配置吗
<img width="897" alt="image" src="https://github.com/user-attachments/assets/ce6e74b6-0705-4c46-a1ce-0fbd9baf3429">

**Comment by smmsmm1988** [comment]
@justinxiongbin 1、是释放单张表的缓存，释放指定virtual_warehouse上的缓存，可以由客户端下发命令到server上执行；
2、是在server.yml中直接配置的，数据超出配置值后，按照LRU进行淘汰。
