### ISSUE TITLE
How to reduce memory usage for Kafka consumer consuming large wide tables.

### ISSUE THREAD

**Issue by skyoct** [ByConity/ByConity#1797]
## Question
We have two tables: 
Table A has over 2000 columns. 
Table B has over 200 columns.

Memory usage at different stages of Kafka consumer consumption is as follows.
Table A：
pull(3.14 GiB) -> write(11.56 GiB) -> commit(11.56 GiB)

Table B:
pull(3.04 GiB) -> write(4.88 GiB) -> commit(4.88 GiB)

They pull similar amounts of data, but differ by several times in the write phase. Is there a way to reduce the memory usage of Table A?

**Comment by smmsmm1988** [comment]
@skyoct hi, you can decrease the number of kafka_max_block_size for table A to reduce the number of rows consumed at a time.

**Comment by smmsmm1988** [comment]
> @smmsmm1988 Is this memory usage situation consistent with normal operation?

it depends on the schema of the table. If one table consists of so many columns, especially string, map, array columns, its memory usage could be large.

**Comment by kevinthfang** [comment]
Hi @skyoct do you still have questions about this?
