### ISSUE TITLE
Is it possible to get column size on  s3 disk

### ISSUE THREAD

**Issue by ozcelgozde** [ByConity/ByConity#1800]
## Question
I have a test table created with:
 ```
create table ed.tokenbf_test (
s String
)
ENGINE = CnchMergeTree 
ORDER BY s
SETTINGS index_granularity = 32768, storage_policy = 'cnch_default_s3'
```
and I insert 20M random strings to that table with: 
```
insert into ed.tokenbf_test (s) select
 substring(replaceRegexpAll(randomPrintableASCII(100), '[^a-zA-Z0-9]', ''), 1, 64) as s
from numbers_mt(20500000)
where length(s) = 64
LIMIT 20000000
```
when I run this command to get how much space the columns take on s3:
```
SELECT
    database,
    table,
    name,
    data_compressed_bytes,
    data_uncompressed_bytes,
    marks_bytes
FROM system.cnch_columns
WHERE database='ed' and table = 'tokenbf_test'
```

This returns:
<img width="1499" alt="Screenshot 2024-08-05 at 19 55 43" src="https://github.com/user-attachments/assets/95095463-9760-42bf-9385-8e3067d5328c">

Is there another way of getting this info?

**Comment by smmsmm1988** [comment]
@ozcelgozde hi, I'm sorry that currently there is no way of getting used space based on columns. You can get used space based on parts by using system.cnch_parts.
