### ISSUE TITLE
HDFS上面有很多合并前文件没有清理

### ISSUE THREAD

**Issue by xinip** [ByConity/ByConity#1802]
byconity-server在8月4号18：40到23点卡住了，重启后，过一段时间发现4号这一段时间里，有很多小文件存在，看样子是没有GC掉，有什么命令可以手动清理这些未清理的GC文件？谢谢

**Comment by xinip** [comment]
没效果，文件数并没有减少[smmsmm1988](https://github.com/smmsmm1988)

**Comment by smmsmm1988** [comment]
> 没效果，文件数并没有减少 @smmsmm1988

这些小文件确定都是无效文件吗，还是说小文件都是有效的part文件。可以通过访问system.cnch_parts看下当前系统中有效的part数目，看看和小文件是否对应的上

**Comment by xinip** [comment]
没清理的文件在这个表找不到，到现在也没有自动清理，我也不敢删除

**Comment by zeromem** [comment]
`system.cnch_trash_items_info` 可以查下这张系统表，看看对应的表是不是有一些残留的 trash_items

**Comment by fky2015** [comment]
如果表的 part 数量不大的话，可以直接查看 `system.cnch_trash_items` （part 级别），否则可以看 `system.cnch_trash_items_info` （table 级别）；以判断是否有残留的 trash_items。

如果没有，需要观察对应 part 的 transaction 在 `system.cnch_transactions` 中的情况。如果为 Finished 或者不存在；则怀疑是数据泄漏了。目前在 0.4.2 上确实可能存在这个问题。

在 0.4.2 上一个非常粗略的判断流程如下：
```mermaid
flowchart TD
    A[怀疑数据泄漏] --> B{是否在 system.cnch_parts 中}
    B -->|No| C{是否在 system.cnch_trash_items 中}
    B -->|Yes| D{观察 system.cnch_parts 中 part 的 end_ts}
    D -->|end_ts>0| D1[一阶段 GC 不及时]
    D -->|end_ts==0| D2[一阶段 GC 或者 Merge 不及时]
    D1 --> GC1_END(尝试 system gc DB.TB 或者等待升级)
    D2 --> GC1_END
    D2 --> MERGE(调整 Merge 频率)
    C -->|Yes| C1[二阶段 GC 不及时]
    C1 --> GC2_END(尝试 system gc DB.TB 或者调整 GC 参数)
    C -->|No| E{对应 part 的 txn 在 system.cnch_transactions 的状态是什么}
    E -->|不存在| E1[有可能数据泄漏（还需要排除 mutation 相关的可能性）]
    E -->|status == Finished| E2[存在数据泄露]
    E -->|status == Aborted| E3[Txn 回收不及时]
    E3 --> E3_END(ByConity 1.0 将修复此问题)
    E2 --> DELETE(可以考虑手动删除数据)
```

**Comment by smmsmm1988** [comment]
@xinip 你好，请问残留的数据手动清理掉了吗？相关的bugfix已经合入到版本1.0.0了。

**Comment by xinip** [comment]
> 如果表的 part 数量不大的话，可以直接查看 `system.cnch_trash_items` （part 级别），否则可以看 `system.cnch_trash_items_info` （table 级别）；以判断是否有残留的 trash_items。
> 
> 如果没有，需要观察对应 part 的 transaction 在 `system.cnch_transactions` 中的情况。如果为 Finished 或者不存在；则怀疑是数据泄漏了。目前在 0.4.2 上确实可能存在这个问题。
> 
> 在 0.4.2 上一个非常粗略的判断流程如下：
> 
> ```mermaid
> flowchart TD
>     A[怀疑数据泄漏] --> B{是否在 system.cnch_parts 中}
>     B -->|No| C{是否在 system.cnch_trash_items 中}
>     B -->|Yes| D{观察 system.cnch_parts 中 part 的 end_ts}
>     D -->|end_ts>0| D1[一阶段 GC 不及时]
>     D -->|end_ts==0| D2[一阶段 GC 或者 Merge 不及时]
>     D1 --> GC1_END(尝试 system gc DB.TB 或者等待升级)
>     D2 --> GC1_END
>     D2 --> MERGE(调整 Merge 频率)
>     C -->|Yes| C1[二阶段 GC 不及时]
>     C1 --> GC2_END(尝试 system gc DB.TB 或者调整 GC 参数)
>     C -->|No| E{对应 part 的 txn 在 system.cnch_transactions 的状态是什么}
>     E -->|不存在| E1[有可能数据泄漏（还需要排除 mutation 相关的可能性）]
>     E -->|status == Finished| E2[存在数据泄露]
>     E -->|status == Aborted| E3[Txn 回收不及时]
>     E3 --> E3_END(ByConity 1.0 将修复此问题)
>     E2 --> DELETE(可以考虑手动删除数据)
> ```

在这两个表里面都没找到遗留的未清理part信息，现在有一张表有9万多个文件，感觉应该有不少小文件没清理

**Comment by xinip** [comment]
你们可以提供一个工具，可以手动执行这个工具清理遗留未清理的小文件，从0.3.2到现在的0.4.2感觉小文件问题一直没停过。

**Comment by fky2015** [comment]
> 你们可以提供一个工具，可以手动执行这个工具清理遗留未清理的小文件，从0.3.2到现在的0.4.2感觉小文件问题一直没停过。

目前编写这样的工具有困难：
1. 我们有处理类似任务的工具，但是不太适配社区的工作流。
2. 有一些 part 无法在代价很小的方式下判断是否应该删除。
3. 涉及到删数据的功能必须经过比较严格的测试，这样会拉低 ROI。

> 到时候这张表我们只能废弃掉旧表，新建表才能解决这种问题。

由于目前 0.4.3 及以下在存在 Abort 相关的数据泄露，所以我比较建议：
1. 升级到 v1.0.0 以上。
2. 通过导入到新表解决问题。

（另外）对于实时导入的表，可以根据其 TTL 来直接筛选出过期分区的文件。

**Comment by smmsmm1988** [comment]
@xinip 你好，如 @fky2015 所说，提供这样的工具确实有点困难，非常抱歉带来的不便。因为目前0.4.2版本有这样的残留bug，所以即便手动清理完当前残留的了，后续可能还会堆积新的残留。所以最高效的方式，就是先升级到没有残留bug的版本，然后重新导入到新表，来根本解决问题。

**Comment by xinip** [comment]
> @xinip 你好，如 @fky2015 所说，提供这样的工具确实有点困难，非常抱歉带来的不便。因为目前0.4.2版本有这样的残留bug，所以即便手动清理完当前残留的了，后续可能还会堆积新的残留。所以最高效的方式，就是先升级到没有残留bug的版本，然后重新导入到新表，来根本解决问题。

等你们的1.1版本发布了，我们再升级吧，因为业务已经在使用了，我们开始注重稳定性了。

**Comment by smmsmm1988** [comment]
> > @xinip 你好，如 @fky2015 所说，提供这样的工具确实有点困难，非常抱歉带来的不便。因为目前0.4.2版本有这样的残留bug，所以即便手动清理完当前残留的了，后续可能还会堆积新的残留。所以最高效的方式，就是先升级到没有残留bug的版本，然后重新导入到新表，来根本解决问题。
> 
> 等你们的1.1版本发布了，我们再升级吧，因为业务已经在使用了，我们开始关注稳定性了，等你们1.0版本稳定后我们再升级，已经有几十TB数据在上面了，除了残留小文件问题，其他还没出现太大问题。

OK

**Comment by smmsmm1988** [comment]
等新版本1.0稳定后升级，根本解决这个问题
