### ISSUE TITLE
0.3.2版本 国内k8s部署 加上timezone 后  启动异常

### ISSUE THREAD

**Issue by xiongbl526** [ByConity/ByConity#1803]
(you don't have to strictly follow this form)

## Question
在values.yaml  configOverwrite配置项中加上timezone: Asia/Shanghai   helm upgrade之后 fdb-storage 以及fdb-log等组件pod自动被删除了 实例删除冲洗部署  服务也起不来

**Comment by xiongbl526** [comment]
我知道问题出在哪里了 
之前我改了byconity-deploy/chart/byconity/charts/fdb-operator/templates/crds目录下apps.foundationdb.org_foundationdbbackups.yaml  
apps.foundationdb.org_foundationdbclusters.yaml  
apps.foundationdb.org_foundationdbrestores.yaml三个文件里的spec.names.plural内容 因为我这边要在同一个命名空间下 部署多个bycontiy实例  昨天在部署第二个实例时报错CustomResourceDefinition 已存在 导致无法部署  后面我改了第二个实例部署文件里spec.names.plural内容 后面部署成功了  
现在看来改spec.names.plural不是根本解决的办法，请问有其它方法避免CustomResourceDefinition报错吗

**Comment by yuanzhubi** [comment]
一定要在同一个命名空间下 部署多个bycontiy实例么？好像这个模版不支持这样用

**Comment by xiongbl526** [comment]
因为一类的之前都是放在一个命名空间下



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月08日 15:11 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] 0.3.2版本 国内k8s部署 加上timezone 后  启动异常 (Issue #1803) |

一定要在同一个命名空间下 部署多个bycontiy实例么？好像这个模版不支持这样用
