### ISSUE TITLE
0.3.2版本 kafka引擎解析数据异常

### ISSUE THREAD

**Issue by xiongbl526** [ByConity/ByConity#1804]
(you don't have to strictly follow this form)

## Question
查看cnch_system.cnch_kafka_log日志
报错 DB::Exception: Cannot parse JSON string: expected opening quote: (while reading the value of key properties): 
内容: {"terminalBrand":"realme","project":"Base","clientOS":"Android","language":"zh_CN","platformId":"3232esdfwfwfwrw","terminalId":"csdwer232423423fwefw","clientVersion":"0.0.0","ttid":"234242dewf2323","userId":5698,"terminalType":"Android","terminalModel":"3453432442","terminalName":"2342342342","clientType":"phone","clientProtocolVersion":"0.0.0","countryCode":"CN","appid":"derwrwerw","clientOV":"Android 12","loginIp":"127.0.0.1","time":1723024995130,"event":"sdfwsfwewrw","region":"hz","properties":{"_flush_time":1723024997564,"$element_path":"werwerwerwrew","$screen_name":"werwrwrwrwwer","$element_id":"iv_pic"}}

**Comment by smmsmm1988** [comment]
![image](https://github.com/user-attachments/assets/ea44b775-aa92-4018-926e-2e5dc19a25d2)

**Comment by xiongbl526** [comment]
> ![image](https://private-user-images.githubusercontent.com/7722001/356061594-ea44b775-aa92-4018-926e-2e5dc19a25d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwODYzMDgsIm5iZiI6MTcyMzA4NjAwOCwicGF0aCI6Ii83NzIyMDAxLzM1NjA2MTU5NC1lYTQ0Yjc3NS1hYTkyLTQwMTgtOTI2ZS0yZTVkYzE5YTI1ZDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDhUMDMwMDA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGU0MzY1NmQ0NzFiZmE2ZjVkOTlkMDkyZDY2MGY0ZjUxMmQyYmM0YTU5MGY5ZTExYTY1M2QyNmJlMmI1Yjc4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eO8PXbe9pBHfCOktEA6NeuV8xtvh7J9XdUw9ZDgLOg4)



> ![image](https://private-user-images.githubusercontent.com/7722001/356061594-ea44b775-aa92-4018-926e-2e5dc19a25d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwODYzMDgsIm5iZiI6MTcyMzA4NjAwOCwicGF0aCI6Ii83NzIyMDAxLzM1NjA2MTU5NC1lYTQ0Yjc3NS1hYTkyLTQwMTgtOTI2ZS0yZTVkYzE5YTI1ZDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDhUMDMwMDA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGU0MzY1NmQ0NzFiZmE2ZjVkOTlkMDkyZDY2MGY0ZjUxMmQyYmM0YTU5MGY5ZTExYTY1M2QyNmJlMmI1Yjc4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eO8PXbe9pBHfCOktEA6NeuV8xtvh7J9XdUw9ZDgLOg4)

input_format_json_read_objects_as_strings这个配置是新版本才有的 0.3.2版本没有 不过现在准备用新版本了  谢谢

**Comment by smmsmm1988** [comment]
> > ![image](https://private-user-images.githubusercontent.com/7722001/356061594-ea44b775-aa92-4018-926e-2e5dc19a25d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwODYzMDgsIm5iZiI6MTcyMzA4NjAwOCwicGF0aCI6Ii83NzIyMDAxLzM1NjA2MTU5NC1lYTQ0Yjc3NS1hYTkyLTQwMTgtOTI2ZS0yZTVkYzE5YTI1ZDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDhUMDMwMDA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGU0MzY1NmQ0NzFiZmE2ZjVkOTlkMDkyZDY2MGY0ZjUxMmQyYmM0YTU5MGY5ZTExYTY1M2QyNmJlMmI1Yjc4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eO8PXbe9pBHfCOktEA6NeuV8xtvh7J9XdUw9ZDgLOg4)
> 
> > ![image](https://private-user-images.githubusercontent.com/7722001/356061594-ea44b775-aa92-4018-926e-2e5dc19a25d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwODYzMDgsIm5iZiI6MTcyMzA4NjAwOCwicGF0aCI6Ii83NzIyMDAxLzM1NjA2MTU5NC1lYTQ0Yjc3NS1hYTkyLTQwMTgtOTI2ZS0yZTVkYzE5YTI1ZDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDhUMDMwMDA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGU0MzY1NmQ0NzFiZmE2ZjVkOTlkMDkyZDY2MGY0ZjUxMmQyYmM0YTU5MGY5ZTExYTY1M2QyNmJlMmI1Yjc4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eO8PXbe9pBHfCOktEA6NeuV8xtvh7J9XdUw9ZDgLOg4)
> 
> input_format_json_read_objects_as_strings这个配置是新版本才有的 0.3.2版本没有 不过现在准备用新版本了 谢谢

嗯，用新版本吧，新版本在稳定性和功能上都有提升
