### ISSUE TITLE
It is failed to read mrk file and the part is broken of system.query_thread_log table.

### ISSUE THREAD

**Issue by zhaojintaozhao** [ByConity/ByConity#1805]
(you don't have to strictly follow this form)

## Bug Report
It is failed to read mrk file and the part is broken of system.query_thread_log table.
This problem occurs occasionally and has occurred once on three servers.

### Briefly describe the bug
There are some error logs in clickhouse-server:
```
<Errorr> auto DB::IBackgroundJobExecutor::execute (DB::JobAndPool)::(anonymous class)::operator()() const[198] : Code: 33, e.displayText()=DB::Exception: Cannot read all data. Bytes read: 385024. Bytes expected: 421888.: while loading marks from file: {path}/{part-uuid}/__ProfileEvents__%27CannotWriteToWriteBufferDiscard%27.null.mrk, file size: 421888, remote file offset: 0 SQLSTATE: 22000, Stack trace
Poco::Exception::Exception (...)
DB::Exception::Exception (...)
DB::ReadBuffer::readStrict(char*, unsigned long)...
DB::MergeTreeMarksLoader::LoadMarksImpi()...
DB::MergeTreeMarksLoader::loadMarks()...
DB::MergeTreeMarksLoader::getMark...
```
Then I restart the clickhouse-server, this broken part was removed to the detached directory. 

### Analysis Process
This broken part belongs to the 'System.query_thread_log'.  
The file name 'CannotWriteToWriteBufferDiscard' is a key of column 'ProfileEvents' of the table 'System.query_thread_log'

This table has many columns with different sizes of mrk files.
```
| size   | filename                                                     |
| ------ | ------------------------------------------------------------ |
| 421888 | port.mrk                                                     |
| 421888 | peak_memory_usage.mrk                                        |
| 421888 | \_\_ProfileEvents\_\_%27ArenaAllocBytes%27.mrk               |
| 421888 | \_\_ProfileEvents\_\_%27ArenaAllocBytes%27.null.mrk          |
| 421888 | \_\_ProfileEvents\_\_%27ArenaAllocChunks%27.mrk              |
| 421888 | \_\_ProfileEvents\_\_%27ArenaAllocChunks%27.null.mrk         |
| 385024 | \_\_ProfileEvents\_\_%27CannotWriteToWriteBufferDiscard%27.mrk |
| 385024 | \_\_ProfileEvents\_\_%27CannotWriteToWriteBufferDiscard%27.null.mrk |
| 421888 | \_\_ProfileEvents\_\_%27CatalogTime%27.mrk                   |
| 421888 | \_\_ProfileEvents\_\_%27CatalogTime%27.null.mrk              |
```
The size of multiple file is less than 421888, such as: __ProfileEvents__%27CnchTxnCommitV2Failed%27.mrk, __ProfileEvents__%27CnchTxnCommitV2Failed%27.null.mkr, __ProfileEvents__%27CompileExpressionBytes%27.mrk, __ProfileEvents__%27CompileExpressionBytes%27.null.mrk. 

I remove the function 'canBeInsizeNullable()' from file ColumnArray.h.
I change the function 'canBeInsizeNullable()' return true from file DataTypeArray.h
Is this change causing the problem?

```

### Version
0.2.2

Does any one face the same problem?

**Comment by smmsmm1988** [comment]
hi @zhaojintaozhao. No, we haven't met such problem before. Maybe the problem has some association with your code modification. Would you like to restore the code and change again? BTW, the version of 0.2.2 is somewhat old...

**Comment by zhaojintaozhao** [comment]
> hi @zhaojintaozhao. No, we haven't met such problem before. Maybe the problem has some association with your code modification. Would you like to restore the code and change again? BTW, the version of 0.2.2 is somewhat old...

Yes, this problem occurs at a low probability. No recurrence condition is found. We will continue to watch to see if this issue reoccurs.

**Comment by smmsmm1988** [comment]
> > hi @zhaojintaozhao. No, we haven't met such problem before. Maybe the problem has some association with your code modification. Would you like to restore the code and change again? BTW, the version of 0.2.2 is somewhat old...
> 
> Yes, this problem occurs at a low probability. No recurrence condition is found. We will continue to watch to see if this issue reoccurs.

OK. Thank you for your effort.

**Comment by smmsmm1988** [comment]
@zhaojintaozhao hi, do you have any further problem, or shall we close this issue？
