### ISSUE TITLE
升级到1.0.0-rc2 之后 提示 The leader from election result not work well SQLSTATE: HY000 (version 21.8.7.1)

### ISSUE THREAD

**Issue by XuCe** [ByConity/ByConity#1806]
我使用docker进行部署的0.42版本  将镜像升级成1.0.0-rc2之后 无法继续正常使用
使用查询命令时提示
DB::Exception: The leader from election result not work well SQLSTATE: HY000 (version 21.8.7.1)

然后我查询system.workers提示
 DB::Exception: Unable to get worker data through Resource Manager at this moment due to: DB::Exception: The leader from election result not work well SQLSTATE: HY000 SQLSTATE: HY000 (version 21.8.7.1)

我的config配置是使用的 [byconity-multiworkers-cluster](https://github.com/ByConity/ByConity/tree/master/docker/docker-compose/byconity-multiworkers-cluster)

**Comment by smmsmm1988** [comment]
这个报错现在还在持续吗？如果是的话，可以帮忙发一下resource manager相关的日志

**Comment by smmsmm1988** [comment]
@kevinthfang 帮忙看一下这个问题吧

**Comment by yuanzhubi** [comment]
@smmsmm1988 这个拉下左闯看看，是resource manager的问题，只是报错里提了一嘴leader

**Comment by XuCe** [comment]
是的 还在持续 每次我重启服务器之后 就会出现  The leader from election result not work well  我晚点把日志文件上传后@你们看下

**Comment by XuCe** [comment]
先说一下我的部署方案 我是把fdb 和 hdfs 分别部署在三个虚拟机内 然后专门有一台虚拟机运行docker 跑byconity的相关组件 当我重启虚拟机之后 byconity的docker可以正常运行 fdb hdfs的状态都是正常的 然后我查询数据 就会报 The leader from election result not work well

**Comment by XuCe** [comment]
我自我感觉是fdb的问题  但是我不知道怎么解决

**Comment by yuanzhubi** [comment]
> 先说一下我的部署方案 我是把fdb 和 hdfs 分别部署在三个虚拟机内 然后专门有一台虚拟机运行docker 跑byconity的相关组件 当我重启虚拟机之后 byconity的docker可以正常运行 fdb hdfs的状态都是正常的 然后我查询数据 就会报 The leader from election result not work well @kevinthfang @yuanzhubi

你能看到有一个resource manager的容器么

**Comment by XuCe** [comment]
> > 先说一下我的部署方案 我是把fdb 和 hdfs 分别部署在三个虚拟机内 然后专门有一台虚拟机运行docker 跑byconity的相关组件 当我重启虚拟机之后 byconity的docker可以正常运行 fdb hdfs的状态都是正常的 然后我查询数据 就会报 The leader from election result not work well @kevinthfang @yuanzhubi
> 
> 你能看到有一个resource manager的容器么

所有的组件都是正常的 我第一次部署好之后没重启虚拟机之前 啥都是好的 即使我重启fdb service 或者整个docker-compose down掉再建容器 都是完全ok的 但是我一重启服务器 再没有直接关闭服务的情况下 直接虚拟机关闭电源 就死掉了。

**Comment by yuanzhubi** [comment]
> > > 先说一下我的部署方案 我是把fdb 和 hdfs 分别部署在三个虚拟机内 然后专门有一台虚拟机运行docker 跑byconity的相关组件 当我重启虚拟机之后 byconity的docker可以正常运行 fdb hdfs的状态都是正常的 然后我查询数据 就会报 The leader from election result not work well @kevinthfang @yuanzhubi
> > 
> > 
> > 你能看到有一个resource manager的容器么
> 
> 所有的组件都是正常的 我第一次部署好之后没重启虚拟机之前 啥都是好的 即使我重启fdb service 或者整个docker-compose down掉再建容器 都是完全ok的 但是我一重启服务器 再没有直接关闭服务的情况下 直接虚拟机关闭电源 就死掉了。

所以resource manager所在的虚拟机是还活着的么

**Comment by XuCe** [comment]
> > > > 先说一下我的部署方案 我是把fdb 和 hdfs 分别部署在三个虚拟机内 然后专门有一台虚拟机运行docker 跑byconity的相关组件 当我重启虚拟机之后 byconity的docker可以正常运行 fdb hdfs的状态都是正常的 然后我查询数据 就会报 The leader from election result not work well @kevinthfang @yuanzhubi
> > > 
> > > 
> > > 你能看到有一个resource manager的容器么
> > 
> > 
> > 所有的组件都是正常的 我第一次部署好之后没重启虚拟机之前 啥都是好的 即使我重启fdb service 或者整个docker-compose down掉再建容器 都是完全ok的 但是我一重启服务器 再没有直接关闭服务的情况下 直接虚拟机关闭电源 就死掉了。
> 
> 所以resource manager所在的虚拟机是还活着的么

是的 活着的 我昨晚试了一下 纯docker部署 包括hdfs、fdb 基于多worker那个版本又是好的。我感觉可能和数据量也有关系 下一步我再测试一次 把我生产库的数据导入2亿进去看看。若还是出现那个问题 可能就需要私下沟通帮我看下了

**Comment by smmsmm1988** [comment]
@XuCe 请问这块还有进一步的问题吗
