### ISSUE TITLE
0.4.2 版本byconity kafka引擎 消费策略是什么

### ISSUE THREAD

**Issue by xiongbl526** [ByConity/ByConity#1807]
(you don't have to strictly follow this form)

## Question
请问如果kafka消费异常  虽然catelog中保存了位点信息，但是已保存的位点信息丢失 服务正常后消费策略是什么样的，是从最新的位点消费还是从能消费的最老的位点消费

**Comment by smmsmm1988** [comment]
从最新的开始消费

**Comment by xiongbl526** [comment]
这个可以通过配置调整吗？



---- 回复的原邮件 ----
| 发件人 | Maomeng ***@***.***> |
| 日期 | 2024年08月12日 10:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] 0.4.2 版本byconity kafka引擎 消费策略是什么 (Issue #1807) |

从最新的开始消费

**Comment by smmsmm1988** [comment]
> 这个可以通过配置调整吗？
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | Maomeng ***@***.***> | | 日期 | 2024年08月12日 10:46 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [ByConity/ByConity] 0.4.2 版本byconity kafka引擎 消费策略是什么 (Issue #1807) | 从最新的开始消费 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

可以的，kafka表配置参数为auto_offset_reset，配置值总共有"smallest", "earliest", "beginning", "largest", "latest", "end"这几种，默认是latest，从最新的开始消费。
