### ISSUE TITLE
kafka引擎表 消费监控如何具象化

### ISSUE THREAD

**Issue by xiongbl526** [ByConity/ByConity#1808]
(you don't have to strictly follow this form)

## Question
目前用的0.4.2版本 bcyonity k8s部署  目前大量使用到kafka引擎 但是除了kafka侧的监控 对于自建的kafka消费表 消费情况等监控很少 请问有什么办法可以完善kafka消费表方面的监控

**Comment by smmsmm1988** [comment]
@xiongbl526，kafka消费表其实不需要监控，因为kafka消费表最终体现在消费lag上，所以一般只需要监控kafka侧的lag情况即可。

**Comment by xiongbl526** [comment]
> @xiongbl526，kafka消费表其实不需要监控，因为kafka消费表最终体现在消费lag上，所以一般只需要监控kafka侧的lag情况即可。

现在有时看byconity引擎 出现几秒内消费量直接降到0 然后过几秒瞬间升起来 这样峰谷的消费情况 消费很不稳定 这种通过调节哪些参数可以优化呢

**Comment by smmsmm1988** [comment]
> > @xiongbl526，kafka消费表其实不需要监控，因为kafka消费表最终体现在消费lag上，所以一般只需要监控kafka侧的lag情况即可。
> 
> 现在有时看byconity引擎 出现几秒内消费量直接降到0 然后过几秒瞬间升起来 这样峰谷的消费情况 消费很不稳定 这种通过调节哪些参数可以优化呢

消费量降到0时，kakfa侧对应的lag大概是多少呢？此时对应的集群cpu、io是个什么情况

**Comment by xiongbl526** [comment]
以每秒生产量3.4k 左右的一个topic为例 kafka引擎消费者数配置的各topic分区数相同，block_size为0.1M 消费降为0时 lag大概三万五左右 基本每隔十五秒消费量就会降为0 每隔十五秒每秒消费量涨到7k左右 我把block_size调大 这个峰谷落差更大了



---- 回复的原邮件 ----
| 发件人 | Maomeng ***@***.***> |
| 日期 | 2024年08月13日 10:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] kafka引擎表 消费监控如何具象化 (Issue #1808) |

@xiongbl526，kafka消费表其实不需要监控，因为kafka消费表最终体现在消费lag上，所以一般只需要监控kafka侧的lag情况即可。

现在有时看byconity引擎 出现几秒内消费量直接降到0 然后过几秒瞬间升起来 这样峰谷的消费情况 消费很不稳定 这种通过调节哪些参数可以优化呢

消费量降到0时，kakfa侧对应的lag大概是多少呢？此时对应的集群cpu、io是个什么情况

**Comment by ChanneRen** [comment]
byconity Kafka消费是攒批消费模式，默认消费8秒提交一次，所以Kafka侧看到offset更新是有时间间隔的，通常为消费的8秒 + 写入时间。block_size表示的是攒批的行数；攒批行数越大，消费时间越长，lag监控看到的间隔越大。正常情况只要lag没有持续增长就是正常的。

**Comment by ChanneRen** [comment]
另 Kafka消费不用按分区数配置消费者数量，每个消费者吞吐还是比较高的，经验值在15-25MiB/s范围内，可以根据这个配置消费者数量；如果有lag的情况下 在酌情增加消费者。建议在保证无lag情况下 尽可能减少消费者，这样part数量少，对merge和查询更友好。

**Comment by xiongbl526** [comment]
谢谢，我们再验证下



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月14日 11:03 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] kafka引擎表 消费监控如何具象化 (Issue #1808) |

另 Kafka消费不用按分区数配置消费者数量，每个消费者吞吐还是比较高的，经验值在15-25MiB/s范围内，可以根据这个配置消费者数量；如果有lag的情况下 在酌情增加消费者。建议在保证无lag情况下 尽可能减少消费者，这样part数量少，对merge和查询更友好。
