### ISSUE TITLE
<Error> Application: DB::ErrnoException: Cannot open file /var/byconity/disks/DISK_INFOS.tmp, errno: 28, strerror: No space left on device SQLSTATE: 58030

### ISSUE THREAD

**Issue by xiongbl526** [ByConity/ByConity#1809]
(you don't have to strictly follow this form)

## Question
k8s部署 镜像版本:0.4.2-testonly-3   最近在迁移clickhouse数据到Byconity时 报这个错实际问题是Inode用完了  请问怎么解决 看issue 848里说添加lru_max_object_num 我在values.yaml中worker配置下加了 然后执行upgrade 之后 感觉没啥效果  目前wrtie宿主机的inode已经用了95%了
configOverwrite:
      logger:
        level: debug
      disk_cache_strategies:
        simple:
          lru_max_size: 12949672960
          lru_max_object_num: 12600000

**Comment by smmsmm1988** [comment]
@xiongbl526 inode到了95%了，按照经验应该是先把inode降下去，而不是更改内核的配置。inode打满说明文件系统不能再继续提供服务了

**Comment by xiongbl526** [comment]
> @xiongbl526 inode到了95%了，按照经验应该是先把inode降下去，而不是更改内核的配置。inode打满说明文件系统不能再继续提供服务了

有什么办法控制inode快速增长吗

**Comment by xiongbl526** [comment]
> @xiongbl526 inode到了95%了，按照经验应该是先把inode降下去，而不是更改内核的配置。inode打满说明文件系统不能再继续提供服务了
/var/byconity/data/auxility_store中文件会自动删除 但是/var/byconity/data/part_disk_cache/meta中会存在大量数据

**Comment by smmsmm1988** [comment]
参考：https://github.com/ByConity/ByConity/issues/1822
