### ISSUE TITLE
怎么清理part_disk_cache磁盘数据

### ISSUE THREAD

**Issue by bright-zy** [ByConity/ByConity#1811]
(you don't have to strictly follow this form)

## Question
表删除后，part_disk_cache占用空间一直没有降低，如何手动清理无效表的part_disk_cache缓存数据

**Comment by smmsmm1988** [comment]
@bright-zy 可以直接去vw的节点上删除，或者执行命令：alter disk cache drop xxx settings virtual_warehouse = '{vw_name}', drop_vw_disk_cache = 1，xxx可以填一个当前存在的表名字。

**Comment by bright-zy** [comment]
@smmsmm1988 好的，我试试，再问下，缓存文件的 uuid，比如：part_disk_cache/data/fff/fffff8ec1b29f34f/ffcbfd06cc31f1f9  ，跟table 或者part是怎么关联的，我没找到他们之前的对应关系

**Comment by smmsmm1988** [comment]
> @smmsmm1988 好的，我试试，再问下，缓存文件的 uuid，比如：part_disk_cache/data/fff/fffff8ec1b29f34f/ffcbfd06cc31f1f9 ，跟table 或者part是怎么关联的，我没找到他们之间的对应关系

路径是经过hash编码的，因此路径名和table或者part暂时无关联关系
