### ISSUE TITLE
慢查询问题分析

### ISSUE THREAD

**Issue by bright-zy** [ByConity/ByConity#1818]
(you don't have to strictly follow this form)

## Question
有一个2亿的数据初始几次查询较慢，根据日志怎么确认查询瓶颈在哪？
<img width="1382" alt="image" src="https://github.com/user-attachments/assets/ea2bf049-6ce3-425b-8e58-14005604cf37">

全量log：
[6384a30e-0d71-44e7-a9d3-17042fa08b71.log](https://github.com/user-attachments/files/16674236/6384a30e-0d71-44e7-a9d3-17042fa08b71.log)

**Comment by smmsmm1988** [comment]
SELECT
    podName() AS pod,
    query_duration_ms as query_ms,
    ProfileEvents.Values[indexOf(ProfileEvents.Names, 'SelectedParts')] AS parts_count,
    ProfileEvents.Values[indexOf(ProfileEvents.Names, 'SelectedMarks')] AS marks_count,
    ProfileEvents.Values[indexOf(ProfileEvents.Names, 'ReadBufferFromFileDescriptorReadBytes')] AS disk_bytes,
    ProfileEvents.Values[indexOf(ProfileEvents.Names, 'DiskReadElapsedMicroseconds')] AS disk_time,
    ProfileEvents.Values[indexOf(ProfileEvents.Names, 'ReadBufferFromS3ReadBytes')] AS s3_bytes,
    (ProfileEvents.Values[indexOf(ProfileEvents.Names, 'ReadBufferFromS3ReadMicroseconds')]) / 1000 AS s3_time,
    round(disk_bytes / (disk_bytes + s3_bytes), 2) AS hit_rate,
    ProfileEvents.Values[indexOf(ProfileEvents.Names, 'RemoteFSAsynchronousReadWaitMicroseconds')] / 1000 AS async_wait_time,
    (MaxIOThreadProfileEvents['RemoteFSAsynchronousReadWaitMicroseconds'] + MaxIOThreadProfileEvents['RemoteFSSynchronousReadWaitMicroseconds'] + MaxIOThreadProfileEvents['DiskReadElapsedMicroseconds']) / 1000 AS IO_max_time,
    query_ms - IO_max_time AS cpu_time,
    ProfileEvents.Values[indexOf(ProfileEvents.Names, 'RemoteFSPrefetchTaskWait')] / (ProfileEvents.Values[indexOf(ProfileEvents.Names, 'RemoteFSPrefetchTaskWait')] + ProfileEvents.Values[indexOf(ProfileEvents.Names, 'RemoteFSPrefetchTaskNotWait')]) AS async_wait_percent
FROM cnch('{worker_vw_name}', system.query_log)
WHERE (initial_query_id = '{query_id}')

主要看hit_rate这个数值，看看是不是缓存没有命中，触发了冷读，导致性能比较慢

**Comment by bright-zy** [comment]
@smmsmm1988 查询出来是下面的图，帮忙分析下
<img width="1285" alt="image" src="https://github.com/user-attachments/assets/68928a3d-1a47-47c5-91a2-9613004fb6de">

**Comment by smmsmm1988** [comment]
> @smmsmm1988 查询出来是下面的图，帮忙分析下 <img alt="image" width="1285" src="https://private-user-images.githubusercontent.com/102500454/360347062-68928a3d-1a47-47c5-91a2-9613004fb6de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTg2OTAsIm5iZiI6MTcyNDMxODM5MCwicGF0aCI6Ii8xMDI1MDA0NTQvMzYwMzQ3MDYyLTY4OTI4YTNkLTFhNDctNDdjNS05MWEyLTk2MTMwMDRmYjZkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQwOTE5NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMmRiMjEyMzZkN2M3YjRmMzZlMWY2ZWVjODE1MzI5MmEwYzkzMDI2MDI0ZTEwOWU2ZDc4ZWMxNGI2ZWIwNDdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.plRqycZgmnWo9LSOZmEFX9TeDnVEWDY1OPQ73ak-d-8">

这就执行了几百毫秒呀，不算慢吧

**Comment by bright-zy** [comment]
@smmsmm1988 但是整体返回花了 几分钟，不知道是耗时在哪，可以看看上面log 

> (you don't have to strictly follow this form)
> 
> ## Question
> 有一个2亿的数据初始几次查询较慢，根据日志怎么确认查询瓶颈在哪？ <img alt="image" width="1382" src="https://private-user-images.githubusercontent.com/102500454/359438217-ea2bf049-6ce3-425b-8e58-14005604cf37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTk3MTUsIm5iZiI6MTcyNDMxOTQxNSwicGF0aCI6Ii8xMDI1MDA0NTQvMzU5NDM4MjE3LWVhMmJmMDQ5LTZjZTMtNDI1Yi04ZTU4LTE0MDA1NjA0Y2YzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQwOTM2NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZGM2ZjA4NGQ5MGEzMGRiNWZhNWZlZTljYjZmMWM2YjcxYzVhMWJhMTVjOWE1MTNjYjI5ZGQxYjBjNjc1MWI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PzqqAsVrqOXTzmOJvQGcGGev4OycM6u0khJT8ClGbsw">
> 
> 全量log： [6384a30e-0d71-44e7-a9d3-17042fa08b71.log](https://github.com/user-attachments/files/16674236/6384a30e-0d71-44e7-a9d3-17042fa08b71.log)

**Comment by smmsmm1988** [comment]
> @smmsmm1988 但是整体返回花了 几分钟，不知道是耗时在哪，可以看看上面log
> 
> > (you don't have to strictly follow this form)
> > ## Question
> > 有一个2亿的数据初始几次查询较慢，根据日志怎么确认查询瓶颈在哪？ <img alt="image" width="1382" src="https://private-user-images.githubusercontent.com/102500454/359438217-ea2bf049-6ce3-425b-8e58-14005604cf37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTk3MTUsIm5iZiI6MTcyNDMxOTQxNSwicGF0aCI6Ii8xMDI1MDA0NTQvMzU5NDM4MjE3LWVhMmJmMDQ5LTZjZTMtNDI1Yi04ZTU4LTE0MDA1NjA0Y2YzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQwOTM2NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZGM2ZjA4NGQ5MGEzMGRiNWZhNWZlZTljYjZmMWM2YjcxYzVhMWJhMTVjOWE1MTNjYjI5ZGQxYjBjNjc1MWI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PzqqAsVrqOXTzmOJvQGcGGev4OycM6u0khJT8ClGbsw">
> > 全量log： [6384a30e-0d71-44e7-a9d3-17042fa08b71.log](https://github.com/user-attachments/files/16674236/6384a30e-0d71-44e7-a9d3-17042fa08b71.log)

@superhail 可以帮忙分析下吗，目前看存储cache都命中了，而且花在io上的时间不多

**Comment by superhail** [comment]
explain analyze pipeline xxx，可以先看看可能是哪个算子的问题

**Comment by smmsmm1988** [comment]
@bright-zy 请问这块还有进一步的问题吗

**Comment by bright-zy** [comment]
> @bright-zy 请问这块还有进一步的问题吗

暂时没有，感觉还是和预加载有点关系，前一两次比较慢，后面就很快了，我在观察下

**Comment by smmsmm1988** [comment]
> > @bright-zy 请问这块还有进一步的问题吗
> 
> ```
> ┌─Explain Analyze────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
> │ Segment[0] [OUTPUT]                                                                                                                                                                                                                                        │
> │    Output Exchange: Output                                                                                                                                                                                                                                 │
> │    Parallel Size: 1, Cluster Name: vw_default_A, Exchange Parallel Size: 1                                                                                                                                                                                 │
> │    [localhost:0]                                                                                                                                                                                                                                           │
> │    Resize  x1 ElapsedTime:0.0 us                                                                                                                                                                                                                           │
> │    │     (Input:[WaitTime:172.4 ms Rows:1 (8.0 Bytes)] Output:[WaitTime:172.4 ms Rows:1 (8.0 Bytes)])                                                                                                                                                      │
> │    └─ Resize  x1 ElapsedTime:0.0 us                                                                                                                                                                                                                        │
> │       │     (Input:[WaitTime:172.5 ms Rows:1 (8.0 Bytes)] Output:[WaitTime:172.5 ms Rows:1 (8.0 Bytes)])                                                                                                                                                   │
> │       └─ MergingAggregatedTransform  x1 ElapsedTime:102.0 us                                                                                                                                                                                               │
> │          │     (Input:[WaitTime:172.3 ms Rows:15 (60.1 KB)] Output:[WaitTime:172.3 ms Rows:1 (8.0 Bytes)])                                                                                                                                                 │
> │          └─ Resize  x1 ElapsedTime:0.0 us                                                                                                                                                                                                                  │
> │             │     (Input:[WaitTime:172.3 ms Rows:15 (60.1 KB)] Output:[WaitTime:172.3 ms Rows:15 (60.1 KB)])                                                                                                                                               │
> │             └─ DeserializeBufTransform  x16 ElapsedTime:16.0 us                                                                                                                                                                                            │
> │                │     (Input:[WaitTime:172.4 ms Rows:0 (0.0 Bytes)] Output:[WaitTime:172.4 ms Rows:15 (60.1 KB)])                                                                                                                                           │
> │                └─ Resize  x1 ElapsedTime:0.0 us                                                                                                                                                                                                            │
> │                   │     (Input:[WaitTime:172.5 ms Rows:0 (0.0 Bytes)] Output:[WaitTime:172.5 ms Rows:0 (0.0 Bytes)])                                                                                                                                       │
> │                   └─ ExchangeSource: MultiPathReceiver[1_0_0_0_10.201.69.32:8124]  x1 ElapsedTime:170.9 ms                                                                                                                                                 │
> │                            (Input:[WaitTime:1.2 ms Rows:0 (0.0 Bytes)] Output:[WaitTime:1.2 ms Rows:0 (0.0 Bytes)])                                                                                                                                        │
> │                                                                                                                                                                                                                                                            │
> │ Segment[1] [SOURCE]                                                                                                                                                                                                                                        │
> │    Output Exchange: GATHER                                                                                                                                                                                                                                 │
> │    Parallel Size: 15, Cluster Name: vw_default_A, Exchange Parallel Size: 1                                                                                                                                                                                │
> │    Outputs: [( SegmentID:0 PlanSegmentType:EXCHANGE ParallelSize:1)]                                                                                                                                                                                       │
> │    [10.201.69.21:8124,10.201.72.34:8124,10.201.72.45:8124,10.201.75.45:8124,10.201.39.45:8124,10.201.68.56:8124,10.201.75.34:8124,10.201.43.57:8124,10.201.72.46:8124,10.201.75.33:8124,10.201.72.58:8124,10.201.72.33:8124,10.201.43.58:8124,10.201.67.56:8124,10.201.72.57:8124] │
> │    MultiPartitionExchangeSink[0]  x120 ElapsedTime:28.0 us                                                                                                                                                                                                 │
> │    │     (Input:[WaitTime:168.5 ms Rows:15 (120.0 Bytes)] Output:[WaitTime:168.5 ms Rows:0 (0.0 Bytes)])                                                                                                                                                   │
> │    └─ Resize  x15 ElapsedTime:0.0 us                                                                                                                                                                                                                       │
> │       │     (Input:[WaitTime:168.4 ms Rows:15 (120.0 Bytes)] Output:[WaitTime:168.4 ms Rows:15 (120.0 Bytes)])                                                                                                                                             │
> │       └─ Resize  x15 ElapsedTime:0.0 us                                                                                                                                                                                                                    │
> │          │     (Input:[WaitTime:168.4 ms Rows:15 (120.0 Bytes)] Output:[WaitTime:168.4 ms Rows:15 (120.0 Bytes)])                                                                                                                                          │
> │          ├─ AggregatingTransform  x15 ElapsedTime:273.0 us                                                                                                                                                                                                 │
> │          │  │     (Input:[WaitTime:168.3 ms Rows:6.2M (11.9 MB)] Output:[WaitTime:168.3 ms Rows:15 (120.0 Bytes)])                                                                                                                                         │
> │          │  └─ ConvertingAggregatedToChunksTransform  x15 ElapsedTime:33.0 us                                                                                                                                                                              │
> │          │           (Input:[WaitTime:36.0 us Rows:0 (0.0 Bytes)] Output:[WaitTime:36.0 us Rows:15 (120.0 Bytes)])                                                                                                                                         │
> │          └─ AggregatingTransform  x600 ElapsedTime:2.3 ms                                                                                                                                                                                                  │
> │             │     (Input:[WaitTime:168.3 ms Rows:223.1M (425.6 MB)] Output:[WaitTime:168.3 ms Rows:15 (120.0 Bytes)])                                                                                                                                      │
> │             └─ StrictResize  x15 ElapsedTime:0.0 us                                                                                                                                                                                                        │
> │                │     (Input:[WaitTime:162.9 ms Rows:223.1M (425.6 MB)] Output:[WaitTime:162.9 ms Rows:223.1M (425.6 MB)])                                                                                                                                  │
> │                └─ FilterTransform  x600 ElapsedTime:1.5 ms                                                                                                                                                                                                 │
> │                   │     (Input:[WaitTime:168.0 ms Rows:223.1M (425.6 MB)] Output:[WaitTime:168.0 ms Rows:223.1M (425.6 MB)])                                                                                                                               │
> │                   └─ MergeTreeThread  x600 ElapsedTime:166.3 ms                                                                                                                                                                                            │
> │                            (Input:[WaitTime:1.3 ms Rows:0 (0.0 Bytes)] Output:[WaitTime:1.3 ms Rows:223.1M (425.6 MB)])                                                                                                                                    │
> │                                                                                                                                                                                                                                                            │
> └────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
> ```
> 
> 是简单的算子查询，感觉还是和预加载有点关系，前一两次比较慢，后面就很快了，我在观察下

嗯，一般冷读都比较慢，命中cache的读就比较快了。

**Comment by smmsmm1988** [comment]
那这个issue先close了，后面有问题的话，可以再新提issue
