### ISSUE TITLE
kafka引擎可以解析字段类型不固定的json消息吗

### ISSUE THREAD

**Issue by xiongbl526** [ByConity/ByConity#1819]
(you don't have to strictly follow this form)

## Question
0.4.2版本

 同一个topic kafka json消息中有个字段的value有的是字符串类型 有的是数组类型 没有转字符串 导致解析报错，请问kafka消费表有办法兼容处理吗

**Comment by ChanneRen** [comment]
那你们是想怎么存在 byconity 里呢？总得有个固定的数据类型吧。
建议最好上游统一数据类型，如果是在上游改造不了，你们就用虚拟列 _content 加 JSONExtractRaw 函数在 VIEW 表里将这个字段统一提取为 String 类型。

**Comment by xiongbl526** [comment]
好，谢谢，我试试



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月23日 10:25 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] kafka引擎可以解析字段类型不固定的json消息吗 (Issue #1819) |

那你们是想怎么存在 byconity 里呢？总得有个固定的数据类型吧。
建议最好上游统一数据类型，如果是在上游改造不了，你们就用虚拟列 _content 加 JSONExtractRaw 函数在 VIEW 表里将这个字段统一提取为 String 类型。
