### ISSUE TITLE
Why remove the docs folder ?

### ISSUE THREAD

**Issue by JiangXiNJU** [ByConity/ByConity#182]
(you don't have to strictly follow this form)

## Question
Hi ,  We are following the guide inside Byconity/docs to learn and test Byconity. 
But today we find that the docs folder is deleted,  is there any problem of the docs ?

**Comment by WillemJiang** [comment]
We moved the docs to [the website](https://byconity.github.io) please checkout [the link](https://byconity.github.io/zh-cn/docs/ByConity%E7%AE%80%E4%BB%8B/%E4%B8%BB%E8%A6%81%E5%8E%9F%E7%90%86%E6%A6%82%E5%BF%B5) for chinese documentation.

**Comment by JiangXiNJU** [comment]
thanks!
