### ISSUE TITLE
查询服务本地缓存使用大小超过lru_max_size限制

### ISSUE THREAD

**Issue by xiongbl526** [ByConity/ByConity#1820]
(you don't have to strictly follow this form)

## Question
0.4.2版本 k8s部署 查询服务挂载的云盘总大小200G  lru_max_size限制了150  但是我看两个查询服务Pod都使用了180G 左右 
 configOverwrite:
      disk_cache_strategies:
        simple:
          lru_max_size: 161061273600 # 150G

**Comment by smmsmm1988** [comment]
磁盘不只有缓存使用，也会存储其他东西，比如log、index等。这个可以去pod里du -sh 看一下就知道了
