### ISSUE TITLE
迁移数据到bcyontiy中vw_write pod挂载云盘的Inode快速上涨

### ISSUE THREAD

**Issue by xiongbl526** [ByConity/ByConity#1822]
(you don't have to strictly follow this form)

## Question
0.4.2版本 K8s部署 worker节点挂载运维大小150G 在使用clickhouse copier工具迁移数据到byconity中时 vw_write服务所在pod的inode 快速上涨 /var/byconity/data/auxility_store中文件会自动删除 但是/var/byconity/data/part_disk_cache/meta中会存在大量数据 一旦Inode使用完 就会报错空间不足 请问如何解决这个问题
https://github.com/ByConity/ByConity/issues/848
这个issue中 最后说添加 lru_max_object_num 但是加了 没什么效果
configOverwrite:
      logger:
        level: debug
      disk_cache_strategies:
        simple:
          lru_max_size: 138935838720 
      # timezone: Etc/UTC
          lru_max_object_num: 7000000

**Comment by foreverneverer** [comment]
1. 你需要先看一下系统inode是多大，然后lru_max_object_num确保小于它
2. 出现inode不足后，查询`select *, formatReadableSize(value) from system.asynchronous_metrics where metric like '%DiskCache%'` 看一下当前DiskCache的inode是多大(MergeTreeDiskCacheFiles这个指标)，如果小于等于配置的大小，说明符合预期
3. 实际上，writer节点本身不需要DiskCache，你可以在write节点users.xml配置<enable_local_disk_cache>0</enable_local_disk_cache>以关闭缓存写入

**Comment by xiongbl526** [comment]
lru_max_object_num加了，主要是/var/byconity/data/part_disk_cache/meta里的文件没有及时删除，我手动删除目录修改时间在10分钟之前的子目录后inode会骤降



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月26日 11:56 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [ByConity/ByConity] 迁移数据到bcyontiy中vw_write pod挂载云盘的Inode快速上涨 (Issue #1822) |

你需要先看一下系统inode是多大，然后lru_max_object_num确保小于它
出现inode不足后，查询select *, formatReadableSize(value) from system.asynchronous_metrics where metric like '%DiskCache%' 看一下当前DiskCache的inode是多大(MergeTreeDiskCacheFiles这个指标)，如果小于等于配置的大小，说明符合预期
实际上，writer节点本身不需要DiskCache，你可以在write节点users.xml配置<enable_local_disk_cache>0</enable_local_disk_cache>以关闭缓存写入

**Comment by foreverneverer** [comment]
lru_max_object_num加了之后，理论上**重启之后**就会主动释放超过的容量

**Comment by xiongbl526** [comment]
额，没有重启，后面我再观察下



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月26日 14:11 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [ByConity/ByConity] 迁移数据到bcyontiy中vw_write pod挂载云盘的Inode快速上涨 (Issue #1822) |

lru_max_object_num加了之后，理论上重启之后就会主动释放超过的容量
