### ISSUE TITLE
exception:Code: 11010,  DB::Exception: DB::Exception: Transaction 452049492197507075 not found SQLSTATE: HY000.

### ISSUE THREAD

**Issue by xiongbl526** [ByConity/ByConity#1823]
(you don't have to strictly follow this form)

## Question
0.4.2版本 运行过程中报错可能是什么原因引起的呢

**Comment by nudles** [comment]
@xiongbl526 does this error repeat? what operations lead to it?

**Comment by xiongbl526** [comment]
正常的insert into select 但是现在tso 所在pod日志都不刷了 一直显示listen xxxx:9000, 是不是有问题呢



---- Replied Message ----
| From | Wei ***@***.***> |
| Date | 08/24/2024 15:13 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [ByConity/ByConity] exception:Code: 11010, DB::Exception: DB::Exception: Transaction 452049492197507075 not found SQLSTATE: HY000. (Issue #1823) |

@xiongbl526 does this error repeat? what operations lead to it?

**Comment by nudles** [comment]
@xiongbl526 可以重启tso 或者整个集群吗？

**Comment by xiongbl526** [comment]
我把tso 所在pod 给delete 一下？我部署了两个tso节点



---- 回复的原邮件 ----
| 发件人 | Wei ***@***.***> |
| 日期 | 2024年08月26日 12:27 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] exception:Code: 11010, DB::Exception: DB::Exception: Transaction 452049492197507075 not found SQLSTATE: HY000. (Issue #1823) |

@xiongbl526 可以重启tso 或者整个集群吗？

**Comment by xiongbl526** [comment]
tso日志不刷，我看了下是我把日志打印级别调到debug了，我改为trace，重启tso后 是正常的，应该不是tso服务的问题了



---- 回复的原邮件 ----
| 发件人 | Wei ***@***.***> |
| 日期 | 2024年08月26日 12:27 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] exception:Code: 11010, DB::Exception: DB::Exception: Transaction 452049492197507075 not found SQLSTATE: HY000. (Issue #1823) |

@xiongbl526 可以重启tso 或者整个集群吗？

**Comment by xiongbl526** [comment]
> @xiongbl526 可以重启tso 或者整个集群吗？
最近跑这个任务天天失败 一旦机器负载达到10以上就报错 3台8C 32G 的worker机器都大概率跑不出来 请问这个瓶颈在哪里呢 
Worker host:172.18.32.18:8124, exception:Code: 11010, e.displayText() = DB::Exception: DB::Exception: Transaction 452155522932015119 not found SQLSTATE: HY000.: While executing TableWrite SQLSTATE: HY000 (version 21.8.7.1) (from 172.18.19.0:60290) (in query: insert into a select toString(toDate(insert_time)) as date, substr(toString(insert_time),1,13) as hour, JSONExtract(properties, 'scId', 'String') as scId, JSONExtract(properties, 'evId', 'String') as evId, countryCode, terminalBrand, terminalModel, project, appid, clientOS, clientVersion, null as country, null as province, null as city, null as county, null as isp, JSONExtract(properties, 'res', 'String') as res, JSONExtract(properties, 'failDesc', 'String') as failDesc, JSONExtract(properties, 'type', 'String') as type, JSONExtract(properties, 'rt', 'String') as rt, JSONExtract(properties, 'net', 'String') as net, JSONExtract(properties, 'link', 'String') as link, JSONExtract(properties, 'vd', 'String') as vd, JSONExtract(properties, 'attribute', 'String') as attribute, JSONExtract(properties, 'did', 'String') as did, userId as uid, JSONExtract(properties, 'cost', 'Int64') as cost, JSONExtract(properties, 'apiCost', 'Int64') as apicost, toFloat64OrZero(JSONExtract(properties, 'flow', 'String')) as flow, JSONExtract(properties, 'bgStayTime', 'Float64') as bgStayTime, toInt64(JSONExtract(properties, 'duration', 'String')) as duration, case when JSONExtract(properties, 'timestamp', 'Int64') = 0 then insert_time else toDateTime(JSONExtract(properties, 'timestamp', 'Int64')/1000) end as time, JSONExtract(properties, 'mtsInfo_statCode', 'String') as mtsInfo_statCode, JSONExtract(properties, 'screen_name', 'String') as screen_name, JSONExtract(properties, 'p2pInfo_statCode', 'String') as p2pInfo_statCode, JSONExtract(properties, 'p2pInfo_nattCt', 'String') as p2pInfo_nattCt, JSONExtract(properties, 'p2pNatState', 'String') as p2pNatState, JSONExtract(properties, 'linkCatchUpCost', 'String') as linkCatchUpCost, JSONExtract(properties, 'linkSwitchCost', 'String') as linkSwitchCost, JSONExtract(properties, 'pid', 'String') as pid, JSONExtract(properties, 'cdk_init_to_getp2pport_cost', 'Int64') as cdk_init_to_getp2pport_cost, JSONExtract(properties, 'cdk_last_hole_to_getp2pport_cost', 'Int64') as cdk_last_hole_to_getp2pport_cost, JSONExtract(properties, 'cdk_last_hole_errcode', 'String') as cdk_last_hole_errcode, JSONExtract(properties, 'cdk_first_pullstream', 'String') as cdk_first_pullstream, JSONExtract(properties, 'cdk_init_id', 'String') as cdk_init_id, JSONExtract(properties, 'ip_version', 'String') as ip_version, JSONExtract(properties, 'p2p_auth_type', 'String') as p2p_auth_type, JSONExtract(properties, 'playSdkType', 'Int32') as playSdkType, JSONExtract(properties, 'avgDecodeTime', 'Int64') as avgDecodeTime, JSONExtract(properties, 'avgRenderTime', 'Int64') as avgRenderTime, JSONExtract(properties, 'maxVDecodeTime', 'Int64') as maxVDecodeTime, JSONExtract(properties, 'vDecodeErrorCount', 'Int32') as vDecodeErrorCount, JSONExtract(properties, 'vff_dec_const', 'Int64') as vff_dec_const, JSONExtract(properties, 'vff_ren_const', 'Int64') as vff_ren_const, JSONExtract(properties, 'v_resolution', 'String') as v_resolution, JSONExtract(properties, 'v_dec_type', 'Int64') as v_dec_type, JSONExtract(properties, 'v_recv_frames', 'Int64') as v_recv_frames, JSONExtract(properties, 'v_recv_bitrate', 'Int64') as v_recv_bitrate, JSONExtract(properties, 'v_buffer_size', 'Float64') as v_buffer_size, JSONExtract(properties, 'v_buffer_duration', 'Int64') as v_buffer_duration, JSONExtract(properties, 'av_max_diff', 'Int64') as av_max_diff, JSONExtract(properties, 'av_min_diff', 'Int64') as av_min_diff, JSONExtract(properties, 'av_avg_diff', 'Int64') as av_avg_diff, JSONExtract(properties, 'enter_from', 'String') as enter_from, JSONExtract(properties, 'cid', 'String') AS cid, JSONExtract(properties, 'streamProto', 'String') as stream_proto, JSONExtract(properties, 'encryptInfo', 'String') as encrypt_info, JSONExtract(properties, 'svrLinkType', 'String') as svr_link_type, JSONExtract(properties, 'getMtsUrlCost', 'Int64') as get_mts_url_cost, JSONExtract(properties, 'reqStreamCost', 'Int64') as req_stream_cost, JSONExtract(properties, 'traversalCost', 'Int64') as traversal_cost, JSONExtract(properties, 'retryCost', 'Int64') as retry_cost, JSONExtract(properties, 'streamDecodingCost', 'Int64') as stream_decoding_cost, JSONExtract(properties, 'uiInitCost', 'Int64') as ui_init_cost, JSONExtract(properties, 'stream_transfer_cost', 'Int64') as stream_transfer_cost2, JSONExtract(properties, 'stream_proto_cost', 'Int64') AS stream_proto_cost, JSONExtract(properties, 'share_media_link', 'Int64') AS share_media_link, JSONExtract(properties, 'shareLink', 'Int64') AS share_link from b where topic = 'c' and dt = '2024-08-27' and toHour(insert_time) >= 18 and toHour(insert_time) < 20), Stack trace (when copying this message, always include the lines below):
2024.08.28 17:15:04.519831 [ 29 ] {} <Warning> StreamHandler: on_closed receiver is expired.
2024.08.28 17:15:04.520158 [ 54983 ] {9450eefa-0118-4747-ac99-754e90f71d70} (452155522932015119) <Error> DynamicQueryHandler: Code: 11010, e.displayText() = DB::Exception: Worker host:172.18.32.18:8124, exception:Code: 11010, e.displayText() = DB::Exception: DB::Exception: Transaction 452155522932015119 not found SQLSTATE: HY000.: While executing TableWrite SQLSTATE: HY000 (version 21.8.7.1) SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):
2024.08.28 17:15:04.560364 [ 231 ] {} <Error> SessionResource(452155522932015119): Error occurs when remove WorkerResource{452155522932015119} in worker 172.18.37.12:8124: Code: 2008, e.displayText() = DB::Exception: 112:[E112]Not connected to 172.18.37.12:8124 yet, server_id=2260 [R1][E112]Not connected to 172.18.37.12:8124 yet, server_id=2260 [R2][E112]Not connected to 172.18.37.12:8124 yet, server_id=2260 [R3][E112]Not connected to 172.18.37.12:8124 yet, server_id=2260 SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):
2024.08.28 17:15:04.817232 [ 1000 ] {} <Error> CnchServerService: auto DB::CnchServerServiceImpl::commitParts(google::protobuf::RpcController *, const Protos::CommitPartsReq *, Protos::CommitPartsResp *, google::protobuf::Closure *)::(anonymous class)::operator()() const: Code: 11010, e.displayText() = DB::Exception: Transaction 452155522932015119 not found SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):
