### ISSUE TITLE
在ByConity S3场景下即使集群没有数据写入依然有大量的ListObjects请求导致MinIO集群持续高负载

### ISSUE THREAD

**Issue by 764276020** [ByConity/ByConity#1840]
(you don't have to strictly follow this form)

## Question
在ByConity S3场景下即使集群没有数据写入依然有大量的ListObjects请求导致MinIO集群持续高负载
ByConity 版本：1.0.0 （刚开始部署的是0.4.2版本因为ListObjects 的问题，升级至1.0.0后问题仍然存在）
![image](https://github.com/user-attachments/assets/acfc80f9-00a7-4dfe-a9be-eefe9646bcd6)
![Uploading image.png…]()

**Comment by ixnzh** [comment]
是部署后一直都没有数据写入吗，还是当时没有写入任务。是后台的merge任务吗

**Comment by 764276020** [comment]
在0.4.2 版本中有数据写入，因为ListObjects 太多了，就停掉了，目前已经升级到1.0.0版本，启动之后 MinIO 的CPU就几乎是100%的跑

**Comment by Alima777** [comment]
你们的 Part 数量多吗？可以试试如果把 daemonManager 停了，是否还有那么高的调用

**Comment by smmsmm1988** [comment]
select toStartOfHour(event_time) as t, countIf(event_type = 1) as i, sumIf(num_source_parts , event_type = 2) as m from cnch(server, system.server_part_log) where event_date >= today() group by t order by t;

也可以用这个sql查一下

**Comment by 764276020** [comment]
> 你们的 Part 数量多吗？可以试试如果把 daemonManager 停了，是否还有那么高的调用

大佬，Part 数量在哪里看呢，我看worker write 节点的data下，一共有3w个文件

**Comment by 764276020** [comment]
> select toStartOfHour(event_time) as t, countIf(event_type = 1) as i, sumIf(num_source_parts , event_type = 2) as m from cnch(server, system.server_part_log) where event_date >= today() group by t order by t;
> 
> 也可以用这个sql查一下

+---------------------+------+------+
| t                   | i    | m    |
+---------------------+------+------+
| 2024-09-03 00:00:00 |    0 |    0 |
| 2024-09-03 01:00:00 |    0 |    0 |
| 2024-09-03 02:00:00 |    0 |    0 |
| 2024-09-03 03:00:00 |    0 |    0 |
| 2024-09-03 04:00:00 |    0 |    0 |
| 2024-09-03 05:00:00 |    0 |    0 |
| 2024-09-03 06:00:00 |    0 |    0 |
| 2024-09-03 07:00:00 |    0 |    0 |
| 2024-09-03 08:00:00 |    0 |    0 |
| 2024-09-03 09:00:00 |    0 |    0 |
| 2024-09-03 10:00:00 |    0 |    0 |
+---------------------+------+------+
11 rows in set (0.05 sec)

**Comment by smmsmm1988** [comment]
> > 你们的 Part 数量多吗？可以试试如果把 daemonManager 停了，是否还有那么高的调用
> 
> 大佬，Part 数量在哪里看呢，我看worker write 节点的data下，一共有3w个文件

system.cnch_parts

**Comment by smmsmm1988** [comment]
> > select toStartOfHour(event_time) as t, countIf(event_type = 1) as i, sumIf(num_source_parts , event_type = 2) as m from cnch(server, system.server_part_log) where event_date >= today() group by t order by t;
> > 也可以用这个sql查一下
> 
> +---------------------+------+------+ | t | i | m | +---------------------+------+------+ | 2024-09-03 00:00:00 | 0 | 0 | | 2024-09-03 01:00:00 | 0 | 0 | | 2024-09-03 02:00:00 | 0 | 0 | | 2024-09-03 03:00:00 | 0 | 0 | | 2024-09-03 04:00:00 | 0 | 0 | | 2024-09-03 05:00:00 | 0 | 0 | | 2024-09-03 06:00:00 | 0 | 0 | | 2024-09-03 07:00:00 | 0 | 0 | | 2024-09-03 08:00:00 | 0 | 0 | | 2024-09-03 09:00:00 | 0 | 0 | | 2024-09-03 10:00:00 | 0 | 0 | +---------------------+------+------+ 11 rows in set (0.05 sec)

这个你需要把event_date改成负载高的那段时间的。后来负载高应该是下来了吧？

**Comment by 764276020** [comment]
> > > select toStartOfHour(event_time) as t, countIf(event_type = 1) as i, sumIf(num_source_parts , event_type = 2) as m from cnch(server, system.server_part_log) where event_date >= today() group by t order by t;
> > > 也可以用这个sql查一下
> > 
> > 
> > +---------------------+------+------+ | t | i | m | +---------------------+------+------+ | 2024-09-03 00:00:00 | 0 | 0 | | 2024-09-03 01:00:00 | 0 | 0 | | 2024-09-03 02:00:00 | 0 | 0 | | 2024-09-03 03:00:00 | 0 | 0 | | 2024-09-03 04:00:00 | 0 | 0 | | 2024-09-03 05:00:00 | 0 | 0 | | 2024-09-03 06:00:00 | 0 | 0 | | 2024-09-03 07:00:00 | 0 | 0 | | 2024-09-03 08:00:00 | 0 | 0 | | 2024-09-03 09:00:00 | 0 | 0 | | 2024-09-03 10:00:00 | 0 | 0 | +---------------------+------+------+ 11 rows in set (0.05 sec)
> 
> 这个你需要把event_date改成负载高的那段时间的。后来负载高应该是下来了吧？

没有呢，依然很高
![image](https://github.com/user-attachments/assets/6351e4fc-62b6-4c15-bd58-1708871925d8)
![image](https://github.com/user-attachments/assets/8e892239-feb0-4d89-8a70-5f6ffbb3d4f8)
![image](https://github.com/user-attachments/assets/df21b689-9eb2-4bd4-b901-d2cc54ed6002)
![image](https://github.com/user-attachments/assets/9f05115a-6531-49eb-a738-729d49e9d845)

**Comment by 764276020** [comment]
> system.cnch_parts

MySQL [(none)]> select count(*) from system.cnch_parts;
+---------+
| count() |
+---------+
|   34731 |
+---------+
1 row in set (0.59 sec)

**Comment by smmsmm1988** [comment]
> > system.cnch_parts
> 
> MySQL [(none)]> select count(*) from system.cnch_parts; +---------+ | count() | +---------+ | 34731 | +---------+ 1 row in set (0.59 sec)

帮忙进一步执行以下两个sql看下：
1、select count(*), part_type from system.cnch_parts group by part_type;
2、select count() from system.cnch_trash_items

**Comment by 764276020** [comment]
> select count() from system.cnch_trash_items

MySQL [(none)]> select count(*), part_type from system.cnch_parts group by part_type;
+---------+-------------+
| count() | part_type   |
+---------+-------------+
|   34503 | VisiblePart |
|      28 | Tombstone   |
|      28 | DroppedPart |
+---------+-------------+
3 rows in set (0.58 sec)

MySQL [(none)]> select count() from system.cnch_trash_items;
+---------+
| count() |
+---------+
|     368 |
+---------+
1 row in set (0.05 sec)

**Comment by smmsmm1988** [comment]
> > select count() from system.cnch_trash_items
> 
> MySQL [(none)]> select count(*), part_type from system.cnch_parts group by part_type; +---------+-------------+ | count() | part_type | +---------+-------------+ | 34503 | VisiblePart | | 28 | Tombstone | | 28 | DroppedPart | +---------+-------------+ 3 rows in set (0.58 sec)
> 
> MySQL [(none)]> select count() from system.cnch_trash_items; +---------+ | count() | +---------+ | 368 | +---------+ 1 row in set (0.05 sec)

从目前的信息看不出来什么了，可以方便把server、worker、daemon manager的log发过来我们分析一下吗

**Comment by 764276020** [comment]
> > > select count() from system.cnch_trash_items
> > 
> > 
> > MySQL [(none)]> select count(*), part_type from system.cnch_parts group by part_type; +---------+-------------+ | count() | part_type | +---------+-------------+ | 34503 | VisiblePart | | 28 | Tombstone | | 28 | DroppedPart | +---------+-------------+ 3 rows in set (0.58 sec)
> > MySQL [(none)]> select count() from system.cnch_trash_items; +---------+ | count() | +---------+ | 368 | +---------+ 1 row in set (0.05 sec)
> 
> 从目前的信息看不出来什么了，可以方便把server、worker、daemon manager的log发过来我们分析一下吗

好的大佬。稍等一下

**Comment by 764276020** [comment]
以下日志是否会有影响呢
2024.09.03 13:25:39.180061 [ 1418408 ] {} <Error> CnchMergePrefetcher: Fail to copy byconity/709643bc-c905-34d1-f67a-14935d76aac6/data to byconity/auxility_store/452287827548569603/2b16b490a87466b6a6d34fd9027f3c3d_452030564831592452_452030564831592452_0_452030564831592449_data_0_0_284373: Code: 107, e.displayText() = DB::ErrnoException: Cannot open file byconity/auxility_store/452287827548569603/2b16b490a87466b6a6d34fd9027f3c3d_452030564831592452_452030564831592452_0_452030564831592449_data_0_0_284373, errno: 2, strerror: No such file or directory, path = byconity/auxility_store/452287827548569603/2b16b490a87466b6a6d34fd9027f3c3d_452030564831592452_452030564831592452_0_452030564831592449_data_0_0_284373 SQLSTATE: 58030, Stack trace (when copying this message, always include the lines below):
                                                                                                        0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x273ac612 in /opt/byconity-dwcloud-server-9010/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x10af09a0 in /opt/byconity-dwcloud-server-9010/bin/clickhouse
2. DB::throwFromErrnoWithPath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int) @ 0x10af1812 in /opt/byconity-dwcloud-server-9010/bin/clickhouse
3. DB::WriteBufferFromFile::WriteBufferFromFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, int, unsigned int, char*, unsigned long) @ 0x10b7e47d in /opt/byconity-dwcloud-server-9010/bin/clickhouse
4. std::__1::__async_func<DB::CnchMergePrefetcher::PartFutureFiles::schedulePrefetchTask(DB::CnchMergePrefetcher::FutureSegment&)::$_0>::operator()() @ 0x2050693c in /opt/byconity-dwcloud-server-9010/bin/clickhouse
5. std::__1::__async_assoc_state<void, std::__1::__async_func<DB::CnchMergePrefetcher::PartFutureFiles::schedulePrefetchTask(DB::CnchMergePrefetcher::FutureSegment&)::$_0> >::__execute() @ 0x205063b7 in /opt/byconity-dwcloud-server-9010/bin/clickhouse
6. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (std::__1::__async_assoc_state<void, std::__1::__async_func<DB::CnchMergePrefetcher::PartFutureFiles::schedulePrefetchTask(DB::CnchMergePrefetcher::FutureSegment&)::$_0> >::*)(), std::__1::__async_assoc_state<void, std::__1::__async_func<DB::CnchMergePrefetcher::PartFutureFiles::schedulePrefetchTask(DB::CnchMergePrefetcher::FutureSegment&)::$_0> >*> >(void*) @ 0x20507762 in /opt/byconity-dwcloud-server-9010/bin/clickhouse
7. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
8. clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 21.8.7.1)

**Comment by smmsmm1988** [comment]
> 以下日志是否会有影响呢 2024.09.03 13:25:39.180061 [ 1418408 ] {} CnchMergePrefetcher: Fail to copy byconity/709643bc-c905-34d1-f67a-14935d76aac6/data to byconity/auxility_store/452287827548569603/2b16b490a87466b6a6d34fd9027f3c3d_452030564831592452_452030564831592452_0_452030564831592449_data_0_0_284373: Code: 107, e.displayText() = DB::ErrnoException: Cannot open file byconity/auxility_store/452287827548569603/2b16b490a87466b6a6d34fd9027f3c3d_452030564831592452_452030564831592452_0_452030564831592449_data_0_0_284373, errno: 2, strerror: No such file or directory, path = byconity/auxility_store/452287827548569603/2b16b490a87466b6a6d34fd9027f3c3d_452030564831592452_452030564831592452_0_452030564831592449_data_0_0_284373 SQLSTATE: 58030, Stack trace (when copying this message, always include the lines below): 0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, int) @ 0x273ac612 in /opt/byconity-dwcloud-server-9010/bin/clickhouse
> 
> 1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, int, bool) @ 0x10af09a0 in /opt/byconity-dwcloud-server-9010/bin/clickhouse
> 2. DB::throwFromErrnoWithPath(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, int, int) @ 0x10af1812 in /opt/byconity-dwcloud-server-9010/bin/clickhouse
> 3. DB::WriteBufferFromFile::WriteBufferFromFile(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, unsigned long, int, unsigned int, char*, unsigned long) @ 0x10b7e47d in /opt/byconity-dwcloud-server-9010/bin/clickhouse
> 4. std::__1::__async_funcDB::CnchMergePrefetcher::PartFutureFiles::schedulePrefetchTask(DB::CnchMergePrefetcher::FutureSegment&)::$_0::operator()() @ 0x2050693c in /opt/byconity-dwcloud-server-9010/bin/clickhouse
> 5. std::__1::__async_assoc_state<void, std::__1::__async_funcDB::CnchMergePrefetcher::PartFutureFiles::schedulePrefetchTask(DB::CnchMergePrefetcher::FutureSegment&)::$_0 >::__execute() @ 0x205063b7 in /opt/byconity-dwcloud-server-9010/bin/clickhouse
> 6. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_deletestd::__1::__thread_struct >, void (std::__1::__async_assoc_state<void, std::__1::__async_funcDB::CnchMergePrefetcher::PartFutureFiles::schedulePrefetchTask(DB::CnchMergePrefetcher::FutureSegment&)::$_0 >::_)(), std::__1::__async_assoc_state<void, std::__1::__async_funcDB::CnchMergePrefetcher::PartFutureFiles::schedulePrefetchTask(DB::CnchMergePrefetcher::FutureSegment&)::$_0 >_> >(void*) @ 0x20507762 in /opt/byconity-dwcloud-server-9010/bin/clickhouse
> 7. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
> 8. clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
>    (version 21.8.7.1)

这个异常反复在报吗

**Comment by 764276020** [comment]
> > 以下日志是否会有影响呢 2024.09.03 13:25:39.180061 [ 1418408 ] {} CnchMergePrefetcher: Fail to copy byconity/709643bc-c905-34d1-f67a-14935d76aac6/data to byconity/auxility_store/452287827548569603/2b16b490a87466b6a6d34fd9027f3c3d_452030564831592452_452030564831592452_0_452030564831592449_data_0_0_284373: Code: 107, e.displayText() = DB::ErrnoException: Cannot open file byconity/auxility_store/452287827548569603/2b16b490a87466b6a6d34fd9027f3c3d_452030564831592452_452030564831592452_0_452030564831592449_data_0_0_284373, errno: 2, strerror: No such file or directory, path = byconity/auxility_store/452287827548569603/2b16b490a87466b6a6d34fd9027f3c3d_452030564831592452_452030564831592452_0_452030564831592449_data_0_0_284373 SQLSTATE: 58030, Stack trace (when copying this message, always include the lines below): 0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, int) @ 0x273ac612 in /opt/byconity-dwcloud-server-9010/bin/clickhouse
> > 
> > 1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, int, bool) @ 0x10af09a0 in /opt/byconity-dwcloud-server-9010/bin/clickhouse
> > 2. DB::throwFromErrnoWithPath(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, int, int) @ 0x10af1812 in /opt/byconity-dwcloud-server-9010/bin/clickhouse
> > 3. DB::WriteBufferFromFile::WriteBufferFromFile(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, unsigned long, int, unsigned int, char*, unsigned long) @ 0x10b7e47d in /opt/byconity-dwcloud-server-9010/bin/clickhouse
> > 4. std::__1::__async_funcDB::CnchMergePrefetcher::PartFutureFiles::schedulePrefetchTask(DB::CnchMergePrefetcher::FutureSegment&)::$_0::operator()() @ 0x2050693c in /opt/byconity-dwcloud-server-9010/bin/clickhouse
> > 5. std::__1::__async_assoc_state<void, std::__1::__async_funcDB::CnchMergePrefetcher::PartFutureFiles::schedulePrefetchTask(DB::CnchMergePrefetcher::FutureSegment&)::$_0 >::__execute() @ 0x205063b7 in /opt/byconity-dwcloud-server-9010/bin/clickhouse
> > 6. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_deletestd::__1::__thread_struct >, void (std::__1::__async_assoc_state<void, std::__1::__async_funcDB::CnchMergePrefetcher::PartFutureFiles::schedulePrefetchTask(DB::CnchMergePrefetcher::FutureSegment&)::$_0 >::_)(), std::__1::__async_assoc_state<void, std::__1::__async_funcDB::CnchMergePrefetcher::PartFutureFiles::schedulePrefetchTask(DB::CnchMergePrefetcher::FutureSegment&)::$_0 >_> >(void*) @ 0x20507762 in /opt/byconity-dwcloud-server-9010/bin/clickhouse
> > 7. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
> > 8. clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
> >    (version 21.8.7.1)
> 
> 这个异常反复在报吗

是的，一直在报，另外server  worker 也一直在报S3相关的请求日志。我已经超过5天没有往byconity 中写入数据了，不应该还有这么多s3请求才对
2024.09.03 15:29:07.195392 [ 1055178 ] {} <Debug> AWSClient: Make request to: http://10.110.104.204:9001/s3dwcloud-byconity-volume1?continuation-token=Ynljb25pdHkvc3Rxxx%3D&list-type=2&max-keys=1000&prefix=byconity%2Fstore%2F296%2F2963d02a-6b39-4f82-bc70-ffb93a906530%2F
2024.09.03 15:29:07.293111 [ 843896 ] {} <Debug> AWSClient: Response status: 200, OK
2024.09.03 15:29:07.293220 [ 843896 ] {} <Debug> AWSClient: Received headers: Server: nginx; Date: Tue, 03 Sep 2024 07:29:07 GMT; Content-Type: application/xml; Content-Length: 313640; Connection: keep-alive; Accept-Ranges: bytes; Strict-Transport-Security: max-age=31536000; includeSubDomains; Vary: Origin; Vary: Accept-Encoding; X-Amz-Bucket-Region: cn-guian-1; X-Amz-Id-2: 2b2d9eeb8a7f468e899c91302716061873xxx; X-Amz-Request-Id: 17F1AB5CBEC2DA14; X-Content-Type-Options: nosniff; X-Xss-Protection: 1; mode=block;

**Comment by smmsmm1988** [comment]
![image](https://github.com/user-attachments/assets/73336a72-5561-4c3b-8bd7-a9a4e67496cc)

@764276020 能看到这个1055178线程在这条日志之前的更多日志吗，看看它在干什么

**Comment by 764276020** [comment]
@smmsmm1988 1055178 线程第一条日志是
2024.09.03 11:45:56.726263 [ 1055178 ] {} <Debug> AWSClient: Make request to: http://10.110.104.204:9001/s3dwcloud-byconity-volume1?list-type=2&max-keys=1000&prefix=byconity%2Fstore%2F296%2F2963d02a-6b39-4f82-bc70-ffb93a906530%2F
2024.09.03 11:45:57.431302 [ 1055178 ] {} <Debug> AWSClient: Response status: 200, OK
2024.09.03 11:45:57.431422 [ 1055178 ] {} <Debug> AWSClient: Received headers: Server: nginx; Date: Tue, 03 Sep 2024 03:45:57 GMT; Content-Type: application/xml; Content-Length: 313640; Connection: keep-alive; Accept-Ranges: bytes; Strict-Transport-Security: max-age=31536000; includeSubDomains; Vary: Origin; Vary: Accept-Encoding; X-Amz-Bucket-Region: cn-guian-1; X-Amz-Id-2: 217f7e951f06f62b525d28b9b2c7d4209128bce0f167ae37b697f241b636049c; X-Amz-Request-Id: 17F19F2F0CEFC510; X-Content-Type-Options: nosniff; X-Xss-Protection: 1; mode=block;
2024.09.03 11:45:57.431491 [ 1055178 ] {} <Debug> AWSClient: AWS S3 slow read(100ms): http://10.110.104.204:9001/s3dwcloud-byconity-volume1?list-type=2&max-keys=1000&prefix=byconity%2Fstore%2F296%2F2963d02a-6b39-4f82-bc70-ffb93a906530%2F, time = 705ms, header = Server: nginx; Date: Tue, 03 Sep 2024 03:45:57 GMT; Content-Type: application/xml; Content-Length: 313640; Connection: keep-alive; Accept-Ranges: bytes; Strict-Transport-Security: max-age=31536000; includeSubDomains; Vary: Origin; Vary: Accept-Encoding; X-Amz-Bucket-Region: cn-guian-1; X-Amz-Id-2: 217f7e951f06f62b525d28b9b2c7d4209128bce0f167ae37b697f241b636049c; X-Amz-Request-Id: 17F19F2F0CEFC510; X-Content-Type-Options: nosniff; X-Xss-Protection: 1; mode=block;

**Comment by zeromem** [comment]
errno: 2, strerror: No such file or directory, path = byconity/auxility_store/452287827548569603/2b16b490a87466b6a6d34fd9027f3c3d_452030564831592452_452030564831592452_0_452030564831592449_data_0_0_284373

@764276020 可以检查下报这个 error 的 write worker 的本地磁盘使用情况，看看最新的报错 对应的这个目录是不是存在的。

这个报错的含义是，在执行 Merge 任务的时候，会有一个 prefetcher 任务把part 数据从 S3 prefetch 到本地磁盘。报错是发现本地的这个目录不存在，prefetch 失败，整个 merge 任务也就失败了。 merge 如果稳定失败的话，会一直重试

**Comment by zeromem** [comment]
另外可以看看包这种 no such file or directory ，是来自同一个表，还是不同的表。如果来自不同的表，很可能是和环境/配置有关系。 如果是来自同一个表，可能和表 schema 有关

**Comment by 764276020** [comment]
byconity/709643bc-c905-34d1-f67a-14935d76aac6/data to byconity/auxility_store/452287827548569603/2b16b490a87466b6a6d34fd9027f3c3d_452030564831592452_452030564831592452_0_452030564831592449_data_0_0_284373
我不确定这个目录应该出现在哪里

[coremail@gzga-byconity-dwcloud-211-76 worker-write]$ df -hT .
Filesystem     Type  Size  Used Avail Use% Mounted on
/dev/sdc1      xfs   745G  365M  744G   1% /data2
[coremail@gzga-byconity-dwcloud-211-76 worker-write]$ ls
data  tmp
[coremail@gzga-byconity-dwcloud-211-76 worker-write]$ ls data/
auxility_store    disk_cache  metadata_dropped    preprocessed_configs    uuid
bsp               disks       metastore           status
data              flags       part_disk_cache     store
dictionaries_lib  metadata    prepared_statement  unique_key_index_cache

**Comment by zeromem** [comment]
> byconity/709643bc-c905-34d1-f67a-14935d76aac6/data to byconity/auxility_store/452287827548569603/2b16b490a87466b6a6d34fd9027f3c3d_452030564831592452_452030564831592452_0_452030564831592449_data_0_0_284373 我不确定这个目录应该出现在哪里
> 
> [coremail@gzga-byconity-dwcloud-211-76 worker-write]$ df -hT . Filesystem Type Size Used Avail Use% Mounted on /dev/sdc1 xfs 745G 365M 744G 1% /data2 [coremail@gzga-byconity-dwcloud-211-76 worker-write]$ ls data tmp [coremail@gzga-byconity-dwcloud-211-76 worker-write]$ ls data/ auxility_store disk_cache metadata_dropped preprocessed_configs uuid bsp disks metastore status data flags part_disk_cache store dictionaries_lib metadata prepared_statement unique_key_index_cache

可以检查下 data/下面的 auxility_store/

**Comment by 764276020** [comment]
auxility_store/ 目录下是空的。我部署完成之后，并没有做过目录迁移或者删除的操作

**Comment by zeromem** [comment]
> auxility_store/ 目录下是空的。我部署完成之后，并没有做过目录迁移或者删除的操作

那看起来更像是某个配置配错了？ 是不是所有表的 merge 都在报这个错

**Comment by smmsmm1988** [comment]
@764276020 请问这块还有问题吗？

**Comment by 764276020** [comment]
> @764276020 请问这块还有问题吗？

你好，我还没来得及测试，我计划将集群所有文件清理掉，然后采用新版本byconity重新部署
