### ISSUE TITLE
jdbc insert  error  

### ISSUE THREAD

**Issue by YoKv** [ByConity/ByConity#1843]
简单的jdbc写入报错：
Can't set parameter at index 1 due to no JDBC style '?' placeholder found in the query

## 代码示例

![Dingtalk_20240902155642](https://github.com/user-attachments/assets/fd2770a9-715b-417a-a765-4c15270ada85)

## 原因
下面方法获取列返回空

![Dingtalk_20240902154700](https://github.com/user-attachments/assets/00876ffd-46d2-4994-b005-4bc2b58afc5e)

### Version
0.4.1

**Comment by nudles** [comment]
@YoKv  it's similar to #1698 which is fixed in 1.0.0. Can you try the byconity 1.0.0

**Comment by YoKv** [comment]
升级到byconity 1.0.0 还是一样的报错
不过jdbc加上参数 `?compress=0&enable_http_compression=0` 是可以的
另外有什么方式获取当前版本呢 `SELECT version() ` 返回的是ch的版本

升级后 `SHOW COLUMNS FROM  table_name` 也查询不到值了

**Comment by nudles** [comment]
@YoKv 我这边可以看见呢。
<img width="455" alt="image" src="https://github.com/user-attachments/assets/02ce62cd-3d00-4d9a-a102-3a91044cf887">

版本可以从这里看看 `select * from system.build_options where name = 'VERSION_GITHASH'` 对比下 release note里面的commit.

**Comment by YoKv** [comment]
@nudles  版本commit 是3c5252ad53cea340a5c25f7992ca29693500fef8 ，确实是1.0.0

```
CREATE DATABASE test ENGINE=Atomic;

CREATE TABLE t1
(
    `key_` String,
    `order_` Int64
)
ENGINE = MergeTree
PRIMARY KEY tuple(key_)
ORDER BY tuple(key_)
SETTINGS index_granularity = 8192;

```

看起来是MergeTree表引擎的原因，如果后续没有支持计划就关闭issue吧

**Comment by smmsmm1988** [comment]
> @nudles 版本commit 是3c5252ad53cea340a5c25f7992ca29693500fef8 ，确实是1.0.0
> 
> ```
> CREATE DATABASE test ENGINE=Atomic;
> 
> CREATE TABLE t1
> (
>     `key_` String,
>     `order_` Int64
> )
> ENGINE = MergeTree
> PRIMARY KEY tuple(key_)
> ORDER BY tuple(key_)
> SETTINGS index_granularity = 8192;
> ```
> 
> 看起来是MergeTree表引擎的原因，如果后续没有支持计划就关闭issue吧

byconity主要是围绕CnchMergeTree引擎打造的，其他表引擎没有适配或者关注
