### ISSUE TITLE
How to configure Kafka consumer when it is consuming slow messages

### ISSUE THREAD

**Issue by skyoct** [ByConity/ByConity#1846]
## Question
32 * 256G * 3 nodes
8 * 64 * 12 nodes
Configuration 1 and Configuration 2 have the same total resources. Configuration 1 may get overloaded when there are more consumers, but overall resource usage is not high.

Is there a configuration that can be adjusted so that Configuration 1 can consume faster when there are more consumers?

**Comment by ChanneRen** [comment]
You can try to find the performance bottleneck of the consumers by cnch_system.cnch_kafka_log. Then we can decide how to improve it.

For most cases, just add consumers and expand max_block_size always works. You can try following steps:
1. modify `kafka_max_block_size` to 655360 or 983040 to make it possible to poll a large enough block and reduce io;
2. add `kafka_num_consumers` according to your number of partitions in the topic;
3. if your `kafka_num_consumers` is larger than the number of you nodes, you'd better set `kafka_cnch_schedule_mode` to 'least_consumers` for load balance.

**Comment by smmsmm1988** [comment]
@skyoct any further question?

**Comment by ChanneRen** [comment]
IO performance has an impact on data ingestion as the part will be written on local disk. You may need to check if you keep the same IO resource. In theory, with enough resources, the kafka consumption performance should be the same if you set the same consume parameters.

**Comment by smmsmm1988** [comment]
hi @skyoct, is there any further question for this issue?
