### ISSUE TITLE
是否可以通过clickhouse-client执行delete cnchmergetree表

### ISSUE THREAD

**Issue by xiongbl526** [ByConity/ByConity#1848]
(you don't have to strictly follow this form)

## Question
bycontiy版本0.4.2
通过clickhouse-client执行delete语句时报错DB::Exception: DELETE query is not supported for table a SQLSTATE: 22000

**Comment by xiongbl526** [comment]
clickhouse 里可以通过 Set  allow_experimental_lightweight_delete=1解决

**Comment by xiongbl526** [comment]
命令行可以直接执行 或者连8123端口 也可以执行

**Comment by smmsmm1988** [comment]
delete from 语法只支持unique表，如果非unique表想要delete，需要用alter table db.table delete xxxxx
