### ISSUE TITLE
worker机器使用内存持续上涨

### ISSUE THREAD

**Issue by xiongbl526** [ByConity/ByConity#1851]
(you don't have to strictly follow this form)

## Question
0.4.2版本byconity k8s部署 worker节点(vw_default和vw_write数各有2到3个，每个pod最大内存32G)宿主机使用内存持续上涨，没有阶段性回收的趋势，有使用kafka引擎
mark_cache_size、cnch_checksums_cache_size、uncompressed_cache_size、cache_size_to_ram_max_ratio 这些我都用的默认的没调整过

**Comment by smmsmm1988** [comment]
这会有在做大量写入和merge吗

**Comment by xiongbl526** [comment]
没有持续的大流量写入，流量是有峰谷的 使用内存一天多1个g 持续上涨



---- 回复的原邮件 ----
| 发件人 | Maomeng ***@***.***> |
| 日期 | 2024年09月09日 15:21 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] worker机器使用内存持续上涨 (Issue #1851) |

这会有在做大量写入和merge吗

**Comment by smmsmm1988** [comment]
刚刚启动的节点吗？那怀疑就是cache的数据在不断填充，还没有到达上限，然后感官上内存使用是不断上涨的。可以执行如下sql排查下：
select *, formatReadableSize(value)  from cnch('{vw_name}', system.asynchronous_metrics) where metric like '%Cache%' order by metric;

**Comment by xiongbl526** [comment]
不是刚启动的，有的实例距离上次重启已经四五天了，有的已经一个多星期了



---- 回复的原邮件 ----
| 发件人 | Maomeng ***@***.***> |
| 日期 | 2024年09月09日 17:31 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] worker机器使用内存持续上涨 (Issue #1851) |

刚刚启动的节点吗？那怀疑就是cache的数据在不断填充，还没有到达上限，然后感官上内存使用是不断上涨的。可以执行如下sql排查下：
select *, formatReadableSize(value) from cnch('{vw_name}', system.asynchronous_metrics) where metric like '%Cache%' order by metric;

**Comment by smmsmm1988** [comment]
> 不是刚启动的，有的实例距离上次重启已经四五天了，有的已经一个多星期了
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | Maomeng ***@***.***> | | 日期 | 2024年09月09日 17:31 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [ByConity/ByConity] worker机器使用内存持续上涨 (Issue #1851) | 刚刚启动的节点吗？那怀疑就是cache的数据在不断填充，还没有到达上限，然后感官上内存使用是不断上涨的。可以执行如下sql排查下： select *, formatReadableSize(value) from cnch('{vw_name}', system.asynchronous_metrics) where metric like '%Cache%' order by metric; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

嗯，可以通过上述sql看一下数据统计

**Comment by smmsmm1988** [comment]
看上去没啥明显的异常。另外，你说的mark_cache_size、cnch_checksums_cache_size、uncompressed_cache_size这些用的默认的，是配置文件里都没有配置吗？没有配置的话，mark_cache_size和cnch_checksums_cache_size默认都是5GB，但是uncompressed_cache_size默认是不限制的。

**Comment by xiongbl526** [comment]
上面sql中哪个指标是和uncompressed_cache_size相关的呢？ 另外uncompressed_cache_size这个配置应该加在哪个配置文件中，我是helm部署的



---- 回复的原邮件 ----
| 发件人 | Maomeng ***@***.***> |
| 日期 | 2024年09月10日 10:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] worker机器使用内存持续上涨 (Issue #1851) |

看上去没啥明显的异常。另外，你说的mark_cache_size、cnch_checksums_cache_size、uncompressed_cache_size这些用的默认的，是配置文件里都没有配置吗？没有配置的话，mark_cache_size和cnch_checksums_cache_size默认都是5GB，但是uncompressed_cache_size默认是不限制的。

**Comment by smmsmm1988** [comment]
> 上面sql中哪个指标是和uncompressed_cache_size相关的呢？ 另外uncompressed_cache_size这个配置应该加在哪个配置文件中，我是helm部署的
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | Maomeng ***@***.***> | | 日期 | 2024年09月10日 10:28 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [ByConity/ByConity] worker机器使用内存持续上涨 (Issue #1851) | 看上去没啥明显的异常。另外，你说的mark_cache_size、cnch_checksums_cache_size、uncompressed_cache_size这些用的默认的，是配置文件里都没有配置吗？没有配置的话，mark_cache_size和cnch_checksums_cache_size默认都是5GB，但是uncompressed_cache_size默认是不限制的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

比较奇怪你这里为啥没有展示出来，预期是应该有个UncompressedCacheBytes字段的统计。你现在内存总体水位达到多少了？
另外，uncompressed_cache_size这个配置就直接配置在worker对应的config中即可，需要重启生效

**Comment by xiongbl526** [comment]
机器总内存32g 目前这个实例内部使用达到70%左右了 我查了其它几个bc实例也没有uncompressed这个缓存的统计数据



---- 回复的原邮件 ----
| 发件人 | Maomeng ***@***.***> |
| 日期 | 2024年09月10日 10:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] worker机器使用内存持续上涨 (Issue #1851) |

上面sql中哪个指标是和uncompressed_cache_size相关的呢？ 另外uncompressed_cache_size这个配置应该加在哪个配置文件中，我是helm部署的
…
---- 回复的原邮件 ---- | 发件人 | Maomeng @.> | | 日期 | 2024年09月10日 10:28 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [ByConity/ByConity] worker机器使用内存持续上涨 (Issue #1851) | 看上去没啥明显的异常。另外，你说的mark_cache_size、cnch_checksums_cache_size、uncompressed_cache_size这些用的默认的，是配置文件里都没有配置吗？没有配置的话，mark_cache_size和cnch_checksums_cache_size默认都是5GB，但是uncompressed_cache_size默认是不限制的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>

比较奇怪你这里为啥没有展示出来，预期是应该有个UncompressedCacheBytes字段的统计。你现在内存总体水位达到多少了？
另外，uncompressed_cache_size这个配置就直接配置在worker对应的config中即可，需要重启生效

**Comment by smmsmm1988** [comment]
> 机器总内存32g 目前这个实例内部使用达到70%左右了 我查了其它几个bc实例也没有uncompressed这个缓存的统计数据
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | Maomeng ***@***.***> | | 日期 | 2024年09月10日 10:55 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [ByConity/ByConity] worker机器使用内存持续上涨 (Issue #1851) | 上面sql中哪个指标是和uncompressed_cache_size相关的呢？ 另外uncompressed_cache_size这个配置应该加在哪个配置文件中，我是helm部署的 … ---- 回复的原邮件 ---- | 发件人 | Maomeng @.> | | 日期 | 2024年09月10日 10:28 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [ByConity/ByConity] worker机器使用内存持续上涨 (Issue #1851) | 看上去没啥明显的异常。另外，你说的mark_cache_size、cnch_checksums_cache_size、uncompressed_cache_size这些用的默认的，是配置文件里都没有配置吗？没有配置的话，mark_cache_size和cnch_checksums_cache_size默认都是5GB，但是uncompressed_cache_size默认是不限制的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***> 比较奇怪你这里为啥没有展示出来，预期是应该有个UncompressedCacheBytes字段的统计。你现在内存总体水位达到多少了？ 另外，uncompressed_cache_size这个配置就直接配置在worker对应的config中即可，需要重启生效 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

知道了，如果你没有配置uncompressed_cache_size的话，UncompressedCacheBytes这个指标看不到，所以可以配置下这个值，先配置成内存容量的一半看看

**Comment by smmsmm1988** [comment]
@xiongbl526 这块还有进一步的问题吗

**Comment by xiongbl526** [comment]
uncompressed_cache_size 这个参数适用于server服务吗 我们发现server服务内存也是持续上涨不释放

**Comment by smmsmm1988** [comment]
> uncompressed_cache_size 这个参数适用于server服务吗 我们发现server服务内存也是持续上涨不释放

也适用
