### ISSUE TITLE
关于升级的问题

### ISSUE THREAD

**Issue by justinxiongbin** [ByConity/ByConity#1853]
(you don't have to strictly follow this form)

## Question
我使用docker-compose部署的所有服务，目前使用0.4.1版本，里面已经存储了业务数据，数据均已经挂载到宿主机磁盘上，如果我要升级到1.0.0的话，只不是只需要升级 byconity/byconity:0.4.1 镜像相关的容器，而fdb、hadoop相关的可以不用更新？

更新 byconity/byconity:0.4.1 相关服务时，是不是只需要替换镜像，重新创建容器即可？

另外，从0.4.1到1.0.0，是否有什么变化，我看官网上的文档，还没有更新到1.0.0

1.0.0版本，目前是否已经可以上生产环境使用？

**Comment by ixnzh** [comment]
FDB和HDFS可以不更新，

ByConity可以Worker、RM、TSO、Server，dm 照这个顺序覆盖升级就可以，

理论上生产使用是没问题的哈，1.0版本我们做了很多测试
