### ISSUE TITLE
server服务突然异常

### ISSUE THREAD

**Issue by xiongbl526** [ByConity/ByConity#1856]
(you don't have to strictly follow this form)

## Question
byconity 0.4.2版本
server服务和tso服务突然报错oid DB::StorageElector::doFollowerCheck(): Code: 1031, e.displayText() = DB::Exception: FDB error : Operation aborted because the transaction timed out SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):

fdb组件均有多个pod

**Comment by xiongbl526** [comment]
server服务探活一直失败不断重启中 加了cpu也不行

**Comment by xiongbl526** [comment]
fdb> status

WARNING: Long delay (Ctrl-C to interrupt)

Using cluster file `/mnt/config-volume/cluster-file'.

Could not communicate with all of the coordination servers.
  The database will remain operational as long as we
  can connect to a quorum of servers, however the fault
  tolerance of the system is reduced as long as the
  servers remain disconnected.

  10.43.30.26:4501  (reachable)
  10.43.202.94:4501  (reachable)
  10.43.62.156:4501  (unreachable)

The coordinator(s) have no record of this database. Either the coordinator
addresses are incorrect, the coordination state on those machines is missing, or
no database has been created.

Unable to locate the data distributor worker.

Unable to locate the ratekeeper worker.

**Comment by xiongbl526** [comment]
fdb相关的Pod容器化里的网段我看都是10.42的 没有10.43的

**Comment by xiongbl526** [comment]
所有Pod不能重启 一重启都起不来了

**Comment by xiongbl526** [comment]
10.43.62.156:4501  (unreachable) 这个是fdb 组件一个storage pod的service 10.43.62.156:4501  (unreachable) 这个是fdb 组件一个storage pod的service 这个storage所在宿主机有问题 被强制从集群中删除了

**Comment by smmsmm1988** [comment]
@xiongbl526  DB::Exception: FDB error : Operation aborted because the transaction timed out
这种异常一般都是fdb出问题了，大多数情况下是fdb负载被打满了

**Comment by xiongbl526** [comment]
这次是元数据丢了，数据没找回来



---- 回复的原邮件 ----
| 发件人 | Maomeng ***@***.***> |
| 日期 | 2024年09月13日 09:57 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] server服务突然异常 (Issue #1856) |

@xiongbl526 DB::Exception: FDB error : Operation aborted because the transaction timed out
这种异常一般都是fdb出问题了，大多数情况下是fdb负载被打满了

**Comment by smmsmm1988** [comment]
> 这次是元数据丢了，数据没找回来
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | Maomeng ***@***.***> | | 日期 | 2024年09月13日 09:57 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [ByConity/ByConity] server服务突然异常 (Issue #1856) | @xiongbl526 DB::Exception: FDB error : Operation aborted because the transaction timed out 这种异常一般都是fdb出问题了，大多数情况下是fdb负载被打满了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

fdb元数据丢的原因是什么

**Comment by xiongbl526** [comment]
因阿里云机房失火进水，导致有个storage所在宿主机异常，没有同步元数据到其它pod上，然后协调器也没更新，这个storage宿主机被删了后，就异常了



---- 回复的原邮件 ----
| 发件人 | Maomeng ***@***.***> |
| 日期 | 2024年09月13日 12:39 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] server服务突然异常 (Issue #1856) |

这次是元数据丢了，数据没找回来
…
---- 回复的原邮件 ---- | 发件人 | Maomeng @.> | | 日期 | 2024年09月13日 09:57 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [ByConity/ByConity] server服务突然异常 (Issue #1856) | @xiongbl526 DB::Exception: FDB error : Operation aborted because the transaction timed out 这种异常一般都是fdb出问题了，大多数情况下是fdb负载被打满了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***>

fdb元数据丢的原因是什么
