### ISSUE TITLE
基于云盘如何恢复fdb数据

### ISSUE THREAD

**Issue by xiongbl526** [ByConity/ByConity#1858]
(you don't have to strictly follow this form)

## Question
bc实例 k8s部署 0.4.2版本 因异常情况导致bc实例fdb的pod被删除  但是fdb的数据云盘都已经打了快照
如何基于云盘恢复fdb到新的Bc实例

**Comment by xiongbl526** [comment]
fdb组件log和storage云盘都在 2副本

**Comment by smmsmm1988** [comment]
意思是fdb没有丢数据是吗，没有丢数据的话，可能得参照下fdb的文档来看看怎么恢复fdb的数据了，fdb这块我们了解也不深入
