### ISSUE TITLE
简单查询性能问题排查

### ISSUE THREAD

**Issue by fs273** [ByConity/ByConity#1859]
**问题简述:**
新建bc集群用于替代现在clickhouse集群，同样结构表、同样查询语句两者性能差异较大
ch集群单表(Distributed) 150亿数据查询响应时间200ms
bc集群单表(CnchMergeTree）13亿数据查询响应时间： 主键(datetime)2s,  int型7s, ipv4 28s,
均为select a from x where b=x 简单查询，列是否为projection影响不大
select a from x limit 100  耗时11秒， 稍复杂查询耗时几分钟以上
**BC集群情况：**
复用CH集群物理机10台部署k8s集群（CH集群目前已闲置用于测试，无生产任务）
参考“基于Kubernetes集群部署”文档，在k8s上部署fdb/hdfs，使用openebs local pv作为存储，最终部署1.0版本bc集群
集群状态正常，无pod重启情况
中间尝试使用minio部署s3存储，性能测试可以跑满万兆带宽，但也遇到了[MinIO集群持续高负载](https://github.com/ByConity/ByConity/issues/1840)问题，怀疑是s3兼容性问题换hdfs后，同样查询性能较弱
**日志（query_log和profile_events）:**
![1](https://github.com/user-attachments/assets/a7899a6a-653e-457d-9f57-ce6f883e7009)
![2](https://github.com/user-attachments/assets/7bf15cb9-264f-4f63-81ac-d16f85f20e48)
![3](https://github.com/user-attachments/assets/d7e6dd33-9720-4d32-b3bc-469a10563af8)
想问下一步该如何排查

**Comment by superhail** [comment]
你这是热查询还是冷查询？
下面的查询执行一下，看看worker上的一些指标
```
select
    sum(ProfileEvents ['SelectedParts']) as selected_parts,
    argMax(podName(), query_duration_ms) as slow_node,
    sum(length(thread_ids)) as thread_count,
    round(max(ProfileEvents ['SystemTimeMicroseconds'] / 1000 + ProfileEvents ['UserTimeMicroseconds'] / 1000)) as max_cpu,
    round(sum(ProfileEvents ['SystemTimeMicroseconds'] / 1000 + ProfileEvents ['UserTimeMicroseconds'] / 1000)) as cpu,
    formatReadableSize(sum(ProfileEvents ['ReadBufferFromHdfsReadBytes'])) as hdfs_read_bytes,
    formatReadableSize(sum(ProfileEvents ['ReadBufferFromFileDescriptorReadBytes'])) as disk_read_bytes,
    sum(ProfileEvents ['SelectedMarks']) as selected_marks,
    max(query_duration_ms),
    max(MaxIOThreadProfileEvents ['RemoteFSAsynchronousReadWaitMicroseconds']) / 1000 as max_hdfs_read_time,
    max(MaxIOThreadProfileEvents ['DiskReadElapsedMicroseconds']) / 1000 AS max_disk_read_time,
    segment_id,
    count()
from
    cnch(<vw_name>, system.query_log)
where
    event_date = <execution_date>
    AND type > 1
    AND initial_query_id = <query_id>
group by
    segment_id
ORDER BY
    cpu DESC;
```

**Comment by fs273** [comment]
![4](https://github.com/user-attachments/assets/05eb2dec-ae31-4715-8950-7f9306850c24)
这是worker的指标

**Comment by smmsmm1988** [comment]
@fs273 你这个看起来是发生了冷读呀，hdfs的读取时间非常慢。多执行几次应该就会变快了。
![image](https://github.com/user-attachments/assets/be16974a-d248-4a7a-ad64-9697321b6114)

**Comment by fs273** [comment]
![5](https://github.com/user-attachments/assets/070ea8a4-7b61-4e1b-85b1-138f501bdae8)
刚才贴错了，这个是query_id为11秒那个的结果，看起来hdfs不是瓶颈问题

**Comment by fs273** [comment]
> @fs273 你这个看起来是发生了冷读呀，hdfs的读取时间非常慢，本地缓存盘的读取时间就比较快。多执行几次应该就会变快了。 ![image](https://private-user-images.githubusercontent.com/7722001/368414381-be16974a-d248-4a7a-ad64-9697321b6114.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MzE4MjksIm5iZiI6MTcyNjYzMTUyOSwicGF0aCI6Ii83NzIyMDAxLzM2ODQxNDM4MS1iZTE2OTc0YS1kMjQ4LTRhN2EtYWQ2NC05Njk3MzIxYjYxMTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MThUMDM1MjA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTNlYmJhMzI3NmE3N2U4ZGFhYzhhMTNjOTg0YzMwYzNjODlhNjgwNDkwNmY1OWNlNGFlZmQzZDk4YmI3MDlhYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vhG-nTBu9ZAU-mLZZPVOmk9jlr5INSvrxiEXIw_PZDc)

应该确实是冷查询，因为现在集群只有我在测试用，也是偶尔查一下，但hdfs也是用的openebs本地盘，这个性能损耗会那么大?前期只用过ch集群，对hdfs这些不太熟悉

**Comment by smmsmm1988** [comment]
> > @fs273 你这个看起来是发生了冷读呀，hdfs的读取时间非常慢，本地缓存盘的读取时间就比较快。多执行几次应该就会变快了。 ![image](https://private-user-images.githubusercontent.com/7722001/368414381-be16974a-d248-4a7a-ad64-9697321b6114.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MzE4MjksIm5iZiI6MTcyNjYzMTUyOSwicGF0aCI6Ii83NzIyMDAxLzM2ODQxNDM4MS1iZTE2OTc0YS1kMjQ4LTRhN2EtYWQ2NC05Njk3MzIxYjYxMTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MThUMDM1MjA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTNlYmJhMzI3NmE3N2U4ZGFhYzhhMTNjOTg0YzMwYzNjODlhNjgwNDkwNmY1OWNlNGFlZmQzZDk4YmI3MDlhYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vhG-nTBu9ZAU-mLZZPVOmk9jlr5INSvrxiEXIw_PZDc)
> 
> 应该确实是冷查询，因为现在集群只有我在测试用，也是偶尔查一下，但hdfs也是用的openebs本地盘，这个性能损耗会那么大?前期只用过ch集群，对hdfs这些不太熟悉

冷查询确实对性能影响比较大，无论是hdfs还是s3，这个无法避免。但是当数据缓存到本地后，后续对缓存数据的查询就直接走本地盘，性能就等同于在本地执行查询了

**Comment by fs273** [comment]
> 冷查询确实对性能影响比较大，无论是hdfs还是s3，这个无法避免。但是当数据缓存到本地后，后续对缓存数据的查询就直接走本地盘，性能就等同于在本地执行查询了
主楼的select a from x limit 100的log显示并没有冷查询hdfs时间消耗，最终也用了11秒多，这个确实非常慢了，请问下原因？还需要怎么排查

**Comment by smmsmm1988** [comment]
> > 冷查询确实对性能影响比较大，无论是hdfs还是s3，这个无法避免。但是当数据缓存到本地后，后续对缓存数据的查询就直接走本地盘，性能就等同于在本地执行查询了
> 
> @smmsmm1988 主楼的select a from x limit 100的log显示并没有冷查询hdfs时间消耗，最终也用了11秒多，这个确实非常慢了，请问下原因？还需要怎么排查

这个也用上面superhail给的sql语句，先找下统计信息看下，看是cpu-bound还是io-bound。另外也可以explain analyze select a from x limit 100执行看下执行计划

**Comment by smmsmm1988** [comment]
@fs273 请问有进一步的进展吗

**Comment by fs273** [comment]
![7](https://github.com/user-attachments/assets/1bc86fb3-28e6-48da-bdaa-f20057e622cf)
![6](https://github.com/user-attachments/assets/9ddf237b-9292-4fa7-99a8-7d92cb34e0e0)
还是一个简单查询的explain analyze和log结果，感觉瓶颈在input wait time这里，这个是等待IO的时间？但为什么log里hdfs感觉并没有耗费太多时间
执行多次还是会在10秒以上，设置了表的预加载level3也没啥提升

**Comment by smmsmm1988** [comment]
@fs273 可以在下面的log里，进一步加如下的sum结果看看io时间：
sum(ProfileEvents.Values[indexOf(ProfileEvents.Names, 'DiskReadElapsedMicroseconds')]) AS disk_time,
sum(ProfileEvents.Values[indexOf(ProfileEvents.Names, 'HDFSReadElapsedMicroseconds')]) AS hdfs_time

**Comment by smmsmm1988** [comment]
你这个表总共有多少个part

**Comment by smmsmm1988** [comment]
![image](https://github.com/user-attachments/assets/ffe6c732-be10-40c8-905f-dfa8a50222ed)
原因可能清楚了，你这个表的part是不是太多了呀，全表做扫描，把part都搞出来了，十几万个part，导致元数据操作耗时比较多（当然十几万个part对应的io操作耗时也不低）。你可以加个where分区过滤，看看时间是不是显著下降了。

**Comment by smmsmm1988** [comment]
把这个表的schema辛苦也发一下

**Comment by fs273** [comment]
schema里面partition by toYYYYMM(begin_time)，是按月做的part，怎么会这么多
我查一下，稍等

**Comment by fs273** [comment]
> 把这个表的schema辛苦也发一下

![8](https://github.com/user-attachments/assets/5002c2ce-aa19-4a93-8a3d-53b33fc206e7)
查了一下system.parts表（byconity也是这个表吧），是正常的，并没有10几万个parts

**Comment by smmsmm1988** [comment]
> > 把这个表的schema辛苦也发一下
> 
> ![8](https://private-user-images.githubusercontent.com/181553768/369799066-5002c2ce-aa19-4a93-8a3d-53b33fc206e7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwODAyNTcsIm5iZiI6MTcyNzA3OTk1NywicGF0aCI6Ii8xODE1NTM3NjgvMzY5Nzk5MDY2LTUwMDJjMmNlLWFhMTktNGE5My04YTNkLTUzYjMzZmMyMDZlNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QwODI1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OWJiODE0MjhhNTBmZGQ3ZWVlYjM3NDc3MDhjYzZjYzJjZjA4NTg1NDkyNjRiOTBmY2VjNDg4MmNmZjczYmViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3ALxQ3b8yNvHR3NaT3cLJtgpQnmU5bvIh7WMv6nCBN8) 查了一下system.parts表（byconity也是这个表吧），是正常的，并没有10几万个parts

select count() from cnch(server, system.cnch_parts) where database = 'xxxx' and table = 'yyyyy'

**Comment by fs273** [comment]
> > > 把这个表的schema辛苦也发一下
> > 
> > 
> > ![8](https://private-user-images.githubusercontent.com/181553768/369799066-5002c2ce-aa19-4a93-8a3d-53b33fc206e7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwODAyNTcsIm5iZiI6MTcyNzA3OTk1NywicGF0aCI6Ii8xODE1NTM3NjgvMzY5Nzk5MDY2LTUwMDJjMmNlLWFhMTktNGE5My04YTNkLTUzYjMzZmMyMDZlNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QwODI1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OWJiODE0MjhhNTBmZGQ3ZWVlYjM3NDc3MDhjYzZjYzJjZjA4NTg1NDkyNjRiOTBmY2VjNDg4MmNmZjczYmViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3ALxQ3b8yNvHR3NaT3cLJtgpQnmU5bvIh7WMv6nCBN8) 查了一下system.parts表（byconity也是这个表吧），是正常的，并没有10几万个parts
> 
> select count() from cnch(server, system.cnch_parts) where database = 'xxxx' and table = 'yyyyy'

原因应该在这了，这个有25万个parts，为什么会这样

**Comment by smmsmm1988** [comment]
> > > > 把这个表的schema辛苦也发一下
> > > 
> > > 
> > > ![8](https://private-user-images.githubusercontent.com/181553768/369799066-5002c2ce-aa19-4a93-8a3d-53b33fc206e7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwODAyNTcsIm5iZiI6MTcyNzA3OTk1NywicGF0aCI6Ii8xODE1NTM3NjgvMzY5Nzk5MDY2LTUwMDJjMmNlLWFhMTktNGE5My04YTNkLTUzYjMzZmMyMDZlNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QwODI1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OWJiODE0MjhhNTBmZGQ3ZWVlYjM3NDc3MDhjYzZjYzJjZjA4NTg1NDkyNjRiOTBmY2VjNDg4MmNmZjczYmViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3ALxQ3b8yNvHR3NaT3cLJtgpQnmU5bvIh7WMv6nCBN8) 查了一下system.parts表（byconity也是这个表吧），是正常的，并没有10几万个parts
> > 
> > 
> > select count() from cnch(server, system.cnch_parts) where database = 'xxxx' and table = 'yyyyy'
> 
> 原因应该在这了，这个有25万个parts 每个part有1万条数据，可能跟入库方式有关了，现在用的kettle的jdbc驱动，每次入库1万条

select toStartOfHour(event_time) as t, countIf(event_type = 1) as i, sumIf(num_source_parts , event_type = 2) as m from cnch(server, system.server_part_log) where event_date >= today() - 3 and database = 'xxx' and table = 'yyy' group by t order by t;

看看merge有没有在正常做

**Comment by smmsmm1988** [comment]
你这个表的partition by和ttl不match，分区的表达式应该和ttl的表达式一致，因为byconity不支持行级别的ttl。如果要确定按月分区，需要把partition改成partition by toStartOfMonth(ip_begin_time)，ttl改成 toStartOfMonth(ip_begin_time) + toIntervalMonth(12)

**Comment by fs273** [comment]
![9](https://github.com/user-attachments/assets/85699d9c-7b22-453a-ae66-2f9ae2317f8e)
这个ttl会对merge产生影响么

**Comment by smmsmm1988** [comment]
select count(), partition from cnch(server, system.cnch_parts) where database = 'xxxx' and table = 'yyyyy' group by partition order by partition。看看每个partition有多少个part

**Comment by fs273** [comment]
> select count(), partition from cnch(server, system.cnch_parts) where database = 'xxxx' and table = 'yyyyy' group by partition order by partition。看看每个partition有多少个part

只有一个partition 202407,  有20多万个part

**Comment by zeromem** [comment]
@fs273 启动 dm 了吗？ 查一下 `select * from system.dm_bg_jobs where table = 'xx' and database = 'xx';` 看看后台的 merge 调度线程的状态

**Comment by fs273** [comment]
> @fs273 启动 dm 了吗？ 查一下 `select * from system.dm_bg_jobs where table = 'xx' and database = 'xx';` 看看后台的 merge 调度线程的状态

这个 system.dm_bg_jobs是空的，看了下k8s上Pod byconity-daemon-manager是正常运行的，需要看下日志？

**Comment by zeromem** [comment]
> > @fs273 启动 dm 了吗？ 查一下 `select * from system.dm_bg_jobs where table = 'xx' and database = 'xx';` 看看后台的 merge 调度线程的状态
> 
> 这个 system.dm_bg_jobs是空的，看了下k8s上Pod byconity-daemon-manager是正常运行的，需要看下日志？

嗯 看一下 dm 的日志。 后台 merge 调度依赖于 dm，正常情况下 dm_bg_jobs 能查到每个CnchMergeTree 的任务调度状态

**Comment by fs273** [comment]
因为物理机上clickhouse占用了9000和8123端口，在部署时，我修改了values.yaml中tcp端口为9100，http端口为8223
但看了下现在byconity-dm-conifg中daemon-manager.yaml端口设置还是8123和9000
是不是这个原因，我改一下试试

**Comment by fs273** [comment]
> 嗯 看一下 dm 的日志。 后台 merge 调度依赖于 dm，正常情况下 dm_bg_jobs 能查到每个CnchMergeTree 的任务调度状态
![10](https://github.com/user-attachments/assets/568b9ddc-568a-41d8-929c-1cc07c0624fb)
报错了

**Comment by fs273** [comment]
> > 嗯 看一下 dm 的日志。 后台 merge 调度依赖于 dm，正常情况下 dm_bg_jobs 能查到每个CnchMergeTree 的任务调度状态
> 
> ![10](https://private-user-images.githubusercontent.com/181553768/369833109-568b9ddc-568a-41d8-929c-1cc07c0624fb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwOTEwMTMsIm5iZiI6MTcyNzA5MDcxMywicGF0aCI6Ii8xODE1NTM3NjgvMzY5ODMzMTA5LTU2OGI5ZGRjLTU2OGEtNDFkOC05MjljLTFjYzA3YzA2MjRmYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QxMTI1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjJjYzExYjc4MDFkNWU2NDYzYjhmNjk5MTJjMGQyNzIzZGM5ZjZlMjkzMGJhN2U5MGJhZjExY2IzOTExYzFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CVlgUnNrDwts62LdFJJPL_Gzz8DqfBSaY_GNAJpvQaM) 报错了 @zeromem
看起来 #1850 解决了这个问题，我试一下

**Comment by fs273** [comment]
打开k8s config map的byconity-dm-config配置，添加一行
`hdfs_addr: hdfs://byconity-hdfs-namenodes:8020`
到daemon-manager.yaml，重启dm pod即可解决上面问题
等待parts merge任务完成后，现在简单查询在毫秒级了
感谢耐心帮助排查

**Comment by smmsmm1988** [comment]
> #1850

问题解决了就好
