### ISSUE TITLE
1.0.0磁盘io异常增加，导致node宕机

### ISSUE THREAD

**Issue by jiumos** [ByConity/ByConity#1867]
(you don't have to strictly follow this form)

## Question
环境上三个node，每个node均部署了读写woker和server。
期间，异常node的磁盘读速率达到了150Mbps。重启异常node以后，整体恢复正常

**Comment by jiumos** [comment]
![20240923-153502](https://github.com/user-attachments/assets/a6205b9f-5493-4187-ba06-7843f00b14a1)
系统资源图

**Comment by smmsmm1988** [comment]
https://github.com/ByConity/ByConity/issues/1764
可以参考下这个issue，有可能是缓存预加载导致的io升高，也有可能是merge增加了（可以通过issue中的sql查询确认下）。另外，这个时间段，集群的查询、写入请求有什么变化吗？

**Comment by jiumos** [comment]
> #1764 可以参考下这个issue，有可能是缓存预加载导致的io升高，也有可能是merge增加了（可以通过issue中的sql查询确认下）。另外，这个时间段，集群的查询、写入请求有什么变化吗？

这个issue 是通过增加work数量解决，这边最开始是一组读写worker，后来单node出现io异常以后，才增加到三组worker。请问还有其他方法吗？

**Comment by smmsmm1988** [comment]
如果确定增加worker数量能解决，那么可能就是查询或者写入高峰把io打满了。需要确定对应的时间段内的查询、写入或者merge是否出现了高峰

**Comment by jiumos** [comment]
> 如果确定增加worker数量能解决，那么可能就是查询或者写入高峰把io打满了。需要确定对应的时间段内的查询、写入或者merge是否出现了高峰

增加worker以后，并没有完全解决问题，现在每天都会出现因为读io过高而宕机的现象。另外，bc有获取查询速率的方法吗

**Comment by smmsmm1988** [comment]
@jiumos select toStartOfHour(event_time) as t, countIf(event_type = 1) as i, formatReadableSize(sumIf(bytes, event_type = 1)) as i_size, sumIf(num_source_parts , event_type = 2) as m, formatReadableSize(sumIf(bytes, event_type = 2)) as m_size from cnch(server, system.server_part_log) where event_date >= today() - 2 group by t order by t;

可以通过上述sql先看看写入和merge的情况

**Comment by jiumos** [comment]
> @jiumos select toStartOfHour(event_time) as t, countIf(event_type = 1) as i, formatReadableSize(sumIf(bytes, event_type = 1)) as i_size, sumIf(num_source_parts , event_type = 2) as m, formatReadableSize(sumIf(bytes, event_type = 2)) as m_size from cnch(server, system.server_part_log) where event_date >= today() - 2 group by t order by t;
> 
> 可以通过上述sql先看看写入和merge的情况

│ 2024-09-24 21:00:00 │  8435 │ 3.42 GiB   │  9104 │ 13.05 GiB │
│ 2024-09-24 22:00:00 │ 22745 │ 8.37 GiB   │ 23519 │ 15.82 GiB │
│ 2024-09-24 23:00:00 │ 18104 │ 7.00 GiB   │ 19332 │ 19.45 GiB │
│ 2024-09-25 00:00:00 │ 12742 │ 5.06 GiB   │ 13442 │ 13.18 GiB │
│ 2024-09-25 01:00:00 │ 13998 │ 5.39 GiB   │ 16064 │ 19.77 GiB │
│ 2024-09-25 02:00:00 │ 15741 │ 5.12 GiB   │ 18088 │ 20.10 GiB   
数据如图，发生宕机的时间段是北京时间8.39.也就是途中的 2024-09-25 00:00:00。

**Comment by jiumos** [comment]
@smmsmm1988 
这是今天宕机前对bc的写入速率的图，并没有出现突增的速率。
![20240925-110222](https://github.com/user-attachments/assets/cefbd15a-2d6c-4965-a911-a3414ee9b4da)

**Comment by smmsmm1988** [comment]
> @smmsmm1988 这是今天宕机前对bc的写入速率的图，并没有出现突增的速率。 ![20240925-110222](https://private-user-images.githubusercontent.com/58871328/370537734-cefbd15a-2d6c-4965-a911-a3414ee9b4da.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNDU2NzYsIm5iZiI6MTcyNzI0NTM3NiwicGF0aCI6Ii81ODg3MTMyOC8zNzA1Mzc3MzQtY2VmYmQxNWEtMmQ2Yy00OTY1LWE5MTEtYTM0MTRlZTliNGRhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDA2MjI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4NDc1N2YwNjdjMWVmMTliZGQ2ZWZkNzhjNmNhMzQyYjE0OGExNTUyNGY2YThjMzU5MzQ0NDcwY2ExNzk4MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.g2j2kGYYrKgFuhR9BAv7rg1857hPLh3UcWZSFiRmrig)

但是宕机前读的速率就打满了是吗？

**Comment by jiumos** [comment]
@smmsmm1988  是的，从监控来看读io突然就满了，然后就宕机了，磁盘读io速率达到了阿里云主机的上限(150Mbps) 。希望有配置能限制下突增的读io速率。

**Comment by smmsmm1988** [comment]
> @smmsmm1988 是的，从监控来看读io突然就满了，然后就宕机了，磁盘读io速率达到了阿里云主机的上限(150Mbps) 。希望有配置能限制下突增的读io速率。

SELECT toStartOfHour(event_time) AS t, count() FROM cnch(server, system, query_log) WHERE (event_date >= today() - 2) AND is_initial_query AND (type != 1) GROUP BY t ORDER BY t ASC
看下查询量的统计

**Comment by jiumos** [comment]
> > @smmsmm1988 是的，从监控来看读io突然就满了，然后就宕机了，磁盘读io速率达到了阿里云主机的上限(150Mbps) 。希望有配置能限制下突增的读io速率。
> 
> SELECT toStartOfHour(event_time) AS t, count() FROM cnch(server, system, query_log) WHERE (event_date >= today() - 2) AND is_initial_query AND (type != 1) GROUP BY t ORDER BY t ASC 看下查询量的统计

┌───────────────────t─┬─count()─┐
│ 2024-09-25 00:00:00 │   68996 │
│ 2024-09-25 01:00:00 │  128685 │
│ 2024-09-25 02:00:00 │  170376 │
│ 2024-09-25 03:00:00 │  176819 │
│ 2024-09-25 04:00:00 │  256913 │
│ 2024-09-25 05:00:00 │  338452 │
│ 2024-09-25 06:00:00 │  308753 │
│ 2024-09-25 07:00:00 │  318444 │
│ 2024-09-25 08:00:00 │  338301 │
│ 2024-09-25 09:00:00 │  323181 │
│ 2024-09-25 10:00:00 │  328416 │
│ 2024-09-25 11:00:00 │  341689 │
│ 2024-09-25 12:00:00 │  315951 │
│ 2024-09-25 13:00:00 │  328529 │
│ 2024-09-25 14:00:00 │  323329 │
│ 2024-09-25 15:00:00 │  328154 │
│ 2024-09-25 16:00:00 │  334936 │
│ 2024-09-25 17:00:00 │  324670 │
│ 2024-09-25 18:00:00 │  323062 │
│ 2024-09-25 19:00:00 │  340693 │
│ 2024-09-25 20:00:00 │  429126 │
│ 2024-09-25 21:00:00 │  439365 │
│ 2024-09-25 22:00:00 │  578920 │
│ 2024-09-25 23:00:00 │  398746 │
│ 2024-09-26 00:00:00 │ 1083293 │
│ 2024-09-26 01:00:00 │  987870 │
│ 2024-09-26 02:00:00 │  581152

**Comment by smmsmm1988** [comment]
![image](https://github.com/user-attachments/assets/83f3a370-b8a0-4893-aa53-3c3dd4dd7913)

@jiumos 这两个时间段的比较猛呀

**Comment by jiumos** [comment]
> ![image](https://private-user-images.githubusercontent.com/7722001/370969918-83f3a370-b8a0-4893-aa53-3c3dd4dd7913.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMjEyMTEsIm5iZiI6MTcyNzMyMDkxMSwicGF0aCI6Ii83NzIyMDAxLzM3MDk2OTkxOC04M2YzYTM3MC1iOGEwLTQ4OTMtYWE1My0zYzNkZDRkZDc5MTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjZUMDMyMTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njk2MTM2YjdjYThhNDRmMDdmNTU0ZmY0YmFkOTBkOTE4OTdjZmRlNTdmYjUwMjM3ZThhMjAwOGUxNWRmZDllYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.HZdnuBu_9Trvn7xF7T5gux4vHVUbSNv39RzO5yCC7Ao)
> 
> @jiumos 这两个时间段的比较猛呀

这个时间段，会重启服务。所以查询会激增，这么看来前几天宕机也多发生在这个时间段。请问有什么办法能缓解这种情况吗？

**Comment by smmsmm1988** [comment]
> > ![image](https://private-user-images.githubusercontent.com/7722001/370969918-83f3a370-b8a0-4893-aa53-3c3dd4dd7913.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMjEyMTEsIm5iZiI6MTcyNzMyMDkxMSwicGF0aCI6Ii83NzIyMDAxLzM3MDk2OTkxOC04M2YzYTM3MC1iOGEwLTQ4OTMtYWE1My0zYzNkZDRkZDc5MTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjZUMDMyMTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njk2MTM2YjdjYThhNDRmMDdmNTU0ZmY0YmFkOTBkOTE4OTdjZmRlNTdmYjUwMjM3ZThhMjAwOGUxNWRmZDllYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.HZdnuBu_9Trvn7xF7T5gux4vHVUbSNv39RzO5yCC7Ao)
> > @jiumos 这两个时间段的比较猛呀
> 
> 这个时间段，会重启服务。所以查询会激增，这么看来前几天宕机也多发生在这个时间段。请问有什么办法能缓解这种情况吗？

你这个查询有点猛，要么增加磁盘访问的带宽限制，要么继续扩容worker

**Comment by smmsmm1988** [comment]
@jiumos 请问还有进一步的问题吗？

**Comment by jiumos** [comment]
> @jiumos 请问还有进一步的问题吗？

没有了
