### ISSUE TITLE
物理机扩容问题

### ISSUE THREAD

**Issue by lee-liyl** [ByConity/ByConity#1868]
我初始三台服务器按照[物理机部署](https://byconity.github.io/zh-cn/docs/deployment/package-deployment)进行部署，并向其打入数据，测试查询后发现机器硬件资源过低，我新增加一台物理机按照[物理机部署](https://byconity.github.io/zh-cn/docs/deployment/package-deployment)步骤操作部署，然后重新启动后，我就看不到我之前创建的数据库表，我看库表磁盘占比也从之前的90%到现在15%，反请帮忙看一下这是什么原因呢？

![451727085312_ pic](https://github.com/user-attachments/assets/a584584c-b8db-42c3-a62e-ed8b2f0a4f43)
![461727085359_ pic](https://github.com/user-attachments/assets/c3dc5c1a-2fcf-4f08-8c63-8a32c9bdb1bb)
![471727087735_ pic](https://github.com/user-attachments/assets/db2ae0bb-f907-4aae-9a8d-d10c1a8ae045)

**Comment by smmsmm1988** [comment]
你好，没太明白是什么意思？你是往fdb增加一台物理机器吗，有重新部署吗？

**Comment by lee-liyl** [comment]
嗯，我按照物理机部署手册操作在新的服务器安装了一遍，并将fdb.cluster分发给了所有服务，全部重新启动了服务

**Comment by lee-liyl** [comment]
> 你好，没太明白是什么意思？你是往fdb增加一台物理机器吗，有重新部署吗？

我在新的服务器安装FoundationDB，并将fdb.cluster分发给了所有服务器，还安装了FoundationDB客户端、byconity-common-static、byconity-worker_0.4.0_amd64.deb，启动后，再查询却看不到我的数据库了

**Comment by smmsmm1988** [comment]
那我理解你是不是重新安装了一遍fdb呀？

**Comment by lee-liyl** [comment]
> 那我理解你是不是重新安装了一遍fdb呀？

嗯，那如何恢复数据？

**Comment by smmsmm1988** [comment]
> > 那我理解你是不是重新安装了一遍fdb呀？
> 
> 嗯，那如何恢复数据？

重新安装的话，数据应该就不存在了吧。。。。。

**Comment by lee-liyl** [comment]
> 重新安装的话，数据应该就不存在了吧。。。。。
这种也会删除掉我存在hdfs的数据？

**Comment by smmsmm1988** [comment]
不会删除hdfs的数据，但是库、表、part对应的元数据，都在fdb中，如果fdb中的数据清空了，那么肯定就查不到了。只有能查到元数据的前提下，才能去访问hdfs上的数据

**Comment by lee-liyl** [comment]
> 不会删除hdfs的数据，但是库、表、part对应的元数据，都在fdb中，如果fdb中的数据清空了，那么肯定就查不到了。只有能查到元数据的前提下，才能去访问hdfs上的数据

那没办法恢复了吗？只能重新建表，再打数据？

**Comment by smmsmm1988** [comment]
> > 不会删除hdfs的数据，但是库、表、part对应的元数据，都在fdb中，如果fdb中的数据清空了，那么肯定就查不到了。只有能查到元数据的前提下，才能去访问hdfs上的数据
> 
> 那没办法恢复了吗？只能重新建表，再打数据？

我理解是没办法恢复了，相当于重装系统了。。。

**Comment by smmsmm1988** [comment]
> > 我理解是没办法恢复了，相当于重装系统了。。。
> 
> 我再咨询一下，那我物理机进行节点扩容，我该如何正确操作？

你指的是fdb的扩容吗？我们使用fdb也是黑盒使用，如果是fdb的扩容的话，建议直接查询fdb的官方文档

**Comment by lee-liyl** [comment]
> 你指的是fdb的扩容吗？我们使用fdb也是黑盒使用，如果是fdb的扩容的话，建议直接查询fdb的官方文档

如果byconity增加读或写的工作节点，该如何操作？

**Comment by lee-liyl** [comment]
> 你指的是fdb的扩容吗？我们使用fdb也是黑盒使用，如果是fdb的扩容的话，建议直接查询fdb的官方文档

老师，不会删除hdfs的数据，为什么17日我查看磁盘占比是92%，20日我扩节点操作后，查看磁盘占比又只有15%了呢？

**Comment by smmsmm1988** [comment]
> > 你指的是fdb的扩容吗？我们使用fdb也是黑盒使用，如果是fdb的扩容的话，建议直接查询fdb的官方文档
> 
> 老师，不会删除hdfs的数据，为什么17日我查看磁盘占比是92%，20日我扩节点操作后，查看磁盘占比又只有15%了呢？

你说的是hdfs的磁盘吗？你不会所有的系统都重装了一遍吧。理论上你只操作fdb的话，不会对hdfs有什么影响的

**Comment by smmsmm1988** [comment]
> > 你指的是fdb的扩容吗？我们使用fdb也是黑盒使用，如果是fdb的扩容的话，建议直接查询fdb的官方文档
> 
> 如果byconity增加读或写的工作节点，该如何操作？

这个我们确认好后，回复你哈

**Comment by lee-liyl** [comment]
> 这个我们确认好后，回复你哈

好的，谢谢

**Comment by smmsmm1988** [comment]
> > 你指的是fdb的扩容吗？我们使用fdb也是黑盒使用，如果是fdb的扩容的话，建议直接查询fdb的官方文档
> 
> 如果byconity增加读或写的工作节点，该如何操作？

你想在哪个vw下增加节点（worker），就配置好worker，直接启动worker就好了

**Comment by smmsmm1988** [comment]
@lee-liyl 请问还有进一步的问题吗

**Comment by lee-liyl** [comment]
> @lee-liyl 请问还有进一步的问题吗

暂时没有了，谢谢
