### ISSUE TITLE
关于hdfs存储策略

### ISSUE THREAD

**Issue by fs273** [ByConity/ByConity#1874]
![11](https://github.com/user-attachments/assets/4c46f554-a3cf-4447-8b1f-4a7e32a5a794)
在对byconity进行测试，入库时报错The directory item limit of is exceeded， hdfs这个默认值为1048576，通过调整dfs.namenode.fs-limits.max-directory-items可设置最大为6400000。
因为在测试，会重复录入数据，最多的数据条目录入4000多次。
想问下hdfs存储策略，以便后续在设计表时要避免这种情况出现

**Comment by foreverneverer** [comment]
默认hdfs有无限容量，不作任何限制

**Comment by fs273** [comment]
需要研究hdfs单目录存储文件数大于6400000这个限制值？查了下一些公有云上hdfs也是有这个限制的
如果byconity持续写入到一个目录，肯定还是会超限

**Comment by foreverneverer** [comment]
包含子目录的文件数是吗？是不是merge、ttl、分区设置不合理？我们目前线上还没碰到过这个限制

**Comment by fs273** [comment]
> dfs.namenode.fs-limits.max-directory-items: 单个目录下不含递归的最大目录数或者文件数，默认值1048576，取值范围1～6400000
partition by toStartOfMonth(begin_time)
ttl toStartOfMonth(begin_time) + toIntervalMonth(12)
#1859 发现dm在merge parts时出问题，已经解决了，现在dm不再报错了
merge时会修改hdfs存储的目录么？ 如果是，是不是还是merge有一些问题，没有把一些零碎的文件合并到一起

**Comment by smmsmm1988** [comment]
merge不会修改目录，merge只会产生新的目录。然后旧的目录会在gc时被删除掉

**Comment by foreverneverer** [comment]
Merge策略可能有些问题，一些遗留的目录文件没有删掉可能；你可以查一下看看是否在part路径那一级，有没有包含空目录吗？如果是，就是gc没有清理

**Comment by foreverneverer** [comment]
可以先list一下hdfs的表级别目录查看一下count数；然后再从cnch_parts里查一下表的part数；看看二者是否对的上，如果diff很大就是有泄漏

**Comment by fs273** [comment]
> @fs273 你现在用的是哪个版本

1.0版本

**Comment by fs273** [comment]
> gc没有清理空目录的问题，已经fix，会在后续发布的新版本中带上

thx

**Comment by fs273** [comment]
在新版本发布之前，如果又出现了这个问题，有没有手动清理空目录的安全做法 @smmsmm1988

**Comment by smmsmm1988** [comment]
@fs273 这个就先close了，有问题再提新的issue

**Comment by smmsmm1988** [comment]
> 在新版本发布之前，如果又出现了这个问题，有没有手动清理空目录的安全做法 @smmsmm1988

可以扫描hdfs目录，发现目录如果是空的话，可以安全删除
