### ISSUE TITLE
物理机部署ByConity，创建表成功，insert报错

### ISSUE THREAD

**Issue by nanyang-12** [ByConity/ByConity#1876]
(you don't have to strictly follow this form)

## Question

物理机部署ByConity，已部署FoundationDB、HDFS，登录byconity，创建表成功，insert报错，报错详情如下：
不知道是哪里没配好？
Received exception from server (version 21.8.7):
Code: 1000. DB::Exception: Received from localhost:9010. DB::Exception: I/O error: Hdfs::HdfsRpcException: HdfsFailoverException: Failed to invoke RPC call "mkdirs" on server "20.20.20.125:12001"     Caused by: HdfsNetworkConnectException: Connect to "20.20.20.125:12001" failed: (errno: 111) Connection refused SQLSTATE: HY000.

![image](https://github.com/user-attachments/assets/8976072c-321c-486c-9c98-a1bf16fb2501)
SQL：
CREATE TABLE helloworld.my_first_table(user_id UInt32,message String,timestamp DateTime)ENGINE = CnchMergeTree() PARTITION BY timestamp ORDER BY (user_id, timestamp);
INSERT INTO helloworld.my_first_table (user_id, message, timestamp) VALUES (101, 'Hello, ByConity!',now())；

**Comment by nanyang-12** [comment]
什么权限？是这个步骤的吗？都按照官网配置了
![image](https://github.com/user-attachments/assets/9d0ea7dd-7fe9-4da8-96d6-a1802eaaae91)

**Comment by nanyang-12** [comment]
配置如下，看着没有问题吧
![9185735cc5cc862aadcd3dae89638eb](https://github.com/user-attachments/assets/dc660083-a1ff-45f5-b322-54c25a484d2f)
![a3c56a0bd710e44dc7951d1d8ed6f19](https://github.com/user-attachments/assets/b4df592a-b4a8-4cb3-bd6d-5e8c4bc001b3)
![bee8a619081a0960ee668cba0291e59](https://github.com/user-attachments/assets/7e5fa20d-1c5d-41fc-959f-6bc3b1561450)

**Comment by foreverneverer** [comment]
使用hdfs cli检查一下hdfs集群是否正常，看起来hdfs集群没有成功worker

**Comment by ixnzh** [comment]
原因是config中的端口和hdfs中配置的不一致，默认端口为12001。已经在文档中更改了表述。
