### ISSUE TITLE
kafka入库数据缺失，数据消费有问题

### ISSUE THREAD

**Issue by wangchucheng123** [ByConity/ByConity#1879]
在实时数据入库提交kafka的时候，上报的数据存在缺失（延时？？？）
我们用的是Python处理kafka数据入库的（数据来源多个服务器（3个），分为v2、v3版本的数据，数据来源数据量大，每分钟入库单个服务器数据量多的有几千条），用的queue管理线程处理数据

**Comment by ChanneRen** [comment]
是说能查到数据，但是数据不完整吗？用这个 sql 查一下消费日志呢：select event_type, count(), sum(metric) from cnch_system.cnch_kafka_log where event_date=today() and cnch_table = '{YOUR_KAFKA_TABLE_NAME}' group by event_type

**Comment by smmsmm1988** [comment]
@wangchucheng123 请问这个有尝试吗

**Comment by smmsmm1988** [comment]
@wangchucheng123 请问还有进一步的问题吗
