### ISSUE TITLE
Stuck on ssb-1 Q4.1

### ISSUE THREAD

**Issue by JiangXiNJU** [ByConity/ByConity#188]
Hi, when I execute ssb.sql on Byconity, It stucks and not return

![image](https://user-images.githubusercontent.com/22412775/227459664-92beb201-1f1f-4bfa-b77f-33778d259e84.png)

**Comment by JiangXiNJU** [comment]
the dataset is ssb with sf 1, the sqls befor Q4.1 are all successful

**Comment by JiangXiNJU** [comment]
byconity-tiger:latest server

cluster deployment:
- A 1 write_worker
- B tso & dm & 1 read_worker
- C 1 server & rm & cli
- FDBcluster : ABC
- hdfs : remote server

**Comment by hustnn** [comment]
hi @JiangXiNJU, did you enable optimizer by adding setting `enable_optimizer=1` ?

**Comment by hustnn** [comment]
I tested this query with the setting `enable_optimizer=1`, it is working for latest master. Remember to enable when running join.
35 rows in set. Elapsed: 0.620 sec.

**Comment by JiangXiNJU** [comment]
Oh, yes ! it works !
