### ISSUE TITLE
Installation keeps failing, it's too complicated

### ISSUE THREAD

**Issue by jianglujun** [ByConity/ByConity#1882]
(you don't have to strictly follow this form)

## describe your build problem
1.00 version，Installation keeps failing, it's too complicated
### Operating system
![1727700698514](https://github.com/user-attachments/assets/679ae91e-ad24-4b5e-a83d-e187408493ab)

**Comment by smmsmm1988** [comment]
Are you deploying ByConity on physical machines? It seems that all errors are related to not configured configuration-files. Please refer to https://byconity.github.io/docs/deployment/package-deployment for more information.

**Comment by jianglujun** [comment]
I used to deploy the open-source clickhouse, but it has been uninstalled. I haven't deployed ByConity before, I just followed the installation process of "physical machine deployment" on the official website, but there was an error when doing RPM installation. The previous HDFS and other content are all fine now.

**Comment by smmsmm1988** [comment]
> I used to deploy the open-source clickhouse, but it has been uninstalled. I haven't deployed ByConity before, I just followed the installation process of "physical machine deployment" on the official website, but there was an error when doing RPM installation. The previous HDFS and other content are all fine now.

![image](https://github.com/user-attachments/assets/ef38311f-16cd-4013-ab62-7ac207a3ea6b)

Maybe you should install the RPMs in this order.

**Comment by smmsmm1988** [comment]
@jianglujun Hi, have you completed the installation process?

**Comment by smmsmm1988** [comment]
@jianglujun hi, just check if you have further questions
