### ISSUE TITLE
部分列更新场景，目标表 key不是唯一的，更新过程报 目标表key出现重复的错误

### ISSUE THREAD

**Issue by liao626** [ByConity/ByConity#1891]
(you don't have to strictly follow this form)

## Question
如题，
<img width="1053" alt="微信图片_20241011120447" src="https://github.com/user-attachments/assets/14b09c38-c75b-4f92-bc17-842183dffe25">
目标表不是UNIQUE KEY表，现需对city_code的battle_region_name字段进行更新，目标表存在很多相同city_code的数据，执行部分列更新报错，如果将目标表city_code唯一，则更新部分列不报错，有参数控制，能确保在city_code不唯一的场景下也能更新其他部分列吗，要不然部分列的更新应用场景太局限了。

**Comment by smmsmm1988** [comment]
这个不支持，按列导入是按 join on {key} 来做匹配的，如果 {key} 不唯一，就没法判断同一个新 key 下的数据应该更新给哪一个原始 key 所在的行。如果能有多个 column 组合比如 col1, col2, col3，能确保唯一的话，也可以用这样的组合。总之就是按列导入的列必须要唯一
