### ISSUE TITLE
cnch类型的表支持把单表分散存储到多个对象存储中

### ISSUE THREAD

**Issue by ArthurZou** [ByConity/ByConity#1893]
部分s3提供商对单个桶有资源限制，比如带宽、qps、存储量等，当前把所有数据存储到一个桶的方式可能面临瓶颈。

**Comment by Alima777** [comment]
可以存储到多个桶，配置多 disk + 多 storage policy 就可以了。

**Comment by ArthurZou** [comment]
多个storage policy，每个storage policy一个disk 这种模式吗？因为我看现在storagepolicy的getAnyDisk 只会取第一个volume的第一块盘。

如果是这种方式的话，会有一些局限性
1、需要业务在上次来选定storage policy，不够灵活
2、分散的粒度是表级别的，一旦建表的时候选定了policy，数据就只会在一个桶了，可能会有热点问题

想要一种能力是一个storage policy支持多个disk。这样一个表的数据也能分散到多个disk

**Comment by Alima777** [comment]
通常情况下，对象存储桶的限制都是够用的。 针对数据量大或访问频繁的大表，可以将它单独放在一个桶里（单独指定 Storage policy），从而实现隔离。只针对大表单独设置 storage policy 的工作量也是可接受的。如果一个表放在一个单独的桶里仍然被限制，那可能需要考虑向对象存储的运营商提工单提高单桶的限制了。

我看了你的实现，只对 getAnyDisk() 进行改动，可能会有些问题。
1. 目前很多实现是基于单 storage policy 单 disk 做的，如果直接改动，可能会有稳定性问题。例如 Part Merge，detach/attach 操作，这些操作可能都需要做多盘的适配。
2. 如果 storage policy 包含多个 disk，那么所有表的数据都会放在多个桶里，对于小表会带来没必要的元数据开销。
3. 随机的数据分布可能不是个好策略，热点 Part 仍然可能在某单个桶里。

这个链路比较关键，需要考虑对所有现有功能的影响，避免可能导致的稳定性问题。

**Comment by smmsmm1988** [comment]
目前看修改这个链路风险不小，如果你有需求自己做定制化开发，强烈建议你加一个配置项来控制这个功能的打开与关闭，这样即便使用出问题，也可以通过配置给临时规避了。

**Comment by ArthurZou** [comment]
> 目前看修改这个链路风险不小，如果你有需求自己做定制化开发，强烈建议你加一个配置项来控制这个功能的打开与关闭，这样即便使用出问题，也可以通过配置给临时规避了。

👌

**Comment by ArthurZou** [comment]
> 通常情况下，对象存储桶的限制都是够用的。 针对数据量大或访问频繁的大表，可以将它单独放在一个桶里（单独指定 Storage policy），从而实现隔离。只针对大表单独设置 storage policy 的工作量也是可接受的。如果一个表放在一个单独的桶里仍然被限制，那可能需要考虑向对象存储的运营商提工单提高单桶的限制了。
> 
> 我看了你的实现，只对 getAnyDisk() 进行改动，可能会有些问题。
> 
> 1. 目前很多实现是基于单 storage policy 单 disk 做的，如果直接改动，可能会有稳定性问题。例如 Part Merge，detach/attach 操作，这些操作可能都需要做多盘的适配。
> 2. 如果 storage policy 包含多个 disk，那么其下所有表的数据都会放在多个桶里，对于小表会带来没必要的元数据开销。
> 3. 随机的数据分布可能不是个好策略，热点 Part 仍然可能在某单个桶里。
> 
> 这个链路比较关键，需要考虑对所有现有功能的影响，避免可能导致的稳定性问题。

我看现有的代码，似乎预留了类似的能力，单目前并没有完成实现。
https://github.com/ByConity/ByConity/blob/master/src/Protos/DataModelHelpers.cpp#293
![image](https://github.com/user-attachments/assets/cd19f2d7-768d-4685-a8b9-e131efdb2b7f)
https://github.com/ByConity/ByConity/blob/master/src/Disks/DiskHelpers.cpp
![image](https://github.com/user-attachments/assets/45d6cfb6-487b-4e92-9dba-3beb78a84414)
所以看看不是统一一下方案来做。

这个链路确实非常关键，一旦出错就会导致找不到part，且几乎无法恢复。
这个已经在我的测试环境中跑了一段时间了，目前没有发现问题，但我的测试环境场景比较单一，所以想请大家一起看看还有哪些问题，特别是对现有功能的影响。

**Comment by ArthurZou** [comment]
另外，我看有个CnchPartMoverThread 的后台任务，看起来是为冷热分离做准备的。这块是否也可以统一考虑下

**Comment by smmsmm1988** [comment]
> 另外，我看有个CnchPartMoverThread 的后台任务，看起来是为冷热分离做准备的。这块是否也可以统一考虑下

应该所有涉及到访问盘的，都需要统一考虑，少一个地方可能就会导致某些功能访问不到数据

**Comment by ArthurZou** [comment]
上面提到的多namenode 和 CnchPartMoverThread，你们计划怎么实现呢？

**Comment by ArthurZou** [comment]
如果这个pr现在不好合，看能够先把proto的协议定一下。不然我这边后面没法合入你们的更新了

**Comment by smmsmm1988** [comment]
CnchPartMoverThread目前应该暂时没有用到。另外，为啥会涉及到proto的协议

**Comment by ArthurZou** [comment]
> CnchPartMoverThread目前应该暂时没有用到。另外，为啥会涉及到proto的协议

Protos::DataModelPart 应该是需要记录自己被写到哪个盘了

**Comment by smmsmm1988** [comment]
> > CnchPartMoverThread目前应该暂时没有用到。另外，为啥会涉及到proto的协议
> 
> Protos::DataModelPart 应该是需要记录自己被写到哪个盘了，类似现有的data_path_id

我有点晕了，这块为啥会需要修改，一个part，应该固定对应一个盘呀，一个part不应该被拆开存多个盘上吧？

**Comment by ArthurZou** [comment]
> > > CnchPartMoverThread目前应该暂时没有用到。另外，为啥会涉及到proto的协议
> > 
> > 
> > Protos::DataModelPart 应该是需要记录自己被写到哪个盘了，类似现有的data_path_id
> 
> 我有点晕了，这块为啥会需要修改，一个part，应该固定对应一个盘呀，一个part不应该被拆开存多个盘上吧？

createPartFromModelCommon 从DataModelPart 构造出MergeTreeDataPartCNCH的时候，需要知道自己所数的盘，这样才能从s3正确的桶中读出数据。因为一个表不同的part被分散到到了不同的桶，需要一个地方记录这个映射关系

**Comment by smmsmm1988** [comment]
嗯，这块是没问题的呀，一个part对应一个盘，通过data_path_id来记录，不同的part就data_path_id不一样

**Comment by ArthurZou** [comment]
我的意思是这里需要统一一下协议。data_path_id是个uint类型的，用起来不方面。后续CnchPartMoverThread 的是否会继续使用这个字段还是说会重新创建一个新字段。我现在是新增了一个string 类型的disk_name字段。如果不统一，后续为了记录这个映射关系就会出现三个字段，不同场景用的还不一样。

**Comment by smmsmm1988** [comment]
> 我的意思是这里需要统一一下协议。data_path_id是个uint类型的，用起来不方面。而且看起来data_path_id是为hdfs设计的，不够通用，后续CnchPartMoverThread 的是否会继续使用这个字段还是说会重新创建一个新字段。我现在是新增了一个string 类型的disk_name字段。如果不统一，后续为了记录这个映射关系就会出现三个字段，不同场景用的还不一样。

CnchPartMoverThread短期应该不会用到的，不过为啥uint类型用起来不方便呢，你可以自己加一层data_path_id到自己bucket的映射呢？或者如果你想在proto里新增一个字段的话，也行，定义成optional的类型，然后代码里所有用到它的地方，都通过自己加的setting给控制住，这样才是安全的。不过我还是建议：
1、复用data_path_id，自己加映射，通过setting给控制住；
2、上层配置多 disk + 多 storage policy

**Comment by ArthurZou** [comment]
新增一个diskpolicy来支持这种模式应该更好一点

**Comment by smmsmm1988** [comment]
@ArthurZou 请问这块还有什么问题吗？你准备采用新的storage policy方案吗

**Comment by ArthurZou** [comment]
> @ArthurZou 请问这块还有什么问题吗？你准备采用新的storage policy方案吗

是的
