### ISSUE TITLE
MaterializedMySQL功能了解

### ISSUE THREAD

**Issue by xiongbl526** [ByConity/ByConity#1895]
(you don't have to strictly follow this form)

## Question
请问1.0版本的bc的MaterializedMySQL是否支持一个mmsql引擎消费多个库吗?

**Comment by smmsmm1988** [comment]
不支持的，一个 mmsql 对应一个 mysql 库

**Comment by xiongbl526** [comment]
后续会计划做一个mmsql同步多个库吗？



---- 回复的原邮件 ----
| 发件人 | Maomeng ***@***.***> |
| 日期 | 2024年10月14日 16:41 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] MaterializedMySQL功能了解 (Issue #1895) |

不支持的，一个 mmsql 对应一个 mysql 库
