### ISSUE TITLE
K8S安装byconity-hdfs-namenode-0出现Unable to write in /var/log/hadoop. Aborting.

### ISSUE THREAD

**Issue by iwangshuai888** [ByConity/ByConity#1898]
(you don't have to strictly follow this form)

## Question

K8S安装byconity-hdfs-namenode-0出现
Formatting HDFS NameNode volumes: /data0/dfs/name

 ERROR: Unable to write in /var/log/hadoop. Aborting.

 ERROR: Unable to write in /var/log/hadoop. Aborting.

**Comment by smmsmm1988** [comment]
/data0/dfs/name这个目录是不是已经安装过一次了，清空试试呢？

**Comment by smmsmm1988** [comment]
@iwangshuai888 请问问题解决了吗

**Comment by iwangshuai888** [comment]
@smmsmm1988 没有解决，不是因为这个吧，持久卷会自动重新创建的，我是K8S环境

**Comment by iwangshuai888** [comment]
有没有社区讨论啊，我想咨询问题

**Comment by iwangshuai888** [comment]
如果无法解决该问题，那么我们只能采用Clickhouse集群了

**Comment by smmsmm1988** [comment]
> 有没有社区讨论啊，我想咨询问题

有的，稍等会有同事和你联系

**Comment by smmsmm1988** [comment]
> @smmsmm1988 没有解决，不是因为这个吧，持久卷会自动重新创建的，我是K8S环境

![image](https://github.com/user-attachments/assets/1d5f7871-b9e0-4e9a-9eac-dae99c4361bf)
可以看下这个方案能不能解决问题

**Comment by iwangshuai888** [comment]
<img width="596" alt="1729085178525" src="https://github.com/user-attachments/assets/1b06b09e-b36e-43d3-ad9e-cce0acf76626">
我在我的yml文件里面增加了这个配置，但是还是不行，也更换了类似的命令，能不能加wx沟通一下ws1994

**Comment by smmsmm1988** [comment]
OK
