### ISSUE TITLE
checksumcache不断增长

### ISSUE THREAD

**Issue by xiongbl526** [ByConity/ByConity#1899]
(you don't have to strictly follow this form)

## Question
版本1.0.0
deploy/chart/byconity/files/worker.yaml文件中配置了
checksums_cache_size: 1073741824
但是查目前缓存大小已经超过限制
SELECT
    *,
    formatReadableSize(value) AS cacheSize
FROM cnch('vw_write', system.asynchronous_metrics)
WHERE metric LIKE '%Cache%'
ORDER BY value DESC
LIMIT 15

Query id: 580ef905-4692-4630-b913-abd1e53225df

┌─metric───────────────────────┬───────value─┬─cacheSize──┐
│ OSMemoryFreePlusCached       │ 10029096960 │ 9.34 GiB   │
│ OSMemoryCached               │  8490508288 │ 7.91 GiB   │
│ ChecksumsCacheBytes          │  1666035328 │ 1.55 GiB   │
│ OSMemoryFreeWithoutCached    │  1538588672 │ 1.43 GiB   │
│ MergeTreeDiskCacheBytes      │    51816615 │ 49.42 MiB  │
│ ChecksumsCacheFiles          │      353414 │ 345.13 KiB │

**Comment by xiongbl526** [comment]
所有wokrer都重启过

**Comment by ho1messi** [comment]
应该是配置有 typo，正确的配置是 checksum_cache_size，checksum 后面没有 's'
