### ISSUE TITLE
where is the "Best Practice of Bucket " ? 

### ISSUE THREAD

**Issue by JiangXiNJU** [ByConity/ByConity#190]
```
由于Bucket表的设置比较复杂，请参考后文中 Bucket 表最佳实践的细则来设置。一般情况下，两种场景适合设置：

表足够大，意味着在一个分区下的parts数量至少需要显著多于 worker 数量；
查询语句可以从上述收益点中获益；
```
Hi ,  when I read this paragraph in https://byconity.github.io/zh-cn/docs/%E5%9F%BA%E7%A1%80%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C/%E8%AE%BE%E8%AE%A1%E5%BA%93%E8%A1%A8#%E8%AE%BE%E8%AE%A1-bucket , I want to find the  " Bucket 表最佳实践的细则", but I can't. Can you help me to get the details ?

**Comment by Adora627** [comment]
> ```
> 由于Bucket表的设置比较复杂，请参考后文中 Bucket 表最佳实践的细则来设置。一般情况下，两种场景适合设置：
> 
> 表足够大，意味着在一个分区下的parts数量至少需要显著多于 worker 数量；
> 查询语句可以从上述收益点中获益；
> ```
> 
> Hi , when I read this paragraph in https://byconity.github.io/zh-cn/docs/%E5%9F%BA%E7%A1%80%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C/%E8%AE%BE%E8%AE%A1%E5%BA%93%E8%A1%A8#%E8%AE%BE%E8%AE%A1-bucket , I want to find the " Bucket 表最佳实践的细则", but I can't. Can you help me to get the details ?

There is a missing section about bucket table as mentioned above, its CN version as below, feel free to read it and contribute it to docs:https://github.com/ByConity/byconity.github.io/pull/81

**Comment by WillemJiang** [comment]
@JiangXiNJU  Here is the latest Chinese document https://byconity.github.io/docs/%E9%AB%98%E7%BA%A7%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C/Bucket%20Table%20%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5

**Comment by JiangXiNJU** [comment]
thank you !

**Comment by WillemJiang** [comment]
As we update the link of the documentation， the latest Chinese document link was changed to 
https://byconity.github.io/zh-cn/docs/advanced-guide/bucket-table-best-practice
