### ISSUE TITLE
能否降低访问 OSS 的网络带宽

### ISSUE THREAD

**Issue by lzf575** [ByConity/ByConity#1906]
有些用户是全公司共用一套 对象存储， 对每个部门使用的访问带宽有限制。
当ByConity写入数据时，1个 write worker 占用的读写双向流量都可达到 1Gbit/s，占用大量网络带宽。

是否有办法降低访问 OSS 的带宽？
例如 可以支持 数据在本地缓存先进行聚合合并后，才写入 OSS。已写入 OSS 的数据 不再读出，进行合并 等。
但是会导致本地还未写入OSS的数据，无法查询到， 所以在本地聚合数据的耗时需要尽量短，并且高效。

**Comment by smmsmm1988** [comment]
write worker有读流量，是因为写入后会做merge，merge操作会同时有读写流量。merge是必要的，如果不想merge做的太频繁，可以在写入的时候，攒个大批写入，可以减少merge来回读写的次数。

**Comment by lzf575** [comment]
@smmsmm1988 
例如 目前有 100K 行数据，每行100列，平均每列10 Byte， 总共100M 大小的数据一起写入。
 这些数据如果按列压缩，预期大小10M 即可。 
写入 OSS 时，是否可以在本地先做一次merge ，变为10M，再写入 OSS？

**Comment by smmsmm1988** [comment]
> @smmsmm1988 例如 目前有 100K 行数据，每行100列，平均每列10 Byte， 总共100M 大小的数据一起写入。 这些数据如果按列压缩，预期大小10M 即可。 写入 OSS 时，是否可以在本地先做一次merge ，变为10M，再写入 OSS？

100M大小的数据一起写入，写入的过程就会压缩呀

**Comment by lzf575** [comment]
> > @smmsmm1988 例如 目前有 100K 行数据，每行100列，平均每列10 Byte， 总共100M 大小的数据一起写入。 这些数据如果按列压缩，预期大小10M 即可。 写入 OSS 时，是否可以在本地先做一次merge ，变为10M，再写入 OSS？
> 
> 100M大小的数据一起写入，写入的过程就会压缩呀
ok， 也就是说， 写入OSS时， 会先对数据排序，压缩，再写入？
读取数据做 merge，也是读取的压缩后的，再解压，再merge，再压缩，写回？

**Comment by smmsmm1988** [comment]
> > > @smmsmm1988 例如 目前有 100K 行数据，每行100列，平均每列10 Byte， 总共100M 大小的数据一起写入。 这些数据如果按列压缩，预期大小10M 即可。 写入 OSS 时，是否可以在本地先做一次merge ，变为10M，再写入 OSS？
> > 
> > 
> > 100M大小的数据一起写入，写入的过程就会压缩呀
> 
> ok， 也就是说， 写入OSS时， 会先对数据排序，压缩，再写入？ 读取数据做 merge，也是读取的压缩后的，再解压，再merge，再压缩，写回？

是这样的，写到远端存储的数据，肯定是压缩后的，否则带宽和存储不都浪费了嘛

**Comment by lzf575** [comment]
> > > > @smmsmm1988 例如 目前有 100K 行数据，每行100列，平均每列10 Byte， 总共100M 大小的数据一起写入。 这些数据如果按列压缩，预期大小10M 即可。 写入 OSS 时，是否可以在本地先做一次merge ，变为10M，再写入 OSS？
> > > 
> > > 
> > > 100M大小的数据一起写入，写入的过程就会压缩呀
> > 
> > 
> > ok， 也就是说， 写入OSS时， 会先对数据排序，压缩，再写入？ 读取数据做 merge，也是读取的压缩后的，再解压，再merge，再压缩，写回？
> 
> 是这样的，写到远端存储的数据，肯定是压缩后的，否则带宽和存储不都浪费了嘛

我想也是，但是实际测试 占用 OSS的带宽还是很大，和发送数据的网络带宽差不多，可能大量的回读回写导致？

**Comment by smmsmm1988** [comment]
@lzf575 是的，merge操作会产生回读会写操作，merge次数多了，带宽占用比较明显

**Comment by smmsmm1988** [comment]
@lzf575 select toStartOfHour(event_time) as t, countIf(event_type = 1) as i, sumIf(num_source_parts , event_type = 2) as m from cnch(server, system.server_part_log) where event_date >= today() group by t order by t;
可以用这个sql来进一步确认下，i列代表写入的part数目，m列代表merge数目。event_date换成你想观测的日期

**Comment by smmsmm1988** [comment]
@lzf575 这个issue看看还有进一步的问题吗

**Comment by lzf575** [comment]
@smmsmm1988  感谢解答
