### ISSUE TITLE
s3的连接池在处理chunked包时，会复用一个不干净的连接

### ISSUE THREAD

**Issue by ArthurZou** [ByConity/ByConity#1909]
(you don't have to strictly follow this form)

### Briefly describe the bug
chunked包结尾会有一个0字节的块。数据形式是0CRLFCRLF。
当应用层需要从http 回包读N个字节，且chunked包的数据大小>= N时，就会在接收缓存中残留部分数据。通常chunked包的数据大小是刚好等于N，所以残留的数据就是最后一个0字节的块。
下一次复用这个连接发起一次新的请求，在解析http回包的时候就会抛出异常，引发请求重试。

### The result you expected
从连接池中拿到的一个session是“干净”的，前面的状态不会影响后续的读写操作

### How to Reproduce
1、开启s3连接池。例如 disk上配置 http_connection_pool_size = 100
2、关闭disk cache查询cnch 表。 关闭的目的是为了增加复现的概率
3、 查看worker的err 日志。
![image](https://github.com/user-attachments/assets/21dc812c-1d01-4be4-8a5f-fc616455a4e8)

**Comment by ArthurZou** [comment]
通过下面两种方式，都能避免这个现象
1、关闭连接池。
2、修改contrib/poco/Net/src/HTTPChunkedStream.cpp的HTTPChunkedStreamBuf::readFromDevice， 提前解析下一个chunk的数据包，避免残留数据在receive buffer里。 
![image](https://github.com/user-attachments/assets/3594b827-4dd0-426f-a779-304753f8dc77)

**Comment by Alima777** [comment]
这个问题应该已经修复了才对，对于残留数据的 session 是会被 reset 掉，不会放回连接池里的。

`ReadBufferFromS3::~ReadBufferFromS3()
{
    try
    {
        S3::resetSessionIfNeeded(readAllRangeSuccessfully(), read_result);
    }
    catch (...)
    {
        tryLogCurrentException(log);
    }
}`

**Comment by ArthurZou** [comment]
resetSessionIfNeeded 这个看起来是只处理了读数据失败的场景。
issue描述的是另一种场景。数据读成功了，只是最后的0CRLFCRLF残留在receive buffer中

**Comment by ArthurZou** [comment]
因为前面的块已经读到了业务想要的数据量，就不会读到最后的0块

**Comment by ArthurZou** [comment]
![image](https://github.com/user-attachments/assets/12b29fe9-b416-4ff7-a59f-18772abec56e)
如果上面是read(buffer, 22), 要读22个字节，只会读到前3个块。

**Comment by Alima777** [comment]
感觉有点奇怪，我们没有遇到过这个问题。

> 如果上层是read(buffer, 22), 要读22个字节，只会读到前3个块。

```
    size_t read(char * to, size_t n)
    {
        size_t bytes_copied = 0;

        while (bytes_copied < n && !eof())
        {
            size_t bytes_to_copy = std::min(static_cast<size_t>(working_buffer.end() - pos), n - bytes_copied);
            ::memcpy(to + bytes_copied, pos, bytes_to_copy);
            pos += bytes_to_copy;
            bytes_copied += bytes_to_copy;
        }

        return bytes_copied;
    }
 ```
 
 read 方法虽然传进去的字节数是 22，但是 working_buffer  并没有拿着这个字节数去读取，仍然是会读取一整批数据（1M或读到eof），然后再从 working_buffer 里拷贝出来 22 字节。
 
 虽然理论上仍然可能会有你说的这个问题，但是需要非常凑巧。

**Comment by Alima777** [comment]
```
    void resetSessionIfNeeded(bool read_all_range_successfully, std::optional<Aws::S3::Model::GetObjectResult> & read_result)
    {
        if (!read_result)
            return;

        if (auto session = getSession(*read_result); !session.isNull())
        {
            /// Only connection with fully consumed response can be reused,
            /// otherwise we'll encounter Malformed Message error on next request.
            if (read_all_range_successfully)
            {
                 **// 也许可以在这里处理下**
                 ProfileEvents::increment(ProfileEvents::S3PreservedSessions);
            }
            else
            {
                ProfileEvents::increment(ProfileEvents::S3ResetSessions);
                auto & http_session = static_cast<Poco::Net::HTTPClientSession &>(*session);
                http_session.reset();
            }
        }
    }

```

**Comment by ArthurZou** [comment]
> 感觉有点奇怪，我们没有遇到过这个问题。
> 
> > 如果上层是read(buffer, 22), 要读22个字节，只会读到前3个块。
> 
> ```
>     size_t read(char * to, size_t n)
>     {
>         size_t bytes_copied = 0;
> 
>         while (bytes_copied < n && !eof())
>         {
>             size_t bytes_to_copy = std::min(static_cast<size_t>(working_buffer.end() - pos), n - bytes_copied);
>             ::memcpy(to + bytes_copied, pos, bytes_to_copy);
>             pos += bytes_to_copy;
>             bytes_copied += bytes_to_copy;
>         }
> 
>         return bytes_copied;
>     }
> ```
> 
> read 方法虽然传进去的字节数是 22，但是 working_buffer 并没有拿着这个字节数去读取，仍然是会读取一整批数据（1M或读到eof），然后再从 working_buffer 里拷贝出来 22 字节，这种情况下 session 仍然是读完数据的。
> 
> 虽然理论上仍然可能会有你说的这个问题，但是需要非常凑巧。

嗯，也许刚好是请求1M

**Comment by ArthurZou** [comment]
> (you don't have to strictly follow this form)
> 
> ## Bug Report
> ### Briefly describe the bug
> chunked包结尾会有一个0字节的块。数据形式是0CRLFCRLF。 当应用层需要从http 回包读N个字节，且chunked包的数据大小>= N时，就会在接收缓存中残留部分数据。通常chunked包的数据大小是刚好等于N，所以残留的数据就是最后一个0字节的块。 下一次复用这个连接发起一次新的请求，在解析http回包的时候就会抛出异常，引发请求重试。
> 
> ### The result you expected
> 从连接池中拿到的一个session是“干净”的，前面的状态不会影响后续的读写操作
> 
> ### How to Reproduce
> 1、开启s3连接池。例如 disk上配置 http_connection_pool_size = 100 2、关闭disk cache查询cnch 表。 关闭的目的是为了增加复现的概率 3、 查看worker的err 日志。 ![image](https://private-user-images.githubusercontent.com/7134918/380602502-21dc812c-1d01-4be4-8a5f-fc616455a4e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMTc3OTksIm5iZiI6MTczMDExNzQ5OSwicGF0aCI6Ii83MTM0OTE4LzM4MDYwMjUwMi0yMWRjODEyYy0xZDAxLTRiZTQtOGE1Zi1mYzYxNjQ1NWE0ZTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjhUMTIxMTM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmI3ZTk0ZDg5YjExM2YyZmE3MTZjM2ZkNzY1MzQ4YmUwOTEyYjc4OTE3MjU0MmJhMjgyNjE1MGQzMjEzNDNmZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.SllKUGMi_4vdS_NQxyunxll183Nwki3hT_8SGAZUbEw)

从这个堆栈看，这个read是预取发起的，请求的刚好是1M

**Comment by smmsmm1988** [comment]
> ```
>     void resetSessionIfNeeded(bool read_all_range_successfully, std::optional<Aws::S3::Model::GetObjectResult> & read_result)
>     {
>         if (!read_result)
>             return;
> 
>         if (auto session = getSession(*read_result); !session.isNull())
>         {
>             /// Only connection with fully consumed response can be reused,
>             /// otherwise we'll encounter Malformed Message error on next request.
>             if (read_all_range_successfully)
>             {
>                  **// 也许可以在这里处理下**
>                  ProfileEvents::increment(ProfileEvents::S3PreservedSessions);
>             }
>             else
>             {
>                 ProfileEvents::increment(ProfileEvents::S3ResetSessions);
>                 auto & http_session = static_cast<Poco::Net::HTTPClientSession &>(*session);
>                 http_session.reset();
>             }
>         }
>     }
> ```

@ArthurZou 你可以试试在这里加些清空残留数据的处理逻辑，看看能不能解决问题

**Comment by ArthurZou** [comment]
> resetSessionIfNeeded

我看这个底层的socket是block的，这个地方没法判断receive buffer里面是否有数据。如果没数据，会一直阻塞？

**Comment by Alima777** [comment]
@ArthurZou 可以直接再读 1 byte 数据？走到这里应该保证数据是读取完的，预期再读 1 byte 应该就能保证跳过最后的 CRLF，实际返回的字节数为0。如果真的实际读出来1byte，就说明这个判断不对，可以直接报错。

**Comment by ArthurZou** [comment]
> @ArthurZou 可以直接再读 1 byte 数据？走到这里应该保证数据是读取完的，预期再读 1 byte 应该就能保证跳过最后的 CRLF，实际返回的字节数为0。如果真的实际读出来1byte，就说明这个判断不对，可以直接报错。

但如果是一个非chunked包的seession，receive buffer里面已经没有数据了，读1个byte也会阻塞的

**Comment by smmsmm1988** [comment]
> resetSessionIfNeeded

@ArthurZou @Alima777 resetSessionIfNeeded函数里直接强制搞一把reset是不是就可以了？

**Comment by Alima777** [comment]
> > resetSessionIfNeeded
> 
> @ArthurZou @Alima777 resetSessionIfNeeded函数里直接强制搞一把reset是不是就可以了？

这个当然不行。。。reset了之后 session 就没法复用了，相当于连接池没用了，对 S3 性能有影响。

**Comment by smmsmm1988** [comment]
@ArthurZou 有办法知道session是否是chunked包的吗

**Comment by smmsmm1988** [comment]
@ArthurZou 这个请问最近有什么进展吗

**Comment by ArthurZou** [comment]
> 通过下面两种方式，都能避免这个现象 1、关闭连接池。 2、修改contrib/poco/Net/src/HTTPChunkedStream.cpp的HTTPChunkedStreamBuf::readFromDevice， 提前解析下一个chunk的数据包，避免残留数据在receive buffer里。 ![image](https://private-user-images.githubusercontent.com/7134918/380603617-3594b827-4dd0-426f-a779-304753f8dc77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2ODgxMzMsIm5iZiI6MTczMDY4NzgzMywicGF0aCI6Ii83MTM0OTE4LzM4MDYwMzYxNy0zNTk0YjgyNy00ZGQwLTQyNmYtYTc3OS0zMDQ3NTNmOGRjNzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDRUMDIzNzEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmNmY2JjNGYyNjNkNTlmYzRiYzdmM2VjM2FhZmEzNGJlNWJjYWYxYTc0MGQ0YWU0MmEzOWEyMDBkZDliYmNmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.LHsWasUzfc79gpYvsHIla7Gz2ZTMfaG_rr5zL33UZxc)

我通过这个方式暂时规避了

**Comment by smmsmm1988** [comment]
> > 通过下面两种方式，都能避免这个现象 1、关闭连接池。 2、修改contrib/poco/Net/src/HTTPChunkedStream.cpp的HTTPChunkedStreamBuf::readFromDevice， 提前解析下一个chunk的数据包，避免残留数据在receive buffer里。 ![image](https://private-user-images.githubusercontent.com/7134918/380603617-3594b827-4dd0-426f-a779-304753f8dc77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2ODgxMzMsIm5iZiI6MTczMDY4NzgzMywicGF0aCI6Ii83MTM0OTE4LzM4MDYwMzYxNy0zNTk0YjgyNy00ZGQwLTQyNmYtYTc3OS0zMDQ3NTNmOGRjNzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDRUMDIzNzEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmNmY2JjNGYyNjNkNTlmYzRiYzdmM2VjM2FhZmEzNGJlNWJjYWYxYTc0MGQ0YWU0MmEzOWEyMDBkZDliYmNmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.LHsWasUzfc79gpYvsHIla7Gz2ZTMfaG_rr5zL33UZxc)
> 
> 我方式2暂时规避了

你用的方式2，对非chunk的数据包有影响吗

**Comment by ArthurZou** [comment]
方式2那里只会处理chunk 包，其他包不会走这个逻辑
