### ISSUE TITLE
ETL模式并行度超过实际worker数量数据量翻倍

### ISSUE THREAD

**Issue by xiongbl526** [ByConity/ByConity#1912]
(you don't have to strictly follow this form)

## Question
1.0.0版本  
读写各部署两个Pod，两个server
sql
`INSERT INTO n.lite_tmp (country_code, clientOS, clientVersion, project, request_time, request_url, service_id, source, status, min, time) SELECT
    u.country_code,
    clientOS,
    clientVersion,
    project,
    request_time,
    request_url,
    service_id,
    source,
    status,
    min,
    time
FROM
(
    SELECT
        userId,
        clientOS,
        clientVersion,
        project,
        request_time,
        request_url,
        service_id,
        source,
        status,
        min,
        time
    FROM n.n_log AS nl
    WHERE toYYYYMMDD(nl.time) = '20241028' 
left JOIN n.user_info_final AS u ON ng.userId = u.user_id settings bsp_mode=1,distributed_max_parallel_size=4`

跑出来的数据相比distributed_max_parallel_size=2多了差不多一倍

**Comment by smmsmm1988** [comment]
@xiongbl526 帮忙提供下如下信息，我们排查下是哪里的问题：
1、刚才执行的distributed_max_parallel_size = 4 和distributed_max_parallel_size = 2的sql分别对应的query_id；
2、期间server、worker、resource manager对应的日志文件
感谢🙏

**Comment by xiongbl526** [comment]
这个实例就是今天kafka消费问题那个实例，现在已经版本回退了，我再其它实例上跑一下



---- 回复的原邮件 ----
| 发件人 | Maomeng ***@***.***> |
| 日期 | 2024年10月29日 15:24 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] ETL模式并行度超过实际worker数量数据量翻倍 (Issue #1912) |

@xiongbl526 帮忙提供下如下信息，我们排查下是哪里的问题：
1、刚才执行的distributed_max_parallel_size = 4 和distributed_max_parallel_size = 2的sql分别对应的query_id；
2、期间server、worker、resource manager对应的日志文件
感谢🙏

**Comment by smmsmm1988** [comment]
> 这个实例就是今天kafka消费问题那个实例，现在已经版本回退了，我再其它实例上跑一下
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | Maomeng ***@***.***> | | 日期 | 2024年10月29日 15:24 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [ByConity/ByConity] ETL模式并行度超过实际worker数量数据量翻倍 (Issue #1912) | @xiongbl526 帮忙提供下如下信息，我们排查下是哪里的问题： 1、刚才执行的distributed_max_parallel_size = 4 和distributed_max_parallel_size = 2的sql分别对应的query_id； 2、期间server、worker、resource manager对应的日志文件 感谢🙏 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

收到，感谢配合🙏

**Comment by xiongbl526** [comment]
> > 这个实例就是今天kafka消费问题那个实例，现在已经版本回退了，我再其它实例上跑一下
> > […](#)
> > ---- 回复的原邮件 ---- | 发件人 | Maomeng _**@**_._**> | | 日期 | 2024年10月29日 15:24 | | 收件人 | _**@**_.**_> | | 抄送至 | _**@**_._**>**_@_**.**_> | | 主题 | Re: [ByConity/ByConity] ETL模式并行度超过实际worker数量数据量翻倍 (Issue #1912) | @xiongbl526 帮忙提供下如下信息，我们排查下是哪里的问题： 1、刚才执行的distributed_max_parallel_size = 4 和distributed_max_parallel_size = 2的sql分别对应的query_id； 2、期间server、worker、resource manager对应的日志文件 感谢🙏 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: _**@**_.***>
> 
> 收到，感谢配合🙏

并行度为4的query_id是51fcc148-9bde-4a16-806e-539cb16091e1
并行度为2的query_id是003df421-00f1-4806-b01a-ca72a0f51561
插入表是nginx.nginx_log_lite_tmp 并行度为2执行时间是零时区8点46分到47分  并行度为4的执行时间是零时区8点49分 下面是所有日志
[bingxing.tar.gz](https://github.com/user-attachments/files/17556454/bingxing.tar.gz)

**Comment by xiongbl526** [comment]
> > > 这个实例就是今天kafka消费问题那个实例，现在已经版本回退了，我再其它实例上跑一下
> > > […](#)
> > > ---- 回复的原邮件 ---- | 发件人 | Maomeng _**@**_._**> | | 日期 | 2024年10月29日 15:24 | | 收件人 | _**@**_.**_> | | 抄送至 | _**@**_._**>**_@_**.**_> | | 主题 | Re: [ByConity/ByConity] ETL模式并行度超过实际worker数量数据量翻倍 (Issue #1912) | @xiongbl526 帮忙提供下如下信息，我们排查下是哪里的问题： 1、刚才执行的distributed_max_parallel_size = 4 和distributed_max_parallel_size = 2的sql分别对应的query_id； 2、期间server、worker、resource manager对应的日志文件 感谢🙏 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: _**@**_.***>
> > 
> > 
> > 收到，感谢配合🙏
> 
> 并行度为4的query_id是51fcc148-9bde-4a16-806e-539cb16091e1 并行度为2的query_id是003df421-00f1-4806-b01a-ca72a0f51561 插入表是nginx.nginx_log_lite_tmp 并行度为2执行时间是零时区8点46分到47分 并行度为4的执行时间是零时区8点49分 下面是所有日志 [bingxing.tar.gz](https://github.com/user-attachments/files/17556454/bingxing.tar.gz)

这次测试的数据量小，跑出来的数据量是真实数据的1.5倍

**Comment by WangTaoTheTonic** [comment]
n.n_log 和 n.user_info_final的建表语句发一下咧？是bucket表吗

**Comment by xiongbl526** [comment]
> n.n_log 和 n.user_info_final的建表语句发一下咧？是bucket表吗

都是cnch表
`CREATE TABLE n.user_info_final
(
    `user_id` String,
    `province_code` String DEFAULT ''
)
ENGINE = CnchMergeTree
ORDER BY (user_id, province_code)
SETTINGS index_granularity = 8192, cnch_vw_default = 'vw_default', cnch_vw_write = 'vw_write'`

` CREATE TABLE n.log
(
    `appid` String,
    `clientIP` String,
    `remote_addr` String,
    `clientOS` String,
    `clientOV` String,
    `clientProtocolVersion` String,
    `clientType` String,
    `clientVersion` String,
    `language` String,
    `project` String,
    `request_time` String,
    `request_url` String,
    `role` String,
    `service_id` String,
    `source` String,
    `status` String,
    `terminalBrand` String,
    `terminalId` String,
    `terminalModel` String,
    `terminalName` String,
    `time_local` String,
    `timezoneOffset` String,
    `topic` String,
    `ttid` String,
    `upstream_addr` String,
    `upstream_response_time` String,
    `userId` String,
    `x_pcs_request_idmin` String,
    `time` DateTime,
    `min` String DEFAULT formatDateTime(time, '%Y-%m-%d %H:%M'),
    `x_pcs_business_code` String
)
ENGINE = CnchMergeTree
PARTITION BY toYYYYMMDD(time)
ORDER BY (userId, appid, topic, source, request_time, status, min)
SETTINGS index_granularity = 8192, cnch_vw_default = 'vw_default', cnch_vw_write = 'vw_write'`

**Comment by xiongbl526** [comment]
请问这个有啥进展吗？

**Comment by smmsmm1988** [comment]
> 请问这个有啥进展吗？

稍等我们根据日志排查一下

**Comment by WangTaoTheTonic** [comment]
> 51fcc148-9bde-4a16-806e-539cb16091e1

Trace级别的日志有吗？辛苦跑一下？

**Comment by smmsmm1988** [comment]
@xiongbl526 哈喽，这个问题我们看了下，大概率是个已知bug，1.0.1版本已经修复，可以用新版本试一下。1.0.0版本的话，可以把distributed_max_parallel_size的数值设置为不大于worker数目来临时规避

**Comment by xiongbl526** [comment]
好的，我试下



---- 回复的原邮件 ----
| 发件人 | Maomeng ***@***.***> |
| 日期 | 2024年11月04日 16:45 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] ETL模式并行度超过实际worker数量数据量翻倍 (Issue #1912) |

@xiongbl526 哈喽，这个问题我们看了下，大概率是个已知bug，1.0.1版本已经修复，可以用新版本试一下。1.0.0版本的话，可以把distributed_max_parallel_size的数值设置为不大于worker数目来临时规避

**Comment by xiongbl526** [comment]
> @xiongbl526 哈喽，这个问题我们看了下，大概率是个已知bug，1.0.1版本已经修复，可以用新版本试一下。1.0.0版本的话，可以把distributed_max_parallel_size的数值设置为不大于worker数目来临时规避

1.0.1版本没问题了
