### ISSUE TITLE
CnchMergeTree 表引擎，官方文档说:核心思想和 LSM-Tree 类似,想咨询ByConity写入实现了memtable吗

### ISSUE THREAD

**Issue by liao626** [ByConity/ByConity#1915]
(you don't have to strictly follow this form)

## Question
如题，有没有实现memtable，数据不经过缓冲而直接写到磁盘吗？

**Comment by smmsmm1988** [comment]
@liao626 目前没有memtable的实现，一次写入的数据，压缩后会直接写到底层存储上

**Comment by liao626** [comment]
> @liao626 目前没有memtable的实现，一次写入的数据，压缩后会直接写到底层存储上

好的，多谢解答
