### ISSUE TITLE
物理机部署，`byconity-server`、`byconity-worker` 和 `byconity-worker-write‘必须要分成三台机器安装吗

### ISSUE THREAD

**Issue by jianglujun** [ByConity/ByConity#1917]
(you don't have to strictly follow this form)
单台物理机器部署，`byconity-server`、`byconity-worker` 和 `byconity-worker-write‘不能同时启动
## Question
但是单台机器配置比较高，分开三台部署比较浪费，除了k8s的方式以外，还有别的方式吗？

**Comment by jianglujun** [comment]
1.0.0版本

**Comment by ixnzh** [comment]
> (you don't have to strictly follow this form) 单台物理机器部署，`byconity-server`、`byconity-worker` 和 `byconity-worker-write‘不能同时启动
> 
> ## Question
> 但是单台机器配置比较高，分开三台部署比较浪费，除了k8s的方式以外，还有别的方式吗？

首先还是建议用k8s来部署，这样能够比较灵活的管理，部署起来也更方便。

如果不方便用k8s，单台资源也足够大，也可以尝试都部署在同一节点。但是如果生产端使用很可能会互相抢占资源导致一些查询失败，merge任务堆积严重还可能导致导入不了数据。另外如果部署在同一节点，端口方面需要做一定的梳理。

**Comment by jianglujun** [comment]
单台如何部署到一起？现在是报错

**Comment by jianglujun** [comment]
单台如何部署到一块？现在报错。byconity-server、byconity-worker 和 `byconity-worker-write‘，现在只有byconity-server可以启动，另外两个报错，如果改哪些内容？
![1730275104827](https://github.com/user-attachments/assets/c2a27680-f230-432b-9d55-b3947edfa9ff)
![1730275159787](https://github.com/user-attachments/assets/65fbafc6-6325-4df7-bba6-a1bc786c41d3)

**Comment by ixnzh** [comment]
可以发一下cnch_config.xml和worker.xml这两个文件关于地址那一块的具体配置吗

**Comment by jianglujun** [comment]
cnch_config.xml
[cnch_config.pdf](https://github.com/user-attachments/files/17570060/cnch_config.pdf)
byconity-worker-writer.xml
[byconity-worker-write.pdf](https://github.com/user-attachments/files/17570103/byconity-worker-write.pdf)
byconity-worker.xml
[byconity-worker.pdf](https://github.com/user-attachments/files/17570138/byconity-worker.pdf)

byconity-server.xml
[byconity-server.pdf](https://github.com/user-attachments/files/17570143/byconity-server.pdf)

**Comment by ixnzh** [comment]
> [byconity-worker.pdf](https://github.com/user-attachments/files/17570138/byconity-worker.pdf)

HDFS的地址没配吗，<hdfs_nnproxy>hdfs://localhost:12001</hdfs_nnproxy>这里localhost要改成hdfs的地址

worker里面要不把<listen_host>::</listen_host>改成本地地址试一下呢

**Comment by ixnzh** [comment]
而且你的报错信息里面看，你好像起了多个实例。worker的二进制文件也有问题，环境文件如果没问题把worker的安装文件重新下载下呢

**Comment by ixnzh** [comment]
> cnch_config.xml [cnch_config.pdf](https://github.com/user-attachments/files/17570060/cnch_config.pdf) byconity-worker-writer.xml [byconity-worker-write.pdf](https://github.com/user-attachments/files/17570103/byconity-worker-write.pdf) byconity-worker.xml [byconity-worker.pdf](https://github.com/user-attachments/files/17570138/byconity-worker.pdf)
> 
> byconity-server.xml [byconity-server.pdf](https://github.com/user-attachments/files/17570143/byconity-server.pdf)

要是还是不行，你在交流群里面直接加我吧
