### ISSUE TITLE
sql报错 tooLargeArray

### ISSUE THREAD

**Issue by xiongbl526** [ByConity/ByConity#1918]
(you don't have to strictly follow this form)

## Question
版本0.4.2 
执行select bitmapCardinality(bitmapBuild(groupArray(toInt64(user_id)))) from user_info.dwd_user_info 这个sql报错 tooLargeArray
user_info.dwd_user_info这个表大概2800w数据  重试多次后能成功

**Comment by smmsmm1988** [comment]
@xiongbl526 user_info.dwd_user_info的schema发一下？

**Comment by smmsmm1988** [comment]
> @xiongbl526 user_info.dwd_user_info的schema发一下？

@xiongbl526 还有报异常的详细堆栈

**Comment by xiongbl526** [comment]
> > @xiongbl526 user_info.dwd_user_info的schema发一下？
> 
> @xiongbl526 还有报异常的详细堆栈
`CREATE TABLE user_info.dwd_user_info
(
    `user_id` Int64 ,
    `project` String ,
    `app_id` String ,
    `user_register_client_type` String ,
    `user_register_client_ov` String ,
    `user_label` String ,
    `user_register_time` DateTime ,
    `user_register_date` Date ,
    `user_register_ip` String ,
    `user_multi_terminal_switch` String ,
    `user_region` String ,
    `user_role` String ,
    `iscn` String ,
    `country_code` String ,
    `province_code` String,
    `city_code` String,
    `county_code` String ,
    `township_code` String ,
    `add_time` DateTime
)
ENGINE = CnchMergeTree
ORDER BY (user_register_date, project, app_id, user_id)
SETTINGS storage_policy = 'cnch_default_oss', index_granularity = 8192, cnch_vw_default = 'vw_default', cnch_vw_write = 'vw_write'`
报错
 <Error> SegmentScheduler: query(74bf7c3d-b208-48fa-9a08-487d5dcc18e6) receive error from host:172.18.40.46 with exception:Code: 128, e.displayText() = DB::Exception: Too large array size SQLSTATE: 54000 (version 21.8.7.1) and plan_send_addresses size:2
2024.11.01 15:40:35.656475 [ 220 ] {74bf7c3d-b208-48fa-9a08-487d5dcc18e6} (453626255146221583) <Error> executeQuery: Code: 128, e.displayText() = DB::Exception: Too large array size SQLSTATE: 54000 (version 21.8.7.1) (from 127.0.0.1:54436) (in query: select bitmapCardinality(bitmapBuild(groupArray(toInt64(user_id)))) from user_info.dwd_user_info), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x2723c3d2 in /opt/byconity/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x1078cbc0 in /opt/byconity/bin/clickhouse
2. DB::GroupArrayNumericImpl<long, DB::GroupArrayTrait<false, false, (DB::Sampler)0> >::deserialize(char*, DB::ReadBuffer&, DB::Arena*) const @ 0x13502d55 in /opt/byconity/bin/clickhouse
3. DB::SerializationAggregateFunction::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const @ 0x208b9e78 in /opt/byconity/bin/clickhouse
4. DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >*) const @ 0x208b54fc in /opt/byconity/bin/clickhouse
5. DB::NativeChunkInputStream::readData(DB::IDataType const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, DB::ReadBuffer&, unsigned long, double) @ 0x2251eddf in /opt/byconity/bin/clickhouse
6. DB::NativeChunkInputStream::readImpl() @ 0x2251f87e in /opt/byconity/bin/clickhouse
7. DB::DeserializeBufTransform::transform(DB::Chunk&) @ 0x2279f1f6 in /opt/byconity/bin/clickhouse
8. DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) @ 0x22477eb3 in /opt/byconity/bin/clickhouse
9. DB::ISimpleTransform::work() @ 0x2247aea2 in /opt/byconity/bin/clickhouse
10. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0, void ()> >(std::__1::__function::__policy_storage const*) @ 0x22331541 in /opt/byconity/bin/clickhouse
11. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0x2232f717 in /opt/byconity/bin/clickhouse
12. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long)::$_5>(DB::PipelineExecutor::executeImpl(unsigned long)::$_5&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x22331ac5 in /opt/byconity/bin/clickhouse
13. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x107c9100 in /opt/byconity/bin/clickhouse
14. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0x107cd57a in /opt/byconity/bin/clickhouse
15. start_thread @ 0x7ea7 in /lib/x86_64-linux-gnu/libpthread-2.31.so
16. clone @ 0xfca2f in /lib/x86_64-linux-gnu/libc-2.31.so

2024.11.01 15:40:35.656571 [ 220 ] {74bf7c3d-b208-48fa-9a08-487d5dcc18e6} (453626255146221583) <Error> TCPHandler: Code: 128, e.displayText() = DB::Exception: Too large array size SQLSTATE: 54000, Stack trace:

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x2723c3d2 in /opt/byconity/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x1078cbc0 in /opt/byconity/bin/clickhouse
2. DB::GroupArrayNumericImpl<long, DB::GroupArrayTrait<false, false, (DB::Sampler)0> >::deserialize(char*, DB::ReadBuffer&, DB::Arena*) const @ 0x13502d55 in /opt/byconity/bin/clickhouse
3. DB::SerializationAggregateFunction::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const @ 0x208b9e78 in /opt/byconity/bin/clickhouse
4. DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >*) const @ 0x208b54fc in /opt/byconity/bin/clickhouse
5. DB::NativeChunkInputStream::readData(DB::IDataType const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, DB::ReadBuffer&, unsigned long, double) @ 0x2251eddf in /opt/byconity/bin/clickhouse
6. DB::NativeChunkInputStream::readImpl() @ 0x2251f87e in /opt/byconity/bin/clickhouse
7. DB::DeserializeBufTransform::transform(DB::Chunk&) @ 0x2279f1f6 in /opt/byconity/bin/clickhouse
8. DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) @ 0x22477eb3 in /opt/byconity/bin/clickhouse
9. DB::ISimpleTransform::work() @ 0x2247aea2 in /opt/byconity/bin/clickhouse
10. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0, void ()> >(std::__1::__function::__policy_storage const*) @ 0x22331541 in /opt/byconity/bin/clickhouse
11. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0x2232f717 in /opt/byconity/bin/clickhouse
12. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long)::$_5>(DB::PipelineExecutor::executeImpl(unsigned long)::$_5&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x22331ac5 in /opt/byconity/bin/clickhouse
13. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x107c9100 in /opt/byconity/bin/clickhouse
14. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0x107cd57a in /opt/byconity/bin/clickhouse
15. start_thread @ 0x7ea7 in /lib/x86_64-linux-gnu/libpthread-2.31.so
16. clone @ 0xfca2f in /lib/x86_64-linux-gnu/libc-2.31.so

**Comment by ixnzh** [comment]
@xiongbl526 目前在v 1.0.0环境中没有复现成功，我们下周在0.4.2环境中尝试复现一下

**Comment by xiongbl526** [comment]
我在1.0.1上试也没问题



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年11月01日 17:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] sql报错 tooLargeArray (Issue #1918) |

@xiongbl526 目前在v 1.0.0环境中没有复现成功，我们下周在0.4.2环境中尝试复现一下

**Comment by smmsmm1988** [comment]
@xiongbl526 @ixnzh 高版本没有问题的话，是不是也就不用在低版本中再花时间复现了？最终肯定是要升级到新版本的

**Comment by xiongbl526** [comment]
好的，我们这边先试运行一段时间新版本再升业务实例



---- 回复的原邮件 ----
| 发件人 | Maomeng ***@***.***> |
| 日期 | 2024年11月01日 18:04 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] sql报错 tooLargeArray (Issue #1918) |

@***@***.*** 高版本没有问题的话，是不是也就不用在低版本中再花时间复现了？最终肯定是要升级到新版本的
