### ISSUE TITLE
server内存一直缓慢增长

### ISSUE THREAD

**Issue by xiongbl526** [ByConity/ByConity#1919]
(you don't have to strictly follow this form)

## Question
版本0.4.2
部署了两个server pod 内存limit给到7G 但是今天有个server pod在使用到4.7G时 探活失败触发重启了 看监控图近七天内存一直在增长

**Comment by smmsmm1988** [comment]
@xiongbl526 继续执行下之前给的内存使用统计语句看看呢

**Comment by xiongbl526** [comment]
> @xiongbl526 继续执行下之前给的内存使用统计语句看看呢

SELECT
    *,
    formatReadableSize(value) AS cacheSize
FROM cnch('server', system.asynchronous_metrics)
WHERE metric LIKE '%Cache%'
ORDER BY value DESC
LIMIT 15

Query id: cb6afa9e-3c7e-4c86-8bdb-47dccb892736

┌─metric────────────────────────┬──────value─┬─cacheSize──┐
│ OSMemoryFreePlusCached        │ 7673643008 │ 7.15 GiB   │
│ OSMemoryFreePlusCached        │ 7425941504 │ 6.92 GiB   │
│ OSMemoryCached                │ 6907875328 │ 6.43 GiB   │
│ OSMemoryCached                │ 6703292416 │ 6.24 GiB   │
│ OSMemoryFreeWithoutCached     │  970350592 │ 925.40 MiB │
│ OSMemoryFreeWithoutCached     │  518066176 │ 494.07 MiB │
│ CnchPartCacheParts            │     487560 │ 476.13 KiB │
│ UniqueKeyIndexMetaCacheBytes  │     380513 │ 371.59 KiB │
│ UniqueKeyIndexBlockCacheBytes │     230645 │ 225.24 KiB │
│ CnchPartCacheParts            │     177010 │ 172.86 KiB │
│ CompiledExpressionCacheBytes  │      57344 │ 56.00 KiB  │
│ CnchPartCachePartitions       │      17181 │ 16.78 KiB  │
│ CompiledExpressionCacheBytes  │      16384 │ 16.00 KiB  │
│ CnchPartCachePartitions       │      15682 │ 15.31 KiB  │
│ DeleteBitmapCacheBytes        │       7066 │ 6.90 KiB   │
└───────────────────────────────┴────────────┴───────────

**Comment by smmsmm1988** [comment]
@xiongbl526 看uncompressed cache和checksum cache，是不是也都没有配置呀

**Comment by xiongbl526** [comment]
在server.yaml和worker.yaml文件里配置了的



---- 回复的原邮件 ----
| 发件人 | Maomeng ***@***.***> |
| 日期 | 2024年11月01日 11:06 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] server内存一直缓慢增长 (Issue #1919) |

@xiongbl526 看uncompressed cache和checksum cache，是不是也都没有配置呀

**Comment by xiongbl526** [comment]
> @xiongbl526 看uncompressed cache和checksum cache，是不是也都没有配置呀
查worker能提现出来这两个缓存配置使用值 server里好像就是查不到具体使用了多少 是不是我加的位置不对
SELECT　    *,　    formatReadableSize(value) AS cacheSize　FROM cnch('vw_default', system.asynchronous_metrics)　WHERE metric LIKE '%Cache%'　ORDER BY value DESC　LIMIT 20

SELECT
    *,
    formatReadableSize(value) AS cacheSize
FROM cnch('vw_default', system.asynchronous_metrics)
WHERE metric LIKE '%Cache%'
ORDER BY value DESC
LIMIT 20

Query id: 42736c1c-f3f8-4f04-b565-8f41423dc82c

┌─metric────────────────────────┬────────value─┬─cacheSize───┐
│ MergeTreeDiskCacheBytes       │ 118621792671 │ 110.48 GiB  │
│ MergeTreeDiskCacheBytes       │ 118558940317 │ 110.42 GiB  │
│ MergeTreeDiskCacheBytes       │ 118392281229 │ 110.26 GiB  │
│ OSMemoryFreePlusCached        │  23313510400 │ 21.71 GiB   │
│ OSMemoryFreePlusCached        │  21705342976 │ 20.21 GiB   │
│ OSMemoryCached                │  21635059712 │ 20.15 GiB   │
│ OSMemoryFreePlusCached        │  21358997504 │ 19.89 GiB   │
│ OSMemoryCached                │  20281786368 │ 18.89 GiB   │
│ OSMemoryCached                │  19551653888 │ 18.21 GiB   │
│ OSMemoryFreeWithoutCached     │   1807343616 │ 1.68 GiB    │
│ OSMemoryFreeWithoutCached     │   1678450688 │ 1.56 GiB    │
│ OSMemoryFreeWithoutCached     │   1423556608 │ 1.33 GiB    │
│ UncompressedCacheBytes        │   1073732284 │ 1023.99 MiB │
│ UncompressedCacheBytes        │   1073732091 │ 1023.99 MiB │
│ UncompressedCacheBytes        │   1073705436 │ 1023.97 MiB │
│ UniqueKeyIndexBlockCacheBytes │   1073705237 │ 1023.97 MiB │
│ DeleteBitmapCacheBytes        │    913082762 │ 870.78 MiB  │
│ DeleteBitmapCacheBytes        │    907479770 │ 865.44 MiB  │
│ DeleteBitmapCacheBytes        │    845847080 │ 806.66 MiB  │
│ PrimaryIndexCacheBytes        │    458910848 │ 437.65 MiB  │
└───────────────────────────────┴──────────────┴─────────────┘

20 rows in set. Elapsed: 0.021 sec. 

10.42.108.32 :) SELECT
:-]     *,
:-]     formatReadableSize(value) AS cacheSize
:-] FROM cnch('vw_write', system.asynchronous_metrics)
:-] WHERE metric LIKE '%Cache%'
:-] ORDER BY value DESC
:-] LIMIT 15

SELECT
    *,
    formatReadableSize(value) AS cacheSize
FROM cnch('vw_write', system.asynchronous_metrics)
WHERE metric LIKE '%Cache%'
ORDER BY value DESC
LIMIT 15

Query id: bc97068f-2251-45dc-a906-597dcbbd0c58

┌─metric────────────────────┬───────value─┬─cacheSize───┐
│ OSMemoryFreePlusCached    │ 21140606976 │ 19.69 GiB   │
│ OSMemoryFreePlusCached    │ 21006340096 │ 19.56 GiB   │
│ OSMemoryCached            │ 20460093440 │ 19.05 GiB   │
│ OSMemoryCached            │ 19557150720 │ 18.21 GiB   │
│ OSMemoryFreeWithoutCached │  1583456256 │ 1.47 GiB    │
│ ChecksumsCacheBytes       │  1073712640 │ 1023.97 MiB │
│ ChecksumsCacheBytes       │  1073706240 │ 1023.97 MiB │
│ OSMemoryFreeWithoutCached │   546246656 │ 520.94 MiB  │
│ UncompressedCacheBytes    │   113519284 │ 108.26 MiB  │
│ UncompressedCacheBytes    │   107769676 │ 102.78 MiB  │
│ MarkCacheBytes            │    43266880 │ 41.26 MiB   │
│ MarkCacheBytes            │    37521680 │ 35.78 MiB   │
│ MergeTreeDiskCacheBytes   │    27060843 │ 25.81 MiB   │
│ MergeTreeDiskCacheBytes   │    26384228 │ 25.16 MiB   │
│ PrimaryIndexCacheBytes    │    26265824 │ 25.05 MiB   │
└───────────────────────────┴─────────────┴─────────────┘

**Comment by smmsmm1988** [comment]
@xiongbl526 通过cnch() udf可能不好区分，你可以直接连上4.7G的server pod查看一下

**Comment by xiongbl526** [comment]
没太懂，麻烦细说下怎么查



---- 回复的原邮件 ----
| 发件人 | Maomeng ***@***.***> |
| 日期 | 2024年11月01日 11:19 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] server内存一直缓慢增长 (Issue #1919) |

@xiongbl526 通过cnch() udf可能不好区分，你可以直接连上4.7G的server pod查看一下

**Comment by smmsmm1988** [comment]
> 没太懂，麻烦细说下怎么查
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | Maomeng ***@***.***> | | 日期 | 2024年11月01日 11:19 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [ByConity/ByConity] server内存一直缓慢增长 (Issue #1919) | @xiongbl526 通过cnch() udf可能不好区分，你可以直接连上4.7G的server pod查看一下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

就是你直接登陆消耗内存高的server pod，执行
SELECT
*,
formatReadableSize(value) AS cacheSize
FROM system.asynchronous_metrics
WHERE metric LIKE '%Cache%'
ORDER BY value DESC
LIMIT 15

**Comment by xiongbl526** [comment]
SELECT
   *,
   formatReadableSize(value) AS cacheSize
FROM system.asynchronous_metrics
WHERE metric LIKE '%Cache%'
ORDER BY value DESC
LIMIT 15

Query id: abbecbed-e3e7-4f2a-b6e9-5c59faec570e

┌─metric─────────────────────────┬──────value─┬─cacheSize──┐
│ OSMemoryFreePlusCached         │ 7216001024 │ 6.72 GiB   │
│ OSMemoryCached                 │ 6722244608 │ 6.26 GiB   │
│ OSMemoryFreeWithoutCached      │  493756416 │ 470.88 MiB │
│ CnchPartCacheParts             │     499370 │ 487.67 KiB │
│ UniqueKeyIndexMetaCacheBytes   │     393191 │ 383.98 KiB │
│ UniqueKeyIndexBlockCacheBytes  │     237525 │ 231.96 KiB │
│ CompiledExpressionCacheBytes   │      57344 │ 56.00 KiB  │
│ CnchPartCachePartitions        │      16402 │ 16.02 KiB  │
│ DeleteBitmapCacheBytes         │       7330 │ 7.16 KiB   │
│ CnchDeleteBitmapCacheBitmaps   │       4110 │ 4.01 KiB   │

看了也没有那两个指标



---- 回复的原邮件 ----
| 发件人 | Maomeng ***@***.***> |
| 日期 | 2024年11月01日 13:52 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] server内存一直缓慢增长 (Issue #1919) |

没太懂，麻烦细说下怎么查
…
---- 回复的原邮件 ---- | 发件人 | Maomeng @.> | | 日期 | 2024年11月01日 11:19 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [ByConity/ByConity] server内存一直缓慢增长 (Issue #1919) | @xiongbl526 通过cnch() udf可能不好区分，你可以直接连上4.7G的server pod查看一下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***>

就是你直接登陆消耗内存高的server pod，执行
SELECT
*,
formatReadableSize(value) AS cacheSize
FROM system.asynchronous_metrics
WHERE metric LIKE '%Cache%'
ORDER BY value DESC
LIMIT 15

**Comment by smmsmm1988** [comment]
@xiongbl526 和同事对齐了下，之前内部解过server端的一个内存泄漏bug（而且不好观测），0.4.2版本上存在这个bug，1.0.0版本上这个bug已经fix了。要不用1.0.0版本试试？0.4.2版本的话，规避方案可能只有重启了

**Comment by xiongbl526** [comment]
好的，但是1.0.0版本有kafka消费异常那个问题我们还不敢用，那个问题什么能修复呢



---- 回复的原邮件 ----
| 发件人 | Maomeng ***@***.***> |
| 日期 | 2024年11月01日 15:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] server内存一直缓慢增长 (Issue #1919) |

@xiongbl526 和同事对齐了下，之前内部解过server端的一个内存泄漏bug（而且不好观测），0.4.2版本上存在这个bug，1.0.0版本上这个bug已经fix了。要不用1.0.0版本试试？0.4.2版本的话，规避方案可能只有重启了

**Comment by smmsmm1988** [comment]
> 好的，但是1.0.0版本有kafka消费异常那个问题我们还不敢用，那个问题什么能修复呢
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | Maomeng ***@***.***> | | 日期 | 2024年11月01日 15:55 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [ByConity/ByConity] server内存一直缓慢增长 (Issue #1919) | @xiongbl526 和同事对齐了下，之前内部解过server端的一个内存泄漏bug（而且不好观测），0.4.2版本上存在这个bug，1.0.0版本上这个bug已经fix了。要不用1.0.0版本试试？0.4.2版本的话，规避方案可能只有重启了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

1.0.1版本就修复了

**Comment by ixnzh** [comment]
刚发布，可以用新版本测试一下
