### ISSUE TITLE
一台Byconity-server查询奔溃，导致另一台byconity-server也写不进去数据

### ISSUE THREAD

**Issue by xinip** [ByConity/ByConity#1920]
一台Byconity-server查询奔溃，导致另一台byconity-server也写不进去数据，我们有两台byconity-server，其中一台专门对外查询使用，另一台专门用来写入，凌晨对外查询的byconity-server奔溃后，另一台写入的byconity-server也写不进去了。附件是dump文件

## Bug Report
[Uploading bb4c16eb-9de7-4db2-e680f193-7f902fb6.zip…]()

**Comment by smmsmm1988** [comment]
@xinip 写不进去报的是什么异常呀？另外，我好像没看到哪里有附件，是不是忘了上传了？

**Comment by xinip** [comment]
补了附件

2024.11.01 05:38:49.473455 [ 148700 ] {a7c0c58a-4d1e-4a9b-ae1a-0bf5d61dafa7} (453616789412642818) <Error> executeQuery: Code: 8054, e.displayText() = DB::Exception: Fail to redirect writeParts request to remote host : {clickhouse-master 172.24.150.91  rpc/8124 tcp/9010}. Error message : 1008:[E1008]Reached timeout=3000ms @172.24.150.91:8124 SQLSTATE: HY000 (version 21.8.7.1) (from [::ffff:172.24.150.131]:40232) (in query: insert into xxdb.xxtest (col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,col_10,col_11,col_12,col_13,col_14,col_15,col_16,col_17,col_18,col_19,col_20,col_21,col_22,col_23,col_24,col_25,col_26,col_27,col_28,col_29,col_30,col_31,col_32,col_33,ext) FORMAT JSONEachRow ), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x2723c412 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x1078cbc0 in /usr/bin/clickhouse
2. DB::Catalog::Catalog::writeParts(std::__1::shared_ptr<DB::IStorage> const&, DB::TxnTimestamp const&, DB::Catalog::CommitItems const&, bool, bool)::$_77::operator()() const @ 0x2008936d in /usr/bin/clickhouse
3. DB::Catalog::Catalog::writeParts(std::__1::shared_ptr<DB::IStorage> const&, DB::TxnTimestamp const&, DB::Catalog::CommitItems const&, bool, bool) @ 0x2004dfee in /usr/bin/clickhouse
4. DB::InsertAction::executeV2() @ 0x20164552 in /usr/bin/clickhouse
5. DB::CnchDataWriter::commitPreparedCnchParts(DB::DumpedData const&, std::__1::unique_ptr<DB::S3AttachPartsInfo, std::__1::default_delete<DB::S3AttachPartsInfo> > const&) @ 0x201558db in /usr/bin/clickhouse
6. DB::CnchDataWriter::commitDumpedParts(DB::DumpedData const&) @ 0x201539e3 in /usr/bin/clickhouse
7. DB::CnchDataWriter::dumpAndCommitCnchParts(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart> > > const&, std::__1::vector<std::__1::shared_ptr<DB::LocalDeleteBitmap>, std::__1::allocator<std::__1::shared_ptr<DB::LocalDeleteBitmap> > > const&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart> > > const&) @ 0x20150fde in /usr/bin/clickhouse
8. DB::CnchDataWriter::schedule(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart> > > const&, std::__1::vector<std::__1::shared_ptr<DB::LocalDeleteBitmap>, std::__1::allocator<std::__1::shared_ptr<DB::LocalDeleteBitmap> > > const&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart> > > const&) @ 0x201571f3 in /usr/bin/clickhouse
9. DB::CloudMergeTreeBlockOutputStream::write(DB::Block const&) @ 0x21db1b17 in /usr/bin/clickhouse
10. DB::PushingToViewsBlockOutputStream::write(DB::Block const&) @ 0x21119152 in /usr/bin/clickhouse
11. DB::AddingDefaultBlockOutputStream::write(DB::Block const&) @ 0x21115e0c in /usr/bin/clickhouse
12. DB::SquashingBlockOutputStream::finalize() @ 0x21115554 in /usr/bin/clickhouse
13. DB::SquashingBlockOutputStream::writeSuffix() @ 0x2111560e in /usr/bin/clickhouse
14. DB::CountingBlockOutputStream::writeSuffix() @ 0x207b3ec3 in /usr/bin/clickhouse
15. DB::ISink::prepare() @ 0x222f4cdf in /usr/bin/clickhouse
16. DB::PipelineExecutor::prepareProcessor(unsigned long, unsigned long, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::unique_lock<std::__1::mutex>) @ 0x2232a6a5 in /usr/bin/clickhouse
17. DB::PipelineExecutor::tryAddProcessorToStackIfUpdated(DB::ExecutingGraph::Edge&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, unsigned long) @ 0x2232a545 in /usr/bin/clickhouse
18. DB::PipelineExecutor::prepareProcessor(unsigned long, unsigned long, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::unique_lock<std::__1::mutex>) @ 0x2232ac6d in /usr/bin/clickhouse
19. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0x2232f98d in /usr/bin/clickhouse
20. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x2232deec in /usr/bin/clickhouse
21. DB::PipelineExecutor::execute(unsigned long) @ 0x2232d8e5 in /usr/bin/clickhouse
22. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::MPPQueryCoordinator>)>, std::__1::optional<DB::FormatSettings> const&, bool) @ 0x215a1357 in /usr/bin/clickhouse
23. DB::HTTPHandler::processQuery(std::__1::shared_ptr<DB::Context>, DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x2225e1b5 in /usr/bin/clickhouse
24. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x22260e2f in /usr/bin/clickhouse
25. DB::HTTPServerConnection::run() @ 0x222d4999 in /usr/bin/clickhouse
26. Poco::Net::TCPServerConnection::start() @ 0x271b1b4c in /usr/bin/clickhouse
27. Poco::Net::TCPServerDispatcher::run() @ 0x271b202c in /usr/bin/clickhouse
28. Poco::PooledThread::run() @ 0x2729913a in /usr/bin/clickhouse
29. Poco::ThreadImpl::runnableEntry(void*) @ 0x27296cec in /usr/bin/clickhouse
30. ? @ 0x94ac3 in /usr/lib/x86_64-linux-gnu/libc.so.6
31. ? @ 0x126850 in /usr/lib/x86_64-linux-gnu/libc.so.6

2024.11.01 05:38:49.474953 [ 148700 ] {a7c0c58a-4d1e-4a9b-ae1a-0bf5d61dafa7} (453616789412642818) <Error> DynamicQueryHandler: Code: 8054, e.displayText() = DB::Exception: Fail to redirect writeParts request to remote host : {clickhouse-master 172.24.150.91  rpc/8124 tcp/9010}. Error message : 1008:[E1008]Reached timeout=3000ms @172.24.150.91:8124 SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x2723c412 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x1078cbc0 in /usr/bin/clickhouse
2. DB::Catalog::Catalog::writeParts(std::__1::shared_ptr<DB::IStorage> const&, DB::TxnTimestamp const&, DB::Catalog::CommitItems const&, bool, bool)::$_77::operator()() const @ 0x2008936d in /usr/bin/clickhouse
3. DB::Catalog::Catalog::writeParts(std::__1::shared_ptr<DB::IStorage> const&, DB::TxnTimestamp const&, DB::Catalog::CommitItems const&, bool, bool) @ 0x2004dfee in /usr/bin/clickhouse
4. DB::InsertAction::executeV2() @ 0x20164552 in /usr/bin/clickhouse
5. DB::CnchDataWriter::commitPreparedCnchParts(DB::DumpedData const&, std::__1::unique_ptr<DB::S3AttachPartsInfo, std::__1::default_delete<DB::S3AttachPartsInfo> > const&) @ 0x201558db in /usr/bin/clickhouse
6. DB::CnchDataWriter::commitDumpedParts(DB::DumpedData const&) @ 0x201539e3 in /usr/bin/clickhouse
7. DB::CnchDataWriter::dumpAndCommitCnchParts(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart> > > const&, std::__1::vector<std::__1::shared_ptr<DB::LocalDeleteBitmap>, std::__1::allocator<std::__1::shared_ptr<DB::LocalDeleteBitmap> > > const&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart> > > const&) @ 0x20150fde in /usr/bin/clickhouse
8. DB::CnchDataWriter::schedule(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart> > > const&, std::__1::vector<std::__1::shared_ptr<DB::LocalDeleteBitmap>, std::__1::allocator<std::__1::shared_ptr<DB::LocalDeleteBitmap> > > const&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart> > > const&) @ 0x201571f3 in /usr/bin/clickhouse
9. DB::CloudMergeTreeBlockOutputStream::write(DB::Block const&) @ 0x21db1b17 in /usr/bin/clickhouse
10. DB::PushingToViewsBlockOutputStream::write(DB::Block const&) @ 0x21119152 in /usr/bin/clickhouse
11. DB::AddingDefaultBlockOutputStream::write(DB::Block const&) @ 0x21115e0c in /usr/bin/clickhouse
12. DB::SquashingBlockOutputStream::finalize() @ 0x21115554 in /usr/bin/clickhouse
13. DB::SquashingBlockOutputStream::writeSuffix() @ 0x2111560e in /usr/bin/clickhouse
14. DB::CountingBlockOutputStream::writeSuffix() @ 0x207b3ec3 in /usr/bin/clickhouse
15. DB::ISink::prepare() @ 0x222f4cdf in /usr/bin/clickhouse
16. DB::PipelineExecutor::prepareProcessor(unsigned long, unsigned long, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::unique_lock<std::__1::mutex>) @ 0x2232a6a5 in /usr/bin/clickhouse
17. DB::PipelineExecutor::tryAddProcessorToStackIfUpdated(DB::ExecutingGraph::Edge&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, unsigned long) @ 0x2232a545 in /usr/bin/clickhouse
18. DB::PipelineExecutor::prepareProcessor(unsigned long, unsigned long, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::unique_lock<std::__1::mutex>) @ 0x2232ac6d in /usr/bin/clickhouse
19. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0x2232f98d in /usr/bin/clickhouse
20. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x2232deec in /usr/bin/clickhouse
21. DB::PipelineExecutor::execute(unsigned long) @ 0x2232d8e5 in /usr/bin/clickhouse
22. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::MPPQueryCoordinator>)>, std::__1::optional<DB::FormatSettings> const&, bool) @ 0x215a1357 in /usr/bin/clickhouse
23. DB::HTTPHandler::processQuery(std::__1::shared_ptr<DB::Context>, DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x2225e1b5 in /usr/bin/clickhouse
24. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x22260e2f in /usr/bin/clickhouse
25. DB::HTTPServerConnection::run() @ 0x222d4999 in /usr/bin/clickhouse
26. Poco::Net::TCPServerConnection::start() @ 0x271b1b4c in /usr/bin/clickhouse
27. Poco::Net::TCPServerDispatcher::run() @ 0x271b202c in /usr/bin/clickhouse
28. Poco::PooledThread::run() @ 0x2729913a in /usr/bin/clickhouse
29. Poco::ThreadImpl::runnableEntry(void*) @ 0x27296cec in /usr/bin/clickhouse
30. ? @ 0x94ac3 in /usr/lib/x86_64-linux-gnu/libc.so.6
31. ? @ 0x126850 in /usr/lib/x86_64-linux-gnu/libc.so.6
 (version 21.8.7.1)

**Comment by smmsmm1988** [comment]
@xinip Byconity的server没有专门用来查询或者专门用来写入的概念，server是一个整体，每个server负责自己划分的表。你的这个问题是，挂掉的server（172.24.150.91），实际负责你要写入的表，所以写入要转发到这个server，因为这个server挂了，所以写入失败。这种异常是可以自恢复的，要么等到挂掉的server拉起来，要么等server的拓扑更新、把挂掉的server踢出拓扑。

**Comment by xinip** [comment]
挂掉的byconity-server当时导致机器负载特别的高，我手动kill掉byconity-server才能启动成功，并且发现查询特别慢。有没有一种命令查询所有byconity-server提交的查询，现在发现system.processes表只能查询到当前byconity-server提交过的查询，并不能查询到所有byconity-server提交的查询

**Comment by smmsmm1988** [comment]
> 挂掉的byconity-server当时导致机器负载特别的高，我手动kill掉byconity-server才能启动成功，并且发现查询特别慢。有没有一种命令查询所有byconity-server提交的查询，现在发现system.processes表只能查询到当前byconity-server提交过的查询，并不能查询到所有byconity-server提交的查询

有，select * from cnch(server, system.processes) where balabala

**Comment by xinip** [comment]
> > 挂掉的byconity-server当时导致机器负载特别的高，我手动kill掉byconity-server才能启动成功，并且发现查询特别慢。有没有一种命令查询所有byconity-server提交的查询，现在发现system.processes表只能查询到当前byconity-server提交过的查询，并不能查询到所有byconity-server提交的查询
> 
> 有，select * from cnch(server, system.processes) where balabala

怎么kill呢？

**Comment by smmsmm1988** [comment]
@xinip kill只能在本地执行。可以select podName(), * from cnch(server, system.processes) where balabala找到query和server pod的对应关系，然后登陆到对应的server上执行kill

**Comment by xinip** [comment]
> @xinip kill只能在本地执行。可以select podName(), * from cnch(server, system.processes) where balabala找到query和server pod的对应关系，然后登陆到对应的server上执行kill

建议你们加一个类似集群kill的命令，不然机器一多，这个方法没法操作

**Comment by smmsmm1988** [comment]
@xinip 物理机部署的话，就select host(), * from cnch(server, system.processes) where balabala

**Comment by smmsmm1988** [comment]
> > @xinip kill只能在本地执行。可以select podName(), * from cnch(server, system.processes) where balabala找到query和server pod的对应关系，然后登陆到对应的server上执行kill
> 
> 建议你们加一个类似集群kill的命令，不然机器一多，这个方法没法操作，我们是物理机部署的podName()好像没有返回

收到，感谢建议。我们后续内部评估一下

**Comment by smmsmm1988** [comment]
@xinip 你好，请问还有进一步的问题吗

**Comment by xinip** [comment]
> @xinip 你好，请问还有进一步的问题吗

现在我们整个集群查询特别慢，还没找到原因

**Comment by smmsmm1988** [comment]
> > @xinip 你好，请问还有进一步的问题吗
> 
> 现在我们整个集群查询特别慢，还没找到原因

1、如果有监控的话，看下监控，看看有没有资源使用瓶颈；
2、取一个查询慢query的query_id，执行命令，可以看看主要瓶颈在哪里：
SELECT　    podName() AS pod,　    query_duration_ms AS query_ms,　    read_bytes,　    ProfileEvents.Values[indexOf(ProfileEvents.Names, 'SelectedParts')] AS parts_count,　    ProfileEvents.Values[indexOf(ProfileEvents.Names, 'SelectedMarks')] AS marks_count,　    ProfileEvents.Values[indexOf(ProfileEvents.Names, 'ReadBufferFromHdfsReadBytes')] AS hdfs_bytes,　    (ProfileEvents.Values[indexOf(ProfileEvents.Names, 'HDFSReadElapsedMicroseconds')]) / 1000 AS hdfs_time,　    ProfileEvents.Values[indexOf(ProfileEvents.Names, 'ReadBufferFromFileDescriptorReadBytes')] AS disk_bytes,　    (ProfileEvents.Values[indexOf(ProfileEvents.Names, 'DiskReadElapsedMicroseconds')]) / 1000 AS disk_time,　    round(disk_bytes / (disk_bytes + hdfs_bytes), 2) AS hit_rate,　    (ProfileEvents.Values[indexOf(ProfileEvents.Names, 'RemoteFSAsynchronousReadWaitMicroseconds')]) / 1000 AS wait_time,　    (MaxIOThreadProfileEvents['RemoteFSAsynchronousReadWaitMicroseconds']) / 1000 AS wait_max_time　FROM cnch('{查询vw的名称}', system.query_log)　WHERE initial_query_id = '{query_id}'　ORDER BY query_ms DESC

**Comment by xinip** [comment]
我把集群全部进程stop掉后，再start后又好了，并且小文件也开始大量减少了，stop之前小文件一直在增加

**Comment by smmsmm1988** [comment]
> 我把集群全部进程stop掉后，再start后又好了，并且小文件也开始大量减少了，stop之前小文件一直在增加

写入的小文件吗

**Comment by ixnzh** [comment]
> 我把集群全部进程stop掉后，再start后又好了，并且小文件也开始大量减少了，stop之前小文件一直在增加

感觉就是part堆积太多，merge任务和查询都夯住了

**Comment by xinip** [comment]
底层hdfs的小文件，这种情况下一般什么原因造成的？我今天先重启单个服务好像没效果，必须全部stop后再全部start才有效果

**Comment by smmsmm1988** [comment]
> 底层hdfs的小文件，这种情况下一般什么原因造成的？我今天先重启单个服务好像没效果，必须全部stop后再全部start才有效果

那就是merge hang住了

**Comment by smmsmm1988** [comment]
@xinip 可以执行下面的sql看一下：
select toStartOfHour(event_time) as t, countIf(event_type = 1) as i, sumIf(num_source_parts , event_type = 2) as m from cnch(server, system.server_part_log) where event_date >= today()-1 group by t order by t;

**Comment by xinip** [comment]
> @xinip 可以执行下面的sql看一下： select toStartOfHour(event_time) as t, countIf(event_type = 1) as i, sumIf(num_source_parts , event_type = 2) as m from cnch(server, system.server_part_log) where event_date >= today()-1 group by t order by t;

[whale_query_45800743.xlsx](https://github.com/user-attachments/files/17598125/whale_query_45800743.xlsx)
这是查询结果

**Comment by smmsmm1988** [comment]
![image](https://github.com/user-attachments/assets/7a36b076-6148-4236-b1c4-5d6096dc0a4c)

@xinip 这个时间段确实没有merge了，只有写入

**Comment by xinip** [comment]
> ![image](https://private-user-images.githubusercontent.com/7722001/382242552-7a36b076-6148-4236-b1c4-5d6096dc0a4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NTM3MDIsIm5iZiI6MTczMDQ1MzQwMiwicGF0aCI6Ii83NzIyMDAxLzM4MjI0MjU1Mi03YTM2YjA3Ni02MTQ4LTQyMzYtYjFjNC01ZDYwOTZkYzBhNGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDFUMDkzMDAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTM2MjIwNTVkZDVjOGZmN2Y5MTNiY2Y3MDczZjE0YWM0ZWFlMTcxNTFjMTgyM2RkYjI3MTkwOWUzYzRmODIwMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.lR05Lp6Jgx2AsLet8WFpLbyilpmzxnmauecmZGNbDjU)
> 
> @xinip 这个时间段确实没有merge了，只有写入

这个时间点是完全没写入文件，卡死了。

**Comment by smmsmm1988** [comment]
> > ![image](https://private-user-images.githubusercontent.com/7722001/382242552-7a36b076-6148-4236-b1c4-5d6096dc0a4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NTM3MDIsIm5iZiI6MTczMDQ1MzQwMiwicGF0aCI6Ii83NzIyMDAxLzM4MjI0MjU1Mi03YTM2YjA3Ni02MTQ4LTQyMzYtYjFjNC01ZDYwOTZkYzBhNGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDFUMDkzMDAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTM2MjIwNTVkZDVjOGZmN2Y5MTNiY2Y3MDczZjE0YWM0ZWFlMTcxNTFjMTgyM2RkYjI3MTkwOWUzYzRmODIwMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.lR05Lp6Jgx2AsLet8WFpLbyilpmzxnmauecmZGNbDjU)
> > @xinip 这个时间段确实没有merge了，只有写入
> 
> 这个时间点是完全没写入文件，卡死了。

那不太对呀，第二列就是写入的part数量

**Comment by smmsmm1988** [comment]
select toStartOfHour(event_time) as t, database, table, countIf(event_type = 1) as i, sumIf(num_source_parts , event_type = 2) as m from cnch(server, system.server_part_log) where event_date >= today()-1 group by t, database, table order by t;
@xinip 可以再执行这个sql看一下

**Comment by xinip** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/7722001/382242552-7a36b076-6148-4236-b1c4-5d6096dc0a4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NTM3MDIsIm5iZiI6MTczMDQ1MzQwMiwicGF0aCI6Ii83NzIyMDAxLzM4MjI0MjU1Mi03YTM2YjA3Ni02MTQ4LTQyMzYtYjFjNC01ZDYwOTZkYzBhNGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDFUMDkzMDAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTM2MjIwNTVkZDVjOGZmN2Y5MTNiY2Y3MDczZjE0YWM0ZWFlMTcxNTFjMTgyM2RkYjI3MTkwOWUzYzRmODIwMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.lR05Lp6Jgx2AsLet8WFpLbyilpmzxnmauecmZGNbDjU)
> > > @xinip 这个时间段确实没有merge了，只有写入
> > 
> > 
> > 这个时间点是完全没写入文件，卡死了。
> 
> 那不太对呀，第二列就是写入的part数量

但是我们在库里确实查询不到中间卡死时写入的数据

**Comment by smmsmm1988** [comment]
![image](https://github.com/user-attachments/assets/c9609fad-1157-40e1-8252-7fbac35acd83)

@xinip 可能需要麻烦你提供这个时间段内，daemon manager、server、write worker对应的日志文件了。我们需要依赖日志文件来分析merge卡住的原因

**Comment by xinip** [comment]
这个日志文件太大了，github附件应该上传不了

**Comment by smmsmm1988** [comment]
> 这个日志文件太大了，github附件应该上传不了

方便的话，可以一起打成一个压缩包，邮件发送给我🙏

**Comment by smmsmm1988** [comment]
> > > 这个日志文件太大了，github附件应该上传不了
> > 
> > 
> > 方便的话，可以一起打成一个压缩包，邮件发送给我🙏
> 
> 给下邮箱，我打下包发个百度网盘共享链接吧

sumaomeng@bytedance.com

**Comment by smmsmm1988** [comment]
> select toStartOfHour(event_time) as t, database, table, countIf(event_type = 1) as i, sumIf(num_source_parts , event_type = 2) as m, countIf(event_type = 5) as remove, countIf(event_type = 6) as delete from cnch(server, system.server_part_log) where event_date >= today()-1 group by t, database, table order by t; @xinip 可以再执行这个sql看一下

@xinip 这个别忘了也执行一下哈

**Comment by xinip** [comment]
> > select toStartOfHour(event_time) as t, database, table, countIf(event_type = 1) as i, sumIf(num_source_parts , event_type = 2) as m, countIf(event_type = 5) as remove, countIf(event_type = 6) as delete from cnch(server, system.server_part_log) where event_date >= today()-1 group by t, database, table order by t; @xinip 可以再执行这个sql看一下
> 
> @xinip 这个别忘了也执行一下哈

@smmsmm1988 已经把上面这个查询结果和日志发生到你的邮箱了，请查收

**Comment by smmsmm1988** [comment]
> > > select toStartOfHour(event_time) as t, database, table, countIf(event_type = 1) as i, sumIf(num_source_parts , event_type = 2) as m, countIf(event_type = 5) as remove, countIf(event_type = 6) as delete from cnch(server, system.server_part_log) where event_date >= today()-1 group by t, database, table order by t; @xinip 可以再执行这个sql看一下
> > 
> > 
> > @xinip 这个别忘了也执行一下哈
> 
> @smmsmm1988 已经把上面这个查询结果和日志发生到你的邮箱了，请查收

你好，不好意思，今天发现公司内可能不方便使用百度网盘。你看要不要你把你的微信号通过邮箱私发我，我加你微信，我们通过微信传输下文件？或者能用飞书传输的话，更方便

**Comment by xinip** [comment]
那我把微信号通过邮箱发给你了

**Comment by xinip** [comment]
@smmsmm1988 我这边现在自从这次崩溃一次后，有的查询非常慢，之前几秒钟查询完的，现在几十分钟都查询不完，还报超时错误
