### ISSUE TITLE
报错Timeout exceeded: While executing Remote SQLSTATE: 08000

### ISSUE THREAD

**Issue by xiongbl526** [ByConity/ByConity#1921]
(you don't have to strictly follow this form)

## Question
版本0.4.2
执行sql
`INSERT INTO clientv3_videoLog.ads_talk_d
select  date,
		IF(b.country_code = 'unkown','unknow',b.country_code) as country_code,
		IF(b.country = '其他国家','unknow',b.country) as country,
		IF(b.province = '其他省份','unknow',b.province) as province,
		sum(case when a.res='success' then 1 else 0 end) as count,
		count() as total_count,
		sum(case when a.res='success' then duration else 0 end) as total_duration,
		case when count=0 then 0 else floor(total_duration/count) end as avg_duration,
    	2024-11-04 as day,
		sum(case when a.res='success' then cost else 0 end) as cost
   from (select date,pid,did,res,duration,cost
           from clientv3_videoLog.dwd_videolog_screal_talk_new 
          where date = 2024-11-04 and cost>=0 and cost<=1672502400000 
	        and pid<>'') a
   inner join
		(select product_id,device_code,device_model,version_sn,country_code,country,province
		   from paas_device.dwd_device_info
		  where vendor_etl='LC'
		    and device_model not in (select model from mapping.unwanted_model)) b
	 on a.pid = b.product_id and a.did=b.device_code
  group by date,b.country_code,b.country,b.province,pid,b.device_model,b.version_sn`

报错:
{2367c182-bd7f-4403-95ba-0cc60872dad3} <Error> DynamicQueryHandler: Code: 209, e.displayText() = DB::NetException: Timeout exceeded: While executing Remote SQLSTATE: 08000, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x2723c3d2 in /opt/byconity/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x1078cbc0 in /opt/byconity/bin/clickhouse
2. DB::RemoteQueryExecutorReadContext::checkTimeoutImpl(bool) @ 0x207d0cb7 in /opt/byconity/bin/clickhouse
3. DB::RemoteQueryExecutorReadContext::checkTimeout(bool) @ 0x207d0a75 in /opt/byconity/bin/clickhouse
4. DB::RemoteQueryExecutorReadContext::resumeRoutine() @ 0x207d0e21 in /opt/byconity/bin/clickhouse
5. DB::RemoteQueryExecutor::read(std::__1::unique_ptr<DB::RemoteQueryExecutorReadContext, std::__1::default_delete<DB::RemoteQueryExecutorReadContext> >&) @ 0x207cb423 in /opt/byconity/bin/clickhouse
6. DB::RemoteSource::tryGenerate() @ 0x224dda56 in /opt/byconity/bin/clickhouse
7. DB::ISource::work() @ 0x222f7179 in /opt/byconity/bin/clickhouse
8. DB::SourceWithProgress::work() @ 0x224e32fa in /opt/byconity/bin/clickhouse
9. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0, void ()> >(std::__1::__function::__policy_storage const*) @ 0x22331541 in /opt/byconity/bin/clickhouse
10. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0x2232f717 in /opt/byconity/bin/clickhouse
11. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x2232de8c in /opt/byconity/bin/clickhouse
12. DB::PipelineExecutor::execute(unsigned long) @ 0x2232d885 in /opt/byconity/bin/clickhouse
13. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::MPPQueryCoordinator>)>, std::__1::optional<DB::FormatSettings> const&, bool) @ 0x215a243f in /opt/byconity/bin/clickhouse
14. DB::HTTPHandler::processQuery(std::__1::shared_ptr<DB::Context>, DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x2225e1b5 in /opt/byconity/bin/clickhouse
15. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x22260e2f in /opt/byconity/bin/clickhouse
16. DB::HTTPServerConnection::run() @ 0x222d4939 in /opt/byconity/bin/clickhouse
17. Poco::Net::TCPServerConnection::start() @ 0x271b1b0c in /opt/byconity/bin/clickhouse
18. Poco::Net::TCPServerDispatcher::run() @ 0x271b1fec in /opt/byconity/bin/clickhouse
19. Poco::PooledThread::run() @ 0x272990fa in /opt/byconity/bin/clickhouse
20. Poco::ThreadImpl::runnableEntry(void*) @ 0x27296cac in /opt/byconity/bin/clickhouse
21. start_thread @ 0x7ea7 in /lib/x86_64-linux-gnu/libpthread-2.31.so
22. clone @ 0xfca2f in /lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.8.7.1)

**Comment by xiongbl526** [comment]
看了下每天还有其它不同sql也会有这种问题 都是超过5分钟后就报错的

**Comment by xuhaitao23** [comment]
> 看了下每天还有其它不同sql也会有这种问题 都是超过5分钟后就报错的

是不是设置了max_execution_time=300，可以尝试增大这个配置

**Comment by xiongbl526** [comment]
这个目前是10800秒



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年11月04日 10:52 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] 报错Timeout exceeded: While executing Remote SQLSTATE: 08000 (Issue #1921) |

看了下每天还有其它不同sql也会有这种问题 都是超过5分钟后就报错的

是不是设置了max_execution_time=300，可以尝试增大这个配置

**Comment by smmsmm1988** [comment]
@xiongbl526 receive_timeout和send_timeout看看是不是配置的是300，如果是的话，调大吧

**Comment by smmsmm1988** [comment]
> > @xiongbl526 receive_timeout和send_timeout看看是不是配置的是300，如果是的话，调大吧
> 
> 我调大试试看

这个调大以后还有问题吗

**Comment by xiongbl526** [comment]
我已经调大了，明天跑离线任务我再观察下



---- 回复的原邮件 ----
| 发件人 | Maomeng ***@***.***> |
| 日期 | 2024年11月04日 16:45 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] 报错Timeout exceeded: While executing Remote SQLSTATE: 08000 (Issue #1921) |

@xiongbl526 receive_timeout和send_timeout看看是不是配置的是300，如果是的话，调大吧

我调大试试看

这个调大以后还有问题吗
