### ISSUE TITLE
server服务磁盘使用限制

### ISSUE THREAD

**Issue by xiongbl526** [ByConity/ByConity#1923]
(you don't have to strictly follow this form)

## Question
0.4.2版本

两个server pod
values.yaml文件中server模块加了本地磁盘限制
单个server pod的磁盘是20G  因为没有开预加载 上午磁盘告警使用率达到80% 我又扩了5G 刚才又告警已经用了21G 但是另外一个server的pod磁盘使用就很少
configOverwrite:
      logger:
        level: debug
      disk_cache_strategies:
        simple:
          lru_max_size: 10737418240

**Comment by smmsmm1988** [comment]
@xiongbl526 可以去磁盘上 du -sh ./*看看是哪个目录占用的空间高

**Comment by xiongbl526** [comment]
是/var/byconity/data/store我看有个子目录占了十几个G



---- 回复的原邮件 ----
| 发件人 | Maomeng ***@***.***> |
| 日期 | 2024年11月06日 12:52 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] server服务磁盘使用限制 (Issue #1923) |

@xiongbl526 可以去磁盘上 du -sh ./*看看是哪个目录占用的空间高

**Comment by smmsmm1988** [comment]
> 是/var/byconity/data/store我看有个子目录占了十几个G
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | Maomeng ***@***.***> | | 日期 | 2024年11月06日 12:52 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [ByConity/ByConity] server服务磁盘使用限制 (Issue #1923) | @xiongbl526 可以去磁盘上 du -sh ./*看看是哪个目录占用的空间高 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

具体是哪个子目录

**Comment by xiongbl526** [comment]
eaa



---- 回复的原邮件 ----
| 发件人 | Maomeng ***@***.***> |
| 日期 | 2024年11月06日 14:33 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] server服务磁盘使用限制 (Issue #1923) |

是/var/byconity/data/store我看有个子目录占了十几个G
…
---- 回复的原邮件 ---- | 发件人 | Maomeng @.> | | 日期 | 2024年11月06日 12:52 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [ByConity/ByConity] server服务磁盘使用限制 (Issue #1923) | @xiongbl526 可以去磁盘上 du -sh ./看看是哪个目录占用的空间高 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.**>

具体是哪个子目录

**Comment by smmsmm1988** [comment]
> eaa
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | Maomeng ***@***.***> | | 日期 | 2024年11月06日 14:33 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [ByConity/ByConity] server服务磁盘使用限制 (Issue #1923) | 是/var/byconity/data/store我看有个子目录占了十几个G … ---- 回复的原邮件 ---- | 发件人 | Maomeng @.> | | 日期 | 2024年11月06日 12:52 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [ByConity/ByConity] server服务磁盘使用限制 (Issue #1923) | @xiongbl526 可以去磁盘上 du -sh ./看看是哪个目录占用的空间高 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.**> 具体是哪个子目录 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

再进去这个目录，看看下面，是不是有一堆uuid，再看看哪个uuid目录对应的空间比较大

**Comment by xiongbl526** [comment]
为啥会这么大呢？



---- 回复的原邮件 ----
| 发件人 | Maomeng ***@***.***> |
| 日期 | 2024年11月06日 15:21 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] server服务磁盘使用限制 (Issue #1923) |

eaa
…
---- 回复的原邮件 ---- | 发件人 | Maomeng @.> | | 日期 | 2024年11月06日 14:33 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [ByConity/ByConity] server服务磁盘使用限制 (Issue #1923) | 是/var/byconity/data/store我看有个子目录占了十几个G … ---- 回复的原邮件 ---- | 发件人 | Maomeng @.> | | 日期 | 2024年11月06日 12:52 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [ByConity/ByConity] server服务磁盘使用限制 (Issue #1923) | @xiongbl526 可以去磁盘上 du -sh ./看看是哪个目录占用的空间高 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.> 具体是哪个子目录 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.*>

再进去这个目录，看看下面，是不是有一堆uuid，再看看哪个uuid目录对应的空间比较大

**Comment by smmsmm1988** [comment]
可能对应的是系统表，拿到uuid后，去system.tables查一下是哪个表

**Comment by xiongbl526** [comment]
eaa下面的目录就一个uuid格式的子目录 ，用这个uuid在system.tables里没搜到，这个子目录里面很多日期格式的子目录



---- 回复的原邮件 ----
| 发件人 | Maomeng ***@***.***> |
| 日期 | 2024年11月06日 15:37 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] server服务磁盘使用限制 (Issue #1923) |

可能对应的是系统表，拿到uuid后，去system.tables查一下是哪个表

**Comment by smmsmm1988** [comment]
> eaa下面的目录就一个uuid格式的子目录 ，用这个uuid在system.tables里没搜到，这个子目录里面很多日期格式的子目录
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | Maomeng ***@***.***> | | 日期 | 2024年11月06日 15:37 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [ByConity/ByConity] server服务磁盘使用限制 (Issue #1923) | 可能对应的是系统表，拿到uuid后，去system.tables查一下是哪个表 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

可以截图看一下吗，以及查询system.tables的sql语句

**Comment by xiongbl526** [comment]
> > eaa下面的目录就一个uuid格式的子目录 ，用这个uuid在system.tables里没搜到，这个子目录里面很多日期格式的子目录
> > […](#)
> > ---- 回复的原邮件 ---- | 发件人 | Maomeng _**@**_._**> | | 日期 | 2024年11月06日 15:37 | | 收件人 | _**@**_.**_> | | 抄送至 | _**@**_._**>**_@_**.**_> | | 主题 | Re: [ByConity/ByConity] server服务磁盘使用限制 (Issue #1923) | 可能对应的是系统表，拿到uuid后，去system.tables查一下是哪个表 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: _**@**_.***>
> 
> 可以截图看一下吗，以及查询system.tables的sql语句
图片一直上传失败
root@user-byconity-server-1:/var/byconity/data/store/eaa/eaa8bc35-fab5-4967-8cf9-45bf03637567# ls  
202408_1_40260_2745       202411_806171_806515_175  202411_806171_806591_247  202411_806171_806663_319  202411_806495_806495_0  202411_806567_806567_0  202411_806639_806639_0
202408_40261_40261_0      202411_806171_806516_176  202411_806171_806592_248  202411_806171_806664_320  202411_806496_806496_0  202411_806568_806568_0  202411_806640_806640_0
202409_254689_384031_743  202411_806171_806521_177  202411_806171_806593_249  202411_806171_806665_321  202411_806497_806497_0  202411_806569_806569_0  202411_806641_806641_0
202409_384032_385371_371  202411_806171_806522_178  202411_806171_806594_250  202411_806171_806666_322  202411_806498_806498_0  202411_806570_806570_0  202411_806642_806642_0
202409_385372_385372_0    202411_806171_806523_179  202411_806171_806595_251  202411_806171_806667_323  202411_806499_806499_0  202411_806571_806571_0  202411_806643_806643_0

`select * from system.tables where uuid = 'eaa8bc35-fab5-4967-8cf9-45bf03637567'

SELECT *
FROM system.tables
WHERE uuid = 'eaa8bc35-fab5-4967-8cf9-45bf03637567'

Query id: 07db6131-62a7-4aed-b34b-74cb64b98a13

Ok.

0 rows in set. Elapsed: 1.295 sec. `

**Comment by smmsmm1988** [comment]
@xiongbl526 这个server做过什么变更吗？可以cd到日期格式的字目录，ls看下，都是哪些列

**Comment by xiongbl526** [comment]
> @xiongbl526 这个server做过什么变更吗？可以cd到日期格式的字目录，ls看下，都是哪些列

部署上没什么变更，ls出来是
bytes.bin      commit_ts.mrk                  end_ts.bin      event_date.mrk  exception.bin          part_id.bin    partition_id.bin  source_part_names.bin        table.mrk   versions.txt
bytes.mrk      count.txt                      end_ts.mrk      event_time.bin  exception.mrk          part_id.mrk    partition_id.mrk  source_part_names.mrk        txn_id.bin
checksums.txt  database.bin                   error.bin       event_time.mrk  is_staged.bin          part_name.bin  primary.idx       source_part_names.size0.bin  txn_id.mrk
columns.txt    database.mrk                   error.mrk       event_type.bin  is_staged.mrk          part_name.mrk  rows.bin          source_part_names.size0.mrk  uuid.bin
commit_ts.bin  default_compression_codec.txt  event_date.bin  event_type.mrk  minmax_event_date.idx  partition.dat  rows.mrk          table.bin                    uuid.mrk
现在磁盘使用率降了一点，由21G降到16G了

**Comment by smmsmm1988** [comment]
这个是server_part_log，用来存储part的变迁历史，就是存储在本地的

**Comment by smmsmm1988** [comment]
@xiongbl526 这个还有进一步的问题吗

**Comment by xiongbl526** [comment]
part_log比较大，是表分区设计还是其它什么原因呢



---- 回复的原邮件 ----
| 发件人 | Maomeng ***@***.***> |
| 日期 | 2024年11月08日 10:47 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] server服务磁盘使用限制 (Issue #1923) |

@xiongbl526 这个还有进一步的问题吗

**Comment by smmsmm1988** [comment]
> part_log比较大，是表分区设计还是其它什么原因呢
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | Maomeng ***@***.***> | | 日期 | 2024年11月08日 10:47 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [ByConity/ByConity] server服务磁盘使用限制 (Issue #1923) | @xiongbl526 这个还有进一步的问题吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

分区是按照月来分区的，你可以show create table system.server_part_log来看下具体的表schema。以及去这个目录下看看是哪个分区的数据量比较大，如果是11月份的话，那就是part操作比较频繁，导致server_part_log存储的比较大

**Comment by xiongbl526** [comment]
是通过statement这种原生的方式批量插入byconity 插入的很慢，不到三百条数据插入要10s 每次跑会导致server的cpu打满



---- 回复的原邮件 ----
| 发件人 | Maomeng ***@***.***> |
| 日期 | 2024年11月08日 13:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] server服务磁盘使用限制 (Issue #1923) |

part_log比较大，是表分区设计还是其它什么原因呢
…
---- 回复的原邮件 ---- | 发件人 | Maomeng @.> | | 日期 | 2024年11月08日 10:47 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [ByConity/ByConity] server服务磁盘使用限制 (Issue #1923) | @xiongbl526 这个还有进一步的问题吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***>

分区是按照月来分区的，你可以show create table system.server_part_log来看下具体的表schema。以及去这个目录下看看是哪个分区的数据量比较大，如果是11月份的话，那就是part操作比较频繁，导致server_part_log存储的比较大

**Comment by smmsmm1988** [comment]
@xiongbl526 这个server_part_log相关的还有进一步的问题吗
