### ISSUE TITLE
Byconity execute sql which partition filter condition is searched from subquery, it is much slower than unset enable_optimizer when set enable_optimize

### ISSUE THREAD

**Issue by zhaojintaozhao** [ByConity/ByConity#1925]
Hi all
I find a special sql, which partition key filter condition is searched from subquery. It is much slower than unset enable_optimizer when set enable_optimize

This is the created table sql:
```
CREATE TABLE if not exists db.test1
(
	did String,
	name String,
    key UInt32,
    value String,
    pt_d Date
)
ENGINE = CnchMergeTree()
PARTITION BY toYYYYMMDD(pt_d)
ORDER BY (id, key);
```
Then I insert data to this table:
```
insert into table db.test1
select  concat('id', toString((rand(now()) % 100))),
	concat('name', toString((rand(now()+1) % 100))),
	((rand(now()+2) % 100)),
	concat('value', toString(((rand(now()+3) % 100)) + 1)),
	toDate(addDays('2020-01-01', rand(now()+4)%100))  from  numbers(9000000);
```

When I execute the sql which partition key filter condition is searched from subquery, it cost 0.3s
```
select name
from
(
   select name, sum(1) as id_users, sum(key) as all_id_users 
   from db.test1
   where pt_d = (select max(pt_d) from db.test1) and id != 'id33' and name != 'name59'
   group by name
   order by id_users desc
) t
where t.all_id_users>300
```

When I execute the sql which partition key filter condition is a specific value, it cost 0.02s
```
select name
from
(
   select name, sum(1) as id_users, sum(key) as all_id_users 
   from db.test1
   where pt_d = '2020-04-09'
   group by name
   order by id_users desc
) t
where t.all_id_users>300
```

When I execute the sql which partition key filter condition is searched from subquery and unset enable_optimizer, it cost 0.08s
```
select name
from
(
   select name, sum(1) as id_users, sum(key) as all_id_users 
   from db.test1
   where pt_d = (select max(pt_d) from db.test1) and id != 'id33' and name != 'name59'
   group by name
   order by id_users desc
) t
where t.all_id_users>300 settings enable_optimizer=0;
```

This may becase the partition key condition is searched from subquery, and we should optimize the query optimizer.

Does any one face the same problem?

**Comment by zhaojintaozhao** [comment]
After I execute "create stats db.test1", then I query the same sql, it's failed and catch exception 
```
Code: 49. DB::Exception: Received from {server-ip}:{server-port}. DB::Exception: Code: 49, e.displayText() = DB::Exception: Worker host:{worker-ip}:{worker-port}, exception:Code: 49, e.displayText() = DB::Exception: Block structure mismatch in  function connect between ExpressionTransform and Resize stream: different number of columns:
name String String(size = 0), key UInt32 UInt32(size = 0), pt_d Date UInt16(size = 0)
id String String(size = 0), name String String(size = 0), key UInt32 UInt32(size = 0), pt_d Date UInt16(size = 0) SQLSTATE: HY000 (version 21.8.7.1) SQLSTATE: HY000 (version 21.8.7.1) SQLSTATE: HY000.
```
This is the stack info from default-worker
```
{time} [ 1519802 ] {query_uuid_2} (........) <Error> PlanSegmentExecutor[200] : [query_uuid_2]: Query has excpetion with code: 49, detail
: Code: 49, e.displayText() = DB::Exception: Block structure mismatch in  function connect between ExpressionTransform and Resize stream: different number of columns:
name String String(size = 0), key UInt32 UInt32(size = 0), pt_d Date UInt16(size = 0)
id String String(size = 0), name String String(size = 0), key UInt32 UInt32(size = 0), pt_d Date UInt16(size = 0) SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xxxxxx in /opt/byconity/default-worker/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xxxxxx in /opt/byconity/default-worker/bin/clickhouse
2. ? @ 0xxxxxx in /opt/byconity/default-worker/bin/clickhouse
3. DB::connect(DB::OutputPort&, DB::InputPort&) @ 0xxxxxx in /opt/byconity/default-worker/bin/clickhouse
4. DB::Pipe::addTransform(std::__1::shared_ptr<DB::IProcessor>, DB::OutputPort*, DB::OutputPort*) @ 0xxxxxx in /opt/byconity/default-worker/bin/clickhouse
5. DB::QueryPipeline::addTransform(std::__1::shared_ptr<DB::IProcessor>) @ 0xxxxxx in /opt/byconity/default-worker/bin/clickhouse
6. DB::MergeTreeSelectPrepareProcessor::expandPipeline() @ 0xxxxxx in /opt/byconity/default-worker/bin/clickhouse
7. DB::PipelineExecutor::expandPipeline(std::__1::stack<unsigned long, std::__1::deque<unsigned long, std::__1::allocator<unsigned long> > >&, unsigned long) @ 0xxxxxx in /opt/byconity/default-worker/bin/clickhouse
8. DB::PipelineExecutor::doExpandPipeline(DB::PipelineExecutor::ExpandPipelineTask*, bool) @ 0xxxxxx in /opt/byconity/default-worker/bin/clickhouse
9. DB::PipelineExecutor::prepareProcessor(unsigned long, unsigned long, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::queue<DB::ExecutingGraph::Node*, std::__1::deque<DB::ExecutingGraph::Node*, std::__1::allocator<DB::ExecutingGraph::Node*> > >&, std::__1::unique_lock<std::__1::mutex>) @ 0xxxxxx in /opt/byconity/default-worker/bin/clickhouse
10. DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) @ 0xxxxxx in /opt/byconity/default-worker/bin/clickhouse
11. DB::PipelineExecutor::executeSingleThread(unsigned long, unsigned long) @ 0xxxxxx in /opt/byconity/default-worker/bin/clickhouse
12. ? @ 0xxxxxx in /opt/byconity/default-worker/bin/clickhouse
13. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xxxxxx in /opt/byconity/default-worker/bin/clickhouse
14. ? @ 0xxxxxx in /opt/byconity/default-worker/bin/clickhouse
```
Then I drop all the cache files, it also throw the same exception.
Then I drop stats "drop stats db.test1" and query the same sql, it's sucess but much slower than which partition key filter condition is a specific value.

**Comment by zhaojintaozhao** [comment]
> Can you try "create stats db.test1", and execute query again? If optimizer is enabled, join will be used to execute "where pt_d = (select max(pt_d) from db.test1)" And if "create stats db.test1" is executed, runtime filter should be used to filter data

In this sql: "where pt_d = (select max(pt_d) from db.test1":  pt_d is the partition key of table, why not first execute the subsql:  "select max(pt_d) from db.test1"  and get the  specific value of partiton key, then using this partition key to filter partitions?

**Comment by mtunique** [comment]
you can set `early_execute_in_subquery  = 1 `  to execute in subquery. There is another similar setting `early_execute_scalar_subquery` to execute saclar subquery at first.

**Comment by zhaojintaozhao** [comment]
> > > Can you try "create stats db.test1", and execute query again? If optimizer is enabled, join will be used to execute "where pt_d = (select max(pt_d) from db.test1)" And if "create stats db.test1" is executed, runtime filter should be used to filter data
> > 
> > 
> > In this sql filter conditions:
> > ```
> > where pt_d = (select max(pt_d) from db.test1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > pt_d is the partition key of table, why not first execute the subsql: "select max(pt_d) from db.test1" and get the specific value of partiton key, then using this partition key to filter partitions?
> 
> you can set `early_execute_in_subquery = 1 ` to execute in subquery. There is another similar setting `early_execute_scalar_subquery` to execute saclar subquery at first.

This is a good idea, which version support "early_execute_in_subquery" or "early_execute_scalar_subquery"?

**Comment by xuhaitao23** [comment]
> > > > Can you try "create stats db.test1", and execute query again? If optimizer is enabled, join will be used to execute "where pt_d = (select max(pt_d) from db.test1)" And if "create stats db.test1" is executed, runtime filter should be used to filter data
> > > 
> > > 
> > > In this sql filter conditions:
> > > ```
> > > where pt_d = (select max(pt_d) from db.test1
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > pt_d is the partition key of table, why not first execute the subsql: "select max(pt_d) from db.test1" and get the specific value of partiton key, then using this partition key to filter partitions?
> > 
> > 
> > you can set `early_execute_in_subquery = 1 ` to execute in subquery. There is another similar setting `early_execute_scalar_subquery` to execute saclar subquery at first.
> 
> This is a good idea, which version support "early_execute_in_subquery" or "early_execute_scalar_subquery"? Does ByConity1.0.0 support these settings?

确认了一下代码ByConity1.0.0应该是支持的

**Comment by zhaojintaozhao** [comment]
> > > > > Can you try "create stats db.test1", and execute query again? If optimizer is enabled, join will be used to execute "where pt_d = (select max(pt_d) from db.test1)" And if "create stats db.test1" is executed, runtime filter should be used to filter data
> > > > 
> > > > 
> > > > In this sql filter conditions:
> > > > ```
> > > > where pt_d = (select max(pt_d) from db.test1
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > pt_d is the partition key of table, why not first execute the subsql: "select max(pt_d) from db.test1" and get the specific value of partiton key, then using this partition key to filter partitions?
> > > 
> > > 
> > > you can set `early_execute_in_subquery = 1 ` to execute in subquery. There is another similar setting `early_execute_scalar_subquery` to execute saclar subquery at first.
> > 
> > 
> > This is a good idea, which version support "early_execute_in_subquery" or "early_execute_scalar_subquery"? Does ByConity1.0.0 support these settings?
> 
> 确认了一下代码ByConity1.0.0应该是支持的

我们当前的1.0.0版本里面不支持“early_execute_in_subquery”或“early_execute_scalar_subquery”;
合入了https://github.com/ByConity/ByConity/commit/0d2cd65ff61a3aefd364c6022094af0e9c67542c 后测试，
early_execute_scalar_subquery为true对enable_optimizer =1对这个查询场景是有用的。
感谢。
