### ISSUE TITLE
cnch_vw_default选择问题

### ISSUE THREAD

**Issue by bright-zy** [ByConity/ByConity#1930]
(you don't have to strictly follow this form)

## Question
T1表 cnch_vw_default = 'vw-work1'
T2表 cnch_vw_default = 'vw-work2'

执行 select ... from T1  where ... 用的是 vw-work1，但是执行 insert T2 select ... from T1  where ... 用的确实vw-work2，期望执行 T1 的查询都是 vw-work1。
有办法指定vw 或者是指定 WG 做资源隔离管控么

**Comment by bright-zy** [comment]
好的，加上之后没问题，不过建议默认用select的表对应的vw，由于预加载的数据是在select表对应的vw中

**Comment by smmsmm1988** [comment]
> 好的，加上之后没问题，不过建议默认用select的表对应的vw，由于预加载的数据是在select表对应的vw中

感谢建议，不过这块用select表对应的vw，涉及的改动可能比较大，现在是统一走insert的逻辑。我们后续再评估一下。临时绕过方案就是通过settings来显式指定
