### ISSUE TITLE
UNIQUE KEY 表 同一个key 多次插入。每次插入列不同，会导致其他列值为空的情况

### ISSUE THREAD

**Issue by liao626** [ByConity/ByConity#1932]
(you don't have to strictly follow this form)

## Question
这里有一张UNIQUE KEY 表，唯一键是shop_code，
涉及的列 (city_code,city_name,shop_code,stat_hour,showing_cnt,pt)
第一次插入 (shop_code,stat_hour,showing_cnt,pt)这几个列
第二次插入(city_code,city_name,shop_code,pt) 这几个列。两次插入，除了分区跟唯一键，没有交叉列。

最后select 查看后 第一次插入的列的数据被清空了，
想问有没有参数控制，第二次插入后，不影响第一次插入的列数据呀

<img width="707" alt="企业微信截图_17316547188068" src="https://github.com/user-attachments/assets/cb23861f-242f-4305-91dc-6b06b1a8262c">

**Comment by smmsmm1988** [comment]
@liao626 请问你这个是哪个版本？目前unique表唯一键采用行级别覆盖的写形式

**Comment by liao626** [comment]
> @liao626 请问你这个是哪个版本？目前unique表唯一键采用行级别覆盖的写形式

0.4版本，我刚试了1.0的也是这种直接覆盖，请问，在insert into values()这种插入方式下，能控制只更新部分列字段吗

**Comment by smmsmm1988** [comment]
> > @liao626 请问你这个是哪个版本？目前unique表唯一键采用行级别覆盖的写形式
> 
> 0.4版本，我刚试了1.0的也是这种直接覆盖，请问，在insert into values()这种插入方式下，能控制只更新部分列字段吗

目前暂时没有部分列更新功能，部分列更新功能，预计在未来的（可能是明年）版本中提供

**Comment by liao626** [comment]
> > > @liao626 请问你这个是哪个版本？目前unique表唯一键采用行级别覆盖的写形式
> > 
> > 
> > 0.4版本，我刚试了1.0的也是这种直接覆盖，请问，在insert into values()这种插入方式下，能控制只更新部分列字段吗
> 
> 目前暂时没有部分列更新功能，部分列更新功能，预计在未来的（可能是明年）版本中提供

好的，感谢解答
