### ISSUE TITLE
为什么Context::resource_group_manager的初始化被注释掉了呢

### ISSUE THREAD

**Issue by xincai98** [ByConity/ByConity#1935]
(you don't have to strictly follow this form)

## Question
void Context::initResourceGroupManager(const ConfigurationPtr & )里面的内容注释掉了

**Comment by smmsmm1988** [comment]
@xincai98 我们暂时不打算支持单pod内部的source group

**Comment by xincai98** [comment]
我看之前是支持的，现在不支持是出于什么考虑呢？

**Comment by smmsmm1988** [comment]
> 我看之前是支持的，现在不支持是出于什么考虑呢？

之前也没有支持过的，之前的代码只是demo代码，没有上线测试和发布过
