### ISSUE TITLE
cache_set_rate_limit 配置问题

### ISSUE THREAD

**Issue by bright-zy** [ByConity/ByConity#1948]
(you don't have to strictly follow this form)

## Question
worker 节点 配置预加载限制后，启动异常
```
    <disk_cache_strategies>
        <MergeTree>
            <cache_set_rate_limit>1000</cache_set_rate_limit>
        </MergeTree>
    </disk_cache_strategies>
```
报错
```
<Error> DiskIteratorLoader(META(simple)): std::exception. Code: 1001, type: std::__1::system_error, e.what() = mutex lock failed: Invalid argument, Stack trace (when copying this message, always include the lines below):

0. std::runtime_error::runtime_error(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x2800ec50 in /data/byconity/clickhouse
1. std::__1::system_error::system_error(std::__1::error_code, char const*) @ 0x280179be in /data/byconity/clickhouse
2. std::__1::__throw_system_error(int, char const*) @ 0x28018032 in /data/byconity/clickhouse
3. ? @ 0x2800d3fb in /data/byconity/clickhouse
4. DB::BucketLRUCache<wide::integer<128ul, unsigned int>, DB::DiskCacheMeta, UInt128Hash, DB::DiskCacheWeightFunction>::setImpl(wide::integer<128ul, unsigned int> const&, std::__1::shared_ptr<DB::DiskCacheMeta> const&, DB::BucketLRUCache<wide::integer<128ul, unsigned int>, DB::DiskCacheMeta, UInt128Hash, DB::DiskCacheWeightFunction>::SetMode) @ 0x223d3066 in /data/byconity/clickhouse
5. DB::DiskCacheLRU::DiskCacheLoader::iterateFile(std::__1::__fs::filesystem::path, unsigned long) @ 0x223cb477 in /data/byconity/clickhouse
6. DB::DiskCacheLRU::DiskIterator::iterateDirectory(std::__1::__fs::filesystem::path, unsigned long)::$_9::operator()(std::__1::__fs::filesystem::path) const @ 0x223ca1b1 in /data/byconity/clickhouse
7. DB::DiskCacheLRU::DiskIterator::iterateDirectory(std::__1::__fs::filesystem::path, unsigned long) @ 0x223c97da in /data/byconity/clickhouse
8. DB::DiskCacheLRU::DiskIterator::iterateDirectory(std::__1::__fs::filesystem::path, unsigned long)::$_9::operator()(std::__1::__fs::filesystem::path) const @ 0x223ca2bf in /data/byconity/clickhouse
9. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::DiskCacheLRU::DiskIterator::iterateDirectory(std::__1::__fs::filesystem::path, unsigned long)::$_10, void ()> >(std::__1::__function::__policy_storage const*) @ 0x223d0f2e in /data/byconity/clickhouse
10. void std::__1::__invoke_void_return_wrapper<void>::__call<createExceptionHandledJob(std::__1::function<void ()>, DB::ExceptionHandler&)::'lambda'()&>(createExceptionHandledJob(std::__1::function<void ()>, DB::ExceptionHandler&)::'lambda'()&) @ 0x10e3fe51 in /data/byconity/clickhouse
11. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x10cb35a1 in /data/byconity/clickhouse
12. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0x10cb50a8 in /data/byconity/clickhouse
13. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x10cafd20 in /data/byconity/clickhouse
14. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0x10cb411a in /data/byconity/clickhouse
15. start_thread @ 0x7e25 in /usr/lib64/libpthread-2.17.so
16. clone @ 0xfebad in /usr/lib64/libc-2.17.so
 (version 21.8.7.1)

 <Fatal> BaseDaemon: Calculated checksum of the binary: 29D960FC197A72CF659D65DA509CEE28. There is no information about the reference checksum.
```

**Comment by foreverneverer** [comment]
这个栈和cache_set_rate_limit的路径理论上没有关系，尝试去掉这个参数重新测试以确认该问题

**Comment by bright-zy** [comment]
> 这个栈和cache_set_rate_limit的路径理论上没有关系，尝试去掉这个参数重新测试以确认该问题

去掉后，启动正常

**Comment by smmsmm1988** [comment]
@bright-zy 加上后是必现的吗？

**Comment by bright-zy** [comment]
> @bright-zy 加上后是必现的吗？
1.0.1 vw节点，加上后必现，去掉后正常
<img width="521" alt="image" src="https://github.com/user-attachments/assets/03b68738-9d8b-4534-b5ce-a5b77bd75e80">

**Comment by smmsmm1988** [comment]
> @smmsmm1988 1.0.1 vw节点，加上后必现，去掉后正常 <img alt="image" width="521" src="https://private-user-images.githubusercontent.com/102500454/391902325-03b68738-9d8b-4534-b5ce-a5b77bd75e80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMDQxNzIsIm5iZiI6MTczMzMwMzg3MiwicGF0aCI6Ii8xMDI1MDA0NTQvMzkxOTAyMzI1LTAzYjY4NzM4LTlkOGItNDUzNC1iNWNlLWE1Yjc3YmQ3NWU4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQwOTE3NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDY1NjIyZjk0N2VlNWM4MWFhYWYzZGNjZGMyMjA5YmNiMjc3NTE3MGI4NWM5NjY1YzFiZDI3YmU1YjRkNWI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.p0Fo72sA8_hInEPeLSKWWV2ABoymM8PVOC5Ye8h21yM">

这个我们内部还没能复现这个问题，你把cache_set_rate_limit的值调小些看看还有问题吗

**Comment by bright-zy** [comment]
@smmsmm1988 还是有问题，帮忙分析下日志
[byconity-worker.log](https://github.com/user-attachments/files/18023557/byconity-worker.log)

**Comment by foreverneverer** [comment]
> @smmsmm1988 1.0.1 vw节点，加上后必现，去掉后正常 <img alt="image" width="521" src="https://private-user-images.githubusercontent.com/102500454/391902325-03b68738-9d8b-4534-b5ce-a5b77bd75e80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NTExOTMsIm5iZiI6MTczMzQ1MDg5MywicGF0aCI6Ii8xMDI1MDA0NTQvMzkxOTAyMzI1LTAzYjY4NzM4LTlkOGItNDUzNC1iNWNlLWE1Yjc3YmQ3NWU4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQwMjA4MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMmIzOTA5MGZjODQzZTI3ZjhiZGYyZjc0ZWNkNGIxYThjNzMzM2U0N2ZkMWQzZTY0YmVkMTdmYjM4ZDI3YTE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4oMjbCJIbU-t13umyugldbARrdQxrlo5KxfdtV8b5FY">

为什么会配置两个diskcache实例？

**Comment by foreverneverer** [comment]
<img width="1621" alt="image" src="https://github.com/user-attachments/assets/660d8093-86ca-4134-ab27-c7462d1b1a39">
这里看起来两个diskcache去加载了同一个路径的数据

**Comment by smmsmm1988** [comment]
@foreverneverer 配置两个diskcache实例是必须的吗？

**Comment by foreverneverer** [comment]
> @foreverneverer 配置两个diskcache实例是必须的吗？

不是必须的，甚至不应该有

**Comment by foreverneverer** [comment]
> @smmsmm1988 1.0.1 vw节点，加上后必现，去掉后正常 <img alt="image" width="521" src="https://private-user-images.githubusercontent.com/102500454/391902325-03b68738-9d8b-4534-b5ce-a5b77bd75e80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NTExOTMsIm5iZiI6MTczMzQ1MDg5MywicGF0aCI6Ii8xMDI1MDA0NTQvMzkxOTAyMzI1LTAzYjY4NzM4LTlkOGItNDUzNC1iNWNlLWE1Yjc3YmQ3NWU4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQwMjA4MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMmIzOTA5MGZjODQzZTI3ZjhiZGYyZjc0ZWNkNGIxYThjNzMzM2U0N2ZkMWQzZTY0YmVkMTdmYjM4ZDI3YTE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4oMjbCJIbU-t13umyugldbARrdQxrlo5KxfdtV8b5FY">

你删除的是<MergeTree></MergeTree>，不单单是limit这个参数吧？

**Comment by foreverneverer** [comment]
把配置修改成这样：
    <disk_cache_strategies>
        <simple>
            <cache_set_rate_limit>1000</cache_set_rate_limit>
            <meta_cache_size_ratio>15</meta_cache_size_ratio>
            <lru_max_size>1649267441664</lru_max_size>
        </simple>
    </disk_cache_strategies>

**Comment by bright-zy** [comment]
> 把配置修改成这样：
> 
> ```
>     <disk_cache_strategies>
>         <simple>
>             <cache_set_rate_limit>1000</cache_set_rate_limit>
>             <meta_cache_size_ratio>15</meta_cache_size_ratio>
>             <lru_max_size>1649267441664</lru_max_size>
>         </simple>
>     </disk_cache_strategies>
> ```
@foreverneverer @smmsmm1988  按照这个配置正常了，感谢支持
