### ISSUE TITLE
使用多server，部分查询其中一个server查询很慢

### ISSUE THREAD

**Issue by skyoct** [ByConity/ByConity#1950]
## 查询
server-0
```
SELECT
    podName(),
    ck_date,
    countDistinct(pd_device_id) AS ck_result,
    countDistinct(pd_device_id) AS ck_uv
FROM ods.app_10001_base_default AS pd_tmp_table
INNER JOIN dim.common_base_user_cohort_v1 AS cohort_table ON pd_tmp_table.pd_device_id = cohort_table.user_id
WHERE (pd_tmp_table.ck_date IN ('2024-12-01')) AND (pd_kind = 'play_game') AND (cohort_id = '106103')
GROUP BY ck_date
ORDER BY
    ck_date ASC,
    ck_result DESC
LIMIT 100000

Query id: 3856dfac-993b-44bd-9293-2c324330d277

┌─podName()──────────────┬────ck_date─┬─ck_result─┬──ck_uv─┐
│ base-byconity-server-0 │ 2024-12-01 │    207265 │ 207265 │
└────────────────────────┴────────────┴───────────┴────────┘

1 row in set. Elapsed: 6.418 sec. Processed 71.63 million rows, 3.32 GB (11.16 million rows/s., 516.75 MB/s.)
```
server-1
```
SELECT
    podName(),
    ck_date,
    countDistinct(pd_device_id) AS ck_result,
    countDistinct(pd_device_id) AS ck_uv
FROM ods.app_10001_base_default AS pd_tmp_table
INNER JOIN dim.common_base_user_cohort_v1 AS cohort_table ON pd_tmp_table.pd_device_id = cohort_table.user_id
WHERE (pd_tmp_table.ck_date IN ('2024-12-01')) AND (pd_kind = 'play_game') AND (cohort_id = '106103')
GROUP BY ck_date
ORDER BY
    ck_date ASC,
    ck_result DESC
LIMIT 100000

Query id: 8a60c413-489e-4065-a124-d66d0e55a2ff

┌─podName()──────────────┬────ck_date─┬─ck_result─┬──ck_uv─┐
│ base-byconity-server-1 │ 2024-12-01 │    207265 │ 207265 │
└────────────────────────┴────────────┴───────────┴────────┘

1 row in set. Elapsed: 0.591 sec. Processed 71.63 million rows, 3.32 GB (121.16 million rows/s., 5.61 GB/s.)
```
## query_log
看query_log 执行耗时相近
![image](https://github.com/user-attachments/assets/076eb2a0-7940-45e5-a00b-bc4fb9df1a61)

# 资源使用情况

![image](https://github.com/user-attachments/assets/fc49a4d9-d950-4e28-9c29-dbc6a24cb45e)

请问造成这个原因可能是什么呢？

**Comment by smmsmm1988** [comment]
@skyoct server-0反复执行都是一样的慢吗？

**Comment by skyoct** [comment]
@smmsmm1988 是的，执行多次还是很慢

**Comment by smmsmm1988** [comment]
> @smmsmm1988 是的，执行多次还是很慢

看下两个join的表，part数目分别有多少呢

**Comment by skyoct** [comment]
@smmsmm1988 
![image](https://github.com/user-attachments/assets/94525004-16d5-457b-a38d-74197dcf409d)
![image](https://github.com/user-attachments/assets/fa93ccdb-94a1-4220-80a6-f8648f237a5f)

237和48

**Comment by smmsmm1988** [comment]
@skyoct 
1、看下两个表各自的part数总和
2、select host from system.cnch_table_host where database = '' and name = ''看下两个表对应的host server

**Comment by skyoct** [comment]
1. 所有分区的part总和
![image](https://github.com/user-attachments/assets/674f75a3-cc13-41a3-b9d5-1521fb20cd6a)
2. 两个表对应的host server都是server-1

**Comment by smmsmm1988** [comment]
@skyoct 那就说的通了，你在server0上执行，server 0上没有part meta cache，它需要去找server 1要，这个是有rpc网络开销的，而在server1上执行，就直接本地load part meta cache了

**Comment by smmsmm1988** [comment]
@skyoct 至于执行时间统计，是有个已知bug的，我们已经修复了，后续版本回带上

**Comment by skyoct** [comment]
@smmsmm1988 
好的，明白了，那感觉目前多server使用有点"鸡肋", 相当于备用server无法用来查询, 这块后面有计划优化下嘛？

**Comment by smmsmm1988** [comment]
> @smmsmm1988 好的，明白了，那感觉目前多server使用有点"鸡肋", 相当于备用server无法用来查询, 这块后面有计划优化下嘛？

有的，我们目前正在做这块的优化，但是改动比较大，所以上线的话时间未定。
