### ISSUE TITLE
dictGet里用toUInt64函数报错

### ISSUE THREAD

**Issue by xiaochaoren1** [ByConity/ByConity#1959]
相同的语句，clickhouse 查询成功，byconity 查询报错
复现步骤：
1. 新建表 test_null，建表语句如下：
CREATE TABLE flow_tag1.test_null
(
id UInt32,
value Nullable(UInt8)
)
ENGINE = CnchMergeTree
ORDER BY id;
插入数据，语句如下：
INSERT INTO test_null (id, value) VALUES
(1, 1),
(2, null);
3. 随便创建一个双主键的dictionary，语句如下
CREATE DICTIONARY flow_tag1.test_map
(
    `id` String,
    `value` UInt64,
    `name` String,
)
PRIMARY KEY id, value
SOURCE (按需填写)
LIFETIME(MIN 30 MAX 60)
LAYOUT(COMPLEX_KEY_HASHED());
4. 结果截图，语句：select if(value is null,'',dictGet('flow_tag1.test_map','name',('xx',toUInt64(value)))) from flow_tag1.test_null
  a. byconity 版本：21.8.7，v1.0.0，报错
![image](https://github.com/user-attachments/assets/8c4b2483-b5e9-4aec-bb9f-6bc881609aef)
  b. clickhouse 版本：23.8.7，不报错
![image](https://github.com/user-attachments/assets/d829baca-5ce9-4bff-9dc9-3912c89e2d91)

**Comment by yuanzhubi** [comment]
可以试下 select if(value is null,'',dictGet('flow_tag1.test_map','name',('xx',toUInt64(**assumeNotNull** (value))))) from flow_tag1.test_null 么

**Comment by xiaochaoren1** [comment]
> 可以试下 select if(value is null,'',dictGet('flow_tag1.test_map','name',('xx',toUInt64(**assumeNotNull** (value))))) from flow_tag1.test_null 么

这个语句没问题，谢谢
