### ISSUE TITLE
Is there any cache in server/read_workers ? 

### ISSUE THREAD

**Issue by JiangXiNJU** [ByConity/ByConity#197]
hi, I try to test ssb-flat-sql on SSB-100G twice, and the two results are quite different(the time usages are listed below)
Is there any cache in server/read_workers ?  If it does exist, I want to close it. How can i do ?

First 
q1: 4995 ms
q2: 150 ms
q3: 142 ms
q4: 5171 ms
q5: 700 ms
q6: 535 ms
q7: 7100 ms
q8: 2031 ms
q9: 172 ms
q10: 3616 ms
q11: 413 ms
q12: 404 ms
Total cost: 25430 ms

Second
q1: 178 ms
q2: 155 ms
q3: 133 ms
q4: 571 ms
q5: 671 ms
q6: 557 ms
q7: 608 ms
q8: 630 ms
q9: 162 ms
q10: 933 ms
q11: 412 ms
q12: 440 ms
Total cost: 5451 ms

**Comment by Adora627** [comment]
> hi, I try to test ssb-flat-sql on SSB-100G twice, and the two results are quite different(the time usages are listed below) Is there any cache in server/read_workers ? If it does exist, I want to close it. How can i do ?
> 
> First q1: 4995 ms q2: 150 ms q3: 142 ms q4: 5171 ms q5: 700 ms q6: 535 ms q7: 7100 ms q8: 2031 ms q9: 172 ms q10: 3616 ms q11: 413 ms q12: 404 ms Total cost: 25430 ms
> 
> Second q1: 178 ms q2: 155 ms q3: 133 ms q4: 571 ms q5: 671 ms q6: 557 ms q7: 608 ms q8: 630 ms q9: 162 ms q10: 933 ms q11: 412 ms q12: 440 ms Total cost: 5451 ms

Hi the server and real_worker do have data cache to improve hot query performance.

**Comment by canhld94** [comment]
Hi @JiangXiNJU, read workers have local LRU cache for data. When you run a query second time, it will read most of data from own local cache instead of hdfs, so the performance will be better. There's no other caches (e.g. query result cache etc...).
To turn off data cache for a table `t`, you can do `ALTER TABLE t MODIFY SETTINGS enable_local_disk_cache=0`.

**Comment by WillemJiang** [comment]
@JiangXiNJU As already set up the [discussions](https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/about-discussions).
Do you mind that post the question in [the discussion  Q&A catalog](https://github.com/ByConity/ByConity/discussions/categories/q-a) next time?

**Comment by JiangXiNJU** [comment]
No, I'm ok with that.
