### ISSUE TITLE
The ByConity Server connection failed

### ISSUE THREAD

**Issue by songlinyu-hub** [ByConity/ByConity#222]
## Question

According to the document: [ByConity集群搭建与TPC-DS Benchmark实践](https://mp.weixin.qq.com/s?__biz=MzkwMTQzMjc2OQ==&mid=2247483709&idx=1&sn=016f3878b2d9ec05ddb724efa944821e&chksm=c0b5959), Error thrown when connecting ByConity Server during verification deployment after docker setup: 
run `./clickhouse client ` then 
' error while loading shared libraries: libfdb_c.so: cannot open shared object file:  No such file or directory'  ; who can give me more advice

**Comment by hustnn** [comment]
The simplest way to solve it is download fdb client binary from here https://github.com/apple/foundationdb/releases and install foundationdb-clients_7.1.27-1_xx. There is one example in this doc https://github.com/ByConity/ByConity/tree/master/packages
