### ISSUE TITLE
Will the Server module limit insertion performance when using SQL to insert data?

### ISSUE THREAD

**Issue by FourSpaces** [ByConity/ByConity#223]
## Will the Server module limit insertion performance when using SQL to insert data
Does it support SDK connection to write_ Worker performs data insertion, and we will use the regular SQL import method to insert data.

Data insertion format
```
INSERT INTO [db.]table [(c1, c2, c3...)] VALUES (v11, v12, v13), (v21, v22, v23), ...

```

**Comment by hustnn** [comment]
Hi @FourSpaces , we can suppport direct insert in workers, we can support it in this month. To get the worker list, you can query system table like `system.workers`, is it ok?

**Comment by FourSpaces** [comment]
@hustnn  We believe it is possible.

**Comment by hustnn** [comment]
> @hustnn We believe it is possible.

Ok, then let's do it.
