### ISSUE TITLE
map loss data

### ISSUE THREAD

**Issue by skyoct** [ByConity/ByConity#231]
(you don't have to strictly follow this form)

### Briefly describe the bug
Data in map type fields will be lost
![image](https://user-images.githubusercontent.com/24541857/233247176-345b6178-c46b-4249-897d-7f73a3bb20c8.png)

### The result you expected
normal data query
### How to Reproduce
create table SQL
`
CREATE TABLE datax.test_map_01
(
    `c_date` Date,
    `c_datetime` DateTime64(3),
    `s_map` Map(String, String),
    `i_map` Map(String, Int64),
    `f_map` Map(String, Float64)
)
ENGINE = CnchMergeTree
PARTITION BY c_date
ORDER BY c_date
TTL toDate(c_date) + toIntervalDay(30)
SETTINGS index_granularity = 8192;
`

insert data SQL
`
insert into datax.test_map_01(c_date, c_datetime, s_map, i_map, f_map)
values ('2023-04-14', '2023-04-14 13:16:17', {'s_a': 'abc', 's_b': 'ffff', 's_c': '123', 's_d': '1233', 's_e': '1234', 's_f': '1234'}, {'age': 18},
        {'price': 10.20000003});
`
query SQL
`
select * from datax.test_map_01;
`
At the beginning, the query is normal. After about 20 minutes, the data will loss

**Comment by canhld94** [comment]
@skyoct it's a merge issue. Data will be lost after merging parts.

**Comment by skyoct** [comment]
@canhld94 got it, thx
