### ISSUE TITLE
Enhance ci to support multi-worker, certificate suits and more cases

### ISSUE THREAD

**Issue by hustnn** [ByConity/ByConity#237]
CI cases is added in https://github.com/ByConity/ByConity/pull/254
Certificate test suit is added in https://github.com/ByConity/ByConity/pull/255
Clickhouse sql test suit is added in https://github.com/ByConity/ByConity/pull/257
The multi worker mode is enabled in https://github.com/ByConity/ByConity/pull/267

**Comment by vivek-debug** [comment]
Solving test case issues in #267

**Comment by vivek-debug** [comment]
Currently disabled cases that need to be solved for GA:

1. tests/queries/4_cnch_stateless/00203_full_join.sql.disabled
2. tests/queries/4_cnch_stateless/32413_window_function_test.sql.disabled
3. tests/queries/4_cnch_stateless/32413_window_rownumber_order_by.sql.disabled
4. tests/queries/4_cnch_stateless/40007_outer_join_to_inner_join.sql.disabled

cc @hustnn @dmthuc @canhld94
