### ISSUE TITLE
Simplify local installation and optimize documents

### ISSUE THREAD

**Issue by zhbdesign** [ByConity/ByConity#24]
1. Directly provide binary installation package
2. Provide the installation documents of fdb and hdfs
3. Local installation reduces dependency, and now python 3.9
4. Detailed documents of cluster deployment and cluster configuration
5. Remove functions and tables that are not supported by byconsistency to avoid misunderstanding
6. Detailed usage documents of all table engines supported

**Comment by zhbdesign** [comment]
What is the reason why local deployment is not recommended? K8s is too big for small companies

**Comment by FourSpaces** [comment]
@canhld94  k8s部署的文档对配置部分需要详细说明，有些地方都不知道如何配置，以及配置的含义。

**Comment by kevinthfang** [comment]
Package installation (non-containerized deployment) doc is ready [here](https://github.com/ByConity/ByConity/tree/master/packages). For k8s development guide, we will keep improving.
