### ISSUE TITLE
Compare ByConity with clickhouse/doris/presto in benchmark cluster (tpcds)

### ISSUE THREAD

**Issue by hustnn** [ByConity/ByConity#242]
We should benchmark with clickhouse, doris and presto and guide us to performance further performance optimization.

**Comment by hustnn** [comment]
Testing is done, will release tpcds cold/hot run result of ByConity, ClickHouse, Doris and Presto after GA.

**Comment by jerryldh** [comment]
> 

can you leave a url?

**Comment by hustnn** [comment]
Will release soon.
