### ISSUE TITLE
Compare ByConity cold/hot run performance

### ISSUE THREAD

**Issue by hustnn** [ByConity/ByConity#243]
We should compare and give the performance w/o disk cache.

**Comment by hustnn** [comment]
Finished the cold/hot run of 1TB TPCDS benchmark on ByConity. Will release the result after GA.

**Comment by xingcici** [comment]
> Finished the cold/hot run of 1TB TPCDS benchmark on ByConity. Will release the result after GA.

Where can I see this data？thks.

**Comment by Adora627** [comment]
> 

we have released the benchmark result: https://zhuanlan.zhihu.com/p/633306972
