### ISSUE TITLE
Kafka table engine 

### ISSUE THREAD

**Issue by skyoct** [ByConity/ByConity#250]
(you don't have to strictly follow this form)

### Describe the feature you'd like
May I ask if there will be a new Kafka table engine added?

**Comment by Adora627** [comment]
> (you don't have to strictly follow this form)
> 
> ## Feature Request
> ### Describe the feature you'd like
> May I ask if there will be a new Kafka table engine added?

What do you mean by new Kafka table engine? ByConity provided one differ from ClickHouse provided.

**Comment by skyoct** [comment]
@Adora627 thx, I originally thought there was no similar functionality to Kafka table engine, but now I see it.
