### ISSUE TITLE
Map type does not support materialized columns

### ISSUE THREAD

**Issue by skyoct** [ByConity/ByConity#269]
(you don't have to strictly follow this form)

### Briefly describe the bug
When I set the materialized column based on the map type, an error will be reported when inserting it.
```
Code: 44, e.displayText() = DB::Exception: Illegal column Map(String,String) of first argument of function arrayElement: while executing 'FUNCTION arrayElement(s_map :: 1, 's_a' :: 2) -> arrayElement(s_map, 's_a') String : 5' SQLSTATE: 42P10 (version 21.8.7.1)
```

 It's normal for me to try the same operation at clickhouse. (version: 23.3.1.2823)
### The result you expected
Can insert query normally
### How to Reproduce
1. create table
```
CREATE TABLE datax.test_map_10
(
    `c_date` Date,
    `s_map` Map(String, String)
)
ENGINE = CnchMergeTree
PARTITION BY c_date
ORDER BY c_date
TTL toDateTime(c_date) + toIntervalDay(30)
SETTINGS index_granularity = 8192
```
2. add materialized column
```
ALTER TABLE datax.test_map_10 ADD COLUMN s_a String MATERIALIZED s_map['s_a'];
```
3. insert data
```
insert into datax.test_map_10 values ('2023-04-21', {'s_a': 'abc', 's_b': 'cde'});
```
4. throw an error
```
Code: 44, e.displayText() = DB::Exception: Illegal column Map(String,String) of first argument of function arrayElement: while executing 'FUNCTION arrayElement(s_map :: 1, 's_a' :: 2) -> arrayElement(s_map, 's_a') String : 5' SQLSTATE: 42P10 (version 21.8.7.1)
```

### Version
21.8.7.1

**Comment by canhld94** [comment]
@skyoct  to access a map element, pls use `{}` instead of `[]`. `[]` is for array.

```sql
ALTER TABLE datax.test_map_10 ADD COLUMN s_a String MATERIALIZED s_map{'s_a'};
```

**Comment by skyoct** [comment]
@canhld94 I tried, using {} is normal, thx

**Comment by skyoct** [comment]
@canhld94 When I set the field type to Nullable, the query will appear 
```
Code: 48, e.displayText() = DB::Exception: Received from xxxxx:xxxx. DB::Exception: FieldVisitorHash Map type not implemented!: (while reading from part /user/clickhouse/2901fbd6-9315-4933-adfb-5e157b98dcf6/20230421_441257789671604225_441257789671604225_0_441257789671604224_0/): While executing MergeTree SQLSTATE: HY000. (version 21.8.7.
```

**Comment by canhld94** [comment]
@skyoct you mean change `s_a` to `Nullable(String)`?

**Comment by skyoct** [comment]
> @skyoct you mean change `s_a` to `Nullable(String)`?

yes
```
ALTER TABLE datax.test_map_10 ADD COLUMN s_a Nullable(String) MATERIALIZED s_map{'s_a'};
```

**Comment by canhld94** [comment]
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/22796953/236413356-5e076874-4ff3-4ef7-8591-4786ab4c484d.png">
I cannot reproduce it

**Comment by canhld94** [comment]
> <img alt="image" width="1185" src="https://user-images.githubusercontent.com/22796953/236413356-5e076874-4ff3-4ef7-8591-4786ab4c484d.png">
> 
> I cannot reproduce it

@skyoct can you paste the full stacktrace here?

**Comment by skyoct** [comment]
@canhld94 I can't reproduce this problem after truncate table. Now it can be used normally. Thank you very much.
