### ISSUE TITLE
tpcds createtable error

### ISSUE THREAD

**Issue by zhbdesign** [ByConity/ByConity#27]
tests\optimizers\tpcds\sql\create_ Table.sql All statements cannot be executed

**Comment by Adora627** [comment]
> tests\optimizers\tpcds\sql\create_ Table.sql All statements cannot be executed

hi, could you describe the steps led to the error?

**Comment by canhld94** [comment]
@hustnn any update on this issue?

**Comment by hustnn** [comment]
I checked this script is only for internal testing purpose, it is used by changing the engine type to memory, we don't have the official tpcds testing guide at this moment, need to enhance it at document level.

**Comment by canhld94** [comment]
@zhbdesign @hustnn I just check the DDL. The table contains nullable sorting key, so we need to add `settings allow_nullable_key=1` in the create SQL. Note that this is a storage setting, not query setting.

<img width="470" alt="image" src="https://user-images.githubusercontent.com/22796953/220826548-0f922652-4a7b-451e-9af3-c6659fb66101.png">
