### ISSUE TITLE
Minus operation between two DateTime64 type should not be allowed

### ISSUE THREAD

**Issue by dmthuc** [ByConity/ByConity#271]
Currently, minus operation between two DateTime64 type is allowed. The result type is IntervalSecond which can't represent the difference between two DateTime64 type. We need to disable this behaviour and update the test case accordingly
![CbeiDyCdhg](https://github.com/ByConity/ByConity/assets/13962605/8c982ee5-c85a-4508-850d-de9bc0f1851c)

**Comment by sperlingxx** [comment]
Hi @dmthuc, after discussing with other fellows, we tend to keep this behaviour unchanged as a useful feature which shall do NO harm to users :)
