### ISSUE TITLE
There is no session or session context has expired

### ISSUE THREAD

**Issue by zhbdesign** [ByConity/ByConity#28]
2023.01.12 15:10:31.676427 [ 186 ] {0d80b5cc-af85-45ec-afc4-ead822a01dda} <Error> executeQuery: Code: 113, e.displayText() = DB::Exception: There is no session or session context has expired SQLSTATE: HY000 (version 21.8.7.1) (from 10.20.1.240:24284) (in query: set enable_optimizer=1), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18e345d2 in /opt/byconity/usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb230820 in /opt/byconity/usr/bin/clickhouse
2. DB::Context::getSessionContext() const @ 0x13b8f621 in /opt/byconity/usr/bin/clickhouse
3. DB::InterpreterSetQuery::execute() @ 0x14109e6a in /opt/byconity/usr/bin/clickhouse
4. ? @ 0x1432ed74 in /opt/byconity/usr/bin/clickhouse
5. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::optional<DB::FormatSettings> const&, bool) @ 0x14332b5f in /opt/byconity/usr/bin/clickhouse
6. DB::HTTPHandler::processQuery(std::__1::shared_ptr<DB::Context>, DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x14bbe7cb in /opt/byconity/usr/bin/clickhouse
7. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x14bc12af in /opt/byconity/usr/bin/clickhouse
8. DB::HTTPServerConnection::run() @ 0x14c0e979 in /opt/byconity/usr/bin/clickhouse
9. Poco::Net::TCPServerConnection::start() @ 0x18db01ec in /opt/byconity/usr/bin/clickhouse
10. Poco::Net::TCPServerDispatcher::run() @ 0x18db06cc in /opt/byconity/usr/bin/clickhouse
11. Poco::PooledThread::run() @ 0x18e9137a in /opt/byconity/usr/bin/clickhouse
12. Poco::ThreadImpl::runnableEntry(void*) @ 0x18e8ef2c in /opt/byconity/usr/bin/clickhouse
13. start_thread @ 0x7fa3 in /lib/x86_64-linux-gnu/libpthread-2.28.so
14. clone @ 0xf906f in /lib/x86_64-linux-gnu/libc-2.28.so

2023.01.12 15:10:31.676925 [ 186 ] {0d80b5cc-af85-45ec-afc4-ead822a01dda} <Error> DynamicQueryHandler: Code: 113, e.displayText() = DB::Exception: There is no session or session context has expired SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18e345d2 in /opt/byconity/usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb230820 in /opt/byconity/usr/bin/clickhouse
2. DB::Context::getSessionContext() const @ 0x13b8f621 in /opt/byconity/usr/bin/clickhouse
3. DB::InterpreterSetQuery::execute() @ 0x14109e6a in /opt/byconity/usr/bin/clickhouse
4. ? @ 0x1432ed74 in /opt/byconity/usr/bin/clickhouse
5. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::optional<DB::FormatSettings> const&, bool) @ 0x14332b5f in /opt/byconity/usr/bin/clickhouse
6. DB::HTTPHandler::processQuery(std::__1::shared_ptr<DB::Context>, DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x14bbe7cb in /opt/byconity/usr/bin/clickhouse
7. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x14bc12af in /opt/byconity/usr/bin/clickhouse
8. DB::HTTPServerConnection::run() @ 0x14c0e979 in /opt/byconity/usr/bin/clickhouse
9. Poco::Net::TCPServerConnection::start() @ 0x18db01ec in /opt/byconity/usr/bin/clickhouse
10. Poco::Net::TCPServerDispatcher::run() @ 0x18db06cc in /opt/byconity/usr/bin/clickhouse
11. Poco::PooledThread::run() @ 0x18e9137a in /opt/byconity/usr/bin/clickhouse
12. Poco::ThreadImpl::runnableEntry(void*) @ 0x18e8ef2c in /opt/byconity/usr/bin/clickhouse
13. start_thread @ 0x7fa3 in /lib/x86_64-linux-gnu/libpthread-2.28.so
14. clone @ 0xf906f in /lib/x86_64-linux-gnu/libc-2.28.so
 (version 21.8.7.1)

**Comment by zhbdesign** [comment]
The dbeaver execution set or use reported an error, and the clickhouse client was OK

**Comment by canhld94** [comment]
We haven't tested thoroughly with dbeaver yet, we will conduct a test as soon as possible. Thank you!
cc @hustnn

**Comment by kevinthfang** [comment]
@zhbdesign  are you trying to use 'USE' statment or 'SET' statement in dbeaver? These statements are not supposed to be used in JDBC (http handler). https://clickhouse.com/docs/en/sql-reference/statements/use/. other queries except 'USE' Other queries in this page https://github.com/ByConity/byconity-docker,  except 'USE' statement are successfully tested in dbeaver.
