### ISSUE TITLE
occur fatal error when enable hdfs switch read 

### ISSUE THREAD

**Issue by juppylm** [ByConity/ByConity#282]
When I set dfs.client.switch.read.enable to true and executed select * from xxx where aa = 'xx', an error occurred. The specific stack information is as follows:

![微信图片_20230515104944](https://github.com/ByConity/ByConity/assets/31834016/9527ea0d-07bc-4fe9-914f-80ff7cc980f2)
![微信图片_20230515110728](https://github.com/ByConity/ByConity/assets/31834016/5a9d9a97-eeac-4d34-b148-14a45e936c45)
![微信图片_20230515110737](https://github.com/ByConity/ByConity/assets/31834016/9235195f-c5e4-400c-89e9-aad308a772b7)

**Comment by canhld94** [comment]
@juppylm thanks for reporting the bug, we will fix it asap.
