### ISSUE TITLE
CnchHive with ORC format: cannot read correct data when `SELECT col FROM table`  with condition that `col` is the partition key

### ISSUE THREAD

**Issue by xiaomo728** [ByConity/ByConity#298]
Table in Hive:
```
CREATE TABLE `mych_orc`(                                               
   `id` int)
PARTITIONED BY (
   `city` string)   
ROW FORMAT SERDE                                                          
   'org.apache.hadoop.hive.ql.io.orc.OrcSerde'                             
STORED AS INPUTFORMAT                                                     
   'org.apache.hadoop.hive.ql.io.orc.OrcInputFormat'                       
OUTPUTFORMAT                                                              
   'org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat'
```

```
+--------------+----------------+
| mych_orc.id  | mych_orc.city  |
+--------------+----------------+
| 3            | chengdu        |
| 2            | guangzhou      |
| 1            | nanjing        |
+--------------+----------------+
```

CnchHive:
```
CREATE TABLE hive_orc
(
    `id` Int32,
    `city` String
)
ENGINE = CnchHive('thrift://xx.xx.xxx.xxx', 'database_name', 'mych_orc')
PARTITION BY city;
```

Bug:
![image](https://github.com/ByConity/ByConity/assets/74600187/6505b57d-cad3-4ef5-ba58-30c85a7dc627)

`city` is the partition key.

Only Hive tables based on ORC format will have this bug, Parquet-based ones will not.

**Comment by xiaomo728** [comment]
The code version is on May 22, 2023 (master).

**Comment by hustnn** [comment]
@Clark0 Pls help to take a look at this issue.

**Comment by Clark0** [comment]
> @Clark0 Pls help to take a look at this issue.

The issue is that the hive does not write the partition column to the orc data file. Therefore when reading the orc file, the partition column is not found and empty result is returned. We should treat the partition column like a virtual column.

**Comment by hustnn** [comment]
> The issue is that the hive does not write the partition column to the orc data file. Therefore when reading the orc file, the partition column is not found and empty result is returned. We should treat the partition column like a virtual column.

Is there any difference for parquet? For parquet, the partition column is not in data file, I think.

**Comment by wordhardqi** [comment]
https://github.com/ByConity/ByConity/pull/311/commits

**Comment by wordhardqi** [comment]
> > The issue is that the hive does not write the partition column to the orc data file. Therefore when reading the orc file, the partition column is not found and empty result is returned. We should treat the partition column like a virtual column.
> 
> Is there any difference for parquet? For parquet, the partition column is not in data file, I think.

The parquet file reader and orc file reader in arrow behave differents if the columns required is empty. The parquet reader will return a arrow::Table with num_rows in meta. The orc reader will simply return a empty arrow::Table whose num_rows is 0.
