### ISSUE TITLE
S3Disk support as main storage layer. 

### ISSUE THREAD

**Issue by UnamedRus** [ByConity/ByConity#30]
**Use case**
AWS, GCP and other main cloud vendors.

Where running own HDFS cluster could be avoided. 

**Additional context**
It seems, that storage_policy requires to have volume named `hdfs`.
And if you try to use in that volume something other than HDFS Disk, it return error during write:

```
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Received from 10.3.1.221:9000. DB::Exception: Writing part to hdfs but write buffer is not hdfs: While executing SinkToOutputStream SQLSTATE: HY000.
```

**Comment by canhld94** [comment]
Thank you for trying out Byconity and giving feedback, we appreciate your contribution!

Yes, for some reason we only focus on developing the storage engine on HDFS. The S3 supports are on track to be released, thank you!

**Comment by hustnn** [comment]
S3 supporting is on the roadmap. https://github.com/ByConity/ByConity/issues/26
