### ISSUE TITLE
ClickHouse response without column names

### ISSUE THREAD

**Issue by zhbdesign** [ByConity/ByConity#31]
dbeaver error 

SELECT * FROM system.cnch_tables where database = currentDatabase() and name = 'dts_bucket_with_split_number_n_range' FORMAT CSV;

SQL 错误 [1002]: ClickHouse exception, code: 1002, host: 10.100.3.48, port: 8123; ClickHouse response without column names

**Comment by kevinthfang** [comment]
Could you please try the solution in this https://github.com/dbeaver/dbeaver/issues/4142?
 in the driver properties of DBeaver I change the "compress" option to "false"

**Comment by zhbdesign** [comment]
clickhouse has the same problem, it's a dbeaver problem
