### ISSUE TITLE
system.distributed_ddl_queue

### ISSUE THREAD

**Issue by zhbdesign** [ByConity/ByConity#32]
The system.distributed_ddl_queue table will cause the server to exit. Now the permission has not been designed.You can remove permission-related tables from the system. SQL error [497]: ClickHouse exception, code: 497, host: 10.100.3.48, port: 8123; Code: 497, e.displayText() = DB::Exception: default:  Not enough privileges. To execute this query it's necessary to have grant SHOW SETTINGS PROFILES ON *.* SQLSTATE:  HY000 (version 21.8.7.1)

**Comment by kevinthfang** [comment]
Could you describe in more details what's your steps?

**Comment by zhbdesign** [comment]
> Could you describe in more details what's your steps?

select * from system.distributed_ddl_queue

**Comment by hustnn** [comment]
We can disable this system table (system.distributed_ddl_queue) in ByConity since it is not used anymore. 

Or anyone has interest on working on it.

**Comment by hustnn** [comment]
@zhbdesign Do you have interest on this issue?

**Comment by hustnn** [comment]
The fix is merged. let me close this issue.
