### ISSUE TITLE
server start error

### ISSUE THREAD

**Issue by zhbdesign** [ByConity/ByConity#34]
Startup error log:
2023.01.13 08:11:20.828947 [ 17 ] {} <Warning> Application: Calculated checksum of the binary: 7B0734FCB0DE0271D880B340784BCEDA. There is no information about the reference checksum.
2023.01.13 08:11:20.896737 [ 17 ] {} <Error> CnchServerManager: There is no zookeeper, skip start background task for serverManager
Restart error log:
2023.01.13 10:27:53.949400 [ 17 ] {} <Warning> Application: Calculated checksum of the binary: 7B0734FCB0DE0271D880B340784BCEDA. There is no information about the reference checksum.
2023.01.13 10:27:53.969618 [ 17 ] {} <Error> CnchServerManager: There is no zookeeper, skip start background task for serverManager
2023.01.13 10:27:54.104651 [ 205 ] {} <Error> auto DB::MergeTreeData::loadPartsFromFileSystem(DB::MergeTreeData::PartNamesWithDisks, DB::MergeTreeData::PartNamesWithDisks, bool, DB::MergeTreeMetaBase::DataPartsLock &)::(anonymous class)::operator()() const: Code: 246, e.displayText() = DB::Exception: While loading part /var/byconity/data/store/09c/09ce3590-8eb7-4dca-aa17-3f475cfbb795/20230113_20230113_507_507_0/: calculated partition ID: 19850803 differs from partition ID in part name: 202301 SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18e345d2 in /opt/byconity/usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb230820 in /opt/byconity/usr/bin/clickhouse
2. DB::IMergeTreeDataPart::loadPartitionAndMinMaxIndex() @ 0x14914689 in /opt/byconity/usr/bin/clickhouse
3. DB::IMergeTreeDataPart::loadColumnsChecksumsIndexes(bool, bool) @ 0x14911473 in /opt/byconity/usr/bin/clickhouse
4. ? @ 0x149988d8 in /opt/byconity/usr/bin/clickhouse
5. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xb26ad9e in /opt/byconity/usr/bin/clickhouse
6. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0xb26cca4 in /opt/byconity/usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb267a3f in /opt/byconity/usr/bin/clickhouse
8. ? @ 0xb26bd1a in /opt/byconity/usr/bin/clickhouse
9. start_thread @ 0x7fa3 in /lib/x86_64-linux-gnu/libpthread-2.28.so
10. clone @ 0xf906f in /lib/x86_64-linux-gnu/libc-2.28.so
(version 21.8.7.1)
2023.01.13 10:27:54.104651 [ 206 ] {} <Error> auto DB::MergeTreeData::loadPartsFromFileSystem(DB::MergeTreeData::PartNamesWithDisks, DB::MergeTreeData::PartNamesWithDisks, bool, DB::MergeTreeMetaBase::DataPartsLock &)::(anonymous class)::operator()() const: Code: 246, e.displayText() = DB::Exception: While loading part /var/byconity/data/store/09c/09ce3590-8eb7-4dca-aa17-3f475cfbb795/20230113_20230113_1_539_108/: calculated partition ID: 19850803 differs from partition ID in part name: 202301 SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):
0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18e345d2 in /opt/byconity/usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb230820 in /opt/byconity/usr/bin/clickhouse
2. DB::IMergeTreeDataPart::loadPartitionAndMinMaxIndex() @ 0x14914689 in /opt/byconity/usr/bin/clickhouse
3. DB::IMergeTreeDataPart::loadColumnsChecksumsIndexes(bool, bool) @ 0x14911473 in /opt/byconity/usr/bin/clickhouse
4. ? @ 0x149988d8 in /opt/byconity/usr/bin/clickhouse
5. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xb26ad9e in /opt/byconity/usr/bin/clickhouse
6. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0xb26cca4 in /opt/byconity/usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb267a3f in /opt/byconity/usr/bin/clickhouse
8. ? @ 0xb26bd1a in /opt/byconity/usr/bin/clickhouse
9. start_thread @ 0x7fa3 in /lib/x86_64-linux-gnu/libpthread-2.28.so
10. clone @ 0xf906f in /lib/x86_64-linux-gnu/libc-2.28.so
 (version 21.8.7.1)
2023.01.13 10:27:54.104712 [ 205 ] {} <Error> system.query_log (09ce3590-8eb7-4dca-aa17-3f475cfbb795): Detaching broken part /var/byconity/data/store/09c/09ce3590-8eb7-4dca-aa17-3f475cfbb795/20230113_20230113_507_507_0. If it happened after update, it is likely because of backward incompability. You need to resolve this manually
2023.01.13 10:27:54.104728 [ 206 ] {} <Error> system.query_log (09ce3590-8eb7-4dca-aa17-3f475cfbb795): Detaching broken part /var/byconity/data/store/09c/09ce3590-8eb7-4dca-aa17-3f475cfbb795/20230113_20230113_1_539_108. If it happened after update, it is likely because of backward incompability. You need to resolve this manually
2023.01.13 10:27:54.105022 [ 204 ] {} <Error> auto DB::MergeTreeData::loadPartsFromFileSystem(DB::MergeTreeData::PartNamesWithDisks, DB::MergeTreeData::PartNamesWithDisks, bool, DB::MergeTreeMetaBase::DataPartsLock &)::(anonymous class)::operator()() const: Code: 246, e.displayText() = DB::Exception: While loading part /var/byconity/data/store/09c/09ce3590-8eb7-4dca-aa17-3f475cfbb795/20230113_20230113_514_514_0/: calculated partition ID: 19850803 differs from partition ID in part name: 202301 SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18e345d2 in /opt/byconity/usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb230820 in /opt/byconity/usr/bin/clickhouse
2. DB::IMergeTreeDataPart::loadPartitionAndMinMaxIndex() @ 0x14914689 in /opt/byconity/usr/bin/clickhouse
3. DB::IMergeTreeDataPart::loadColumnsChecksumsIndexes(bool, bool) @ 0x14911473 in /opt/byconity/usr/bin/clickhouse
4. ? @ 0x149988d8 in /opt/byconity/usr/bin/clickhouse
5. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xb26ad9e in /opt/byconity/usr/bin/clickhouse
6. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0xb26cca4 in /opt/byconity/usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb267a3f in /opt/byconity/usr/bin/clickhouse
8. ? @ 0xb26bd1a in /opt/byconity/usr/bin/clickhouse
9. start_thread @ 0x7fa3 in /lib/x86_64-linux-gnu/libpthread-2.28.so
10. clone @ 0xf906f in /lib/x86_64-linux-gnu/libc-2.28.so
 (version 21.8.7.1)
2023.01.13 10:27:54.105076 [ 204 ] {} <Error> system.query_log (09ce3590-8eb7-4dca-aa17-3f475cfbb795): Detaching broken part /var/byconity/data/store/09c/09ce3590-8eb7-4dca-aa17-3f475cfbb795/20230113_20230113_514_514_0. If it happened after update, it is likely because of backward incompability. You need to resolve this manually
2023.01.13 10:27:54.106491 [ 205 ] {} <Error> auto DB::MergeTreeData::loadPartsFromFileSystem(DB::MergeTreeData::PartNamesWithDisks, DB::MergeTreeData::PartNamesWithDisks, bool, DB::MergeTreeMetaBase::DataPartsLock &)::(anonymous class)::operator()() const: Code: 246, e.displayText() = DB::Exception: While loading part /var/byconity/data/store/09c/09ce3590-8eb7-4dca-aa17-3f475cfbb795/20230113_20230113_515_515_0/: calculated partition ID: 19850803 differs from partition ID in part name: 202301 SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18e345d2 in /opt/byconity/usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb230820 in /opt/byconity/usr/bin/clickhouse
2. DB::IMergeTreeDataPart::loadPartitionAndMinMaxIndex() @ 0x14914689 in /opt/byconity/usr/bin/clickhouse
3. DB::IMergeTreeDataPart::loadColumnsChecksumsIndexes(bool, bool) @ 0x14911473 in /opt/byconity/usr/bin/clickhouse
4. ? @ 0x149988d8 in /opt/byconity/usr/bin/clickhouse
5. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xb26ad9e in /opt/byconity/usr/bin/clickhouse
6. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0xb26cca4 in /opt/byconity/usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb267a3f in /opt/byconity/usr/bin/clickhouse
8. ? @ 0xb26bd1a in /opt/byconity/usr/bin/clickhouse
9. start_thread @ 0x7fa3 in /lib/x86_64-linux-gnu/libpthread-2.28.so
10. clone @ 0xf906f in /lib/x86_64-linux-gnu/libc-2.28.so
 (version 21.8.7.1)
2023.01.13 10:27:54.106528 [ 205 ] {} <Error> system.query_log (09ce3590-8eb7-4dca-aa17-3f475cfbb795): Detaching broken part /var/byconity/data/store/09c/09ce3590-8eb7-4dca-aa17-3f475cfbb795/20230113_20230113_515_515_0. If it happened after update, it is likely because of backward incompability. You need to resolve this manually
2023.01.13 10:27:54.108316 [ 205 ] {} <Error> auto DB::MergeTreeData::loadPartsFromFileSystem(DB::MergeTreeData::PartNamesWithDisks, DB::MergeTreeData::PartNamesWithDisks, bool, DB::MergeTreeMetaBase::DataPartsLock &)::(anonymous class)::operator()() const: Code: 246, e.displayText() = DB::Exception: While loading part /var/byconity/data/store/09c/09ce3590-8eb7-4dca-aa17-3f475cfbb795/20230113_20230113_523_523_0/: calculated partition ID: 19850803 differs from partition ID in part name: 202301 SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):
0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18e345d2 in /opt/byconity/usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb230820 in /opt/byconity/usr/bin/clickhouse
2. DB::IMergeTreeDataPart::loadPartitionAndMinMaxIndex() @ 0x14914689 in /opt/byconity/usr/bin/clickhouse
3. DB::IMergeTreeDataPart::loadColumnsChecksumsIndexes(bool, bool) @ 0x14911473 in /opt/byconity/usr/bin/clickhouse
4. ? @ 0x149988d8 in /opt/byconity/usr/bin/clickhouse
5. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xb26ad9e in /opt/byconity/usr/bin/clickhouse
6. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0xb26cca4 in /opt/byconity/usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb267a3f in /opt/byconity/usr/bin/clickhouse
8. ? @ 0xb26bd1a in /opt/byconity/usr/bin/clickhouse
9. start_thread @ 0x7fa3 in /lib/x86_64-linux-gnu/libpthread-2.28.so
10. clone @ 0xf906f in /lib/x86_64-linux-gnu/libc-2.28.so
 (version 21.8.7.1)
2023.01.13 10:27:54.108344 [ 205 ] {} <Error> system.query_log (09ce3590-8eb7-4dca-aa17-3f475cfbb795): Detaching broken part /var/byconity/data/store/09c/09ce3590-8eb7-4dca-aa17-3f475cfbb795/20230113_20230113_523_523_0. If it happened after update, it is likely because of backward incompability. You need to resolve this manually
2023.01.13 10:27:54.109351 [ 207 ] {} <Error> auto DB::MergeTreeData::loadPartsFromFileSystem(DB::MergeTreeData::PartNamesWithDisks, DB::MergeTreeData::PartNamesWithDisks, bool, DB::MergeTreeMetaBase::DataPartsLock &)::(anonymous class)::operator()() const: Code: 246, e.displayText() = DB::Exception: While loading part /var/byconity/data/store/09c/09ce3590-8eb7-4dca-aa17-3f475cfbb795/20230113_20230113_505_505_0/: calculated partition ID: 19850803 differs from partition ID in part name: 202301 SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18e345d2 in /opt/byconity/usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb230820 in /opt/byconity/usr/bin/clickhouse

**Comment by hustnn** [comment]
how did you start it? From binary or with our docker script?

**Comment by zhbdesign** [comment]
docker script

**Comment by hustnn** [comment]
How to reproduce it?

**Comment by zhbdesign** [comment]
delete all contain ，docker-compose up -d，run some insert sql，restart

**Comment by zhbdesign** [comment]
sql:
CREATE DATABASE test;
CREATE TABLE test.events (`id` UInt64, `s` String) ENGINE = CnchMergeTree ORDER BY id;
INSERT INTO test.events SELECT number, toString(number) FROM numbers(10);
SELECT * FROM test.events ORDER BY id;

**Comment by kevinthfang** [comment]
unable to reproduce your error. could you start with a clean environment and record each steps? Also include, what's your system, linux, windows, or Mac? Are you using docker desktop, docker-machine or colima? what's the vm size ? (cpu, memory, etc)

**Comment by zhbdesign** [comment]
> unable to reproduce your error. could you start with a clean environment and record each steps? Also include, what's your system, linux, windows, or Mac? Are you using docker desktop, docker-machine or colima? what's the vm size ? (cpu, memory, etc)

creata table， insert some data， restart

**Comment by zhbdesign** [comment]
linux，docker-machine ，4cpu，16G

**Comment by zhbdesign** [comment]
For a clean environment, run sudo docker-compose up -d, sudo docker stop $(sudo docker ps -a -q), and sudo docker-compose up -d

**Comment by kevinthfang** [comment]
Unable to reproduce with debian 9.13 and docker 19.03.15. Please check if you miss any steps in https://github.com/ByConity/byconity-docker.
