### ISSUE TITLE
配置了kerberos之后不生效

### ISSUE THREAD

**Issue by inewzone** [ByConity/ByConity#346]
(you don't have to strictly follow this form)

## Bug Report
在byconity-server.xml 、byconity-worker.xml、byconity-worker-writer.xml 配置了 kerberos 不生效
![image](https://github.com/ByConity/ByConity/assets/7139504/520f6647-d4d7-4d16-a351-5dcc7eee756a)

### Briefly describe the bug

![image](https://github.com/ByConity/ByConity/assets/7139504/a211dbd0-679c-4e9b-aeb8-bfbaebd17f78)

### Version
发布的release的 byconity-server-0.1.0.x86_64.rpm

**Comment by dmthuc** [comment]
Hi @wordhardqi , could you help to take a look at this?

**Comment by white-cc** [comment]
please check your hdfs3.xml，If you are not sure, please keep the configuration consistent with HDFS configuration.
and add
```
<property>
    <name>dfs.use.internal.credential.format</name>
    <value>false</value>
</property>
```
```
add conf in hdfs3.xml like 
<property>
    <name>hadoop.security.authentication</name>
    <value>KERBEROS</value>
</property>
<property>
    <name>dfs.use.internal.credential.format</name>
    <value>false</value>
</property>
<property>
    <name>dfs.data.transfer.protection</name>
    <value>authentication</value>
</property>
<property>
    <name>dfs.block.access.token.enable</name>
    <value>true</value>
</property>
```

**Comment by inewzone** [comment]
ok，thanks，Is it enough to add the hdfs3. xml file to the/etc/bicity/directory and add the configuration you just sent？

**Comment by inewzone** [comment]
> please check your hdfs3.xml，If you are not sure, please keep the configuration consistent with HDFS configuration. and add
> 
> ```
> <property>
>     <name>dfs.use.internal.credential.format</name>
>     <value>false</value>
> </property>
> ```
> 
> ```
> add conf in hdfs3.xml like 
> <property>
>     <name>hadoop.security.authentication</name>
>     <value>KERBEROS</value>
> </property>
> <property>
>     <name>dfs.use.internal.credential.format</name>
>     <value>false</value>
> </property>
> <property>
>     <name>dfs.data.transfer.protection</name>
>     <value>authentication</value>
> </property>
> <property>
>     <name>dfs.block.access.token.enable</name>
>     <value>true</value>
> </property>
> ```

ok，thanks，Is it enough to add the hdfs3. xml file to the/etc/bicity/directory and add the configuration you just sent？

**Comment by white-cc** [comment]
> ok，thanks，Is it enough to add the hdfs3. xml file to the/etc/bicity/directory and add the configuration you just sent？

You also need to modify libhdfs3_config path to your hdfs3.xml abd keep the configuration consistent with HDFS configuration. And add 
```
<property> <name>dfs.use.internal.credential.format</name> 
<value>false</value>
 </property>
```
in your hdfs3.xml

**Comment by inewzone** [comment]
> dfs.use.internal.credential.format

Just now, I tried and still reported an error. I configured the content you just sent on the HDFS of CDH

**Comment by linkwk7** [comment]
Hi, can you enable trace log in worker by set yandex.logger.level to trace in configuration file and paste the entire log for query here by `grep {query_id} byconity-worker.log`

**Comment by linkwk7** [comment]
btw, in byconity, the config key for libhdfs3.xml is yandex.hdfs3_config rather than yandex.libhdfs3_config. can you change the config key and retry again?

**Comment by inewzone** [comment]
> logger.level to trace

![image](https://github.com/ByConity/ByConity/assets/7139504/a84cdefe-bb9d-4fd4-91d7-44e1b5feaa56)
![image](https://github.com/ByConity/ByConity/assets/7139504/8aa87943-b018-41cc-a011-902e0038c50e)

I have tried it according to your request, but it still doesn’t work. I don’t know what is wrong with me.

**Comment by inewzone** [comment]
> btw, in byconity, the config key for libhdfs3.xml is yandex.hdfs3_config rather than yandex.libhdfs3_config. can you change the config key and retry again?
thanks ,The problem is finally solved, I didn't notice, the label hdfs_conf of the configuration file needs to be changed to hdfs_config

**Comment by inewzone** [comment]
> > btw, in byconity, the config key for libhdfs3.xml is yandex.hdfs3_config rather than yandex.libhdfs3_config. can you change the config key and retry again?
> > thanks ,The problem is finally solved, I didn't notice, the label hdfs_conf of the configuration file needs to be changed to hdfs_config

![image](https://github.com/ByConity/ByConity/assets/7139504/a391026b-3b39-4ee1-94c7-472c8cb3df75)

**Comment by xingcici** [comment]
> 

Hi, did you solve the problem ?
