### ISSUE TITLE
`lru_max_size` config doesn't work: the `auxility_store` folder is too large when inserting large amounts of data

### ISSUE THREAD

**Issue by xiaomo728** [ByConity/ByConity#404]
We found this issue when inserting data into ByConity. 
When inserting large amounts of data, the `auxility_store` directory of clickhouse-worker would generate a plenty of temporary data, which would eventually fill up the disk and cause an exception.

In order to solve this problem, we consulted the documentation and used the recommended configuration item: `lru_max_size`

However, it seems that this config does not work at all...
When we configure `lru_max_size` as `12G`, `auxility_store` reaches over `700G` and `disk_cache_v1` reaches over `1.1G`;
when we configure `lru_max_size` as `0.5G` and inserting more data, `auxility_store` can also reach over `1.6T`; `disk_cache_v1` reaches over `553M`...

The following are my questions:
1. Is there an available configuration item that can limit the size of the `auxility_store` folder?
2. `lru_max_size` - does this configuration item really work? What is helped by it?

Thank you very much.

**Comment by hustnn** [comment]
Similar to issue https://github.com/ByConity/ByConity/issues/458%EF%BC%9F， the disk space is too small
