### ISSUE TITLE
配置hdfs的短读快，但是不生效

### ISSUE THREAD

**Issue by inewzone** [ByConity/ByConity#407]
(you don't have to strictly follow this form)
配置了hdfs 的short-circuit，设置了为true不生效
## Question
![image](https://github.com/ByConity/ByConity/assets/7139504/3c4e32ca-1afe-4381-845c-fe82db10424b)

![image](https://github.com/ByConity/ByConity/assets/7139504/34acb55b-2d77-41f1-9bc8-6d0a66bc0e8a)

**Comment by wordhardqi** [comment]
could u check the existence of /var/run/hdfs-sockets/dn

**Comment by inewzone** [comment]
The directory and files exist here, you can take a look at my screenshot for details, so I am curious why such a problem occurs
![image](https://github.com/ByConity/ByConity/assets/7139504/032efcd1-94e0-4fcc-b8e7-31429e2259af)

**Comment by inewzone** [comment]
> The directory and files exist here, you can take a look at my screenshot for details, so I am curious why such a problem occurs

![image](https://github.com/ByConity/ByConity/assets/7139504/428a404f-4e57-4e51-b6a3-86289b1e5381)

**Comment by inewzone** [comment]
> could u check the existence of /var/run/hdfs-sockets/dn

The directory and files exist here, you can take a look at my screenshot for details, so I am curious why such a problem occurs

![image](https://github.com/ByConity/ByConity/assets/7139504/1682436d-5e43-4da3-8a55-d203e22e520d)

**Comment by wordhardqi** [comment]
the problem indicates that the client has some issues using this domain socket. 
we can try write a small hdfs program and run on that node to debug.

**Comment by kevinthfang** [comment]
Resolved and no further questions.
