### ISSUE TITLE
Create CnchHive table engine error

### ISSUE THREAD

**Issue by inewzone** [ByConity/ByConity#415]
创建hive的表引擎报错，下面是我的错误列表

通过client创建表的报的错误信息
![image](https://github.com/ByConity/ByConity/assets/7139504/659c0d8f-561b-4fa5-9ea7-54a1331fd45e)
server日志报的错误信息
![image](https://github.com/ByConity/ByConity/assets/7139504/4a6b50f4-a79c-42eb-a299-a117f2d57204)

hive的创表语句：
![image](https://github.com/ByConity/ByConity/assets/7139504/930cbdd1-bd5e-4330-8013-1e7121f5796d)

server conf的配置文件

![image](https://github.com/ByConity/ByConity/assets/7139504/0ccedf75-8eb0-4592-ad1d-469458eeb0df)

**Comment by inewzone** [comment]
> Can you try Int64 for hive data type BigInt? The error message is ambiguous. We will release the feature of hive schema inference soon.

我这边改了没有生效，是否是认证没有配置对呢？
![image](https://github.com/ByConity/ByConity/assets/7139504/1287e85f-fb23-49c1-90a0-8f03cf4e721b)
是否没有正常与元数据建立连接呢

**Comment by hustnn** [comment]
> 我这边改了没有生效，是否是认证没有配置对呢？

改用Int64之后是什么报错呢？

**Comment by wordhardqi** [comment]
the connection to HMS should be normal.

**Comment by wordhardqi** [comment]
@inewzone could u share the hive schema and the cnch schema in text?

**Comment by inewzone** [comment]
> > 我这边改了没有生效，是否是认证没有配置对呢？
> 
> 改用Int64之后是什么报错呢？

一样错误，没什么变化
![image](https://github.com/ByConity/ByConity/assets/7139504/a8872f3a-abf3-4288-81fb-6b33db04fb66)
![image](https://github.com/ByConity/ByConity/assets/7139504/7944b32b-bd5e-4230-9a91-033777e980eb)

**Comment by inewzone** [comment]
> @inewzone could u share the hive schema and the cnch schema in text?

你好，上面有hive与cnchhive的创表语句

**Comment by hustnn** [comment]
@inewzone 你们用的ByConity哪个版本？

**Comment by inewzone** [comment]
> @hustnn 我们这边用的是0.1-ga release的rpm在物理机上安装的

**Comment by wordhardqi** [comment]
try Nullable(Int64)

**Comment by kevinthfang** [comment]
Resolved and no further questions.
