### ISSUE TITLE
Cannot lock file status, Another server instance in the same directory is already running

### ISSUE THREAD

**Issue by liby888** [ByConity/ByConity#416]
During the containerization of workers, the hostpath mode is used to mount the cache directory. When the pods of multiple workers are started on the same node, the message "cannot lock file status, Another server instance in the same directory is already running" is displayed. I would like to ask how I should mount the cache directory of the worker.

**Comment by dmthuc** [comment]
Hi @liby888 , thank you for reporting bug. May I ask if you are deploying using k8s?

**Comment by hustnn** [comment]
> During the containerization of workers, the hostpath mode is used to mount the cache directory. When the pods of multiple workers are started on the same node, the message "cannot lock file status, Another server instance in the same directory is already running" is displayed. I would like to ask how I should mount the cache directory of the worker.

when you config multiple workers in the same node, you need to config different local path for different workers such as read-worker1, read-worker2, write-worker1 and more

**Comment by hustnn** [comment]
@liby888 Is it working now?

**Comment by liby888** [comment]
This is OK, but for now, we're trying to set anti-affinity so that only one writer-worker and default-worker are enabled for each node. If you have best practices, you can synchronize them to us.

> @利比888现在起作用了吗？

**Comment by hustnn** [comment]
> This is OK, but for now, we're trying to set anti-affinity so that only one writer-worker and default-worker are enabled for each node. If you have best practices, you can synchronize them to us.
> 
> > @利比888现在起作用了吗？

in k8s, if so, you can use label to set anti-affinity.

**Comment by hustnn** [comment]
hi @liby888 any more question for this issue?

**Comment by liby888** [comment]
> 嗨@利比888这个问题还有什么问题吗？

没问题了，感谢

**Comment by serenallttyy** [comment]
hello你好👋请问在关注ByConity社区吗，感兴趣的话可以加我们的交流群沟通下

<img width="117" alt="小助手二维码（新）" src="https://github.com/ByConity/ByConity/assets/88301094/0934366c-0061-40e0-8c24-f148aa8d6859">
