### ISSUE TITLE
TPC-DS tests import data failed

### ISSUE THREAD

**Issue by yanggang2019** [ByConity/ByConity#417]
(you don't have to strictly follow this form)

## Question
我采用docker一键式部署byconity，采用TPC-DS采集集验证byconity和clickhouse的性能，在单节点情况下，byconity导入20G的TPC-DS测试数据集报错信息如下（导入10G的数据没有问题，ClickHouse导入相同的数据也没问题），请问应当怎么修复?

I use Docker to deploy byconity in one-click mode, and use the TPC-DS collection set to verify the performance of byconity and clickhouse. When a single node is used, the following error information is displayed when a 20 GB TPC-DS test data set is imported to byconity:(I only can import 10 GB data to Byconity and ClickHouse can import 20GB data succ). How can I fix it?

![image](https://github.com/ByConity/ByConity/assets/43461382/536452bd-53f8-4ff4-bcc2-9f02532d2b90)

**Comment by dmthuc** [comment]
Hi @yanggang2019 , may I know which docker repo you are using?

**Comment by yanggang2019** [comment]
use docker-compose from https://github.com/ByConity/byconity-docker/blob/public/docker-compose.yml

----------------------------------------------------------------
version: "3"
services:
# hdfs / remote fs
  hdfs:
    image: gchq/hdfs:3.3
    command: namenode
    container_name: hdfs-namenode
    environment:
      - HADOOP_CONF_DIR=/etc/hadoop/conf
    ports:
      - 9870:9870
    volumes:
      - /usr1/yg/byconity-docker-public/hdfs:/etc/hadoop/conf:ro
      - /var/log/hadoop
      - /data1
      - /data2

  hdfs-datanode:
    depends_on:
      - hdfs
    image: gchq/hdfs:3.3
    command: datanode
    container_name: hdfs-datanode
    environment:
      - HADOOP_CONF_DIR=/etc/hadoop/conf
    volumes:
      - /usr1/yg/byconity-docker-public/hdfs:/etc/hadoop/conf:ro
      - /var/log/hadoop
      - ./data1:/data1
      - ./data2:/data2

# foundation db / catalog
  fdb:
    image: foundationdb/foundationdb:7.1.24
    ports:
      - "4550:4550"
    environment:
      FDB_NETWORKING_MODE: container
      FDB_COORDINATOR_PORT: 4550
      FDB_PORT: 4550
    container_name: fdb-0

# byconity:
  tso:
    image: byconity/byconity:0.1.0-GA
    command: bash -c "fdbcli -C /config/fdb.cluster --exec \"configure new single ssd\"; tso-server --config-file /config/tso.yml"
    depends_on:
      - fdb
      - hdfs
    volumes:
      - "./byconity-simple-cluster/:/config/:ro"
    # evironment:
    container_name: tso-0
    healthcheck:
      test:
        - CMD
        - curl
        - "tso-0:18845/status"
      interval: 10s
      timeout: 5s
      retries: 5
    cap_add:
      - SYS_PTRACE

  server:
    image: byconity/byconity:0.1.0-GA
    command: bash -c "curl --retry 10 --retry-delay 5 --retry-connrefused --retry-max-time 120 --max-time 120 tso-0:18845/status && clickhouse-server --config-file /config/server.yml"
    depends_on:
      - tso
      - hdfs
    ports:
      - "9000:52145"
      - "8123:21557"
    container_name: server-0
    volumes:
      - "./byconity-simple-cluster/:/config/:ro"
    healthcheck:
      test:
        - CMD
        - curl
        - "server-0:21557/?query=SELECT%201"
      interval: 10s
      timeout: 5s
      retries: 5
    cap_add:
      - SYS_PTRACE

  worker-write:
    image: byconity/byconity:0.1.0-GA
    command: bash -c "curl --retry 10 --retry-delay 5 --retry-connrefused --retry-max-time 120 --max-time 120 server-0:21557 && clickhouse-server --config-file /config/worker.yml"
    depends_on:
      - server
    container_name: worker-write-0
    volumes:
      - "./byconity-simple-cluster/:/config/:ro"
    healthcheck:
      test:
        - CMD
        - curl
        - "worker-write-0:21557/?query=SELECT%201"
      interval: 10s
      timeout: 5s
      retries: 5
    cap_add:
      - SYS_PTRACE

  worker-default:
    image: byconity/byconity:0.1.0-GA
    command: bash -c "curl --retry 10 --retry-delay 5 --retry-connrefused --retry-max-time 120 --max-time 120 server-0:21557 && clickhouse-server --config-file /config/worker.yml"
    depends_on:
      - server
    container_name: worker-default-0
    volumes:
      - "./byconity-simple-cluster/:/config/:ro"
    healthcheck:
      test:
        - CMD
        - curl
        - "worker-default-0:21557/?query=SELECT%201"
      interval: 10s
      timeout: 5s
      retries: 5
    cap_add:
      - SYS_PTRACE

  daemon-manager:
    image: byconity/byconity:0.1.0-GA
    command: bash -c "curl --retry 10 --retry-delay 5 --retry-connrefused --retry-max-time 120 --max-time 120 server-0:21557 && daemon-manager --config-file ./config/daemon-manager.yml"
    depends_on:
      - server
    container_name: daemon-manager-0
    volumes:
      - "./byconity-simple-cluster/:/config/:ro"
    healthcheck:
      test:
        - CMD
        - curl
        - "daemon-manager-0:17553/status"
      interval: 10s
      timeout: 5s
      retries: 5
    cap_add:
      - SYS_PTRACE

**Comment by yanggang2019** [comment]
> Hi @yanggang2019 , may I know which docker repo you are using?

use docker-compose from https://github.com/ByConity/byconity-docker/blob/public/docker-compose.yml

**Comment by yanggang2019** [comment]
> Hi @yanggang2019 , may I know which docker repo you are using?

**Comment by yanggang2019** [comment]
我今天使用ssb测试集测试byconity性能，导入数据的时候也依然报错，提示如下：
![image](https://github.com/ByConity/ByConity/assets/43461382/d0420833-4b99-457e-a5fc-5e810d8b8554)

同时，通过客户端命令clickhouse client 连接进入，执行SQL报错如下：
![image](https://github.com/ByConity/ByConity/assets/43461382/2b2e8cdb-f494-4e24-a8c5-7249dba11aa5)

查看/var/byconity/out.log日志，报错堆栈如下：
![image](https://github.com/ByConity/ByConity/assets/43461382/39cde861-f5ce-4770-9ddc-bc6e6eafa5ee)

![image](https://github.com/ByConity/ByConity/assets/43461382/5bbd8467-1fc6-4788-b86f-e2d0487bd91f)

**Comment by hustnn** [comment]
@yanggang2019 looks like the issue related to fdb，where env （os）are you using？

**Comment by yanggang2019** [comment]
@hustnn 
Huawei EulerOS：
![image](https://github.com/ByConity/ByConity/assets/43461382/21f1ed2e-faf9-40a3-a629-d6978b610d1b)

**Comment by hustnn** [comment]
looks like your FDB is slow, can you refer this doc to deploy in physical mode? https://byconity.github.io/zh-cn/docs/deployment/package-deployment

**Comment by dmthuc** [comment]
Hi @yanggang2019 , we have some fixed but we haven't release docker image yet. For testing performance, I would like to suggest you to try docker executable wrapper or deployed using package into physical machine. https://github.com/ByConity/ByConity/tree/master/docker/executable_wrapper

**Comment by dmthuc** [comment]
> hi @dmthuc ，what is the fix you mentioned here？

The fix here https://github.com/ByConity/ByConity/pull/399
