### ISSUE TITLE
Error when querying `SHOW CREATE TABLE` on system table

### ISSUE THREAD

**Issue by xiaomo728** [ByConity/ByConity#422]
SHOW CREATE TABLE system.events;

```
Received exception from server (version 21.8.7):
Code: 107. DB::Exception: Received from xxx.xxx.xxx.xxx:pppp. DB::Exception: Cannot open file /xx/xx/xxxx/clickhouse-server/server/store/dca/dcab689e-2871-4b9b-9e46-5b8af5864572/events.sql, errno: 2, strerror: No such file or directory SQLSTATE: 58030. 
```

**Comment by vivek-debug** [comment]
> Code: 107. DB::Exception: Received from xxx.xxx.xxx.xxx:pppp. DB::Exception: Cannot open file /xx/xx/xxxx/clickhouse-server/server/store/dca/dcab689e-2871-4b9b-9e46-5b8af5864572/events.sql, errno: 2, strerror: No such file or directory SQLSTATE: 58030. 

it seems like I do not get this error on my local development and docker deployment. @xiaomo728 Can you try this again on the latest version of the master branch?

**Comment by kevinthfang** [comment]
Can not reproduce it. Please reopen it if you reproduce in the new version.
