### ISSUE TITLE
Run create stats if not exists all; Cause server crash

### ISSUE THREAD

**Issue by zhbdesign** [ByConity/ByConity#43]
log：
2023.01.16 08:30:54.874708 [ 41799 ] {} <Fatal> BaseDaemon: ########################################
2023.01.16 08:30:54.874809 [ 41799 ] {} <Fatal> BaseDaemon: (version 21.8.7.1 scm cdw-2.0.0/2.0.0.115, build id: B1C8E2A14E2DBD1E5587FAA6B806FACBBA832810) (from thread 8930) (query_id: 598756cf-d1a5-485e-960c-a295a62a8bca) Received signal Segmentation fault (11)
2023.01.16 08:30:54.874870 [ 41799 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
2023.01.16 08:30:54.874924 [ 41799 ] {} <Fatal> BaseDaemon: Stack trace: 0x14c9be30 0x14c9b8a5 0x14cd8036 0xb26ad9e 0xb26cca4 0xb267a3f 0xb26bd1a 0x7fc1a8e5efa3 0x7fc1a787d06f
2023.01.16 08:30:54.875085 [ 41799 ] {} <Fatal> BaseDaemon: 3. DB::IRowOutputFormat::write(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > const&, unsigned long) @ 0x14c9be30 in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:30:54.875146 [ 41799 ] {} <Fatal> BaseDaemon: 4. DB::IRowOutputFormat::consume(DB::Chunk) @ 0x14c9b8a5 in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:30:54.875299 [ 41799 ] {} <Fatal> BaseDaemon: 5. DB::ParallelFormattingOutputFormat::formatterThreadFunction(unsigned long, std::__1::shared_ptr<DB::ThreadGroupStatus> const&) @ 0x14cd8036 in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:30:54.875389 [ 41799 ] {} <Fatal> BaseDaemon: 6. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xb26ad9e in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:30:54.875486 [ 41799 ] {} <Fatal> BaseDaemon: 7. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0xb26cca4 in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:30:54.875543 [ 41799 ] {} <Fatal> BaseDaemon: 8. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb267a3f in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:30:54.875599 [ 41799 ] {} <Fatal> BaseDaemon: 9. ? @ 0xb26bd1a in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:30:54.875662 [ 41799 ] {} <Fatal> BaseDaemon: 10. start_thread @ 0x7fa3 in /lib/x86_64-linux-gnu/libpthread-2.28.so
2023.01.16 08:30:54.875721 [ 41799 ] {} <Fatal> BaseDaemon: 11. clone @ 0xf906f in /lib/x86_64-linux-gnu/libc-2.28.so
2023.01.16 08:30:55.018096 [ 41800 ] {} <Fatal> BaseDaemon: ########################################
2023.01.16 08:30:55.018144 [ 41800 ] {} <Fatal> BaseDaemon: (version 21.8.7.1 scm cdw-2.0.0/2.0.0.115, build id: B1C8E2A14E2DBD1E5587FAA6B806FACBBA832810) (from thread 61835) (query_id: 598756cf-d1a5-485e-960c-a295a62a8bca) Received signal Segmentation fault (11)
2023.01.16 08:30:55.018192 [ 41800 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
2023.01.16 08:30:55.018225 [ 41800 ] {} <Fatal> BaseDaemon: Stack trace: 0x14c9be30 0x14c9b8a5 0x14cd8036 0xb26ad9e 0xb26cca4 0xb267a3f 0xb26bd1a 0x7fc1a8e5efa3 0x7fc1a787d06f
2023.01.16 08:30:55.018291 [ 41800 ] {} <Fatal> BaseDaemon: 3. DB::IRowOutputFormat::write(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > const&, unsigned long) @ 0x14c9be30 in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:30:55.018348 [ 41800 ] {} <Fatal> BaseDaemon: 4. DB::IRowOutputFormat::consume(DB::Chunk) @ 0x14c9b8a5 in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:30:55.018374 [ 41800 ] {} <Fatal> BaseDaemon: 5. DB::ParallelFormattingOutputFormat::formatterThreadFunction(unsigned long, std::__1::shared_ptr<DB::ThreadGroupStatus> const&) @ 0x14cd8036 in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:30:55.018439 [ 41800 ] {} <Fatal> BaseDaemon: 6. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xb26ad9e in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:30:55.018531 [ 41800 ] {} <Fatal> BaseDaemon: 7. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0xb26cca4 in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:30:55.018554 [ 41800 ] {} <Fatal> BaseDaemon: 8. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb267a3f in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:30:55.018579 [ 41800 ] {} <Fatal> BaseDaemon: 9. ? @ 0xb26bd1a in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:30:55.018644 [ 41800 ] {} <Fatal> BaseDaemon: 10. start_thread @ 0x7fa3 in /lib/x86_64-linux-gnu/libpthread-2.28.so
2023.01.16 08:30:55.018671 [ 41800 ] {} <Fatal> BaseDaemon: 11. clone @ 0xf906f in /lib/x86_64-linux-gnu/libc-2.28.so
2023.01.16 08:30:55.091275 [ 41799 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: 7B0734FCB0DE0271D880B340784BCEDA. There is no information about the reference checksum.
2023.01.16 08:30:55.141027 [ 41801 ] {} <Fatal> BaseDaemon: ########################################
2023.01.16 08:30:55.141116 [ 41801 ] {} <Fatal> BaseDaemon: (version 21.8.7.1 scm cdw-2.0.0/2.0.0.115, build id: B1C8E2A14E2DBD1E5587FAA6B806FACBBA832810) (from thread 8518) (query_id: 598756cf-d1a5-485e-960c-a295a62a8bca) Received signal Segmentation fault (11)
2023.01.16 08:30:55.141211 [ 41801 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
2023.01.16 08:30:55.141277 [ 41801 ] {} <Fatal> BaseDaemon: Stack trace: 0x14c9be30 0x14c9b8a5 0x14cd8036 0xb26ad9e 0xb26cca4 0xb267a3f 0xb26bd1a 0x7fc1a8e5efa3 0x7fc1a787d06f
2023.01.16 08:30:55.141393 [ 41801 ] {} <Fatal> BaseDaemon: 3. DB::IRowOutputFormat::write(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > const&, unsigned long) @ 0x14c9be30 in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:30:55.141448 [ 41801 ] {} <Fatal> BaseDaemon: 4. DB::IRowOutputFormat::consume(DB::Chunk) @ 0x14c9b8a5 in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:30:55.141511 [ 41801 ] {} <Fatal> BaseDaemon: 5. DB::ParallelFormattingOutputFormat::formatterThreadFunction(unsigned long, std::__1::shared_ptr<DB::ThreadGroupStatus> const&) @ 0x14cd8036 in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:30:55.141575 [ 41801 ] {} <Fatal> BaseDaemon: 6. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xb26ad9e in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:30:55.141687 [ 41801 ] {} <Fatal> BaseDaemon: 7. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0xb26cca4 in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:30:55.141764 [ 41801 ] {} <Fatal> BaseDaemon: 8. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb267a3f in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:30:55.141816 [ 41801 ] {} <Fatal> BaseDaemon: 9. ? @ 0xb26bd1a in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:30:55.141905 [ 41801 ] {} <Fatal> BaseDaemon: 10. start_thread @ 0x7fa3 in /lib/x86_64-linux-gnu/libpthread-2.28.so
2023.01.16 08:30:55.141965 [ 41801 ] {} <Fatal> BaseDaemon: 11. clone @ 0xf906f in /lib/x86_64-linux-gnu/libc-2.28.so
2023.01.16 08:30:55.216678 [ 41800 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: 7B0734FCB0DE0271D880B340784BCEDA. There is no information about the reference checksum.
2023.01.16 08:30:55.259437 [ 41802 ] {} <Fatal> BaseDaemon: ########################################
2023.01.16 08:30:55.259563 [ 41802 ] {} <Fatal> BaseDaemon: (version 21.8.7.1 scm cdw-2.0.0/2.0.0.115, build id: B1C8E2A14E2DBD1E5587FAA6B806FACBBA832810) (from thread 691) (query_id: 598756cf-d1a5-485e-960c-a295a62a8bca) Received signal Segmentation fault (11)
2023.01.16 08:30:55.259629 [ 41802 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Address not mapped to object.
2023.01.16 08:30:55.259684 [ 41802 ] {} <Fatal> BaseDaemon: Stack trace: 0x14c9be30 0x14c9b8a5 0x14cd8036 0xb26ad9e 0xb26cca4 0xb267a3f 0xb26bd1a 0x7fc1a8e5efa3 0x7fc1a787d06f
2023.01.16 08:30:55.259803 [ 41802 ] {} <Fatal> BaseDaemon: 3. DB::IRowOutputFormat::write(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > const&, unsigned long) @ 0x14c9be30 in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:30:55.259865 [ 41802 ] {} <Fatal> BaseDaemon: 4. DB::IRowOutputFormat::consume(DB::Chunk) @ 0x14c9b8a5 in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:30:55.259929 [ 41802 ] {} <Fatal> BaseDaemon: 5. DB::ParallelFormattingOutputFormat::formatterThreadFunction(unsigned long, std::__1::shared_ptr<DB::ThreadGroupStatus> const&) @ 0x14cd8036 in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:30:55.259991 [ 41802 ] {} <Fatal> BaseDaemon: 6. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xb26ad9e in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:30:55.260063 [ 41802 ] {} <Fatal> BaseDaemon: 7. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0xb26cca4 in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:30:55.260126 [ 41802 ] {} <Fatal> BaseDaemon: 8. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb267a3f in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:30:55.260231 [ 41802 ] {} <Fatal> BaseDaemon: 9. ? @ 0xb26bd1a in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:30:55.260302 [ 41802 ] {} <Fatal> BaseDaemon: 10. start_thread @ 0x7fa3 in /lib/x86_64-linux-gnu/libpthread-2.28.so
2023.01.16 08:30:55.260362 [ 41802 ] {} <Fatal> BaseDaemon: 11. clone @ 0xf906f in /lib/x86_64-linux-gnu/libc-2.28.so
2023.01.16 08:30:55.290290 [ 41801 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: 7B0734FCB0DE0271D880B340784BCEDA. There is no information about the reference checksum.
2023.01.16 08:30:55.452277 [ 41802 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: 7B0734FCB0DE0271D880B340784BCEDA. There is no information about the reference checksum.
2023.01.16 08:31:16.415813 [ 8930 ] {598756cf-d1a5-485e-960c-a295a62a8bca} <Error> Minidump: SCM cdw-2.0.0/2.0.0.115, core dump path: /var/byconity//f0fee29a-09ab-4f0b-7aa5988f-bf24e61c.dmp

**Comment by kevinthfang** [comment]
what exact SQL are you running?

**Comment by kevinthfang** [comment]
Can't reproduce this. Server crash may caused by multiple queries. Another issue related to stats (#44 ) is under fixing.
