### ISSUE TITLE
fdb Segmentation fault

### ISSUE THREAD

**Issue by xingcici** [ByConity/ByConity#438]
when i try to deloy cluster in local k8s, it's shows that fdb start error
![image](https://github.com/ByConity/ByConity/assets/38656144/e2298413-2d01-4275-8873-0db506d0504c)

i got this log below
```
Defaulted container "foundationdb" out of: foundationdb, foundationdb-kubernetes-sidecar, foundationdb-kubernetes-init (init)
sh: line 1:    11 Segmentation fault      fdbmonitor --conffile /var/dynamic-conf/fdbmonitor.conf --lockfile /var/dynamic-conf/fdbmonitor.lockfile --loggroup byconity-fdb >> /var/log/fdb-trace-logs/fdbmonitor-$(date '+%Y-%m-%d').log 2>&1
```
Has anyone experienced this problem ?

My env:

mac m1 max

docker mem 12G

steps:

kind create cluster --config examples/kind/kind-byconity.yaml

helm upgrade --install --create-namespace --namespace byconity -f ./examples/kind/values-kind.yaml byconity ./chart/byconity --set fdb.enabled=false

helm upgrade --install --create-namespace --namespace byconity -f ./examples/kind/values-kind.yaml byconity ./chart/byconity

**Comment by hustnn** [comment]
Hi, it is a known FDB issue when running in docker on Apple Silicon architecture (e.g., M1). https://github.com/apple/foundationdb/issues/4111. Currently, we are also looking for FDB alternative to have more metadata backend. 
@xingcici Do you have linux to run it?

**Comment by xingcici** [comment]
> apple/foundationdb#4111

sure，i will try it on linux/amd64 device. thanks !
