### ISSUE TITLE
create stats if not exists helloworld.*; Report an error

### ISSUE THREAD

**Issue by zhbdesign** [ByConity/ByConity#44]
2023.01.16 08:40:21.942519 [ 204 ] {b516140f-19fc-41bb-b739-dec2cf3db000} <Error> executeQuery: Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 39 ('*'): *. Expected identifier SQLSTATE: 42000 (version 21.8.7.1) (from 10.20.1.240:10097) (in query: create stats if not exists helloworld.*), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18e345d2 in /opt/byconity/usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb230820 in /opt/byconity/usr/bin/clickhouse
2. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0x154651de in /opt/byconity/usr/bin/clickhouse
3. DB::parseQuery(DB::IParser&, char const*, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long) @ 0x15465262 in /opt/byconity/usr/bin/clickhouse
4. ? @ 0x1432d414 in /opt/byconity/usr/bin/clickhouse
5. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::optional<DB::FormatSettings> const&, bool) @ 0x14332b5f in /opt/byconity/usr/bin/clickhouse
6. DB::HTTPHandler::processQuery(std::__1::shared_ptr<DB::Context>, DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x14bbe7cb in /opt/byconity/usr/bin/clickhouse
7. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x14bc12af in /opt/byconity/usr/bin/clickhouse
8. DB::HTTPServerConnection::run() @ 0x14c0e979 in /opt/byconity/usr/bin/clickhouse
9. Poco::Net::TCPServerConnection::start() @ 0x18db01ec in /opt/byconity/usr/bin/clickhouse
10. Poco::Net::TCPServerDispatcher::run() @ 0x18db06cc in /opt/byconity/usr/bin/clickhouse
11. Poco::PooledThread::run() @ 0x18e9137a in /opt/byconity/usr/bin/clickhouse
12. Poco::ThreadImpl::runnableEntry(void*) @ 0x18e8ef2c in /opt/byconity/usr/bin/clickhouse
13. start_thread @ 0x7fa3 in /lib/x86_64-linux-gnu/libpthread-2.28.so
14. clone @ 0xf906f in /lib/x86_64-linux-gnu/libc-2.28.so
2023.01.16 08:40:21.942746 [ 204 ] {b516140f-19fc-41bb-b739-dec2cf3db000} <Error> DynamicQueryHandler: Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 39 ('*'): *. Expected identifier SQLSTATE: 42000, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18e345d2 in /opt/byconity/usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb230820 in /opt/byconity/usr/bin/clickhouse
2. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0x154651de in /opt/byconity/usr/bin/clickhouse
3. DB::parseQuery(DB::IParser&, char const*, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long) @ 0x15465262 in /opt/byconity/usr/bin/clickhouse
4. ? @ 0x1432d414 in /opt/byconity/usr/bin/clickhouse
5. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::optional<DB::FormatSettings> const&, bool) @ 0x14332b5f in /opt/byconity/usr/bin/clickhouse
6. DB::HTTPHandler::processQuery(std::__1::shared_ptr<DB::Context>, DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x14bbe7cb in /opt/byconity/usr/bin/clickhouse
7. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x14bc12af in /opt/byconity/usr/bin/clickhouse
8. DB::HTTPServerConnection::run() @ 0x14c0e979 in /opt/byconity/usr/bin/clickhouse
9. Poco::Net::TCPServerConnection::start() @ 0x18db01ec in /opt/byconity/usr/bin/clickhouse
10. Poco::Net::TCPServerDispatcher::run() @ 0x18db06cc in /opt/byconity/usr/bin/clickhouse
11. Poco::PooledThread::run() @ 0x18e9137a in /opt/byconity/usr/bin/clickhouse
12. Poco::ThreadImpl::runnableEntry(void*) @ 0x18e8ef2c in /opt/byconity/usr/bin/clickhouse
13. start_thread @ 0x7fa3 in /lib/x86_64-linux-gnu/libpthread-2.28.so
14. clone @ 0xf906f in /lib/x86_64-linux-gnu/libc-2.28.so
 (version 21.8.7.1)

**Comment by Adora627** [comment]
mark: Jingpeng will assign @Gou_Guining

**Comment by canhld94** [comment]
@mtunique any progress on this issue?

**Comment by Adora627** [comment]
related pr #112

**Comment by kevinthfang** [comment]
#112  merged
