### ISSUE TITLE
repeatedly read orc file data using cnchhive

### ISSUE THREAD

**Issue by juppylm** [ByConity/ByConity#443]
After I created the cnchhive table, I found that the read data was inconsistent with the data in the orc file during query, which was more than the original orc data.
By reading the code, it is found that the processing of Parquet and orc in the CnchHiveThreadSelectBlockInputProcessor::getNewTask() method is inconsistent. What I understand should be that a thread reads the stripe of an orc file, but the current code finds that this is not the case.

**Comment by hustnn** [comment]
Thanks for your PR. We will take a look
