### ISSUE TITLE
Multiple write workers for 'insert into ... select xxx'

### ISSUE THREAD

**Issue by juppylm** [ByConity/ByConity#450]
I found that when executing the sql 'insert into ... select xxx', the server only selects one write worker to write data, instead of multiple write workers writing at the same time.

**Comment by dmthuc** [comment]
Hi @juppylm , yeah, it is true. Thank you for your recommendation. We will try to improve in future

**Comment by hustnn** [comment]
It should can be supported in August.

**Comment by hustnn** [comment]
solved in https://github.com/ByConity/ByConity/pull/638
