### ISSUE TITLE
The execution caused the server to crash

### ISSUE THREAD

**Issue by zhbdesign** [ByConity/ByConity#46]
CREATE WAREHOUSE
IF NOT EXISTS `vw_default`
SETTINGS num_workers = 1, type = 'Default',
auto_suspend = 3600, auto_resume = 1,
min_worker_groups = 0, max_worker_groups = 1, max_concurrent_queries=200;

log：
2023.01.16 08:53:36.257992 [ 261 ] {} <Fatal> BaseDaemon: ########################################
2023.01.16 08:53:36.258131 [ 261 ] {} <Fatal> BaseDaemon: (version 21.8.7.1 scm cdw-2.0.0/2.0.0.115, build id: B1C8E2A14E2DBD1E5587FAA6B806FACBBA832810) (from thread 204) (query_id: 78231797-fbf2-4466-af51-bfc6ca2c4911) Received signal Segmentation fault (11)
2023.01.16 08:53:36.258296 [ 261 ] {} <Fatal> BaseDaemon: Address: 0xc0 Access: read. Address not mapped to object.
2023.01.16 08:53:36.258354 [ 261 ] {} <Fatal> BaseDaemon: Stack trace: 0xe23d4f0 0x135acb99 0x13efb8ab 0x1432ed74 0x14332b5f 0x14bbe7cb 0x14bc12af 0x14c0e979 0x18db01ec 0x18db06cc 0x18e9137a 0x18e8ef2c 0x7f6d11d83fa3 0x7f6d107a206f
2023.01.16 08:53:36.258526 [ 261 ] {} <Fatal> BaseDaemon: 3. DB::WithContextImpl<std::__1::shared_ptr<DB::Context const> >::getContext() const @ 0xe23d4f0 in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:53:36.258607 [ 261 ] {} <Fatal> BaseDaemon: 4. DB::ResourceManagement::ResourceManagerClient::createVirtualWarehouse(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ResourceManagement::VirtualWarehouseSettings const&, bool) @ 0x135acb99 in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:53:36.258688 [ 261 ] {} <Fatal> BaseDaemon: 5. DB::InterpreterCreateWarehouseQuery::execute() @ 0x13efb8ab in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:53:36.258737 [ 261 ] {} <Fatal> BaseDaemon: 6. ? @ 0x1432ed74 in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:53:36.258828 [ 261 ] {} <Fatal> BaseDaemon: 7. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::optional<DB::FormatSettings> const&, bool) @ 0x14332b5f in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:53:36.258930 [ 261 ] {} <Fatal> BaseDaemon: 8. DB::HTTPHandler::processQuery(std::__1::shared_ptr<DB::Context>, DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x14bbe7cb in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:53:36.259029 [ 261 ] {} <Fatal> BaseDaemon: 9. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x14bc12af in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:53:36.259101 [ 261 ] {} <Fatal> BaseDaemon: 10. DB::HTTPServerConnection::run() @ 0x14c0e979 in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:53:36.259196 [ 261 ] {} <Fatal> BaseDaemon: 11. Poco::Net::TCPServerConnection::start() @ 0x18db01ec in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:53:36.259281 [ 261 ] {} <Fatal> BaseDaemon: 12. Poco::Net::TCPServerDispatcher::run() @ 0x18db06cc in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:53:36.259352 [ 261 ] {} <Fatal> BaseDaemon: 13. Poco::PooledThread::run() @ 0x18e9137a in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:53:36.259411 [ 261 ] {} <Fatal> BaseDaemon: 14. Poco::ThreadImpl::runnableEntry(void*) @ 0x18e8ef2c in /opt/byconity/usr/bin/clickhouse
2023.01.16 08:53:36.259468 [ 261 ] {} <Fatal> BaseDaemon: 15. start_thread @ 0x7fa3 in /lib/x86_64-linux-gnu/libpthread-2.28.so
2023.01.16 08:53:36.259527 [ 261 ] {} <Fatal> BaseDaemon: 16. clone @ 0xf906f in /lib/x86_64-linux-gnu/libc-2.28.so
2023.01.16 08:53:36.448579 [ 261 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: 7B0734FCB0DE0271D880B340784BCEDA. There is no information about the reference checksum.

**Comment by canhld94** [comment]
@zeromem any update on this issue?
