### ISSUE TITLE
Slower queries with cache

### ISSUE THREAD

**Issue by coulsonm** [ByConity/ByConity#463]
**table schema：**

```
CREATE TABLE test.test7
(
    `time` DateTime,
    `str` String,
    `num` Int64,
    `store_time` DateTime DEFAULT now(),
    `dt` DateTime DEFAULT toDate(now()),
    INDEX index1 num TYPE bloom_filter GRANULARITY 4,
    INDEX index3 str TYPE tokenbf_v1(32768, 2, 0) GRANULARITY 4,
    INDEX index4 str TYPE bloom_filter GRANULARITY 4,
    INDEX index5 store_time TYPE minmax GRANULARITY 4
)
ENGINE = CnchMergeTree
PARTITION BY dt
ORDER BY time
SETTINGS index_granularity = 8192, parts_to_throw_insert = 1200, storage_policy = 'cnch_default_hdfs', enable_local_disk_cache = 0
```

Mock 235600000 rows.  The Size of the str column of a record is 100 bytes.

### **Step-1**
Not use cache：
alter table test.test7 modify setting enable_local_disk_cache = 0

Now we check this sql 3 times.
`select max(str) from test.test7` 
Cost time is：100s+/30s/31s

Use cache：
alter table test.test7 modify setting enable_local_disk_cache = 1

Now we check this sql 3 times.
`select max(str) from test.test7` 
Cost time is：100s+/50s/51s

**Using cache is slower than not using cache？**

### **Step-2**

We try more

set disk_cache_mode = 'FORCE_CHECKSUMS_DISK_CACHE'

then
alter table test.test7 modify setting enable_local_disk_cache = 0

Now we check this sql 3 times.
`select max(str) from test.test7` 
Cost time is：100s+/100s+/50s

alter table test.test7 modify setting enable_local_disk_cache = 1

Now we check this sql 3 times.
`select max(str) from test.test7` 
Cost time is：100s+/30s/31s

**Using cache is faster than not using cache？**

### **Step-3**
set disk_cache_mode = 'AUTO'
repeat step-1,but result is same to step-2!

**What is the performance of using the cache?**

**Comment by foreverneverer** [comment]
@coulsonm Please use the step to check it:
1. check the MaxIOThreadProfileEvents:
```sql
select 
MaxIOThreadProfileEvents.Values[indexOf(MaxIOThreadProfileEvents.Names, 'HDFSReadElapsedMilliseconds')] AS hdfs_ms,
MaxIOThreadProfileEvents.Values[indexOf(MaxIOThreadProfileEvents.Names, 'DiskReadElapsedMicroseconds')]/1000 AS disk_ms,
MaxIOThreadProfileEvents.Values[indexOf(MaxIOThreadProfileEvents.Names, 'ReadBufferFromHdfsRead')] AS hdfs_count,
MaxIOThreadProfileEvents.Values[indexOf(MaxIOThreadProfileEvents.Names, 'ReadBufferFromFileDescriptorRead')] AS disk_count,
hdfs_ms/hdfs_count as hdfs_once,
disk_ms/disk_count as hdfs_once
from cnch('{vw_name}', system.query_log) where event_date = XXX and initial_query_id = xxxx
```

2. if disk io is long, then 
- use `fio` to benchmark your disk to make sure the disk performance is normal
- use https://github.com/brendangregg/perf-tools/blob/master/fs/cachestat to check the pagecache hit is normal when query process.

**Comment by foreverneverer** [comment]
About if enable_disk_cache under different setting:
```c++
bool IMergeTreeDataPart::enableDiskCache() const
{
    if (disk_cache_mode == DiskCacheMode::AUTO)
        return storage.getSettings()->enable_local_disk_cache;
    else if (disk_cache_mode == DiskCacheMode::SKIP_DISK_CACHE)
        return false;
    else if (disk_cache_mode == DiskCacheMode::USE_DISK_CACHE || disk_cache_mode == DiskCacheMode::FORCE_CHECKSUMS_DISK_CACHE)
        return true;
    else
        throw Exception(ErrorCodes::LOGICAL_ERROR, "Unknown disk cache mode");
}
```

**Comment by coulsonm** [comment]
I run two times
`select max(str) from test.test7`

then run analytical sql：
`select 
ProfileEvents.Values[indexOf(ProfileEvents.Names, 'HDFSReadElapsedMilliseconds')] AS hdfs_ms,
ProfileEvents.Values[indexOf(ProfileEvents.Names, 'DiskReadElapsedMicroseconds')]/1000 AS disk_ms,
ProfileEvents.Values[indexOf(ProfileEvents.Names, 'ReadBufferFromHdfsRead')] AS hdfs_count,
ProfileEvents.Values[indexOf(ProfileEvents.Names, 'ReadBufferFromFileDescriptorRead')] AS disk_count,
hdfs_ms/hdfs_count as hdfs_once,
disk_ms/disk_count as disk_once
from cnch('vw_default', system.query_log) where initial_query_id = 'XXX'`

The results ：

- 
<img width="618" alt="e96c153025532b8a5c5d4582e55c45f" src="https://github.com/ByConity/ByConity/assets/127475879/f9a35024-e693-4532-955d-b472ca9d8f73">

- 
<img width="586" alt="ab7b5e48fce257584a3a29c3437be76" src="https://github.com/ByConity/ByConity/assets/127475879/c00485ea-a1e7-4db3-9efa-eea7bf6df6b2">

**Comment by coulsonm** [comment]
上述例子执行数次，发现执行耗时依次为：
<html>
<body>


USE_DISK_CACHE | SKIP_DISK_CACHE
-- | --
59.718 sec | 186.857 sec
58| 281.176
58 | 197
58 | 197
58 | 180


</body>
</html>

期间清理了page cache :  sync; echo 1 > /proc/sys/vm/drop_caches
磁盘压测dd </dev/zero >/a.txt bs=1M count=2k oflag=direct  单磁盘io 200MB/s左右

ck执行同样的sql，耗时在：
230s/11/15

结论：

- ck使用了pagecache/byconity似乎并没有使用
- 同样条件下，本地测试未达到同样性能（可以说非常慢，原因疑似和部署有关）
- 如果磁盘性能慢，似乎会成为瓶颈
