### ISSUE TITLE
Use CnchHive table to run the TPC-DS benchmark (2GB), more than half of the SQL statements cannot be executed successfully.

### ISSUE THREAD

**Issue by xiaomo728** [ByConity/ByConity#469]
### Version Information
ByConity 0.1.0 GA, with merged pull request https://github.com/ByConity/ByConity/pull/348 (cnchhive adapt optimizer)

### Cluster Information
All machines are 4 Cores + 32G Memory.
Cluster: 1 server + 4 default workers + 1 write workers.

### TPCDS Table Statistics
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

</head>

<body link=blue vlink=purple>

Table Name | Rows in Hive
-- | --
call_center | 8
catalog_page | 11718
catalog_returns | 288491
catalog_sales | 2880058
customer | 144000
customer_address | 72000
customer_demographics | 1920800
date_dim | 73049
household_demographics | 7200
income_band | 20
inventory | 16966305
item | 2600
promotion | 322
reason | 36
ship_mode | 0
store | 22
store_returns | 575285
store_sales | 5760749
time_dim | 86400
warehouse | 5
web_page | 74
web_returns | 143629
web_sales | 1439247
web_site | 30

</body>

</html>

### Result Overview
Before querying, we set the following settings:
```
set enable_optimizer = 1;
set dialect_type = 'ANSI';
```
As a result, a total of 38 SQL statements are successfully executed and **64 SQL statements fail to be executed**.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

</head>

<body link=blue vlink=purple>

Error Code | Numbers
-- | --
43 | 1
210 | 9
386 | 9
439 | 20
2007 | 21
5008 | 4

</body>

</html>

**Error Code 43**
Code: 43. DB::Exception: Received from (_server address_). DB::Exception: Illegal types String and IntervalDay of arguments of function plus

**Error Code 210**
Code: 210. DB::Exception: Received from (_server address_). DB::Exception: Unable to connect to HDFS: OutOfMemoryError: GC overhead limit exceeded

**Error Code 386**
Code: 386. DB::Exception: Received from (_server address_). DB::Exception: ExchangeSource: BrpcReciver[(_uuid_)]@(_worker address_) fail to receive data: BrpcRemoteBroadcastReceiver: already has been finished code: 9015 exception: Segment:6, exception:Code: 386, e.displayText() = DB::Exception: There is no supertype for types String, Date because some of them are String/FixedString and some of them are not: while executing 'FUNCTION lessOrEquals(d_date : 1, cast(11779, 'Date') : 6) -> lessOrEquals(d_date, cast(11779, 'Date')) UInt8 : 7' SQLSTATE: HY000 (version 21.8.7.1): While executing ExchangeSource: BrpcReciver[(_uuid_)]@(_worker address_)

**Error Code 439**
Code: 439. DB::Exception: Received from (_server address_). DB::Exception: Cannot schedule a task: no free thread (timeout=0) (threads=64, jobs=64)

**Error Code 2007**
Code: 2007. DB::Exception: Received from (_server address_) DB::Exception: ExchangeSource: BrpcReciver[(_uuid_)]@(_worker address_) fail to receive data: BrpcRemoteBroadcastReceiver: already has been finished code: 900100 exception: Segment:18, exception:Code: 2007, e.displayText() = DB::Exception: RpcClient exception happen-2004:[E2004] Too many user code to run when -usercode_in_pthread is on SQLSTATE: HY000 (version 21.8.7.1): While executing ExchangeSource: BrpcReciver[(_uuid_)]@(_worker address_)

**Error Code 5008**
Code: 5008. DB::Exception: Received from (_server address_). DB::Exception: 1008:[E1008]Reached timeout=3000ms @(_worker address_)

### Details
SQL numbers refer from: https://github.com/ByConity/byconity-tpcds/tree/main/sql/standard
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

</head>

<body link=blue vlink=purple>

SQL Number | Error Code
-- | --
sql4 | 2007
sql5 | 439
sql9 | 439
sql11 | 439
sql12 | 386
sql14.1 | 439
sql14.2 | 439
sql16 | 386
sql20 | 386
sql21 | 386
sql23 | 439
sql24.1 | 439
sql24.2 | 439
sql25 | 2007
sql26 | 5008
sql28 | 439
sql29 | 439
sql30 | 2007
sql31 | 2007
sql32 | 2007
sql33 | 2007
sql35 | 439
sql37 | 386
sql39.1 | 439
sql40 | 386
sql45 | 2007
sql47 | 2007
sql48 | 5008
sql49 | 210
sql50 | 210
sql51 | 210
sql53 | 2007
sql54 | 439
sql55 | 2007
sql56 | 439
sql57 | 439
sql58 | 2007
sql59 | 2007
sql60 | 2007
sql61 | 439
sql64 | 2007
sql65 | 439
sql72 | 43
sql73 | 2007
sql74 | 2007
sql75 | 2007
sql77 | 5008
sql78 | 5008
sql79 | 2007
sql80 | 439
sql82 | 210
sql83 | 210
sql84 | 210
sql85 | 210
sql86 | 210
sql87 | 210
sql88 | 2007
sql89 | 2007
sql90 | 439
sql91 | 2007
sql92 | 386
sql94 | 386
sql95 | 439
sql98 | 386

</body>

</html>

**Comment by wordhardqi** [comment]
do u have scripts for setting up tcp-ds tables and running testing sqls?

**Comment by xiaomo728** [comment]
> do u have scripts for setting up tcp-ds tables and running testing sqls?

@wordhardqi We just manually did these. As our version has been merged https://github.com/ByConity/ByConity/pull/316 issue, creating cnchhive table is very convenient.

**Comment by wordhardqi** [comment]
When i try to reproduce, i met a new error ~~

`Code: 70. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: ExchangeSource: BrpcReciver[e7812654-519f-44ca-9340-157ccdb9473d_1_0_1_0] fail to receive data: BrpcRemoteBroadcastReceiver: already has been finished code: 9015 exception: Segment:1, exception:Worker host:192.168.168.170:9510, exception:Code: 70, e.displayText() = DB::Exception: The type "fixed_size_binary" of an input column "cc_call_center_id" is not supported for conversion from a ORC data format.: While executing CnchHiveThread SQLSTATE: HY000 (version 21.8.7.1): While executing ExchangeSource: BrpcReciver[e7812654-519f-44ca-9340-157ccdb9473d_1_0_1_0] SQLSTATE: HY000.`

**Comment by wordhardqi** [comment]
@xiaomo728 did u run bthread in pthread

**Comment by wordhardqi** [comment]
For this Error Code 210
Code: 210. DB::Exception: Received from (server address). DB::Exception: Unable to connect to HDFS: OutOfMemoryError: GC overhead limit exceeded,
check the hdfs namenode.

**Comment by xiaomo728** [comment]
> @xiaomo728 did u run bthread in pthread

@wordhardqi due to some special issues of our version, we disabled bthread (as I understand it) as follows:
in `contrib/incubator-brpc/src/brpc/event_dispatcher.cpp` line 32:
DEFINE_bool(usercode_in_pthread, false, 
            "Call user's callback in pthreads, use bthreads otherwise");

we just modified this line to:
DEFINE_bool(usercode_in_pthread, **true**, 
            "Call user's callback in pthreads, use bthreads otherwise");

Is there any influences?

**Comment by xiaomo728** [comment]
> For this Error Code 210 Code: 210. DB::Exception: Received from (server address). DB::Exception: Unable to connect to HDFS: OutOfMemoryError: GC overhead limit exceeded, check the hdfs namenode.

@wordhardqi I am sorry, what do u mean about the hdfs namenode? Thx.

**Comment by xiaomo728** [comment]
> When i try to reproduce, i met a new error ~~
> 
> `Code: 70. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: ExchangeSource: BrpcReciver[e7812654-519f-44ca-9340-157ccdb9473d_1_0_1_0] fail to receive data: BrpcRemoteBroadcastReceiver: already has been finished code: 9015 exception: Segment:1, exception:Worker host:192.168.168.170:9510, exception:Code: 70, e.displayText() = DB::Exception: The type "fixed_size_binary" of an input column "cc_call_center_id" is not supported for conversion from a ORC data format.: While executing CnchHiveThread SQLSTATE: HY000 (version 21.8.7.1): While executing ExchangeSource: BrpcReciver[e7812654-519f-44ca-9340-157ccdb9473d_1_0_1_0] SQLSTATE: HY000.`

@wordhardqi does this look like a table data format conversion issue (Arrow ORC -> CH column)?

**Comment by wordhardqi** [comment]
> 

The message shows that the namenode of HDFS get OOMed

**Comment by wordhardqi** [comment]
> > When i try to reproduce, i met a new error ~~
> > `Code: 70. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: ExchangeSource: BrpcReciver[e7812654-519f-44ca-9340-157ccdb9473d_1_0_1_0] fail to receive data: BrpcRemoteBroadcastReceiver: already has been finished code: 9015 exception: Segment:1, exception:Worker host:192.168.168.170:9510, exception:Code: 70, e.displayText() = DB::Exception: The type "fixed_size_binary" of an input column "cc_call_center_id" is not supported for conversion from a ORC data format.: While executing CnchHiveThread SQLSTATE: HY000 (version 21.8.7.1): While executing ExchangeSource: BrpcReciver[e7812654-519f-44ca-9340-157ccdb9473d_1_0_1_0] SQLSTATE: HY000.`
> 
> @wordhardqi does this look like a table data format conversion issue (Arrow ORC -> CH column)?

this is a issue  that the byconity cannot read fixed sized string and we already have a pr to solve it.

**Comment by kevinthfang** [comment]
@xiaomo728 Could you verify if it's fixed?

**Comment by xiaomo728** [comment]
> @xiaomo728 Could you verify if it's fixed?

@kevinthfang Yes, we just run TPC-DS 2GB on GA0.2.0 and all queries can be executed*.

* Some SQLs are modified because syntax errors are reported (even if `dialect_type = 'ANSI'` is enabled).
