### ISSUE TITLE
Directory: Configure compute groups. sql in the document caused the server to crash

### ISSUE THREAD

**Issue by zhbdesign** [ByConity/ByConity#47]
Directory: Configure compute groups. sql in the document caused the server to crash

**Comment by hustnn** [comment]
Can you provide the sql? Thanks.

**Comment by zhbdesign** [comment]
CREATE WAREHOUSE
IF NOT EXISTS `vw_default`
SETTINGS num_workers = 1, type = 'Default',
auto_suspend = 3600, auto_resume = 1,
min_worker_groups = 0, max_worker_groups = 1, max_concurrent_queries=200;

**Comment by zhbdesign** [comment]
docker-compose.yml  start occur crash，resource-manage-0 
 start don't crash

**Comment by Adora627** [comment]
dup to issue#46
