### ISSUE TITLE
The daemon-manager and resource-manager services do not support multi-instance deployment

### ISSUE THREAD

**Issue by blueChild** [ByConity/ByConity#474]
The daemon-manager and resource-manager services do not support multi-instance deployment.
To improve reliability, multi-instance deployment is supported.

<html>
<body>
<ul style="box-sizing: border-box; margin-top: ; margin-right: ; margin-bottom: var(--ifm-leading); margin-left: ; padding-left: var(--ifm-list-left-padding); color: rgb(35, 47, 71); font-family: &quot;Sofia Pro&quot;, system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, Ubuntu, Cantarell, &quot;Noto Sans&quot;, sans-serif, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box; overflow-wrap: break-word;">Production Environment</li></ul>

Component Name | CPU | Memory | Hard Disk | Network | Number of Instances
-- | -- | -- | -- | -- | --
TSO | 2 | 500M | 5G | 10 Gigabit LAN | 3
Server | 14 | 60G | 1T | 10 Gigabit NIC | >=1
Worker | 30 | 240G | 2T+ | 10 Gigabit LAN | >=1
DaemonManager | 4 | 10G | 10G | 10 Gigabit NIC | 1
ResourceManager | 8 | 16G | 10G | 10 Gigabit NIC | 1

</body>
</html>

**Comment by dmthuc** [comment]
Hi @blueChild , we do have multi-instance deployment supported for ResourceManager but not Deamon Manager because the high-availability of this service is not critical

**Comment by blueChild** [comment]
hi, you mean the GA version is already support multi-instance deployment for ResourceManager ?

**Comment by blueChild** [comment]
> Hi @blueChild , we do have multi-instance deployment supported for ResourceManager but not Daemon Manager because the high-availability of this service is not critical

hi, you mean the GA version is already support multi-instance deployment for ResourceManager ?

**Comment by blueChild** [comment]
> > > Hi @blueChild , we do have multi-instance deployment supported for ResourceManager but not Daemon Manager because the high-availability of this service is not critical
> > 
> > 
> > hi, you mean the GA version is already support multi-instance deployment for ResourceManager ?
> 
> Hi @blueChild , at the moment GA version doesn't have it yet. But we will have this in near future. We will integrate keeper for leader election

will zooKeeper be no longer used for election?

**Comment by serenallttyy** [comment]
@blueChild 请问您是不是在公司内部有相关的需求，可以通过微信群加下小助手联系我们试试看。
<img width="96" alt="image" src="https://github.com/ByConity/ByConity/assets/88301094/89fd2b22-6720-4db6-88e7-21d6df9d232b">

**Comment by blueChild** [comment]
> 

ok

> 

ok

**Comment by blueChild** [comment]
> > > > > Hi @blueChild , we do have multi-instance deployment supported for ResourceManager but not Daemon Manager because the high-availability of this service is not critical
> > > > 
> > > > 
> > > > hi, you mean the GA version is already support multi-instance deployment for ResourceManager ?
> > > 
> > > 
> > > Hi @blueChild , at the moment GA version doesn't have it yet. But we will have this in near future. We will integrate keeper for leader election
> > 
> > 
> > will zooKeeper be no longer used for election?
> 
> Yeah, we want to avoid external dependency so the `clickhouse-keeper` will be integrated into TSO service.

ok, we will try it when the ability is available

**Comment by blueChild** [comment]
> @blueChild Hi,i'm from byconity operation team. May I ask if you have any relevant needs within the company, and if you could add a chatbot to the WeChat group to contact us and try it out? <img alt="image" width="96" src="https://user-images.githubusercontent.com/88301094/253873814-89fd2b22-6720-4db6-88e7-21d6df9d232b.png">

OK
