### ISSUE TITLE
query failed after leader of clickhouse-server instances is stopped

### ISSUE THREAD

**Issue by blueChild** [ByConity/ByConity#476]
## Bug Report
After multiple clickhouse-servers are deployed, the leader of clickhouse-server instances is stopped.  As a result, select, insert and alter sql all failed.
### The result you expected
The query, insert, and alter statements can be executed successfully.
### How to Reproduce

Component Name  | Number of Instances | host
-- | -- | --
TSO | 3 | host1,host2,host3
Server | 4 | host1,host2,host3,host4
default-worker  | 5 | host5,host6,host7,host8,host9
write-worker  | 3 | host10,host11,host12
DaemonManager  | 1 | host1
ResourceManager  | 1 | host1
zookeeper | 3 | host13,host14,host15

1. create a table:
``` sql
CREATE TABLE test.import_test_S3_ttl_on (
did UInt32,
num1 Int8,
num2 Int16,
num3 Int32,
num4 Int64,
unum1 UInt8,
unum2 UInt16,
unum3 UInt32,
unum4 UInt64,
fnum1 Float32,
fnum2 Float64,
a1 String,
dataCycle Date default today(),
updatetime DateTime default now(),
aa Array(Int16)) 
ENGINE = CnchMergeTree() Partition by toYYYYMMDD(dataCycle) 
Order by did TTL dataCycle + toIntervalDay(10) 
SETTINGS index_granularity=8192;
```
2. insert data into table:
``` sql
insert into test.import_test_S3_ttl_on 
select (rand() % ((1000000 - 1) + 1)) + 1,
(rand() % ((1000000 - 1) + 1)) + 1,
(rand() % ((1000000 - 1) + 1)) + 1,
(rand() % ((1000000 - 1) + 1)) + 1,
(rand() % ((1000000 - 1) + 1)) + 1,
(rand() % ((1000000 - 1) + 1)) + 1,
(rand() % ((1000000 - 1) + 1)) + 1,
(rand() % ((1000000 - 1) + 1)) + 1,
(rand() % ((1000000 - 1) + 1)) + 1,
(rand() % ((1000000 - 1) + 1)) + 1,
(rand() % ((1000000 - 1) + 1)) + 1,
concat('jwx', toString((rand() % ((1000000 - 1) + 1)) + 1)),
(toDate('2023-06-19') + (rand(3)%((90)))),now(),['1'] 
from numbers(500);
```
 3. query table:
``` sql
select count(),dataCycle from test.import_test_S3_ttl_on group by dataCycle;
```
According to the logs, the selected leader node is displayed:
`will reroute query select count(),dataCycle from test.import_test_S3_ttl_on group by dataCycle to 11.12.13.14:4567`
so, the leader is 11.12.13.14 
4. stop the leader clickhouse-server
here is stop clickhouse-server with port 4567 on 11.12.13.14
5. execute query, insert, alter sql again:
``` sql
select count(),dataCycle from test.import_test_S3_ttl_on group by dataCycle;
```
``` sql
insert into test.import_test_S3_ttl_on 
select (rand() % ((1000000 - 1) + 1)) + 1,
(rand() % ((1000000 - 1) + 1)) + 1,
(rand() % ((1000000 - 1) + 1)) + 1,
(rand() % ((1000000 - 1) + 1)) + 1,
(rand() % ((1000000 - 1) + 1)) + 1,
(rand() % ((1000000 - 1) + 1)) + 1,
(rand() % ((1000000 - 1) + 1)) + 1,
(rand() % ((1000000 - 1) + 1)) + 1,
(rand() % ((1000000 - 1) + 1)) + 1,
(rand() % ((1000000 - 1) + 1)) + 1,
(rand() % ((1000000 - 1) + 1)) + 1,
concat('jwx', toString((rand() % ((1000000 - 1) + 1)) + 1)),
(toDate('2023-06-19') + (rand(3)%((90)))),now(),['1'] 
from numbers(500);
```
``` sql
alter table test.import_test_S3_ttl_on drop partition 20230825
```
those sql all failed, report the error: Connection refused (11.12.13.14:4567) or Not connected to 11.12.13.14:7890 yet

### Version
0.1.0-GA

**Comment by kevinthfang** [comment]
which clickhouse-server is stopped? Do you mean byconity server? If yes, would you please paste the server configuration in your cnch_config.xml? And are there any exceptions in the server log?

**Comment by hustnn** [comment]
let's use https://github.com/ByConity/ByConity/issues/547 to track the progress of HA feature of ByConity
