### ISSUE TITLE
query failed after the ZooKeeper Service is restarted

### ISSUE THREAD

**Issue by blueChild** [ByConity/ByConity#477]
## Bug Report
When the ZooKeeper service connected to the Byconity is stopped and then restarted, the SQL query fails after the ZooKeeper service on the Byconity is normal.
### Briefly describe the bug

Component Name  | Number of Instances | host
-- | -- | --
TSO | 3 | host1,host2,host3
Server | 4 | host1,host2,host3,host4
default-worker  | 5 | host5,host6,host7,host8,host9
write-worker  | 3 | host10,host11,host12
DaemonManager  | 1 | host1
ResourceManager  | 1 | host1
zookeeper | 3 | host13,host14,host15

### The result you expected
the SQL query can be execute successfully
### How to Reproduce
``` sql
CREATE TABLE  IF NOT EXISTS  test.test_S3_RMT3(
did UInt32, 
num1 Int8,
num2 Int16,
num3 Int32,
num4 Int64,
unum1 UInt8,
unum2 UInt16,
unum3 UInt32,
unum4 UInt64,
fnum1 Float32,
fnum2 Float64,
a1 String,
dataCycle Date default today(),
updatetime DateTime default now(),
aa Array(Int16)) 
ENGINE = CnchMergeTree() 
Partition by toYYYYMMDD(dataCycle) 
Order by did SETTINGS index_granularity=8192, storage_policy = 'bytes3_test';

insert into test_S3_RMT3 select (
rand() % ((1000000 - 1) + 1)) + 1,
(rand() % ((1000000 - 1) + 1)) + 1,
(rand() % ((1000000 - 1) + 1)) + 1,
(rand() % ((1000000 - 1) + 1)) + 1,
(rand() % ((1000000 - 1) + 1)) + 1,
(rand() % ((1000000 - 1) + 1)) + 1,
(rand() % ((1000000 - 1) + 1)) + 1,
(rand() % ((1000000 - 1) + 1)) + 1,
(rand() % ((1000000 - 1) + 1)) + 1,
(rand() % ((1000000 - 1) + 1)) + 1,
(rand() % ((1000000 - 1) + 1)) + 1,
concat('jwx', toString((rand() % ((1000000 - 1) + 1)) + 1)),
(toDate('2023-05-05') + (rand(3)%((90)))),
now(),['1']  from  numbers(5000);
```

1. stop one of the zookeeper service
2. restart one of the zookeeper service
3. execute query on byconity
`select * from test.test_S3_RMT3 limit 10;`
 query failed.
### Version
0.1.0-GA

**Comment by kevinthfang** [comment]
What the purpose of the zookeeper here? Would you please describe your deployment topology? and the configuration of your zookeeper?

**Comment by dmthuc** [comment]
Hi @blueChild , currently we do not use zookeeper for byconity deployment, we will use internal keeper instead in near future.

**Comment by blueChild** [comment]
ok, we will try it when the ability is available

**Comment by blueChild** [comment]
> What the purpose of the zookeeper here? Would you please describe your deployment topology? and the configuration of your zookeeper?

the zookeeper cluster is just for election. if you do not use zookeeper for byconity deployment, we will try the clickhouse-keeper later when the ability is available

**Comment by dmthuc** [comment]
Hi @blueChild , we've created an issue here to support HA deployment.
