### ISSUE TITLE
execute sql appears error in document

### ISSUE THREAD

**Issue by zhbdesign** [ByConity/ByConity#48]
SYSTEM RESTART MERGES helloworld.my_first_table;Cannot execute
SYSTEM RESTART GC helloworld.my_first_table;Cannot execute
It appears in the document SYSTEM START CONSUMER helloworld.cnch_kafka_consume;Cannot execute，SYSTEM START CONSUME helloworld.cnch_kafka_consume;Can execute
system.cnch_kafka_tables doesn't exist
Cnchkafka table execute select * from table error，Code: 48. DB::Exception: Received from localhost:9000. DB::Exception: Method read is not supported by storage CnchKafka SQLSTATE: HY000. (NOT_IMPLEMENTED)

**Comment by chenxing-xc** [comment]
thanks @zhbdesign , SYSTEM RESTART MERGES|GC should not be supported. this is document bug.
system.cnch_kafka_tables has not been merged to byconity, we'll add it soon
