### ISSUE TITLE
SIMPLE authentication is not enabled

### ISSUE THREAD

**Issue by xingcici** [ByConity/ByConity#487]
I want to use exist hdfs cluster. it use Kerberos, 
Refer to https://github.com/ByConity/ByConity/issues/346, i config as below.

cnch-config.yaml
```
    other ...

    hdfs_nnproxy: hdfs://dc07-daily-bigdata-xxxx.com:8020
    hadoop_kerberos_keytab: /tmp/vivi-byconity.keytab
    hadoop_kerberos_principal: byconity/byconity@vivi.com
    hadoop_security_kerberos_ticket_cache_path: /tmp/krb5cc_0
    hadoop_security_authentication: kerberos
```

hdfs3.xml
```
        other ...

        <property>
            <name>hadoop.security.authentication</name>
            <value>KERBEROS</value>
        </property>
        <property>
            <name>dfs.use.internal.credential.format</name>
            <value>false</value>
        </property>
        <property>
            <name>dfs.data.transfer.protection</name>
            <value>authentication</value>
        </property>
        <property>
            <name>dfs.block.access.token.enable</name>
            <value>true</value>
        </property>
```

and i put krb5.conf at /etc/

But when the server start, it show 

<img width="1332" alt="image" src="https://github.com/ByConity/ByConity/assets/38656144/b3721c01-854b-4af7-a75b-fc25729a3d45">

what else need i config ?

**Comment by xingcici** [comment]
I have searched at  apache hdfs config doc. and there is no config named `dfs.use.internal.credential.format`

**Comment by hustnn** [comment]
hi, which version of ByConity are you using?

**Comment by xingcici** [comment]
> 



> hi, which version of ByConity are you using?



> hi, which version of ByConity are you using?

docker image 0.1.0-GA

**Comment by xingcici** [comment]
@hustnn it's suddenly worked ! 😂
But How can i config hdfs_nnproxy  as HA ？
I tried `hdfs_nnproxy: xxx:8020,xxx:8020`，but it's seems go to service discovey consul mode.

**Comment by hustnn** [comment]
> 

what did you do? Any config do you change since the server_part_log shouldn't go through the hdfs path, it is a normal merge tree table.
