### ISSUE TITLE
k8s helm 方式部署 ByConity 的话，FoundationDB 和 HDFS 是不是必须的？

### ISSUE THREAD

**Issue by hillbun** [ByConity/ByConity#493]
https://byconity.github.io/docs/deployment/deploy-k8s

k8s helm 方式部署 ByConity 的话，FoundationDB 和 HDFS 是不是必须的？

**Comment by Adora627** [comment]
> k8s helm 方式部署 ByConity 的话，FoundationDB 和 HDFS 是不是必须的？

HDFS 是作为byconity的远端数据存储，可以换成 S3；FoundationDB是作为系统元数据存储，目前没提供替换方案。

**Comment by hillbun** [comment]
https://byconity.github.io/docs/deployment/deploy-k8s#prepare-your-storage-provider

这里提到的   [OpenEBS local PV](https://openebs.io/docs/concepts/localpv).   指哪个组件？

**Comment by hustnn** [comment]
> https://byconity.github.io/docs/deployment/deploy-k8s#prepare-your-storage-provider
> 
> 这里提到的 [OpenEBS local PV](https://openebs.io/docs/concepts/localpv). 指哪个组件？

这个不是ByConity的组件，是跟k8s部署相关的。

**Comment by hillbun** [comment]
我在 K8S 没有部署  OpenEBS ， 为什么也可以安装成功？

**Comment by hillbun** [comment]
@hustnn 

请指教

**Comment by dmthuc** [comment]
Hi @weigangchen1 , please help with this issue

**Comment by weigangchen1** [comment]
> https://byconity.github.io/docs/deployment/deploy-k8s
> 
> k8s helm 方式部署 ByConity 的话，FoundationDB 和 HDFS 是不是必须的？

不是必须的可以引用自己已有的fdb和hdfs

**Comment by weigangchen1** [comment]
![image](https://github.com/ByConity/ByConity/assets/131356308/c4bfc498-ddb1-4a7c-bccf-2dbceaf36404)

**Comment by hillbun** [comment]
OpenEBS 
和
fdb和hdfs

对比，哪个性能好一点？

**Comment by weigangchen1** [comment]
> 
OpenEBS 跟fdb hdfs是不同领域的东西。好像没法对比？
fdb是用来存储metadata
openebs是管理k8s上节点的存储
hdfs存&读数据

**Comment by hillbun** [comment]
openebs  是存储组件，用来创建PVC的吗？

**Comment by weigangchen1** [comment]
创建pv

hillbun ***@***.***> 于2023年7月24日周一 15:07写道：
