### ISSUE TITLE
Write a document on how to configure S3 storage

### ISSUE THREAD

**Issue by dmthuc** [ByConity/ByConity#499]
Write a document on how to configure S3 storage

**Comment by hustnn** [comment]
hi @dmthuc , do you want https://byconity.github.io/docs/basic-guide/cluster-configuration#storage_configuration?

**Comment by dmthuc** [comment]
> hi @dmthuc , do you want https://byconity.github.io/docs/basic-guide/cluster-configuration#storage_configuration?

yeah, this document look good.
