### ISSUE TITLE
More than one server in cluster without leader-election is not supported now

### ISSUE THREAD

**Issue by xingcici** [ByConity/ByConity#500]
Is byconity not support multi byconity-server with dns service discovery at present ?
When i set replicas as 2, the sever show 
```
More than one server in cluster without leader-election is not supported now
```

And i read the code, found that need zookeeper.
But according to doc, byconity do not need zk.

byconity image : 0.1.0-GA

**Comment by dmthuc** [comment]
> @dmthuc Can you answer this qustion ? Thanks !

Hi @xingcici , currently ByConity configuration do not support multiple server. Let me check if i can configure multiple server

**Comment by xingcici** [comment]
> > @dmthuc Can you answer this qustion ? Thanks !
> 
> Hi @xingcici , currently ByConity configuration do not support multiple server. But our code is ready to support multiple servers, TSO and resource managers. Let me update the config to support them

TSO also not support ? I read the doc and it show that tso support mutiple and rm/dm not support.

**Comment by dmthuc** [comment]
Hi @xingcici, it is probably 2 days

**Comment by xingcici** [comment]
Hi @dmthuc , I have the following questions.
1. Is the byconity-server multiple support need zk after the config update ? According to the code, i found it strong dependency on zk to do election.
2. Why server need election ?  Does it mean all write request go through leader like raft or just for merge part ?

**Comment by xingcici** [comment]
> Hi @xingcici, it is probably 2 days

OK, Thanks

**Comment by dmthuc** [comment]
Hi @xingcici , no we do not need zk after config update. We will use internal keeper which has the same interface as zk. We need a server as a leader to do some of the leader job like maintains server topology. The write and merge will be distributed among servers based on the calculation of consistent hash value of table uuid.

**Comment by xingcici** [comment]
> Hi @xingcici , no we do not need zk after config update. We will use internal keeper which has the same interface as zk. We need a server as a leader to do some of the leader job like maintains server topology. The write and merge will be distributed among servers based on the calculation of consistent hash value of table uuid.

Great !

**Comment by xingcici** [comment]
> Hi @xingcici , a member are working to provide multi servers K8s config. I think it will take more time. You can follow the ticket here #515

OK, Thanks.

**Comment by hustnn** [comment]
Let's close this issue and follow up on #515
