### ISSUE TITLE
failed to create user

### ISSUE THREAD

**Issue by hillbun** [ByConity/ByConity#504]
CREATE USER clickhouse_admin IDENTIFIED BY 'xxxxx';

but return error:

Code: 514. DB::Exception: Received from localhost:9000. DB::Exception: Not found a storage to insert user `clickhouse_admin`: Couldn't insert user `clickhouse_admin`. Successfully inserted: none SQLSTATE: HY000.

**Comment by hillbun** [comment]
```
CREATE USER clickhouse_admin IDENTIFIED WITH sha256_hash BY 'FF22B0CFA61C0DA762093438D279F900080187F62CA0DA9DF3F71F5829EDA4FF'

Query id: 3411c552-66b3-4f54-b058-b20bebfa0220

[byconity-server-0] 2023.07.19 08:42:19.684333 [ 228 ] {3411c552-66b3-4f54-b058-b20bebfa0220} <Debug> TransactionCoordinator: Created txn txn_id: 442959433473458176 commit_ts: 0 status: Running priority: high location: "10.0.2.34:8124" initiator: "Server" type: Implicit

[byconity-server-0] 2023.07.19 08:42:19.684417 [ 228 ] {3411c552-66b3-4f54-b058-b20bebfa0220} <Debug> trySetVirtualWarehouse: Trying to set virtual warehouse for query `CREATE USER clickhouse_admin IDENTIFIED WITH sha256_hash BY 'FF22B0CFA61C0DA762093438D279F900080187F62CA0DA9DF3F71F5829EDA4FF'` ...
[byconity-server-0] 2023.07.19 08:42:19.684448 [ 228 ] {3411c552-66b3-4f54-b058-b20bebfa0220} <Debug> trySetVirtualWarehouse: Trying to set virtual warehouse for expression `CREATE USER clickhouse_admin IDENTIFIED WITH sha256_hash BY 'FF22B0CFA61C0DA762093438D279F900080187F62CA0DA9DF3F71F5829EDA4FF'` ...
[byconity-server-0] 2023.07.19 08:42:19.684507 [ 228 ] {3411c552-66b3-4f54-b058-b20bebfa0220} <Debug> executeQuery: (from [::1]:51438) CREATE USER clickhouse_admin IDENTIFIED BY 'xcVB$#Rawd2w';
[byconity-server-0] 2023.07.19 08:42:19.684672 [ 228 ] {3411c552-66b3-4f54-b058-b20bebfa0220} <Trace> ContextAccess (default): Access granted: CREATE USER ON *.*
[byconity-server-0] 2023.07.19 08:42:19.684842 [ 228 ] {3411c552-66b3-4f54-b058-b20bebfa0220} <Debug> TransactionCoordinator: Deleted txn 442959433473458176

[byconity-server-0] 2023.07.19 08:42:19.684864 [ 228 ] {3411c552-66b3-4f54-b058-b20bebfa0220} <Trace> TransactionCoordinator: No need to erase active timestamp for txn 442959433473458176

[byconity-server-0] 2023.07.19 08:42:19.684942 [ 228 ] {3411c552-66b3-4f54-b058-b20bebfa0220} <Error> executeQuery: Code: 514, e.displayText() = DB::Exception: Not found a storage to insert user `clickhouse_admin`: Couldn't insert user `clickhouse_admin`. Successfully inserted: none SQLSTATE: HY000 (version 21.8.7.1) (from [::1]:51438) (in query: CREATE USER clickhouse_admin IDENTIFIED BY 'xcVB$#Rawd2w';), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x19e02db2 in /opt/byconity/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb665400 in /opt/byconity/bin/clickhouse
2. DB::MultipleAccessStorage::insertImpl(std::__1::shared_ptr<DB::IAccessEntity const> const&, bool) @ 0x13dece41 in /opt/byconity/bin/clickhouse
3. DB::IAccessStorage::insert(std::__1::vector<std::__1::shared_ptr<DB::IAccessEntity const>, std::__1::allocator<std::__1::shared_ptr<DB::IAccessEntity const> > > const&) @ 0x13dcc598 in /opt/byconity/bin/clickhouse
4. DB::InterpreterCreateUserQuery::execute() @ 0x146ea44e in /opt/byconity/bin/clickhouse
5. ? @ 0x149e419b in /opt/byconity/bin/clickhouse
6. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool) @ 0x149e1405 in /opt/byconity/bin/clickhouse
7. DB::TCPHandler::runImpl() @ 0x15354f93 in /opt/byconity/bin/clickhouse
8. DB::TCPHandler::run() @ 0x1536241c in /opt/byconity/bin/clickhouse
9. Poco::Net::TCPServerConnection::start() @ 0x19d7e9cc in /opt/byconity/bin/clickhouse
10. Poco::Net::TCPServerDispatcher::run() @ 0x19d7eeac in /opt/byconity/bin/clickhouse
11. Poco::PooledThread::run() @ 0x19e5fb5a in /opt/byconity/bin/clickhouse
12. Poco::ThreadImpl::runnableEntry(void*) @ 0x19e5d70c in /opt/byconity/bin/clickhouse
13. start_thread @ 0x7fa3 in /lib/x86_64-linux-gnu/libpthread-2.28.so
14. clone @ 0xf906f in /lib/x86_64-linux-gnu/libc-2.28.so


0 rows in set. Elapsed: 0.002 sec. 

Received exception from server (version 21.8.7):
Code: 514. DB::Exception: Received from localhost:9000. DB::Exception: Not found a storage to insert user `clickhouse_admin`: Couldn't insert user `clickhouse_admin`. Successfully inserted: none SQLSTATE: HY000. 

```

**Comment by dmthuc** [comment]
> ```
> CREATE USER clickhouse_admin IDENTIFIED WITH sha256_hash BY 'FF22B0CFA61C0DA762093438D279F900080187F62CA0DA9DF3F71F5829EDA4FF'
> 
> Query id: 3411c552-66b3-4f54-b058-b20bebfa0220
> 
> [byconity-server-0] 2023.07.19 08:42:19.684333 [ 228 ] {3411c552-66b3-4f54-b058-b20bebfa0220} <Debug> TransactionCoordinator: Created txn txn_id: 442959433473458176 commit_ts: 0 status: Running priority: high location: "10.0.2.34:8124" initiator: "Server" type: Implicit
> 
> [byconity-server-0] 2023.07.19 08:42:19.684417 [ 228 ] {3411c552-66b3-4f54-b058-b20bebfa0220} <Debug> trySetVirtualWarehouse: Trying to set virtual warehouse for query `CREATE USER clickhouse_admin IDENTIFIED WITH sha256_hash BY 'FF22B0CFA61C0DA762093438D279F900080187F62CA0DA9DF3F71F5829EDA4FF'` ...
> [byconity-server-0] 2023.07.19 08:42:19.684448 [ 228 ] {3411c552-66b3-4f54-b058-b20bebfa0220} <Debug> trySetVirtualWarehouse: Trying to set virtual warehouse for expression `CREATE USER clickhouse_admin IDENTIFIED WITH sha256_hash BY 'FF22B0CFA61C0DA762093438D279F900080187F62CA0DA9DF3F71F5829EDA4FF'` ...
> [byconity-server-0] 2023.07.19 08:42:19.684507 [ 228 ] {3411c552-66b3-4f54-b058-b20bebfa0220} <Debug> executeQuery: (from [::1]:51438) CREATE USER clickhouse_admin IDENTIFIED BY 'xcVB$#Rawd2w';
> [byconity-server-0] 2023.07.19 08:42:19.684672 [ 228 ] {3411c552-66b3-4f54-b058-b20bebfa0220} <Trace> ContextAccess (default): Access granted: CREATE USER ON *.*
> [byconity-server-0] 2023.07.19 08:42:19.684842 [ 228 ] {3411c552-66b3-4f54-b058-b20bebfa0220} <Debug> TransactionCoordinator: Deleted txn 442959433473458176
> 
> [byconity-server-0] 2023.07.19 08:42:19.684864 [ 228 ] {3411c552-66b3-4f54-b058-b20bebfa0220} <Trace> TransactionCoordinator: No need to erase active timestamp for txn 442959433473458176
> 
> [byconity-server-0] 2023.07.19 08:42:19.684942 [ 228 ] {3411c552-66b3-4f54-b058-b20bebfa0220} <Error> executeQuery: Code: 514, e.displayText() = DB::Exception: Not found a storage to insert user `clickhouse_admin`: Couldn't insert user `clickhouse_admin`. Successfully inserted: none SQLSTATE: HY000 (version 21.8.7.1) (from [::1]:51438) (in query: CREATE USER clickhouse_admin IDENTIFIED BY 'xcVB$#Rawd2w';), Stack trace (when copying this message, always include the lines below):
> 
> 0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x19e02db2 in /opt/byconity/bin/clickhouse
> 1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb665400 in /opt/byconity/bin/clickhouse
> 2. DB::MultipleAccessStorage::insertImpl(std::__1::shared_ptr<DB::IAccessEntity const> const&, bool) @ 0x13dece41 in /opt/byconity/bin/clickhouse
> 3. DB::IAccessStorage::insert(std::__1::vector<std::__1::shared_ptr<DB::IAccessEntity const>, std::__1::allocator<std::__1::shared_ptr<DB::IAccessEntity const> > > const&) @ 0x13dcc598 in /opt/byconity/bin/clickhouse
> 4. DB::InterpreterCreateUserQuery::execute() @ 0x146ea44e in /opt/byconity/bin/clickhouse
> 5. ? @ 0x149e419b in /opt/byconity/bin/clickhouse
> 6. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool) @ 0x149e1405 in /opt/byconity/bin/clickhouse
> 7. DB::TCPHandler::runImpl() @ 0x15354f93 in /opt/byconity/bin/clickhouse
> 8. DB::TCPHandler::run() @ 0x1536241c in /opt/byconity/bin/clickhouse
> 9. Poco::Net::TCPServerConnection::start() @ 0x19d7e9cc in /opt/byconity/bin/clickhouse
> 10. Poco::Net::TCPServerDispatcher::run() @ 0x19d7eeac in /opt/byconity/bin/clickhouse
> 11. Poco::PooledThread::run() @ 0x19e5fb5a in /opt/byconity/bin/clickhouse
> 12. Poco::ThreadImpl::runnableEntry(void*) @ 0x19e5d70c in /opt/byconity/bin/clickhouse
> 13. start_thread @ 0x7fa3 in /lib/x86_64-linux-gnu/libpthread-2.28.so
> 14. clone @ 0xf906f in /lib/x86_64-linux-gnu/libc-2.28.so
> 
> 
> 0 rows in set. Elapsed: 0.002 sec. 
> 
> Received exception from server (version 21.8.7):
> Code: 514. DB::Exception: Received from localhost:9000. DB::Exception: Not found a storage to insert user `clickhouse_admin`: Couldn't insert user `clickhouse_admin`. Successfully inserted: none SQLSTATE: HY000. 
> ```

Hi, currently you need to create user by update user.xml files

**Comment by hillbun** [comment]
test-user:
    networks:
      ip: ::/0
    password: "12345abc"
    profile: default
    quota: default

what's password value format should be?

**Comment by dmthuc** [comment]
> test-user: networks: ip: ::/0 password: "12345abc" profile: default quota: default
> 
> what's password value format should be?

Hi @hillbun , the password format is supported with both plan text and hash encoding, please take a look at the following document. I suggest use to use hash encoding instead of plain text to improve security
https://clickhouse.com/docs/en/operations/settings/settings-users
