### ISSUE TITLE
hdfs-datanode can not start

### ISSUE THREAD

**Issue by hillbun** [ByConity/ByConity#506]
```
kubectl get pods -n byconity |grep byconity |grep byconity-hdfs
byconity-hdfs-datanode-0                    0/1     Init:0/1   3 (78s ago)   19m
byconity-hdfs-datanode-1                    0/1     Init:0/1   3 (80s ago)   19m
byconity-hdfs-datanode-2                    0/1     Init:0/1   3 (75s ago)   19m
byconity-hdfs-namenode-0                    1/1     Running    0             32m
byconity-hdfs-shell-78ccd45745-4sm8x        1/1     Running    0             32m
```

```
kubectl describe pods byconity-hdfs-datanode-0  -n byconity

Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  20m                   default-scheduler  Successfully assigned byconity/byconity-hdfs-datanode-0 to eklet-subnet-ezvuf44o-100832
  Normal   Starting   20m                   eklet              Starting pod sandbox eks-0k9pbd1w
  Normal   Starting   18m                   eklet              Sync endpoints
  Warning  BackOff    2m33s (x3 over 8m2s)  eklet              Back-off restarting failed container
  Normal   Pulled     2m21s (x4 over 18m)   eklet              Container image "alpine:3.10.2" already present on machine
  Normal   Created    2m21s (x4 over 18m)   eklet              Created container wait-for-namenode-startup
  Normal   Started    2m21s (x4 over 18m)   eklet              Started container wait-for-namenode-startup
```

kubectl logs byconity-hdfs-datanode-0  -n byconity --all-containers
nc: bad address 'byconity-hdfs-namenode-0.byconity-hdfs-namenodes:8021'
nc: bad address 'byconity-hdfs-namenode-0.byconity-hdfs-namenodes:8021'
nc: bad address 'byconity-hdfs-namenode-0.byconity-hdfs-namenodes:8021'
nc: bad address 'byconity-hdfs-namenode-0.byconity-hdfs-namenodes:8021'
nc: bad address 'byconity-hdfs-namenode-0.byconity-hdfs-namenodes:8021'
nc: bad address 'byconity-hdfs-namenode-0.byconity-hdfs-namenodes:8021'
nc: bad address 'byconity-hdfs-namenode-0.byconity-hdfs-namenodes:8021'
nc: bad address 'byconity-hdfs-namenode-0.byconity-hdfs-namenodes:8021'
nc: bad address 'byconity-hdfs-namenode-0.byconity-hdfs-namenodes:8021'
nc: bad address 'byconity-hdfs-namenode-0.byconity-hdfs-namenodes:8021'
nc: bad address 'byconity-hdfs-namenode-0.byconity-hdfs-namenodes:8021'
nc: bad address 'byconity-hdfs-namenode-0.byconity-hdfs-namenodes:8021'
nc: bad address 'byconity-hdfs-namenode-0.byconity-hdfs-namenodes:8021'
Error from server (InternalError): Internal error occurred: container "datanode" in pod "byconity-hdfs-datanode-0" is waiting to start: PodInitializing

**Comment by hustnn** [comment]
hi, are you using https://github.com/ByConity/byconity-deploy?

**Comment by hillbun** [comment]
Yes

Helm chart

**Comment by hustnn** [comment]
@weigangchen1  pls help to check

**Comment by hillbun** [comment]
@weigangchen1 

HI.  I can not find this in 

https://github.com/ByConity/byconity-deploy/blob/master/chart/byconity/values.yaml

**Comment by weigangchen1** [comment]
https://github.com/ByConity/byconity-deploy/blob/master/chart/byconity/charts/hdfs/values.yaml#L15

hillbun ***@***.***> 于2023年7月24日周一 11:24写道：

**Comment by weigangchen1** [comment]
> @weigangchen1
> 
> HI. I can not find this in
> 
> https://github.com/ByConity/byconity-deploy/blob/master/chart/byconity/values.yaml

https://github.com/ByConity/byconity-deploy/blob/master/chart/byconity/charts/hdfs/values.yaml#L15 
you can find it here. it's opensource hdfs

**Comment by hillbun** [comment]
I change to:

```
alpine:
  repository: amd64/alpine #if your machine is amd64.please use amd64/alpine
  tag: 3.10.2
  imagePullPolicy: IfNotPresent
```

But  same errors.

after I disable ingress of hdfs,   all hdfs-datanode pods works.

why?
