### ISSUE TITLE
how to config pvc of fdb-log-data and fdb-storage-data CAPACITY and STORAGECLASS

### ISSUE THREAD

**Issue by hillbun** [ByConity/ByConity#507]
how to config pvc of fdb-log-data and fdb-storage-data CAPACITY and STORAGECLASS?

I can not see them in values file

```
kubectl get pvc -n byconity 
NAME                                  STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
byconity-fdb-log-1-data               Bound    pvc-c1517575-9383-4c2c-ad99-2291b6eb9d9e   120Gi      RWO            cbs            34s
byconity-fdb-log-2-data               Bound    pvc-fd95cff5-59e0-4495-b29a-80bb6ce7c520   120Gi      RWO            cbs            34s
byconity-fdb-log-3-data               Bound    pvc-455bf18c-31d8-4e7a-b446-1eff5986f745   120Gi      RWO            cbs            34s
byconity-fdb-log-4-data               Bound    pvc-aa408257-5f70-466e-bcaf-69c465f2bc49   120Gi      RWO            cbs            34s
byconity-fdb-storage-1-data           Bound    pvc-ec132a06-6ae0-486b-b368-980f334c7ada   120Gi      RWO            cbs            34s
byconity-fdb-storage-2-data           Bound    pvc-fae00dce-ef2b-4f0e-b8ad-d9bb3a1d1b76   120Gi      RWO            cbs            34s
byconity-fdb-storage-3-data           Bound    pvc-6759f813-0b97-46f0-be1d-95f2c629b778   120Gi      RWO            cbs            34s
```

**Comment by hillbun** [comment]
any advice?

**Comment by hillbun** [comment]
@dmthuc 

Please advice,  thanks.

**Comment by dmthuc** [comment]
Hi @hillbun , thank you for open the issue. Hi @weigangchen1 , could you help with this issue?

**Comment by weigangchen1** [comment]
> how to config pvc of fdb-log-data and fdb-storage-data CAPACITY and STORAGECLASS?
> 
> I can not see them in values file
> 
> ```
> kubectl get pvc -n byconity 
> NAME                                  STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
> byconity-fdb-log-1-data               Bound    pvc-c1517575-9383-4c2c-ad99-2291b6eb9d9e   120Gi      RWO            cbs            34s
> byconity-fdb-log-2-data               Bound    pvc-fd95cff5-59e0-4495-b29a-80bb6ce7c520   120Gi      RWO            cbs            34s
> byconity-fdb-log-3-data               Bound    pvc-455bf18c-31d8-4e7a-b446-1eff5986f745   120Gi      RWO            cbs            34s
> byconity-fdb-log-4-data               Bound    pvc-aa408257-5f70-466e-bcaf-69c465f2bc49   120Gi      RWO            cbs            34s
> byconity-fdb-storage-1-data           Bound    pvc-ec132a06-6ae0-486b-b368-980f334c7ada   120Gi      RWO            cbs            34s
> byconity-fdb-storage-2-data           Bound    pvc-fae00dce-ef2b-4f0e-b8ad-d9bb3a1d1b76   120Gi      RWO            cbs            34s
> byconity-fdb-storage-3-data           Bound    pvc-6759f813-0b97-46f0-be1d-95f2c629b778   120Gi      RWO            cbs            34s
> ```

there is a example here. 
https://github.com/ByConity/byconity-deploy/blob/master/examples/k8s/values.yaml#L260
for more details, please refer to https://github.com/FoundationDB/fdb-kubernetes-operator/blob/main/docs/cluster_spec.md
