### ISSUE TITLE
How to disable or config ingress byconity-hdfs

### ISSUE THREAD

**Issue by hillbun** [ByConity/ByConity#508]
https://github.com/ByConity/byconity-deploy

When I enable hdfs,  ingress byconity-hdfs will be installed.

How to disable or config ingress byconity-hdfs type?

```
kubectl get ingress -n byconity
NAME            CLASS    HOSTS   ADDRESS          PORTS   AGE
byconity-hdfs   <none>   *       43.153.xx.xx   80      9m12s
```

**Comment by weigangchen1** [comment]
> https://github.com/ByConity/byconity-deploy
> 
> When I enable hdfs, ingress byconity-hdfs will be installed.
> 
> How to disable or config ingress byconity-hdfs type?
> 
> ```
> kubectl get ingress -n byconity
> NAME            CLASS    HOSTS   ADDRESS          PORTS   AGE
> byconity-hdfs   <none>   *       43.153.xx.xx   80      9m12s
> ```
the helm chart we prodived is the open-source hdfs chart. 
you can set ingress disabled here
https://github.com/ByConity/byconity-deploy/blob/master/chart/byconity/charts/hdfs/values.yaml#L109

**Comment by hillbun** [comment]
what's usage if ingress of hdfs ?

May I disable it?

**Comment by weigangchen1** [comment]
i think you can disabled it. because byconity using service for
hdfs-service discovery.
this is open-source hdfs chart , the ingress was created by the chart
owner. for more details , maybe you can consult the hdfs doc.
