### ISSUE TITLE
How to config S3 for storage_configuration?

### ISSUE THREAD

**Issue by hillbun** [ByConity/ByConity#509]
https://byconity.github.io/docs/basic-guide/cluster-configuration#storage_configuration

3 files contains storage_configuration section

chart/byconity/files/daemon-manager.yaml
chart/byconity/files/worker.yaml
chart/byconity/files/server.yaml

All 3 files need to config or not?

**Comment by dmthuc** [comment]
Hi @white-cc could you help with this issue?

**Comment by dmthuc** [comment]
Hi @hillbun , i think it is necessary to update all 3 files
