### ISSUE TITLE
is Tencent cloud  CHDFS supported?

### ISSUE THREAD

**Issue by hillbun** [ByConity/ByConity#512]
https://www.tencentcloud.com/zh/document/product/1106/41965

ofs://${mountpoint}/

this format hdfs

**Comment by hillbun** [comment]
or just support  standard  HDFS？

**Comment by Adora627** [comment]
> or just support standard HDFS？

standard HDFS is supported: https://byconity.github.io/zh-cn/docs/basic-guide/cluster-configuration#hdfs--%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0

**Comment by hillbun** [comment]
how about  tencentcloud CHDFS

https://www.tencentcloud.com/zh/document/product/1106/41965

ofs://${mountpoint}/  format

**Comment by Adora627** [comment]
> how about tencentcloud CHDFS
> 
> https://www.tencentcloud.com/zh/document/product/1106/41965
> 
> ofs://${mountpoint}/ format

no plan to verify compatibility recently, please go verify it if you're interested
