### ISSUE TITLE
insert data to VersionedCollapsingMergeTree get final error 

### ISSUE THREAD

**Issue by xiaohu-zhang** [ByConity/ByConity#513]
1 CREATE DATABASE test2 ENGINE = Atomic;
2. use test2;
3. CREATE TABLE UAct
             (
                 UserID UInt64,
                 PageViews UInt8,
                 Duration UInt8,
                 Sign Int8,
                 Version UInt8
             )
             ENGINE = VersionedCollapsingMergeTree(Sign, Version)
             ORDER BY UserID;
4. INSERT INTO UAct VALUES (4324182021466249494, 5, 146, 1, 1);
got error:
10.0.3.14 :) INSERT INTO UAct VALUES (4324182021466249494, 5, 146, 1, 1);

INSERT INTO UAct FORMAT Values

Query id: d8f3e1c5-a0e1-4bda-90b9-652dbdccb90f

[byconity-server-0] 2023.07.20 07:54:11.022128 [ 55284 ] {d8f3e1c5-a0e1-4bda-90b9-652dbdccb90f} <Debug> TransactionCoordinator: Created txn txn_id: 442981325467287552 commit_ts: 0 status: Running priority: high location: "10.0.3.14:8124" initiator: "Server" type: Implicit

[byconity-server-0] 2023.07.20 07:54:11.022214 [ 55284 ] {d8f3e1c5-a0e1-4bda-90b9-652dbdccb90f} <Debug> trySetVirtualWarehouse: Trying to set virtual warehouse for query `INSERT INTO UAct VALUES` ...
[byconity-server-0] 2023.07.20 07:54:11.022241 [ 55284 ] {d8f3e1c5-a0e1-4bda-90b9-652dbdccb90f} <Debug> trySetVirtualWarehouse: Trying to set virtual warehouse for expression `INSERT INTO UAct VALUES` ...
[byconity-server-0] 2023.07.20 07:54:11.022282 [ 55284 ] {d8f3e1c5-a0e1-4bda-90b9-652dbdccb90f} <Debug> trySetVirtualWarehouse: Try set virtual warehouse for table `test2.UAct`
[byconity-server-0] 2023.07.20 07:54:11.024608 [ 55284 ] {d8f3e1c5-a0e1-4bda-90b9-652dbdccb90f} <Debug> executeQuery: (from [::ffff:192.168.0.13]:56262) INSERT INTO UAct VALUES
[byconity-server-0] 2023.07.20 07:54:11.031199 [ 55284 ] {d8f3e1c5-a0e1-4bda-90b9-652dbdccb90f} <Trace> ContextAccess (default): Access granted: INSERT(UserID, PageViews, Duration, Sign, Version) ON test2.UAct
[byconity-server-0] 2023.07.20 07:54:11.306080 [ 56032 ] <Fatal> BaseDaemon: ########################################
[byconity-server-0] 2023.07.20 07:54:11.306158 [ 56032 ] <Fatal> BaseDaemon: (version 21.8.7.1 scm 1.0.0.0, build id: D89888E231F8AF1F) (from thread 55284) (query_id: d8f3e1c5-a0e1-4bda-90b9-652dbdccb90f) Received signal Segmentation fault (11)
[byconity-server-0] 2023.07.20 07:54:11.306226 [ 56032 ] <Fatal> BaseDaemon: Address: 0xffffffffffffff58 Access: read. Address not mapped to object.
[byconity-server-0] 2023.07.20 07:54:11.306276 [ 56032 ] <Fatal> BaseDaemon: Stack trace: 0x1518e250 0x15092dc5 0x1472ce12 0x1472aa4c 0x1472a194 0x1472a24e 0x13fffb23 0x1535a1af 0x15355078 0x1536241c 0x19d7e9cc 0x19d7eeac 0x19e5fb5a 0x19e5d70c 0x7fcf97c5efa3 0x7fcf9678306f
[byconity-server-0] 2023.07.20 07:54:11.306366 [ 56032 ] <Fatal> BaseDaemon: 3. DB::MergeTreeDataWriter::writeTempPart(DB::BlockWithPartition&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>, unsigned long, long, long) @ 0x1518e250 in /opt/byconity/bin/clickhouse
[byconity-server-0] 2023.07.20 07:54:11.306424 [ 56032 ] <Fatal> BaseDaemon: 4. DB::MergeTreeBlockOutputStream::write(DB::Block const&) @ 0x15092dc5 in /opt/byconity/bin/clickhouse
[byconity-server-0] 2023.07.20 07:54:11.306475 [ 56032 ] <Fatal> BaseDaemon: 5. DB::PushingToViewsBlockOutputStream::write(DB::Block const&) @ 0x1472ce12 in /opt/byconity/bin/clickhouse
[byconity-server-0] 2023.07.20 07:54:11.306542 [ 56032 ] <Fatal> BaseDaemon: 6. DB::AddingDefaultBlockOutputStream::write(DB::Block const&) @ 0x1472aa4c in /opt/byconity/bin/clickhouse
[byconity-server-0] 2023.07.20 07:54:11.306595 [ 56032 ] <Fatal> BaseDaemon: 7. DB::SquashingBlockOutputStream::finalize() @ 0x1472a194 in /opt/byconity/bin/clickhouse
[byconity-server-0] 2023.07.20 07:54:11.306669 [ 56032 ] <Fatal> BaseDaemon: 8. DB::SquashingBlockOutputStream::writeSuffix() @ 0x1472a24e in /opt/byconity/bin/clickhouse
[byconity-server-0] 2023.07.20 07:54:11.306720 [ 56032 ] <Fatal> BaseDaemon: 9. DB::CountingBlockOutputStream::writeSuffix() @ 0x13fffb23 in /opt/byconity/bin/clickhouse
[byconity-server-0] 2023.07.20 07:54:11.306779 [ 56032 ] <Fatal> BaseDaemon: 10. DB::TCPHandler::processInsertQuery(DB::Settings const&) @ 0x1535a1af in /opt/byconity/bin/clickhouse
[byconity-server-0] 2023.07.20 07:54:11.306827 [ 56032 ] <Fatal> BaseDaemon: 11. DB::TCPHandler::runImpl() @ 0x15355078 in /opt/byconity/bin/clickhouse
[byconity-server-0] 2023.07.20 07:54:11.306873 [ 56032 ] <Fatal> BaseDaemon: 12. DB::TCPHandler::run() @ 0x1536241c in /opt/byconity/bin/clickhouse
[byconity-server-0] 2023.07.20 07:54:11.306936 [ 56032 ] <Fatal> BaseDaemon: 13. Poco::Net::TCPServerConnection::start() @ 0x19d7e9cc in /opt/byconity/bin/clickhouse
[byconity-server-0] 2023.07.20 07:54:11.306982 [ 56032 ] <Fatal> BaseDaemon: 14. Poco::Net::TCPServerDispatcher::run() @ 0x19d7eeac in /opt/byconity/bin/clickhouse
[byconity-server-0] 2023.07.20 07:54:11.307035 [ 56032 ] <Fatal> BaseDaemon: 15. Poco::PooledThread::run() @ 0x19e5fb5a in /opt/byconity/bin/clickhouse
[byconity-server-0] 2023.07.20 07:54:11.307083 [ 56032 ] <Fatal> BaseDaemon: 16. Poco::ThreadImpl::runnableEntry(void*) @ 0x19e5d70c in /opt/byconity/bin/clickhouse
[byconity-server-0] 2023.07.20 07:54:11.307140 [ 56032 ] <Fatal> BaseDaemon: 17. start_thread @ 0x7fa3 in /lib/x86_64-linux-gnu/libpthread-2.28.so
[byconity-server-0] 2023.07.20 07:54:11.307207 [ 56032 ] <Fatal> BaseDaemon: 18. clone @ 0xf906f in /lib/x86_64-linux-gnu/libc-2.28.so
[byconity-server-0] 2023.07.20 07:54:11.438447 [ 56032 ] <Fatal> BaseDaemon: Calculated checksum of the binary: D8D53BB200DF1030D35655EB8FF519C9. There is no information about the reference checksum.
[byconity-server-0] 2023.07.20 07:54:11.438560 [ 56032 ] <Information> SentryWriter: Not sending crash report
Exception on client:
Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from byconity-server.dev.kaya:9000. (ATTEMPT_TO_READ_AFTER_EOF)

Connecting to database test2 at byconity-server.dev.kaya:9000 as user default.
Code: 210. DB::NetException: Connection refused (byconity-server.dev.kaya:9000). (NETWORK_ERROR)

silversilver@silverdeMacBook-Pro ~ % docker run -it yandex/clickhouse-client --host byconity-server.dev.kaya --port 9000 --user default
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
<jemalloc>: MADV_DONTNEED does not work (memset will be used instead)
<jemalloc>: (This is the expected behaviour if you are running under QEMU)
ClickHouse client version 22.1.3.7 (official build).
Connecting to byconity-server.dev.kaya:9000 as user default.
Connected to ClickHouse server version 21.8.7 revision 54450.

ClickHouse server version is older than ClickHouse client. It may indicate that the server is out of date and can be upgraded.

**Comment by dmthuc** [comment]
Hi @xiaohu-zhang , thank you for try ByConity. We do not maintain *MergeTree any more in ByConity. Can you try VersionedCollapsingCnchMergeTree instead?

**Comment by dmthuc** [comment]
and also it is better to use client program from ByConity

**Comment by xiaohu-zhang** [comment]
<img width="1329" alt="image" src="https://github.com/ByConity/ByConity/assets/26646273/3b73f3d6-e392-4ebf-ba10-99c7747da323">
did not have this engine

**Comment by dmthuc** [comment]
> <img alt="image" width="1329" src="https://user-images.githubusercontent.com/26646273/254909144-3b73f3d6-e392-4ebf-ba10-99c7747da323.png"> did not have this engine

Sorry my bad, it is CnchVersionedCollapsingCnchMergeTree
![image](https://github.com/ByConity/ByConity/assets/13962605/4a7ca05d-bcde-4b2c-bd00-5d5690facd6c)
But look like this engine has some problem at the moment we will look at it

**Comment by dmthuc** [comment]
This issue has been fixed in internal branch, for ByConity it will be fixed by code synchronisation
