### ISSUE TITLE
Core config mofidy for PROD  deploy

### ISSUE THREAD

**Issue by xingcici** [ByConity/ByConity#516]
Hi, @dmthuc  I have deployed ByConity to prod. But I found  that the cpu/memory/disk are not fully used.
And the query is very slow.
Are there any config I need modify for prod, like cpu core num / thread nums or others.

![image](https://github.com/ByConity/ByConity/assets/38656144/90c4095a-b696-4d35-8274-96fd4a186dc0)

docker image : 0.1.0-GA
server : 32C 128G 1.5T SSD 10G NetCard
deploy topology : 1 by-conity-sever. 2 reader. 2 writer.

By the way, is there any way to see the execute plan executed  on which readers/writers ?

**Comment by dmthuc** [comment]
Hi @xingcici , at this moment the easiest way to view executed plan is enable trace log with `set send_logs_level='trace'` and execute the query again

**Comment by dmthuc** [comment]
> 128G

The select query will mostly executed by worker, so can you check if worker is allocated with enough resource?

**Comment by xingcici** [comment]
> Hi @xingcici , at this moment the easiest way to view executed plan is enable trace log with `set send_logs_level='trace'` and execute the query again

Thanks !
I found that the file size in hdfs are very small. It's may be the reson for slow query.
But I remember ByConity  will merge the same partitions. 
<img width="1186" alt="image" src="https://github.com/ByConity/ByConity/assets/38656144/52de57c0-5f26-4fc5-a3d2-7207332f7afb">

**Comment by dmthuc** [comment]
> > Hi @xingcici , at this moment the easiest way to view executed plan is enable trace log with `set send_logs_level='trace'` and execute the query again
> 
> Thanks ! I found that the file size in hdfs are very small. It's may be the reson for slow query. But I remember ByConity will merge the same partitions. <img alt="image" width="1186" src="https://user-images.githubusercontent.com/38656144/254873860-52de57c0-5f26-4fc5-a3d2-7207332f7afb.png">

yeah, the daemon manager will start merge process in server. It will always running. But it may take some time to merge

**Comment by xingcici** [comment]
Is this param control size of the part ?
<img width="1088" alt="image" src="https://github.com/ByConity/ByConity/assets/38656144/4d39f014-5dfd-4979-ad84-1226155996c7">

**Comment by dmthuc** [comment]
> Is this param control size of the part ? <img alt="image" width="1088" src="https://user-images.githubusercontent.com/38656144/254876424-4d39f014-5dfd-4979-ad84-1226155996c7.png">

I don't see that settings in our code

**Comment by dmthuc** [comment]
Hi @xingcici , can you select system table `system.bg_threads` to see if the merge thread is running for your table?

**Comment by xingcici** [comment]
> system.cnch_parts

OK, I'll look into the problem myself first.  Thanks a lot ! 😄

**Comment by xingcici** [comment]
Hi @dmthuc
![image](https://github.com/ByConity/ByConity/assets/38656144/99722d1e-ba20-4c9b-868d-abe537f3cea6)
Is this mean the merge task stuck ?
I found that the merge task work fine when part num is small, but with the increase of the part num, it's  stuck.

**Comment by dmthuc** [comment]
> Hi @dmthuc ![image](https://user-images.githubusercontent.com/38656144/255053837-99722d1e-ba20-4c9b-868d-abe537f3cea6.png) Is this mean the merge task stuck ? I found that the merge task work fine when part num is small, but with the increase of the part num, it's stuck.

Yeah, look like it is stuck. Hi @zeromem , please help to take a look at this issue

**Comment by dmthuc** [comment]
Hi @xingcici, can you upgrade to latest version to see it this issue has been resolved

**Comment by xingcici** [comment]
Hi @dmthuc ,I use the docker image `latest` now. I saw version 0.1.2 earlier，but  the DIGEST is same as `0.1.2`, so i did not upgrade.
Can you confrim the `0.1.2`  image is the latest version ?
![image](https://github.com/ByConity/ByConity/assets/38656144/941141c9-aa5e-400d-ae0c-0a51e07a2659)
https://hub.docker.com/r/byconity/byconity/tags

**Comment by xingcici** [comment]
> Hi @dmthuc ,I use the docker image `latest`（Last pushed 15 days ago） now. I saw version 0.1.2 earlier（Last pushed 3 days ago），but the DIGEST is same as `latest`, so i did not upgrade. Can you confrim the `0.1.2` image is the latest version ? ![image](https://user-images.githubusercontent.com/38656144/255091715-941141c9-aa5e-400d-ae0c-0a51e07a2659.png) https://hub.docker.com/r/byconity/byconity/tags

**Comment by dmthuc** [comment]
> Hi @dmthuc ,I use the docker image `latest` （Last pushed 15 days ago）now. I saw version 0.1.2 （Last pushed 3 days ago） earlier，but the DIGEST is same as `latest`, so i did not upgrade. Can you confrim the `0.1.2` image is the latest version or pushed by mistake? ![image](https://user-images.githubusercontent.com/38656144/255091715-941141c9-aa5e-400d-ae0c-0a51e07a2659.png) https://hub.docker.com/r/byconity/byconity/tags

Then it is no need to upgrade, can you try to look at worker log to see if there is any exception related to the merge. We perform the merge in worker pod

**Comment by xingcici** [comment]
> > Hi @dmthuc ,I use the docker image `latest` （Last pushed 15 days ago）now. I saw version 0.1.2 （Last pushed 3 days ago） earlier，but the DIGEST is same as `latest`, so i did not upgrade. Can you confrim the `0.1.2` image is the latest version or pushed by mistake? ![image](https://user-images.githubusercontent.com/38656144/255091715-941141c9-aa5e-400d-ae0c-0a51e07a2659.png) https://hub.docker.com/r/byconity/byconity/tags
> 
> Then it is no need to upgrade, can you try to look at worker log to see if there is any exception related to the merge. We perform the merge in worker pod

I think may be some param i did not config right.

![image](https://github.com/ByConity/ByConity/assets/38656144/3526107d-009d-4004-83c6-70b0b747cc74)

When the cluster is very busy, the cpu usage never over 2 %, mem usage never over 3 %.
And the merge speed less than write speed even i set `enable_addition_bg_task = 1, cnch_merge_enable_batch_select = 1, cnch_merge_pick_worker_algo = 'RoundRobin'`.

From cnch_parts_info it show that the cluster take at least 60 second merge from 574 to 451.
![image](https://github.com/ByConity/ByConity/assets/38656144/75e1fe33-2178-4150-86e6-71d9c104437a)

Is there any param i need config for prod to increase cpu/mem usage ?

**Comment by xingcici** [comment]
By the way, i found that when i drop table, the hdfs data will not be droped.

**Comment by xingcici** [comment]
Here are cpu /mem/ net

![image](https://github.com/ByConity/ByConity/assets/38656144/84043196-1ce5-4da1-aba2-662a9ac5c335)

![image](https://github.com/ByConity/ByConity/assets/38656144/2fc9f724-54d1-4e67-9d1a-bdf9418842aa)

![image](https://github.com/ByConity/ByConity/assets/38656144/c6cecdb6-1f51-4e0c-8329-6c81a7fb8123)

**Comment by dmthuc** [comment]
Hi @zeromem , could you check if anything settings can change to improve merge performance?

**Comment by zeromem** [comment]
> Hi @zeromem , could you check if anything settings can change to improve merge performance?

@dmthuc @xingcici hi, there is a doc introducing some useful parameters for merge https://byconity.github.io/docs/advanced-guide/background-task-configuration . 

If the `elapsed` is more than 10000 seconds, then need to figure out why the merge task is so slow (maybe check related logs on worker). 

On the other hand, you can set `cnch_merge_max_total_rows_to_merge` smaller to make the merge task smaller which would be finished in a shorter time.

**Comment by hustnn** [comment]
The PrefetchedReader for merge is not included in this version, maybe we can try it in the newer version.

**Comment by xingcici** [comment]
> https://byconity.github.io/docs/advanced-guide/background-task-configuration

OK, I will try it. Thanks !

**Comment by xingcici** [comment]
Hi @zeromem , I am already set cnch_merge_max_total_rows_to_merge to 5000000, but the merge speed still very slow. Is there any performence doc for ByConity merge speed ?
BTW,  Does reducing `cnch_merge_max_total_rows_to_merge` lead  to lower query performance ?
Our scene is metric data write into ByConity by flink in a batch of 30000(max).

**Comment by zeromem** [comment]
> 



> Hi @zeromem , I am already set cnch_merge_max_total_rows_to_merge to 5000000, but the merge speed still very slow. Is there any performence data for ByConity merge speed, such as xxx row(part)/s ? BTW, Does reducing `cnch_merge_max_total_rows_to_merge` lead to lower query performance ? Our scene is metric data write into ByConity by flink in a batch of 30000(max). A row of data is about 0.2 KB.

Hi @xingcici sorry for the late reply. 
About the merge speed, as @hustnn mentioned, the merge prefetcher is not implemented yet. the merge progress will be slow as source parts need to be fetched from hdfs. @hustnn do we have a plan to sync the related code?

About the digest information of merge progress, you can search logs on worker using key words `Merge sorted`, it print some digest info after the merge task finish.

About the query performance, usually it depends on the number of worker and the number of part. We can get a better performance when the worker process less parts. In your case, if the big merge task can be finished finally (maybe it will take a long time), then it's worth to do this.
