### ISSUE TITLE
does support S3 table function?

### ISSUE THREAD

**Issue by xiaohu-zhang** [ByConity/ByConity#521]
`select
                        *
                      from
                s3('https://xxxx/generation=1/chain=polygon/network=mainnet/dataset=BlockWithReceipt/{2000000_2999999,nofile}.pq', 'xxxx', 'xxxx', 'Parquet','block String, transactions String') limit 10;`
and get
`Connecting to byconity-server.dev.kaya:9000 as user default.
Code: 209. DB::NetException: Timeout: connect timed out: 10.0.3.152:9000 (byconity-server.dev.kaya:9000, receive timeout 0 ms, send timeout 0 ms). (SOCKET_TIMEOUT)`

what settings shoud i set to prevent this err?

**Comment by foreverneverer** [comment]
Supported but the latest code hasn't been merged into the master, please wait

**Comment by xiaohu-zhang** [comment]
when merge into master,pls tell me the settings key ,thank you

**Comment by hustnn** [comment]
> when merge into master,pls tell me the settings key ,thank you

ok, around end of Aug.
