### ISSUE TITLE
CnchKafka engine can not get message

### ISSUE THREAD

**Issue by xiaohu-zhang** [ByConity/ByConity#524]
`
CREATE TABLE queue2 (
    timestamp UInt64,
    level String,
    message String
  ) ENGINE = CnchKafka SETTINGS kafka_broker_list = 'kafka.dev.kaya:9094',
                            kafka_topic_list = 'byconity-test',
                            kafka_group_name = 'group1',
                            kafka_format = 'JSONEachRow',
                            kafka_num_consumers = 1;

 CREATE TABLE queue2Store (
    timestamp UInt64,
    level String,
    message String
  ) ENGINE = CnchMergeTree order by timestamp;

  CREATE MATERIALIZED VIEW consumer TO queue2Store
    AS SELECT timestamp, level, message
    FROM queue2 ;
`
when I produce the mesage , then select * from queue2Store is empty.
but if I use clickhouse ,nothing changed except CnchKafka to Kafka and CnchMergeTree to MergeTree. Then select * from queue2Store  i can get the record.
is there anything i can find whats wrong with my sql?

**Comment by dmthuc** [comment]
Hi @xiaohu-zhang , thank you for trying ByConity. We have this document https://github.com/ByConity/ByConity/blob/master/doc/system_table.md contains some system tables that could useful for debugging. Could you to try select into `system.cnch_kafka_tables` and `cnch_system.cnch_kafka_log` and give me the result?

**Comment by xiaohu-zhang** [comment]
the reson is :https://github.com/ByConity/ByConity/issues/457

by the way:
1. using this sql
CREATE MATERIALIZED VIEW consumer TO queue2Store
    AS SELECT timestamp, level, message
    FROM queue2 ;
2. I can get record from queue2Store which consume the kafka msg.
3. but when I wirte sql:
select * from consumer; 
i got the err:Code: 49. DB::Exception: Received from[ byconity-server.dev.kaya:9000.]DB::Exception: Worker group is not set
Is it the right way that can not select from consumer? Since clickhouse can both select from consumer and queue2Store

**Comment by xiaohu-zhang** [comment]
thank you
