### ISSUE TITLE
insert into table using by MATERIALIZED VIEW get error

### ISSUE THREAD

**Issue by xiaohu-zhang** [ByConity/ByConity#527]
1. CREATE TABLE testMv
(
    `timestamp` UInt64,
    `level` String,
    `message` String
)
ENGINE = CnchMergeTree
ORDER BY timestamp

2. CREATE TABLE testMvstore
(
    `timestampsum` UInt64
)
ENGINE = CnchMergeTree
ORDER BY timestampsum

3. CREATE MATERIALIZED VIEW testMvmv to testMvstore AS select sum(timestamp) as timestampsum from testMv group by level;
4. insert into testMv values (213,'s','s'); 
get err:
[byconity-server-0] 2023.07.21 18:18:39.801612 [ 273 ] {12fa0935-5eda-4073-ae94-819344952cc4} <Error> executeQuery: Code: 49, e.displayText() = DB::Exception: Transaction is not in running status, but in Finished: while write prefix to view test.testMvmv (19b844b1-bd0c-4f96-9bd0-83c8230ea3c3) SQLSTATE: HY000 (version 21.8.7.1) (from [::ffff:192.168.0.13]:62815) (in query: insert into testMv values ), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x19e02db2 in /opt/byconity/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb665400 in /opt/byconity/bin/clickhouse
2. DB::CnchServerTransaction::precommit() @ 0x13a9695b in /opt/byconity/bin/clickhouse
3. DB::CnchServerTransaction::commitV2() @ 0x13a960d8 in /opt/byconity/bin/clickhouse
4. DB::CloudMergeTreeBlockOutputStream::writeSuffixForInsert() @ 0x14ffb836 in /opt/byconity/bin/clickhouse
5. DB::CloudMergeTreeBlockOutputStream::writeSuffix() @ 0x14ffb237 in /opt/byconity/bin/clickhouse
6. DB::PushingToViewsBlockOutputStream::writeSuffix() @ 0x1472df46 in /opt/byconity/bin/clickhouse
7. DB::CountingBlockOutputStream::writeSuffix() @ 0x13fffb23 in /opt/byconity/bin/clickhouse
8. DB::PushingToViewsBlockOutputStream::writeSuffix() @ 0x1472e205 in /opt/byconity/bin/clickhouse
9. DB::CountingBlockOutputStream::writeSuffix() @ 0x13fffb23 in /opt/byconity/bin/clickhouse
10. DB::TCPHandler::processInsertQuery(DB::Settings const&) @ 0x1535a1af in /opt/byconity/bin/clickhouse
11. DB::TCPHandler::runImpl() @ 0x15355078 in /opt/byconity/bin/clickhouse
12. DB::TCPHandler::run() @ 0x1536241c in /opt/byconity/bin/clickhouse
13. Poco::Net::TCPServerConnection::start() @ 0x19d7e9cc in /opt/byconity/bin/clickhouse
14. Poco::Net::TCPServerDispatcher::run() @ 0x19d7eeac in /opt/byconity/bin/clickhouse
15. Poco::PooledThread::run() @ 0x19e5fb5a in /opt/byconity/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x19e5d70c in /opt/byconity/bin/clickhouse
17. start_thread @ 0x7fa3 in /lib/x86_64-linux-gnu/libpthread-2.28.so
18. clone @ 0xf906f in /lib/x86_64-linux-gnu/libc-2.28.so

**Comment by dmthuc** [comment]
Hi @hustnn , please help to take a look

**Comment by hustnn** [comment]
hi @dmthuc , @xiaohu-zhang The MV is not supported yet in ByConity, we will support it soon, pls wait.
