### ISSUE TITLE
create table support Bucket table err

### ISSUE THREAD

**Issue by xiaohu-zhang** [ByConity/ByConity#529]
```
 CREATE TABLE test_join (
    timestamp UInt64,
    level String,
    message String
  ) ENGINE = CnchMergeTree order by timestamp PARTITION BY level
CLUSTER BY (timestamp,level) INTO 6 BUCKETS SPLIT_NUMBER 6 WITH_RANGE;
```
and get error:
Expected one of: token, Comma, Arrow, Dot, UUID, DoubleColon, MOD, DIV, NOT, BETWEEN, LIKE, ILIKE, NOT LIKE, NOT ILIKE, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, IS, AND, OR, QuestionMark, PRIMARY KEY, SAMPLE BY, TTL, SETTINGS, AS, COMMENT, INTO OUTFILE, FORMAT, end of query

is there any more precise doc I can follow? Only I can find is https://byconity.github.io/zh-cn/docs/basic-guide/database-table-design. Even there is no example about how to create table using cluster by yet.

**Comment by dmthuc** [comment]
Hi @xiaohu-zhang , we will upload document in next week. For now, please refer to example in this file, https://github.com/ByConity/ByConity/blob/master/tests/queries/4_cnch_stateless/10027_bucket.sql

**Comment by xiaohu-zhang** [comment]
also err:
10.0.9.201 :) CREATE TABLE bucket (name String, age Int64) ENGINE = CnchMergeTree() PARTITION BY name CLUSTER BY age INTO 1 BUCKETS ORDER BY name;

Syntax error: failed at position 89 ('CLUSTER'):

CREATE TABLE bucket (name String, age Int64) ENGINE = CnchMergeTree() PARTITION BY name CLUSTER BY age INTO 1 BUCKETS ORDER BY name;

Expected one of: token, Comma, Arrow, Dot, UUID, DoubleColon, MOD, DIV, NOT, BETWEEN, LIKE, ILIKE, NOT LIKE, NOT ILIKE, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, IS, AND, OR, QuestionMark, PRIMARY KEY, ORDER BY, SAMPLE BY, TTL, SETTINGS, AS, COMMENT, INTO OUTFILE, FORMAT, end of query

version is 0.1.2

**Comment by dmthuc** [comment]
This is weird, i try both of above create queries in my local env and it works
![image](https://github.com/ByConity/ByConity/assets/13962605/d9ad7f55-0612-4239-be3e-a791ace5e316)

**Comment by dmthuc** [comment]
Hi @xiaohu-zhang may i ask if you are using community Clickhouse client or you are using ByConity client?

**Comment by xiaohu-zhang** [comment]
use
docker run -it byconity/byconity:0.1.2 clickhouse client -h
is ok
