### ISSUE TITLE
Is CnchMergeTree table is gloabal table?

### ISSUE THREAD

**Issue by xiaohu-zhang** [ByConity/ByConity#531]
As clickhouse , usually we create table with 2 steps:
1. create table base_block_serials_local on cluster 'default'
(
    label String,
    start UInt64,
    end   UInt64
)
    engine = ReplicatedMergeTree('/clickhouse/tables/chain_ethereum/base_block_serials__dbt_tmp_local/{shard}/{uuid}',
             '{replica}')
        ORDER BY (label, start, end)
        SETTINGS index_granularity = 8192;
2. create table base_block_serials on cluster 'default'
(
    label String,
    start UInt64,
    end   UInt64
)
    engine = Distributed('default_cluster', 'chain_ethereum', 'base_block_serials_local', sipHash64(start));

and base_block_serials is global table , base_block_serials_local is not. select base_block_serials_local will only get data from current node.

my question is ,is CnchMergeTree table is gloabal,and insert data into CnchMergeTree table will automaticly sharding to all nodes? thus means, if I select from CnchMergeTree table, the data is not just current node but all the data from all nodes.

If not, what should I do to get the same target as Distributed engine in ck？

**Comment by dmthuc** [comment]
Hi @xiaohu-zhang , yeah CnchMergeTree is global table. And it stores data in HDFS/S3. Select from CnchMergeTree in different server node will get the same result

**Comment by dmthuc** [comment]
Yeah, we have a settings can be used to specified which virtual warehouse(a group of worker node) to execute the query. Sharding are automatically

**Comment by dmthuc** [comment]
Hi, it is not needed. Most of query on Cnch table engine will be distributed to workers
