### ISSUE TITLE
multipul replica of hdfs-namenode supported?

### ISSUE THREAD

**Issue by hillbun** [ByConity/ByConity#533]
```
kubectl get sts -n byconity
byconity-hdfs-namenode   1/1     11m
```

current replica of hdfs-namenode is 1,  does it support to scale?

**Comment by dmthuc** [comment]
I think we need a namenode proxy to support multiple namenode

**Comment by dmthuc** [comment]
Hi @wordhardqi , could you help to answer the question

**Comment by wordhardqi** [comment]
https://github.com/ByConity/byconity.github.io/pull/169
