### ISSUE TITLE
Can not install  in 2 differrent namespace

### ISSUE THREAD

**Issue by hillbun** [ByConity/ByConity#538]
Iuse helm to install
https://github.com/ByConity/byconity-deploy

1. firstly, install in namespace byconity is OK

helm upgrade --install --namespace byconity -f ./chart2/byconity/values.yaml byconity ./chart2/byconity --set fdb.enabled=false
helm upgrade --install --namespace byconity -f ./chart2/byconity/values.yaml byconity ./chart2/byconity

2. next, I try to install into another namespace kaya-dev, but failed.

helm upgrade --install --namespace kaya-dev -f ./chart/byconity/values.yaml byconity ./chart/byconity --set fdb.enabled=false

```
Release "byconity" does not exist. Installing it now.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "foundationdbbackups.apps.foundationdb.org" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "kaya-dev": current value is "byconity"

```

**Comment by hillbun** [comment]
@dmthuc 

Please  advice,  thanks.

**Comment by dmthuc** [comment]
Hi @weigangchen1 , please help

**Comment by hillbun** [comment]
@weigangchen1     please help on this issue,   thanks

**Comment by weigangchen1** [comment]
> Iuse helm to install https://github.com/ByConity/byconity-deploy
> 
> 1. firstly, install in namespace byconity is OK
> 
> helm upgrade --install --namespace byconity -f ./chart2/byconity/values.yaml byconity ./chart2/byconity --set fdb.enabled=false helm upgrade --install --namespace byconity -f ./chart2/byconity/values.yaml byconity ./chart2/byconity
> 
> 2. next, I try to install into another namespace kaya-dev, but failed.
> 
> helm upgrade --install --namespace kaya-dev -f ./chart/byconity/values.yaml byconity ./chart/byconity --set fdb.enabled=false
> 
> ```
> Release "byconity" does not exist. Installing it now.
> Error: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "foundationdbbackups.apps.foundationdb.org" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "kaya-dev": current value is "byconity"
> ```

 fdb crd dumplicated. can comment out  all crd files in the following folder when you try to deploy in another namespace.
 https://github.com/ByConity/byconity-deploy/tree/master/chart/byconity/charts/fdb-operator/templates/crds

**Comment by hillbun** [comment]
@weigangchen1 

`Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "byconity-hdfs-namenode" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "kaya-dev": current value is "byconity"`

But another problem issued.

**Comment by weigangchen1** [comment]
ClusterRole can not be created repeatedly.

hillbun ***@***.***> 于2023年8月3日周四 10:17写道：
