### ISSUE TITLE
What's usage of zk?

### ISSUE THREAD

**Issue by hillbun** [ByConity/ByConity#540]
What's usage of zk?  if I enable it

**Comment by dmthuc** [comment]
Hi @hillbun , it is for leader election and leader discovery

**Comment by hillbun** [comment]
helm chart default value is disabled.

it is leader election and leader discovery  for which resource?

**Comment by hustnn** [comment]
> 

mainly for server, tso and rm.

**Comment by hillbun** [comment]
@hustnn 

Is zk in the helm chart,  or I need to install it manually?

**Comment by hillbun** [comment]
I need  information，thanks

**Comment by hustnn** [comment]
> @hustnn
> 
> Is zk in the helm chart, or I need to install it manually?

In ByConity, you don't need to zk. We are just using the keeper, it is already embedded. We plan to add HA support in byconity-deployment repo in late of Aug.

**Comment by hillbun** [comment]
in HA support in byconity-deployment , ZK  is needed or not?

**Comment by dmthuc** [comment]
Hi @hillbun , in HA support in byconity-deployment ZK is not needed. My college said in tmr he will updated the byconity-deploy repo to support HA

**Comment by dmthuc** [comment]
> that means ZK is not required at all, now or future HA supported?

yeah
