### ISSUE TITLE
HA with keeper - Q3

### ISSUE THREAD

**Issue by hustnn** [ByConity/ByConity#547]
Provide the HA ability for TSO, server and RM with the help of self-included keeper component.

For this feature, we need detailed doc to let user know how to config it in both k8s and physical deployment mode.

**Comment by weigangchen1** [comment]
You can refer to this example.
https://github.com/ByConity/byconity-deploy/blob/master/examples/k8s/value_HA_example.yaml
Especially the tso part，including additionalVolumeClaimTemplates、additionalVolumes、configOverwrite and the replicas of server、rm、tso。
besides, you need to add zookeeper tag in the files. dae mon-manager.yaml、server.yaml、resource-manager.yaml、tso.yaml and worker.yaml https://github.com/ByConity/byconity-deploy/tree/master/chart/byconity/files
here is an example https://github.com/ByConity/byconity-deploy/blob/master/chart/byconity/files/tso.yaml#L39
but i comment it out now.
