### ISSUE TITLE
Support RBAC (role based access control) - Q3 (project https://github.com/orgs/ByConity/projects/4)

### ISSUE THREAD

**Issue by hustnn** [ByConity/ByConity#548]
It is tracked in this project. https://github.com/orgs/ByConity/projects/4/views/1

**Comment by vivek-debug** [comment]
1. RBAC picked [here](https://github.com/ByConity/ByConity/pull/662)
2. RFC added [here](https://github.com/ByConity/ByConity/issues/660)
3. User documentation added [here](https://github.com/ByConity/byconity.github.io/pull/180)
