### ISSUE TITLE
能否提高数据写入速率？  比如多线程？

### ISSUE THREAD

**Issue by hillbun** [ByConity/ByConity#571]
我发现在K8S部署后，写入到集群内的HDFS和S3存储，速率都不高，特别是S3

能否提高数据写入速率？  比如多线程？

**Comment by Clark0** [comment]
There's a setting to control the number of dumping threads, by default it's disabled, can you try with `SETTINGS max_threads_for_cnch_dump = 16`

**Comment by hillbun** [comment]
in which xml file to config it?

**Comment by Clark0** [comment]
it's a query setting, you can use run the SET SQL `SET max_threads_for_cnch_dump = 16` or attach it to the end of the sql `SETTINGS max_threads_for_cnch_dump = 16` in client
