### ISSUE TITLE
clickhouse-keeper instead of foundationDB

### ISSUE THREAD

**Issue by UnamedRus** [ByConity/ByConity#58]
**Use case**
clickhouse-keeper also have support for key-value storage.

Simplify setup for endusers, have less dependency on external projects.
I didn't dig into codebase, so it's unclear for me, how much is byconity depends on foundationdb featureset, but it seems it also support bytekv, which is another type of key-value storage, so it seems that it's possible to do.

**Comment by LiuYangkuan** [comment]
House-keeper exports APIs which are the same as zookeeper. But zookeeper is weak when user needs prefix-scan.

**Comment by hustnn** [comment]
@UnamedRus 

> I didn't dig into codebase, so it's unclear for me, how much is byconity depends on foundationdb featureset


ByConity uses foundationdb for metadata storage purpose, similar to how snowflake uses foundationdb. 

>  but it seems it also support bytekv, which is another type of key-value storage, so it seems that it's possible to do.

Bytekv is another distributed key-value store but it is not open source. ByConity did some catalog api abstraction, so it can be extended to different distributed key-value store.
