### ISSUE TITLE
How to setup CLion development environment?

### ISSUE THREAD

**Issue by mdianjun** [ByConity/ByConity#582]
(you don't have to strictly follow this form)

## Question

<img width="652" alt="image" src="https://github.com/ByConity/ByConity/assets/12122541/a361bef1-f2a7-486a-b8e3-1bf6a163ccf8">

**Comment by hustnn** [comment]
Have you install fdb-cli？ https://github.com/ByConity/ByConity#1-prepare-prerequisites
