### ISSUE TITLE
Trying to ALTER RENAME key old_column_name column which is a part of key expression SQLSTATE: HY000

### ISSUE THREAD

**Issue by zhbdesign** [ByConity/ByConity#59]
# Step 1: create a table 
CREATE TABLE db_name.table_name
(
    `order_by_column` String,
    `old_column_name` Int64
)
ENGINE = `CnchMergeTree`
ORDER BY (`old_column_name`)

# Step 2: rename column
ALTER TABLE db_name.table_name RENAME COLUMN old_column_name TO new_column_name

ClickHouse exception, code: 524, host: 10.100.3.48, port: 8123; Code: 524, e.displayText() = DB::Exception: Trying to ALTER RENAME key old_column_name column which is a part of key expression SQLSTATE: HY000 (version 21.8.7.1)

**Comment by chenxing-xc** [comment]
this should be as design, order by column can not be renamed for now.

**Comment by zhbdesign** [comment]
> this should be as design, order by column can not be renamed for now.

The documentation needs to modify the second step and specify restrictions on use
