### ISSUE TITLE
renew credentials too often

### ISSUE THREAD

**Issue by xingcici** [ByConity/ByConity#591]
![image](https://github.com/ByConity/ByConity/assets/38656144/a5da0742-1a79-4b30-a91c-8ced0992b381)

Hi, I found that the server/writer/reader are all renew credentials very often. And the kerbs ticket cache is refresh very frequently. 
Is that normal?
<img width="601" alt="image" src="https://github.com/ByConity/ByConity/assets/38656144/6da653d6-1a58-4ae6-909a-d26e5d3447d4">

docker version : latest
hdfs cluster :  exist hdfs cluster

**Comment by dmthuc** [comment]
Hi @wordhardqi , could you help to answer this question?

**Comment by wordhardqi** [comment]
@dmthuc  i am not familiar with this part. I spot one potential issue. Whenever we created a new hdfs filesystem, we will run kerberosInit and whenever we created a new readBufferFromByteHdfs, we will create a new filesystem. We might call the kerberosInit too often. As for why the renew request failed, @xingcici could u check the KDC log?

**Comment by dmthuc** [comment]
> @dmthuc i am not familiar with this part. I spot one potential issue. Whenever we created a new hdfs filesystem, we will run kerberosInit and whenever we created a new readBufferFromByteHdfs, we will create a new filesystem. We might call the kerberosInit too often. As for why the renew request failed, @xingcici could u check the KDC log?

yeah, this is part gc job. It try to remove outdated file. As I can see here is that is is failed to remove certain file

**Comment by dmthuc** [comment]
We have found the issue with the file not found

**Comment by xingcici** [comment]
> @dmthuc i am not familiar with this part. I spot one potential issue. Whenever we created a new hdfs filesystem, we will run kerberosInit and whenever we created a new readBufferFromByteHdfs, we will create a new filesystem. We might call the kerberosInit too often. As for why the renew request failed, @xingcici could u check the KDC log?

Hi, I do not find the KDC log on byconity-server（Or can you tell me in which dir.）。And the KDC sever log shows like below.
<img width="1221" alt="image" src="https://github.com/ByConity/ByConity/assets/38656144/e6ecb98f-74bc-4802-8bf4-da8cee996a94">

**Comment by hustnn** [comment]
> > @dmthuc i am not familiar with this part. I spot one potential issue. Whenever we created a new hdfs filesystem, we will run kerberosInit and whenever we created a new readBufferFromByteHdfs, we will create a new filesystem. We might call the kerberosInit too often. As for why the renew request failed, @xingcici could u check the KDC log?
> 
> Hi @wordhardqi , I have found the bug with part gc that that cause failed to delete file. But about the issue run kerberosInit whenever we create a new readBufferFromByteHdfs, is this normal?

what is the gc bug? If kerberos authentication is enabled, I think it is expected with kerberosInit when reading.

**Comment by dmthuc** [comment]
> > > @dmthuc i am not familiar with this part. I spot one potential issue. Whenever we created a new hdfs filesystem, we will run kerberosInit and whenever we created a new readBufferFromByteHdfs, we will create a new filesystem. We might call the kerberosInit too often. As for why the renew request failed, @xingcici could u check the KDC log?
> > 
> > 
> > Hi @wordhardqi , I have found the bug with part gc that that cause failed to delete file. But about the issue run kerberosInit whenever we create a new readBufferFromByteHdfs, is this normal?
> 
> what is the gc bug? If kerberos authentication is enabled, I think it is expected with kerberosInit when reading.

The issue is that the GC try to remove the data part that already have its data file in HDFS removed. Yeah, it is expected with kerberos init when reading but i think we don't need to call it everytime. caichen is handling the issue with kerberos
