### ISSUE TITLE
install byconity byconity-server-0 failed

### ISSUE THREAD

**Issue by Zhuyaguang782126** [ByConity/ByConity#593]
(you don't have to strictly follow this form)

## Question

 byconity-server-0 健康检查一直失败

![image](https://github.com/ByConity/ByConity/assets/140598706/0b6a1cc0-79b2-4710-9d1b-2431530e6bdf)

**Comment by dmthuc** [comment]
Hi @weigangchen1 , we need to add listen try to support ipv4 only enviroment

**Comment by weigangchen1** [comment]
> byconity-server-0 日志
> 
> ![image](https://user-images.githubusercontent.com/140598706/259354109-b5677300-1ade-4bcc-9efa-a8d92e97325d.png)

please pull the latest code and retry
