### ISSUE TITLE
复杂查询执行模型设置问题

### ISSUE THREAD

**Issue by hillbun** [ByConity/ByConity#603]
https://byconity.github.io/zh-cn/docs/advanced-guide/complex-query-model-and-optimisation

上面写道

开启优化器会自动走复杂查询执行模型。通过配置 enable_optimizer=1，或者 dialect_type='ANSI' 可以开启。

请问是手动执行，还是可以写在配置文件？

**Comment by dmthuc** [comment]
Hi @hillbun , it can be written in configuration file, you can add this value to users.xml file in all servers

**Comment by hillbun** [comment]
profiles:
  default:
    load_balancing: random
    log_queries: 1
    max_execution_time: 180
    exchange_timeout_ms: 300000
    enable_optimizer = 1

这样吗

**Comment by dmthuc** [comment]
> profiles: default: load_balancing: random log_queries: 1 max_execution_time: 180 exchange_timeout_ms: 300000 enable_optimizer = 1
> 
> 这样吗

Yeah, this will do
