### ISSUE TITLE
cannot alter table modify setting max_bytes_to_merge_at_max_space_in_pool

### ISSUE THREAD

**Issue by skyoct** [ByConity/ByConity#608]
(you don't have to strictly follow this form)

### Briefly describe the bug
Cannot alter table modify setting max_bytes_to_merge_at_max_space_in_pool and max_bytes_to_merge_at_min_space_in_pool.
When modifying, it will appear `Code: 344, e.displayText() = DB::Exception: Setting max_bytes_to_merge_at_max_space_in_pool cannot be modified SQLSTATE: HY000 (version 21.8.7.1)`

### The result you expected
These parameters can be set normally
### How to Reproduce
`alter table xxxx modify setting max_bytes_to_merge_at_max_space_in_pool=5368709120;`
### Version
`21.8.7.1`

**Comment by hustnn** [comment]
@zeromem I found this config is not added to the list allowing modifying. pls help to check

**Comment by zeromem** [comment]
@skyoct hi, now in the newest version, you can use a new setting `cnch_merge_max_total_bytes_to_merge` for limiting the max bytes of a merged part

**Comment by skyoct** [comment]
@zeromem Okay, thank you very much
