### ISSUE TITLE
Exception on client: Code: 73. DB::Exception: Unknown format VALUES: data for INSERT was parsed from query. (UNKNOWN_FORMAT)

### ISSUE THREAD

**Issue by zhbdesign** [ByConity/ByConity#61]
INSERT INTO test.example_table FORMAT VALUES (1, 'a', '2021-07-27'), (2, 'b', '2021-07-27');

Exception on client:
Code: 73. DB::Exception: Unknown format VALUES: data for INSERT was parsed from query. (UNKNOWN_FORMAT)

**Comment by chenxing-xc** [comment]
@zhbdesign which client were you using? as this exception is thrown from client side, is it client compatible issue?

**Comment by zhbdesign** [comment]
> @zhbdesign which client were you using? as this exception is thrown from client side, is it client compatible issue?

This is the same error with command line execution on the server

**Comment by chenxing-xc** [comment]
oh, you don't need to specify FORMAT here, just issue

**Comment by zhbdesign** [comment]
> oh, you don't need to specify FORMAT here, just issue INSERT INTO test.example_table VALUES (1, 'a', '2021-07-27'), (2, 'b', '2021-07-27');

document error
