### ISSUE TITLE
The server service keeps printing the following logs. Check whether the logs are affected

### ISSUE THREAD

**Issue by zhbdesign** [ByConity/ByConity#63]
2023.01.19 09:16:00.373015 [ 106221 ] {} <Warning> TransactionCleaner: Transaction 438852010306437120 is still running.

**Comment by hustnn** [comment]
Is it happening in the deployment with https://github.com/ByConity/byconity-docker?

**Comment by zhbdesign** [comment]
> Is it happening in the deployment with https://github.com/ByConity/byconity-docker?

yes

**Comment by hustnn** [comment]
Did you change any config for it? Like TXN_GC option.

**Comment by zhbdesign** [comment]
> Did you change any config for it? Like TXN_GC option.

no，Can't be reproduced？

**Comment by hustnn** [comment]
yes, can you upload the server log and dm log? Thanks

**Comment by zhbdesign** [comment]
This should be caused by the cnch table creation in the default library

**Comment by hustnn** [comment]
The fix is merged and let me close this issue.
