### ISSUE TITLE
在mac上运行make image搭建环境时失败了

### ISSUE THREAD

**Issue by SYaoJun** [ByConity/ByConity#636]
(you don't have to strictly follow this form)
<img width="1496" alt="image" src="https://github.com/ByConity/ByConity/assets/17510621/ebb37466-a2ee-453d-9ef5-105bd82c2cd5">

**Comment by Clark0** [comment]
since FoundationDB cannot work propertly in Docker on Apple Silicon machines, docker build does not work on mac m1/m2.

**Comment by Clark0** [comment]
Fails on installing dev dependencies, is there a network issue?

**Comment by SYaoJun** [comment]
> since FoundationDB cannot work propertly in Docker on Apple Silicon machines, docker build does not work on mac m1/m2.

Thanks, maybe I need to change a developing environment.
