### ISSUE TITLE
hdfs-datanode and hdfs-namenode can not start

### ISSUE THREAD

**Issue by hillbun** [ByConity/ByConity#650]
```
byconity-daemon-manager-64bc864b8f-d9zmm                     1/1     Running     0             36m
byconity-fdb-log-1                                           2/2     Running     0             33m
byconity-fdb-log-2                                           2/2     Running     0             33m
byconity-fdb-log-3                                           2/2     Running     0             33m
byconity-fdb-operator-b76888b4d-l8262                        1/1     Running     0             36m
byconity-fdb-stateless-1                                     2/2     Running     0             33m
byconity-fdb-stateless-2                                     2/2     Running     0             33m
byconity-fdb-stateless-3                                     2/2     Running     0             33m
byconity-fdb-storage-1                                       2/2     Running     0             33m
byconity-fdb-storage-2                                       2/2     Running     0             33m
byconity-fdb-storage-3                                       2/2     Running     0             33m
byconity-fdbcli-895b9bf57-g9lnf                              1/1     Running     0             36m
byconity-hdfs-datanode-0                                     0/1     Init:0/1    0             2m36s
byconity-hdfs-datanode-1                                     0/1     Init:0/1    0             2m47s
byconity-hdfs-datanode-2                                     0/1     Init:0/1    0             2m47s
byconity-hdfs-namenode-0                                     1/1     Running     1 (18s ago)   2m46s
byconity-hdfs-shell-5b69cb45cc-9sths                         1/1     Running     0             36m
byconity-resource-manager-6f4c949bd9-24ng2                   1/1     Running     0             39m
byconity-server-0                                            1/1     Running     0             19m
byconity-tso-7d86c9687c-cgvp6                                1/1     Running     0             19m
byconity-vw-vw-default-0                                     1/1     Running     0             18m
byconity-vw-vw-write-0                                       1/1     Running     0             18m
```

```
Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Scheduled  3m12s  default-scheduler  Successfully assigned kaya-dev/byconity-hdfs-datanode-0 to eklet-subnet-ezvuf44o-100832
  Normal  Starting   3m12s  eklet              Starting pod sandbox eks-carndf98
  Normal  Starting   53s    eklet              Sync endpoints
  Normal  Pulled     26s    eklet              Container image "alpine:3.10.2" already present on machine
  Normal  Created    26s    eklet              Created container wait-for-namenode-startup
  Normal  Started    26s    eklet              Started container wait-for-namenode-startup
```

```
root@kaya-vpn:~# kubectl logs  byconity-hdfs-datanode-0  -n kaya-dev
Defaulted container "datanode" out of: datanode, wait-for-namenode-startup (init)
Error from server (InternalError): Internal error occurred: container "datanode" in pod "byconity-hdfs-datanode-0" is waiting to start: PodInitializing
```

How to check more details of error?

**Comment by wordhardqi** [comment]
the byconity-hdfs-datanode-0 is still in initilization?

**Comment by wordhardqi** [comment]
use ·kubectl describe pod· to check whether there is any error msg?

**Comment by weigangchen1** [comment]
> ```
> byconity-daemon-manager-64bc864b8f-d9zmm                     1/1     Running     0             36m
> byconity-fdb-log-1                                           2/2     Running     0             33m
> byconity-fdb-log-2                                           2/2     Running     0             33m
> byconity-fdb-log-3                                           2/2     Running     0             33m
> byconity-fdb-operator-b76888b4d-l8262                        1/1     Running     0             36m
> byconity-fdb-stateless-1                                     2/2     Running     0             33m
> byconity-fdb-stateless-2                                     2/2     Running     0             33m
> byconity-fdb-stateless-3                                     2/2     Running     0             33m
> byconity-fdb-storage-1                                       2/2     Running     0             33m
> byconity-fdb-storage-2                                       2/2     Running     0             33m
> byconity-fdb-storage-3                                       2/2     Running     0             33m
> byconity-fdbcli-895b9bf57-g9lnf                              1/1     Running     0             36m
> byconity-hdfs-datanode-0                                     0/1     Init:0/1    0             2m36s
> byconity-hdfs-datanode-1                                     0/1     Init:0/1    0             2m47s
> byconity-hdfs-datanode-2                                     0/1     Init:0/1    0             2m47s
> byconity-hdfs-namenode-0                                     1/1     Running     1 (18s ago)   2m46s
> byconity-hdfs-shell-5b69cb45cc-9sths                         1/1     Running     0             36m
> byconity-resource-manager-6f4c949bd9-24ng2                   1/1     Running     0             39m
> byconity-server-0                                            1/1     Running     0             19m
> byconity-tso-7d86c9687c-cgvp6                                1/1     Running     0             19m
> byconity-vw-vw-default-0                                     1/1     Running     0             18m
> byconity-vw-vw-write-0                                       1/1     Running     0             18m
> ```
> 
> ```
> Events:
>   Type    Reason     Age    From               Message
>   ----    ------     ----   ----               -------
>   Normal  Scheduled  3m12s  default-scheduler  Successfully assigned kaya-dev/byconity-hdfs-datanode-0 to eklet-subnet-ezvuf44o-100832
>   Normal  Starting   3m12s  eklet              Starting pod sandbox eks-carndf98
>   Normal  Starting   53s    eklet              Sync endpoints
>   Normal  Pulled     26s    eklet              Container image "alpine:3.10.2" already present on machine
>   Normal  Created    26s    eklet              Created container wait-for-namenode-startup
>   Normal  Started    26s    eklet              Started container wait-for-namenode-startup
> ```
> 
> ```
> root@kaya-vpn:~# kubectl logs  byconity-hdfs-datanode-0  -n kaya-dev
> Defaulted container "datanode" out of: datanode, wait-for-namenode-startup (init)
> Error from server (InternalError): Internal error occurred: container "datanode" in pod "byconity-hdfs-datanode-0" is waiting to start: PodInitializing
> ```
> 
> How to check more details of error?

kubectl describe pod xxx.  check if there is any error msg in containers part
