### ISSUE TITLE
Reached time out

### ISSUE THREAD

**Issue by luozhenglin** [ByConity/ByConity#656]
DB::Exception: 1008:[E1008]Reached timeout=90000ms @10.0.6.101:8124: While executing Remote SQLSTATE: HY000.

**Comment by Adora627** [comment]
> DB::Exception: 1008:[E1008]Reached timeout=90000ms @10.0.6.101:8124: While executing Remote SQLSTATE: HY000.

Hi could you describe how to reproduce this issue?

**Comment by kevinthfang** [comment]
no response. close issue
