### ISSUE TITLE
 Transaction is too old to perform reads or be committed

### ISSUE THREAD

**Issue by luozhenglin** [ByConity/ByConity#657]
Received exception from server (version 21.8.7)

 when collecting table xxx  having the following error: Code: 8067, e.displayText() = DB::Exception: Error whiling scanning data through FBDItrator. message: Transaction is too old to perform reads or be committed SQLSTATE: HY000,

**Comment by dmthuc** [comment]
Hi @luozhenglin , thank you for reporting the issue. I wonder what is the version that you are using and what is the query. I think this issue already been handled in latest code

**Comment by dmthuc** [comment]
And can you tell more about your ByConity setup?
