### ISSUE TITLE
Optimize query time to seconds

### ISSUE THREAD

**Issue by luozhenglin** [ByConity/ByConity#661]
I want to ask a question. Do you have any optimization suggestions?
There is a unified_native_transfer(block_number,block_hash,block_time,tx_hash,from,to,value,amount,transfer_type,_version,_sign) table with 3550431361 pieces of data.
The requirements are queried based on the from and to fields for details. The query now takes 16 minutes. Then did stats optimization. The query takes 6 minutes.
We want to achieve second-level queries. The following optimizations have been made.

create table v1_ethereum.unified_native_transfer_address_linked_1
(
     `linked_address` String,
    `block_number` UInt64,
    `block_hash` String,
    `block_time` DateTime('UTC'),
    `tx_hash` String,
    `from` String,
    `to` String,
    `value` Decimal(38, 0),
    `amount` Decimal(76, 18),
    `transfer_type` String,
    `_version` UInt8,
    `_sign` Int8
)
ENGINE = CnchMergeTree()
CLUSTER BY (linked_address) INTO 24 BUCKETS
PRIMARY KEY (linked_address, block_number, block_time, from, to, _version, _sign)
ORDER BY (linked_address, block_number, block_time, from, to, _version, _sign)
PARTITION BY (toYYYYMM(block_time))
SETTINGS storage_policy = 's3';
The from to field was extracted into the linked_address field, and the linked_address field was used for bucket storage and primary key. It took 11 minutes to perform the stats query. The current resources are 12 reader nodes, each 8core, 32g
I would like to ask if you have any experience or suggestions?

**Comment by luozhenglin** [comment]
The SQL statement before optimization is:

select block_number, block_hash, block_time, tx_hash, from, to, value, amount, transfer_type, _version
      from  unified_native_transfer_address_linked
      where `from` = '0XXXXXX'
         or `to` = '0XXXXXX'
      group by block_number, block_hash, block_time, tx_hash, from, to, value, amount, transfer_type, _version
      having sum(_sign) > 0.
 The optimized query statement is:
 select  block_number, block_hash, block_time, tx_hash, from, to, value, amount, transfer_type, _version
      from  unified_native_transfer_address_linked_1 where linked_address= '0XXXXXX'   group by block_number, block_hash, block_time, tx_hash, from, to, value, amount, transfer_type, _version
      having sum(_sign) > 0.

**Comment by wordhardqi** [comment]
could u enable optimzier and run explain analyze SQL to check the time of each step

**Comment by Adora627** [comment]
Turn on Optimizer and run Explain syntax: https://byconity.github.io/docs/advanced-guide/query-optimiser

**Comment by luozhenglin** [comment]
> Turn on Optimizer and run Explain syntax: https://byconity.github.io/docs/advanced-guide/query-optimiser

Using byconity/byconity:0.1.2 DOCKER image.
When executing EXPLAIN ANALYZE LOGICAL, Syntax error: failed at position 17 ('LOGICAL') (line 1, col 17) is thrown:

**Comment by luozhenglin** [comment]
Same error

**Comment by wordhardqi** [comment]
I tired on recent byconity, it‘s okay. Let me check older versions

**Comment by wordhardqi** [comment]
it's a bug. In the new version it should be fixed. 
There is no much room for schema optimization.

**Comment by luozhenglin** [comment]
Is there a new version of Docker Image？

**Comment by kevinthfang** [comment]
The bug has been fixed. Please run the analyze sql can update the result here.
