### ISSUE TITLE
master build fail in Debug mode

### ISSUE THREAD

**Issue by nzpznk** [ByConity/ByConity#667]
(you don't have to strictly follow this form)

## describe your build problem
I am learning the code, but after I pull the latest master branch commit #662 , and changed the **CUSTOM_CMAKE_BUILD_TYPE** to **"Debug"** in **build_bin.sh**, the building process fails in linking stage. 

The default build_bin.sh works well to build the repo in "RelWithDebInfo" mode.

### Building Environment

I used the official byconity-ci docker environment to build the project. And I can successfully build in RelWithDebInfo mode, but build only fails in Debug mode. So it should not be the environment problem.

### Full cmake and/or ninja output

The linker reported that the newly added declarations
https://github.com/ByConity/ByConity/blob/26b50755b08fb7b98ee79e3cc332f0e1532be820/src/Catalog/Catalog.cpp#L418-L427
can not find corresponding definitions.

The new variables are used here.
https://github.com/ByConity/ByConity/blob/26b50755b08fb7b98ee79e3cc332f0e1532be820/src/Catalog/Catalog.cpp#L5289-L5290

I global searched the new variables, and found that it seems that they shoud be defined using 
https://github.com/ByConity/ByConity/blob/26b50755b08fb7b98ee79e3cc332f0e1532be820/src/Common/ProfileEvents.cpp#L28

at here

https://github.com/ByConity/ByConity/blob/26b50755b08fb7b98ee79e3cc332f0e1532be820/src/Common/ProfileEvents.cpp#L784-L791

However the macro does not contain the new variables.

So I failed to find the definitions of the new variables.

But, How could the RelWithDebugInfo mode build successfully???

I'm confused now...

**Comment by nzpznk** [comment]
CMake output is here
[cmakeoutput.log](https://github.com/ByConity/ByConity/files/12572063/cmakeoutput.log)
ninja output is here.
[ninjaoutput.log](https://github.com/ByConity/ByConity/files/12572049/ninjaoutput.log)

**Comment by vivek-debug** [comment]
This issue is fixed here https://github.com/ByConity/ByConity/pull/673
