### ISSUE TITLE
byconity column rename,  query for new name failed

### ISSUE THREAD

**Issue by datavisorhenryzhao** [ByConity/ByConity#676]
(you don't have to strictly follow this form)

### Briefly describe the bug
after column rename (5 min later), query for new name will failed.
### The result you expected
query for new name should success
### How to Reproduce
1. create a table;
2. rename column_name to column_name_2;
3. wait 5 min, query column_name_2
### Version
just using https://github.com/ByConity/byconity-deploy (config with S3 as storage)

**Comment by wordhardqi** [comment]
@zeromem  could u take this

**Comment by zeromem** [comment]
> @zeromem could u take this

Sure, I will try to reproduce and fix it

**Comment by zeromem** [comment]
Hi @datavisorhenryzhao I can't reproduce the issue in my dev env using master branch. could you try the newest release version?

**Comment by zeromem** [comment]
Update: 
verison: 0.2.0 .
After RENAME is executed, the query on new column will not failed but data lost. I will fix this issue soon
