### ISSUE TITLE
create stats db.table_name failed

### ISSUE THREAD

**Issue by datavisorhenryzhao** [ByConity/ByConity#679]
(you don't have to strictly follow this form)

## Bug Report
when executing "create stats db.table_name" , failed
### Briefly describe the bug
just executing "create stats db.table_name",  database not exist

─elapsed_time─┐
│ alert_events │           30 │ Code: 279, e.displayText() = DB::NetException: All connection tries failed. Log: 

Code: 210, e.displayText() = DB::NetException: Connection refused (192.168.111.132:9000) SQLSTATE: 08000 (version 21.8.7.1)
Code: 210, e.displayText() = DB::NetException: Connection refused (192.168.111.132:9000) SQLSTATE: 08000 (version 21.8.7.1)
Code: 210, e.displayText() = DB::NetException: Connection refused (192.168.111.132:9000) SQLSTATE: 08000 (version 21.8.7.1)

: While executing Remote SQLSTATE: 08000 (version 21.8.7.1) │ 16.099103447 │
└──────────────┴──────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────┘
┌─table_name───┬─column_count─┬─row_count_or_error─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─elapsed_time─┐
│ alert_events │           30 │ Code: 81, e.displayText() = DB::Exception: Received from 192.168.111.132:9000. DB::Exception: Database neo doesn't exist SQLSTATE: 42000. Stack trace:

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x19e02db2 in /opt/byconity/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb665400 in /opt/byconity/bin/clickhouse
2. DB::DatabaseCatalog::assertDatabaseExistsUnlocked(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x14443cf0 in /opt/byconity/bin/clickhouse
3. DB::DatabaseCatalog::getDatabase(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x14444b47 in /opt/byconity/bin/clickhouse
4. DB::DatabaseCatalog::getDatabase(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context const>) const @ 0x144472b3 in /opt/byconity/bin/clickhouse
5. DB::Context::resolveStorageID(DB::StorageID, DB::Context::StorageNamespace) const @ 0x143a3a8d in /opt/byconity/bin/clickhouse
6. DB::JoinedTables::getLeftTableStorage() @ 0x14804fb0 in /opt/byconity/bin/clickhouse
7. 
### The result you expected
should succeed 
### How to Reproduce
create table with 40 million record in it;
### Version
just using https://github.com/ByConity/byconity-deploy (config with S3 as storage)

**Comment by wordhardqi** [comment]
@FluorineDog  could u help take a look

**Comment by wordhardqi** [comment]
The worker may get OOMed.

**Comment by FluorineDog** [comment]
We have reproduced similar problem internally, mainly due to sampling is working as expected. A PR is on the way to fix it.

**Comment by kevinthfang** [comment]
confirmed with @FluorineDog , the PR is for another issue. For this issue the worker may get OOMed as @wordhardqi mentioned. @datavisorhenryzhao Please confirm if you can still reproduce this issue?
