### ISSUE TITLE
skipped index: bloom filter not working

### ISSUE THREAD

**Issue by datavisorhenryzhao** [ByConity/ByConity#694]
(you don't have to strictly follow this form)

## Bug Report
when i use bloom type skip index, find it did not work, and will trigger full table scan
### Briefly describe the bug
the skipped index not working, and system.mutations is empty;
<img width="1422" alt="image" src="https://github.com/ByConity/ByConity/assets/142382355/670f3e28-5736-49d9-9752-567ed0b02981">

### The result you expected
the skipped index should working.
### How to Reproduce
1. create a table test, include eventId field(string type);
2. add skip index;
ALTER TABLE  event_result ADD INDEX eventId_index(eventId) TYPE bloom_filter(0.0001) GRANULARITY 1;
ALTER TABLE event_result  MATERIALIZE INDEX eventId_index;

3. query by skip index
select eventId from test where eventId in ("aaaa")

### Version
https://github.com/ByConity/byconity-deploy,  config with s3 as storage
     i try byconity:stable is not working

**Comment by dmthuc** [comment]
Hi @datavisorhenryzhao thank you for reporting the issue, @hustnn please help to look into this issue

**Comment by hustnn** [comment]
I think it is already fixed in our recent release, can you trying 0.2.1?
