### ISSUE TITLE
v0.2.0  part merge slow

### ISSUE THREAD

**Issue by skyoct** [ByConity/ByConity#703]
### Briefly describe the bug
part merge slow
### Version
0.2.0

**Comment by dmthuc** [comment]
Hi @skyoct , thank you for reporting the issue, could you help to provide more info about how slow?, we could get the info about part merge speed by select system system.server_part_log

**Comment by wordhardqi** [comment]
version 0.2.1 has fixed a bug which could increase merge speed @skyoct

**Comment by skyoct** [comment]
@dmthuc @dmthuc Okay, thank you
