### ISSUE TITLE
ClickHouse exception, code: 49, host: 10.100.3.48, port: 8123; Code: 49, e.displayText() = DB::Exception: DB::Exception: No daemon job found for ClusteringThread, this may always be caused by lack of config SQLSTATE: HY000. SQLSTATE: HY000 (version 21.8.7.1)

### ISSUE THREAD

**Issue by zhbdesign** [ByConity/ByConity#71]
select * from system.dm_bg_jobs;

**Comment by hustnn** [comment]
Can you provide the sql to for the clustering ? cc @dmthuc

**Comment by dmthuc** [comment]
Clustering thread is disabled by @canhld94 in DaemonManager.cpp:178 recently. I think the Clustering feature is not finished yet

**Comment by canhld94** [comment]
@dmthuc it should be ready, we accidentally remove this in default settings. If users want to use, they can config the job in daemon config.

**Comment by hustnn** [comment]
@canhld94  @vivek-debug Do you known which setting do we missed？Maybe we can add it back

**Comment by dmthuc** [comment]
I will try to fix the issue by this PR https://github.com/ByConity/ByConity/pull/116

**Comment by hustnn** [comment]
Thanks @dmthuc ， we can close it now.
