### ISSUE TITLE
v0.2.0 cannot run on centos7 system

### ISSUE THREAD

**Issue by juppylm** [ByConity/ByConity#712]
I do this by executing :
**docker pull byconity/byconity:0.2.0**
I downloaded the docker version of byconity on my centos7 system, but the byconity service cannot be started.

And, I downloaded the **byconity-common-static-0.2.0.x86_64.rpm** installation package, but it cannot be installed by executing 
**rpm -ivh byconity-common-static-0.2.0.x86_64.rpm**

The error is reported as shown below:
![2023-09-20 17-18-02 的屏幕截图](https://github.com/ByConity/ByConity/assets/31834016/6bdbe854-b37c-4d14-a81b-ad1299d4c374)

**Comment by dmthuc** [comment]
Hi @juppylm , it seems our recently modification has cause this issue, could you help to copy the error message, or help to translate them to english?

**Comment by juppylm** [comment]
ok, this is information:

>  rpm -ivh byconity-common-static-0.2.0.x86_64.rpm
In preparation... ################################# [100%]
Upgrading/installing...
   1:byconity-common-static-0:0.2.0-1 ################################ [100 %]
Error: Unzipping archive in file /usr/bin/clickhouse;650b9b66 failed: cpio: digest mismatch
Error: byconity-common-static-0:0.2.0-1.x86_64: Installation failed

**Comment by juppylm** [comment]
The MD5 value of the installation package I downloaded is:
![2023-09-21 09-52-56屏幕截图](https://github.com/ByConity/ByConity/assets/31834016/74712268-ca75-41e9-88d7-05ffae0a7196)

**Comment by dmthuc** [comment]
Hi @juppylm , thank you very much for your info. I wonder can you check if it is possible to install with `rpm -i --nofiledigest byconity-common-static-0.2.0.x86_64.rpm`? And could you provide some info with docker failure?

**Comment by dmthuc** [comment]
> Hi @juppylm , thank you very much for your info. I wonder can you check if it is possible to install with `rpm -i --nofiledigest byconity-common-static-0.2.0.x86_64.rpm`? And could you provide some info with docker failure?
Btw, how do you deployed byconity docker image, are you using k8s or using docker compose? We will also check on our side too

**Comment by juppylm** [comment]
I tried two ways to install byconity on my centos7 system machine:
1) Download the rpm package and use the rpm -ivh byconity-common-static-0.2.0.x86_64.rpm command to install it. The error message is as follows:

> [root@localhost byconity]# rpm -ivh byconity-common-static-0.2.0.x86_64.rpm
In preparation... ################################# [100%]
Upgrading/installing...
1:byconity-common-static-0:0.2.0-1 ################################ [100 %]
Error: Unzipping archive in file /usr/bin/clickhouse;650b9b66 failed: cpio: digest mismatch
Error: byconity-common-static-0:0.2.0-1.x86_64: Installation failed

2) Use docker-compose to pull byconity/byconity:0.2.0 through docker. The error message is as follows:

> [root@32f06a42e759 bin]# clickhouse tso-server --config-file=/config/tso.yml
libc++abi: terminating with uncaught exception of type std::invalid_argument: stoul: no conversion
Aborted (core dumped)

**Comment by dmthuc** [comment]
Hi @Clark0 , currently byconity docker image has issue with centos, please take a look

**Comment by dmthuc** [comment]
> I tried two ways to install byconity on my centos7 system machine:
> 
> 1. Download the rpm package and use the rpm -ivh byconity-common-static-0.2.0.x86_64.rpm command to install it. The error message is as follows:
> 
> > [root@localhost byconity]# rpm -ivh byconity-common-static-0.2.0.x86_64.rpm
> > In preparation... ################################# [100%]
> > Upgrading/installing...
> > 1:byconity-common-static-0:0.2.0-1 ################################ [100 %]
> > Error: Unzipping archive in file /usr/bin/clickhouse;650b9b66 failed: cpio: digest mismatch
> > Error: byconity-common-static-0:0.2.0-1.x86_64: Installation failed
> 
> 2. Use docker-compose to pull byconity/byconity:0.2.0 through docker. The error message is as follows:
> 
> > [root@32f06a42e759 bin]# clickhouse tso-server --config-file=/config/tso.yml
> > libc++abi: terminating with uncaught exception of type std::invalid_argument: stoul: no conversion
> > Aborted (core dumped)

Thank you, i think both the problem should related to the library

**Comment by dmthuc** [comment]
Hi @juppylm , I think the problem with the rpm file is that the `clickhouse` binary in this version is bigger than 4 GB so that the package won't work with centos7. Can you try to download the .tgz package `https://github.com/ByConity/ByConity/releases/download/0.2.0/byconity-common-static-0.2.0-amd64.tgz` to get the clickhouse binary. And install the package rmp package with lower version `https://github.com/ByConity/ByConity/releases/download/0.1.1/byconity-common-static-0.1.1.x86_64.rpm` . Then use the clickhouse binary version 0.2.0 to override the binary that provide by package version 0.1.1

**Comment by juppylm** [comment]
By using gdb debugging, we found that an error occurred in **init_max_numa_node**. In the [src/Common/SystemUtils.cpp](https://github.com/ByConity/ByConity/blob/dc43a1b01d63f9b87ddaec8489faf43144bf87d0/src/Common/SystemUtils.cpp) file, we need to read the contents of the **/sys/devices/system/node/has_cpu** file. In the centos system, this file has no value. Therefore, a **std::invalid_argument** exception will occur, causing the byconity program to fail to run. See the solution:
#720

**Comment by dmthuc** [comment]
> #720

Great catch. This will fix the docker compose issue
