### ISSUE TITLE
ClickHouse exception, code: 4004, host: 10.100.3.48, port: 8123; Code: 4004, e.displayText() = DB::Exception: Resource group manager not available! SQLSTATE: HY000 (version 21.8.7.1)

### ISSUE THREAD

**Issue by zhbdesign** [ByConity/ByConity#72]
docker-compose.yml.multiworkers starts the service and resource-manage has been started.

select * from system.resource_groups;

**Comment by hustnn** [comment]
It is expected. We are not config this component in the  docker-compose.yml.multiworkers cc @canhld94

**Comment by Adora627** [comment]
We think the docker deployment guide should be refined by making it more clear that resource manager is not included. So this is a doc issue.

**Comment by canhld94** [comment]
> We think the docker deployment guide should be refined by making it more clear that resource manager is not included. So this is a doc issue.


Docker deployment includes resource manager. This resource group is another feature from quite a long time ago, not sure if it's in active development.

**Comment by canhld94** [comment]
@Adora627 I just confirmed with @tchuangbd and confirm that this feature (resource groups) is legacy and may be removed in the future. Can label this issue as unfinished code.

**Comment by Adora627** [comment]
Conclusion:

**Comment by kevinthfang** [comment]
Close as we have the conclusion and no further discussion
