### ISSUE TITLE
Why INSERT VALUES queries cannot be auto forwarded from server to workers?

### ISSUE THREAD

**Issue by xiaomo728** [ByConity/ByConity#722]
Currently, in `InterpreterInsertQuery.cpp`, the logic of forwarding INSERT query to workers is as following:

```
......
    StorageCnchMergeTree * cnch_merge_tree = dynamic_cast<StorageCnchMergeTree *>(table.get());
    /// Directly forward the query to cnch worker if select or infile
    if (getContext()->getServerType() == ServerType::cnch_server && (query.select || query.in_file) && cnch_merge_tree)
    {
        /// Handle the insert commit for insert select/infile case in cnch server.
        BlockInputStreamPtr in = cnch_merge_tree->writeInWorker(query_ptr, metadata_snapshot, getContext());

        bool enable_staging_area_for_write = settings.enable_staging_area_for_write;
        if (const auto * cnch_table = dynamic_cast<const StorageCnchMergeTree *>(table.get());
            cnch_table && metadata_snapshot->hasUniqueKey() && !enable_staging_area_for_write)
        {
            /// for unique table, insert select|infile is committed from worker side
            res.in = std::move(in);
        }
        else
        {
            auto txn = getContext()->getCurrentTransaction();
            txn->setMainTableUUID(table->getStorageUUID());
            res.in = std::make_shared<TransactionWrapperBlockInputStream>(in, std::move(txn));
        }
        return res;
    }

    BlockOutputStreams out_streams;
    ......

```

My questions: 
1. Why we only forward INSERT SELECT or INSERT INFILE queries to workers here? 
2. Is the design of not forwarding INSERT VALUES queries functionally difficult to implement, or would it cause performance issues?

Thank you very much.

**Comment by dmthuc** [comment]
Hi @xiaomo728 , thank you for your concert. When INSERT VALUES or cat file | ./clickhouse client -q "INSERT". The parsing work will be done at client side. It will convert text data into clickhouse binary format. When come to server the block of data is ready for insert. So we don't need to forward them to worker. Let me know if it is unclear for you

**Comment by xiaomo728** [comment]
> Hi @xiaomo728 , thank you for your concert. When INSERT VALUES or cat file | ./clickhouse client -q "INSERT". The parsing work will be done at client side. It will convert text data into clickhouse binary format. When come to server the block of data is ready for insert. So we don't need to forward them to worker. Let me know if it is unclear for you

@dmthuc Thx and I understood. However, we now have a scenario where we import a large amount of data to the server using the INSERT VALUE query generated by the pre-order service, so we want to use the ability of the write worker to execute the INSERT VALUE query. I wonder if this is feasible?

**Comment by dmthuc** [comment]
Hi @xiaomo728 , in that case you can connect to worker directly and enable this setting. Please see this example
```
SET prefer_cnch_catalog=1; INSERT INTO test.test_direct_insert VALUES (1, 1);
```

**Comment by xiaomo728** [comment]
> Hi @xiaomo728 , in that case you can connect to worker directly and enable this setting. Please see this example
> 
> ```
> SET prefer_cnch_catalog=1; INSERT INTO test.test_direct_insert VALUES (1, 1);
> ```

@dmthuc Ok, thanks for your guidance. I will try it first.

**Comment by xiaomo728** [comment]
> Hi @xiaomo728 , in that case you can connect to worker directly and enable this setting. Please see this example
> 
> ```
> SET prefer_cnch_catalog=1; INSERT INTO test.test_direct_insert VALUES (1, 1);
> ```

@dmthuc Could I send the INSERT VALUES query to worker directly with JDBC connection?

**Comment by dmthuc** [comment]
Hi @xiaomo728 , i haven't tried but i think it should work the same way as send to server. At the moment we have an issue that ClickHouse community client not able to connect to Byconity. We have solve this issue in internal branch and will pick the fix to ByConity in probably next week

**Comment by dmthuc** [comment]
> @dmthuc we're using the HTTP interface to do the insert, something like
> 
> ```
> clickhouse-local --query "SELECT ..." --format Native | gzip -c | curl "http://byconity-server:8123/?query=INSERT INTO my_logs"
> ```
> 
> does it mean this "insert" will actually be performed by the server and hence the workers will not be able to help with the performance / throughput?
> 
> Is the better way to do this by directly connecting to the workers as suggested above and running with following?
> 
> ```
> clickhouse-local --query "SELECT ..." --format Native | gzip -c | curl "http://byconity-worker:8123/?query=INSERT INTO my_logs SETTINGS prefer_cnch_catalog=1"
> ```

Yeah, send to worker with the settings is the way if you want to make the insertion happen in worker when insert from client

**Comment by xiaomo728** [comment]
> Hi @xiaomo728 , i haven't tried but i think it should work the same way as send to server. At the moment we have an issue that ClickHouse community client not able to connect to Byconity. We have solve this issue in internal branch and will pick the fix to ByConity in probably next week

@dmthuc Got it. I just tested the JDBC connection, and it was the same as using the client: the text after the VALUES keyword was erased.

**Comment by xiaomo728** [comment]
Hi @dmthuc I just met a new problem: when I setup multiple write-workers, I must `set prefer_cnch_catalog = 1` first, otherwise I cannot run some INSERT queries from server.
Why??

**Comment by dmthuc** [comment]
> Hi @dmthuc I just met a new problem: when I setup **multiple** write-workers, I must `set prefer_cnch_catalog = 1` first, otherwise I cannot run some INSERT queries from server; However, when I start **only one** write-worker, this problem does not exist. Why??

Hi @xiaomo728 , you should always able to run insert query from server. But in worker you need to `set perfer_cnch_catalog = ` in worker cli to insert in worker. This logic doesn't related to how many workers you have

**Comment by xiaomo728** [comment]
> > Hi @dmthuc I just met a new problem: when I setup **multiple** write-workers, I must `set prefer_cnch_catalog = 1` first, otherwise I cannot run some INSERT queries from server; However, when I start **only one** write-worker, this problem does not exist. Why??
> 
> Hi @xiaomo728 , you should always able to run insert query from server. But in worker you need to `set perfer_cnch_catalog = ` in worker cli to insert in worker. This logic doesn't related to how many workers you have

Hi @dmthuc please check the message that I just edited. Many thanks.
Do you mean that u guys have not met this problem right?

**Comment by dmthuc** [comment]
Hi @xiaomo728 , we never met that problem. Can you execute `set send_logs_level='trace'` and then send us the log?

**Comment by xiaomo728** [comment]
> Hi @xiaomo728 , we never met that problem. The insert query is always supposed to be executed in server without any settings. Can you execute `set send_logs_level='trace'` and then send us the log?

@dmthuc We have done this. Input an INSERT query from server:

_(All things are normal before)_
```
...... 
<Debug> executeQuery: [951]: pipeline has all used StorageIDs: true
<Debug> executeQuery: [1601]: Query pipeline:
TransactionWrapperBlockInputStream
  Remote

<Trace> Connection (xx.xx.xxx.xxx:pppp): [99]: Connecting. Database: default. User: Server
```
and after this, the query is on stuck.

**Comment by dmthuc** [comment]
Hi @xiaomo728 , may i know what kind of INSERT query you execute. And there is one thing is that the settings `prefer_cnch_catalog` is only supposed to be set in worker cli. Do not set it in config file or in server. You can give me the example query, i will try to reproduce it?

**Comment by xiaomo728** [comment]
> Hi @xiaomo728 , may i know what kind of INSERT query you execute. And there is one thing is that the settings `prefer_cnch_catalog` is only supposed to be set in worker cli. Do not set it in config file or in server. You can give me the example query, i will try to reproduce it?
> 
> And if you want to debug by yourself, i think at the moment the query is `stuck` it is actually is executing in worker, so you can see which worker that the query is forward to and take a look at the worker log.

@dmthuc 
1. Just a very simple query: insert into table_name select (rand() % ((1000000 - 1) + 1)) + 1,(rand() % ((1000000 - 1) + 1)) + 1 from  numbers(50);
2. Okay, I am checking that.

**Comment by xiaomo728** [comment]
> Hi @xiaomo728 , may i know what kind of INSERT query you execute. And there is one thing is that the settings `prefer_cnch_catalog` is only supposed to be set in worker cli. Do not set it in config file or in server. You can give me the example query, i will try to reproduce it?
> 
> And if you want to debug by yourself, i think at the moment the query is `stuck` it is actually is executing in worker, so you can see which worker that the query is forward to and take a look at the worker log.

One more thing: how to understand that this config `prefer_cnch_catalog` needs to be set **only** on the worker cli? If I use JDBC to connect, do I need `INSERT... VALUES SETTINGS prefer_cnch_catalog = 1` every time? Isn't this a bit of a hassle...

Could I open this config in worker's config as default and close it in server's config?

**Comment by dmthuc** [comment]
> > Hi @xiaomo728 , may i know what kind of INSERT query you execute. And there is one thing is that the settings `prefer_cnch_catalog` is only supposed to be set in worker cli. Do not set it in config file or in server. You can give me the example query, i will try to reproduce it?
> > And if you want to debug by yourself, i think at the moment the query is `stuck` it is actually is executing in worker, so you can see which worker that the query is forward to and take a look at the worker log.
> 
> One more thing: how to understand that this config `prefer_cnch_catalog` needs to be set **only** on the worker cli? If I use JDBC to connect, do I need `INSERT... VALUES SETTINGS prefer_cnch_catalog = 1` every time? Isn't this a bit of a hassle...
> 
> Could I open this config in worker's config as default and close it in server's config?

I think setting this config in worker config might break some use case, like kafka insertion. For now you can try it and if it doesn't break any use case that it is ok. In future we will try to remove this config

**Comment by juppylm** [comment]
> > Hi @xiaomo728 , we never met that problem. The insert query is always supposed to be executed in server without any settings. Can you execute `set send_logs_level='trace'` and then send us the log?
> 
> @dmthuc We have done this. Input an INSERT query from server:
> 
> _(All things are normal before)_
> 
> ```
> ...... 
> <Debug> executeQuery: [951]: pipeline has all used StorageIDs: true
> <Debug> executeQuery: [1601]: Query pipeline:
> TransactionWrapperBlockInputStream
>   Remote
> 
> <Trace> Connection (xx.xx.xxx.xxx:pppp): [99]: Connecting. Database: default. User: Server
> ```
> 
> and after this, the query is on stuck.

@xiaomo728 Excuse me. Please tell me, has this problem been solved? I also encountered the same problem.

**Comment by Doslin** [comment]
> Hi @xiaomo728 , i haven't tried but i think it should work the same way as send to server. At the moment we have an issue that ClickHouse community client not able to connect to Byconity. We have solve this issue in internal branch and will pick the fix to ByConity in probably next week
@dmthuc  ByConity latest version 0.3 is it possible to write data using other drivers, such as jdbc:clickhouse or jdbc:bytehouse?

**Comment by dmthuc** [comment]
Let close this issue now. Please reopen if you meet any issue
