### ISSUE TITLE
Gzip doesn't work with HTTP Interface (inflateReset failed)

### ISSUE THREAD

**Issue by lazywei** [ByConity/ByConity#730]
### Briefly describe the bug
Insert file over HTTP protocol with Gzip doesn't seem to work

### How to Reproduce
Dump some records into a CH native format file and compress it with gzip or pipe it with `gzip -c`, and then insert over http
```
clickhouse local --query "SELECT * FROM file('24dc.native.gzip') LIMIT 1" --format Native | curl "http://localhost:8123/?query=INSERT%20INTO%20my_logs%20FORMAT%20Native" -H 'Content-Encoding: gzip' --data-binary @-
```

It will got error
```
Code: 354, e.displayText() = DB::Exception: inflateReset failed: data error SQLSTATE: HY000 (version 21.8.7.1)
```

### Version

I'm using the stable build docker image running on k8s.

### Misc

Upstream CH seems to have this issue previously as well but it got fixed. Not sure if we can port the fix here as well

https://github.com/ClickHouse/clickhouse-connect/issues/93

**Comment by dmthuc** [comment]
Hi lazywei, thank you for reporting this bug. We will fix it

**Comment by dmthuc** [comment]
This issue should not be P1. Currently no user use it for ingest. The original user also doesn't use it

**Comment by dmthuc** [comment]
Hi @lazywei , this error because you forget `gzip -c` in
```
clickhouse local --query "SELECT * FROM file('24dc.native.gzip') LIMIT 1" --format Native | curl "http://localhost:8123/?query=INSERT%20INTO%20my_logs%20FORMAT%20Native" -H 'Content-Encoding: gzip' --data-binary @-
```

**Comment by dmthuc** [comment]
Let close this now, if there is any other issue, please reopen the issue again
