### ISSUE TITLE
Memory usage in `system.workers` is incorrect

### ISSUE THREAD

**Issue by lazywei** [ByConity/ByConity#732]
### Briefly describe the bug

The memory usage / memory available reported by `system.workers` doesn't seem to be correct

```
SELECT
    worker_id,
    memory_usage
FROM system.workers

Query id: 78a72326-4ac2-48c1-9424-f573e79779d2

┌─worker_id────────────────┬──────────memory_usage─┬────memory_available─┐
│ byconity-vw-vw-write-3   │ 3.5862868230651673e-9 │ 9223372036523995136 │
│ byconity-vw-vw-write-2   │ 4.9217074860052914e-9 │ 9223372036400824320 │
│ byconity-vw-vw-write-4   │  3.498001888146975e-9 │ 9223372036532137984 │
│ byconity-vw-vw-write-1   │  4.911626660941695e-9 │ 9223372036401754112 │
│ byconity-vw-vw-default-0 │  2.002042975846053e-9 │ 9223372036670115840 │
│ byconity-vw-vw-write-0   │  4.257305619148612e-9 │ 9223372036462104576 │
│ byconity-vw-vw-write-5   │  1.809983274370098e-8 │ 9223372035185356800 │
│ byconity-vw-vw-write-6   │  1.215827438727502e-9 │ 9223372036742631424 │
└──────────────────────────┴───────────────────────┴─────────────────────┘
```

CPU on the other hand seems to be correct (if i understand it correctly, the CPU usage is percentage, right?, i.e., 0%-100%)

**Comment by dmthuc** [comment]
Hi @lazywei , could you tell more about how memory usage is incorrect. Is the real usage is bigger or smaller and how much is the difference? cc @zeromem

**Comment by dmthuc** [comment]
Hi @zeromem , I think currently the `memory_available` field haven't been implemented. You can take a look

**Comment by zeromem** [comment]
Actually the memory_available is read from `/proc/meminfo`. or `/sys/fs/cgroup/memory/memory.usage_in_bytes` and `/sys/fs/cgroup/memory/memory.limit_in_bytes` if it's in a container.  @lazywei you can check those files on your worker pod.

**Comment by lazywei** [comment]
OK confirmed it works if we set the CPU/RAM resources request & limit explicitly on the k8s. Previously we didn't set any resource limit so perhaps it's not reading from the actual physical machine but rather the container's info only.

Thanks!
