### ISSUE TITLE
Application: DB::Exception: cnch_config not found SQLSTATE: F0000

### ISSUE THREAD

**Issue by xiaomo728** [ByConity/ByConity#75]
I am trying ByConity and pulling down its source code onto my machine (Linux CentOS) and installing it **manually**.

I have finished compiling (generated bin files like `clickhouse`) and then there has required FoundationDB and HDFS dependencies installed.

I also have changed the values inside the relevant configuration files, but I'm not sure if I changed them correctly (mainly those `.xml` files in the `deploy/template` folder).

When I run the following steps in the installation tutorial:

> Run the deploy script in a separate terminal. `template_paths` and `program_dir` args are compulsory
`cd ByConity/deploy`
`python3.9 deploy.py --template_paths template/byconity-server.xml template/byconity-worker.xml --program_dir /home/ByConity/build/programs`

Several of the services I start report this error: 
`<Error> Application: DB::Exception: cnch_config not found SQLSTATE: F0000`

How can I fix this error?

**Comment by xiaomo728** [comment]
BTW - are there any plans for the community to write an instructional document on modifying configuration files (i.e. modifying those `.xml` and the `deploy.py` files under the `/deploy`)?

**Comment by hustnn** [comment]
do you mean a doc to describe the meaning of each parameter?

**Comment by xiaomo728** [comment]
> do you mean a doc to describe the meaning of each parameter?

@hustnn Yes exactly. And, I would like to know the minimum settings that users need - in other words, now I have a stand-alone running environment, a local fdb and hdfs service, I only need to set up what parameters to ensure that I can run the ByConity as well as execute R/W in database on a stand-alone machine?

**Comment by hustnn** [comment]
you can refer this one, it is in chinese https://github.com/ByConity/byconity.github.io/blob/main/source/_posts/zh-cn/docs/%E5%9F%BA%E7%A1%80%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C/%E9%9B%86%E7%BE%A4%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0.md

**Comment by vivek-debug** [comment]
I tried this on my side and it seems the `TEMPLATE_USER_CONFIG` value in `deploy.py` should be changed from `cnch-users.xml` to `byconity-users.xml`. Let me know if this works and I will create a PR for this
![Screenshot 2023-02-13 at 2 33 01 PM](https://user-images.githubusercontent.com/67144643/218387276-378a09ae-5ab2-41b8-b39a-e3c5221157a0.png)

Please also ensure the your FDB local installation has the database configured and the path to your FDB cluster file has been updated in `byconity-server.xml` and `byconity-worker.xml`
![Screenshot 2023-02-13 at 2 34 50 PM](https://user-images.githubusercontent.com/67144643/218387582-eee63ff9-8ef3-461b-af0c-082c2f989763.png)
