### ISSUE TITLE
How to config S3 storage of GCP?

### ISSUE THREAD

**Issue by hillbun** [ByConity/ByConity#756]
# server_s3_disk_0:
        #   path: byconity0
        #   endpoint: http://xxx.xxx.xxx.xxx:9000
        #   region: cn-beijing
        #   bucket: cch-test
        #   ak_id: minio
        #   ak_secret: minio123
        #   type: bytes3
        #   is_virtual_hosted_style: false

for S3 storage of GCP, is there any endpoint, ak_id, ak_secret demo?

I just see gs://xxxxx, key.json  for  GCP platform.

**Comment by hillbun** [comment]
done with Service account HMAC and storage URI

**Comment by hustnn** [comment]
hi @hillbun , is it working?

**Comment by hillbun** [comment]
yes
