### ISSUE TITLE
Data import issues that occur after upgrading to 0.2.1

### ISSUE THREAD

**Issue by luozhenglin** [ByConity/ByConity#759]
1.Use the remote function on the clickhouse to export data to byconity, and Netexception appears. In version 0.1 it is possible to import successfully.
   Error message :Code: 519. DB::NetException: All attempts to get table structure failed. Log:Code: 279. DB::NetException: All connection tries failed. Log:
   sql : INSERT INTO FUNCTION remote('0.0.0.0:9000', 'db.test', 'user', 'p' )
select  * from db.test limit 10;

2.Use the s3 function to import data, which can also be used in version 0.1, and now an error is reported
  Error: DB::Exception: Unknown table function s3 SQLSTATE: 42883.
   sql:INSERT INTO db.test SELECT
    x1,
    x2,
    x3
FROM s3('path', 'xxx', 'xxx', 'CSV', 'x1     UInt64,x2       DateTime(\'UTC\'),x3       String')
SETTINGS max_execution_time = 9999999999, receive_timeout = 999999, send_timeout = 999999, max_partitions_per_insert_block = 20000

**Comment by hustnn** [comment]
Hi @luozhenglin , For S3 function, pls try CnchS3.
For remote function, it is not supported yet, we will provide the dump tools to help migrate data from CH to ByConity soon.

**Comment by luozhenglin** [comment]
Ok. Can you give an example of CnchS3? Thank you.
For remote function,I would like to confirm if the remote function cannot be used after the upgrade.Because at 0.1, I used it successfully

**Comment by hustnn** [comment]
> Ok. Can you give an example of CnchS3? Thank you.

Function = CnchS3(url, structure, [format], [compression], [ak, sk])

> For remote function,I would like to confirm if the remote function cannot be used after the upgrade.Because at 0.1, I used it successfully

yes, it is breaked in 0.2.1, we already fixed it in master and next release should be working.

**Comment by hillbun** [comment]
@hustnn 

what's best practice？    CnchS3 or remote?

**Comment by luozhenglin** [comment]
> > Ok. Can you give an example of CnchS3? Thank you.
> 
> Function = CnchS3(url, structure, [format], [compression], [ak, sk])
> 
> > For remote function,I would like to confirm if the remote function cannot be used after the upgrade.Because at 0.1, I used it successfully
> 
> yes, it is breaked in 0.2.1, we already fixed it in master and next release should be working.

OK， It worked.  Thank you.

**Comment by hillbun** [comment]
> > For remote function,I would like to confirm if the remote function cannot be used after the upgrade.Because at 0.1, I used it successfully
> 
> yes, it is breaked in 0.2.1, we already fixed it in master and next release should be working.


@hustnn 

Is it fixed in version of 0.2.2?
