### ISSUE TITLE
ByConity server leader election

### ISSUE THREAD

**Issue by ozcelgozde** [ByConity/ByConity#773]
## Question
Hello, I have a ByConity kubernetes deployment from default helm values. This deploys byconity-server statefulset with 2 replicas. When i go into the pod logs of byconity-server-0 I see this error:
```
<Error> CnchServerManager: More than one server in cluster without leader-election is not supported now, stop refreshTopology, psm: byconity-server
```
How do I activate the leader election properly?

**Comment by yuanzhubi** [comment]
Currently multi replicas of byconity-server support is experimental. 

Personally, I suggest you can try this pre-release solution https://github.com/ByConity/ByConity/pull/757, according to pull the branch "sync_storage_election" and deploy following https://github.com/ByConity/ByConity/blob/ad2ad4677bf2793ffadf98fbcf33896fe8240202/doc/ha_support.md#2-i-want-to-use-this-feature-and-want-to-increase-or-decrease-the-replicas-count.

**Comment by yuanzhubi** [comment]
> Currently multi replicas of byconity-server support is experimental.
> 
> Personally, I suggest you can try this pre-release solution #757, according to pull the branch "sync_storage_election" and deploy following https://github.com/ByConity/ByConity/blob/ad2ad4677bf2793ffadf98fbcf33896fe8240202/doc/ha_support.md#2-i-want-to-use-this-feature-and-want-to-increase-or-decrease-the-replicas-count.


It is already merged into master branch. Feel free to use it or raise the issue you meet.

**Comment by dmthuc** [comment]
Thank you for your confirmation
