### ISSUE TITLE
ByConity finishes servers' election without Zookeeper/ClickHouse keeper

### ISSUE THREAD

**Issue by xiaomo728** [ByConity/ByConity#775]
Currently in 0.2.2 (`src\MergeTreeCommon\CnchServerManager.cpp`), it seems that ByConity still needs Zookeeper to do server election.

```
CnchServerManager::CnchServerManager(ContextPtr context_, const Poco::Util::AbstractConfiguration & config)
    : WithContext(context_)
    , LeaderElectionBase(getContext()->getConfigRef().getUInt64("server_master.election_check_ms", 100))
{
    auto task_func = [this] (String task_name, std::function<bool ()> func, UInt64 interval, std::atomic<UInt64> & last_time, BackgroundSchedulePool::TaskHolder & task)
    {
        /// Check schedule delay
        UInt64 start_time = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count();
        if (last_time && start_time > last_time && (start_time - last_time) > (1000 + interval))
            LOG_WARNING(log, "{} schedules over {}ms. Last finish time: {}, current time: {}", task_name, (1000 + interval), last_time, start_time);

        bool success = false;
        try
        {
            success = func();
        }
        catch (...)
        {
            tryLogCurrentException(log, __PRETTY_FUNCTION__);
        }
        /// Check execution time
        UInt64 finish_time = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count();
        if (finish_time > start_time && finish_time - start_time > 1000)
            LOG_WARNING(log, "{} executed over 1000ms. Start time: {}, current time: {}", task_name, start_time, finish_time);
        
        last_time = finish_time;
        auto schedule_delay = success ? interval 
                                      : getContext()->getSettingsRef().topology_retry_interval_ms.totalMilliseconds(); 
        task->scheduleAfter(schedule_delay);        
    };

    topology_refresh_task = getContext()->getTopologySchedulePool().createTask("TopologyRefresher", [this, task_func](){
        task_func("TopologyRefresher"
            , [this]() -> bool { return refreshTopology(); }
            , getContext()->getSettingsRef().topology_refresh_interval_ms.totalMilliseconds()
            , refresh_topology_time
            , topology_refresh_task);
    });

    lease_renew_task = getContext()->getTopologySchedulePool().createTask("LeaseRenewer", [this, task_func](){
        task_func("LeaseRenewer"
            , [this]() -> bool { return renewLease(); }
            , getContext()->getSettingsRef().topology_lease_renew_interval_ms.totalMilliseconds()
            , renew_lease_time
            , lease_renew_task);
    });

    async_query_status_check_task = getContext()->getTopologySchedulePool().createTask("AsyncQueryStatusChecker", [this, task_func](){
        UInt64 async_query_status_check_interval = getContext()->getRootConfig().async_query_status_check_period * 1000;
        task_func("AsyncQueryStatusChecker"
            , [this]() -> bool { return checkAsyncQueryStatus(); }
            , async_query_status_check_interval
            , async_query_status_check_time
            , async_query_status_check_task);
    });

    updateServerVirtualWarehouses(config);
    if (!getContext()->hasZooKeeper())
    {
        // throw Exception(ErrorCodes::NOT_IMPLEMENTED, "Can't start server manage due to lack of zookeeper");
        LOG_ERROR(log, "There is no zookeeper, skip start background task for serverManager");

        onLeader();
        return;
    }

    startLeaderElection(getContext()->getTopologySchedulePool());
}
```

**Comment by xiaomo728** [comment]
@kevinthfang I heard that here you have a solution that does not rely on ZooKeeper to do server election. Will this be picked in the near future?

**Comment by kevinthfang** [comment]
yes. It's already picked. Just not included in the latest release. And the document is on the way.

**Comment by xiaomo728** [comment]
> yes. It's already picked. Just not included in the latest release. And the document is on the way.

@kevinthfang It's on master? Sorry I do not find it... Which module are it in?😢

**Comment by kevinthfang** [comment]
@yuanzhubi . please take a look

**Comment by yuanzhubi** [comment]
> @yuanzhubi . please take a look

Ok. @xiaomo728 The pull request is here and not merged yet. https://github.com/ByConity/ByConity/pull/757

**Comment by xiaomo728** [comment]
> > @yuanzhubi . please take a look
> 
> Ok. @xiaomo728 The pull request is here and not merged yet. #757

@yuanzhubi Okay, thank you very much! I will take a look first.

**Comment by xiaomo728** [comment]
> Ok. @xiaomo728 The pull request is here and not merged yet. #757

Hi @yuanzhubi . I found [this page](https://github.com/ByConity/ByConity/blob/ad2ad4677bf2793ffadf98fbcf33896fe8240202/doc/ha_support.md#2-i-want-to-use-this-feature-and-want-to-increase-or-decrease-the-replicas-count) and it says that:

> For manual deployment of the Byconity cluster, add extra service processes with different listening addresses and log paths for expansion, or stop them for contraction. When changing the replica count for the Byconity component "server," update the service discovery information in the cnch-config configuration file, as demonstrated here: https://github.com/ByConity/ByConity/blob/67e2eaab6d5b9c646a336619b2b5500203efc4fd/docker/docker-compose/byconity-multi-cluster/cnch-config.yml **(other components like resource manager/TSO are not needed).**

What means "other components like resource manager/TSO are not needed" here? It that means that, for example, if I want to deploy 3 tso + 3 resource-manager + 3 server instance, I only need to configure multiple servers in cnch_config, and only configure 1 resource-manager and 1 tso?

**Comment by yuanzhubi** [comment]
> @yuanzhubi is #757 a different approach than #547? It seems with #547, we can add the `zookeeper: { }` empty tag to the helm/k8s files to allow servers / RM / DM to use TSO as keeper to elect leader already. Or is that an incomplete solution?

Yes, https://github.com/ByConity/ByConity/issues/547 will be an deprecated solution and it is not suggested to use it any more.

**Comment by yuanzhubi** [comment]
> > Ok. @xiaomo728 The pull request is here and not merged yet. #757
> 
> Hi @yuanzhubi . I found [this page](https://github.com/ByConity/ByConity/blob/ad2ad4677bf2793ffadf98fbcf33896fe8240202/doc/ha_support.md#2-i-want-to-use-this-feature-and-want-to-increase-or-decrease-the-replicas-count) and it says that:
> 
> > For manual deployment of the Byconity cluster, add extra service processes with different listening addresses and log paths for expansion, or stop them for contraction. When changing the replica count for the Byconity component "server," update the service discovery information in the cnch-config configuration file, as demonstrated here: https://github.com/ByConity/ByConity/blob/67e2eaab6d5b9c646a336619b2b5500203efc4fd/docker/docker-compose/byconity-multi-cluster/cnch-config.yml **(other components like resource manager/TSO are not needed).**
> 
> What means "other components like resource manager/TSO are not needed" here? It that means... for example, if I want to deploy 3 tso + 3 resource-manager + 3 server instances, I only need to configure multiple servers in cnch_config, and only configure 1 resource-manager and 1 tso?

It means for resource-manager and tso, if the replicas count was changed, we do not need to update the service discovery configuration for them.
