### ISSUE TITLE
byconity server deadlock  when do heavy benchmark test

### ISSUE THREAD

**Issue by blueskygzhz** [ByConity/ByConity#787]
when i do benchmark for a period of time, byconity【0.2.2】 server stucks on connection pool and no more client can connect successfully

benchmark scenior:
launch 10 threads, each thread do 1000000 times   group by

server stacktrace
(gdb) bt
#0  0x000000000d48682d in PoolBase<DB::Connection>::get(long) (this=0x7f45576d7ea0, timeout=<optimized out>) at ../src/Common/PoolBase.h:157
#1  0x000000000d486022 in DB::ConnectionPool::get(DB::ConnectionTimeouts const&, DB::Settings const*, bool) (this=<optimized out>, timeouts=..., settings=<optimized out>, force_connected=false) at ../src/Client/ConnectionPool.h:111
#2  0x0000000018e7dae5 in DB::ConnectionEstablisher::run(PoolWithFailoverBase<DB::IConnectionPool>::TryResult&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) (this=0x7f385fed2088, result=..., fail_message=...) at ../src/Client/ConnectionEstablisher.cpp:37
#3  0x0000000018e776f9 in DB::ConnectionPoolWithFailover::tryGetEntry(DB::IConnectionPool&, DB::ConnectionTimeouts const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, DB::Settings const*, DB::QualifiedTableName const*) (this=<optimized out>, pool=..., timeouts=..., 
    fail_message=..., settings=<optimized out>, table_to_check=0x7f385fed2440) at ../src/Client/ConnectionPoolWithFailover.cpp:259
#4  0x0000000018e77bed in operator() (this=<optimized out>, pool=..., fail_message=...) at ../src/Client/ConnectionPoolWithFailover.cpp:171
#5  __invoke<(lambda at ../src/Client/ConnectionPoolWithFailover.cpp:169:37) &, DB::IConnectionPool &, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > &> (__f=..., __args=..., __args=...) at ../contrib/libcxx/include/type_traits:3676
#6  __call<(lambda at ../src/Client/ConnectionPoolWithFailover.cpp:169:37) &, DB::IConnectionPool &, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > &> (__args=..., __args=..., __args=...) at ../contrib/libcxx/include/__functional_base:317
#7  operator() (this=<optimized out>, __arg=..., __arg=...) at ../contrib/libcxx/include/functional:1608
#8  std::__1::__function::__policy_invoker<PoolWithFailoverBase<DB::IConnectionPool>::TryResult (DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::ConnectionPoolWithFailover::getManyChecked(DB::ConnectionTimeouts const&, DB::Settings const*, DB::PoolMode, DB::QualifiedTableName const&)::$_9, PoolWithFailoverBase<DB::IConnectionPool>::TryResult (DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)> >(std::__1::__function::__policy_storage const*, DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) (__buf=<optimized out>, __args=..., __args=...) at ../contrib/libcxx/include/functional:2089
#9  0x0000000018e786a7 in operator() (this=0x3, __args=..., __args=...) at ../contrib/libcxx/include/functional:2221
#10 operator() (this=0x3, __arg=..., __arg=...) at ../contrib/libcxx/include/functional:2560
#11 PoolWithFailoverBase<DB::IConnectionPool>::getMany(unsigned long, unsigned long, unsigned long, unsigned long, bool, std::__1::function<PoolWithFailoverBase<DB::IConnectionPool>::TryResult (DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)> const&, std::__1::function<unsigned long (unsigned long)> const&) (this=0x7f3ceae85120, min_entries=1, max_entries=1, max_tries=3, max_ignored_errors=<optimized out>, fallback_to_stale_replicas=<optimized out>, try_get_entry=..., get_priority=...) at ../src/Common/PoolWithFailoverBase.h:262
#12 0x0000000018e772dc in DB::ConnectionPoolWithFailover::getManyImpl(DB::Settings const*, DB::PoolMode, std::__1::function<PoolWithFailoverBase<DB::IConnectionPool>::TryResult (DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)> const&) (
    this=this@entry=0x7f3ceae85118, settings=<optimized out>, settings@entry=0x7f45070d22c0, pool_mode=<optimized out>, pool_mode@entry=GET_MANY, try_get_entry=...) at ../src/Client/ConnectionPoolWithFailover.cpp:244
#13 0x0000000018e774ee in DB::ConnectionPoolWithFailover::getManyChecked(DB::ConnectionTimeouts const&, DB::Settings const*, DB::PoolMode, DB::QualifiedTableName const&) (this=0x7f3ceae85118, timeouts=..., settings=0x7f45070d22c0, pool_mode=(unknown: 4193135488), table_to_check=...)
    at ../src/Client/ConnectionPoolWithFailover.cpp:174
#14 0x0000000017a684ff in operator() (this=0x7f429c9a0750) at ../src/DataStreams/RemoteQueryExecutor.cpp:107
#15 __invoke<(lambda at ../src/DataStreams/RemoteQueryExecutor.cpp:88:26) &> (__f=...) at ../contrib/libcxx/include/type_traits:3676
#16 __call<(lambda at ../src/DataStreams/RemoteQueryExecutor.cpp:88:26) &> (__args=...) at ../contrib/libcxx/include/__functional_base:317
#17 operator() (this=0x7f429c9a0750) at ../contrib/libcxx/include/functional:1608
#18 std::__1::__function::__policy_invoker<std::__1::unique_ptr<DB::IConnections, std::__1::default_delete<DB::IConnections> > ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::RemoteQueryExecutor::RemoteQueryExecutor(std::__1::shared_ptr<DB::ConnectionPoolWithFailover> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Block const&, std::__1::shared_ptr<DB::Context const>, std::__1::shared_ptr<DB::Throttler> const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, DB::Block, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, DB::Block> > > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<DB::IStorage>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::shared_ptr<DB::IStorage> > > > const&, DB::QueryProcessingStage::Enum, std::__1::shared_ptr<std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()> >)::$_2, std::__1::unique_ptr<DB::IConnections, std::__1::default_delete<DB::IConnections> > ()> >(std::__1::__function::__policy_storage const*) (
    __buf=<optimized out>) at ../contrib/libcxx/include/functional:2089
#19 0x0000000017a64650 in operator() (this=0x7f450705baf8) at ../contrib/libcxx/include/functional:2221
#20 operator() (this=0x7f450705baf8) at ../contrib/libcxx/include/functional:2560
#21 DB::RemoteQueryExecutor::sendQuery() (this=0x7f450705ba18) at ../src/DataStreams/RemoteQueryExecutor.cpp:183
#22 0x00000000190f3d48 in DB::RemoteSource::tryGenerate() (this=0x7f45ac425918) at ../src/Processors/Sources/RemoteSource.cpp:88
#23 0x0000000018f39e7d in DB::ISource::work() (this=0x7f45ac425918) at ../src/Processors/ISource.cpp:74
#24 0x00000000190f975a in DB::SourceWithProgress::work() (this=0x7f45ac425918) at ../src/Processors/Sources/SourceWithProgress.cpp:81
#25 0x0000000018f73e81 in executeJob (processor=0x7f45ac425918) at ../src/Processors/Executors/PipelineExecutor.cpp:131
#26 operator() (this=0x7f45ac4f5d70) at ../src/Processors/Executors/PipelineExecutor.cpp:148
#27 __invoke<(lambda at ../src/Processors/Executors/PipelineExecutor.cpp:143:16) &> (__f=...) at ../contrib/libcxx/include/type_traits:3676
#28 __call<(lambda at ../src/Processors/Executors/PipelineExecutor.cpp:143:16) &> (__args=...) at ../contrib/libcxx/include/__functional_base:348
#29 operator() (this=0x7f45ac4f5d70) at ../contrib/libcxx/include/functional:1608
#30 std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0, void ()> >(std::__1::__function::__policy_storage const*) (__buf=0x7f45ac4f5d70) at ../contrib/libcxx/include/functional:2089
#31 0x0000000018f71ef7 in operator() (this=0x7f3ef9ee6bf0) at ../contrib/libcxx/include/functional:2221
#32 operator() (this=0x7f3ef9ee6bf0) at ../contrib/libcxx/include/functional:2560
#33 DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) (this=this@entry=0x7f46a06fb418, thread_num=<optimized out>, thread_num@entry=0, num_threads=num_threads@entry=1, yield_flag=yield_flag@entry=0x0) at ../src/Processors/Executors/PipelineExecutor.cpp:865
#34 0x0000000018f7065c in executeSingleThread (this=0x7f46a06fb418, thread_num=0, num_threads=1) at ../src/Processors/Executors/PipelineExecutor.cpp:750
#35 DB::PipelineExecutor::executeImpl(unsigned long) (this=this@entry=0x7f46a06fb418, num_threads=num_threads@entry=1) at ../src/Processors/Executors/PipelineExecutor.cpp:1100
#36 0x0000000018f70065 in DB::PipelineExecutor::execute(unsigned long) (this=0x7f46a06fb418, num_threads=1) at ../src/Processors/Executors/PipelineExecutor.cpp:643
#37 0x0000000018f7bd3d in threadFunction (data=..., thread_group=..., num_threads=1) at ../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:101
#38 operator() (this=<optimized out>) at ../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:128
#39 __invoke_constexpr<(lambda at ../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:126:21) &> (__f=...) at ../contrib/libcxx/include/type_traits:3682
#40 __apply_tuple_impl<(lambda at ../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:126:21) &, std::__1::tuple<> &> (__f=..., __t=...) at ../contrib/libcxx/include/tuple:1415
#41 apply<(lambda at ../src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:126:21) &, std::__1::tuple<> &> (__f=..., __t=...) at ../contrib/libcxx/include/tuple:1424
#42 operator() (this=<optimized out>) at ../src/Common/ThreadPool.h:222
#43 __invoke<(lambda at ../src/Common/ThreadPool.h:201:41) &> (__f=...) at ../contrib/libcxx/include/type_traits:3676
#44 __call<(lambda at ../src/Common/ThreadPool.h:201:41) &> (__args=...) at ../contrib/libcxx/include/__functional_base:348
#45 operator() (this=<optimized out>) at ../contrib/libcxx/include/functional:1608
#46 std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::{lambda()#1}, void ()> >(std::__1::__function::__policy_storage const*) (__buf=<optimized out>) at ../contrib/libcxx/include/functional:2089
#47 0x000000000d2f8cbf in operator() (this=0x7f385fed2f10) at ../contrib/libcxx/include/functional:2221
#48 operator() (this=0x7f385fed2f10) at ../contrib/libcxx/include/functional:2560
#49 ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) (this=0x7f48275177c0, thread_it=...) at ../src/Common/ThreadPool.cpp:354
#50 0x000000000d2fcf9a in operator() (this=0x7f3ef9ee6b88) at ../src/Common/ThreadPool.cpp:170
---Type <return> to continue, or q <return> to quit---
#51 __invoke<(lambda at ../src/Common/ThreadPool.cpp:170:42)> (__f=<unknown type in /usr/bin/clickhouse, CU 0x410422, DIE 0x48bd5d>) at ../contrib/libcxx/include/type_traits:3676
#52 __thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, (lambda at ../src/Common/ThreadPool.cpp:170:42)> (__t=...) at ../contrib/libcxx/include/thread:280
#53 std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#2}> >(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#2}>) (__vp=<optimized out>) at ../contrib/libcxx/include/thread:291
#54 0x00007f482a7c0ea5 in start_thread () from /lib64/libpthread.so.0
#55 0x00007f4828ac5b0d in clone () from /lib64/libc.so.6
(gdb) 
(gdb) 
(gdb) p *this
warning: RTTI symbol not found for class 'DB::ConnectionPool'
$2 = warning: RTTI symbol not found for class 'DB::ConnectionPool'
{<noncopyable> = {<> = {<No data fields>}, <No data fields>}, _vptr$PoolBase = 0x715e838 <vtable for DB::ConnectionPool+72>, max_items = 1024, behaviour_on_limit = Wait, 
  items = {<__vector_base<std::__1::shared_ptr<PoolBase<DB::Connection>::PooledObject>, std::__1::allocator<std::__1::shared_ptr<PoolBase<DB::Connection>::PooledObject> > >> = {<__vector_base_common<true>> = {<No data fields>}, __begin_ = 0x7f3ef9ee2b80, __end_ = 0x7f3ef9ee6b80, __end_cap_ = {<> = {
          __value_ = 0x7f3ef9ee6b80}, <> = {<allocator<std::__1::shared_ptr<PoolBase<DB::Connection>::PooledObject> >> = {<No data fields>}, <No data fields>}, <No data fields>}}, <No data fields>}, mutex = {__m_ = {__data = {__lock = 2, __count = 0, __owner = 47314, __nusers = 1, __kind = 0, __spins = 0, 
        __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = "\002\000\000\000\000\000\000\000Ҹ\000\000\001", '\000' <repeats 26 times>, __align = 2}}, available = {__cv_ = {__data = {{__wseq = 0, __wseq32 = {__low = 0, __high = 0}}, {__g1_start = 0, __g1_start32 = {__low = 0, __high = 0}}, __g_refs = {
          0, 0}, __g_size = {0, 0}, __g1_orig_size = 0, __wrefs = 0, __g_signals = {0, 0}}, __size = '\000' <repeats 47 times>, __align = 0}}, log = 0x7f46d915e880}
(gdb) p items
No symbol "items" in current context.
(gdb) p this->items
warning: RTTI symbol not found for class 'DB::ConnectionPool'
$3 = {<__vector_base<std::__1::shared_ptr<PoolBase<DB::Connection>::PooledObject>, std::__1::allocator<std::__1::shared_ptr<PoolBase<DB::Connection>::PooledObject> > >> = {<__vector_base_common<true>> = {<No data fields>}, __begin_ = 0x7f3ef9ee2b80, __end_ = 0x7f3ef9ee6b80, __end_cap_ = {<> = {
        __value_ = 0x7f3ef9ee6b80}, <> = {<allocator<std::__1::shared_ptr<PoolBase<DB::Connection>::PooledObject> >> = {<No data fields>}, <No data fields>}, <No data fields>}}, <No data fields>}
(gdb) 

log output:
2023.10.12 16:43:46.377931 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.377937 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.377942 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.377948 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.377953 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.377959 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.377964 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.377970 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.377975 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.377981 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.377986 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.377992 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.377997 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.378003 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.378008 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.378014 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.378019 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.378025 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.378030 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.378036 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.378041 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.378047 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.378052 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.378058 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.378063 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.378073 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.378078 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.378084 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.378089 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.378095 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.378100 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.378106 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.378111 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.378117 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.
2023.10.12 16:43:46.378122 [ 47314 ] {5515e4cd-a393-4009-b20f-723a9d6121eb} <Information> ConnectionPool (10.50.208.77:9010): No free connections in pool. Waiting 0 ms.

**Comment by wordhardqi** [comment]
Thanks for the contribution @blueskygzhz
