### ISSUE TITLE
When do  ByConity support  to read data from  hive external table which needs kerberos ?

### ISSUE THREAD

**Issue by nelsonspark** [ByConity/ByConity#788]
(you don't have to strictly follow this form)

**Comment by Clark0** [comment]
https://github.com/ByConity/ByConity/blob/d21f3b159b810b2a086df9a8e0c3ece525d6d462/src/Storages/Hive/CnchHiveSettings.h#L56C1-L57C1 Add kerberos settings when creating hive table.

**Comment by nelsonspark** [comment]
> https://github.com/ByConity/ByConity/blob/d21f3b159b810b2a086df9a8e0c3ece525d6d462/src/Storages/Hive/CnchHiveSettings.h#L56C1-L57C1 Add kerberos settings when creating hive table.

Thanks
