### ISSUE TITLE
Exception: Cannot alter table because of choosing wrong server according to current topology

### ISSUE THREAD

**Issue by xiaomo728** [ByConity/ByConity#810]
Exception occurred when using ALTER TABLE queries; 3 servers are running on cluster.

Code: 8052. DB::Exception: Received from **(HOST1)**. DB::Exception: Cannot alter table because of choosing wrong server according to current topology, chosen server: **(HOST2)** SQLSTATE: HY000.

We just merged the Support leader election in storage https://github.com/ByConity/ByConity/pull/757

**Comment by yuanzhubi** [comment]
1. https://github.com/ByConity/ByConity/pull/757 is already merged into master.
2. Currently "alter table" operations should be executed on a special host server(to update the latest meta cache). The server address can be achieved according to query: select host, tcp_port from system.cnch_table_host where database='{db_name}' and name='{table_name}'

**Comment by yuanzhubi** [comment]
If you meet this problems again, you can give more context information here to trace it.
