### ISSUE TITLE
求助 Centos7.9 无法安装 byconity-0.2.2 报错。

### ISSUE THREAD

**Issue by mdys** [ByConity/ByConity#814]
(you don't have to strictly follow this form)
感谢。求助
OS: Centos7.9 X64
GCC ：gcc-11
Cmake : 3.26.3
python: 2.7

## Question
执行如下 
 rpm -ivh --force --nodeps  --replacepkgs byconity-*.rpm 
![图片](https://github.com/ByConity/ByConity/assets/1708120/726697eb-4de8-43f2-ae9a-20ba8cdb2fb3)

**Comment by mdys** [comment]
> Hi @mdys , please try the method in this issue #712. We will try to provide the no debug info package in next version

感谢 请问新版本快出来了么？ 需要安装生产了，无比感谢提供这个软件！

**Comment by dmthuc** [comment]
Hi @mdys, could you please download this package `https://github.com/ByConity/ByConity/releases/download/0.2.2/byconity-common-static_no_debug_info-0.2.2.x86_64.rpm` . And rename it into `byconity-common-static-0.2.2.x86_64.rpm`  and try to install

**Comment by mdys** [comment]
感谢大佬 ，试了 还是出错
![图片](https://github.com/ByConity/ByConity/assets/1708120/2067692c-d1ca-495d-9eb3-c53eff6617c1)

**Comment by dmthuc** [comment]
Hi @mdys , please follow this guideline to install the package. https://byconity.github.io/docs/deployment/package-deployment. The ByConity packages has some dependencies and also require you to make change to the configuration files

**Comment by WillemJiang** [comment]
@mdys  Is this issue fixed?
