### ISSUE TITLE
heavy single table query cause byconity server cpu burst when enable_optimizer is off

### ISSUE THREAD

**Issue by blueskygzhz** [ByConity/ByConity#816]
Recurrence Scene：
1. one workergroup with two worknodes
2. two concurrent query threads do heavy query：

-- table schema:  
```
CREATE TABLE helloworld.my_first_table
(
    `user_id` UInt32,
    `message` String,
    `timestamp` DateTime
)
ENGINE = CnchMergeTree
PARTITION BY timestamp
ORDER BY (user_id, timestamp)
SETTINGS storage_policy = 'cnch_default_s3', index_granularity = 8192
```
--query
`SELECT count(*) as cnt, user_id FROM helloworld.my_first_table GROUP BY user_id ORDER BY user_id settings offloading_with_query_plan = 1`

byconity server cpu usage:
![6ba9e168e2c9af2bc764645be77265f](https://github.com/ByConity/ByConity/assets/147569085/e5583cca-bd9f-4512-8336-bb3b7d8061e4)

byconity server log:
![a77fe3b61f8a838f4e4254df3065e93](https://github.com/ByConity/ByConity/assets/147569085/369b37b6-95b1-4da4-81f2-bf76427e4755)

byconity worker log:
![123085f1124fd949130a99610027715](https://github.com/ByConity/ByConity/assets/147569085/9e6e280d-907b-47fb-aa8b-5ab6892f4870)

**Comment by yuanzhubi** [comment]
@FluorineDog Could you please to help to check this issue, or whether it is a normal workload for the server to execute this query?

**Comment by TKaxe** [comment]
hi, can you provide the number of parts and approximate data volume?
