### ISSUE TITLE
我想为ByConity贡献代码，但不会搭建开发环境，请老师帮忙解答。I want to contribute code to ByConity, yet I can't set up a development environment, help.

### ISSUE THREAD

**Issue by YuanHanzhong** [ByConity/ByConity#822]
## Question
1. 是否建议在mac上配置开发环境？
2. 对mac的硬件有什么要求？比如最小内存、芯片类型。
3. 您推荐使用什么IDE开发? 您使用的是什么什么环境、什么IDE？
4. 有没有一个从0开始，一步步配置开发环境的文档？
5. 配置好开发环境之后，如何确保自己写的代码没有问题？能否在本地测试代码正确性？需要运行哪些测试用例，如何运行？

### 已经查到的资料

1. https://github.com/ByConity/ByConity/issues/636
    1. 这个issue回答了不能在Apple Silicon machines上make image，但还是不清楚应该具体正确搭建环境。
2. https://github.com/ByConity/ByConity/issues/794
    1. 这个issue回答了中间的一部分搭建步骤，对于之前和之后做什么还是不清楚。

**Comment by Clark0** [comment]
ByConity does not support compile on mac. The simplest way to compile codes is to use docker [dev-env](https://github.com/ByConity/ByConity/tree/master/docker/debian/dev-env).  For IDE you can try vscode https://code.visualstudio.com/docs/devcontainers/containers and develop inside docker, so that you don't have to worry about dependencies.

**Comment by YuanHanzhong** [comment]
> ByConity does not support compile on mac. The simplest way to compile codes is to use docker [dev-env](https://github.com/ByConity/ByConity/tree/master/docker/debian/dev-env). For IDE you can try vscode https://code.visualstudio.com/docs/devcontainers/containers and develop inside docker, so that you don't have to worry about dependencies.

Thank you for your advice! I can use dev image in terminal now (first screenshot). But I still don't know how to configure vscode, can you please specify the second and third screenshot?
 ![CleanShot 2023-10-25 at 15 02 08@2x](https://github.com/ByConity/ByConity/assets/57024493/73076d38-c518-4f6b-ac16-19ad9d10274a)
![CleanShot 2023-10-25 at 15 37 47@2x](https://github.com/ByConity/ByConity/assets/57024493/0b7d8259-5f10-4060-9bbc-8a8b084da9d5)
![CleanShot 2023-10-25 at 15 39 33@2x](https://github.com/ByConity/ByConity/assets/57024493/32b60c37-981f-4c12-8789-e651457fd893)

**Comment by YuanHanzhong** [comment]
I guess there are two ways to run the dev-env container. The first is make pull and make run in terminal, the other is click run button in Docker desktop, right?

but I don't  know which image should I choose, do you know the difference between them?

![CleanShot 2023-10-25 at 15 48 08@2x](https://github.com/ByConity/ByConity/assets/57024493/401a8136-26cb-44d8-a937-a35c675488b3)

**Comment by YuanHanzhong** [comment]
![CleanShot 2023-10-25 at 16 01 59@2x](https://github.com/ByConity/ByConity/assets/57024493/357c4d53-9f00-45f6-a28b-9d7a50ba43b5)
 要开发的话，需要保持哪个container运行？

**Comment by Clark0** [comment]
> ![CleanShot 2023-10-25 at 16 01 59@2x](https://user-images.githubusercontent.com/57024493/277918208-357c4d53-9f00-45f6-a28b-9d7a50ba43b5.jpg) 要开发的话，需要保持哪个container运行？

dev-env

**Comment by YuanHanzhong** [comment]
> > ![CleanShot 2023-10-25 at 16 01 59@2x](https://user-images.githubusercontent.com/57024493/277918208-357c4d53-9f00-45f6-a28b-9d7a50ba43b5.jpg) 要开发的话，需要保持哪个container运行？
> 
> dev-env

Thank you. what about this question? 
![CleanShot 2023-10-25 at 16 49 08@2x](https://github.com/ByConity/ByConity/assets/57024493/438b638d-82cf-4261-9f10-204eb67d7bd3)

**Comment by YuanHanzhong** [comment]
Thanks a lot for your help. I made it finally.
![CleanShot 2023-10-25 at 17 02 31@2x](https://github.com/ByConity/ByConity/assets/57024493/3ceb0103-4821-459d-bb3b-9e5fec0fca6a)

**Comment by YuanHanzhong** [comment]
In order to help other brothers, I'd like to write a document about setting up development environment. Where should I put the document?

**Comment by Clark0** [comment]
> In order to help other brothers, I'd like to write a document about setting up development environment. Where should I put the document?

Thanks, you can make a pr to https://github.com/ByConity/byconity.github.io/tree/main/docs/quick-start

**Comment by YuanHanzhong** [comment]
I made summary about how to set up development environment and raised a PR. This is it: https://github.com/ByConity/byconity.github.io/pull/193
