### ISSUE TITLE
if not exists clause while creating worker group does not work

### ISSUE THREAD

**Issue by ozcelgozde** [ByConity/ByConity#823]
## Bug Report
I'm running some automated queries on a database and sometimes I send the same create commands for warehouses and worker groups. 
When i run 
```
create warehouse if not exists `vw_test` settings num_workers=0,type='Default'
```
it works when I already have the same warehouse created before:
![Screenshot 2023-10-25 at 22 58 37](https://github.com/ByConity/ByConity/assets/90635824/575d533d-f89d-4411-a767-7dd60df4597f)

But when I try the same thing with worker groups:
```
create worker group if not exists `wg_test` in `vw_test`
```
![Screenshot 2023-10-25 at 23 00 30](https://github.com/ByConity/ByConity/assets/90635824/22975a15-cd30-43d4-9b3b-23926a4fff6c)

I get error 
```
Code: 5041, e.displayText() = DB::Exception: DB::Exception: Worker group wg_test already exists. SQLSTATE: HY000. SQLSTATE: HY000 (version 21.8.7.1)
```
### The result you expected
I expected it to not return an error like warehouse case. 

### Version
0.2.2

**Comment by yuanzhubi** [comment]
Thank you for your issues, it seems "create if not exist" is not fully supported for worker group

**Comment by yuanzhubi** [comment]
The feature “create worker group if not exists” will be deprecated in future(because its logic is conflict with disable creating the same work group between different vw)

**Comment by yuanzhubi** [comment]
The feature “create worker group if not exists” will be deprecated in future(because its logic is conflict with disable creating the same work group between different vw)

**Comment by ozcelgozde** [comment]
But what about doing it in the same warehouse? Users would have to send 2 queries to check if the wg exists before sending the actual create query

**Comment by yuanzhubi** [comment]
> But what about doing it in the same warehouse? Users would have to send 2 queries to check if the wg exists before sending the actual create query

Well, if users need to create a new worker group using "create if not exist" and the query execution returns successfully, they will use an old workgroup as a new empty one. It is believed not an expected behaviour.
