### ISSUE TITLE
搭建完成开发环境后，有很多报错，请提示下调试思路？ How to debug?

### ISSUE THREAD

**Issue by YuanHanzhong** [ByConity/ByConity#824]
## Question
搭建完成开发环境后，什么也没做，过了一会vscode中有很多报错，这些错误怎么处理？如何调试？请提示个思路，感谢！
![CleanShot 2023-10-25 at 23 35 04@2x](https://github.com/ByConity/ByConity/assets/57024493/8a2d4813-3f9b-47ed-834c-e200babadb80)

**Comment by FourSpaces** [comment]
You can try the following command 
```
git submodule update --init --recursive
```

**Comment by YuanHanzhong** [comment]
Thanks for your help, by  execute `git submodule update --init --recursive` then `cmake -S /root/ByConity -B build_dev` this issue resolved.

![CleanShot 2023-10-26 at 12 33 01@2x](https://github.com/ByConity/ByConity/assets/57024493/7f7ef1b6-b378-4bc1-804f-7fe1965abaaa)
