### ISSUE TITLE
byconity server cannot offload "insert values" write request to write worker

### ISSUE THREAD

**Issue by blueskygzhz** [ByConity/ByConity#825]
Byconity can only offload "insert select" write request to writer worekr, other write request like "insert values" will be executed on by conity worker, this will cause server to be the system bottleneck.

**Comment by FourSpaces** [comment]
If you are reading data from Kafka, you can choose to use the CnchKafka engine.

**Comment by FourSpaces** [comment]
@hustnn  Is the functionality to insert data directly to the write worker available now?

I see that this [issue](https://github.com/ByConity/ByConity/issues/223) has been closed, but I didn't see the usage instructions in the documentation. Can you please add them?

**Comment by blueskygzhz** [comment]
> If you are reading data from Kafka, you can choose to use the CnchKafka engine.

In our scene, we need do many etl job, so we cannot use cnchkafka engine.

**Comment by FourSpaces** [comment]
@blueskygzhz  You can try this inserting data directly to the write worker. https://github.com/ByConity/ByConity/issues/722#issuecomment-1730736674
