### ISSUE TITLE
Could I continue to use MergeTree table engine in ByConity?

### ISSUE THREAD

**Issue by xiaomo728** [ByConity/ByConity#84]
Just a question..
Cause `CnchMergeTree` table only can be used in `Cnch` engine's database...

I just tried to build an `Atomic` database, and tried to create a `MergeTree` table:

```
$ create table st(`did` UInt32, `col` String) engine=MergeTree() order by did;

CREATE TABLE st
(
    `did` UInt32,
    `col` String
)
ENGINE = MergeTree
ORDER BY did

Query id: ba5e3263-0ac4-45fb-9fc9-e54373121ca4


0 rows in set. Elapsed: 0.009 sec. 

Received exception from server (version 21.8.7):
Code: 79. DB::Exception: Received from 127.0.0.1:34159. DB::Exception: MergeTree storages require data path SQLSTATE: 58P01. 
```

AND I added path...

```
$ create table st(`did` UInt32, `col` String) engine=MergeTree('mergetree/') order by did;

CREATE TABLE st
(
    `did` UInt32,
    `col` String
)
ENGINE = MergeTree('mergetree/')
ORDER BY did

Query id: 0251e700-c349-4681-828e-7962b1689ff6


Code: 42. DB::Exception: Received from 127.0.0.1:34159. DB::Exception: With extended storage definition syntax storage MergeTree requires no parameters

Syntax for the MergeTree table engine:

CREATE TABLE [IF NOT EXISTS] [db.]table_name [ON CLUSTER cluster]
(
    name1 [type1] [DEFAULT|MATERIALIZED|ALIAS expr1] [TTL expr1],
    name2 [type2] [DEFAULT|MATERIALIZED|ALIAS expr2] [TTL expr2],
    ...
    INDEX index_name1 expr1 TYPE type1(...) GRANULARITY value1,
    INDEX index_name2 expr2 TYPE type2(...) GRANULARITY value2
) ENGINE = MergeTree()
ORDER BY expr
[PARTITION BY expr]
[CLUSTER BY expr INTO <TOTAL_BUCKET_NUMBER> BUCKETS [SPLIT_NUMBER <SPLIT_NUMBER_VALUE>] [WITH_RANGE] ]
[PRIMARY KEY expr]
[SAMPLE BY expr]
[TTL expr [DELETE|TO DISK 'xxx'|TO VOLUME 'xxx'], ...]
[SETTINGS name=value, ...]

See details in documentation: https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/mergetree/. Other engines of the family support different syntax, see details in the corresponding documentation topics.

If you use the Replicated version of engines, see https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/replication/.
 SQLSTATE: 42000. 
```

Is it a bug?

**Comment by hustnn** [comment]
It is related to config, may I know what is the use case for using mergeTree in ByConity.

**Comment by xiaomo728** [comment]
> It is related to config, may I know what is the use case for using mergeTree in ByConity?

@hustnn Just a question for MergeTree. Is ByConity designed to completely abandon the MergeTree engine?

**Comment by hustnn** [comment]
> > It is related to config, may I know what is the use case for using mergeTree in ByConity?
> 
> @hustnn Just a question for MergeTree. Is ByConity designed to completely abandon the MergeTree engine?

From user side, the answer is yes. Since in ByConity, we are considering a global scenario, user should only need to create the table and use it globally. The mergeTree is a local concept, you can use it in one machine.

**Comment by hustnn** [comment]
@xiaomo728 Any more question?

**Comment by xiaomo728** [comment]
> @xiaomo728 Any more question?

There are no more questions in this regard, thank you very much for your answer.
But I would like (as a noob user) to give a suggestion: since `CnchMergeTree` can only be built in `Cnch` database, and meanwhile `CnchMergeTree` is the main engine of ByConity, why not default the database engine to `Cnch` when creating a new database (it still seems to default to `Atomic` when creating a new database)?

**Comment by hustnn** [comment]
> > @xiaomo728 Any more question?
> 
> There are no more questions in this regard, thank you very much for your answer. But I would like (as a noob user) to give a suggestion: since `CnchMergeTree` can only be built in `Cnch` database, and meanwhile `CnchMergeTree` is the main engine of ByConity, why not default the database engine to `Cnch` when creating a new database (it still seems to default to `Atomic` when creating a new database)?

`Cnch` is the default engine when creating database.

**Comment by xiaomo728** [comment]
> > > @xiaomo728 Any more question?
> > 
> > 
> > There are no more questions in this regard, thank you very much for your answer. But I would like (as a noob user) to give a suggestion: since `CnchMergeTree` can only be built in `Cnch` database, and meanwhile `CnchMergeTree` is the main engine of ByConity, why not default the database engine to `Cnch` when creating a new database (it still seems to default to `Atomic` when creating a new database)?
> 
> `Cnch` is the default engine when creating database.

Ok. I just tested it and it is indeed as you said. My information is stuck in the January code when I was using ByConity that the default database was `Atomic`.
Anyway this change is very good.
