### ISSUE TITLE
avaliable inodes: 0.00

### ISSUE THREAD

**Issue by skyoct** [ByConity/ByConity#848]
### Briefly describe the bug
ERROR: 
```
Total space: 540.30 GiB
Available space: 224.95 GiB
Total inodes: 36.04 million
Available inodes: 0.00
Mount point: /var/byconity
Cannot print extra info: Code: 425, e.displayText() = DB::Exception: Cannot open /etc/mtab to get name of filesystem SQLSTATE: 58000 (version 21.8.7.1) (version 21.8.7.1)
2023.11.03 10:12:25.269390 [ 95663 ] {} <Debug> executeManipulationTask: Finished manipulate 445376769604714496
2023.11.03 10:12:26.176884 [ 79 ] {} <Debug> StoragePolicy::getDiskByName: Storage disk name: server_s3_disk01 loaded
2023.11.03 10:12:26.188923 [ 79 ] {} <Debug> StoragePolicy::getDiskByName: Storage disk name: server_s3_disk01 loaded
2023.11.03 10:12:26.190646 [ 79 ] {} <Debug> CnchWorkerService: Received manipulation from [::ffff:10.80.88.74]:8124 :ManipulationTask {445376769418592256}, type Merge, ods.app_10001_rec_default (bf9dac3f-f9ff-42aa-befa-dacdf3de2592):  source_parts: { 20231103_445367142576029696_445376130235498496_61_445376564841414656, 20231103_445376133420285952_445376170760601600_1_445376636684599296 } new_part_names: { 20231103_445367142576029696_445376170760601600_62_445376769418592256 } columns_commit_time: 445285748237664256
2023.11.03 10:12:26.200134 [ 1380 ] {} <Debug> ThreadPool: clear thread for finalize : [1224, 1368, ]
2023.11.03 10:12:26.200854 [ 1380 ] {} <Debug> ods.app_10001_rec_default (bf9dac3f-f9ff-42aa-befa-dacdf3de2592): Loaded data parts (2 items)
2023.11.03 10:12:26.200910 [ 1380 ] {} <Debug> DiskLocal: Reserving 2.88 GiB on disk `default`, having unreserved 224.95 GiB.
2023.11.03 10:12:26.202119 [ 1380 ] {} <Error> void DB::ManipulationTask::execute(): std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in create_directory: No space left on device [/var/byconity/auxility_store//tmp_merge_445376769418592256-20231103_445367142576029696_445376170760601600_62_445376769418592256], Stack trace (when copying this message, always include the lines below):

0. std::runtime_error::runtime_error(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1e103130 in ?
1. std::__1::system_error::system_error(std::__1::error_code, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x1e10bd17 in ?
2. ? @ 0x17bb02a3 in /opt/byconity/bin/clickhouse
3. ? @ 0x1e0b1795 in ?
4. ? @ 0x1e0b4b69 in ?
5. std::__1::__fs::filesystem::__create_directory(std::__1::__fs::filesystem::path const&, std::__1::error_code*) @ 0x1e0b5368 in ?
6. std::__1::__fs::filesystem::__create_directories(std::__1::__fs::filesystem::path const&, std::__1::error_code*) @ 0x1e0b5170 in ?
7. DB::DiskLocal::createDirectories(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x17ba9ff5 in /opt/byconity/bin/clickhouse
8. DB::MergeTreeDataMerger::prepareNewParts(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > > const&, DB::IMergeTreeDataPart const*, DB::NamesAndTypesList const&) @ 0x1758bfcd in /opt/byconity/bin/clickhouse
9. DB::MergeTreeDataMerger::mergePartsToTemporaryPartImpl(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::MergeTreeMetaBase::MergingParams const&, DB::ManipulationListElement*, DB::IMergeTreeDataPart const*) @ 0x1758d20e in /opt/byconity/bin/clickhouse
10. DB::MergeTreeDataMerger::mergePartsToTemporaryPart() @ 0x17594a7f in /opt/byconity/bin/clickhouse
11. DB::CloudMergeTreeMergeTask::executeImpl() @ 0x175855cc in /opt/byconity/bin/clickhouse
12. DB::ManipulationTask::execute() @ 0x1758846f in /opt/byconity/bin/clickhouse
13. DB::executeManipulationTask(std::__1::shared_ptr<DB::ManipulationTask>, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart> > >) @ 0x175885e4 in /opt/byconity/bin/clickhouse
14. ? @ 0x1756d5a6 in /opt/byconity/bin/clickhouse
15. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xd2ed23f in /opt/byconity/bin/clickhouse
16. ? @ 0xd2f151a in /opt/byconity/bin/clickhouse
17. start_thread @ 0x7fa3 in /lib/x86_64-linux-gnu/libpthread-2.28.so
18. clone @ 0xf906f in /lib/x86_64-linux-gnu/libc-2.28.so
```
### The result you expected
Are there policy parameters related to configuring inodes?

**Comment by dmthuc** [comment]
Hi @skyoct , thank you for reporting the issue. Currently we have an issue that the temporary file is not clean up. We will fix it in future. Can you go to the path `/var/byconity/auxility_store/`. And delete the file with create time longer than 1 day?

**Comment by skyoct** [comment]
Hi @dmthuc Thanks for your reply, i deleted the PVC and restarted the pod, it worked fine.

**Comment by skyoct** [comment]
@dmthuc Hi @dmthuc When is it expected to fix this problem? It may have to delete disks twice a day during peak business hours.

**Comment by skyoct** [comment]
@dmthuc Hi, May I ask if it is possible to clear temporary files that exceed 2 hours. Deleting PVC multiple times a day is too frequent.

**Comment by dmthuc** [comment]
Hi @skyoct , yeah, it is ok

**Comment by skyoct** [comment]
Provide a temporary workaround.
chart->byconity->templates->vw-configmap.yaml  add this
![image](https://github.com/ByConity/ByConity/assets/24541857/fe83c2fd-e72d-46b2-baa5-e7c29d9e6857)

```
    echo "10 * * * * find /var/byconity/auxility_store -name 'tmp_merge*' -type d -mmin +120 -exec rm -r {} \;" | crontab -
```

**Comment by skyoct** [comment]
@dmthuc Hi, may I ask if this issue has been resolved in the code? I can help test it if needed.

**Comment by dmthuc** [comment]
> @dmthuc Hi, may I ask if this issue has been resolved in the code? I can help test it if needed.

Hi @skyoct , yeah, it has been fixed

**Comment by dogauzuncukoglu** [comment]
We still run into this issue from time to time. For reference our write worker settings are like this

```yaml
configOverwrite:
        logger:
          level: trace
        disk_cache_strategies:
          simple:
            lru_max_size: 150000000000 # 150Gi
        mark_cache_size: 10000000000 # 10 Gi
```

```yaml
storage:
        localDisk:
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 200Gi
            storageClassName: default
```

And we run into this issue like this
<img width="236" alt="Screenshot 2023-12-29 at 14 38 23" src="https://github.com/ByConity/ByConity/assets/100557431/e47d88a0-ad66-404e-9ef1-e2af373d3134">

We are using version: 0.3.0

@dmthuc should we increase the size because there are other components that use it? Is there a safe limit?

**Comment by dmthuc** [comment]
Hi dogauzuncukoglu , thank you very for report the issue. Do you know which folder consume all the inodes? Hi @zeromem , the issue seems haven't been fixed

**Comment by skyoct** [comment]
@dogauzuncukoglu @dmthuc  From my side, everything seems to be normal. It has been running for several days and has successfully merged tens of terabytes of data (total 15 nodes).

![image](https://github.com/ByConity/ByConity/assets/24541857/e2ce8143-9e5c-4d75-85b1-1f462d44f058)

**Comment by dogauzuncukoglu** [comment]
Hello everyone and sorry for the late reply. Sadly we deleted the pvc so I cannot gather more information when issue happened. I'll be monitoring the write workers and notify again. Currrently it seems that %76 of total inodes are in use.
<img width="748" alt="Screenshot 2024-01-03 at 00 12 19" src="https://github.com/ByConity/ByConity/assets/100557431/cbafa5d7-34e5-4937-b9d2-17650f7a80e4">

I tried running: `du -h --inodes /var/byconity --max-depth=1` but it seems to run forever due to high number of files it seems. Checking manually I see a lot of files under `data/part_disk_cache/meta`
<img width="427" alt="Screenshot 2024-01-03 at 00 21 49" src="https://github.com/ByConity/ByConity/assets/100557431/031529df-c37c-4628-95d8-984bb18daea8">

**Comment by dogauzuncukoglu** [comment]
I see this error logged ~1k times in the last 24h, I do not know whether it is relevant.

```
2024.01.02 21:24:09.784096 [ 3030189 ] {} TransactionCleaner: auto DB::TransactionCleaner::scheduleTask((lambda at ../src/Transaction/TransactionCleaner.cpp:103:18) &&, DB::CleanTaskPriority, DB::TxnTimestamp, DB::Protos::TransactionStatus &&)::(anonymous class)::operator()() const: Code: 49, e.displayText() = DB::Exception: the metadata size in kv is not matched with the record size in undo buffer SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below): 0. Poco::Exception::Exception(std::__1::basic_string, std::__1::allocator > const&, int) @ 0x1f837c12 in /opt/byconity/bin/clickhouse 1. DB::Exception::Exception(std::__1::basic_string, std::__1::allocator > const&, int, bool) @ 0xdbc33a0 in /opt/byconity/bin/clickhouse 2. void std::__1::__function::__policy_invoker::__call_impl(DB::TransactionCleaner::cleanCommittedTxn(DB::TransactionRecord const&)::$_1&&, DB::CleanTaskPriority, DB::TxnTimestamp, DB::Protos::TransactionStatus&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x18c3c244 in /opt/byconity/bin/clickhouse 3. ThreadPoolImpl::worker(std::__1::__list_iterator) @ 0xdc06b9e in /opt/byconity/bin/clickhouse 4. ThreadFromGlobalPool::ThreadFromGlobalPool::scheduleImpl(std::__1::function, int, std::__1::optional)::'lambda0'()>(bool&&, bool ThreadPoolImpl::scheduleImpl(std::__1::function, int, std::__1::optional)::'lambda0'()&&...)::'lambda'()::operator()() @ 0xdc09428 in /opt/byconity/bin/clickhouse 5. ThreadPoolImpl::worker(std::__1::__list_iterator) @ 0xdc0377f in /opt/byconity/bin/clickhouse 6. void* std::__1::__thread_proxy >, void ThreadPoolImpl::scheduleImpl(std::__1::function, int, std::__1::optional)::'lambda0'()> >(void*) @ 0xdc07a5a in /opt/byconity/bin/clickhouse 7. start_thread @ 0x7ea7 in /lib/x86_64-linux-gnu/libpthread-2.31.so 8. clone @ 0xfca2f in /lib/x86_64-linux-gnu/libc-2.31.so (version 21.8.7.1)
```

**Comment by dmthuc** [comment]
> I see this error logged ~1k times in the last 24h, I do not know whether it is relevant.
> 
> ```
> 2024.01.02 21:24:09.784096 [ 3030189 ] {} <Error> TransactionCleaner: auto DB::TransactionCleaner::scheduleTask((lambda at ../src/Transaction/TransactionCleaner.cpp:103:18) &&, DB::CleanTaskPriority, DB::TxnTimestamp, DB::Protos::TransactionStatus &&)::(anonymous class)::operator()() const: Code: 49, e.displayText() = DB::Exception: the metadata size in kv is not matched with the record size in undo buffer SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):
> 0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1f837c12 in /opt/byconity/bin/clickhouse
> 1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xdbc33a0 in /opt/byconity/bin/clickhouse
> 2. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<void DB::TransactionCleaner::scheduleTask<DB::TransactionCleaner::cleanCommittedTxn(DB::TransactionRecord const&)::$_1, DB::Protos::TransactionStatus>(DB::TransactionCleaner::cleanCommittedTxn(DB::TransactionRecord const&)::$_1&&, DB::CleanTaskPriority, DB::TxnTimestamp, DB::Protos::TransactionStatus&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x18c3c244 in /opt/byconity/bin/clickhouse
> 3. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xdc06b9e in /opt/byconity/bin/clickhouse
> 4. ThreadFromGlobalPool::ThreadFromGlobalPool<bool ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<bool>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(bool&&, bool ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<bool>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0xdc09428 in /opt/byconity/bin/clickhouse
> 5. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xdc0377f in /opt/byconity/bin/clickhouse
> 6. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0xdc07a5a in /opt/byconity/bin/clickhouse
> 7. start_thread @ 0x7ea7 in /lib/x86_64-linux-gnu/libpthread-2.31.so
> 8. clone @ 0xfca2f in /lib/x86_64-linux-gnu/libc-2.31.so
>  (version 21.8.7.1)
> ```

Yeah, it seems to be a new bug, @hustnn please help to look at this

**Comment by dogauzuncukoglu** [comment]
thanks @dmthuc , I am monitoring the write worker and it seems that `part_disk_cache` keeps getting larger in terms of file count.

<img width="473" alt="Screenshot 2024-01-04 at 10 38 52" src="https://github.com/ByConity/ByConity/assets/100557431/7d69490c-0b35-4e3e-89d7-0abe82ae1659">

<img width="753" alt="Screenshot 2024-01-04 at 10 43 25" src="https://github.com/ByConity/ByConity/assets/100557431/a0fe5d72-f340-4bce-8d54-25368a96f8cb">

**Comment by foreverneverer** [comment]
@dogauzuncukoglu do you mean the cache size still keep increase though  the `lru_max_size = 150GB`? you can see the log with prefix ”Creating DiskCache of“ and make sure the actually config value

**Comment by dogauzuncukoglu** [comment]
not exactly cache size, but inode usage keeps increasing. It hits the inode limit before hitting the size limit due to number of files under `part_disk_cache`

**Comment by foreverneverer** [comment]
`inode` has config: lru_max_object_num. 
now the default value is  `std::numeric_limits<size_t>::max()` @dogauzuncukoglu.

**Comment by dogauzuncukoglu** [comment]
> `inode` has config: lru_max_object_num. now the default value is `std::numeric_limits<size_t>::max()` @dogauzuncukoglu.

Oh I didn't see that thanks @foreverneverer , that is most likely the issue. I will set a reasonable limit and check again thank you very much!

**Comment by dogauzuncukoglu** [comment]
I can confirm this no longer happens for us as well after adding ` lru_max_object_num`.

**Comment by xiongbl526** [comment]
> `inode` has config: lru_max_object_num. now the default value is `std::numeric_limits<size_t>::max()` @dogauzuncukoglu.

hello  Which configuration file should the lru_max_object_num parameter be added to, and what is a suitable value to set?
