### ISSUE TITLE
cnch_auxility_policy clarification

### ISSUE THREAD

**Issue by ozcelgozde** [ByConity/ByConity#854]
## Question
Looking at the cluster configuration documentation, I see a reference to:
cnch_auxility_policy, specifies the StoragePolicy used by ByConity to store temporary data on the local disk, optional configuration item, the default is default
What constitutes as temporary data here? Is it read/write agnostic or specific to certain functions?  Can you give us an example usage of this setting?

**Comment by vivek-debug** [comment]
@Michael-LinYu Can I get your help to answer this question?

**Comment by Michael-LinYu** [comment]
check StorageLocation. Table's data are divide into two category, one is main storage, which stores actual table data, other one is auxility storage, which used to store some temporary data. For example, cnch use hdfs/s3 as main storage to store table data, and use auxility storage to write temporary data or cache files
