### ISSUE TITLE
merge puts a lot of pressure on s3 storage

### ISSUE THREAD

**Issue by skyoct** [ByConity/ByConity#859]
## Question
Write 1.3T of data every day, with high combined usage of QPS and bandwidth.
After disabling the merge, the bandwidth and QPS (Queries Per Second) decreased by 80%.
May I ask if there is a way to reduce bandwidth and QPS?

Bucket table number: 16
Write Work: 8 * 10C 16G
Write batch size: 13w 

![image](https://github.com/ByConity/ByConity/assets/24541857/1a4bf475-fecd-4d5d-9f74-6d0407309ab2)
![image](https://github.com/ByConity/ByConity/assets/24541857/aeee5111-50f6-4274-bbfe-38f6f61d79ea)

**Comment by lazywei** [comment]
Have you tried utilizing local disk as cache (like increase the size of cache limit?) for write workers?

**Comment by skyoct** [comment]
Hi @lazywei  Our cluster is deployed using k8s, with local disk PVC mounted. Are there any additional configurations available？

**Comment by lazywei** [comment]
This is the setting I'm referring to -- the local cache's size https://github.com/ByConity/byconity-deploy/blob/master/examples/k8s/values.yaml#L205-L226

**Comment by skyoct** [comment]
@lazywei This is already configured

**Comment by skyoct** [comment]
Caused by opening parameters `enable_preload_parts`.
