### ISSUE TITLE
Explain Pipeline failed and catch DB::Exception "Table xx.xx doesn't exist  SQLSTATE: 42P01"

### ISSUE THREAD

**Issue by zhaojintaozhao** [ByConity/ByConity#862]
## Bug Report
Explain Pipeline failed and catch DB::Exception "Table xx.xx_44561... doesn't exist SQLSTATE: 42P01."

### Briefly describe the bug
Hi, All.
There are three servers and two default-workers in my ByConity cluster. 
I create a CnchMergeTree table and insert some values.
The explain sql query shows the Query Plan, and it can return the currect result.
But the explain pipepline sql query failed and catch DB::Exception "Table xx.xx_44561... doesn't exist SQLSTATE: 42P01."

#### Step1:  create tabe.
```
CREATE TABLE test.t1
(`id` UInt32,
`pt_d` Date DEFAULT today()) 
ENGINE = CnchMergeTree()
PARTITION BY pt_d
Order by id
```
#### Step2: insert values
```
insert into test.t1 select (rand() % 1000), today() from numbers(50);
```
#### Step3: query explain sql
```
 explain select count(id), pt_d from test.t1 group by pt_d;
```
it returns the right result. 

#### Step4: query explain pipeline sql
```
explain pipeline  select count(id), pt_d from test.t1 group by pt_d;
```

It execute failed and the error message is: 
```
DB::Exception: Table test.t1_4456... doesn't exist SQLSTATE: 42P01.
```

### Version
0.2.0

Does any one face the same problem?

**Comment by vivek-debug** [comment]
@zhaojintaozhao I tried this set of queries on the latest version of ByConity and it executes successfully. I recommend updating your version to the latest version and giving it a try.

**Comment by xiaomo728** [comment]
> @zhaojintaozhao I tried this set of queries on the latest version of ByConity and it executes successfully. I recommend updating your version to the latest version and giving it a try.

The latest version -- it means 0.2.2?

**Comment by vivek-debug** [comment]
> @vivek-debug The latest version -- it means 0.2.2?
yes
