### ISSUE TITLE
“distributed_group_by_no_merge” is also effective in ByConity BucketMergeTree?

### ISSUE THREAD

**Issue by zhaojintaozhao** [ByConity/ByConity#863]
“distributed_group_by_no_merge” is also effective in ByConity BucketMergeTree?

## Question
Hi All.
ClickHouse support  the "distributed_group_by_no_merge" setting to support data sharding scenario
We can find the description from https://clickhouse.com/docs/en/operations/settings/settings.
```
Do not merge aggregation states from different servers for distributed query processing, you can use this in case it is for certain that there are different keys on different shards

Possible values:

0 — Disabled (final query processing is done on the initiator node).
1 - Do not merge aggregation states from different servers for distributed query processing (query completely processed on the shard, initiator only proxy the data), can be used in case it is for certain that there are different keys on different shards.
2 - Same as 1 but applies ORDER BY and LIMIT (it is not possible when the query processed completely on the remote node, like for distributed_group_by_no_merge=1) on the initiator (can be used for queries with ORDER BY and/or LIMIT).
Default value: 0
```

This setting is also effective in ByConity BucketMergeTree? We can use this setting in BucketMergeTree ?

**Comment by vivek-debug** [comment]
> This setting is also effective in ByConity BucketMergeTree? We can use this setting in BucketMergeTree ?

Yes this is also effective when used with bucket table. Usually we suggest using `distributed_perfect_shard`, since it could cover more agg functions than `distributed_group_by_no_merge`.

**Comment by kevinthfang** [comment]
@ zhaojintaozhao  Any more questions?
