### ISSUE TITLE
What is the difference between vw and wg?

### ISSUE THREAD

**Issue by mo-avatar** [ByConity/ByConity#88]
At first, I thought vw is something like a  virtual cluster contains server, tso, dm, rm, and a set of writer worker(wg), read worker(wg).

But after read  some material from internet, ie. https://www.zhihu.com/question/578084634. It seems indicates a set of  worker is a vw.

I am a bit confused.

**Comment by hustnn** [comment]
Hello,

vw is short for virtual warehouse and one vw can contain multiple worker groups (wg). It is more like replicas. By default, the vw only has 1 wg (replica), and for scaling purpose, one vw can be scaled to have multiple wgs.

**Comment by mo-avatar** [comment]
> Hello,
> 
> vw is short for virtual warehouse and one vw can contain multiple worker groups (wg). It is more like replicas. By default, the vw only has 1 wg (replica), and for scaling purpose, one vw can be scaled to have multiple wgs.

Thanks for answering, so can one vw contains both read wgs and write wgs, or an vw can only contains read wgs or write wgs

**Comment by hustnn** [comment]
one vw and even one wg can be used for both read and write. The best practice is separate the read and write, in this case, you need 2 vws. One for read and one for write, the wg under the vw can only be used for one purpose.

**Comment by mo-avatar** [comment]
> one vw and even one wg can be used for both read and write. The best practice is separate the read and write, in this case, you need 2 vws. One for read and one for write, the wg under the vw can only be used for one purpose.
> 
> In short, the answer is later one.
I see, thanks!
