### ISSUE TITLE
GlobalGCThread stuck at removing trash table

### ISSUE THREAD

**Issue by lazywei** [ByConity/ByConity#904]
### Briefly describe the bug

We're seeing a lot of such logs repeatedly on the Daemon Manager
```
2023.11.29 16:25:52.598345 [ 526873 ] {} <Trace> GlobalGCThread: Trash table: database ed_mt , name ed_metric_bad3423e-2eff-43ca-9863-b5fdf49f7df0_agg_5m_mv , uuid 80145e8d-8fb3-4a0b-b88c-e56902a34274
2023.11.29 16:25:52.601524 [ 526873 ] {} <Trace> GlobalGCThread: Trash table: database ed_mt , name ed_metric_bad3423e-2eff-43ca-9863-b5fdf49f7df0_agg_5m , uuid 2297e11d-b0df-425f-9d45-c7d66414c7c0
2023.11.29 16:25:52.605967 [ 526873 ] {} <Trace> GlobalGCThread: Trash table: database ed_mt , name ed_metric_bad3423e-2eff-43ca-9863-b5fdf49f7df0 , uuid 6374bd96-e507-4921-b4b6-ea1f252c9427
// .... more of such logs ...
2023.11.29 16:25:52.841795 [ 526873 ] {} <Trace> GlobalGCThread: Trash table: database ed_mt , name ed_metric_f984111d-ddd0-479e-b7a8-89dc5bcc0ffb_agg_5m , uuid 06a33436-5c54-4a7f-bb12-82669e706230
2023.11.29 16:25:52.845916 [ 526873 ] {} <Trace> GlobalGCThread: Trash table: database ed_mt , name ed_metric_f984111d-ddd0-479e-b7a8-89dc5bcc0ffb , uuid dbbb06c6-2959-4f2d-a078-7c418035b783
2023.11.29 16:25:52.849867 [ 526873 ] {} <Debug> GlobalGCThread: send 3 table to server for GC, they are
2023.11.29 16:25:52.849890 [ 526873 ] {} <Debug> GlobalGCThread: table 1 : ed_445864008924004365.ed_logs_old
2023.11.29 16:25:52.849893 [ 526873 ] {} <Debug> GlobalGCThread: table 2 : ed_445864008924004365.ed_logs
2023.11.29 16:25:52.849895 [ 526873 ] {} <Debug> GlobalGCThread: table 3 : ed_445864008924004365.test_table
2023.11.29 16:25:52.851765 [ 526873 ] {} <Information> GlobalGCThread: Finish executeImpl in global GC
```

But it doesn't seem to make any progress. It always start with these 3 tables
```
2023.11.29 16:25:52.849890 [ 526873 ] {} <Debug> GlobalGCThread: table 1 : ed_445864008924004365.ed_logs_old
2023.11.29 16:25:52.849893 [ 526873 ] {} <Debug> GlobalGCThread: table 2 : ed_445864008924004365.ed_logs
2023.11.29 16:25:52.849895 [ 526873 ] {} <Debug> GlobalGCThread: table 3 : ed_445864008924004365.test_table
```

And these 3 are never cleaned up or GC because it would show up again in the same logs.

### The result you expected

GlobalGCThread should finish all the trash tables GC.

**Comment by dmthuc** [comment]
The log for clean up trash table in like this `https://github.com/ByConity/ByConity/blob/master/src/MergeTreeCommon/GlobalGCManager.cpp#L194`. By following this log, we should able to find the error that cause GlobalGC failed to clean up table

**Comment by lazywei** [comment]
It seems we're not able to do it because there is no free threads

```
2023.11.30 16:28:27.043349 [ 1274 ] {} <Error> GlobalGCManager: Failed to remove meta data for table ed_445864008924004365.ed_logs_old (66b78bbe-20ff-402e-8c30-9fa58ae300a7)
2023.11.30 16:28:27.043350 [ 154 ] {} <Trace> ed_mt.`ed_metric_0113b806-3771-488c-ba2f-b1d4c73d40e3_agg_5m` (0e6218f5-a4f2-42ea-b8ce-7276c535a0d4)(PartGCThread): Candidate partitions: 
2023.11.30 16:28:27.043378 [ 154 ] {} <Trace> PartitionSelector: ed_mt.`ed_metric_0113b806-3771-488c-ba2f-b1d4c73d40e3_agg_5m` (0e6218f5-a4f2-42ea-b8ce-7276c535a0d4) GCThread: estimators size - 1
2023.11.30 16:28:27.043391 [ 154 ] {} <Trace> PartitionSelector: ed_mt.`ed_metric_0113b806-3771-488c-ba2f-b1d4c73d40e3_agg_5m` (0e6218f5-a4f2-42ea-b8ce-7276c535a0d4) GCThread: do round-robin as candidates is empty.
2023.11.30 16:28:27.043397 [ 1274 ] {} <Error> GlobalGCManager: Code: 439, e.displayText() = DB::Exception: Cannot schedule a task: no free thread (timeout=0) (threads=4, jobs=4) SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1e268692 in /opt/byconity/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xd4c9800 in /opt/byconity/bin/clickhouse
2. DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long&>(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long&&, unsigned long&) @ 0xd50dcd2 in /opt/byconity/bin/clickhouse
3. void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda'(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0xd50e73e in /opt/byconity/bin/clickhouse
4. void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>) @ 0xd50a26b in /opt/byconity/bin/clickhouse
5. ThreadPoolImpl<ThreadFromGlobalPool>::scheduleOrThrow(std::__1::function<void ()>, int, unsigned long) @ 0xd50b986 in /opt/byconity/bin/clickhouse
6. DB::GlobalGCHelpers::executeGlobalGC(DB::Protos::DataModelTable const&, DB::Context const&, Poco::Logger*) @ 0x178a99b7 in /opt/byconity/bin/clickhouse
7. DB::GlobalGCManager::GlobalGCTask::operator()() @ 0x178aca67 in /opt/byconity/bin/clickhouse
8. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xd50cebe in /opt/byconity/bin/clickhouse
9. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0xd50ed08 in /opt/byconity/bin/clickhouse
10. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xd509a9f in /opt/byconity/bin/clickhouse
11. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0xd50dd7a in /opt/byconity/bin/clickhouse
12. start_thread @ 0x7ea7 in /lib/x86_64-linux-gnu/libpthread-2.31.so
13. clone @ 0xfca2f in /lib/x86_64-linux-gnu/libc-2.31.so
 (version 21.8.7.1)
2023.11.30 16:28:27.043400 [ 154 ] {} <Trace> Context::getCnchTSOClient: TSO Leader host-port is: 10.64.252.80:9000
2023.11.30 16:28:27.043415 [ 202 ] {} <Trace> Context::getCnchTSOClient: TSO Leader host-port is: 10.64.252.80:9000  
2023.11.30 16:28:27.043428 [ 1274 ] {} <Information> GlobalGCManager: Table: ed_445864008924004365.ed_logs (656536d5-33b6-417f-a6c1-515ee5e5fed1) is deleted, will execute GlobalGC for it
```

**Comment by dmthuc** [comment]
> It seems we're not able to do it because there is no free threads
> 
> ```
> 2023.11.30 16:28:27.043349 [ 1274 ] {} <Error> GlobalGCManager: Failed to remove meta data for table ed_445864008924004365.ed_logs_old (66b78bbe-20ff-402e-8c30-9fa58ae300a7)
> 2023.11.30 16:28:27.043350 [ 154 ] {} <Trace> ed_mt.`ed_metric_0113b806-3771-488c-ba2f-b1d4c73d40e3_agg_5m` (0e6218f5-a4f2-42ea-b8ce-7276c535a0d4)(PartGCThread): Candidate partitions: 
> 2023.11.30 16:28:27.043378 [ 154 ] {} <Trace> PartitionSelector: ed_mt.`ed_metric_0113b806-3771-488c-ba2f-b1d4c73d40e3_agg_5m` (0e6218f5-a4f2-42ea-b8ce-7276c535a0d4) GCThread: estimators size - 1
> 2023.11.30 16:28:27.043391 [ 154 ] {} <Trace> PartitionSelector: ed_mt.`ed_metric_0113b806-3771-488c-ba2f-b1d4c73d40e3_agg_5m` (0e6218f5-a4f2-42ea-b8ce-7276c535a0d4) GCThread: do round-robin as candidates is empty.
> 2023.11.30 16:28:27.043397 [ 1274 ] {} <Error> GlobalGCManager: Code: 439, e.displayText() = DB::Exception: Cannot schedule a task: no free thread (timeout=0) (threads=4, jobs=4) SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):
> 
> 0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1e268692 in /opt/byconity/bin/clickhouse
> 1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xd4c9800 in /opt/byconity/bin/clickhouse
> 2. DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long&>(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long&&, unsigned long&) @ 0xd50dcd2 in /opt/byconity/bin/clickhouse
> 3. void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda'(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0xd50e73e in /opt/byconity/bin/clickhouse
> 4. void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>) @ 0xd50a26b in /opt/byconity/bin/clickhouse
> 5. ThreadPoolImpl<ThreadFromGlobalPool>::scheduleOrThrow(std::__1::function<void ()>, int, unsigned long) @ 0xd50b986 in /opt/byconity/bin/clickhouse
> 6. DB::GlobalGCHelpers::executeGlobalGC(DB::Protos::DataModelTable const&, DB::Context const&, Poco::Logger*) @ 0x178a99b7 in /opt/byconity/bin/clickhouse
> 7. DB::GlobalGCManager::GlobalGCTask::operator()() @ 0x178aca67 in /opt/byconity/bin/clickhouse
> 8. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xd50cebe in /opt/byconity/bin/clickhouse
> 9. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0xd50ed08 in /opt/byconity/bin/clickhouse
> 10. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xd509a9f in /opt/byconity/bin/clickhouse
> 11. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0xd50dd7a in /opt/byconity/bin/clickhouse
> 12. start_thread @ 0x7ea7 in /lib/x86_64-linux-gnu/libpthread-2.31.so
> 13. clone @ 0xfca2f in /lib/x86_64-linux-gnu/libc-2.31.so
>  (version 21.8.7.1)
> 2023.11.30 16:28:27.043400 [ 154 ] {} <Trace> Context::getCnchTSOClient: TSO Leader host-port is: 10.64.252.80:9000
> 2023.11.30 16:28:27.043415 [ 202 ] {} <Trace> Context::getCnchTSOClient: TSO Leader host-port is: 10.64.252.80:9000  
> 2023.11.30 16:28:27.043428 [ 1274 ] {} <Information> GlobalGCManager: Table: ed_445864008924004365.ed_logs (656536d5-33b6-417f-a6c1-515ee5e5fed1) is deleted, will execute GlobalGC for it
> ```

Hi it error look weird, I wonder if you see any other error in Global GC. Can you send a bit more log? And do you have any config in the server for global GC?

**Comment by dmthuc** [comment]
This error is highly because of the same hang issue happen recently.

**Comment by dmthuc** [comment]
The fix has been merged. Please let me know if you still encounter this

**Comment by lazywei** [comment]
Testing with the fix it seems the issue is gone. Thank you!

**Comment by skyoct** [comment]
@dmthuc Hi, Will this cause the files in S3 to be unable to be deleted?

**Comment by dmthuc** [comment]
> @dmthuc Hi, Will this cause the files in S3 to be unable to be deleted?

yeah
