### ISSUE TITLE
Lots of S3 Parts that are empty 

### ISSUE THREAD

**Issue by ozcelgozde** [ByConity/ByConity#907]
## Question
We have a test cluster with 5 tables & we do fairly ok batch inserts to that cluster. But when I look at the s3 side i see lots of almost empty parts created like this (notice 635 B ones): 
<img width="1312" alt="Screenshot 2023-11-30 at 16 39 57" src="https://github.com/ByConity/ByConity/assets/90635824/57e80c22-60ec-4a50-be15-cb841262b529">

They only contain CNCH header and 0 columns knowledge. Is there anywhere to check whats happening?

**Comment by GallifreyY** [comment]
hi @gaodayue, can help take a look at this issue?

**Comment by gaodayue** [comment]
@ozcelgozde I think the first step is to find out which table and part does the folder (uuid) belong to. We recently add a [part_id](https://github.com/ByConity/ByConity/blob/master/src/Storages/System/StorageSystemCnchParts.cpp#L75) field to `system.cnch_parts`, so that you can check that using `select * from system.cnch_parts where part_id = 'xx-xx-xx' settings enable_multiple_tables_for_cnch_parts = 1 format Vertical`. If that field is missing, you can check that by grepping the uuid in server or worker logs

**Comment by gaodayue** [comment]
and ByConity will create empty part as tombstone (DropRange/DropPart) during part merge, those parts will be periodically garbage collected by the background gc thread. So it's ok as long as the number of empty parts is not particularly large or keeps growing.

You can check the number of empty parts using `select concat(database, '.', table) as t, part_type, count() c from system.cnch_tables where rows_count = 0 group by t, part_type order by t, part_type settings enable_multiple_tables_for_cnch_parts = 1`

**Comment by dogauzuncukoglu** [comment]
Hi @gaodayue , the query you have shared results in an error
```
Code: 47, e.displayText() = DB::Exception: Missing columns: 'table' 'rows_count' 'part_type' while processing query: 'SELECT concat(database, '.', table) AS t, part_type, count() AS c FROM system.cnch_tables WHERE rows_count = 0 GROUP BY t, part_type ORDER BY t ASC, part_type ASC SETTINGS enable_multiple_tables_for_cnch_parts = 1', required columns: 'part_type' 'rows_count' 'database' 'table', source_columns: 'engine' 'split_number' 'cluster_key' 'sampling_key' 'primary_key' 'partition_key' 'is_detached' 'is_preallocated' 'modification_time' 'previous_version' 'definition' 'dependencies_table' 'current_version' 'with_range' 'sorting_key' 'database' 'vw_name' 'uuid' 'dependencies_database' 'txn_id' 'name', maybe you meant: ['database'] SQLSTATE: 42703 (version 21.8.7.1)
```

I see no `part_type` column in `system.cnch_tables`, I used `describe system.cnch_tables` to check.

Is there a way to check metadata health? I am asking because I see lot of files (around 100k) on s3 even though I drop all tables from the database. It seems that garbage collection stops after a while and does not issue delete requests.

I checked error logs and overwhelming majority looks like the line below. I do not know whether it is relevant.

```2023.12.13 19:48:30.654423 [ 880051 ] {} TransactionCleaner: auto DB::TransactionCleaner::scheduleTask((lambda at ../src/Transaction/TransactionCleaner.cpp:103:18) &&, DB::CleanTaskPriority, DB::TxnTimestamp, DB::Protos::TransactionStatus &&)::(anonymous class)::operator()() const: Code: 49, e.displayText() = DB::Exception: the metadata size in kv is not matched with the record size in undo buffer SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below): 0. Poco::Exception::Exception(std::__1::basic_string, std::__1::allocator > const&, int) @ 0x1f2578d2 in /opt/byconity/bin/clickhouse 1. DB::Exception::Exception(std::__1::basic_string, std::__1::allocator > const&, int, bool) @ 0xd9c4ca0 in /opt/byconity/bin/clickhouse 2. void std::__1::__function::__policy_invoker::__call_impl(DB::TransactionCleaner::cleanCommittedTxn(DB::TransactionRecord const&)::$_1&&, DB::CleanTaskPriority, DB::TxnTimestamp, DB::Protos::TransactionStatus&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x186a50e4 in /opt/byconity/bin/clickhouse 3. ThreadPoolImpl::worker(std::__1::__list_iterator) @ 0xda0827e in /opt/byconity/bin/clickhouse 4. ThreadFromGlobalPool::ThreadFromGlobalPool::scheduleImpl(std::__1::function, int, std::__1::optional)::'lambda0'()>(bool&&, bool ThreadPoolImpl::scheduleImpl(std::__1::function, int, std::__1::optional)::'lambda0'()&&...)::'lambda'()::operator()() @ 0xda0ab08 in /opt/byconity/bin/clickhouse 5. ThreadPoolImpl::worker(std::__1::__list_iterator) @ 0xda04e5f in /opt/byconity/bin/clickhouse 6. void* std::__1::__thread_proxy >, void ThreadPoolImpl::scheduleImpl(std::__1::function, int, std::__1::optional)::'lambda0'()> >(void*) @ 0xda0913a in /opt/byconity/bin/clickhouse 7. start_thread @ 0x7ea7 in /lib/x86_64-linux-gnu/libpthread-2.31.so 8. __clone @ 0xfca2f in /lib/x86_64-linux-gnu/libc-2.31.so (version 21.8.7.1)
```

Anyone has any suggestion where to look for more information?

**Comment by smmsmm1988** [comment]
hi, @dogauzuncukoglu. Not from system.cnch_tables, but from system.cnch_parts.

select concat(database, '.', table) as t, part_type, count() c from system.cnch_parts where rows_count = 0 group by t, part_type order by t, part_type settings enable_multiple_tables_for_cnch_parts = 1

**Comment by smmsmm1988** [comment]
> Hi @gaodayue , the query you have shared results in an error
> 
> ```
> Code: 47, e.displayText() = DB::Exception: Missing columns: 'table' 'rows_count' 'part_type' while processing query: 'SELECT concat(database, '.', table) AS t, part_type, count() AS c FROM system.cnch_tables WHERE rows_count = 0 GROUP BY t, part_type ORDER BY t ASC, part_type ASC SETTINGS enable_multiple_tables_for_cnch_parts = 1', required columns: 'part_type' 'rows_count' 'database' 'table', source_columns: 'engine' 'split_number' 'cluster_key' 'sampling_key' 'primary_key' 'partition_key' 'is_detached' 'is_preallocated' 'modification_time' 'previous_version' 'definition' 'dependencies_table' 'current_version' 'with_range' 'sorting_key' 'database' 'vw_name' 'uuid' 'dependencies_database' 'txn_id' 'name', maybe you meant: ['database'] SQLSTATE: 42703 (version 21.8.7.1)
> ```
> 
> I see no `part_type` column in `system.cnch_tables`, I used `describe system.cnch_tables` to check.
> 
> Is there a way to check metadata health? I am asking because I see lot of files (around 100k) on s3 even though I drop all tables from the database. It seems that garbage collection stops after a while and does not issue delete requests.
> 
> I checked error logs and overwhelming majority looks like the line below. I do not know whether it is relevant.
> 
> ```
> 2023.12.13 19:48:30.654423 [ 880051 ] {} TransactionCleaner: auto DB::TransactionCleaner::scheduleTask((lambda at ../src/Transaction/TransactionCleaner.cpp:103:18) &&, DB::CleanTaskPriority, DB::TxnTimestamp, DB::Protos::TransactionStatus &&)::(anonymous class)::operator()() const: Code: 49, e.displayText() = DB::Exception: the metadata size in kv is not matched with the record size in undo buffer SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below): 0. Poco::Exception::Exception(std::__1::basic_string, std::__1::allocator > const&, int) @ 0x1f2578d2 in /opt/byconity/bin/clickhouse 1. DB::Exception::Exception(std::__1::basic_string, std::__1::allocator > const&, int, bool) @ 0xd9c4ca0 in /opt/byconity/bin/clickhouse 2. void std::__1::__function::__policy_invoker::__call_impl(DB::TransactionCleaner::cleanCommittedTxn(DB::TransactionRecord const&)::$_1&&, DB::CleanTaskPriority, DB::TxnTimestamp, DB::Protos::TransactionStatus&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x186a50e4 in /opt/byconity/bin/clickhouse 3. ThreadPoolImpl::worker(std::__1::__list_iterator) @ 0xda0827e in /opt/byconity/bin/clickhouse 4. ThreadFromGlobalPool::ThreadFromGlobalPool::scheduleImpl(std::__1::function, int, std::__1::optional)::'lambda0'()>(bool&&, bool ThreadPoolImpl::scheduleImpl(std::__1::function, int, std::__1::optional)::'lambda0'()&&...)::'lambda'()::operator()() @ 0xda0ab08 in /opt/byconity/bin/clickhouse 5. ThreadPoolImpl::worker(std::__1::__list_iterator) @ 0xda04e5f in /opt/byconity/bin/clickhouse 6. void* std::__1::__thread_proxy >, void ThreadPoolImpl::scheduleImpl(std::__1::function, int, std::__1::optional)::'lambda0'()> >(void*) @ 0xda0913a in /opt/byconity/bin/clickhouse 7. start_thread @ 0x7ea7 in /lib/x86_64-linux-gnu/libpthread-2.31.so 8. __clone @ 0xfca2f in /lib/x86_64-linux-gnu/libc-2.31.so (version 21.8.7.1)
> ```
> 
> Anyone has any suggestion where to look for more information?

When dropping a table,  the engine will wait for 3 days to clean data in the shared storage
