### ISSUE TITLE
Parts Merge Failure If Set index_granularity_bytes When Create Table

### ISSUE THREAD

**Issue by wuwenw** [ByConity/ByConity#928]
In Byconity 0.2.2, if set index_granularity_bytes when create table, byconity fails to merge parts. Leave it with default value (0) can resolve this issue.

**Comment by tigerwangyb** [comment]
already block shein‘s testing

**Comment by zeromem** [comment]
> already block shein‘s testing

@tigerwangyb hi, I thought shein already know the root cause and remove adaptive_granularity from their table schema. in a word, adaptive_granularity is not well adapted in the current code. and it's a low priority thing to fix it for now. better to disable it from schema.

**Comment by kevinthfang** [comment]
MR in review, will release this week

**Comment by kevinthfang** [comment]
this have been fixed in https://github.com/ByConity/ByConity/commit/62a54eb915a2938481dfd93203bdb37ea2eabade
