### ISSUE TITLE
CI timeouts while droping table 

### ISSUE THREAD

**Issue by canhld94** [ByConity/ByConity#93]
## Describe the issue
CI often timeouts recently
https://github.com/ByConity/ByConity/actions/runs/4201676221/jobs/7288914944
https://github.com/ByConity/ByConity/actions/runs/4202651030/jobs/7291074011

**Comment by kevinthfang** [comment]
@vivek-debug Would you please take a look?

**Comment by vivek-debug** [comment]
Seems to be ok now. let's wait for more PRs and see if there any more issues

**Comment by Adora627** [comment]
@hustnn please add PR info

**Comment by hustnn** [comment]
Related to https://github.com/ByConity/ByConity/pull/119
