### ISSUE TITLE
Projections do not seem to work with byconity

### ISSUE THREAD

**Issue by iskendermert** [ByConity/ByConity#937]
## Question

I tried the projections by following [this](https://clickhouse.com/docs/en/sql-reference/statements/alter/projection#example-pre-aggregation-query) tutorial.
Followed the tutorial for a byconity and clickhouse cluster. Validation queries showed that projections were being utilized for clickhouse but not for byconity. Is there something that I am missing?

Exact queries that I used.

when creating for byconity change 
ENGINE = MergeTree() --->>> ENGINE = CnchMergeTree

```
CREATE DATABASE IF NOT EXISTS test

CREATE TABLE test.`visits`
(
   `user_id` UInt64,
   `user_name` String,
   `pages_visited` Nullable(Float64),
   `user_agent` String,
   PROJECTION projection_visits_by_user
   (
       SELECT
           user_agent,
           sum(pages_visited)
       GROUP BY user_id, user_agent
   )
)
ENGINE = MergeTree()
ORDER BY user_agent

```

```
INSERT INTO test.`visits` SELECT
    number,
    'test',
    1.5 * (number / 2),
    'Android'
FROM numbers(1, 100);
```

```
INSERT INTO test.`visits` SELECT
    number,
    'test',
    1. * (number / 2),
   'IOS'
FROM numbers(100, 500);
```

A query that is expected to use projections
```
SELECT
    user_agent,
    sum(pages_visited)
FROM test.`visits`
GROUP BY user_agent
```

Validation query
```
SELECT * FROM system.query_log 
WHERE type = 'QueryFinish' AND query_kind = 'Select' AND arrayExists(x -> x = 'test.visits', tables) = 1 
ORDER BY query_start_time_microseconds DESC
Limit 10
```
When executed on clickhouse cluster, validation query shows the projection being utilized in `projection`column. But on byconity cluster it returns empty.

**Comment by Clark0** [comment]
Hi, what's the version of byconity using now?

**Comment by Clark0** [comment]
Projection is not enabled by default, you can enable with settings
`SETTINGS allow_experimental_projection_optimization = 1, enable_optimizer=1, optimizer_projection_support=1`

Even though ByConity skipped writing the projection result to the query_log. You can check the log on vw default worker if the project is applied. 
https://github.com/ByConity/ByConity/blob/6254bfd3e91c9ddd5a764d4f9b621516e1db9651/src/QueryPlan/TableScanStep.cpp#L449

**Comment by iskendermert** [comment]
> Projection is not enabled by default, you can enable with settings `SETTINGS allow_experimental_projection_optimization = 1, enable_optimizer=1, optimizer_projection_support=1`
> 
> Even though ByConity skipped writing the projection result to the query_log. You can check the log on vw default worker if the project is applied.
> 
> https://github.com/ByConity/ByConity/blob/6254bfd3e91c9ddd5a764d4f9b621516e1db9651/src/QueryPlan/TableScanStep.cpp#L449

Thanks, I will try
