### ISSUE TITLE
Version 0.2.2 bug: ReadBufferFromS3::seek expects SEEK_SET as whence exception, cannot pass the UT `tests/queries/4_cnch_stateless/00926_adaptive_index_granularity_pk.sql`

### ISSUE THREAD

**Issue by xiaomo728** [ByConity/ByConity#966]
**ByConity Version: 0.2.2
Workers in cluster: 2 default worker + 2 write worker
UT location: https://github.com/ByConity/ByConity/blob/master/tests/queries/4_cnch_stateless/00926_adaptive_index_granularity_pk.sql
Optimizer: open**

**Got exception:**
Received exception from server (version 21.8.7):
Code: 36. DB::Exception: Received from xxx.xxx.xxx.xxx:pppp. DB::Exception: Received from xxx.xxx.xxx.xx:pppp. DB::Exception: ReadBufferFromS3::seek expects SEEK_SET as whence while reading clickhouse/bytes3/0f484b66-0ab2-43ce-a40a-03983065e0cf/data: While executing MergeTree SQLSTATE: 22000.

**Comment by Clark0** [comment]
That's because `ReadBufferFromS3` does not support `SEEK_CUR` mode of seek. We are fixing this issue and try add S3 env to the test CI.
