### ISSUE TITLE
materialize view table can not  directly forward insert request to write worker

### ISSUE THREAD

**Issue by blueskygzhz** [ByConity/ByConity#981]
2023.12.18 14:19:03.794760 [ 1932126 ] {daf0eebb-90d2-4600-a4d9-de5f0b72f91c} (446399864798445626) <Error> executeQuery: Code: 57, e.displayText() = DB::Exception: Table carms.carms_metrics_exception_transaction already exists. SQLSTATE: 42P07 (version 21.8.7.1) (from 172.26.86.128:46414) (in query: insert into carms.carms_trace_aggregation (aggregation_type, region_code, tenant_code, project_code,deployment,service_name, instance_id, transaction_name, timestamp_ms, span_type,target_type, target_subtype, target_subtype_info, net_host_addr, db_system,db_operation, db_statement, sql_type, if_vaild_statement, db_name,message_operation, message_destination, message_system, message_destination_kind,message_delay_cost,exception_type, exception_stacktrace_id,exception_stacktrace, exception_ids,agent_type,app_language,tag, target_project_code,target_deployment, target_service_name,target_instance_id, target_transaction_name,license_type, timestamp_hour_ms,span_report_timestamps,span_report_count,span_storage_count, total_count, total_cost, duration_max,duration_min,duration_values,duration_map,result_map,error_count, exception_count) VALUES), Stack trace (when copying this message, always include the lines below):

0. /home/carms/byconity_code/contrib/libcxx/include/exception:133: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1f02e712 in /usr/bin/clickhouse

1. /home/carms/byconity_code/src/Common/Exception.cpp:97: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x1295f8c0 in /usr/bin/clickhouse

2. /home/carms/byconity_code/src/CloudServices/CnchWorkerResource.cpp:0: DB::CnchWorkerResource::executeCreateQuery(std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) @ 0x18487d53 in /usr/bin/clickhouse

3. /home/carms/byconity_code/contrib/libcxx/include/memory:3211: DB::InterpreterInsertQuery::getTable(DB::ASTInsertQuery&) @ 0x190d6cca in /usr/bin/clickhouse

4. /home/carms/byconity_code/src/Interpreters/InterpreterInsertQuery.cpp:0: DB::InterpreterInsertQuery::execute() @ 0x190d8559 in /usr/bin/clickhouse

5. /home/carms/byconity_code/src/Interpreters/executeQuery.cpp:0: DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::IAST>, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*) @ 0x195811d8 in /usr/bin/clickhouse

6. /home/carms/byconity_code/src/Interpreters/executeQuery.cpp:1940: DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool) @ 0x1957dadb in /usr/bin/clickhouse

7. /home/carms/byconity_code/src/Server/TCPHandler.cpp:475: DB::TCPHandler::runImpl() @ 0x1a18825e in /usr/bin/clickhouse

8. /home/carms/byconity_code/src/Server/TCPHandler.cpp:2119: DB::TCPHandler::run() @ 0x1a19679c in /usr/bin/clickhouse

9. /home/carms/byconity_code/contrib/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x1efa2c4c in /usr/bin/clickhouse

10. /home/carms/byconity_code/contrib/libcxx/include/memory:1397: Poco::Net::TCPServerDispatcher::run() @ 0x1efa30e5 in /usr/bin/clickhouse

11. /home/carms/byconity_code/contrib/poco/Foundation/src/ThreadPool.cpp:213: Poco::PooledThread::run() @ 0x1f08f647 in /usr/bin/clickhouse

12. /home/carms/byconity_code/contrib/poco/Foundation/include/Poco/SharedPtr.h:156: Poco::ThreadImpl::runnableEntry(void*) @ 0x1f08ceec in /usr/bin/clickhouse

13. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so

14. __clone @ 0xfe96d in /usr/lib64/libc-2.17.so

**Comment by smmsmm1988** [comment]
this issue has been solved
