### ISSUE TITLE
memory tracker for merge mutate is not correct

### ISSUE THREAD

**Issue by blueskygzhz** [ByConity/ByConity#982]
pod memory cost is 32G, but memory tracker show 1T and never decrease

![image](https://github.com/ByConity/ByConity/assets/147569085/8b87bc34-89c4-45f3-95b6-7b51a8195f5e)

![image](https://github.com/ByConity/ByConity/assets/147569085/866af8bc-1602-4a7d-8665-bdf9aebba2d5)

**Comment by yuanzhubi** [comment]
Let me add lianwenlong to confirm it.

**Comment by blueskygzhz** [comment]
![img_v3_026v_bbd6397f-bd1b-4eba-8e75-4c5148409e9g](https://github.com/ByConity/ByConity/assets/147569085/8d90bcd1-0c5d-495f-83dc-b8c69659f4c5)
this metric

**Comment by yuanzhubi** [comment]
https://github.com/ClickHouse/ClickHouse/pull/10449 could we merge this PR, to remove the unused and incorrect metric?
![image](https://github.com/ByConity/ByConity/assets/25676580/5a695793-1488-4ba2-a3be-687d1350d895)
@qusijun

**Comment by kevinthfang** [comment]
We are merging this PR from ck community.

**Comment by kevinthfang** [comment]
We will merge this week.

**Comment by kevinthfang** [comment]
This merge is still on the way

**Comment by luffyhwl** [comment]
The PR from ck community has been merged. (https://github.com/ClickHouse/ClickHouse/pull/48787)
