### ISSUE TITLE
What's the minimum support OS of ByConity?

### ISSUE THREAD

**Issue by fky2015** [ByConity/ByConity#986]
## Question

Does ByConity have any commitments about minimum supported operating systems?

**Comment by dmthuc** [comment]
We have libc version dependency.

**Comment by fky2015** [comment]
From what I see in the release binary, currently ByConity only requires utmost GLIBC `2.4`.
```
--- /data00/fengkaiyu.hi/playground/231220/byconity-common-static-0.3.0/usr/bin                                                                                                                     with fengkaiyu.hi@n14-147-092 at  03:02:40 PM
❯ objdump -T clickhouse | grep -i glibc | sed 's/.*GLIBC_\([.0-9]*\).*/\1/g' | sort -Vu

000000001fce2e54 g    DF .text  0000000000000000  Base        musl_glibc_longjmp
2.2.5
2.3
2.3.2
2.3.3
2.3.4
2.4
```

So for GLIBC versions between 2.4 and 2.18, will we maintain compatibility?

**Comment by dmthuc** [comment]
Hi @fky2015 , we suppose to support glibc at some minimum version and onward because newer OS will have newer glibc version
