### ISSUE TITLE
How to increase the number of simultaneous merge tasks

### ISSUE THREAD

**Issue by skyoct** [ByConity/ByConity#998]
## Question
We have a table that receives approximately 7T of data per day. During peak business hours, the average number of parts written per second is 8. Here are some of our configuration parameters:
```
enable_addition_bg_task = 1
max_addition_bg_task_num = 2000
cnch_merge_enable_batch_select = 1
```
In the default settings, the number of merge tasks that each worker can handle simultaneously is calculated as thread_num * 1.5.  we have already increased this value.

During peak periods, if the number of threads to be merged is already 400+, and there are over 8000+ parts, how can we increase the number of merge threads even further?

According to this method(https://github.com/ByConity/ByConity/blob/6e3ddae5a4b2aaf5ddffd1d32aa2f45b14a81e21/src/CloudServices/CnchMergeMutateThread.cpp#L389C29-L389C36), if the scheduling is successful, it waits for 1 second before scheduling the next time. If there are too many parts, perhaps this frequency is not sufficient? And can we optimize the scheduling algorithm in this area?

**Comment by zeromem** [comment]
@skyoct sleep 1 second before next scheduling is ok, because it can generate many tasks (at most 1 thound tasks and push them to a task queue) in one round if `cnch_merge_enable_batch_select` is enabled. after this, it will submit `max_partition_for_multi_select` tasks every second. you can try to increase this parameter vlaue

**Comment by skyoct** [comment]
@zeromem Thank you very much. It is evident from the related code that this parameter is useful.
